### ISSUE TITLE
Question regarding Evo lang files

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#100]
At the moment, in "manager/includes/lang/" there are two Spanish lang files:
- spanish.inc.php
- spanish-utf8.inc.php

I have also found that in some plugs/modules/snippets there are one or the other or both.
I see no need for this as it isn't very consistent and is also adding extra files/weight to the overall package. 
(maybe this should be done for all langs as well as removing "-utf8" from file name, as I dont think it is necessary.)
Also I think some could be updated for the new branding, replacing Modx with Evo.

So my question is, can I just upload a .zip with all files, and info about remove or replace, or to I have to fork the project?

**Comment by fourroses666** [comment]
Translations should go by:
https://www.transifex.com/evolutioncms/evolution/dashboard/

I think one of these files is linking to the other.
Don't know about the consequences if one (utf8) is removed.

**Comment by risingisland** [comment]
Thanks Marc, will take a look now.

As for the utf8, some langs have it others dont, I think it is a remnant from long ago when iso-8859-1 was more in use.

**Comment by risingisland** [comment]
I think that as long as the file is encoded as utf-8, there shouldn't be a problem. 
I didnt look at all the other langs, but "spanish.inc.php" just has a string that points to "spanish-utf8.inc.php", so it really seems like an unnecessary extra file.

Also, I see in many of the lang. files there are comments similar to:
`* Please commit your language changes on Transifex (https://www.transifex.com/projects/p/modx-evolution/) or on GitHub (https://github.com/modxcms/evolution).`
which should be updated too.

**Comment by fourroses666** [comment]
@dmi3yy The comments on the lang files needs to be fixed. modx -> evo
But I think that needs to be done on Transifex because that is the base location?
