### ISSUE TITLE
1.4.5 шаблон скрыт после редактирования

### ISSUE THREAD

**Issue by fonpixel** [evolution-cms/evolution#1000]
После редактирования шаблона, он становится скрытым. Очистка кеша сайта не помогает.
Подскажите, как его "включить", чтобы он был виден в списке шаблонов ресурса.
Спасибо.
![image](https://user-images.githubusercontent.com/25525060/52488894-90d7e680-2bc9-11e9-8e29-19ad7d8a2792.png)

**Comment by 64j** [comment]
@fonpixel 
Должно выглядеть так.

![image](https://user-images.githubusercontent.com/4653189/52490127-16ad5f00-2bd5-11e9-9794-c8d29d4d56cd.png)

**Comment by fonpixel** [comment]
Такого чекбокса нет
![image](https://user-images.githubusercontent.com/25525060/52491651-3e4df880-2bd0-11e9-96d7-755853a25fc0.png)

**Comment by 64j** [comment]
@fonpixel 
Он виден только если зайти под учёткой администратора.

**Comment by fonpixel** [comment]
Роль - Publisher. Сайт достался как есть. Задача ставилась подкорректировать шаблон под новые требования.

**Comment by 64j** [comment]
Восстанавливайте доступ с ролью администратора.

**Comment by bossloper** [comment]
Please ignore but...
Congratulation @fonpixel for issue number #1000 ;-)

**Comment by fonpixel** [comment]
Проблема в правах доступа пользователя. Под Администратором работает нормально.
Спасибо @64j  за помощь
