### ISSUE TITLE
Help: DocLister with a multiTV

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1001]
In my page template I have:

> [!DocLister?
> &display=`1`
> &documents=`16`
> &tpl=`menu-Sugencia`
> &tvList=`Food-Menu`
> !]

Doc 16 has a multiTV

The template chuck:

> <h4>[+longtitle+]</h4>
> [+content+]
> [[multiTV? &tvName=`Food-Menu` &display=`all`]]

The page title and content display fine, but the multiTV does not display at all?

**Comment by risingisland** [comment]
@dmi3yy @AgelxNash 
Anybody know how to get this working?
Any help would be much appreciated.

**Comment by AgelxNash** [comment]
Add [docid](https://github.com/extras-evolution/multiTV/blob/master/assets/tvs/multitv/multitv.snippet.php#L59) to the call

**Comment by risingisland** [comment]
Yes, that does work, for a single document, but I have several DocListers pulling from different docs using the same chunck.
Is it possible to using something like:

> [[multiTV? &tvName=`Food-Menu` &display=`all` &docid=`[~[+id+]~]`]]
 or 
> [[multiTV? &tvName=`Food-Menu` &display=`all` &docid=`[*id*]`]]

To get the mutiTV from Doclister "&documents"

**Comment by AgelxNash** [comment]
```[~[+id+]~]``` make url for each pages
```[*id*]``` should return static id for the current page
```[+id+]``` returning id for each pages

You mast use ```[[multiTV? &tvName=`Food-Menu` &display=`all` &docid=`[+id+]`]]```

**Comment by risingisland** [comment]
That did it. Thank you for the info & solution. Much appreciated!
