### ISSUE TITLE
Пользователь не авторизуется через Formlister, если у него логин состоит только из цифр

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#1002]
Есть в системе пользователь, который в качестве логина указал "1234567".

В итоге он не может авторизоваться через Formlister - Login. Причину нашел.
В классе modUsers.php есть функция findUser(), в которой есть вот такая строка:
`case (is_int($data) || ((int)$data > 0 && (string)intval($data) === $data)):` 

Соответственно, так как переданый параметр прекрасно преобразуется в int - запускается ветка, которая ищет по 'attribute.internalKey', а не по 'user.username'  - и естественно, пользователя с ключом 1234567 не находит. 

Если пользователь вводит e-mail вместо логина, то авторизация проходит нормально, но пользователи сами не догадываются об этом.

У себя эту проблему пока решил, унаследовав класс modUsers и переопределив в нем этот метод, но наверное, это все же баг, так как система спокойно позволяет пользователям регистироваться с такими логинами.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/030_%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.md
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/025_%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.md

**Comment by Dreamer0x01** [comment]
Не очень понял, при чем здесь валидация - предлагаете просто запретить регистрировать пользователей с такими логинами?

**Comment by Pathologic** [comment]
Именно.

**Comment by Dreamer0x01** [comment]
В системе УЖЕ есть такие пользователи, и их не мало, база пользователей достаточно старая, раньше на сайте был друпал-6 - я поменял движок на modx. 
Сейчас добавил надстройку в prepare - устанавливаю username через setfield, вытащив соответствующий e-mail из базы, а в форме его вообще не передаю, вместо него передаю другое поле,  о ктором formlister не знает - тогда работает хорошо.

**Comment by Pathologic** [comment]
Тогда правильное решение - расширить modUsers, а новым пользователям запретить регистрацию с такими логинами.
