### ISSUE TITLE
@evoParser('{{chunkName}}') - не работает

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#1003]
@evoParser обрабатывает все, кроме чанков. Для чанков выдает ```<!--?php echo e(chunkName); ?-->```
Скорее всего дело в конфликте синтаксиса с blade - и там и там двойные фигурные скобки

**Comment by webber12** [comment]
Временный вариант решения
`<?php echo evo_parser($modx->getChunk('chunkName')); ?>`

**Comment by 64j** [comment]
@webber12 
Если смотреть код страницы

```html
<?php echo e(Comments); ?>
```

**Comment by 64j** [comment]
А так всё работает
```blade
<?php echo evo_parser('{{Comments}}');?>
```

**Comment by 64j** [comment]
И так работает
```balde
@evoParser('@{{Comments}}')
```

**Comment by webber12** [comment]
@evoParser('@{{chunkName}}') - да, так тоже работает. Но по инструкции http://modx.im/blog/news/5832.html должно работать и @evoParser('{{chunkName}}') - так что либо инструкцию надо править, либо cms :)

**Comment by AgelxNash** [comment]
Возможно тут конфликт MODX парсера и blade. Кто-то где-то кого-то опережает:-) Если сработает конструкция `@evoParser('[[snippetName]]')` то тогда нам остается только документировать особенность.

**Comment by webber12** [comment]
Да, остальные все конструкции отрабатываются. Пробовал 
`@evoParser('[*id*] [~[*id*]~] [*pagetitle*] [(site_name)] [[DocInfo? &docid=`4`]] {{feedback}}')`
отработало все, кроме {{feedback}} - вместо этого в коде `<!--?php echo e(feedback); ?-->`
В варианте с @ - отрабатывают и чанки
`@evoParser('[*id*] [~[*id*]~] [*pagetitle*] [(site_name)] [[DocInfo? &docid=`4`]] @{{feedback}}')`

Проще, чтобы не было конфликтов, второй вариант и использовать, чем пытаться править стандартный парсер блейда для фигурных скобок {{ .. }}

**Comment by AgelxNash** [comment]
> Проще, чтобы не было конфликтов, второй вариант и использовать, чем пытаться править стандартный парсер блейда для фигурных скобок {{ .. }}

Согласен. Значит нужно просто документировать эту особенность
