### ISSUE TITLE
Slack invite

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1005]
I understand that there is another support site on Slack, but you need an invite to participate?
https://evocmf.slack.com/

**Comment by pmfx** [comment]
Yup. In my opinion Slack is good for live discussion, but we need a real, official forum (so discussions/solutions/examples won't be lost).

**Comment by risingisland** [comment]
Agreed. I just visited the ModX forum, but it looks like Evo is more or less dead over there. 
Looks like they recommend the Slack site. 
Not sure if there are any other options for a not Russian speaker?

**Comment by bossloper** [comment]
@pmfx - I totally agree. I remember years ago when I was first learning about ModX the forum was an invaluable resource to search through, find examples and learn from. Searching through github closed issues is just not the same.

**Comment by nick0** [comment]
+100. A forum is way more important than v2 devlopment imho.

We need somewhere where we can ask questions in a friendly envionment, like how the MODx forums were for Evo users previously.

**Comment by fourroses666** [comment]
@risingisland I can invite you to Slack if you give your emailaddress.

If you have questions you can ask them there. Thats what I also do, I don't use the Modx forums anymore for a long time.

Not sure about the progress on an English forum, the modx.im is Russian only.

**Comment by risingisland** [comment]
Thanks Mark (@fourroses666 )
risingisland@yahoo.com

**Comment by fourroses666** [comment]
You should have an invite in your mailbox
