### ISSUE TITLE
DocLister - tplId0 or tplAlt

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1007]
Hello, does anyone know how parameters "tplId0, tplId1, ... tplIdN" works in DocLister ?

&tplId0='tpl_name0' &tplId1='@CODE: test tpl1 [+pagetitle+]' <-- this is not working properly?

**Comment by AgelxNash** [comment]
`@CODE !== @code`
Please ask questions about the component in its repository. https://github.com/AgelxNash/DocLister/issues
