### ISSUE TITLE
`Error : in_array() expects parameter 2 to be array, null given` during file upload

### ISSUE THREAD

**Issue by mrhyde** [evolution-cms/evolution#1009]
Uploading file using file manager leads to `Error : in_array() expects parameter 2 to be array, null given`
Code part related to this issue is located [/core/functions/actions/files.php#L241](https://github.com/evolution-cms/evolution/blob/2.0.x/core/functions/actions/files.php#L241) and is failing due to the fact that global `uploadablefiles` is set to NULL

Unfortunately, I'm not familiar with CMS internals and can't locate the issue, so any help would be greatly appreciated.

Trace:
![image](https://user-images.githubusercontent.com/1016321/53080970-e89c1900-350a-11e9-83c4-5d5b3813fe81.png)

**Comment by Ruslan-Aleev** [comment]
The same error occurs when renaming or copying a file in "Manag Files" section.
