### ISSUE TITLE
Бага в multitTv для поля с типом richtext

### ISSUE THREAD

**Issue by dzhuryn** [evolution-cms/evolution#1013]
Вот такая бага 
https://monosnap.com/file/lOQDnbgKcOsIld49SyFxW9NkgUwfDJ
Если для поля задать еще theme то все вообще сламаеться.

**Comment by 64j** [comment]
Это не бага, а фича...
чтобы не грузить браузер скриптами пока они не нужны.

**Comment by dzhuryn** [comment]
Гуд, сделал скрин, тепер на предяву закажчика скину. Спасибо))))

**Comment by dzhuryn** [comment]
А то что theme ламает также фича?

**Comment by 64j** [comment]
На видео только инициализация tinymce в multitv.
Что за theme?

**Comment by dzhuryn** [comment]
https://monosnap.com/file/WeKbwIbh9X8j26HG2gwYqdBJg7isPv

**Comment by 64j** [comment]
Отправьте ишу в соответвующий репозиторий https://github.com/extras-evolution/multiTV
