### ISSUE TITLE
How to create dynamic TV's "tags" ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1014]
Hello,

There is a last thing I need to know :).
Is there any chance to create custom "checkbox" TV's which will be automatic generated for example by Ditto or DocLister from CMS documents tree ?

Yea I know how to create  a "manual checkboxes" in TV but I need to create something like dynamic "tags" added in CMS - check out my screenshoot. Can I do that in Evo ?

![tags](https://user-images.githubusercontent.com/35030936/53645675-b2147b80-3c39-11e9-8014-41a99caa0849.png)

**Comment by pmfx** [comment]
**Create a snippet tvSelectResources**

```php
<?php
$params['parents']=$parents;
$params['depth']='1';
$params['showNoPublish']='0';
$params['showParent']='0';
$params['tpl']='@CODE:[+pagetitle+]==[+id+]||';
$params['tplLast']='@CODE:[+pagetitle+]==[+id+]';
$params['orderBy']='menuindex ASC';

$output = $modx->runSnippet('DocLister',$params);

return $output;
```

**Create a Template Variable tags**
Type: Checkbox
Widget: Delimeted list
Input Option Values:
```php
@EVAL return $modx->runSnippet('tvSelectResources',[
  'parents' => '38'
]);
```

**Comment by modwebpl** [comment]
Thank u so much. God bless U =).
