### ISSUE TITLE
При добавление фото через менеджер файлов ошибка

### ISSUE THREAD

**Issue by dzhuryn** [evolution-cms/evolution#1016]
При добавление фото через менеджер файлов ошибка 
http://joxi.ru/bmo4Lzptxa0EJ2. Причем внутри документа норм.
https://monosnap.com/file/ZyYk08pyAiSBI0t5mLwxcgHz0ZICdC

**Comment by Ruslan-Aleev** [comment]
Спасибо, issue уже есть - https://github.com/evolution-cms/evolution/issues/1009
