### ISSUE TITLE
Контекстное меню появляется вплотную к левому краю

### ISSUE THREAD

**Issue by Ruslan-Aleev** [evolution-cms/evolution#1018]
Контекстное меню в дереве ресурсов, пли клике правой кнопкой на ресурс, появляется вплотную к левому краю дерева.

Меню перекрывает ресурс и это чревато мисс-кликами. В предыдущих версиях Evolution такого нет.

![context_menu](https://user-images.githubusercontent.com/12523676/53842992-80454100-3fba-11e9-8dc2-f6765041bd1a.png)

Evoluton 2.0.0-alpha

**Comment by Dmi3yy** [comment]
fixed
