### ISSUE TITLE
Проверка на валидность rules в FormLister

### ISSUE THREAD

**Issue by keslo** [evolution-cms/evolution#102]
В _FormLister_ в параметре _rules_ данные задаются в формате JSON.
Если допустить синтаксическую ошибку - из-за чего JSON ломается, то при валидации не выводятся ошибки для каждого отдельного поля. Лог ошибок также чистый. Не сразу пожно понять в чем проблема.

Может сделать валидатор данные rules на соответствие JSON?

**Comment by Pathologic** [comment]
Можно включить отладку параметром &debug и увидеть, что правила не загрузились.
