### ISSUE TITLE
EVO 1.4.8 "POST...manager/index.php 500 (Internal Server Error)"

### ISSUE THREAD

**Issue by yanqpl** [evolution-cms/evolution#1024]
Hi guys!

On my EVO 1.4.8 when i try to edit or save any document i see an empty page (earlier i see a "Save complete" confirmation message) and in browser console i see errors like this: "POST .../manager/index.php 500 (Internal Server Error)"

When i switch off Friendly URLs everythings work fine, but it's not a solution.
Please help, and write me whats the problem?

PHP Version |   | 5.6.40-0+deb8u1

**Comment by dmi3yy** [comment]
how mach documents you have?

**Comment by dmi3yy** [comment]
Best way read the error log  on the server

**Comment by yanqpl** [comment]
About 400

wt., 12 mar 2019, 17:51 użytkownik Dmytro Lukianenko <
notifications@github.com> napisał:

**Comment by dmi3yy** [comment]
> About 400 wt., 12 mar 2019, 17:51 użytkownik Dmytro Lukianenko < notifications@github.com> napisał:
> […](#)

it is little, much is if more than 50 000

if can send login/pass to dmi3yy@gmail.com 
i have 1 hour and can help it will faster. 

next what need see: - plugin list

**Comment by dmi3yy** [comment]
I found bug 

Some docs have own child like parent and when EVO try build cache go tu recursive and eat all memory after that die

Need for this documents set correct parents. list of incorrect docs send by Email

after that you can set URI and all been work
