### ISSUE TITLE
Evo 2.0.0 не удаляются дочерние документы

### ISSUE THREAD

**Issue by lazar2038** [evolution-cms/evolution#1032]
При удалении документа, содержащего дочерние документы, дочерние документы не помечаются удалёнными. При очистке корзины, в Базе Данных дочерние остаются.

**Comment by 64j** [comment]
Duplicate of #1020

**Comment by lazar2038** [comment]
@64j Не согласен, я писал совершенно про другое.

**Comment by 64j** [comment]
@lazar2038 
Та же проблема, по ссылке.

**Comment by lazar2038** [comment]
> @lazar2038
> Та же проблема, по ссылке.

По ссылке - другая проблема, заключающаяся в том, что при удалении ресурса перекидывает на родителя, а сам ресурс при редактировании не восстановить.

А моя тема про то, что если удалить родительский, то дочерние не помечаются на удаление. При этом если очистить корзину, родительский документ окончательно удаляется из базы данных. В то же время, его дочерние документы пропадают из дерева страниц, но полностью остаются в базе данных. Скорее, это баг, а не фича. До 2.0.0 такого не было, удалялось всё и безвозвратно, как и должно.

**Comment by 64j** [comment]
@lazar2038 
Согласен, немного ошибся.
Duplicate of #1012
