### ISSUE TITLE
Order of slides changing in Chrome when going back to the page

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#1037]
Hello,

Just wondering if any other EvolutionCMS 1.4.8 users have experienced this issue in Chrome...

Slides in a Cycle2 Slideshow changing order when going back to the home page.

Scenario: There is a slideshow on the home page. 
The slide order is as expected / intended when first viewing the home page. 
When surfing the site, then going back to the home page (upon clicking the logo in the header or the browser back button), the order of the slides change - at this stage the slide order is wrong.

The slideshow is currently built in MultiTV (2.0.15), but also the same problem existed in DocLister (2.4.1) and Ditto (2.1.3) versions.

I know these 3 snippets are considered separate to the EvolutionCMS core but didn't want to repeat myself three times until I work out what's going on.

The problem appears unique to Chrome for my client and their IT guy (on a different network).
They are using Chrome Version 73.0.3683.86 (Official Build) (64-bit) in Windows 10.1.
The same issue occurs for them in Chrome on their Mac. 
The problem apparently persists with browser extensions disabled. 
The reordering problem does not happen in incognito mode.

On my pc in Windows 8.1, I use Chrome Version 73.0.3683.86 (Official Build) (64-bit) and cannot replicate the issue.

No other browsers appear to have this problem.

The site was recently updated from 1.2.1.

MultiTV call (using the default sorting of slide order within the TV)
```
[[multiTV?
&tvName=`slides`
&docid=`[+id+]`
&outerTpl=`slideshow-mtv-wrapper`
&rowTpl=`slideshow-mtv-row`
&display=`all`
&emptyOutput=`1`
]]
```

DocLister call
```
[[DocLister?
&id=`slider[*id*]`
&idType=`parents`
&parents=`9`
&depth=`1`
&ownerTPL=`slideshowH-wrapper`
&tpl=`slideshowH-row`
&noneTPL=`@CODE `
&noneWrapOuter=`0`
&tvList=`banner`
&orderBy=`c.menuindex ASC`
]]
also tried using a tv to sort, no difference either
&tvList=`banner,slider-sort`
&sortBy=`slider-sort`
&sortDir=`ASC`
```

Ditto call
```
[[Ditto? 
&id=`slider[*id*]` 
&parents=`9` 
&depth=`1` 
&tpl=`slideshow-row` 
&tplFirst=`slideshow-row-first` 
&orderBy=`menuindex ASC`
]]

```

Any ideas?
Have any users seen anything similar to this and do you know of a workaround? 

Many thanks.

**Comment by nick0** [comment]
I forgot to say - this is for a cycle 2 slideshow.

**Comment by 64j** [comment]
@nick0 
Add sorting to multTV 
```
&orderBy=`iteration`
```

to DL
```
&orderBy=`id`
```

to Ditto
```
&orderBy=`id`
```

**Comment by nick0** [comment]
Thanks @64j Serg.

Hmmmm... Only tried on MultiTV for now but that actually randomises the order in Firefox and Chrome - perhaps not what we'd expect with that iteration parameter. Weird.

So the MultiTV is worse with that iteration parameter.

For Ditto and DocLister we definitely want to orderby the order of the resources in the tree - the parameter for that would be menuindex surely?

Currently - it starts out fine and then Chrome changes the order. I don't think the above parameters will change that behaviour?? To me it seems like it would more be some sort of Chrome caching issue???

**Comment by 64j** [comment]
@nick0 
Better orderBy = id, because menuindex can be zero

**Comment by nick0** [comment]
Thanks @64j Serg.

Isn't that how menuindex sorting works though - the first item starts at 0 when you change the order of Resources with drag and drop in the Manager. Has that been changed in 1.4.8 to start at 1?

The ids of the resources are not inline with the order that we want them. So sorting by id would stuff up the intended order.

I think regardless, the weirdness is that Chrome seems to change the order when going back to the page. The order is right to start, then it changes.

More confused than ever :)

**Comment by pmfx** [comment]
It does not sound like an EVO issue at all, but typical frontend code issue. Menuindex after drag&drop starts at 0. Probably something is wrong with your JS code. Try different jQuery/Cycle2 versions or change Cycle2 to something like OwlCarousel.

**Comment by nick0** [comment]
Thanks @pmfx. 
Ok very weird though, its the same cycle2 v2.1.6 version with the same call used on many other of my sites and no such problems (not found or reported at least :). 
````
 <div class="cycle-slideshow"
  data-cycle-slides="> div.slider"
  data-cycle-fx="scrollHorz"
  data-cycle-delay="1000"
  data-cycle-timeout="6000"
  data-cycle-speed="900"
  data-cycle-pause-on-hover="true"
  data-cycle-tmpl-regex="%((\.)?.*?)%"
  data-cycle-pager="#slider-pager"
  data-cycle-pager-template="<a href=# title=slide&nbsp;%slideNum%><span>%slideNum%</span></a>"
  data-cycle-pager-active-class="active"
  data-cycle-loader="true"
  data-cycle-swipe="true"
 >
```
I need to display html text over the top of the slides to match existing style and don't think I can do that with OwlCarousel but will seek an alternative for testing. 
Cheers.

**Comment by bossloper** [comment]
From your first post if it is only happening on Chrome and there is no problem when using incognito mode and it only occurs for them then surely it is a client side chrome caching issue? Have they been re-uploading different images but using the same name?

**Comment by nick0** [comment]
Thanks @bossloper. 
Good call. Client side Chrome caching issue is what I keep trying to tell them but they don't seem to accept / understand my answer.
Good question. I don't believe so. There are 10 images and they all have unique names, with no problems in the naming conventions.
I am testing with a different slider called Slick - will get that working before calling it busted.
Many thanks for your input.

**Comment by Deesen** [comment]
Too late but just my 2 cents.. you can also try to force "no-cache" by adding

```
header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0 "); // Proxies.
```

to /vendor/autoload.php . Maybe this would give more hints about what is happening.

**Comment by nick0** [comment]
Thanks @Deesen 
The web host just changed the PHP execution mode from FCGId to plain CGI and php version to 7.1 and that may have done the trick for the client's system. Just awaiting final confirmation.
If that fails, I will try your much appreciated suggestion.
ps there is no autoload.php file in the vendor folder so I am presuming I would need to create the file new.
Thanks again.

**Comment by nick0** [comment]
Apparently the client and the IT guy are still seeing the order change. 
I cannot replicate and I am with Mr B - client side caching issue.
They are still complaining.

I tried @Deesen 's suggestion but think I did it wrong...
I created a new file called autoload.php and uploaded it into the vendor folder (which only had an index file and an htaccess file in it). All it seemed to do was print the exact code that @Deesen provided. Does it sound like I missed something or interpreted that wrong?
Thanks and again appreciate the input

**Comment by Deesen** [comment]
Sorry, you need to add a `<?php ?>`

```
<?php
header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0 "); // Proxies.
?>
```

I needed this code to force Safari-cache to reload every page-call (I mean HTML-code generated by index.php) instead of caching it. Maybe by forcing Chrome to reload, it will solve your issue too.

**Comment by nick0** [comment]
Hehe, whoops! Thanks @Deesen - I didn't think about php tags but makes total sense :)
Plugged that in and looks to be working behind the scenes (meaning I can't see the code on the page now).
Great stuff and good thinking, thanks so much for your help.
Will see if that does anything. Fingers crossed and a have a good one.

**Comment by nick0** [comment]
Thanks for the help on this.
@Deesen's trick, along with commenting out the htaccess gzip compression on javascript and html has resolved the issue at my client's end. Happy days. 
Many thanks to all for the input and suggestions.
