### ISSUE TITLE
Module dropdown list needs to honour permissions

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#105]
For the manager top menu, the modules dropdown list of modules to execute should chech module permissions. Only those with permission to execute should be listed.

**Comment by 64j** [comment]
@bossloper 
https://monosnap.com/file/ecyCTOdvRCRgHPNmxKEz9B0r7xs95f

**Comment by bossloper** [comment]
No, I am referring to the module 'access permissions' tab and the use of a 'user group' to control execution to certain groups of managers.

**Comment by 64j** [comment]
@bossloper 
If you find a problem, find a solution and we will happily used it !

**Comment by bossloper** [comment]
I'll see if I can find the code next week, but the functionality I described was honoured in the old manager template.

**Comment by 64j** [comment]
@bossloper 
There is a verification for the run of modules
https://github.com/evolution-cms/evolution/blob/develop/manager/frames/mainmenu.php#L224

**Comment by bossloper** [comment]
Just checked again and I had not added my admin manager to the security group so it was empty.
All looks fine, closing...

**Comment by 64j** [comment]
@bossloper 
I open it again.
No check-out, depending on the access rights to the module

![image](https://user-images.githubusercontent.com/4653189/28743461-1aab0cc8-7453-11e7-862a-e93a46ee8a72.png)

**Comment by 64j** [comment]
@bossloper 
Check to see if there is access to modules at the permission level

**Comment by 64j** [comment]
@bossloper 
Check, whether all so?
If everything works, then close issue.

**Comment by bossloper** [comment]
One small issue.  A test manager with these roles:
![untitled](https://user-images.githubusercontent.com/1744687/28743860-7882763a-744c-11e7-97bf-d713d2c53453.png)
cannot see 'Manage Modules'.

**Comment by 64j** [comment]
@bossloper 
No one makes any restrictions.
Usually pose: create a new, edit, save, delete, run.
Or only the run.

**Comment by bossloper** [comment]
Ok, though that is not the same as snippets and chunks.
Otherwise ok now so I will close.
