### ISSUE TITLE
if - bug

### ISSUE THREAD

**Issue by jorjik** [evolution-cms/evolution#1053]
modx-1.4.8

при вы вызове первый и третий тэг - отработал окей, для "описание" -- вообще ничего (и да, я пробовал без вложенных запросов - но там ещё хужее)

> 		<title>[[if? &is=`[*titl*]:notempty` &then=`[*titl*]`
					   &else=`[[if? &is=`[*template*]:=:6` 
					   		&then=`Бегущая строка [*pagetitle*] - подать объявление, цены, телефон`
					   ]][[if? &is=`[*template*]:=:8` 
					   		&then=`Быстро подать бегущую строку; разместить рекламу на телевидении города [*pagetitle*]`
					   ]][[if? &is=`[*template*]:not_in:6,8` 
					   		&then=`[*pagetitle*] - [(site_name)]`
					   ]]`
				]]
		</title>
		<base href="[(site_url)]"/>  [*noIndex*]
		<meta name="description" 
			  content="[[if? &is=`[*desc*]:notempty` &then=`[*desc*]`
					   &else=`[[if? &is=`[*template*]:=:7` 
					   		&then=`Быстро подать объявление в бегущую строку в [*pagetitle*], низкая цена и быстрое размещение! Звоните!`
					   		]][[if? &is=`[*template*]:=:6` 
					   		&then=`Объявления на радио, тв и в газетах [*pagetitle*]. Подать заявку через сайт, легко и быстро!`
					   		]][[if? &is=`[*template*]:=:8` 
					   		&then=`Подать объявления в бегущую строку в [*pagetitle*], онлайн. Быстро размещение, низкая цена!`
					   		]]`
					   ]]" />
		<meta name="keywords" 
			  content="[[if? &is=`[*keyw*]:notempty` &then=`[*keyw*]`
					   &else=`[[if? &is=`[*template*]:in:6,7` 
					   		&then=`Подать объявление бегущей строкой на телеканале СТС | ТНТ | РЕН-ТВ | ТВ`
					   		]][[if? &is=`[*template*]:=:8` 
					   		&then=`[*pagetitle*], Разместить, Подать, Набрать, Персонал, Вакансия, ТВ, Телевидение, Телеканал, Радио, Газета, Печатное издание, Персонал, Вакансия, Контакты, Реклама, Заставка, Видеоролик, бегущая строка`
					   		]]`
					   ]]" />
p.s я говорю про блок

> &is=`[*desc*]:notempty` &then=`[*desc*]`

**Comment by jorjik** [comment]
p.p.s Должен вывести

> тел. (383) 353-47-07. Подать бегущую строку и разместить рекламу на телеканалах «СТС», «Рен-ТВ», «Перец», «ТНТ», «ТВЦ», «ТВ-3», «5 Канал», «Россия», «Первый». Подать объявление в бегущую строку на телевидении РОССИИ. Разместить вакансию, найти газеты издания о работе такие как: «Профессия», «Есть работа», «Работа для Вас», «Работа сегодня», «Хочу работать».

**Comment by gadev** [comment]
у вас там в тексте есть двоеточие, поэтому строка неправильно обрабатывается. 
в вызове сниппета используйте другой (более сложный) разделитель, например:
`&is='[*desc*]:::notempty' &then='[*desc*]' &separator=':::'`
