### ISSUE TITLE
Manager top menu - close dropdown if no action wanted

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#106]
On touch device there is no easy way to close/cancel a manager top menu dropdown menu without selecting an action. Should either be a second press of top level item or click outside menu?

**Comment by 64j** [comment]
Swipe to left.

**Comment by bossloper** [comment]
Swipe left is closing site tree (on iPhone / iPad? )
I am looking to close dropdown for elements, modules etc. E.g. Click elements menu then change your mind.

**Comment by 64j** [comment]
@bossloper 
I'll try to fix it today

**Comment by 64j** [comment]
@bossloper 
https://monosnap.com/file/rslB2bXrA9QumotmpncRFSY2nOzY3z

**Comment by bossloper** [comment]
The video is for the site tree not the top horizontal menu drop downs. I will explain in screenshots tomorrow if you need then.

**Comment by 64j** [comment]
@bossloper 
https://monosnap.com/file/mHzvpfJmTCOkNWysd0B2nf3IzyUjIs

**Comment by bossloper** [comment]
Affirmative! Thanks.

**Comment by bossloper** [comment]
I just noticed I cannot get to the 'Manage Elements' page from the top menu now .i.e. manager/index.php?a=76
