### ISSUE TITLE
multiTV - changing config template?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1060]
Hello,

mutiTV it seems to be very useful but is there any chance to change dynamically TV template in config ?

Of course I can change it manually in assets/tvs/multitv/configs/ and change template in "default.config.inc.php", but what about two different multiTV template for exmaple adding multiple text in blog page and adding multiple images in portfolio ?

**Comment by dmi3yy** [comment]
For that you can use different tv  
and set any config what you want. 

for  tv =  tvname,  need use config: tvname.config.inc.php
