### ISSUE TITLE
multiTV different config array() in multiple templates ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1063]
Hello,

I found in assets/tvs/multitv/configs different ways of changing "multiTV" in EVO template but I rly don't know how setup 2 different "multiTV" for 2 different EVO template:

for example I have multidata box in multiTV:
![Zrzut ekranu 2019-04-18 o 15 48 51](https://user-images.githubusercontent.com/35030936/56366113-a03f6580-61f2-11e9-9b04-4ce8314a8e6f.png)

And now i want to display different configuration of multiTV on different template for example in "contact" or "portfolio" it could be only two simple fields like: "email" and "description".

Can I do that, and how ?

**Comment by pmfx** [comment]
Just create new template variable (multiTV) and new multiTV config file with the name of this new TV. 
Then assign this new TV to your template. Like this:

TV name: myNewTv
Config file name: myNewTv.config.inc.php

**Comment by modwebpl** [comment]
Thx a lot!!
