### ISSUE TITLE
Ошибка после включения плагина "ElementsInTree"

### ISSUE THREAD

**Issue by Makhovik** [evolution-cms/evolution#107]
После включения плагина "ElementsInTree" и клике на иконке в левом сайдбаре
![screenshot_2](https://user-images.githubusercontent.com/2615376/28498797-e18e7324-6fae-11e7-965e-eae80bfc6638.png) "Click here to reload elements list" появляется пустая страница с сообщением "document.ready error: ReferenceError: jQuery is not defined". Ошибка появляется как после обновления с версии 1,2,2 так и на чистой установке Evolution v.1.3,3, как на локальном Apache так и на хостинге nginx. Версии Php=5.6
![screenshot_1](https://user-images.githubusercontent.com/2615376/28498699-0c629c7c-6fac-11e7-94d0-4c4c6009e549.png)

**Comment by 64j** [comment]
Да, там есть косяк с кнопкой обновления.
Но по сути там и без нажатия всё обновляется
