### ISSUE TITLE
DB bag in TRANSACTION query

### ISSUE THREAD

**Issue by dzhuryn** [evolution-cms/evolution#1074]
Если выполнить на том же сервере запрос
$modx->db->query("START TRANSACTION");
 в evo 1.4.8 все будет ок.
При выполнении того же запроса в evo 2.0 получаю ошибку http://joxi.ru/J2b8bV7C0MMkyr.

Трабла при установке дополнения https://github.com/vanchelo/MODX-Evolution-Star-Rating

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/modx-evo-database/commit/7c9d622801f28ee1130d28ca92637cd275a0261f
