### ISSUE TITLE
sql_mode strict

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#1076]
I have a new hoster. Sql_mode strict is on – I can‘t work with evolution. The administrator does not change the configuration for security reasons! This is for me an big Problem. I work in my projects withEVOLUTION.
in 1.4.8 I cant‘t editing Ressources and others. In 2.0.x not parsing.

**Comment by dmi3yy** [comment]
I tested on 1.4.8 with strict all work 

can you send more info what not working ?

**Comment by webkarli** [comment]
1.4.8
Install/UpdateInstall
Host DB: 127.0.0.1:3307
Warning: MySQL server has "sql_mode strict" enabled
Warning: Certain MODX functions do not work correctly as long as "STRICT_TRANS_TABLES sql_mode" is enabled. You can change the MySQL mode by modifying the file "my.cnf" or by contacting your server administrator. (translated from german install)

If I want to open a resource, the right side remains empty. The content is not displayed and cannot be edited.

**Comment by webkarli** [comment]
Here a Screenshot
![screenshot_evo](https://user-images.githubusercontent.com/26146656/57718704-478eab80-767e-11e9-9f02-3fad76c6f17b.png)

**Comment by webkarli** [comment]
Systeminfo:
EVO-Version 	  	1.4.8
Veröffentlichungsdatum 	  	Jan 09, 2019
PHP Version 	  	7.2.15
phpInfo() 	  	Ansehen
Zugriffsberechtigung 	  	Aktiviert
Server-Zeit 	  	17:43:08
Ortszeit 	  	17:43:08
Server-Zeitverschiebung 	  	0 h
Datenbank-Name 	  	__________
Datenbank-Server 	  	127.0.0.1:3307
Datenbank-Version 	  	5.7.11
Datenbank-Zeichensatz 	  	utf8
Datenbank-Kollations-Zeichensatz 	  	utf8_general_ci

**Comment by webkarli** [comment]
**More Info:** from english install
Pre-install validation
Setup has carried out a number of checks to see if everything's ready to start the setup.

Checking PHP version: OK!

Checking if extension iconv is available: OK!

Checking if sessions are properly configured: OK!

Checking if /assets/cache and /assets/cache/rss directories exist: OK!

Checking if /assets/cache and /assets/cache/rss directories are writable: OK!

Checking if /assets/cache/siteCache.idx.php file is writable: OK!

Checking if /assets/cache/sitePublishing.idx.php file is writable: OK!

Checking if /assets/images, /assets/files, /assets/backup and /assets/.thumbs directories exists: OK!

Checking if /assets/images, /assets/files, /assets/backup and /assets/.thumbs directories are writable: OK!

Checking if /assets/export directory exists: OK!

Checking if /assets/export directory is writable: OK!

Checking if /manager/includes/config.inc.php exists and is writable: OK!

Creating connection to the database: OK!

Checking MySQL version: OK!   Your MySQL version is: 5.7.11

**Checking MySQL for strict sql_mode: WARNING!    MySQL server strict sql_mode is enabled!

Certain features of EVO may not work properly unless the STRICT_TRANS_TABLES sql_mode is disabled. You can set the MySQL mode by editing the my.cnf file or contact your server administrator.**

**Comment by Ser1ous** [comment]
I tried to repeat u bug, but all ok. 
U can run comand `SELECT @@sql_mode` and show result
My SQL MODE
![image](https://user-images.githubusercontent.com/4497968/58169600-d19bcd00-7c99-11e9-8986-2be76ced41b2.png)
