### ISSUE TITLE
Trying to get property of non-object « MODX Parse Error »

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#108]
Hi,
I have a lot of error email like this ;
Error : Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,'

This error make like a spam over 100 emails to me.
How to fix this error and now I change"Send mail on MODX errors" to not notify.

**Comment by yama** [comment]
Is this fixed?

**Comment by dmi3yy** [comment]
cant reproduse this bug
