### ISSUE TITLE
Error : session_start(): Failed to read session data

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#1085]
```
Error : session_start(): Failed to read session data: files (path: /var/www/virtual/site/phptmp)
Error information	
ErrorType[num]	WARNING[2]
File	/var/www/virtual/site/htdocs/manager/includes/preload.functions.inc.php
Line	55
Source	session_start();
```

**Моделирование ситуации.**
Смотрим какую куку устанавливает сайт:
`curl -I http://site`
(например: Set-Cookie: **evo123**=0802fc3703922d5d7f5de967a53e98ac; path=/; HttpOnly)
Создаем на сайте ссылку (на страницу, на файл - без разницы), например /link.html (Ссылка на корень сайта / )
**Выполняем:**
`telnet site 80`
**Отправляем:**
```
GET /link.html HTTP/1.1
Host: site
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 7.0) PTX
Cookie: evo123=asd.qwe;
Accept: text/html, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Connection: Close


```
**Получаем:**
`HTTP/1.1 500 Internal Server Error` 
и соответствующую ошибку в журнале событий:
`Parser - session_start(); / PHP Parse Error - Просмотр событий`

Ошибка проявляется на всех версиях 1.4.х

**Comment by q2apro** [comment]
I also got this error:

> Error : session_start(): Failed to read session data: files (path: /srv/users/serverpilot/tmp/website)

About 10 times the same event (bot access):
> 02-07-2019 02:50 AM

This was caused by the Bitdefender bot. Two weeks ago I had a Chinese hack bot with 1000+ requests, which triggered the same.

```
Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /srv/users/serverpilot/apps/matheretter/public/elite/includes/preload.functions.inc.php
Line | 55
Source | session_start();
```

```
Backtrace
DocumentParser->{closure}()on line
```

Could it be that Evolution CMS "blocks" the visitor if it sends 100s of requests?
