### ISSUE TITLE
Web User - new feature :)

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1086]
"Web User" system could be really helpfull but I can't use it because it's restricted to common input data fields. I would love to see the way to create new custom input data fields for "Web User".

What u think about that ?

**Comment by modwebpl** [comment]
Does anybody know how to add a custom input field for WebUser for example: "access code" or "mother surname" etc.  ?

**Comment by dmi3yy** [comment]
http://modx.im/blog/docs/4720.html

**Comment by modwebpl** [comment]
Ok, thx a lot.

**Comment by modwebpl** [comment]
Well this solution: http://modx.im/blog/docs/4720.html
 don't work on Evo 2.0.1 any idea how create and insert custom fields on register ?
