### ISSUE TITLE
ditto2.1.2 doesn't work with php7 (evo 1.2.1 )

### ISSUE THREAD

**Issue by wishbone-design** [evolution-cms/evolution#1089]
Have to upgrade to php7. Can't upgrade evo version (too many customised elements that I don't know).
Upgraded to php7 I get this error:

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /assets/snippets/ditto/classes/ditto.class.inc.php
Line | 584
Source | if (($summarize == 0 && $summarize != "all") \|\| count($IDs) == 0 \|\| ($IDs == false && $IDs != "0")) {
Current Snippet | Ditto

More info:

DocumentParser->executeParser()index.php on line 128
--
DocumentParser->prepareResponse()manager/includes/document.parser.class.inc.php on line 2141
DocumentParser->outputContent()manager/includes/document.parser.class.inc.php on line 2234
DocumentParser->parseDocumentSource(string $var1)manager/includes/document.parser.class.inc.php on line 668
DocumentParser->evalSnippets(string $var1)manager/includes/document.parser.class.inc.php on line 2003
DocumentParser->_get_snip_result(string $var1)manager/includes/document.parser.class.inc.php on line 1408
DocumentParser->evalSnippet(string $var1, array $var2)manager/includes/document.parser.class.inc.php on line 1466
eval()manager/includes/document.parser.class.inc.php on line 1360
require(string $var1)manager/includes/document.parser.class.inc.php(1360) : eval()'d code on line 1
ditto->determineIDs(47, 'parents', array $var3, array $var4, 1, 1, 1, 1, 1, 0, '', 0, 'createdon', 0, 9, '', 1, 0)assets/snippets/ditto/snippet.ditto.php on line 817

Can this be fixed?
Thanks !

**Comment by bossloper** [comment]
Update to Ditto 2.1.4 ?

https://github.com/extras-evolution/Ditto

**Comment by wishbone-design** [comment]
great! Is there a how-to?

**Comment by bossloper** [comment]
Should be in the extras module.
From manager
modules->extras
then search for ditto

**Comment by bossloper** [comment]
I would suggest you remove all urls in your last post as you are potentially at risk of hackers based on the outdated evo version.

Then you could try reverting php to an earlier version and installing the ditto version via extras.
Or you could upload the latest ditto version files using FTP.

**Comment by wishbone-design** [comment]
thx for the tipp with the urls ;-)
works neither with php5.6 nor with php7 - same error (?)
uploaded the new ditto.class.inc.php ("fix for php7.2") - no change. Error as above.

**Comment by bossloper** [comment]
Sorry out of ideas, maybe you have a ditto extension?

**Comment by wishbone-design** [comment]
no, no modifications within the snippet

**Comment by BBloke** [comment]
Could this have something to do with Evo 1.2.1?

Uploading via FTP should get ditto to 2.1.4 but remember to amend the Ditto snippet code accordingly.  I'm not up with Ditto but if $where is a populate ditto parameter then the error is really saying the function ltrim cannot handle $where because it's an array not a string.  So what is $where?

What does your Ditto call look like?

I know I have one site still using Ditto on 1.4.8 and it's fine as the latest revision.

**Comment by wishbone-design** [comment]
thx BBloke for looking into this!
I got ditto updated to 2.1.4 via extras. But same error message.
here is the Ditto call:
`[!Ditto? &orderBy=`menuindex ASC,createdon DESC` &tpl=`dittoEinBuchMitPreis` &extenders=`dateFilter,summary` &hideFolders=`1` &paginate=`1` &display=`9` &trunc=`1` &truncLen=`5000` &truncAt=`` &truncText=`weiter >>`!]`
$where is in all those mentioned files, see above

**Comment by BBloke** [comment]
I currently have Evo 1.4.8 with php 7.0.33 with ditto 2.1.3 and your snippet on my machine works even though I left the template chunk as yours anothing displayed.
Have you tried adding &debug=1 to your snippet and see if there is something it gives you?
Often when I'm trying to track a problem down I start from scratch with the basic snippet command and see if it works.  Then I start adding parameters one by one to see if any of those are causing the issue.

**Comment by Deesen** [comment]
You can also just rename parameters to disable them, instead of removing and adding them one by one again. Like

```
[!Ditto? 
   &XXX_orderBy=menuindex ASC,createdon DESC 
   &XXX_tpl=dittoEinBuchMitPreis 
   &XXX_extenders=dateFilter,summary 
   &XXX_hideFolders=1
   ...
!]
```

and then just remove XXX_ one by one to test which parameter is involved in causing the issue.

**Comment by wishbone-design** [comment]
oh thx!
removed all parameters - same error. Removed the whole ditto call chunk - no error.
((
must be a matter of the old evo version.
Dennis you remember the last upgrade ? it was not that easy...

**Comment by Deesen** [comment]
I think this "not easy" has nothing to do with your issue. As I still have login-credentials I took a quick look, and I think I solved it. I had to add

```
$sqlWhere = implode(' ', $sqlWhere);
```

after line 842: https://github.com/extras-evolution/Ditto/blob/master/assets/snippets/ditto/classes/ditto.class.inc.php#L842

**Comment by Deesen** [comment]
An update to Evo v1.3.4 or later would have fixed this issue too: https://github.com/evolution-cms/evolution/commit/f5092ab1ac641f974e1481b5ced5e32d80debe44#diff-97eb9a7799e0d04086a78b7bb483742fR252

**Comment by wishbone-design** [comment]
works !! you are my hero... Where is your Kaffeekasse?
I don't know any of these php-things.
Not easy: I was referring to the update. Don't dare to try...

**Comment by yama** [comment]
@Deesen thanks
