### ISSUE TITLE
minifyphp_incache breaks heredoc syntax

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#109]
Related: https://github.com/modxcms/evolution/issues/938

**Comment by yama** [comment]
Is this solved? I want test case.

**Comment by Pathologic** [comment]
Create snippet:
```
<?php
$str = <<<EOD
Example of string
spanning multiple lines
using heredoc syntax.
EOD;
return $str;
```
Call it with minifyphp_incache enabled and you'll get parse error.

**Comment by yama** [comment]
Thanks, I'll fix it later.

**Comment by yama** [comment]
Maybe fixed
