### ISSUE TITLE
Баг при обновлении движка

### ISSUE THREAD

**Issue by devbeta** [evolution-cms/evolution#1095]
Как воспроизвести: запустить обновление движка в Хроме с сохраненным паролем от админки сайта. При этом пароль от базы данных будет считываться не из конфига сайта, а из автозаполнения сохраненного пароля от админки сайта, что вызовет ошибку коннекта к базе. Запуск обновления движка в режиме инкогнито или в другом браузере решает проблему.

Как исправить:  в инсталляторе поменять имя поля для пароля к базе, чтобы избежать его автозаполнения.

**Comment by Ser1ous** [comment]
Расскажите какая версия движка с которой производилось и на какую?

**Comment by devbeta** [comment]
Обновление происходило с версии 1.4.8 до 1.4.9.

**Comment by 2frags** [comment]
этот баг присутствует на всех версиях, начиная с 1.4.4 +

**Comment by Dmi3yy** [comment]
Надо отключить там просто автозаполнение
