### ISSUE TITLE
Ditto error sql

### ISSUE THREAD

**Issue by Kyrsorf** [evolution-cms/evolution#1099]
« Evo Parse Error »
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘orderBy=menuindex ASC’ at line 1
SQL > SELECT DISTINCT sc.id,sc.published,sc.isfolder,sc.createdon FROM bd_sait.modx_site_content sc LEFT JOIN bd_sait.modx_document_groups dg on dg.document=sc.id WHERE sc.id IN (11,12,13,14,15,359) AND sc.published=1 AND sc.deleted=0 AND sc.privateweb=0 GROUP BY sc.id,sc.published,sc.isfolder,sc.createdon ORDER BY sc.createdon DESC LIMIT 3orderBy=menuindex ASC

**Comment by Dmi3yy** [comment]
All about Ditto need write here: https://github.com/extras-evolution/ditto/issues
