### ISSUE TITLE
Некоректно отображаются плагины в меню выпадающем

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#11]
http://modx.im/blog/news/5301.html#comment45693

**Comment by Dreamer0x01** [comment]
Обратил внимание - похожее происходит и с TV-параметрами. 
Создал новый TV-параметр - он не появился в выпадающем списке TV-параметров до тех пор, пока я принудительно не обновил страницу админки.

**Comment by 64j** [comment]
когда вы в верхнем меню выбираете создать новый ТВ, верхнее меню запоминает положение, и выбранный пункт, когда вы создаёте новый тв и потом опять нажимаете на верхнее меню, оно показывает последнее положение, если навести мышь на другие элементы, а затем опять на ТВ, то в третьем уровне обновятся все элементы, и новый ваш созданный.
Сделано это для того, чтобы не плодить кучи запросов при простом наведении мыши на пункты меню.
Так же если обратили внимание есть задержка, чтобы скрипт понял, что именно это раздел вам нужен и только тогда сделал запрос на сервер.
