### ISSUE TITLE
Wrong prompt text before delete elements from grid

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#110]
![wrong template](https://user-images.githubusercontent.com/3012304/28503690-267157bc-7014-11e7-8459-e5c6887352fc.png)

**Comment by 64j** [comment]
так в мастере 1.3.3 тоже самое пишет(

**Comment by Pathologic** [comment]
Ну да, а должно писать чанк, сниппет и т.д. (:

**Comment by 64j** [comment]
добавил для разных элементов, свои сообщения
