### ISSUE TITLE
Доступ к файлам отключен, но он есть

### ISSUE THREAD

**Issue by warchild1** [evolution-cms/evolution#1112]
В ролях право доступа к файлам отключено
![photo_2019-07-23_14-02-58](https://user-images.githubusercontent.com/17488086/61690113-c83ee780-ad52-11e9-801f-1c14c96697be.jpg)
а по факту оно есть
![photo_2019-07-23_14-02-46](https://user-images.githubusercontent.com/17488086/61690112-c83ee780-ad52-11e9-8182-728c67e0ab83.jpg)
эво 2.0

**Comment by Dmi3yy** [comment]
Fixed
