### ISSUE TITLE
submitLimit instead sucessTpl

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#1113]
I use a contact form in version 1.4.9 and in version 2.0. Under 1.4.9 it works without errors, but in version 2.0 the submitLimit ( Sie können Ihre Nachricht erneut senden in 1 min - You may send message again in 1 min) is displayed after successful sending of the message instead of the sucessTpl.

**Comment by Pathologic** [comment]
Try develop version https://github.com/Pathologic/FormLister/tree/develop

**Comment by webkarli** [comment]
It's the same.
Here the DocLister (PDF)
[Doclister.pdf](https://github.com/evolution-cms/evolution/files/3426667/Doclister.pdf)

**Comment by webkarli** [comment]
The error is not in FormLister.
Strange, with the Minimal Template everything works.
