### ISSUE TITLE
Animated spinner blocks the screen

### ISSUE THREAD

**Issue by sunhaim** [evolution-cms/evolution#112]
При сохранении ресурса (или чего-либо другого), если какие-то проблемы с сетью, получаю это:

<img src="https://monosnap.com/file/TyqRPQsWdOBYk3XQxtoviPgGxgwAp8.png">

Раньше я бы нажал на кнопку "Попробовать снова", а теперь не могу.
Может добавить заставке "pointer-events: none"?

**Comment by 64j** [comment]
Это решило вашу проблему?

It resolved your problem?
