### ISSUE TITLE
[Discussion] Participation and language barrier issues

### ISSUE THREAD

**Issue by Indigo744** [evolution-cms/evolution#114]
Looking through the list of Github issues, I notice that a lot of them are written in Russian.

The thing is, how can we search for bugs / solutions / discussions, or even participate in Evo development, if some (more than a few) are written in a language not spoken by the majority of the Evo users?

I mean, I'm French, but I would never open an issue in French. Why would I? It's a multinational community.

**It would be good if the main Evo devs/maintainers would address properly this issue**, by trying to enforce English where it is possible. For example, if someone open a new thread in another language, asking him to rephrase in English, or adding the translation in English inside. And always replying in English.

Don't get me wrong. I do respect the fact that MODX/Evo has a large Russian community, and I understand that the main devs are Russian as well. However, please don't forget to be inclusive and to address the largest number of people possible. That way, Evo will always grow and be loved all over the world.

I love what you are doing with Evo CMS, and I can't wait to try the new features. Keep up the good work.
I will contribute if I can find the time.

_An humble (MODX) Evo fan since 2005._

**Comment by 64j** [comment]
4 questions out of 25 on one page in Russian.
People write from Russia and do not know English.
You do not ask your questions in Russian?

**Comment by Pathologic** [comment]
@Indigo744 Some issues in russian were transfered from Dmi3yy's fork repo. I've translated their titles, maybe it helps a bit. In general, we need a contribution guide to prevent such problems.

**Comment by Indigo744** [comment]
@64j yes sorry, "half" was a bit over-exaggerated.

@Pathologic great idea regarding the contribution guide. Also, I've seen some repo which set the default text seen when opening a new issue with some guidelines. Maybe it could be an idea? I found some information here: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by modxuser** [comment]
@Indigo744 

I addressed this issue when the transfer happend / shortly after - you can [read more here](https://github.com/evolution-cms/evolution/issues/16#issuecomment-315520686)

**Comment by yama** [comment]
This is my personal thought.
For general users, posting in their mother tongue (such as Russian) can be allowed.
It is better to post something than to not post anything.
(I can read Russian in Google Translate)

**Comment by Indigo744** [comment]
@modxuser my bad, I didn't saw this issue. But maybe this is for the best, as a discussion is still needed.

@yama I don't know, actually. I'm not really talking about how to understand a given issue in another language. Of course I can always use Google to translate (with some limitation). 
If someone post something in another language, and a solution is given in this same language, then how can I search and find properly this solution? Should I now try to search for keywords in all languages? That doesn't make sense in a multinational community.

Also, how someone could work with Evo and not be able to understand and write some basic English?
Some efforts are required from all parties here.

Back when Evo was still modx, we had a forum with localized sub-boards (French, German, Russian and others). There users could ask questions in their mother tongue. Maybe a similar forum needs to be provided for day to day question and leave Github for development / technical issues.

**Comment by modxuser** [comment]
> For general users, posting in their mother tongue (such as Russian) can be allowed.
It is better to post something than to not post anything.
(I can read Russian in Google Translate)

I disagree, that would mean the board would become full of multinational languages and you wouldn't know where to start, not only that, what about researching problems ?

If you are new to Evo (or not) and you stumble across a problem, you will want to research if someone else has had a similar or the same problem. You can't expect to be able to carry out a successful search if multiple languages are used.

And don't forget to mention that Googles translation algorithm is by far not the best, so trying to translate a language may cause more confusion

**Comment by fourroses666** [comment]
I don't like the idea to post multi language. Its good to have issues posted but these should be English here on Github (if you ask me). Github itself is English and programming language is also English. Don't know the best solution for this. Maybe Google translate and post both languages? Or issues can be posted on the Russian forum and someone who can write both languages adds them here if needed?

**Comment by nick0** [comment]
I vote English (with mucho patience for English as a second language speakers) as the primary language.

**Comment by Nicola1971** [comment]
i agree Github issues should be written in English (note: i'm italian and my english is very bad :) ).

My point of view is that **github is not the place for questions**, but for posting verified issues. For questions, even in native languages, we need a forum

**Comment by 64j** [comment]
@Nicola1971 
Absolutely agree with you.

**Comment by zabudkin** [comment]
The current modx evo developers is Russian/Ukrainian most people.

**Comment by fourroses666** [comment]
Its a good thing, happy to have such good developers. 👍 

I think the issue is that we (non Russian) are a bit afraid Evo is going to be a mainly Russian (language) product, well thats my only concern. I'd like to continue using Evo for a long time, helpout where I can but have English as main language. (Just like the new website).

With a new forum this will be a good solution to have different language sections.

**Comment by yama** [comment]
By the way, in the old days GitHub corresponded to multiple languages. Navigation etc. were displayed in Japanese. But later, now interface of GitHub became English only.

**Comment by Nicola1971** [comment]
> The current modx evo developers is Russian/Ukrainian most people.

I collaborated with the first modx team in the development of the first manager theme (not etomite), and initially they were almost all Americans from Texas, but there were years where the greatest contribution to the modx dev, came from French, English, Japanese...
Like any opensource project, **modx evo would not survive more than a decade without the contribution of people from all over the world**.

...and, for this reason, on modx forum and modx github, they have never written in Texas dialect :D :D
yeeeeeeeeeeeeah! :D

**Comment by Pathologic** [comment]
Don't feed the troll, guys.

**Comment by Indigo744** [comment]
Well, the remark seemed legit...
