### ISSUE TITLE
Inserting a string with [~123~] transforms it to "sanitize_seed_"

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1143]
I am writing a string to the database (custom table) using $POST, such as:

    <p>This is my the article: <a href="/[~123~]">Article One</a>

In the database however, it shows up as:

    <p>This is my the article: <a href="/sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g[sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g~sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g2739sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g~sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g]sanitize_seed_bx5t4pu9b0o4kkg0c4008gs8g">Article One</a>

When reading the string in the CMS, Evo CMS is not creating the correct link for the front end, but just as `[~123~]`.

How to prevent the sanitization?

Or do I need to have it sanitized and I need to call some method when reading the string from my custom table into the Evo CMS?

<br>

References: https://github.com/modxcms/evolution/search?q=sanitize_seed&type=Code

<br>

I am logged-in as Manager. Should the sanitizing not be disabled then? IN_MANAGER_MODE https://github.com/modxcms/evolution/blob/10371f37a7df399be21d1091d5a4d8245062470d/manager/includes/protect.inc.php#L80

**Comment by q2apro** [comment]
It seems that for instance the FormLister does it manually:

https://github.com/Pathologic/FormLister/blob/1f7c61265e0181a7dde2b136c586b7d8129cd284/assets/snippets/FormLister/core/FormLister.abstract.php#L1331

And provides an option: https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/020_Parameters.md#removegpc

?

**Comment by Pathologic** [comment]
It's the default behavior. You can declare IN_MANAGER_MODE constant in case of using external php file to process requests, or use  FormLister's workaround. Anyway don't forget to filter your output.

**Comment by q2apro** [comment]
To unsanitize in EVO 1.4 I used:

```
function helper_unsanitize_content($content)
{
	if(empty($content))
	{
		return null;
	}

	// evo-cms transforms [~123~] to href="/sanitize_seed_bx5t4pu9b0o..."
	global $modx;
	$gpc_seed = 'sanitize_seed_' . base_convert(md5(realpath(MODX_MANAGER_PATH . 'includes/protect.inc.php')), 16, 36);
	$content = str_replace($gpc_seed, '', $content);

	return $content;
}
```

In EVO2 this does not work anymore.

**Comment by Dmi3yy** [comment]
In core have function for unsanitaze no need include protect inc

**Comment by q2apro** [comment]
Yes, this was only for Evolution 1.4.

But if you upgrade von EVO1 to EVO2, then all the old links in the database are protected with a *wrong seed* and all links will show frontend with `<a href="sanitize_seed_...">Test</a>`.

I am using both functions now, the custom one above and the core one.
