### ISSUE TITLE
double slashes in urls

### ISSUE THREAD

**Issue by ivan-s-1** [evolution-cms/evolution#1148]
В версии Evolution CMS 1.4.9 есть проблема с урлами.
Есть урл вот такого вида:
http://site.com/category/pages1/

Если подставим вот такое значение в урл то он все равно обрабатывается и открывается дубль страницы
http://site.com////category/////pages1/////

Так можно спамом через хрумер по разным бордам наспамить произвольными урлами на любой сайт и потом получим в индексе много левых страниц что не есть хорошо для сайта в поиске...

**Comment by ivan-s-1** [comment]
Решение.

Для => .htaccess
# Remove excess slash
RewriteCond %{THE_REQUEST} ^(.*)//(.*)$
RewriteRule . %1/%2 [R,L]

Для => Nginx
if ($request_uri ~* "\/\/") {
  #rewrite ^/(.*)      $scheme://$host/    permanent;
  rewrite ^/(.*) $scheme://$server_name/$1 permanent;
}

**Comment by Dmi3yy** [comment]
https://github.com/evolution-cms/evolution/wiki/Fix-double-slash-in-url
