### ISSUE TITLE
error in the use of the word

### ISSUE THREAD

**Issue by ivan-s-1** [evolution-cms/evolution#1152]
error in the use of the word
![2019-08-12_11-35-22](https://user-images.githubusercontent.com/24613445/62848503-72c47d80-bcf5-11e9-986f-7cbdf0b775a6.jpg)

**Comment by Ruslan-Aleev** [comment]
Спасибо. Поправлено в https://github.com/evolution-cms/evolution/pull/1154

**Comment by Ruslan-Aleev** [comment]
@Dmi3yy Я правда для 1.4.9 не правил, сделать?
