### ISSUE TITLE
Plugin - Simple Tab - checkTable

### ISSUE THREAD

**Issue by dmpol18** [evolution-cms/evolution#1153]
/assets/lib/SimpleTab/plugin.class.php

public function checkTable()
{
    global $modx;
    // $sql = "SHOW TABLES LIKE '{$this->_table}'";
    // Gives SHOW TABLES LIKE '`db_name`.`prefix_table_name`' - it is wrong
    $sql = "SHOW TABLES LIKE '{$modx->db->config['table_prefix']}{$this->table}'";
    return $this->modx->db->getRecordCount($this->modx->db->query($sql));
}

**Comment by Dmi3yy** [comment]
need more details, cant understand what need

**Comment by dmpol18** [comment]
Делали кастомный плагин. 
Выдавалась ошибка о пустом query, когда срабатывал метод createTable.
Тогда решили, чтобы не создавать метод, повесить на таблицу site_content.
Но было замечено, что метод createTable все равно выполняется.
Стали разбираться почему. Оказывается есть метод checkTable, проверяющий существует ли таблица. Там прописан запрос. Если его вывести, то получается, к примеру

"SHOW TABLES LIKE '{$modx->db->config['table_prefix']}{$this->table}'"
Но если выполнить этот запрос при сущ-й таблице, он выдаст 0 rows
Потому что оператор LIKE ожидает строку, а мы даем ссылку на "имя базы данных.имя таблицы"
Поэтому таблица не определяется как существующая и всегда выполняется скрипт createTable.
В примере я написал свой рабочий вариант кода с проверкой таблицы
$sql = "SHOW TABLES LIKE '{$modx->db->config['table_prefix']}{$this->table}'";

**Comment by Pathologic** [comment]
Да, есть такая проблема.
