### ISSUE TITLE
Display EVO tags on page

### ISSUE THREAD

**Issue by yama** [evolution-cms/evolution#116]
\[\[Snippet call\]\]
    \[\*Content tag\*\]
    \{\{Chunk\}\}

Write tags with escaping backslashes. Then we can display the tag as it is. It's convenient for making EVO documents. ok?

**Comment by yama** [comment]
https://www.smarty.net/docsv2/en/language.function.literal.tpl
Other method

    <@LITERAL>
    [[Snippet call]]
    [*content tags*]
    {{Chunk}}
    <@ENDLITERAL>

**Comment by yama** [comment]
https://vuejs.org/v2/guide/

    <div id="app">
      {{ message }}
    </div>
Can solve batting of vue.js and chunk

**Comment by modxuser** [comment]
Whats the point @yama ?

You can display Evo tags anyway - I re-built the English documentation completely and didn't have any problems in displaying tags.

Simply use the character entity - [example here](http://www.evolution-docs.com/contact/contributing-to-the-documentation#code-blocks)

Another example is the actual [Evo Tags page](http://www.evolution-docs.com/documentation/content-editing/cms-tags/)

**Comment by fourroses666** [comment]
I like the second one yama. This way you just need to wrap it :-)

**Comment by 64j** [comment]
@yama 
And what if use this syntax?
```html

<evo:if $id = 1 >
  ...
  <evo:elseif $id >5 >
  ...
  <evo:else>
  ...
</evo:if>

or

<evo:if cond="$id = 1">
  ...
  <evo:elseif cond="$id >5">
  ...
  <evo:else>
  ...
</evo:if>

 or

<evo:literal>
  ...
</evo:literal>

or

<e:if > => <evo:if >
```

**Comment by yama** [comment]
Nice idea, thanks!

**Comment by 64j** [comment]
codemirror autoformat code))

Ctr+A and Shift+Tab

![image](https://user-images.githubusercontent.com/4653189/28573279-dc83b5e2-7152-11e7-8e8a-42d4ae375909.png)

**Comment by yama** [comment]
thanks more hint

**Comment by yama** [comment]
@modxuser 
Thanks for reply. I think that it is difficult to memorize numbers such as &#91; . If possible, simple way is good. It is also necessary to write vue.js, Smarty and so on.

**Comment by 64j** [comment]
@yama 
It would be nice if you make an event for the **mergeConditionalTagsContent** function, for custom plugins.

**Comment by yama** [comment]
Thanks @64j , For example, we can make the following functions for only myrself.
````
<@HTMLSPECIALCHARS>
This is html tags tutorial
<abc><def><ghi><etc>
<@ENDHTMLSPECIALCHARS>
````
