### ISSUE TITLE
Параграф при вставке текста в Tiny MCE

### ISSUE THREAD

**Issue by warchild1** [evolution-cms/evolution#1162]
При вставке текста в Tiny MCE из MS Word параграф вставляется нормально с тэгом <p>. Из LibreOffice или в MacOS из Pages текст вставляется без <p>, а с переносом строки <br />. Проверено на разных системах и версиях.

**Comment by 64j** [comment]
@warchild1 

![image](https://user-images.githubusercontent.com/4653189/63324766-65307880-c331-11e9-92a9-a823be4da120.png)

**Comment by warchild1** [comment]
Дело не в очистке формата. Он очищен. По факту если вставляется br то он им и останется. я про тэг параграфа. Проверено уже не однократно. из ворда вставляется с тэгом p из остальных текстовых редакторов просто перенос строки
