### ISSUE TITLE
Добавить возможность blade шаблонам подключаться из папок

### ISSUE THREAD

**Issue by projkin** [evolution-cms/evolution#1166]
views/page/default.blade.php - не работает. Даже если прописать в админке alias "page.default" т.е. через точку в лучших традициях ларавел.
![Clip2net_190821151116](https://user-images.githubusercontent.com/54156948/63427537-698a8d80-c426-11e9-91d8-20921c385d91.png)
![Clip2net_190821151437](https://user-images.githubusercontent.com/54156948/63427546-6b545100-c426-11e9-8897-006f3f022fd5.png)
Чтобы сайт не превращался в помойку, желательно иметь возможность деления шаблонов на папки. Как в модиксе по категориям.

**Comment by 64j** [comment]
Настройте плагин TransAlias

![image](https://user-images.githubusercontent.com/4653189/63429132-e9622900-c421-11e9-8c10-b257f64dadc7.png)

![image](https://user-images.githubusercontent.com/4653189/63429166-fd0d8f80-c421-11e9-9473-37f83ff61dc2.png)

**Comment by Dmi3yy** [comment]
Так не совсем правильно на самом деле ибо тогда и для документов добавиться / а это не логично проще через . и просто подменять при получении .  на. /

**Comment by 64j** [comment]
@Dmi3yy 
Значит нужно отключить плагин TransAlias при сохранении шаблонов.

**Comment by 64j** [comment]
Точнее не использовать.

**Comment by Dmi3yy** [comment]
Ну да так логичней :)

**Comment by projkin** [comment]
TransAlias если отключить замену слешей тогда будет плохо для генерации урлов.

**Comment by 64j** [comment]
> TransAlias если отключить замену слешей тогда будет плохо для генерации урлов.

Не надо отключать, на скрине выше, как его настроить.

**Comment by Dmi3yy** [comment]
Отключить для шаблона только :) что б все ок было поставил на ser1ous поправит

**Comment by projkin** [comment]
Ну ад, я сделал по совету, и померли урлы вложенные, =)

**Comment by Ser1ous** [comment]
https://monosnap.com/file/oJ2z4hlNer4uCGta82FLd8PjyZKSMW
Немного не понимаю почему у Вас не работает. Я только что протестировал всё ок.

**Comment by Dmi3yy** [comment]
Работает если использововать так 

folder.template 

и файлик 
views/folder/template.blade.php
