### ISSUE TITLE
Дерево в evo 2.0.

### ISSUE THREAD

**Issue by nuclear4547** [evolution-cms/evolution#1167]
при перетаскивании ресурсов в дереве ресурсов возникает такая ошибка в консоли браузера.
[1566447511284.log](https://github.com/evolution-cms/evolution/files/3528252/1566447511284.log)
при этом визуально это проявляется так:
когда ресурс, в который перетаскивается другой ресурс, становится папкой то вместо иконки папки появляются классы иконки
http://joxi.ru/Vm64JqVt469NDA
в документ id 1 был перенесен другой документ

Версия Evolution CMS |   2.0.0-alpha
Браузер Chrome 76

**Comment by kivamp** [comment]
Версия Evolution CMS |   2.0.0-RC
При перетаскивании красная иконка позиционирования потерялась

**Comment by Dmi3yy** [comment]
Перепроверил сейчас все ок
