### ISSUE TITLE
Add module/plugin/etc. from file

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1177]
@Ser1ous @Dmi3yy 
A few questions...
I see that "Add module from file" #1175 is being added to 2.x. Will something like this also be added to the 1.49 branch?

Also, [PackageManager](https://github.com/extras-evolution/PackageManager), (which is now depreciated), had a nice feature that would also be nice to see available again in the future.

With PackageManager, it was possible to have folder "assets/packages/" and drop any Module, Snippet, Plugin or Chunk in this folder at the time of installation, and once PackageManager was installed, these frequently used packages were ready to install. No need to upload or search.

This is very convenient for packages/modules that are used frequently in all new projects.

**Comment by Dmi3yy** [comment]
Soon will lessons about 2.0 

basic on russian but in want translate into English too. 

in 2.0 we have packages by default ) 

Some info you can find here: 
https://github.com/evolution-cms/example-package
