### ISSUE TITLE
Cannot declare class DLTemplate, because the name is already in use

### ISSUE THREAD

**Issue by ivan-s-1** [evolution-cms/evolution#1182]
![2019-09-03_00-56-46](https://user-images.githubusercontent.com/24613445/64131960-9c992d80-cde5-11e9-9a58-7c32a11d05bd.jpg)

- Evolution CMS 2.0.0-alpha
- Пробовал обновить DocLister из Extras и https://github.com/AgelxNash/DocLister. Не помогло.

**Comment by Dmi3yy** [comment]
Откуда скачивали? 
С релизов или с ветки 2.0.X ?

**Comment by ivan-s-1** [comment]
с ветки 2.0.X

**Comment by ivan-s-1** [comment]
Проблема оказалась в сниппете самописном.

**Comment by ivan-s-1** [comment]
Проблема оказалась не в сниппете самописном. А все таки проблема в DocLister, показывается таже ошибка. Отключил где выводиться через DocLister + DLmenu и ошибка исчезла.

**Comment by ivan-s-1** [comment]
![2019-09-03_01-36-31](https://user-images.githubusercontent.com/24613445/64132717-2ef00000-cdeb-11e9-9357-ee9cccb5f2db.jpg)

**Comment by AgelxNash** [comment]
Файл с классом должен быть пустой. А у вас там код https://github.com/evolution-cms/evolution/blob/2.0.0-alpha/assets/snippets/DocLister/lib/DLTemplate.class.php
Проблема на вашей стороне
