### ISSUE TITLE
No more dashboard widget support with new theme

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#12]
The new theme does not support dashboard widgets.. why??

**Comment by dmi3yy** [comment]
New system for widgets like in top menu on tree.

`
$e = &$modx->Event;
switch($e->name){
        case 'OnManagerWelcomeHome':
				//if($_SESSION['mgrRole']!=='2') return;
                
                //unset($widgets['welcome']);
				//unset($widgets['onlineinfo']);
				//unset($widgets['recentinfo']);
				//unset($widgets['news']);
				//unset($widgets['security']);
				
				$widgets['test'] = array(
					'menuindex' =>'1',
					'id' => 'test',
					'cols' => 'col-sm-6',
					'icon' => 'fa-rss',
					'title' => 'test',
					'body' => '<div style="max-height:200px;overflow-y: scroll;">[+modx_news_content+]</div>'
				);
                $e->output(serialize($widgets));
        break;
}
`

**Comment by Nicola1971** [comment]
ok, it's nice, but 

Some remarks:

- ordering widgets with menuindex parameter inside the code (not user friendly) 
- if you need more widgets, you must have all in the same plugin code
- with more than one complex widget the code will be very, very long
and harder to understand wich widget does not work (when all your dashboard is not accessible...) 
- **i can not see a way to share and install widgets as extras** (not user friendly, bad for developers) 


menuindex could be added to the plugin settings, but you need to add new menundex parameter for any new widget added.
If you develop widgets that require many configuration parameters, the configuration page will become unmanageable

Your new dashboard code is **clean** and **faster**, but the dashboard it's something more for users, power users, managers...

In any kind of Software and Operating System, widgets are "_**gadgets for user interface**_": easy to install, move, delete, resize...
And that's why I moved out default widgets from evodashboard plugin, years ago.

For this kind of things we need to learn from WP not Revo.

**Comment by dmi3yy** [comment]
1 plugins for 1 widgets its no problems ). sry lost last commits with this changes.  fix tonight.
2 we are not have many widgets and then  not see sense for sortable. but now i can add and sort widget for each manager. And without js its fork very fast. You can check load speed manager page)
3 yes we can do more widgets and then do user frendly for manager to install, move, delete, resize

**Comment by dmi3yy** [comment]
http://take.ms/C6hHM

**Comment by Nicola1971** [comment]
an easy way (any kind) to sort widgets is usefull.

i think about widgets like a new extras category and an interesting feature for evo packages.

example:  a dashboard widget for evoshop with selling summary ( like in wp woocommerce)
![woocommerce-status-dashboard-widget](https://user-images.githubusercontent.com/7342798/28126135-e96f6a5a-6728-11e7-8cf1-594aa7ccbced.png)

**Comment by Nicola1971** [comment]
> 2 we are not have many widgets ....

http://www.tattoocms.it/tags.html?tags=dashboard+widgets  :D

All my customers are addicted to see in their dashboard
- registered users (useful to delete daily spammers)
- comments
- basic system stats
- analytics
- shortcuts for publisìhers/editors to fast create documents in the right folder (modx tree is not for all)

what my customer does not want to see: most of default widgets :D

**Comment by dmi3yy** [comment]
Then need new category in extras for widgets 

And add one plugin or module for manage wedget:)

Отправлено с iPhone

**Comment by toha-proud** [comment]
I think that we need to create folder like assets/wigets and put all wigets in this folder with file format .tpl and manage all wigets in Configuration. This way to install any wigets from extras without creating a lot of plugins.
