### ISSUE TITLE
Multi domains in Evo 1.4 or 2.0 ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1201]
Hello,

Can anyone give quick info how to manage multi domains in EVO 1.4.9 or 2.0 RC ?

e.g. en.company.com -> start doc_id = 1, ru.company.com -> start doc_id = 190

**Comment by Dmi3yy** [comment]
Are you have diff stucture or same?

**Comment by modwebpl** [comment]
Well, structure will be the same with difference names and alias. For example:

- polish version: www.domain.com/kategoria/dokument
- and same structure with different names and alias: en.domain.com/category/document

**Comment by modwebpl** [comment]
Well the main problem is "index" because in PL version we have start_page ID 1: www.domain.com/
and I don't know how redirect "site_start ID" for en.domain.com/ -> to different index template ID

**Comment by Dmi3yy** [comment]
I use this: https://github.com/bumkaka/bLang

but some fix 

BLang plugin: 
```
$modx->config['agent'] = $_SERVER['HTTP_USER_AGENT'];

require_once MODX_BASE_PATH.'assets/modules/blang/lang.class.inc.php';

$langs = array();
$roots = array();

$dd_domens = json_decode($modx->config['dd_domens'], true);
$domens = $dd_domens['fieldValue'];

foreach($domens as $k => $v){
	$langs[] = $v['lang'];
	$roots[$v['lang']] = $v['domen'];
}

$Lang = new LANG($modx, 'ru', $langs, $roots);
$lang = (string)$Lang->lang;

if($lang == 'ro'){
	//die();
}

$_SESSION['lang'] = $lang;
$_SESSION['Lang'] = strtoupper($lang);
$_SESSION['root'] = $modx->config['_root'];
```

Domains config on ClientConfig with multiTV 
https://take.ms/WoAov
And fix blang class for work with domain 
https://take.ms/0sco1



https://take.ms/0sco1

**Comment by modwebpl** [comment]
Ok thanks, I will figure it out =)
