### ISSUE TITLE
Загрузка изображений в файловом  менеджере

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#1202]
Evo 2.0.0RC
Изображения загружаются, но сообщения не верно отображают на них ссылки (от корня)
![Screenshot](https://user-images.githubusercontent.com/6448120/65819003-0c051000-e220-11e9-8bae-9ad52004f5a1.png)

**Comment by kivamp** [comment]
PS: просмотр (глаз), кстати тоже не работает: ссылку на изображение выставляет: ../assets/images/news/20190927181142_5d8e26aeaed78.jpg
(две точки впереди)

**Comment by Dmi3yy** [comment]
Поправил путь, права и просмотр
