### ISSUE TITLE
European Union court decided to ban cookies in the EU

### ISSUE THREAD

**Issue by sirfranz** [evolution-cms/evolution#1203]
On Oktober 1, 2019 the JUDGMENT OF THE COURT (Grand Chamber) of the European Union decided to ban cookies in den EU, see Judgment number 56 following: http://curia.europa.eu/juris/document/document.jsf?text=&docid=218462&pageIndex=0&doclang=EN&mode=req&dir=&occ=first&part=1&cid=1438506

Now, cookies can only be placed after the visitor to a website agrees. If the visitor does not agree, cookies now are prohibited. The cookie treatment must be done through the website. But evo places cookies without asking the visitor.

Next is the planned new e-privacy directive of the European Union. The use of cookies will be further restricted in the future. In the future, visitors to a website will not only have to accept cookies, but also be able to choose which category of cookies will be set: technical cookies, tracking cookies, etc. In addition, machine communication should also be restricted.

It's terrible.
Hope you have a cookie solution for evo.

**Comment by modwebpl** [comment]
Damn.. :/

**Comment by leonie12** [comment]
It seems that technical necessary, especially session cookies, are excluded from the obligation to ask for consent before setting them. How I understand it Evo cokkies are falling under this exclusion.

**Comment by sirfranz** [comment]
Trank you leonie12

Article 5(3) of Directive 2002/58:
3. Member States shall ensure that the use of electronic communications networks to store information or to gain access to information stored in the terminal equipment of a subscriber or user is only allowed on condition that the subscriber or user concerned is provided with clear and comprehensive information in accordance with Directive 95/46/EC, inter alia about the purposes of the processing, and is offered the right to refuse such processing by the data controller. This shall not prevent any technical storage or access for the sole purpose of carrying out or facilitating the transmission of a communication over an electronic communications network, or as strictly necessary in order to provide an information society service explicitly requested by the subscriber or user.
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32002L0058&from=DE

Evo works without cookies, too. Only the access at protected areas is not possible. Cookies therefore not strictly neccessary to visit an evo website. So, evo cookies are not covered by the exemption. That's the problem.

**Comment by Dmi3yy** [comment]
I think we can create plugin for that with some def style 

its not hard

**Comment by sirfranz** [comment]
Sounds great.
I don’t really have the time to do that right now.

My thoughts:

[technical]
The cookie-settings should be saved within the SESSION, like this structure:

$_SESSION['cookies']['permission']

under that:

['allow_technical']	bool [0|1]	default 1	0=disabled	1=enabled
['allow_tracking']	bool [0|1]	default 0	0=disabled	1=enabled
['allow_other']		bool [0|1]	default 0	0=disabled	1=enabled

How long cookies can be stored is controversial. I think so far a maximum of 30 days.


[plugin]
If the user visit the website and no session cookie is set, a dialog opens to get the user exemption. This dialog have to include (by law)

a)	an information that this website uses cookies
b)	an link to the privacy policy
c)	options to select which type of cookies the user want to allow
d)	two buttons: "save and accept cookies" and "don’t accept cookies"


[snippet]
It has to do two things:

a)	allow the site manager to include content, that set cookies (e.g. google ads)
b)	show the "cookie-central"

a) could be like this [!cookie? cmode=`set_content` type=`<the cookie type>` content=`<the content chunk>` error=`<the error chunk>`!]

cmode	the snippet mode
	        [set_content|cookie_central]	default:	set_content
 
type	        the type of the cookie the content will set
                set [tech|tracking|other]
 
content	the name of the chunk, that contains the content that set cookies
 
error        	the name of the chunk, that contains an error message if the user has chosen that he don't want to set cookies of the chosen type (see 'type' above)

The snippet returns the content of the applicable chunk.


b) Cookie-Central
By law, website visitors have to be able to change their choices. So we need a cookie-central where the user can change his exemption. The snippet call could be like this [!cookie? cmode=` cookie_central`!]

The Cookie-Central can be placed on a separate page.

**Comment by webkarli** [comment]
I am first and foremost a user of EVOLUTION. Unfortunately I am not a great developer. I do a few simple snippets myself. Other than that I use almost only the standard extras. I do not trust myself to develop plugins. But I urgently need a solution for cookies in the EU. It is European law and violations can be very expensive. I have been using MODX for many years and now I use EVOLUTION. In the meantime I have changed my projects completely to EVOLUTION 1.4 and 2.0. If I can not meet the requirements of the European Union court, I have a very big problem. Since I probably can't develop it myself, I have to rely on help. Please help.

Translated with www.DeepL.com/Translator (free version)

**Comment by Dmi3yy** [comment]
For example can use this: 
https://www.cookiebot.com


I think i have time for that only in March (

**Comment by bossloper** [comment]
And also https://github.com/Nicola1971/DivasCookies-Plugin

**Comment by webkarli** [comment]
If I see this correctly, Nicola's solution in 2020 is no longer sufficient. I had created a similar solution, without administration in the backend, with a snipped.

**Comment by bossloper** [comment]
@webkarli - yes you may well be right.

**Comment by bossloper** [comment]
This might be an option when they release version 4.0:
https://github.com/osano/cookieconsent

v4 category opt out thread:
https://github.com/osano/cookieconsent/issues/556

**Comment by webkarli** [comment]
At osano 7500 hits are free, after that 99 $ per month are due. The 7500 hits are easily accessible even with small projects. This exceeds my budgets. 

Oh, osanao on github is MIT. I'll try.

Other question: 90% of my projects have only the EVOLUTION-cookie. How can I prevent the setting of the EVOLUTION-cookie for normal website visitors. If this is practical for me, I try to make a cookie-consent for many of my own projects by myself, as a temporary solution.

**Comment by Dmi3yy** [comment]
I add task for developer do plugin for Evo, need some time for that

**Comment by risingisland** [comment]
As I too am looking for a solution, maybe this will be of help to others:
• https://www.jqueryscript.net/other/GDPR-Cookie-Compliance-Plugin.html
• https://github.com/osano/cookieconsent
• https://www.freeprivacypolicy.com/cookie-consent/

**Comment by sirfranz** [comment]
The big problem is, that cookies are only allowed, if the visitor confirmed it before - before the first cookie was set. If there is no user consent, cookies are prohibited. And so it’s not allowed to set any cookie except of special technical cookies.

My suggested solution above has to parts: one Plugin and one Snippet.

The Plugin is for the user consent. The user is asked witch type of cookies he wants to accept. And the user must be able to change his choice at any time.

The second part, the Snippet is for setting the content which set cookies. So it can assure that only cookies were set, which the user allow.

The snippet call could be like this: [!cookie? &type=`cookie type` &name=`name of the cookie` &vendor=`the vendor of the cookie` &content=`CODE:|Chunk-Name`!]

type is the type of the cookie e.g. technical, advertise, and so on
name is the name of the cookie e.g. ads
vendor is the vendor of the cookie e.g. google
content is the content which set cookies. It could be set by a chunk or as code.

I think this would be an acceptable solution.

**Comment by risingisland** [comment]
Has there been any progress on a solution for this, or has anybody created their own solution that they are willing to share?

**Comment by bossloper** [comment]
As mentioned and as you linked https://github.com/osano/cookieconsent/blob/dev/CHANGELOG.md should do the job, but only if you use the dev branch as it has the cookie categories  'Uncategorized', 'Essential', 'Analytics', 'Marketing', 'Personalization' . not just a 'yes/no'.
See the changelog third item down.
I have not tried it yet though!

**Comment by risingisland** [comment]
Ok. Just wasn't sure if somebody had already created a plugin from this or other as that is beyond my capabilities. Will take a look and see if I can figure out something.

**Comment by webkarli** [comment]
If I have understood this correctly, the evo session cookie is only needed at login. Why is it always used? Is there no other solution? Cookies that I set myself, I can manage through different cookie-content-solutions like [https://klaro.kiprotect.com](url) oder [https://www.oiljs.org/](url) or others. I cannot access the cookies from Evolution. If I want to implement the European Union court correctly, I may only set cookies after the site visitor has agreed. This is currently not possible with EVOLUTION. I violate the law. I do not want that. Violations of the law can also be punished, including violations of the European Union court. The problem should be easy to solve by setting the session cookie only at login. For me the problem is becoming more and more a decision of principle for or against EVOLUTION.

**Comment by Dmi3yy** [comment]
Havent see any problem  With this task 

In Evo you can control all, even popup with check use cookie or not. 

I know who do solution for that. I think soon in public :)

**Comment by bossloper** [comment]
I can recommend:
https://www.termsfeed.com/cookie-consent/ 
for a working up-to-date with regulations cookie consent solution that has cookie type options. 

You just need to add adjust scripts to include a cookie-consent tag of strictly-necessary, functionality, tracking or targeting. And then change the script type to text/plain. It is all well documented on the above link.

**Comment by webkarli** [comment]
I have already asked what I have to do to prevent the evo-cookie from being set for normal website visitors. Or the other way round, what I have to do or set so that the evo-cookie is only set at login.
I assume that this post [https://github.com/evolution-cms/evolution/issues/1471](https://github.com/evolution-cms/evolution/issues/1471) is also about that.
**I need a quick, simple, helpful answer now!!**

**Comment by sirfranz** [comment]
@webkarli
try this as fast workaround:
1. open the file on your server: core\bootstrap.php
2. search the line: startCMSSession(); // start session
3. uncomment this line like this: //startCMSSession(); // start session
4. save it on your server

Now there is no longer a session cookie set, but nobody can log in.
If it does'nt work, or there are errors undo the changes.

**Comment by bossloper** [comment]
Correct me if I am wrong but I thought 'strictly necessary' cookies i.e. those that allow the basic site work were allowed without specific consent?

See 'Strictly necessary cookies' in the 'Types of cookies' section.

https://gdpr.eu/cookies/

**Comment by sirfranz** [comment]
@bossloper 
I think so.

Some people wants no cookies. In some countries there are lawyers who send warning letters - even that is abuse of law. And there are also people who believe that all cookies can spy on them, collect data and see what they have previously viewed.

**Comment by bossloper** [comment]
Yes, and why you also need a page describing what each of the cookies on your site do.

To get and example from source where cookies are still there even if you say no cookies. Go to the EU website:
https://europa.eu/

Select 'I refuse cookies' at the top. You with three cookies relating to your rejection of consent:
cck1, eu_cookie_consent, main_eu_optout
Which is fine as ironically you have to have cookies set to be able to reject other cookies.

But If you then navigate elsewhere on the site or use their search you can get other system cookies appearing and they are obviously needed to make the site work:. E.g.
has_js
JSESSIONID
These are necessary system cookies. So if it is good for them it is good enough for me! :-)
