### ISSUE TITLE
Cannot declare class DLTemplate, because the name is already in use

### ISSUE THREAD

**Issue by ivan-s-1** [evolution-cms/evolution#1206]
Cannot declare class DLTemplate, because the name is already in use,

- php 7.3
- Evolution CMS 2.0.0-RC (чистая установка)

Пробовал удалить полностью DocLister из папки и все его файлы, и поставить DL по новой, не помогло, ошибка сохраняется. Пробовал ставить DL через Extras, ошибка сохранилась. Пробовал выкачать DL с https://github.com/AgelxNash/DocLister, ошибка сохранилась. 

![2019-10-03_22-59-44](https://user-images.githubusercontent.com/24613445/66151745-6263bb80-e631-11e9-8343-319573cda2aa.jpg)

**Comment by Dmi3yy** [comment]
https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/lib/DLTemplate.class.php#L2

проверьте что у вас вот такая 2 строка

**Comment by ivan-s-1** [comment]
не было строки, заменил файл этим что указали, теперь другая ошибка при запуске DL
![2019-10-04_00-42-58](https://user-images.githubusercontent.com/24613445/66158695-d7d68880-e63f-11e9-8b55-b6f7cedeff42.jpg)

**Comment by Dmi3yy** [comment]
Попробуйте еще раз перезалить RC 
ибо если у вас не было этой строки то у вас не RC версия ибо там есть 
https://github.com/evolution-cms/evolution/blob/2.0.x/assets/snippets/DocLister/lib/DLTemplate.class.php#L2


А по части ошибки новой 
Надо в конфиге mysql вырубить грубую GROUP BY

**Comment by ivan-s-1** [comment]
Спасибо!

**Comment by Dmi3yy** [comment]
Как понимаю все работает уже
