### ISSUE TITLE
Problem with parsing polish character on automatic generated alias Evo 1.4x, 2.x

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1212]
Hello,

I found a problem with parsing polish char "ś". When I create and save new document for example with name "jakość" it create alias with wrong name: "jakoc" but It could be "jakosc" it's really important for Polish SEO links :(

I tested on MYSQL character SET utf8_polish_ci and utf8_general_ci - same error :/

**Comment by Dmi3yy** [comment]
You can change rules in stripAlias plugin

**Comment by Dmi3yy** [comment]
You can create rules for polish
https://github.com/evolution-cms/evolution/tree/2.0.x/assets/plugins/transalias/transliterations

**Comment by modwebpl** [comment]
OK, thanks a lot

**Comment by modwebpl** [comment]
I check "common" $table_name wich is default and I found this:
'ś'=>'s', but it doesn't work in real ?

**Comment by Dmi3yy** [comment]
Show transalias plugin settings plz

**Comment by modwebpl** [comment]
My apologize, before I manually add str_replace('ś', 's', $alias); I check plugins option and set to "common" - now its everything ok :)
