### ISSUE TITLE
[(use_alias_path)]

### ISSUE THREAD

**Issue by ivan-s-1** [evolution-cms/evolution#1213]
Не корректная работа функции "Использовать вложенные URL:" [(use_alias_path)].
При переносе cms на др. хостинг, перестает работать эта функция. 

Evolution 1.4.9
php 7.1

**Comment by Dmi3yy** [comment]
В чем же не корректность если перестала работать при смене хостинга??

Может стоит  проверить все ли ок с новым хостингом?

**Comment by ivan-s-1** [comment]
проблема странная, потому что др. аналогичные сайты на той же сборке работают без проблем, с той же конфигурацией nginx. А здесь чистая сборка запущена была на хостинге где apache а потом перенесена на локалку где nginx, и перестала работать функция эта

**Comment by Dmi3yy** [comment]
Так если везде работает а тут нет то явно ж вопрос к окружению и настройке

Если б глючила функция она бы глючила везде 

Да в целом не вижу информации по которой можно было бы понять что за ошибка и где :(

**Comment by ivan-s-1** [comment]
понял вас, проверю еще раз у себя в linux, просто странно что др. аналогичные сайты все работают
