### ISSUE TITLE
Question - migrate from 1.4 to 2.0

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1216]
Hello,

In EVO 1.4.9 we have in /manager/includes/config.inc.php line:

/**
 * Preventing the overwrite of the config when updating
 * Here you can
 *  - define manual constants, dedicated specifically for you project
 *  - inject composer
 *  - change predefined variables by the environment variables
 *  - ...
 *  - etc.
 *  - PROFIT!
 */

and here we can add all php file / helpers etc we would include like:

require_once __DIR__ . '/core/Helpers.php';

Where I can includes those files in EVO 2.0 ?

**Comment by Dmi3yy** [comment]
you can use: 
https://github.com/evolution-cms/evolution/blob/2.0.x/core/custom/define.php.example

for define manual constants 

and you can use packages for '/core/Helpers.php';

**Comment by modwebpl** [comment]
Awesome, thanks a lot!
