### ISSUE TITLE
Changing default MGR_DIR

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1217]
Hello,

How can I change in EVO 2 default /manager/ directory (for security reason) for example to /admp_access/ ?
In 1.4.9 we can change it in /assets/cache/siteManager.php

In define.php i set:

DEFINE('MODX_MANAGER_PATH', 'admp_access');

and change folder name from "manager" into "admp_access" but it still doesn't work.

**Comment by Dmi3yy** [comment]
<img width="160" alt="2345" src="https://user-images.githubusercontent.com/669491/66903449-2ce4a800-f00b-11e9-969f-34ba79418249.png">

**Comment by modwebpl** [comment]
God bless you :)
