### ISSUE TITLE
Check if multitv value is empty

### ISSUE THREAD

**Issue by Sybrenb** [evolution-cms/evolution#1218]
How can I check if a value in multitv is empty? This doesn't work:

Config:
```
'width' => array(
        'caption' => 'width',
        'type' => 'text'
    ),
```
rowTpl:
```
[[if? &is=`[+width+]:empty` &then=`value is empty` &else=`value is not empty`]]
```

**Comment by mehistaken** [comment]
If you've enabled filters in config, you can use phx syntax:
```
[+width:is=``:then=`value is empty`:else=`value is not empty`+]
```

**Comment by sashabeep** [comment]
@mehistaken don't try to do this NEVER anymore

**Comment by sashabeep** [comment]
@Sybrenb try 
```
[if? &is=`[+width+]:not:[]`
```
by default multiTv is array
BTW, you can use
```
&outerTpl=`@CODE: <my div>[+wrapper+]</div>`
```
to prevent empty block render if multitv is empty

**Comment by Dmi3yy** [comment]
`[[if? &is=`[+width+]:!=:[]:or:[+width+]:!=:` &then=`` &else=``]]`

**Comment by Sybrenb** [comment]
This doesn't work. Can someone please help me?

**Comment by sashabeep** [comment]
@Sybrenb please provide your code snippet. Have you tried to use wrapper for multitv call?
