### ISSUE TITLE
DocLister  tpl

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1219]
Hi

i don't know where else to put this question :). we are using DocLister on evo1.4.9 and all is well.

we have  tpl though for the doclister:

"
<li>
                    <div class="index-item">
                        <h3><a href="[~[+id+]~]">[+pagetitle+]</a></h3>
                        <a href="[~[+id+]~]"><img src="[+tv.page-right-aligned-image1+]" alt=""></a>
                        <p>[+introtext+]  ...</p>
                    </div>
 </li>
"

and we need to dynamically shorten the  "[+introtext+] "  text to 40 characters each time the tpl is called. can that be done dynamically in the tpl with some clever  text shortening  code? thanks in advance if you have any suggestions.

**Comment by Dmi3yy** [comment]
Better way use prepare + snippet summary

**Comment by user83743** [comment]
? How do I do that? We just use the introtext. If we call a snippet then it
does not run for each tpl call - it just runs the exact same for each tpl.
And that is not what we want

**Comment by Dmi3yy** [comment]
You use prepare param for DocLister where do what need with  data 


like here https://www.youtube.com/watch?v=bwbTJ4hLxjs&t=9s 
but use summary  not phpthumb )

**Comment by user83743** [comment]
Thanks. Is there any web page on the new eco site with some demo code?

**Comment by Dmi3yy** [comment]
After 02.11 i will do new video tutorial and new sample site

**Comment by user83743** [comment]
Good to hear. Thanks

**Comment by user83743** [comment]
I made sure i had this "Summary" snippet in place
https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/summary/snippet.summary.php
-
on my evo it was not there.

and then i called it with:

 <div class="index-item">
                        <h3><a href="[~[+id+]~]">[+pagetitle+]</a></h3>
                        <a href="[~[+id+]~]"><img
src="[+tv.page-right-aligned-image1+]" alt=""></a>
                        <p>[[summary? &text=[+introtext+] &len=70]]...</p>
</div>

and it works perfectly. i know you have all used "summary" , but we hadn't
:) .

**Comment by Pathologic** [comment]
There's no need to use prepare or summary snippet:
```
&tpl=`@CODE:<div class="index-item">
                        <h3><a href="[+url+]">[+pagetitle+]</a></h3>
                        <a href="[+url+]"><img
src="[+tv.page-right-aligned-image1+]" alt=""></a>
                        <p>[+summary+]</p>
</div>`
&summary=`notags,len:70` 
&dotSummary=`1`
&introField=``
&contentField=`introtext`
```

**Comment by user83743** [comment]
thnanks
