### ISSUE TITLE
Column not found error after upgrade 2.0.0 alpha to 2.0 RC 

### ISSUE THREAD

**Issue by gotthehot** [evolution-cms/evolution#1222]
After overwriting
/assets
/core
/manager
index.php

from 2.0 RC release bundle (downloaded zip) got the follwing in frontend:

> Undefined index: view
> « Evolution CMS Parse Error »
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'templatealias' in 'field list' (SQL: select `templatealias` from `modx_site_templates` where `modx_site_templates`.`id` = 5 limit 1)
> 

filename:

> /core/vendor/illuminate/database/Connection.php

PHP 7.3

**Comment by Dmi3yy** [comment]
Before update to 2.0 need update to last 1.4.* (1.4.9) 
we add in 1.4.9 this column

**Comment by gotthehot** [comment]
Just tried. Site already runs 2.0.0 alpha (since 2019/01) and after overwriting with 1.4.9 stops with Error 500. Can you describe step-by-step process for 2.0.0 alpha users to upgrade to 2.0 RC?

**Comment by gotthehot** [comment]
Job's done. Just finished successfull upgrade from 2.0.0 alpha to 2.0 RC using update manager from admin panel. Seems update managers solves compatibility issues and should be used instead of hardcore copy-via-ftp method. Now got the point. Sorry for distraction and thanks for the new life of Evo.

**Comment by Dmi3yy** [comment]
I think in manager we do only informer and update move to console, because in 2.0 you can't full update without composer

**Comment by gotthehot** [comment]
Site already runs 2.0, upgraded almost year ago from original Evo. Deal was upgrade to latest 2.0 RC.

**Comment by Dmi3yy** [comment]
You can just update files and run install 

or manually update table by this row: 
https://github.com/evolution-cms/evolution/blob/2.0.x/install/stubs/sql/setup.sql#L886
