### ISSUE TITLE
Weird error message: Error : syntax error, unexpected ''

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1226]
The snippets of my evolution CMS are running stable, however, I have found a weird error message today:

```
Error : syntax error, unexpected ''$geoversion = \'1.39\';
' (T_ENCAPSED_AND_WHITESPACE)
```
```
Error information |  
ErrorType[num] | PARSING ERROR[4]
File | /assets/cache/siteCache.idx.php
Line | 9683
Source | return $user[\'isloggedin\'];';$s['geoservant']='$geoversion = \'1.39\';


Backtrace
--
DocumentParser->{closure}()on line
```

```
Benchmarks |  
MySQL | 0.0055 s (0 Requests)
PHP | 0.0356 s
Total | 0.0411 s
Memory | 11.623161315918 mb
```

How could this happen? The snippets are intact.

Could this be a problem with the cache?

**Comment by Dmi3yy** [comment]
its problem not in core  Evo havent "geoservant"

**Comment by q2apro** [comment]
```
<?php
$geoversion = '1.39';
```

is the beginning of a snippet. The snippet has no mistakes, very simple code. It is unrelated.

From 10k visits, only once the visit above was thrown.

**Comment by q2apro** [comment]
Thanks for the feedback. Mhh, server says 38 % of 79 GB used. Maybe a memory issue or something else with the server. Thanks again 👍
