### ISSUE TITLE
Fatal Error: No hint path defined for [cache]

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1236]
Примеры шаблона на blade, вызывающие ошибку:
```blade
{!! $modx->runSnippet('DocLister',['parents' => '0', 'tpl' => '@B_CODE:<fieldset><h3>{{ $data["pagetitle"] }}</h3><br />{{ $data["introtext"] }}</fieldset>']) !!}
```
```blade
{{ $modx->tpl->parseChunk('@B_CODE:'.$chunk, ['param1' => 'value with "quote"']) }}
```

**Comment by sazanof** [comment]
После обновления с 2.0 RC  до 2.0 офф релиза тоже словил эту же ошибку также в доклистере

**Comment by sazanof** [comment]
![image](https://user-images.githubusercontent.com/3595562/68461727-f241ea00-021b-11ea-8963-9f94a380b364.png)
![image](https://user-images.githubusercontent.com/3595562/68461746-038af680-021c-11ea-87d7-17c1110e3323.png)
Вот еще скрины конструкций, которые вызывают данную ошибку

**Comment by Dmi3yy** [comment]
Спасибо пометил как важную исправим

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/commit/cdca6687cf3e868245798d673d65508ecd69b6b5

**Comment by modwebpl** [comment]
After "cdca668" fix I still get same error "No hint path defined for [cache] if I do:

`{!! $modx->runSnippet('DocLister', ['parents' => $data['id'], 'addWhereList' => 'hidemenu=0', 'orderBy' => 'menuindex ASC', 'tpl' => '@B_FILE:chunks/top_nav_tpl_list']) !!}`

views/chunks/top_nav_tpl_list.blade.php :

`{!! $modx->runSnippet('DocLister', ['orderBy' => 'menuindex ASC', 'parents' => $data['id'], 'tpl' => '@B_CODE:<a href="#">{{ $data["pagetitle"] }}</a>']) !!}`

it works if I change @B_CODE: to @B_FILE:

**Comment by sashabeep** [comment]
@modwebpl AFAIK you should provide
```php
'templatePath' => 'views/',
'templateExtension' => 'php'
```
in doclister call. Can you try with this parameters?

**Comment by modwebpl** [comment]
> @modwebpl AFAIK you should provide
> 
> ```
> 'templatePath' => 'views/',
> 'templateExtension' => 'php'
> ```
> 
> in doclister call. Can you try with this parameters?

Same error with those parameters:

```
{!! $modx->runSnippet('DocLister', ['parents' => $data['id'], 'orderBy' => 'menuindex ASC', 'templatePath' => 'views/',
'templateExtension' => 'php', 'tpl' => '@B_CODE:

@if ($data["isfolder"])
  <span class="up cur sub @if ($modx->documentObject["parent"] == $data["id"]) is_act @endif">{{ $data["pagetitle"] }}</span>
@else
  <a class="up cur @if ($modx->documentObject["parent"] == $data["id"]) is_act @endif" href="{{ $modx->makeUrl($data["id"]) }}">{{ $data["pagetitle"] }}</a>
@endif

']) !!}
```

only @B_FILE: works
