### ISSUE TITLE
Fatal Error: View [] not found.

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1237]
Из примера сайта на blade - вызов doclister с шаблоном из файла
```blade
{!! $modx->runSnippet('DocLister',[
  'parents' => '0', 
	'tpl' => '@B_FILE: partials/doc-tpl',
	'templatePath' => 'views',
	'templateExtension' => 'php'
	]) 
!!}
```

**Comment by sashabeep** [comment]
Справедливости ради, он и до обновления не выводил ничего вообще. Только через inline- шаблон работало

**Comment by Dmi3yy** [comment]
Темплейт паз view/ 

Нет слеша вот и путь кривой



https://github.com/evolution-cms/evolution/blob/2.0.x/assets/snippets/DocLister/lib/DLTemplate.class.php#L22

**Comment by sashabeep** [comment]
Решено
