### ISSUE TITLE
does not find icon EVO 2.0

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#1245]
does not find icon. #treeRoot a[data-private="1"] .icon::after

**Comment by sashabeep** [comment]
@cimt try to wipe the file /manager/media/style/default/css/styles.min.css
and re-upload /manager/media from release zip. Something was fixed after release

**Comment by cimt** [comment]
No, not working.
content: "\ f023" does not exist!

**Comment by Dmi3yy** [comment]
Like for me this icon no need: 
https://take.ms/sGPeB

and all work only this block display: none

**Comment by sashabeep** [comment]
@Dmi3yy он вроде говорил про защищенный ресурс. К ним иконки надо поправить

**Comment by Dmi3yy** [comment]
Да это тоже исправил жеж 
https://take.ms/n5mLZ

**Comment by cimt** [comment]
Yes, that's what I mean!
