### ISSUE TITLE
Иконки FA5 - Evo 1.4.10

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#1246]
![evo1](https://user-images.githubusercontent.com/6448120/68391060-c2410b00-0177-11ea-9854-e3c16e21997f.png)

**Comment by Dmi3yy** [comment]
Спасибо, поправим

**Comment by AndreyMyagkov** [comment]
**1) Фикс иконок в хлебных крошках:**

/manager/media/style/default/css/custom.css
Строка 197, добавьте жирность
ul.breadcrumbs span::after { margin-left: 2em; font-family: 'Font Awesome 5 Free'; content: "\f105"; **font-weight:900** }

**2) Фикс иконок в  менеджере картинок**
/manaer/media/browser/mcpuk/themes/evo/style.css

Строки 29-31 - добавить жирность

span.opened:before { display: inline-block; font-family: 'Font Awesome 5 Free'; content: "\f107"; width: 1.3em; font-size: 1.3rem; line-height: .8em; vertical-align: middle; color: #565656; **font-weight: 900**;}
span.closed:before { display: inline-block; font-family: 'Font Awesome 5 Free'; content: "\f105"; width: 1.3em; font-size: 1.3rem; line-height: .8em; vertical-align: middle; color: #565656; **font-weight: 900**;}
span.denied:before { display: inline-block; font-family: 'Font Awesome 5 Free'; content: "\f05e"; width: 1.3em; font-size: 1.3rem; line-height: .8em; vertical-align: middle; color: #565656; **font-weight: 900**;}

**Comment by Dmi3yy** [comment]
done
