### ISSUE TITLE
FormLister - Evo 1.4.10

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#1249]
Error : Uncaught ArgumentCountError: Too few arguments to function FormLister\Validator::length(), 1 passed and exactly 2 expected in assets/snippets/FormLister/lib/Validator.php:206
Stack trace:
#0 [internal function]: FormLister\Validator::length('')
#1 assets/snippets/FormLister/core/FormLister.abstract.php(639): call_user_func_array(Array, Array)
#2 assets/snippets/FormLister/core/FormLister.abstract.php(583): FormLister\Core->validate(Object(FormLister\Validator), Array, Array)
#3 assets/snippets/FormLister/core/controller/Form.php(56): FormLister\Core->validateForm()
#4 assets/snippets/FormLister/core/FormLister.abstract.php(434): FormLister\Form->validateForm()
#5 assets/snippets/FormLister/core/controller/Form.php(280): FormLister\Core->render()

**Comment by Pathologic** [comment]
Show the snippet call.

**Comment by kivamp** [comment]
Со старой версией (попробовал откатить) работает
```
[!FormLister?
&formid=`letterForm`
&rules=`{
	"date":{
		"length":0
	},
	"addressee":{
		"required":"Обязательно выберите адресата"
	},
	"fname":{
		"required":"Обязательно введите Фамилию"
	},
	"iname":{
		"required":"Обязательно введите Имя"
	},
	"email":{
		"required":"Обязательно введите email",
		"email":"Введите email правильно"
	},
	"phone":{
		"phone":"Введите телефон правильно"
	},
	"content":{
		"required":"Обязательно введите сообщение"
	}
}`
&captcha=`evoCaptcha`
&attachments=`attachment`
&fileRules=`{
	"attachment":{
    	"optional":"Не удалось загрузить файл",
    	"maxSize" : {
        	"params": 10240,
        	"message": "Размер файла не должен превышать 10 мб"
    	},
		"allowed":{
			"params": [ ["txt","doc","docx","rtf","xls","xlsx","pps","ppt","odt","ods","odp","pub","pdf","jpg","jpeg","bmp","png","tif","gif","pcx","mp3","wma","avi","mp4","mkv","wmv","mov","flv"] ],
			"message": "Недопустимый тип файла"
		}
	}
}`
&to=`i@am.com`
&subject=`Получено обращение через [(site_name)]`
&errorClass=` has-error`
&requiredClass=` has-warning`
&errorTpl=`@CODE:<span class="help-block">[+message+]</span>`
&messagesOuterTpl=`@CODE:<div class="alert alert-danger" role="alert">[+messages+]</div>`
&formTpl=`letter.form`
&reportTpl=`letter.report`
&successTpl=`letter.success`
&prepareAfterProcess=`letter.prepare`
&parseDocumentSource=`1`
!]
```

**Comment by Pathologic** [comment]
Что именно работает?

**Comment by kivamp** [comment]
Пригляделся внимательнее. Вопрос снимается.
(Хотя указанный код в пред. версиях FormLister в ошибку не валился. Так то "кривые" [указанные юзером] правила валидации надо обрабатывать, дабы PHP не ругался.)
