### ISSUE TITLE
DB-unrelated methods in DBAPI

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#125]
getXML, getHTMLGrid, replaceFullTableName - do we need them, @yama @Deesen @dmi3yy @64j ? I see no usage examples both in manager and assets.

**Comment by 64j** [comment]
@Pathologic 
only getXML and getHTMLGrid not used

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/blob/1.3.3/manager/includes/extenders/dbapi.mysqli.class.inc.php#L416-L428

```
$rs = $modx->db->select('*', '[+prefix+]site_content', 'parent=5');
```
```
$tbl_name = $modx->db->replaceFullTableName('my_table');
```

etXML and getHTMLGrid are unnecessary

**Comment by Pathologic** [comment]
replaceFullTableName duplicates getFullTableName almost completely. It should be declined deprecated.

**Comment by Deesen** [comment]
Not 100% sure but getXML and getHTMLGrid indeed seem useless.

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/commit/ac62798a3162f69eb7c2e9f64e896f09404a7ccf
