### ISSUE TITLE
Невозможно установить 2.0 через браузер

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1250]
php7.3
Стандартная установка через /install/index.php
![Снимок экрана 2019-11-08 в 13 08 33](https://user-images.githubusercontent.com/5689796/68468619-72bb1780-0229-11ea-9fa6-10382bb3d926.png)

На 2 шаге при вводе реквизитов БД
![Снимок экрана 2019-11-08 в 13 11 02](https://user-images.githubusercontent.com/5689796/68468663-88c8d800-0229-11ea-9363-0b62e97f5aa8.png)

Ссылка "проверить соединение" не нажимается вообще
При отключении баннерорезки (хотя чего бы ей там блокировать) вылезает
![Снимок экрана 2019-11-08 в 13 16 18](https://user-images.githubusercontent.com/5689796/68468878-f8d75e00-0229-11ea-8c9e-d4556d7e7fea.png)

Если подкинуть конфиг БД в /core/config/database/connections/default.php и начать установку заново, выбрав Обновить - то админка устанавливается без запроса юзера для админской части. А так как пользователя нет - то в таблицу пытается вставиться строка с you@example.com. Скриншота нет, извините

При выборе "Расширенное обновление"
соединение с БД происходит с теми данными, что есть в конфиге. Они не менялись. Далее есть возможность заполнить данные администраторского аккаунта и т.д.
![](https://d3dehtdmp2rwcw.cloudfront.net/ms_57655/0PXTrkEdwERPyWP8Gutc0uSfFe4Lrc/%25D0%25A1%25D0%25BD%25D0%25B8%25D0%25BC%25D0%25BE%25D0%25BA%2B%25D1%258D%25D0%25BA%25D1%2580%25D0%25B0%25D0%25BD%25D0%25B0%2B2019-11-08%2B%25D0%25B2%2B13.30.19.png?Expires=1573210800&Signature=ayL7rJCbUBePnwfMSyvcnjKss2wNs7NcZ1ogGjG9fbCX9djGFYK9NlOCNVZ8itevxvoabxpgNsFSJYRvX7r2sncrTVhLrfuJ1WYmY114~9AeFo3aSz5Q39OVjp0cx6U1tC-o2ezfas3rXJ2eOOWYp9B1N3XBZNxfv2WDozmT931GV1wqjKjQQDc3w3xpyDMH7gSrhdOfoN16nwTSvTM3rJP-w2NevkHQeh8Sa~~CTORGaH4idhNEs~USuH5Z6n4YbWaCztiufTwJC5CKzugu9M2iZXTzDUprgrowkaqU2DFZqGqkM8MB3apaXCVD-GGP2EzlFNM1-owi2A4vRxHJfA__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

Выбираю "Пример веб-сайта"
![](https://d3dehtdmp2rwcw.cloudfront.net/ms_57655/TxFyIqpKAubo6xy7e504W9qJJIY7PO/%25D0%25A1%25D0%25BD%25D0%25B8%25D0%25BC%25D0%25BE%25D0%25BA%2B%25D1%258D%25D0%25BA%25D1%2580%25D0%25B0%25D0%25BD%25D0%25B0%2B2019-11-08%2B%25D0%25B2%2B13.22.47.png?Expires=1573210800&Signature=H7Z76Vm15OXUYv3pMW7U9VlCPFNfo1S4HJUtWPPS9V0X~TpuPAHnU6QV58mS7XHZNJ1pWVceYRO3VGUbTwOgLg2vvpLUsOA6R8Be13kMUGvVTuYbFz8hR9wywWnqhWe3LboK2r~GW47nkx~yQtCZykR4uL0Hjxy1waua7U1EYDxoB-l08UuYQ43Pogqf80TH7hD4vFVAEHLL~PjVeYMnQebZrUvYrqiMhdGTMtnB5vLE7vLhSwOyk-JpxgZwOXWsNJjdnEE6WobX9EJei31jrSx0O1hffKDP8kIwum3XyqKu~w61qLOq0YMW88s8uz~3UdWEO8jbbJcgX18pMBSBxg__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

Но при переходе на предпоследний шаг
```
Проверка версии PHP: OK!
Проверка доступности iconv: OK!
Проверка настроек сессий: OK!
Проверка возможности записи в папки /assets/cache и /assets/cache/rss: OK!
Проверка возможности записи в файл /assets/cache/siteCache.idx.php: OK!
Проверка существования папок /assets/images, /assets/files, /assets/backup и /assets/.thumbs: OK!
Проверка возможности записи в папки /assets/images, /assets/files, /assets/backup и /assets/.thumbs: OK!
Проверка существования папки /assets/export: OK!
Проверка возможности записи в папку /assets/export: OK!
Проверка существования и возможности записи в файл /manager/includes/config.inc.php: OK!
Проверка соединения с базой данных: OK!
Проверка префикса таблиц `a20dev_`: ОШИБКА! - нет такого префикса таблиц в базе данных!
```
Потому что в базе, естественно, таких таблиц не было, она пустая

**Comment by sashabeep** [comment]
1-click installer тоже надо поправить, наверное

**Comment by Dmi3yy** [comment]
Перепроверил все работает.
Нашли пару причин при которых может работать не коректно: 
- Addblock 
- кеш старых параметров
