### ISSUE TITLE
After update to Evo 2.0: mysql STRICT_TRANS_TABLES breaks website when not logged in in backend

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1253]
Evo 2.0
PHP 7.3.11

After Upgrade from 1.4.10 (everything works fine) I get this error WHEN being logged out of backend. Being logged in in backend eveything works:

> Plugin - PHx / SQLSTATE[22001]: String data, right
E[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1

```

Backtrace
--
EvolutionCMS\Core->executeParser()index.php on line 130
EvolutionCMS\Core->prepareResponse()core/src/Core.php on line 2786
EvolutionCMS\Core->parseDocumentSource(string $var1)core/src/Core.php on line 2926
EvolutionCMS\Core->invokeEvent('OnParseDocument')core/src/Core.php on line 2645
EvolutionCMS\Core->evalPlugin(string $var1, array $var2)core/src/Core.php on line 5699
eval()core/src/Core.php on line 1806
EvolutionCMS\Legacy\Phx->OnParseDocument()core/src/Core.php(1806) : eval()'d code on line 9
EvolutionCMS\Legacy\Phx->Parse(string $var1)core/src/Legacy/Phx.php on line 74
EvolutionCMS\Legacy\Phx->Parse(string $var1)core/src/Legacy/Phx.php on line 109
EvolutionCMS\Legacy\Phx->Parse(string $var1)core/src/Legacy/Phx.php on line 109
EvolutionCMS\Legacy\Phx->Parse(string $var1)core/src/Legacy/Phx.php on line 109
EvolutionCMS\Legacy\Phx->Parse(string $var1)core/src/Legacy/Phx.php on line 109
EvolutionCMS\Core->logEvent(12, 1, string $var3, 'PHx 2.2.0')core/src/Legacy/Phx.php on line 113
AgelxNash\Modx\Evo\Database\AbstractDatabase->insert(array $var1, string $var2)core/src/Core.php on line 3615
EvolutionCMS\Database->query(string $var1)core/vendor/agelxnash/modx-evo-database/src/AbstractDatabase.php on line 386

```
Being logged out this error brings up a white page with the word Error. Being logged in everything is working as expected. In 1.4.10 everything is fine – logged in and out.

Any suggestions what is happening and how to solve this issue?

**Comment by leonie12** [comment]
It seems that it was an issue with my installation of PHP 7.3.11. After reinstalling this PHP version it works now :-) .

**Comment by leonie12** [comment]
Error on my side: It works fine with PHP 7.3.0 and 7.2.12.
The issue happens with PHP 7.3.11 and only when being logged out of manager.

**Comment by Dmi3yy** [comment]
PHx -  not support many years. Recommend turn off and replace to snippet IF or better to BLADE )
