### ISSUE TITLE
No site tree in Firefox after update

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#1254]
After an update to version 1.4.9 or 1.4.10, the site tree is no longer displayed in Firefox. Everything ok in Chrome? Does anyone have any idea why?
Nach einem Update auf Version 1.4.9 oder 1.4.10 wird der Site tree im Firefox nicht mehr angezeigt. In Chrome ist alles ok? Hat jemand eine Idee, woran das liegen kann?

**Comment by modwebpl** [comment]
Try reloging into admin panel in incognito Firefox tab.

**Comment by risingisland** [comment]
Via Dmi3yy in Slack:

> If you have problem with icons after update to 1.4.10
> - delete 'manager/media/style/default/css/styles.min.css'
> - re-save settings in manager panel

**Comment by webkarli** [comment]
Thanks for the answers. I wasn't on the site with Firefox for a few days.  I could work with Chrome without any problems. To my surprise, everything now works in Firefox, including version 1.4.10. When I opened the thread, this was not the case. I had tried a lot without success.
