### ISSUE TITLE
2.0 New install - custom manager theme doesn't show

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1256]
Have selected a custom theme for the manager but the head still uses "default" and not "custom".

`<link rel="stylesheet" type="text/css" href="media/style/default/css/styles.min.css?v=0">`

**Comment by Nicola1971** [comment]
Same for me. Custom themes do not work in current Evo2.0.
Theme folder does not change in header styles url 
` <link rel="stylesheet" type="text/css" href="{{ ManagerTheme::css() }}"/>`

and color picker url

`<script src="{{ ManagerTheme::getThemeUrl() }}/js/color.switcher.js" type="text/javascript"></script>`

**Comment by fourroses666** [comment]
Configuration page doesn't change anything :( 

![huh](https://user-images.githubusercontent.com/523389/69095080-e80cc080-0a51-11ea-88ac-f4f76655fe2e.jpg)


I also think modifying the manager theme is way too hard to do. :(
All I see is a minifyed CSS file called style.min.css
So many different files are being used.

**Comment by fourroses666** [comment]
Same as: https://github.com/evolution-cms/evolution/issues/1285
