### ISSUE TITLE
Warning "Resource is already using the URL alias 'xyz'.

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1257]
I am using the latest Evolution 2.0 release: https://github.com/evolution-cms/evolution/tree/2.0

Every time I am saving a resource I get:

![screenshot 2019-11-12](https://user-images.githubusercontent.com/6764548/68651762-b6b36280-0530-11ea-8334-902b48c7986b.png)

**Comment by Dmi3yy** [comment]
You cant use same alias for different documents. 

Or on all site or in one folder. You can set this the settings

**Comment by q2apro** [comment]
Well, I know. I am saying that this happens with every new resource. Having **different aliases**. 

Otherwise I would not report it as a bug ...

**Comment by Dmi3yy** [comment]
Can you send access i check

**Comment by q2apro** [comment]
Can I send you the access by email?

**Comment by q2apro** [comment]
The update to "Evolution CMS version 2.0.1" solved it 👍
