### ISSUE TITLE
Missing mini navigation bar in side tree (Evo 2.0)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1258]
Latest EVO release: https://github.com/evolution-cms/evolution/tree/2.0

Bug: Missing mini navigation bar in side tree!

Before (Evo 1.x):

![image](https://user-images.githubusercontent.com/6764548/68651930-16aa0900-0531-11ea-86d2-3e0198df5aea.png)

Now with Evo 2.0:

![screenshot 2019-11-12 (1)](https://user-images.githubusercontent.com/6764548/68651894-0560fc80-0531-11ea-9784-54a6f94d9448.png)

**Comment by q2apro** [comment]
Seems that the config of the Plugin "ElementsInTree" was missing.

Fix:

1. Go to plugin options, under tab "Properties"

2. Paste:

```
{
  "adminRoleOnly": [
    {
      "label": "Administrators only",
      "type": "list",
      "value": "yes",
      "options": "yes,no",
      "default": "yes",
      "desc": ""
    }
  ],
  "treeButtonsInTab": [
    {
      "label": "Tree buttons in tab",
      "type": "list",
      "value": "yes",
      "options": "yes,no",
      "default": "yes",
      "desc": ""
    }
  ]
}
```

3. Go to tab "System Events" and tick:

![screencapture-2019-11-12-10_06_20](https://user-images.githubusercontent.com/6764548/68653307-1fe8a500-0534-11ea-9cc1-b5c5c7151c1a.png)

**Comment by fourroses666** [comment]
"Add default configuration" button can be used too I think.

**Comment by Dmi3yy** [comment]
need only turn on Plugin by default its turn off
