### ISSUE TITLE
Dashboard not displaying on 2.0

### ISSUE THREAD

**Issue by Cipa** [evolution-cms/evolution#1267]
<img width="1033" alt="Screen Shot 2019-11-14 at 5 46 31 PM" src="https://user-images.githubusercontent.com/293377/68910500-d1d7cb00-0706-11ea-838c-e8befe65ac21.png">

The problem might be with the use of ->view in core/src/ManagerTheme.php on line 393.

Backtrace
--
Illuminate\Support\Facades\Facade::__callStatic('handle', array $var2)manager/index.php on line 205
EvolutionCMS\ManagerTheme->handle(2)core/vendor/illuminate/support/Facades/Facade.php on line 239
Illuminate\View\View->render()core/src/ManagerTheme.php on line 393
Illuminate\View\View->renderContents()core/vendor/illuminate/view/View.php on line 91
Illuminate\View\View->getContents()core/vendor/illuminate/view/View.php on line 126
Illuminate\View\Engines\CompilerEngine->get(string $var1, array $var2)core/vendor/illuminate/view/View.php on line 143
Illuminate\View\Engines\PhpEngine->evaluatePath(string $var1, array $var2)core/vendor/illuminate/view/Engines/CompilerEngine.php on line 59
include(string $var1)core/vendor/illuminate/view/Engines/PhpEngine.php on line 43
EvolutionCMS\Core->getChunk(string $var1)core/storage/blade/cbea8ee3fc774a40c6e07bad70081e50955a72ee.php on line 32
EvolutionCMS\Core->__get('tpl')core/src/Core.php on line 4445
trigger_error(string $var1, 16384)core/src/Core.php on line 247

**Comment by Dmi3yy** [comment]
Can't reproduce
