### ISSUE TITLE
Evolution CMS 2.0 doesn't work with MariaDB (mysqli driver) after upgrade from 1.4.10

### ISSUE THREAD

**Issue by php-force** [evolution-cms/evolution#1268]
Have tried upgrading to Evo CMS 2.0 and it doesn't work keep getting Server error 500. Tested with MariaDB 10.1 and 10.4. It seems that mysqli driver not working out of the box.

Have found that composer require shakahl/laravel-eloquent-mysqli package might solve the problem however there seems to be conflict with other packages message below:
Your requirements could not be resolved to an installable set of packages.
//===================================================
  Problem 1
    - Can only install one of: illuminate/support[v6.0.4, 5.4.x-dev].
    - Can only install one of: illuminate/support[5.4.x-dev, v6.0.4].
    - Can only install one of: illuminate/support[5.4.x-dev, v6.0.4].
    - shakahl/laravel-eloquent-mysqli dev-master requires illuminate/support 5.4.* -> satisfiable by illuminate/support[5.4.x-dev].
    - Installation request for shakahl/laravel-eloquent-mysqli dev-master -> satisfiable by shakahl/laravel-eloquent-mysqli[dev-master].
    - Installation request for illuminate/support (locked at v6.0.4, required as 6.0.*) -> satisfiable by illuminate/support[v6.0.4].

Installation failed, reverting ./composer.json to its original content.
//==================================================================

**Comment by Cipa** [comment]
I have it working with mariadb-10.4, installed both 2.0.0 and 2.0.1 without issues.
Maybe try the cli install or some other method, maybe update composer

**Comment by edvukass** [comment]
> I have it working with mariadb-10.4, installed both 2.0.0 and 2.0.1 without issues.
> Maybe try the cli install or some other method, maybe update composer

Can you tell what environment you have used for installation? windows, linux...?, 
which PHP version ? 
What PHP extensions you have got enabled on your system? 
Was that a fresh install or existing application upgrade? 
Database config file example? 

I have tried upgraded my existing application following the video tutorial online and If i try to access a web page i get error 500 with no details in the error_log. From what i remember  it was impossible to login to manager as well. The Captcha image on manager Login page wouldn't display and even if i disable captcha setting directly in the database it would still complain about incorrect login details.. tried clearing cache ... disabling plugins etc.. nothing worked for me.
