### ISSUE TITLE
dd on collections not working, VarDumper missing

### ISSUE THREAD

**Issue by Cipa** [evolution-cms/evolution#1269]
Example:

In a snippet put:

```
$collection = collect(['John Doe', 'Jane Doe']);
$collection->dd();
```

You will get this error 

« Evolution CMS Parse Error »
Class 'Symfony\Component\VarDumper\VarDumper' not found

Running 
composer require symfony/var-dumper
inside the core folder seems to have fixed the issue

**Comment by Dmi3yy** [comment]
dd() not work without var-dumper 
try dump()

**Comment by Cipa** [comment]
dump works but you still have to put an exit() after
After doing some research seems dumpe() is the Tracy way of doing that.
Also bdump() will add the dump to the tracy bar
