### ISSUE TITLE
childrens should be children 

### ISSUE THREAD

**Issue by Cipa** [evolution-cms/evolution#1271]
<img width="444" alt="Screen Shot 2019-11-15 at 8 04 55 PM" src="https://user-images.githubusercontent.com/293377/68987871-42541a00-07e3-11ea-91bf-214534ed6a45.png">
This should be an easy fix

**Comment by Dmi3yy** [comment]
Did not understand what was the mistake :(

**Comment by Cipa** [comment]
"Children" is already plural. Child is singular.

Code should be foreach($children as $child) so no S at the end

**Comment by Dmi3yy** [comment]
yep :)   thanks
