### ISSUE TITLE
Lang issue &amp;

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1272]
https://github.com/evolution-cms/evolution/blob/2.0.x/manager/includes/lang/nederlands-utf8.inc.php#L957

$_lang["settings_ui"] = 'Interface &amp; mogelijkheden';

<img width="791" alt="Schermafbeelding 2019-11-16 om 12 36 41" src="https://user-images.githubusercontent.com/523389/68992657-89d3b800-086e-11ea-8cb4-09ce5ec51aca.png">

**Comment by Dmi3yy** [comment]
done
