### ISSUE TITLE
Странные отступы перед (id)

### ISSUE THREAD

**Issue by Ruslan-Aleev** [evolution-cms/evolution#1282]
1) У элементов, перед (id), есть странный (как будто двойной) отступ:

![tpl](https://user-images.githubusercontent.com/12523676/69091904-b2250780-0a64-11ea-8eab-7fb744772406.png)

Хотя для ресурсов такого не наблюдается:

![res](https://user-images.githubusercontent.com/12523676/69091908-b5b88e80-0a64-11ea-9b62-cba4972a95a3.png)

2) Если навести на вкладку ресурса/элемента, то в title вкладки вообще нет отступа:

![res_2](https://user-images.githubusercontent.com/12523676/69092116-22cc2400-0a65-11ea-8e3a-6b2f42426653.png)

В общем смотрится странновато :)

**Comment by Dmi3yy** [comment]
В шаблоне поправил а вот в документе надо все на блейд для начала пересобрать
