### ISSUE TITLE
2.0 Manager theme selection is not working

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#1285]
Evo settings are not ready when ManagerTheme object is initialized: https://github.com/evolution-cms/evolution/blob/2.0.x/core/src/Providers/ManagerThemeServiceProvider.php#L24 So $theme variable value is always "default".

**Comment by Dmi3yy** [comment]
fixed by https://github.com/evolution-cms/evolution/commit/b79cb2a13b2c8a1d56abc8fedc90697478a115c3
