### ISSUE TITLE
Manage Files Chrome Browser - The XSS Auditor blocked access

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#129]
If I edit files using 'Manage Files' then for some files I get a 'something went wrong' message when attempting to save the file.
The Chrome log indicates: The XSS Auditor blocked access.

E.g. in Chrome, from 'Manage Files' edit the file manager/actions/access_permissions.dynamic.php and then try and save.

**Comment by 64j** [comment]
@bossloper 
Chrome found an unusual code on this page and blocked it to protect your data (for example, passwords, as well as phone numbers and bank cards)

**Comment by bossloper** [comment]
Yes but it happens for many manager files... most in the files in actions folder for example.
Do we need sometihng like this adding?

header("X-XSS-Protection: 0");

**Comment by 64j** [comment]
Yes, there is a problem.
Do not close isssue
