### ISSUE TITLE
Ошибка при восстановлении резервной копии

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#1291]
> SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

**Comment by Dmi3yy** [comment]
Попробовал и создать востановить и кастомный код выполнить везде гладко :( 
https://take.ms/vRWMS

можно чутка больше деталей
