### ISSUE TITLE
TinyMCE4 does not work in chunks

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [evolution-cms/evolution#1292]
When i try to select TinyMCE editor in a chunk, it does not work

![error](https://user-images.githubusercontent.com/16403917/69260067-524b6f80-0bd0-11ea-8fdd-6ef3fd29b037.jpg)

**Comment by Ser1ous** [comment]
Plugin TinyMCE4 is enabled? And this event's is checked?https://monosnap.com/file/2RlxIf8J61Q7GqlfQ01bjPkgED5icm?

**Comment by iWatchYouFromAfar** [comment]
> Plugin TinyMCE4 is enabled? And this event's is checked?https://monosnap.com/file/2RlxIf8J61Q7GqlfQ01bjPkgED5icm?

Yeap, here it is:

![2](https://user-images.githubusercontent.com/16403917/71562528-ad576880-2a92-11ea-9da7-4884ba3bef79.jpg)

And gif example:

![123](https://user-images.githubusercontent.com/16403917/71562530-b5afa380-2a92-11ea-8851-226a08e99c09.gif)

TinyMCE does not apply to chunk content.
