### ISSUE TITLE
TinyMCE4 с конфига ушла?

### ISSUE THREAD

**Issue by xrustit** [evolution-cms/evolution#1297]
TinyMCE4 в конфиге пропала и соответственно не работает, хотя файлы и присутствуют. Вроде как во второй ветке корректировку вносили. 
CodeMirror тоже не работает в чанках, шаблонах и др.

**Comment by Ruslan-Aleev** [comment]
TinyMCE4 отображается в разделе "Конфигурация", как и прежде. Стоит последняя 2.x:

![tiny](https://user-images.githubusercontent.com/12523676/69500832-1e49b480-0f18-11ea-8bc4-e32cbe785e4b.png)

Или вы про другое?

**Comment by xrustit** [comment]
Я вроде в ветке с 1.4.10 писал. Речь об этой версии

**Comment by Dmi3yy** [comment]
Проверьте настройки плагина TinyMCE и CodeMirror 
скорей всего там что то не так потому и не работает

**Comment by xrustit** [comment]
С нуля поставленная система не имеет настроек TinyMCE  в конфигурации. Хотя в версии 1.4.9 все норма. Плагины TinyMCE и CodeMirror запущены и работают, файлы все есть.

![Снимок](https://user-images.githubusercontent.com/32340712/69752302-b17e2680-1172-11ea-962e-5150da384b51.PNG)

**Comment by bezalkogoln1y-coder** [comment]
Мне помогло тут авто выставление системных событий у плагинов.
Почему то из коробки там нет галочек...
