### ISSUE TITLE
EVO Не обновляется если установлен evobalel

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#13]
Здравствуйте! Попробовал обновить сайт MODX EVO Custom 1.2.1-d9.1.7 -> MODX Evolution 1.3.0b (Jul 10, 2017)
Получил редирект на 404 страницу при установленном плагине evobabel. Возможно это не баг, но решил сюда написать.

**Comment by bagi091** [comment]
Только что обновился с теми же условиями, но у меня все прошло хорошо и сайт продолжает работать как надо.
