### ISSUE TITLE
1.4.10 - Не видны иконки в разделе Элементы: Снипеты, Плагины, Общий просмотр

### ISSUE THREAD

**Issue by SerNeo** [evolution-cms/evolution#1303]
После обновления до 1.4.10 в разделе 
Элементы: Сниппеты, Плагины, Общий просмотр
Не показываются иконки. Фаил стилей в /manager удалял - не помогло

![](https://i.imgur.com/rs14esP.jpg)

А так же в **multiTV**
![](http://dl3.joxi.net/drive/2019/11/27/0003/0955/222139/39/56a7e005f8.jpg)

**Comment by Dmi3yy** [comment]
В мультитв надо обновить мультитв остальное поправили уже скоро будет 1.4.11 с фиксами этими
