### ISSUE TITLE
CMS 2.0.1 ajax usage

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#1308]
Hi All,

I've been slowly building up to migrating from 1.4.10 to 2.0.1.  Whilst I have it all setup and working I'm having trouble getting anything I've written which uses ajax to work.

I'm getting 500 internal server error.  I've checked my code and it seems to fail when I call $modx->db->connect();

Here's my code:

```<?php
// Set the groups allowed to access this ajax program
$webgroups = "Employees, Customers";

define('MODX_API_MODE', true);
define('AS_SPATH', 'assets/snippets/test/');

include_once($_SERVER["DOCUMENT_ROOT"].'/modx/index.php');
include_once($_SERVER["DOCUMENT_ROOT"].'/modx/assets/cache/siteManager.php');
require_once($_SERVER["DOCUMENT_ROOT"].'/modx/manager/includes/protect.inc.php');

$modx->db->connect();

//if (empty ($modx->config)) {
    $modx->getSettings();
//}

// Crude way of restricting access.  This is not using the web groups permission but should
// Die if we are not logged in.  
// Prevents spamming to get email addresses or errors!

if (!$modx->getLoginUserID()) { die("not allowed!"); }
if (!$modx->isMemberOfWebGroup(explode(',', $webgroups))) {	die("not in approved group!"); }

$modx->invokeEvent("OnWebPageInit");
```
Is there a different way to handle ajax calls in v2.0?

Thanks,

**Comment by Dmi3yy** [comment]
about update:
https://www.youtube.com/watch?v=jbhrTlcjqQ4&list=PLKTHZGrYLdtoMegu0vG1Isek4_HsZPtZf&index=3

about ajax from file: 
http://modx.im/blog/triks/2103.html
this no need: 
```
include_once($_SERVER["DOCUMENT_ROOT"].'/modx/assets/cache/siteManager.php');
require_once($_SERVER["DOCUMENT_ROOT"].'/modx/manager/includes/protect.inc.php');
```

**Comment by BBloke** [comment]
Ah.  Ignore my post.  Total brain fart on my end. Forgot to change a directory name.  Thank you for the heads up on the other two lines.

Cheers Demi3yy
