### ISSUE TITLE
Множественные вопросы от браузера на Webkit при сабмите форм админки

### ISSUE THREAD

**Issue by Ronef** [evolution-cms/evolution#1309]
При любом сабмите формы и при переходе по ссылкам внутри CMS, браузер выдаёт 2 предупреждения. Нагляднее на видео:

![2019 12 06, 12 39 50](https://user-images.githubusercontent.com/1333424/70313065-f286d280-1825-11ea-92f0-8d156e6ee1ff.gif)

Такое стало происходить буквально на днях, с последней обновой браузеров на Webkit. В FireFox всё хорошо работает, как и раньше.

Мне пожаловались несколько человек, не связанных между собой, так что похоже на общую проблему.

* Windows 10.
* Yandex.Browser | Opera (в Chrome и Safari не тестил, но там, как пить дать, то же самое будет).

**Comment by Dmi3yy** [comment]
fixed in 1.4.10
