### ISSUE TITLE
[ManagerManager] Troubles with sections in new manager theme

### ISSUE THREAD

**Issue by Typodin** [evolution-cms/evolution#131]
При создании секции ширина ячеек распределяется равномерно, что не соответствует общим стилям: http://joxi.ru/12MBYoESMxKelA

Для лечения в файл /manager/media/style/default/style.css добавил в длинный список классов строки 189 еще один:

`.sectionBody > table > tr > td:first-child, `

**Comment by 64j** [comment]
а каким образом так разделили страницу, написали Шапка сайта ?

**Comment by Typodin** [comment]
Существует mm_ddCreateSection и много других прикольных штук которые стоят из коробки.

**Comment by 64j** [comment]
боюсь это не надолго))
и если ставите сторонние компоненты, возможно их разработчики заинтересованны в своих решениях и обязательно исправят в будущем эти недочёты.

Можете попробовать это решение для категорий и для оформления документа в админке.

**Comment by Typodin** [comment]
Ненадолго что - дополнения к плагину managermanager от DivanDesign которые там есть почти столько же сколько Evo существует?

**Comment by 64j** [comment]
@Typodin 
Эти внедрения в системе появились относительно недавно, и не с появлением Modx evo.
В EVO 1.3 будут и в дальнейшем появляться новые возможности, не имеющие обратной совместимости.

**Comment by Typodin** [comment]
Без этих внедрений система потеряет часть своего функционала, причем очень востребованного. Но если вы не в курсе что это, то о чем вообще говорить?

**Comment by Pathologic** [comment]
Правильнее было бы, как уже Дима говорил, подождать пока стабилизируется нынешняя тема, потом под нее внести правки в ManagerManager.

**Comment by Typodin** [comment]
Макс, как показывает практика лучше все эти мелочи сразу собирать в кучу, иначе потом до них руки не дойдут никогда.

**Comment by Pathologic** [comment]
Здесь дело такое, MM все-таки дополнение, поэтому логичнее чтобы дополнение подстраивалось под тему, а не тема под него.

**Comment by Typodin** [comment]
У разработчиков руки могут и не дойти до этих дополнений, а они дают такие возможности, которые я не встречал в других системах даже близко. Я протестирую их и соберу все правки в кучу под эту тему, пока опять новую не ввели.

**Comment by 64j** [comment]
@Typodin 
Было бы здорово, если вы соберёте чаще всего используемые плагины ММ.

**Comment by Typodin** [comment]
Плагин вообще один, все остальное - это виджеты. Большую часть их разработали в DivanDesign и бесплатно передали для общего пользования. Виджетов больше 30 идет "из коробки", я лично активно использую не менее половины, но какой смысл собирать самые активные?

**Comment by 64j** [comment]
@Typodin 
Чтобы разработчики знали, что не работает или работает

**Comment by Typodin** [comment]
Мне проще будет самому поправить и прислать сюда для внесения изменений.

**Comment by 64j** [comment]
@Typodin 
А почему не разработчикам ММ?

**Comment by Typodin** [comment]
Мне быстрее так.

**Comment by 64j** [comment]
@Typodin 
Вы можете поправить у себя локально, либо создать свою собственную тему оформления, и тогда всё будет отображаться как вам нужно.

**Comment by Typodin** [comment]
Да при чем тут как мне нужно или нет? Если бы я так делал то и не создавал бы никакого багрепорта. Тему закроем, я вообще не знаю кто вы такой, с Димой буду решать.
