### ISSUE TITLE
Incorrect server time on Evo 2.0

### ISSUE THREAD

**Issue by Dmi3yy** [evolution-cms/evolution#1310]
создал файл core\custom\config\app\timezone.php

содержание:
<?php
return 'Asia/Krasnoyarsk';

в адмнике указал часовой пояс 0

**Comment by MarkTWIC** [comment]
I don't know if this is the same issue but in Evolution 1.4.11 the my template variable for when an article was written has suddenly changed and now is a few hours ahead (it's like the server offset is applied twice actually). The variable is saved as Unixtime when I write the article. Has something changed?

**Comment by Rom-ON** [comment]
> создал файл core \ custom \ config \ app \ timezone.php


Добрый день, Дмитрий! В архиве версии Evolution CMS 2.0.3 данный файл отсутствует. Подскажите пожалуйста откуда его можно скачать?

**Comment by Dmi3yy** [comment]
Его можно создать самому там банально 
Return timezone

**Comment by Rom-ON** [comment]
Прошу прощения, но я в php не силён... -(

**Comment by Rom-ON** [comment]
Этот код верен?
<?php 
$date = new DateTime();
$date->setTimezone(new DateTimeZone(ini_get('date.timezone')));?>

**Comment by Rom-ON** [comment]
> Его можно создать самому там банально
> Return timezone

Прошу прощения, в php не силён... -(

Этот код верен?

$date = new DateTime();
$date->setTimezone(new DateTimeZone(ini_get('date.timezone')));

**Comment by Dmi3yy** [comment]
Все проще: 

` <?php return 'Etc/GMT-7';`

**Comment by Rom-ON** [comment]
> Все проще:
> 
> ` <?php return 'Etc/GMT-7';`

Благодарствую 👍
