### ISSUE TITLE
Ошибка при отправке комментария

### ISSUE THREAD

**Issue by yuri25** [evolution-cms/evolution#1316]
При попытке отправить комментарий
Methods with the same name as their class will not be constructors in a future
 version of PHP; CChunkie has a deprecated constructor
« Evolution CMS Parse Error »
Class 'PHPMailer' not found

Жалуется в этом файле assets/snippets/jot/jot.class.inc.php
На строку 617
В ней написано
$mail = new PHPMailer();

А перед этим в 616 строке
include_once MODX_MANAGER_PATH . "includes/controls/class.phpmailer.php";

Но по этому пути никакого class.phpmailer.php нету. Кто знает где взять и почему его там нет?

**Comment by Dmi3yy** [comment]
1 есть репозиторий джот и писать нужно туда 
2 надо переписать на то как сделано в еформ формлистер шопкипер использовать апи модх 

Или как минимум глянуть куда переехал файлик он +- там же просто называется по другому
