### ISSUE TITLE
Duplicated Plugin events after upgrade to 1.4.10 

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#1317]
I have a very strange issue in one of my sites:
After upgrade from 1.4.9 to 1.4.10 all plugin events are duplicated
![screenshot-www sportivamenteasd it-2019 12 13-10_53_14](https://user-images.githubusercontent.com/7342798/70792154-e4423480-1d98-11ea-8809-8422fa21eea2.png)

moreover all the plugins are executed twice, so I have multiple fields of codemirror or tinymce, duplicated  tabs of manager manager and, obviously, lots of js errors.

- Overwriting manager folder with 1.4.9 files does not solve.
- downgrade to 1.4.9 (manager folder and db datas) solve the issue

**Comment by Dmi3yy** [comment]
I fix it soon

**Comment by Nicola1971** [comment]
it's weird, because it's not the first site I update from 1.4.9 to 1.4.10, on the same server and I've never had this problem.

**Comment by Pathologic** [comment]
Try to install current 1.4 branch.
