### ISSUE TITLE
КСFinder - перестали отображаться иконки "уголочков", начиная с 1.4.10

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#1319]
После обновления на 1.4.10 выглядит вот так:
(при этом в самом дереве ресурсов иконки нормальные)

**Comment by Dreamer0x01** [comment]
![Screenshot_2019-12-15 Русский промышленник- (EVO CMS Manager)](https://user-images.githubusercontent.com/12978365/70862572-1f866400-1f4f-11ea-84f4-bb3b16735ba8.png)

**Comment by risingisland** [comment]
Also, icon to create new sub-folders...
![My Evolution Site   EVO CMS Manager ](https://user-images.githubusercontent.com/6113504/71591534-a5e09f80-2b24-11ea-84d6-22a9e8422990.png)

**Comment by risingisland** [comment]
I believe that this has been fixed via #https://github.com/evolution-cms/evolution/commit/787bf71c499fe563cd6c41ba2c12cfe259986b4c
