### ISSUE TITLE
How long will version 1.4.x be developed?

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#1322]
How long will version 1.4.x be developed?
For an answer I would be grateful.

**Comment by Dmi3yy** [comment]
1.4 will support ( bug fix and security issues) 
Until 2022 

But will not active develop

1.4 recommended for old project were need only stable work, and not active develop. 

For new project recommend 2.0 branch

**Comment by cimt** [comment]
Hello Dmi3yy, thanks for the answer.
OK. I would like to work with the 2.0 but unfortunately I don't get an answer to my questions
here: https://github.com/evolution-cms/evolution/issues/1305#issuecomment-565111293

Please... can you answer me how you develop locally and upload the files to the web server without "composer".
**thanks**

**Comment by Dmi3yy** [comment]
I work like in video: 
https://www.youtube.com/watch?v=xQ_aqYpS0Cc&list=PLKTHZGrYLdtoMegu0vG1Isek4_HsZPtZf

soon i will write manual how work with Docker, i think its better type of local server
