### ISSUE TITLE
[TransAlias] Adding # to URL

### ISSUE THREAD

**Issue by 64j** [evolution-cms/evolution#133]
Do you need tuning in the plugin, to select URL with # ?

![image](https://user-images.githubusercontent.com/4653189/28753274-f0e4c422-753a-11e7-99f6-34bcb2e367b1.png)

**Comment by Pathologic** [comment]
It would be better to create one more field to enter allowed characters (like in revo), then add an option to "Restict alias to" to use this field.

**Comment by 64j** [comment]
@Pathologic 
If my memory serves me, a long time ago, that's exactly what happened.

Если мне не изменяет память, то давным давно, именно так и было
