### ISSUE TITLE
Eform error message on 2.0

### ISSUE THREAD

**Issue by Sybrenb** [evolution-cms/evolution#1333]
I've just updated my site to 2.0 and it works great!

There is only one problem.. When I try to use eform (click on the send button on the form) I'm getting the following parse error:

Error : The EvolutionCMS\Core::sanitize_gpc() method is undefined 
(file: ...../core/src/Core.php)

Is there a way to fix this?

Formlister also doesn't seem to work..

**Comment by Neoziox** [comment]
Same issue for me. Any clue to fix it?

**Comment by Neoziox** [comment]
In the `eform.inc.php` file, I replace line 174:
`$modx->sanitize_gpc($fields);`
by:
`modx_sanitize_gpc($fields);`
