### ISSUE TITLE
Phx from DocLister logging system events

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#1336]
I've just upgraded from 1.4.10 to 2.0.1.  Everything went well after moving things away from Ditto and WebLoginPE.

I've noticed there are a lot of PHX 2.2.0 logs in system events.  I have PHx installed, ver 2.2.2 which is set to not log.  I've checked it out and it appears the logs are coming from DLphx.class.inc.php as this is version 2.2.0.

How do I stop it from logging events without having to comment the line out?

Thanks,
BBloke

**Comment by sashabeep** [comment]
Please do not use PHX and turn off system filters.
DLPhx is independent class to build phx-like conditions inside of doclister templates.

For any simple logic use built-in blade syntax(if you decide to use blade templates) or IF snippet

**Comment by BBloke** [comment]
@sashabeep Thank you for replying.  It's not the plugin version which is the issue.  It's the addin DLphx which is creating the System Event.

I did try to find the "enable_filters" option in configuration but alas I cannot find it.

I will change my PHX calls over to IF so I can disable PHx plugin.

**Comment by BBloke** [comment]
I think I've rid my template of all the PHX code in favour of IF. Everything looks like it's ok now. 

Thanks
