### ISSUE TITLE
keeping jQuery show/hide state on submitting efrom

### ISSUE THREAD

**Issue by Tourist4Life** [evolution-cms/evolution#1339]
I have a form that is hidden when first loading this page:

https://www.outerbankslaw.com/home-lead-generation-round-1.html

If the user clicks the chevron down then form appears and they can submit it.  However, once eform submits the form becomes hidden again and validation and thank messages are not viewable unless the chevron is clicked again as seen here:  

https://share.getcloudapp.com/p9u56lzN

I'm using 

`<button type="button" value="Submit" onclick="this.form.submit();">Submit</button>`

to submit the form.  Is it possible to call another javascript function here to show the form or should i do this in a snippet?

Here is my eform code:

`[!casePush!]	
								[!eForm?
										&protectSubmit=`0`
										&from=`((email))` 
										&fromname=`((firstname)) ((lastname))` 
										&to=`eliotgjones@gmail.com`
										&tpl=`case_form_tpl`  
										&report=`case_form_report`
										&subject=`[(site_name)] Website Case Submission`
										&formid=`contact_form`
										&eFormOnBeforeMailSent=`casePush`
										&vericode=`1`
										&gotoid=`37`
								!]`

The casePush snippet loads the form date into a table in the DB.

**Comment by Tourist4Life** [comment]
``

**Comment by bossloper** [comment]
p.s. you might want to remove urls to your site from your  post for security.

**Comment by Tourist4Life** [comment]
i'm fine with leaving it up so people can view the source code....but thanks will remove at a later date.  How do I open this issue again?  I accidently closed it.

**Comment by bossloper** [comment]
Your choice, but you are inviting hackers that now know this site uses Evo to 'test out' the security of your site.
reopen issue button at the end of the thread.

**Comment by Tourist4Life** [comment]
thanks i've removed from here and recreated another post which just links to the site.  any thoughts on how to get the form to show?

**Comment by bossloper** [comment]
sorry not sure about the form issue. Your new post screenshot still shows the url and I can tell your site is not up-to-date with the latest Evo version :-)

**Comment by Tourist4Life** [comment]
i thought 1.2.1 is pretty stable and fixed a bunch of the holes and critical security issues?

**Comment by bossloper** [comment]
Stable maybe, but I am sure there are  many security fixes since then. You really need to be on a 1.4.x version.
