### ISSUE TITLE
Cross References

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#134]
Simple `[*pagetitle@3*]` "Cross References" don't work on clean install 1.3.3.

**Comment by kivamp** [comment]
@prev, @next - not working
Before and after fix 1.3.3

**Comment by yama** [comment]
![2017-08-04](https://user-images.githubusercontent.com/73999/28947533-627c7432-78eb-11e7-97ae-4bd39685cdaa.png)
![2017-08-04 1](https://user-images.githubusercontent.com/73999/28947532-6279f95a-78eb-11e7-97a0-a3b4fc50cf7a.png)

It works in my development environment.
Could you give me more information?

**Comment by kivamp** [comment]
In development brench - already fixed. Thanx.

document.parser.class.inc.php:1008
Version 1.3.3 : missing second parameter.

**Comment by yama** [comment]
ok, thanks

**Comment by Pathologic** [comment]
Is it solved?

**Comment by dmi3yy** [comment]
Test 
[*pagetitle@prev*]
[*pagetitle@next*]
all work correct on 1.3.4
