### ISSUE TITLE
IF with SNIPPETS and processing

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#1342]
I've removed all my PHX stuff in favour of IF and I've found one thing that has raised an eyebrow.

Whilst changing over I've noticed that when I use and IF and put a SNIPPET in THEN, the snippet will ALWAYS be run.  This is not to say that the output will be displayed as this only happens if my IF snippet is true.

It has, however, cause a few hiccups especially when utilising a snippet multiple times within my template.  Which is where is showed it's head.

I have 2 IF snippets which when true runs the same SNIPPET with different parameters.  The SNIPPET in question creates a cookie which caused an issue which I got rid of by sorting my program out.

I found the better way forward was to put the snippet call in a chunk and use @TPL: in the &then parameter which appears to make it only produce the snippet call when IF Is true.

I can understand this is by design/default as it's the way the template is processed.  It doesn't know that the snippet is nested in an IF so runs the snippet regardless.

Just thought I'd post up my findings as to help others.

**Comment by sashabeep** [comment]
@BBloke setting cookie in template is BAD idea. Cookie must be set before anything will be displayed. And anyway, cookie not always be accessible without page reload.

The best approach for that is set cookie AND some internal variable. Cookie will be accessible after page reload or when user goes to another page

example plugin (onWebPageInit):
```php
if(someCondition){
 $myvalue=1;
 setcookie("mycookie", $myvalue, time()+3600*24*7, "/"); //accessible only after page reload or on the other page
 $modx->mycookie = $myvalue; //to use everywhere
}
```
I'm not sure that setting ```$modx->myOwnVariable``` is correct but it works.

get value snippet
```php
$myVal = ($modx->mycookie!='') ? $modx->mycookie : $_COOKIE["mycookie"];
return ($myVal);
```
and IF
```
[!if? &is=`[[myGetValueSnippet]]:is:1` &then=`{{someOtherBlock}}`!]
```

PLUS do not use nesting snippet in snippet call more than 3 levels deep – it wouldn't work

**Comment by BBloke** [comment]
Thank you for replying @sashabeep 

I was trying to relate the issue as being a parsing issue from the IF snippet.  Not something I find easy to describe but maybe this is an easier explanation.

If 2 IF snippets &then parameter calls a snippet then both snippets run whether IF is true or not.

[[if? &is=`User:webGroup` &custom=`webGroup` &then=`[[Snippet? &group=`Users`]]` ]]
[[if? &is=`Manager:webGroup` &custom=`webGroup` &then=`[[Snippet &gorup=`Managers`]]` ]]
		
In the above 2 IF statements a user can only be a USER or a MANAGER.  Although it doesn't matter what the &is reflects the snippet in &then will always be run.  In my poor code, it created issues as I only need the snippet to be run once.  

In order to prevent this I found it better to put the snippet call in a chunk.

[[if? &is=`User:webGroup` &custom=`webGroup`  &then=`@TPL:ChunknameUsers` ]]
[[if? &is=`Manager:webGroup` &custom=`webGroup`  &then=`@TPL:ChunknameManagers` ]]

I hope this helps explain things a little better.
