### ISSUE TITLE
Manage Categories Help Toggle Not Work

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#135]
The Manage Categories "help" toggle does not work in default theme.

fix in form.css
deleting
```.element-edit-message { display: none }```

**Comment by Nicola1971** [comment]
so, you prefer i revert the css fix and change class in the module. No problem for me.

I really love the new manager improvements , but we need more infos about it.
The previous changes and improvements have always been annunced, proposed and discussed together on github or Slack 

Even to prevent one from hurting the other's work ;)

**Comment by 64j** [comment]
I'm sorry.
The work in the theme of the design is not yet complete, and therefore I can not write all the changes.

In the category manager, you need to rewrite all javascript to native and remove **mootools**.

**Comment by 64j** [comment]
@Nicola1971 
![image](https://user-images.githubusercontent.com/4653189/28822703-eef62d70-76c2-11e7-9dea-36705c90b866.png)

**Comment by Nicola1971** [comment]
> In the category manager, you need to rewrite all javascript to native (ES5.1 or ES6) and remove mootools.

i just fixed the toggle issue for now, but dont know very well how Category Manager works. it was developed by @Deesen, he knows better

**Comment by 64j** [comment]
@Nicola1971 Ok)

**Comment by Nicola1971** [comment]
Issue closed

**Comment by 64j** [comment]
@Nicola1971 
Few finished your corrections )

**Comment by Nicola1971** [comment]
@64j it's already done, don't waste your time  wait my pull, so you can mix with your modifications ;)
