### ISSUE TITLE
[2.0.1] PHPthumb warnings

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1354]
php 7.4.1

1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.functions.php:219
-- | --
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.functions.php:1019
3× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:585
1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1438
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1278
1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1271
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1261

**Comment by ProjectSoft-STUDIONIONS** [comment]
Та же ошибка будет и здесь [JamesHeinrich/phpThumb](https://github.com/JamesHeinrich/phpThumb/)
https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.functions.php#L222 и т. д.
Нужно туда ишу писать или туда форкать, а потом уже здесь phpThumb обновлять.

**Comment by Dmi3yy** [comment]
Логично и тут исправить и туда заслать 

что б уже работало но и после обновления работало

**Comment by ProjectSoft-STUDIONIONS** [comment]
Тут сначала у нас до версии поднять надо, а уже потом туда слать.

**Comment by sashabeep** [comment]
@Dmi3yy @ProjectSoft-STUDIONIONS Писал. Пока глухо. Там и патчи на эту тему есть, но непринятые

**Comment by sashabeep** [comment]
@Dmi3yy вроде пропатчили в оригинале, можно пробовать утянуть
