### ISSUE TITLE
[2.0.1] Fatal error: Uncaught ErrorException: Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1358]
При попытке установить дополнение, например,
```
php artisan package:installrequire zeeyn/evocms-minifier '^1.1.1'
```

Получаю ошибку
```
artisan package:installrequire zeeyn/evocms-minifier '^1.1.1'
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /home/.../core/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php on line 223
Fatal error: Uncaught ErrorException: Undefined index: HTTP_HOST in /home/.../core/src/ExceptionHandler.php:175
Stack trace:
#0 /home/.../core/src/ExceptionHandler.php(175): Composer\Util\ErrorHandler::handle(8, 'Undefined index...', '/home/.../w...', 175, Array)
#1 /home/.../core/src/ExceptionHandler.php(510): EvolutionCMS\ExceptionHandler->messageQuit('Allowed memory ...', '', true, '', '/home/.../w...', '', '', 223, '', Array)
#2 /home/.../core/src/ExceptionHandler.php(46): EvolutionCMS\ExceptionHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 [internal function]: EvolutionCMS\ExceptionHandler->handleShutdown()
#4 {main}
  thrown in /home/.../core/src/ExceptionHandler.php on line 175
```

Но после этого дополнение всё равно установлено и работает...

php 7.4.1
Сайт находится на поддомене - может это имеет значение, если проблема с HTTP_HOST.
И вообще, HTTP_HOST вроде как не существует в командной строке.

Нужно как-то переписать, видимо, эту строку?

https://github.com/evolution-cms/evolution/blob/e5933247339787d67184da0798d72a280e68ee6f/core/src/ExceptionHandler.php#L175

Далее по тексту там есть
```
Fatal error: Uncaught ErrorException: Undefined index: REMOTE_ADDR in /home/.../core/src/ExceptionHandler.php:275
```
который тоже существует вроде только на внешке.

С памятью непонятно. Поставил 1G - ```core/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php``` как пытался выделить 4096 байт, так и не смог. Это проблема не в памяти, вероятно

**Comment by sashabeep** [comment]
```php -d memory_limit=-1 php artisan package:installrequire .....```

Composer runs out of memory pretty fast

**Comment by bezalkogoln1y-coder** [comment]
@sashabeep Поняли как фиксить?

**Comment by sashabeep** [comment]
@bezalkogoln1y-coder вроде как с композером не все хорошо в 2.0.1

**Comment by bezalkogoln1y-coder** [comment]
@sashabeep У меня даже на 2.0.2 такая проблема возникла... Вылечил командой в папке core/
composer update
Там видимо опять что то упустили и пофиксили, но в дев ветку не добавили апдейт((

**Comment by sashabeep** [comment]
@bezalkogoln1y-coder при обновлении надо всегда делать composer upd
