### ISSUE TITLE
Ajax search of elements %LIKE%

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#136]
# Здравствуйте!!!
### The search for chunks, snippets, etc.
If I have a chunk "testChunk" and I want to find if I enter in the search field "test", then the chunk is found, and if you introduce "Chunk" or "stCh" the search result will be empty.
Perhaps this is by design, but if I want for example to find all chunks with %form% provided that they have the name "test_form_lister_tpl", "123_chunk_formtest" or "form_tpl" - search results will be wrong.
___________________________________
### Поиск по чанкам, сниппетам, и т.д.
Если у меня есть чанк "testChunk" и я его хочу найти, то если я введу в поле поиска "test", то чанк будет найден, а если введу "Chunk" или "stCh" то результат поиска будет пустой.
Возможно так задумано, но если я хочу например найти все чанки с %form%, при условии что они имеют названия "test_form_lister_tpl", "123_chunk_formtest" или "form_tpl" - поисковая выдача будет неверная.
![2017-08-02_10-11-20](https://user-images.githubusercontent.com/3595562/28861820-501125da-776b-11e7-8418-fa63c0716b12.png)

**Comment by 64j** [comment]
The output of the elements is carried out in alphabetical order, and the search works by entering a search phrase at the beginning of the element name.
Otherwise there will be confusion in the search.
The global search is at the top right.
<hr>
Вывод элементов осуществляется в алфавитном порядке, и поиск работает по вхождению поисковой фразы в начало названия элемента.
Иначе появится путаница в поиске.
Глобальный поиск находится справа вверху.
<hr>

![image](https://user-images.githubusercontent.com/4653189/28863681-a0b39f16-7772-11e7-84ca-62d4bb1c17cb.png)

**Comment by 64j** [comment]
And if you put search through the %LIKE%, then when you search for one letter there will be a lot of results
<hr>
А если ставить поиск через %LIKE%, то при поиске по одной букве будет много результатов

**Comment by sazanof** [comment]
But the search page chunks or snippets works %like%. Well, here on taste and color. And so for three kinds of search system, choose what you want.))
__
Но поиск на странице чанков или сниппетов работает по %like%. Хорошо, тут на вкус и цвет. И так уже три вида поиска в системе, выбирай что хочешь.))

**Comment by 64j** [comment]
In the global search, the search starts from 3 characters
<hr>
В глобальном поиске, поиск начинает работать от 3 символов

**Comment by sazanof** [comment]
я про этот поиск
![2017-08-02_11-17-42](https://user-images.githubusercontent.com/3595562/28864153-44153f24-7774-11e7-9913-fc15ce20a592.png)
В любом случае - хозяин - барин)

**Comment by 64j** [comment]
It's a little uncomfortable
<hr>
Это немного неудобно
<hr>

![image](https://user-images.githubusercontent.com/4653189/28864407-241fa6c2-7775-11e7-8164-d1e0460ec1a4.png)

**Comment by sazanof** [comment]
Yes...
