### ISSUE TITLE
evo 1.4.2 -- upgrading from mysql 5.6 to 5.7

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1365]
hi evo-experts. a few sites that will be EVO upgraded shortly, will have a mysql upgrade in a few days time. do you know if there are any issues with upgrading from mysql 5.6 to 5.7 on an EVO 1.4.2?

**Comment by Dmi3yy** [comment]
Need update to last version 1.4.x all work fine on mysql 5.7 and mysql 8

**Comment by user83743** [comment]
thanks again Dmytro

**Comment by user83743** [comment]
last questions Dymtro. i have a number of them on 1.4.9 now as that is the one i have on a number of other trusted sites and i know it works 100% .  does evo 1.4.9 work with mysql 5.7 too?  and what about mysql 8

**Comment by user83743** [comment]
the mysql has been upgraded to 5.7 and the evo is 1.4.9 but on the cms screen called "system info"     (/manager/#?a=53)

we now get a big error screen with the following text:

"

« Evo Parse Error »
Execution of a query to the database failed - Native table 'performance_schema'.'session_variables' has the wrong structure
SQL > show variables like 'character_set_database'

Basic info	
REQUEST_URI	http://gamemachine.ie:443/manager/?a=53
Manager action	53 - Viewing system info
Referer	https://gamemachine.ie/manager/
User Agent	Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
IP	51.171.76.115
Current time	2020-02-04 07:53:03

Benchmarks	
MySQL	0.5443 s (2 Requests)
PHP	0.0300 s
Total	0.5743 s
Memory	3.5109710693359 mb

Backtrace
include_once(string $var1)
manager/index.php on line 733
DBAPI->query(string $var1)
manager/actions/sysinfo.static.php on line 9

"

**Comment by user83743** [comment]
any ideas?

**Comment by user83743** [comment]
i tried a few of the website that have mysql-5.7 and evo-1.4.9 and they all show the same error screen above for "system info"

**Comment by bossloper** [comment]
Works fine for me with same versions. Maybe you need to restart mysql after upgrading it?

https://stackoverflow.com/questions/32000911/errornative-table-performance-schema-has-the-wrong-structure

https://stackoverflow.com/questions/48672311/native-table-performance-schema-session-variables-has-the-wrong-structure

**Comment by user83743** [comment]
thanks @bossloper . i'll try that

**Comment by user83743** [comment]
that worked @bossloper . thanks for the prompt and informed reply. thnaks earlier @Dmi3yy too. the upgrade went fine. mysql 5.7 is perfect with evo 1.4.9  .
