### ISSUE TITLE
Массовое удаление в элементах

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#137]
I never had a mass deletion of items. To checkboxes and it is possible byloby to allocate a page of chunks (and best yet and all the tabs make this work) from the required chunks,snippets , templates, and say, delete them
------------------------------
Мне всегда не хватало массового удаления элементов. Чтобы были чекбоксы и можно былобы выделить на странице чанков (а лучше еще и на всех табах чтоб это работало) сразу необходимые чанки,сниппеты , шаблоны и скажем, удалить их

**Comment by 64j** [comment]
In Yandex mail it is conveniently done
<hr>
В почте яндекса удобно это сделано
<hr>

https://monosnap.com/file/Pqps6Q96MzVdxrCZQ4xnpS4XB0ba3O

**Comment by Dmi3yy** [comment]
В целом не вижу смысла в 3.0 переходим на файлы удаляй там как надо : )
