### ISSUE TITLE
[2.0.3] Checkbox mispositioned in site backup

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1370]
![Снимок экрана 2020-02-07 в 10 29 06](https://user-images.githubusercontent.com/5689796/74009742-ef7aa080-4994-11ea-94ac-c59a04bfd942.png)

**Comment by sashabeep** [comment]
Всё еще присутствует в 2.0.2

**Comment by nick0** [comment]
The same issue also exists in 1.4.10 and 1.4.11

Will open a new issue to confirm

![Untitled-1](https://user-images.githubusercontent.com/1768308/79409045-10d2bb00-7fdc-11ea-83d8-440d7b76037b.jpg)

**Comment by sashabeep** [comment]
Все еще есть в 2.0.3
