### ISSUE TITLE
Icons in Imagemanager and filemanager (evolution2.0/2.0.1)

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#1371]
In the manager for images some icons are missing or displayed incorrectly.
![evo_imagemanager](https://user-images.githubusercontent.com/26146656/74026869-6325a900-49a7-11ea-980c-e01edd796f50.png)

**Comment by sashabeep** [comment]
@webkarli Should be fixed for now https://github.com/evolution-cms/evolution/pull/1373

**Comment by webkarli** [comment]
Thanks.
