### ISSUE TITLE
problem parsing IF condition in chunk

### ISSUE THREAD

**Issue by jamiloo** [evolution-cms/evolution#1372]
I noticed problem with conditional template syntax. I am not able parse correctly this code:

<@IF:[!LanguageDetect:is(en)!]>
	[!Wayfinder? 
	&startId=`11` 
	&level=`1` 
	&outerTpl=`menu_outer` 
	&rowTpl=`menu_row` 
	&rowClass=`nav-item` 
	&parentRowTpl=`menu_row_parent` 
	&parentClass=`dropdown` 
	&innerRowTpl=`menu_row_child`
	!]
<@ELSE>
	[!Wayfinder? 
	&startId=`0` 
	&level=`1` 
	&outerTpl=`menu_outer` 
	&rowTpl=`menu_row` 
	&rowClass=`nav-item` 
	&parentRowTpl=`menu_row_parent` 
	&parentClass=`dropdown` 
	&innerRowTpl=`menu_row_child`
	!]
<@ENDIF>

[!LanguageDetect!] snippet returns correctly en or cs value but IF / ELSE  statement returns part for ELSE only. It looks like there is not interpreted [!LanguageDetect!] snippet during conditional comparing. Or am I missing anything?

**Comment by BBloke** [comment]
I would have thought your conditional part would be:

[[if? &is='[!LanguageDetect?!]:is:en' ....

It may be that you need to use a custom method similar to "webGroup".

Something like:
[[if? &is=`en:LanguageDetect` &custom=`LanguageDetect`  &then=`` &else=``

Where "LanguageDetect" is a file in assets/snippets/if/custom folder called "if.LanguageDetect.php". The code inside could be the same code is your LanguageDetect snippet.

Hope that makes sense.

**Comment by jamiloo** [comment]
Hi BBloke,

yes you are definitelly right. Snippet [[if]] works perfectly correctly 
as expected. Thank you. I used this way and it works correctly.

[[if? &is=`[!LanguageDetect? !]:is:en` &then=`
                         [!Wayfinder?
                             &startId=`11`
                             &level=`1`
                             &outerTpl=`menu_outer`
                             &rowTpl=`menu_row`
                             &rowClass=`nav-item`
                             &parentRowTpl=`menu_row_parent`
                             &parentClass=`dropdown`
                             &innerRowTpl=`menu_row_child`
                         !]
                     ` &else=`
                         [!Wayfinder?
                             &startId=`0`
                             &level=`1`
                             &outerTpl=`menu_outer`
                             &rowTpl=`menu_row`
                             &rowClass=`nav-item`
                             &parentRowTpl=`menu_row_parent`
                             &parentClass=`dropdown`
                             &innerRowTpl=`menu_row_child`
                         !]
                     `]]

Does it mean that syntax below does not work in Evolution? It has switch 
in settings.

<@SYNTAX>(atmark syntax) is simple and lightweight template syntax. This 
is designed to consider coexistence with HTML tags and content strings.

  * @@IF @@ELSEIF @@ELSE @@ENDIF
    <https://github.com/modxcms/evolution/wiki/@@IF-@@ELSEIF-@@ELSE-@@ENDIF>
  * <@LITERAL> {{string}} [*string*] [[string]] <@ENDLITERAL>
  *


Best Regards Kamil Vašica

**Comment by BBloke** [comment]
Thanks Kamil,

I removed my post because I didn't feel it was what you were looking for whilst using @IF syntax.  

Glad it helped.

**Comment by jamiloo** [comment]
Yes, aouare right, I was looking for something different a little but 
you helped me to solve problem other way.

Thanks.

Bye Kamil Vašica
