### ISSUE TITLE
PHx is not working anymore

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#138]
PHx is not working on 1.3.3
Many of my projects cannot been updated immediately to use built-in filters so anybody has a clue with PHx?

**Comment by pmfx** [comment]
Yeah, I have updated one site today and noticed it too. Simple conditional works but modifiers like [*pagetitle:esc*] doesn't.

**Comment by sashabeep** [comment]
@pmfx in my case all the PHx things doesn't work. Basically, i'm using just couple of this, but i have no success nor with simple conditions like
```
[*template:is=`something`:then=`something`*]
```
nor with the output modifiers like
```
[*pagetitle:htmlspecialchars*]
```

**Comment by sashabeep** [comment]
2 versions PHx i've used:
- https://github.com/Temus/PHx
- https://github.com/extras-evolution/PHx from Extras

**Comment by sashabeep** [comment]
@pmfx can you try to disable plugin and turn on built-in filters in the first tab on settings page? Looks like buil-in filters can deal with PHx conditions without change syntax...

**Comment by pmfx** [comment]
Something like this works with PHx 2.2.2:

`[*documentDescription:ne:then='[*documentDescription:notags:strip:esc*]'*]`

But this doesn't (I suppose because of snippet in else statement):

`[*documentDescription:ne:then='[*documentDescription*]':else='
[[replace? &from='@'&into=''&in='[*content_tv:notags:strip:esc:word_limit='35'*]']]
'*]`

Then I have tested both with built-in filters and everything worked just fine. 
Strange, I used to have this kind of issues with built in filters, not with phx.

**Comment by dmi3yy** [comment]
today test: 

[+blogimage:isNot(''):then('<img src=/[[phpthumb?&input=`[+blogimage+]`]]>')+]
in Ditto and on the page 
<@IF:[*blogimage:isnot('')*]>
    <img src=/[[phpthumb?&input=`[*blogimage*]` &options=`w=150,h=76,far=C,bg=FFFFFF`]]>
<@ENDIF>
	
[*blogimage:isNot(''):then('<img src=/[[phpthumb?&input=`[*blogimage*]`]]>')*]

Work only if on system modifiers and off PHx 
if On phx on page nothing
in ditto have error: 
 http://take.ms/fUdMp

**Comment by yama** [comment]
```
[+blogimage:isNot(''):then('img src=/[[phpthumb?&input=`[+blogimage+]`]]')+]
in Ditto and on the page 
<@IF:[*blogimage:isnot('')*]>
    img src=/[[phpthumb?&input=`[*blogimage*]` &options=`w=150,h=76`]]
<@ENDIF>
	
[*blogimage:isNot(''):then('img src=/[[phpthumb?&input=`[*blogimage*]`]]')*]
```
ok, I'll fix it later

**Comment by yama** [comment]
@pmfx , Is this solved?

**Comment by pmfx** [comment]
It works fine with built-in filters in 1.3.6 (no phx). Closing.
