### ISSUE TITLE
Bug in Chrome

### ISSUE THREAD

**Issue by Sybrenb** [evolution-cms/evolution#1382]
I'm getting an error message in Chrome when I want to edit chunks.

**Comment by Dmi3yy** [comment]
Fixed by this:
https://github.com/evolution-cms/evolution/commit/076261f7e0b3dcc29dc30f1c2003e9e7743a8794

**Comment by fourroses666** [comment]
I'm on 1.4.11 and this didn't fix it for me.

**Comment by Dmi3yy** [comment]
Clear browser cache ( or try in private tab )

Its simple 100% work fix 

Function all time return only true

**Comment by fourroses666** [comment]
Ah it was cache. Thanks :)
