### ISSUE TITLE
Question: Evo 2.0.1 DB API

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1386]
Hello,

Is there a class or methods to manually add or edit documents from manager tree via PHP / snippet ?

For example user "John" login to Evo Manager and add documents "test" with id 19.
I want to create blade template with button to manually add new documents in this tree with all TV etc.

Does anyone know how to do that ?

**Comment by Dmi3yy** [comment]
You want create document with Childs?

Cant’t understand what need :(

**Comment by modwebpl** [comment]
Well let me explain, for example I would like to add a new child of parent id:12 and set his value of TV "price" = 40,5

![Zrzut ekranu 2020-03-3 o 23 18 32](https://user-images.githubusercontent.com/35030936/75825447-ace69100-5da5-11ea-836e-7e007f3a9562.png)

**Comment by modwebpl** [comment]
Well I figured it out with eloquent model ;)
