### ISSUE TITLE
Слова для генерации CAPTCHA кодов

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#139]
Начиная с версии 1.2.1 из конфигурации пропала настройка "Слова для генерации CAPTCHA кодов"

В таблице _system_settings эти слова есть(поля captcha_words, captcha_words_default), но раньше можно было менять их из конфигурации.

**Comment by 64j** [comment]
А вы нажимали в конфигурации на вкладке Безопасность - Использовать код CAPTCHA ?

**Comment by sashabeep** [comment]
@64j Да, теперь понятно, куда она делась.
Только лишнее действие появилось - чтобы поменять слова для капчи eForm надо включить капчу при логине, которая в-общем, не нужна, и обратно ее надо выключать
