### ISSUE TITLE
After "cdca668" fix I still get same error "No hint path defined for [cache] if I do:

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1390]
After "cdca668" fix I still get same error "No hint path defined for [cache] if I do:

`{!! $modx->runSnippet('DocLister', ['parents' => $data['id'], 'addWhereList' => 'hidemenu=0', 'orderBy' => 'menuindex ASC', 'tpl' => '@B_FILE:chunks/top_nav_tpl_list']) !!}`

views/chunks/top_nav_tpl_list.blade.php :

`{!! $modx->runSnippet('DocLister', ['orderBy' => 'menuindex ASC', 'parents' => $data['id'], 'tpl' => '@B_CODE:<a href="#">{{ $data["pagetitle"] }}</a>']) !!}`

it works if I change @B_CODE: to @B_FILE:

_Originally posted by @modwebpl in https://github.com/evolution-cms/evolution/issues/1236#issuecomment-595349844_

**Comment by Pathologic** [comment]
You should not use @B_CODE construction inside of blade templates:
```
{!! $modx->runSnippet('DocLister', ['parents' => $data['id'], 'addWhereList' => 'hidemenu=0', 'orderBy' => 'menuindex ASC', 'tpl' => '@B_CODE:<a href="#">{{ $data["pagetitle"] }}</a>']) !!}
```
But it should work with php code:
```
$out = $modx->runSnippet('DocLister', ['parents' => $data['id'], 'addWhereList' => 'hidemenu=0', 'orderBy' => 'menuindex ASC', 'tpl' => '@B_CODE:<a href="#">{{ $data["pagetitle"] }}</a>']);

return $out;
```
