### ISSUE TITLE
Question: DocLister split pagination ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1394]
Does anyone know quick solution for DocLister split pagination like: [prev] .... [5] [6] [7] [8] .... [next] ?

**Comment by sashabeep** [comment]
@modwebpl built-in by deafult:
![Снимок экрана 2020-03-10 в 17 50 30](https://user-images.githubusercontent.com/5689796/76324868-aac98880-62f7-11ea-9ba4-f3a1e419b1d2.png)

```&paginate=`pages` ```

**Comment by modwebpl** [comment]
"Split pagination" as default ? :o - I need test it ;p

**Comment by modwebpl** [comment]
> @modwebpl built-in by deafult:
> ![Снимок экрана 2020-03-10 в 17 50 30](https://user-images.githubusercontent.com/5689796/76324868-aac98880-62f7-11ea-9ba4-f3a1e419b1d2.png)
> 
> `` &paginate=`pages` ``

Sashabeep can u give me a example in code how use split pagination in blade template ? This doesn't works for me:

```
{!! $modx->runSnippet('DocLister',['controller' => 'onetable', 'parents' => $documentObject['id'], 'display' => 1, 'showParent' => 0, 'depth' => 3, 'tpl' => '@B_FILE:chunks/cat-product', 'tvList' => 'img,price', 'orderBy' => 'menuindex ASC', 'filters' => 'AND(content:hidemenu:=:0;content:template:!=:5)', 'paginate' => 'pages', 'TplPage' => '@CODE:<li><a href="[+link+]">[+num+]</a></li>']) !!}

@evoParser('[+list.pages+]')
```

displays only one Product without pagination links :/

**Comment by sashabeep** [comment]
@modwebpl 
```{!! $modx->getPlaceholder("pages") !!}```

If you are using multiple instances of DL you should provide some id in DL call: 'id'=>'whatever'
and pagination placeholder 
```{!! $modx->getPlaceholder("whatever.pages") !!}```

**Comment by modwebpl** [comment]
Thank you for your help =). Works like a charm, I render standard pagination:

![Zrzut ekranu 2020-03-11 o 00 57 44](https://user-images.githubusercontent.com/35030936/76369320-74a9fa00-6333-11ea-8516-3591b40e4ba9.png)

How can I split them ? I need to set special parameters in DocLister ?

**Comment by sashabeep** [comment]
@modwebpl you sholuld specify amount of pages.
Try to change some params:
**pageAdjacents** - number of pages before and after current page(default 4)
**pageLimit** - limit of pages in pagination

And, please welcome to our telegram chat https://t.me/evolutioncms, since github is not suitable for technical support :)

**Comment by modwebpl** [comment]
Ok thanks for respond. I didn't know about "pageAdjacents" and "pageLimit" parameters - I can't find it on Evo Docs :o.

In deed, soon I will download Telegram :)

**Comment by fourroses666** [comment]
http://www.evolution-docs.com/extras/doclister/output-parameters

**Comment by fourroses666** [comment]
maybe: &id=`list` and yes you have : and need =
		
		```
		[!DocLister? 
		&parents=`[*id*]` 
		&showParent=`0` 
		&display=`1` 
		&depth=`0` 
		&sortBy=`menuindex` 
		&sortDir=`ASC`
		&id=`list`
		&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>` 
		&tpl=`@CODE:<li><a href="[+url+]">[+menutitle+]</a></li>`  
		&paginate=`pages`
		&PrevNextAlwaysShow=`1` 
		&pageLimit=`10` 
		&pageAdjacents=`2`
		&TplWrapPaginate=`@CODE:<nav class="pagination"><ul>[+wrap+]</ul></nav>` 
		&TplFirstP=`@CODE:<li><a href="[+link+]">First</a></li>` 
		&TplFirstI=`@CODE:<li>First</li>`  
		&TplPrevP=`@CODE:<li><a href="[+link+]">Prev</a></li>`  
		&TplPrevI=`@CODE:<li>Prev</li>` 
		&TplNextP=`@CODE:<li><a href="[+link+]">Next</a></li>` 
		&TplNextI=`@CODE:<li>Next</li>` 
		&TplLastP=`@CODE:<li><a href="[+link+]">Last</a></li>` 
		&TplLastI=`@CODE:<li>Last</li>` 
		&TplPage=`@CODE:<li><a href="[+link+]">[+num+]</a></li>` 
		&TplCurrentPage=`@CODE:<li>[+num+]</li>
		&TplDotsPage=`@CODE:<li>...</li>`
		!]
		
		```
