### ISSUE TITLE
How to remove document content from within a snippet?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1396]
I am sorry to ask this basic question, but I could not find an answer in the [docs](http://www.evolution-docs.com/documentation/developers-guide/api-reference/documentparser-object/).

I have a snippet and want to remove the document content using the snippet (if user is not loggedin).

I have tried:

```
unset($modx->documentObject['content']); // gives NULL
$modx->documentObject['content'] = ''; // gives string(0)
```

But the content still appears frontend.

Note: The snippet is called from a template.

**Comment by modwebpl** [comment]
In Evo 2.0.1 u can use blade template with eloquent model from Laravel to retrieve specified id document content and update it to null directly do MySQL

read more about eloquent here: https://laravel.com/docs/6.x/eloquent
and here: https://github.com/evolution-cms/evolution/releases/tag/2.0.0-alpha

u can also look inside Evo 2.0.1 code how it works.

**Comment by sashabeep** [comment]
@q2apro You should use built-in MODxAPI since DocumentParser is only for getting values:

Simple call in snippet
```php
include_once(MODX_BASE_PATH."assets/lib/MODxAPI/modResource.php");
$doc = new modResource($modx);
$doc->edit(10); //ID of edited document
$doc->set('content', ""); //any field/tv
$id = $doc->save(false, true); //returns id. Why? I dunno
```

What parameters of $doc->save(false, true) means:

1st parameter - save with OnBeforeDocFormSave OnDocFormSave events (if needed for plugins etc)
2nd parameter - clear cache after saving

**Comment by q2apro** [comment]
Isn't that overriding the content of the document?

My goal is to remove it for the rendering process (but maintain it backend (for loggedin users)).

**Comment by sashabeep** [comment]
@q2apro Hmmm, just remove ```[*content*]``` or ```{!! @evoParser($documentObject['content']) !!}``` from template. Make another template without content

I thought you wanted to remove doc content from snippet

**Comment by sashabeep** [comment]
@q2apro Finally, i got that you want to display something only for logged users...
You can totally hide the page using default groups or check

```php
$modx->userLoggedIn(); //array with 
Array (
    [loggedIn] => 1 
    [id] => 1 
    [username] => siteadmin 
    [usertype] => web 
)
```

**Comment by modwebpl** [comment]
> @q2apro You should use built-in MODxAPI since DocumentParser is only for getting values:
> 
> Simple call in snippet
> 
> ```
> include_once(MODX_BASE_PATH."assets/lib/MODxAPI/modResource.php");
> $doc = new modResource($modx);
> $doc->edit(10); //ID of edited document
> $doc->set('content', ""); //any field/tv
> $id = $doc->save(false, true); //returns id. Why? I dunno
> ```
> 
> What parameters of $doc->save(false, true) means:
> 
> 1st parameter - save with OnBeforeDocFormSave OnDocFormSave events (if needed for plugins etc)
> 2nd parameter - clear cache after saving

Awesome solution =)

**Comment by q2apro** [comment]
> Hmmm, just remove [*content*] or {!! @evoParser($documentObject['content']) !!} from template. Make another template without content

As I said *from the snippet*.

> You can totally hide the page using default groups or check

I have another framework in the backend that does the user management. So I have only a boolean `$loggedin`.

So is there really no way to remove the content from a snippet? Wow.

**Comment by sashabeep** [comment]
@q2apro WHY?
if you have boolean variable
```
$out='';
if($loggedin){
$out=$documentObject['content']
//or $modx->getDocumentObject('icontent');
}
return($out)
```
???

**Comment by q2apro** [comment]
My current **template**:

```
[!checkaccess!]   ← snippet

[*content*]

...
```

Now I try to remove the document content with snippet checkaccess.

**Comment by Pathologic** [comment]
[*content*] had been parsed before your snippet was executed. Try to change documentObject with OnLoadWebDocument event.
