### ISSUE TITLE
В админ панели съехали стили в разделе бэкапа

### ISSUE THREAD

**Issue by mapstr1** [evolution-cms/evolution#14]
![mozilla firefox](https://user-images.githubusercontent.com/30168899/28199290-eab89642-687d-11e7-9830-9250ffdac507.jpg)

Версия EVO |   | 1.3.0b
Дата выпуска |   | Jul 10, 2017
PHP Version |   | 5.5.36

**Comment by dmi3yy** [comment]
Исправленно https://github.com/evolution-cms/evolution/commit/626b416fb4fe784f2ad2f392ce8f0b99e16d5339
http://take.ms/ntE5i
