### ISSUE TITLE
Кракозябры при редактировании шаблона

### ISSUE THREAD

**Issue by SuicideStalker** [evolution-cms/evolution#140]
При редактировании шаблона под именем шаблона вылезают красные кракозябры.
[http://joxi.ru/ZrJ0WZLt1MJkk2](url)

**Comment by 64j** [comment]
Выберите в конфигурации язык в кодировке  UTF

**Comment by SuicideStalker** [comment]
Стоит russian-utf8

**Comment by 64j** [comment]
Всё так же?

![image](https://user-images.githubusercontent.com/4653189/28911551-957fb8d8-7839-11e7-862a-beeb451650df.png)

![image](https://user-images.githubusercontent.com/4653189/28911591-af54e878-7839-11e7-89d1-12a14278b7a6.png)

**Comment by 64j** [comment]
@SuicideStalker всё как на скриншоте выше?
