### ISSUE TITLE
Calling a snippet directly as parameter of another snippet (snippet call within snippet call)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1401]
Wow, I have just realized that this works:

```
    [!exercise? &nr=`a`&content=`
        [!calculate? &z=1&n=2!]
    `!]
```

Snippet "exercise" expects a string in parameter "content". Snippet "calculate" throws back a string. All seem happy :)

Is that safe to use for the future version of Evolution CMS?

**Comment by sashabeep** [comment]
@q2apro how did you use separate menus many years ago without calling ultimateparent as wayfinder parent ? :)

But for now is not recommended, especially deeper than 3rd level

**Comment by q2apro** [comment]
> calling ultimateparent as wayfinder

Never used those :) 

I am using it for now, otherwise I would need to pass the snippet name to the calling snippet with all parameters attached to it, and then call the snippet from there... but for now it works.
