### ISSUE TITLE
DocLister Error: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by djad33** [evolution-cms/evolution#1408]
Evo 2.0.2

This just started happening. I have a DocLister snippet in the template. When I remove it, the page renders.

---
I rolled the snippet back to the version from 2.0.1 and everything is working normally.

**Comment by sashabeep** [comment]
@djad33 Yep, there are some glitches with DocLister reported. Can you provide the code that produces error?
