### ISSUE TITLE
[2.0.2] Невозможно завершить обновление через Updater через веб

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1409]
При наличии кастомных пакетов, установка завершается на белой странице с мешком ошибок после выбора элементов для установки. Последний шаг в инсталлере не проходит, папка /install/ не удаляется. Надо что-то придумать с этим.

Пока не будет выполнен ```composer update``` невозможно даже зайти в админку.

**Comment by Dmi3yy** [comment]
По хорошему надо в виджете только указывать что есть обновления а само обновление выполнять через php artisan update так будет логично и оно тогда сможет само и композер обновить. Боюсь через браузер с кастомными пакетами не получиться ибо врядли лимиты позволят автоматом выполнить composer update

**Comment by sashabeep** [comment]
@Dmi3yy php artisan update выдает в консоль кучу html кода стандартную ошибку
![Снимок экрана 2020-03-20 в 14 13 59](https://user-images.githubusercontent.com/5689796/77158871-3a6bf580-6ab5-11ea-9d81-d3b5e3c928c2.png)

**Comment by sashabeep** [comment]
@Dmi3yy Вообще,если можно как-то описать по шагам процесс обновления

**Comment by Dmi3yy** [comment]
Сейчас процесс такой: 
- нажимаем обновить
- скачаются все файлы и перезапишутся и система перекинет на инсталл
- уже в этот момент можно выполнить composer update из папки core
- и после этого продолжить установку и все будет работать
