### ISSUE TITLE
formlister and datepicker

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1416]
hi evo experts :)

has anyone used formlister with a datepicker? if so, could you give me a link to see how it's done or any docs?

thanks

**Comment by fourroses666** [comment]
You just need to add the date field and use some datepicker script.
http://t1m0n.name/air-datepicker/docs/

**Comment by user83743** [comment]
thanks marc

**Comment by fourroses666** [comment]
No problem. Maybe you can close this issue.
