### ISSUE TITLE
Dynamic TAB panel

### ISSUE THREAD

**Issue by yanqpl** [evolution-cms/evolution#142]
Please help us to solve problem with dynamic tab panel in modX 1.3.3
After install on other hosting provider dynamic tab is missing.

Take a look screenshot below

![untitled-1](https://user-images.githubusercontent.com/24938064/28908588-c57388cc-7824-11e7-82da-ca281e048741.jpg)

**Comment by yanqpl** [comment]
I found a configuration error.
After install plugin "ElementsInTree" was disabled as default. After turning on  dynamic tabs is active.

**Comment by dmi3yy** [comment]
Turn on plugin elementsTree

Отправлено с iPhone

**Comment by bossloper** [comment]
I would question if 'ElementsInTree' should even be in the default installation?

**Comment by dmi3yy** [comment]
I think in new default theme no need

Отправлено с iPhone

**Comment by bossloper** [comment]
Agreed. There are now enough features built in for finding and editing elements.

**Comment by pmfx** [comment]
I think it should be included in default setup and maintained. For me it is the fastest and easiest way to get to the elements. Can be turned off by default but should be bundled with default package. It is a great feature.

**Comment by Nicola1971** [comment]
i agree with pmfx, ElementsInTree is still the faster and easy way to manage elements.

**Comment by bossloper** [comment]
Then should it be built (with an option) in rather than a plugin? I thought the long-term was to reduce the number of bundled extras from the core development?

**Comment by Nicola1971** [comment]
+1 for an option.
for me is the best revo-like feature.

**Comment by pmfx** [comment]
Yes, I vote with my both hands for having it built in.
