### ISSUE TITLE
404 in manager main page

### ISSUE THREAD

**Issue by mplavala** [evolution-cms/evolution#1422]
Hi all, after updating from 1.4.11 to 2.0.2 I started getting a 404 error in manager after I log in. The 404 error is thrown by the URL https://www.xxx.yy/manager/index.php?a=2 which should display the "Welcome to manager" page. Instead of that, the 404 page for the website (i.e. the page you get when you go to https://www.xxx.yy/404-page-does-not-exist ) is displayed.
I have no idea how this is even possible and how to fix it. Could anyone help? Thanks.

**Comment by Dmi3yy** [comment]
https://www.youtube.com/watch?v=jbhrTlcjqQ4

**Comment by Dmi3yy** [comment]
And check php version

**Comment by mplavala** [comment]
Thank you Dmi3yy, you are the best.
