### ISSUE TITLE
Evolution CMS Parse Error

### ISSUE THREAD

**Issue by priyankagarg-python** [evolution-cms/evolution#1426]
Hi,

We are upgrading from MODX Evolution CMS from 1.4.10 to 2.0 but after upgrading we are having errors.

When we open our site in browser first time we get following error 
« Evolution CMS Parse Error »
Error : Module 'imagic' already loaded 

And if we refresh page for 2 or 3 times then we get following error
« Evolution CMS Parse Error »
Error : Use of undefined constant id - assumed 'id' (this will throw an Error in a future version of PHP)

We can see above errors if we are logged in in manager otherwise we can see only Error written on web page.

However internal pages of the site are working fine. We are having this problem only on home page.

Can anyone please help?

**Comment by fourroses666** [comment]
Maybe some plugins needs to be updated from extras? PHP version update perhaps. Or turn off some plugins/modules to see which one is causing it. Clear assets/cache files.

**Comment by Pathologic** [comment]
It seems to be a problem with any custom snippet or plugin - its name should be shown in error page.

**Comment by ericfilippi** [comment]
Hello all,

I have the same problem with core.php file, so it's not a custom extra problem I guess.

Eric

**Comment by johngehrig** [comment]
@Pathologic I am getting the same error after upgrade to Evolution 2.0.1.

Here is the error message I see on the error page:

`« Evolution CMS Parse Error »
Error : Use of undefined constant id - assumed 'id' (this will throw an Error in a future version of PHP)
Error information	
ErrorType[num]	WARNING[2]
File	/core/src/Core.php(1867) : eval()'d code
Line	27

Basic info	
REQUEST_URI	/test
Resource	[259] Test
Referer	
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

Benchmarks	
MySQL	0.0000 s (0 Requests)
PHP	0.0836 s
Total	0.0836 s
Memory	1.6100540161133 mb

Backtrace
EvolutionCMS\Core->executeParser()
index.php on line 130
EvolutionCMS\Core->prepareResponse()
core/src/Core.php on line 2785
EvolutionCMS\Core->outputContent()
core/src/Core.php on line 2943
EvolutionCMS\Core->parseDocumentSource(string $var1)
core/src/Core.php on line 723
EvolutionCMS\Core->evalSnippets(string $var1)
core/src/Core.php on line 2655
EvolutionCMS\Core->_get_snip_result(string $var1)
core/src/Core.php on line 1943
EvolutionCMS\Core->evalSnippet(string $var1, array $var2)
core/src/Core.php on line 2032
eval()`

The error only appears when using the "Home" Page Template. All other pages and Page Templates, including custom Page Templates, load correctly.

**Comment by Dmi3yy** [comment]
current version 2.0.2
