### ISSUE TITLE
Broken sorting of snippets and chunks

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#143]
These lists should be sorted by category and name, but <a href="https://github.com/evolution-cms/evolution/commit/696d96e7c64b8b5a0ef84f9cd0efd603f9841609">this commit</a> brokes it, because order of sql columns changed.
So, something must be fixed here:
https://github.com/evolution-cms/evolution/blob/develop/manager/actions/resources/mgrResources.class.php#L90

**Comment by Pathologic** [comment]
@Deesen would you change numbers to column names in $orderby?

**Comment by Deesen** [comment]
I was on a short holiday so I just read it now. No problem, I will take care.
