### ISSUE TITLE
failed - could not create database

### ISSUE THREAD

**Issue by Nossulenko** [evolution-cms/evolution#1438]
Failing to install a new Evo installation, 
<img width="999" alt="Screenshot 2020-04-12 at 15 30 51" src="https://user-images.githubusercontent.com/12098675/79069984-b92e0a00-7cd2-11ea-9d76-ef6455615308.png">

**Comment by fourroses666** [comment]
what happens if you use an other collation? **latin1_general_ci**

**Comment by fourroses666** [comment]
I see latin1 is not recommended.
You need to go to phpmyadmin and change the collation.
This is the issue 100%. Button next to Import in phpmyadmin, on the bottom you can change it. Good luck.

![Schermafbeelding 2020-04-20 om 12 18 33](https://user-images.githubusercontent.com/523389/79741296-4c81c380-8301-11ea-9001-295ad86006c3.jpg)

**Comment by fourroses666** [comment]
This post can be closed
