### ISSUE TITLE
Modifiers problem with special chars in document params

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#144]
**[*longtitle:ifempty=[*pagetitle*]*]**
No working when pagetitle contains colon :
Ex.: pagetitle="Bla, bla: bla, bla"

[*longtitle:ifempty='[*pagetitle*]'*] , [*longtitle:ifempty([*pagetitle*])*] - OK

**Comment by yama** [comment]
In the process of parsing, syntax errors occur, so need to use delimiters.
````
[*longtitle:ifempty='[*pagetitle*]'*] , [*longtitle:ifempty([*pagetitle*])*] - OK
````
Of course, we can improve so that we can avoid using delimiters. However, the processing becomes complicated and the overhead also increases. At the moment, I think that this is a better solution.
