### ISSUE TITLE
INTL_IDNA_VARIANT_UTS46 is deprecated

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#1446]
I'm running PHP 7.2 and formlister is giving an error on validation with an email address.

Turns out Validator.php file doesn't account for this.

Line 282 should read:
$_email[1] = idn_to_ascii($_email[1],0,INTL_IDNA_VARIANT_UTS46);

to stop the program throwing an event.

**Comment by Dmi3yy** [comment]
fixed
