### ISSUE TITLE
Can't use resource which Content-Type is "text/css".

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1448]
Is this function deprecated in EVO 2?

![css](https://user-images.githubusercontent.com/523389/80474982-79108d80-8948-11ea-8b10-33a23e3448c2.jpg)

**Comment by Neoziox** [comment]
I have the issue. I had to modify directly in the database. But I cannot modify the ressource without re-edit the database.

**Comment by fourroses666** [comment]
When using TemplatesEdit3 the options like text/css came back.
