### ISSUE TITLE
Core modifiers snippet call and TV recursive usage

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#145]
call
```
[*blogimage:isNotEmpty
:then('<a href="[*blogimage*]" rel="lightbox">
	<img src="[[phpthumb? &input=`[*blogimage*]` &options=`w=270`]]" alt="[*pagetitle*]" class="carim">
	</a>')*]
```
does nothing, but
```
<@IF:[*blogimage:isNotEmpty*]>
	<a href="[*blogimage*]" rel="lightbox">
	<img src="[[phpthumb? &input=`[*blogimage*]` &options=`w=270`]]" alt="[*pagetitle*]" class="carim"></a>
<@ENDIF>
```
works, even
```
[*blogimage:isNotEmpty:then('<img src="[*blogimage*]>')*]
```
shows nothing, but
```
[*anyTV:anyCondition:then( any chunk or snippet or HTML ONLY without ANY TV call )*]
```
works again

dafuq?
Guys! new core modifiers must be described anywhere in more readable way. I never had an issues using PHx, but it doesn't work on 1.3.3 anymore

**Comment by sashabeep** [comment]
+ Core modifiers absolutely doesn't work with Ditto and DocLister using any syntax scheme

**Comment by yama** [comment]
![2017-08-04 4](https://user-images.githubusercontent.com/73999/28948221-4938e2f4-78ef-11e7-8b1e-38d15881ee21.png)
![2017-08-04 3](https://user-images.githubusercontent.com/73999/28948220-492ee736-78ef-11e7-8fa9-c2048f5f179e.png)

> Core modifiers absolutely doesn't work in Ditto and DocLister item templates using any syntax scheme

It works in my development environment.
Do you have more information?

**Comment by sashabeep** [comment]
Tried item chunk
```
<@IF:[+blogimage:isnot('')+]>
     [[phpthumb?&input=`[+blogimage+]`]]
<@ENDIF>
```
and
```
[+blogimage:isNot(''):then('[[phpthumb?&input=`[+blogimage+]`]]')+]
```
in Ditto?tpl=`my_chunk`
Same with DocLister.
DocLister just cut conditions from output, Ditto showed thumbnails even if its not defined.
First post in this issue was addressed to using modifiers on the page, this one to template items. 

PHP 5.6

**Comment by sashabeep** [comment]
@yama Another strange behavior
Tried on the page:
```
[*blogimage:isNotEmpty:then('<img src="[[phpthumb?input=`[*blogimage*]`&options=`w=50`]]">')*]
```
WORKS, BUT displays error on the top of site
```
Parse error: syntax error, unexpected ')' in /home/****/manager/includes/extenders/modifiers.class.inc.php(338) : eval()'d code on line 1
```
After refresh(!) error message disappears.
Maybe it's cache-related problem?
When i changing condition to
```
[*blogimage:isNot(''):then('<img src="[[phpthumb?input=`[*blogimage*]`&options=`w=50`]]">')*]
```
again works, but displays the same warning which disappears afrer refresh.
How can i tell you more information about my environment

**Comment by yama** [comment]
````
<@IF:[+blogimage:isnot('')+]>
    <img src= [[phpthumb?&input=`[+blogimage+]`]]>
<@ENDIF>
````

````
[+blogimage:isNot(''):then('<img src= [[phpthumb?&input=`[+blogimage+]`]]>')+]
````

I tried it with by Ditto, but it doesn't reproduce in my environment. Do you have more information?

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/3f108c9b1249d99d0de836351d72afc639c12572
Improved DocLister

**Comment by yama** [comment]
````
[*blogimage:isNotEmpty:then('<img src="[[phpthumb?input=`[*blogimage*]`&options=`w=50`]]">')*]
````
It works in my environment. Is there any other information?

**Comment by dmi3yy** [comment]
Test on page and in chunk inside Ditto all work correct
