### ISSUE TITLE
getConfig в админке

### ISSUE THREAD

**Issue by milkamil93** [evolution-cms/evolution#1460]
На момент регистрации ManagerThemeServiceProvider config пустой. getConfig не подтягивает актуальные настройки.

Пример 
[core\src\Providers\ManagerThemeServiceProvider.php строка 24](https://github.com/evolution-cms/evolution/blob/2.0.x/core/src/Providers/ManagerThemeServiceProvider.php#L24). Всегда возвращает default даже если в админке стоит другая тема.

**Comment by dzhuryn** [comment]
fix bug pr https://github.com/evolution-cms/evolution/pull/1463
