### ISSUE TITLE
External image in [(login_logo)]

### ISSUE THREAD

**Issue by Bahbv** [evolution-cms/evolution#1468]
Hello!

It isn't possible to put external images like "http://awesome.com/image1.jpg" in the [(login_logo)] or [(login_bg)] fields at configuration > interface, it comes out like "https://yoursite.com/http://awesome.com/image1.jpg". I dont want to change the login.tpl because i would like to keep the option of changing it in the manager.

I did tried to put logic in the login.tpl so i can use a an external images if the field isnt filled in but that also doesnt work. Is there another place i could put logic for that?

**Comment by Dmi3yy** [comment]
done in 3.1.3
