### ISSUE TITLE
ERROR: Too many forward attempts! The request could not be completed due to too many unsuccessful forward attempts.

### ISSUE THREAD

**Issue by Romkond** [evolution-cms/evolution#147]
Hi there, I've got this error:

> ERROR: Too many forward attempts! The request could not be completed due to too many unsuccessful forward attempts.

На beget делался новый сайт на сборке 1.3.3. Обратил внимание, что на некоторые страницы разрабатываемого сайта переход в браузере на фронте занимает секунд 15. При этом загрузившаяся страница загружается сразу (нет постепенной загрузки css и картинок). А иногда получаю просто ошибку, указанную выше.

Ответ сервера:

```
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Thu, 03 Aug 2017 15:22:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=60
P3P: CP="NOI NID ADMa OUR IND UNI COM NAV"
Cache-Control: private, must-revalidate
Set-Cookie: evoeunt78=ho30m0ore8o14e2keduj3s6a72; path=/
Set-Cookie: evoeunt78=ho30m0ore8o14e2keduj3s6a72; path=/; HttpOnly
```

**Comment by Romkond** [comment]
Установил Redis на другом хостинге. Не помогло. Вот результаты производительности одной из страниц:
Mem : 2 mb, MySQL: 0.0161 s, 20 request(s), PHP: 8.5803 s, total: 8.5963 s, document from database.

**Comment by dmi3yy** [comment]
Используйте  функцию debug она покажет какой глючит снипет

**Comment by Romkond** [comment]
Ошибка бывает при большом количестве phpthumb на странице - создаю много версий каждой картинки для разных разрешений браузера (метод srs-set). Пока скрипт не создаст все картинки, сыпятся ошибки. Можно получить и 404-ую (видимо, из-за отсутствия указанного в настройках id для Site unavailable page). Хотя вот 404-ая была на странице с единственной маленькой картинкой и без phpthumb. Ошибка воспроизводится только при переносе файлов на другой сервер.

**Comment by Pathologic** [comment]
Времени выполнения скрипта (и памяти) может не хватать на много phpthumb. Я стараюсь создавать картинки при загрузке, чтобы не использовать phpthumb при выводе.

**Comment by dmi3yy** [comment]
Если не хватает времени то падает с 502 ошибкой но нажимая обновить оно продолжает генерить жеж картинки с того места где отвалилось остальные уже в кеше ) проще как раз разруливать размер картинок на выводе ибо если потом меняется дизайн и надо поменять размер картинок то наступает печалька, вернее больше работы. А когда через phpthumb то просто меняем параметры и все)

**Comment by Pathologic** [comment]
Если памяти не хватает, то упадет скорее всего с 500 ошибкой.

**Comment by dmi3yy** [comment]
Тоже может но потом продолжит с новых фото, вообще я такую проблему наблюдал только в формате когда идет импорт тоесть массово добавляются товары но обычно это только на этапе наполнения контентом а когда сайт уже жив то никто не добавляет по 500 фоток ) за раз

**Comment by Romkond** [comment]
О, ну так-то получается, что у меня картинок совсем не много. Например, на странице кешированный или некешированный Ditto выводит 10 товаров по 6 тамбнейлов на каждый. Может, в кешировании дело... Вот шаблон Дитто:
```
[[if? &is=`[+ditto_iteration+]:%:3:and:[+ditto_iteration+]:>:0` &then=`</div><div class="row shop-grid filter-container">`]]
<div class="col-md-4 grid-item mb30 [+brand+]">
    <div class="overlay">
		<!--<img src="[ [phpthumb? & input=`[ +tv-img+]` & options=`w=270&h=270&zc=C`]]" alt="[ +menutitle+]">-->
		<img src="[[phpthumb? &input=`[+tv-img+]` &options=`w=263&h=263&zc=C`]]" alt="[+menutitle+]"
			sizes="
		(min-width: 1200px) 263px,   
		(min-width: 992px) 213px,
		(min-width: 583px) 720px,
		(min-width: 460px) 530px,
		(min-width: 321px) 409px,
		(max-width: 320px) 270px"
		srcset="[[phpthumb? &input=`[+tv-img+]`&options=`w=263&h=263&far=0&zc=1&q=80`]] 263w,
				[[phpthumb? &input=`[+tv-img+]`&options=`w=213&h=213&far=0&zc=1&q=80`]] 213w,
				[[phpthumb? &input=`[+tv-img+]`&options=`w=720&h=720&far=0&zc=1&q=80`]] 720w, 
				[[phpthumb? &input=`[+tv-img+]`&options=`w=530&h=530&far=0&zc=1&q=80`]] 530w,
				[[phpthumb? &input=`[+tv-img+]`&options=`w=409&h=409&far=0&zc=1&q=80`]] 409w,
				[[phpthumb? &input=`[+tv-img+]`&options=`w=270&h=270&far=0&zc=1&q=80`]] 270w">
		<div class="mask2">	
											
				<a href="[~[+id+]~]" class="button-def button-mid">Ver más </a>
										
        </div>
	</div>
```

**Comment by 64j** [comment]
@Romkond 
Попадался сайт, там картинки были все перенесены на отдельный сервер на гникс, и ресайзились по запросу, типа
site/images/123-200x200.jpg.
Сервер был на океане, и довольно шустро обрабатывал запросы.
Сборку затачивали исключительно под картинки, но помню долго решение искали по скорости загрузки.

**Comment by bossloper** [comment]
?
