### ISSUE TITLE
MCPUK no right-click in Firefox

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1477]
While using the file browser in both images and files, the right-click to bring up Rename, Delete, etc., does not appear in Firefox.
evo1.4.11

**Comment by bossloper** [comment]
Works for me. Firefox 76 and 77.0.1
Try clearing browser cache or force file refresh with Ctrl F5.
Also if it works in a Private Window then it is likely client side caching.

**Comment by risingisland** [comment]
Tried two different sites in Private mode using FF 77.0.1 and its not working in either.
Any other ideas?

**Comment by bossloper** [comment]
Open Developer Tools (F12) while in KCFinder and check the Console for any errors.

**Comment by risingisland** [comment]
Thanks @bossloper 
After starting FF in safe mode, I found that it was a plugin causing the problem (gesturefy).  
Everything is fine when that is disabled.
