### ISSUE TITLE
Tabs for tv

### ISSUE THREAD

**Issue by 64j** [evolution-cms/evolution#148]
Do we need tabs for TV parameters?

Choose radiobutton  in the configuration
![image](https://user-images.githubusercontent.com/4653189/28936585-cc735ee2-7890-11e7-8544-d3b17bdb9e7b.png)

And it turns out
![image](https://user-images.githubusercontent.com/4653189/28936733-47f2b3f6-7891-11e7-9058-9e5b4d6122c3.png)

**Comment by pmfx** [comment]
That would be perfect! Now I always use CategorizedTabs plugin to have this great functionality.
https://github.com/pmfx/CategorizedTabs

**Comment by ShCoder-1** [comment]
suggestion: change in configuration option title "Default" on "Default (No)" or "No" etc.

**Comment by ProjectSoft-STUDIONIONS** [comment]
Нужны!
Параметров TV для шаблона может быть море.
И зачастую именно группировки спасает от длинной портянки + хоть какой-то порядок.

**Comment by dmi3yy** [comment]
Так они ж легко групируются в табы и так 
Не вижу проблемы ;)

Отправлено с iPhone

**Comment by ProjectSoft-STUDIONIONS** [comment]
@dmi3yy так группируем с помощью ManagerManager
А если уже заточено в CMS и если задать настройку для шаблона - супер.
От сторонних плагинов надо брать лучшее.

**Comment by dmi3yy** [comment]
Это да. 

Отправлено с iPhone

**Comment by 64j** [comment]
@pmfx 
Help please with the correct translation into English .

<br>
In configuration

![image](https://user-images.githubusercontent.com/4653189/29001644-ca59d5dc-7a98-11e7-863b-ee953d4dc7be.png)

![image](https://user-images.githubusercontent.com/4653189/29001645-d2d6551e-7a98-11e7-9941-f6415ab5f2b7.png)

1
![image](https://user-images.githubusercontent.com/4653189/29001653-23068590-7a99-11e7-87c3-f8e19fbe0fb0.png)

2
![image](https://user-images.githubusercontent.com/4653189/29001656-384dbac2-7a99-11e7-8b1a-d80595a6f49c.png)

3
![image](https://user-images.githubusercontent.com/4653189/29001658-4b6b30e4-7a99-11e7-910c-988d40c14418.png)


4
![image](https://user-images.githubusercontent.com/4653189/29001661-5cfc34fc-7a99-11e7-9c81-98c47100bcf7.png)

5
![image](https://user-images.githubusercontent.com/4653189/29001663-6f8f0626-7a99-11e7-8b74-79702ef57053.png)

**Comment by pmfx** [comment]
@64j here you go. Not perfect but should do it:

> Group TV
> 
> Choose if Template Variables should be grouped in sections or tabs (named by TV category) when editing a Resource.
> 
> Sections in General tab
> Tabs in General tab
> Sections in new tab
> Tabs in new tab
> New tabs

Question: will tabs/sections be ordered by "Sort categories" set in "Manage Categories"?

**Comment by 64j** [comment]
@pmfx Yes, all sorts remain
Thank you for the translation.
