### ISSUE TITLE
Blade передача параметров в контроллер

### ISSUE THREAD

**Issue by bezalkogoln1y-coder** [evolution-cms/evolution#1484]
Можно ли как то через Blade передавать параметры в контроллер?
Например чтобы вызвать доклистер в доклистере (Категории - Элемент категории) на главной.
Для этого раньше использовался вызов prepare и добавление плейсхолдера, который выведет доклистер с текущим id.
На данный момент я сделал это с помощью вызова пхп в Blade.

**Comment by bezalkogoln1y-coder** [comment]
`@php
            $cat_item = json_decode($modx->runSnippet('DocLister', [
                'parents'=> $item['id'],
                'tvList'=> 'image,price,weight,pbchange',
                'orderBy'=> 'menuindex ASC',
                'api'=> 1,
                'display'=> 999,
            ]),true)
 @endphp`

**Comment by bezalkogoln1y-coder** [comment]
`@php
            $cat_item = json_decode($modx->runSnippet('DocLister', [
                'parents'=> $item['id'],
                'tvList'=> 'image,price,weight,pbchange',
                'orderBy'=> 'menuindex ASC',
                'api'=> 1,
                'display'=> 999,
            ]),true)
        @endphp`
Это завернул в переменную и передал следующему партиалсу через data.

**Comment by bezalkogoln1y-coder** [comment]
@Dmi3yy @AgelxNash Help)

**Comment by Dmi3yy** [comment]
Есть же видео по 2.0 
https://www.youtube.com/watch?v=T9Ws_kgF75M&list=PLKTHZGrYLdtoMegu0vG1Isek4_HsZPtZf&index=7

Вот в частности про контроллеры 

использовать @php настоятельно не рекомендую

**Comment by bezalkogoln1y-coder** [comment]
> Есть же видео по 2.0
> https://www.youtube.com/watch?v=T9Ws_kgF75M&list=PLKTHZGrYLdtoMegu0vG1Isek4_HsZPtZf&index=7
> 
> Вот в частности про контроллеры
> 
> использовать @php настоятельно не рекомендую

Это все понятно.
Вопрос в другом.
Контроллеру нужен заранее готовый параметр.
А в моей ситуации он меняется динамчески с перебором массива.
![image](https://user-images.githubusercontent.com/52246224/84639092-8ede1000-af00-11ea-9ca6-0e6d899ee80f.png)

**Comment by bezalkogoln1y-coder** [comment]
И т.е. мне в комбо нужно выводить дочерние элементы и соответсвенно в доклистер нужно давать параметр parents в зависимости от элемента в цикле.

**Comment by Dmi3yy** [comment]
Ну так получаем это все в контроллере и работаем там , во вьюху только данные уже прокидываются на отображение и все
