### ISSUE TITLE
EVO 1.4.9 and 1.4.11 target="_blank" is not working for new tab for resource link

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1498]
hi

EVO 1.4.9 and 1.4.11    target="_blank"    is not working for opening a new tab for a resource link . any ideas?   i tried some javascript for opening new tabs and that didn't work either.

**Comment by bossloper** [comment]
Either client browser setup or JavaScript. But it is not really an Evo CMS issue :-)
If you create a simple html file outside Evo does that work:
```
<html>
<head></head>
<body>
<a href="https://github.com/evolution-cms/evolution" target="_blank">test link</a>
</body>
</html>
```

**Comment by user83743** [comment]
it is an EVO issue if that "Link Attributes" box is not working for target="_blank" . yes, target="_blank" does work outside of that "Link Attributes" box.

**Comment by bossloper** [comment]
Ah, you did not say you were using a weblink resource.

Assuming you are using DLMenu it does not include link attributes by default. See here:
http://docs.evo.im/en/04_extras/dlmenu.html

You will need to override rowTpl to include the [+link_attributes+] placeholder. e.g.:

`@CODE:<li[+classes+]><a href="[+url+]" [+link_attributes+]>[+title+]</a></li>`

**Comment by user83743** [comment]
thanks Mr B. that worked 100%. thanks for your time and help
