### ISSUE TITLE
Присвоение ТВ-параметра шаблону

### ISSUE THREAD

**Issue by Aharito** [evolution-cms/evolution#15]
Невеликий баг, но всё же.
Закинул installer.php из 1.3 в 1.2.2, обновил на develop.

Открываю шаблон, тыкаю вкладку "Назначенные TV", там ряд не-назначенных шаблону ТВ со ссылкой Редактировать.

Нажимаю Редактировать рядом с каким-либо ТВ, там нажатием кнопки "Включить все" присваиваю этот ТВ всем шаблонам, нажимаю Сохранить.

Меня возвращает на вкладку шаблона Назначенные TV (что логично), но там не отмечен ни один ТВ, хотя некоторые уже присвоены шаблону.

Перезагрузкой страницы (Shift+Ctrl+R) это не лечится, лечится заходом в редакт-е шаблона через верхнее меню, тогда все галочки на месте.

**Comment by 64j** [comment]
есть такое... возвращает, вообще на пустой-несуществующий шаблон..

**Comment by dmi3yy** [comment]
Так все логично править нужно или там или там. По другому работать оно особо и не может

**Comment by Aharito** [comment]
Не согласен, Дмитрий. Видимо, ты не воспроизвел ошибку, а сориентировался по описанию.

Логичным было бы возвращение "на то место, откуда выкинуло", то есть:
* **В идеале** - на ту самую вкладку "Назначенные ТВ" того самого шаблона, где я нажал "Редактировать" рядом с этим ТВ.
* Или **хотя бы** на вкладку "Элементы->Параметры ТВ", где находятся все ТВ параметры.

А нынешнее поведение **абсолютно нелогично** и вызывает ступор.

**Comment by 64j** [comment]
исправить можно и очень просто, надо ли?

**Comment by Aharito** [comment]
С точки зрения UX-обязательно (мое мнение).

Но можно подождать мнения других. Если никого описанное мной поведение не смутит, значит и не надо.

**Comment by 64j** [comment]
исправлено
https://github.com/evolution-cms/evolution/commit/92f954faaa2e9bba2007214d3c6192e51a619236
