### ISSUE TITLE
ditto - Modx parse error

### ISSUE THREAD

**Issue by wishbone-design** [evolution-cms/evolution#1505]
> 
Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /kunden/298153_90451/modx2016/assets/snippets/ditto/classes/ditto.class.inc.php
Line | 255
Source | $ph['ditto_index'] = $r_start+$x+1;
Current Snippet | Ditto

The snippet works nonetheless, but I keep getting these error notes.
Hopefully not breaking anything?
Can I get rid of them?
ditto 2.14
evo 1.2.1
and no, no way to update

**Comment by Deesen** [comment]
Hi, I know what the reason is. You need to change line 254 in ditto.class.inc.php as follow:

`$r_start = isset($_GET['start']) ? $_GET['start'] : 0;`

to 

`$r_start = isset($_GET['start']) && is_numeric($_GET['start']) ? $_GET['start'] : 0;`

**Comment by wishbone-design** [comment]
Schneller als der Schall...
dankeee !!
