### ISSUE TITLE
Use of undefined constant IN_PARSER_MODE in Manager

### ISSUE THREAD

**Issue by djad33** [evolution-cms/evolution#1515]
Warning: Use of undefined constant IN_PARSER_MODE - assumed 'IN_PARSER_MODE' (this will throw an Error in a future version of PHP) in /path/to/core/src/Core.php on line 745

This error started showing up yesterday. I'm not sure how to clear it.

**Comment by fourroses666** [comment]
I have the same issue after saving my Template.
After updating the manager to the development version I got an different error.
My error disappears when I disable "templatesEdit 3".
Thats the only plugin I have installed.

PHP 7.4.7

**Comment by fourroses666** [comment]
When I upgrade TemplatesEdit3 from Extras as Development version (not master) then I have no errors anymore.

Maybe you can, or upgrade to the development version of EVO or try to disable some plugins and see which one is causing your problem.

**Comment by djad33** [comment]
I replaced /core with a copy from the install package and then ran the installer again.  That cleared the error and everything is operating normally.
