### ISSUE TITLE
Update 2.0.3 loads blank screen after saving configuration page

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1522]
After I update EVO to 2.0.3 I need to go manual to the /manager.
Its loading configuration page full page without the manager and when saving that it shows a blank page.

Don't know if everyone has this issue and if this can be fixed easy.

**Comment by Dmi3yy** [comment]
Send me access i check 

Dmi3yy@gmail.com

**Comment by fourroses666** [comment]
It is only right after updating. When going manual to /manager its all oke again.
Not a big problem, just wanted to let you know. Its not correct for me.

Upgrading
![1](https://user-images.githubusercontent.com/523389/89886691-5770a480-dbcd-11ea-9c2f-0ee074ea77af.jpg)

After installing it goes to configuration (in fullscreen not with tree and top menu)
![2](https://user-images.githubusercontent.com/523389/89886697-5a6b9500-dbcd-11ea-9f54-9617c7bfc16c.jpg)

After saving configuration page I get a blank page. `/manager/index.php?a=7&r=10` <- this is the URL and shows a blank screen.
![3](https://user-images.githubusercontent.com/523389/89886698-5b9cc200-dbcd-11ea-94a6-afe57a27d0ff.jpg)

Going manual to /manager its all oke.
