### ISSUE TITLE
Using your site to spam with WebSignup or FormLister with default registration form

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#1537]
Someone can use the registration confirmation email of your site to send  spam.

With **WebSignup** : 
Emails with spam content are sent, using the [(websignupemail_message)], inserting the spam text in the placeholder of the user's **fullname** [+ uid +] and recipient email in the registration email field.

I.e:
Instead :
"Hello John Smith..."

"Hello PASSIVES EINKOMMEN VON 8755 EUR PRO TAG - GONNEN SIE SICH FINANZIELLE FREIHEIT, check at http://www.spamdomain.com/..."

On one of my old websites, they sent thousands of spam emails using this method with WebSignup.
Updated to FormLister : same possibility to use registration to spam.

With **FormLister**  : 
Emails with spam content are sent, using the &ccSenderTpl [+fullname.value+] placeholder

We need to improve FormLister Data validation  in demo content registration form
http://docs.evo.im/en/04_extras/formlister/validaciya_dannyh.html

**Comment by Nicola1971** [comment]
maybe

```
		"fullname":{
			"required":"Insert your full name",
			"alpha":"Only letters",
		        "lengthBetween" : {
                        "params" : [5,25],
                        "message" : "Min 5, Max 25 characters"
        }
```

**Comment by Nicola1971** [comment]
and remove [+fullname.value+] from FormLister call in **Request an Account** page

```
&ccSenderTpl=`@CODE:
		<h3>[+fullname.value+], signup completed successfully!</h3>
		Login: [+email.value+]<br>
		Password: [+user.password+]<br>
	`
```

**Comment by fourroses666** [comment]
Does that work? I use reCaptcha and seems to be safe.

**Comment by Nicola1971** [comment]
> Does that work? I use reCaptcha and seems to be safe.

With recaptcha you are quite safe,  but I cannot use it with all my clients.
Anyway, after replacing WebSignup with FormLister and adding all the changes, it seems there were no spam mails today, but I have to delete over 20,000 fake users from the db

![screenshot-www sportivamenteasd it-2020 09 02-14_23_17](https://user-images.githubusercontent.com/7342798/91980795-1c731400-ed28-11ea-8aff-d406aa375e8c.png)

**Comment by modwebpl** [comment]
Using form without for example Google reCaptcha it's crazy in these times :/

**Comment by Nicola1971** [comment]
> Using form without for example Google reCaptcha it's crazy in these times :/

I agree, but some of my clients don't want anything from Google :) 
The form of this site uses the default evolution captchas

**Comment by risingisland** [comment]
Look at it on the upside, you now know the best dating sites for this year 🤣

**Comment by Pathologic** [comment]
> maybe
> 
> ```
> 		"fullname":{
> 			"required":"Insert your full name",
> 			"alpha":"Only letters",
> 		        "lengthBetween" : {
>                         "params" : [5,25],
>                         "message" : "Min 5, Max 25 characters"
>         }
> ```

It would be simplier to check fullname against "http"  using "matches" rule. Maybe a new rule is needed to check occurrences in slightly more convenient way then "matches"?

**Comment by Pathologic** [comment]
https://forum.evo.im/d/19-formlister-example-i-use/19
