### ISSUE TITLE
Remove web users

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#157]
The current concept of managers and web users leads us to some problems:
* web users have no permissions system;
* createdby, editedby, deletedby fields of site_content are not for web users, in spite of the fact that creating documents from frontend is a frequent task;
* it's difficult to get real user id (https://github.com/AgelxNash/DocLister/issues/184) and log web users actions (https://github.com/AgelxNash/DocLister/issues/75).

So, I propose to remove web users completely and create predefined user role named "Web user"; users of this role are prevented from being logged in to manager interface and have other restrictions. So we'll reduce code base and solve problems I described above. Of course, it wll be done not tomorrow, so developers will have time to get ready.

Any thoughts?

**Comment by pmfx** [comment]
First I was like "No way" cause I like the concept of separated web and manager users, but you got a point there with missing permissions system and frontend resources editing. So I think, what you are proposing makes sense, to merge both groups and give web users a special role. I only hope that it will stay simple and easy to understand/develop like it is now.

**Comment by Nicola1971** [comment]
i agree about missing permission in web users, this is a real issue when you manage sites with a lot of frontend editing and submission.

My only concern is about "backward compatibility": we need a simple way to help moving webusers from old webusers tables and webloginpe.


and to help replacing webloginpe we need something like this https://github.com/evolution-cms/evolution/issues/51

**Comment by bossloper** [comment]
Sort of how MODX Revo is. I would also like to see the ability to have duplicate email addresses as in Revo.
'My only concern is about "backward compatibility"' - agree that is a major factor in any changes.

If the suggestion is to effectively enhance manager users with a new 'web users' role then is it possible to keep (but not develop further) web users, then at least compatibility would be maintained.

**Comment by Pathologic** [comment]
I don't understand how to work with non-unique emails: who will be authorized by email? who will receive password reset notification?.

**Comment by Nicola1971** [comment]
@Pathologic  dont know about revo duplicate email address, but check github email address settings, it's nice:
https://github.com/settings/profile
and 
https://github.com/settings/emails

**Comment by Pathologic** [comment]
These are three different types of email: primary, secondary, visible for all. I don't think I'll be able to reset somebody's password if I add his email as my secondary.

**Comment by bossloper** [comment]
@Pathologic - for duplicate emails then all accounts with that email address receive reset emails. Each email also has the username in the email information so only the appropriate one would be acted on. By definition if 'family members' are sharing email address then there is no security issue in sending multiple reset emails.

**Comment by bossloper** [comment]
...Though I would say duplicate email addresses are only applicable to 'web users' - managers should probably still be restricted to unique emails addresses.

**Comment by Breezer** [comment]
Has any more thought/work been done on this subject, I was going to re-start work on my forum soon so  I'm curious.

**Comment by Pathologic** [comment]
No, this idea is still an idea.

**Comment by AgelxNash** [comment]
Why duplicate? Just add the sudo field

**Comment by Dmi3yy** [comment]
done in 3.0
