### ISSUE TITLE
Tag list not visible

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#158]
Installed latest dev and have problem with tag list:

![screenshot_1](https://user-images.githubusercontent.com/10888055/29024059-97a07320-7b70-11e7-9014-1626d85c7c58.png)

**Comment by 64j** [comment]
@pmfx 
How can I repeat this error?

**Comment by pmfx** [comment]
Just use mm_widget_tags. I've looked into it and it seems that problem is with float set in custom.css line 27.

![screenshot_1](https://user-images.githubusercontent.com/10888055/29040590-df293e36-7baf-11e7-9296-19e085478290.png)

Tags showed up when I have disbled this css property.

**Comment by pmfx** [comment]
Also, while we are at small css issues, selects have strange padding. Caused by min-height I think.

![screenshot_2](https://user-images.githubusercontent.com/10888055/29040808-b95a5810-7bb0-11e7-98a3-686b51b4bc69.png)

**Comment by 64j** [comment]
> Also, while we are at small css issues, selects have strange padding. Caused by min-height I think.

Yes. At the moment I'm dealing with this problem

![image](https://user-images.githubusercontent.com/4653189/29041019-ee2cb958-7bb9-11e7-9bd8-9990e9e1e2d7.png)
