### ISSUE TITLE
Idea (for EVO 3) - Move main-menu to Sidebar

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1590]
We can keep the Resource tree but add the main-navigation buttons below it.
This is a very rough concept. Missing icons and spaces/heights etc. Most of the time my resource tree isn't large and it can be collapsed.
I like the idea to have 2 frames and remove the top frame. Maybe its a bit more understandable for new CMS users.
The resource tree could ALSO be loaded into the mainframe. Hard to break a 16 year old concept thow :)
Wonder what you guys think of it.

![idea](https://user-images.githubusercontent.com/523389/95198697-eb30ac80-07db-11eb-9a25-337febda4441.jpg)

**Comment by nick0** [comment]
-1
Please keep the main menu at the top - and the resource tree in the LHS. It's one of the things that sets Evo apart from other CMS's.
If making this change please provide an option in the configuration to control the location for main menu (top or left) and resource tree (lhs or xxx) etc.
On big sites, the tree is critical on the LHS and needs to be primary thing in the LHS frame.
WordPress pages is junk - the resource tree in the LHS is a million times better.

**Comment by fourroses666** [comment]
@nick0 Well EVO is not WP:

![Uploading wp.png…]()

**Comment by Dmi3yy** [comment]
This already done 

Try change in settings menu position ;)

**Comment by Dmi3yy** [comment]
Param: manager_menu_position

**Comment by fourroses666** [comment]
Didn't know that!

But its not the same. Its an extra sidepanel.

**Comment by Dmi3yy** [comment]
Yes but all another cms haven’t site content tree. 

For Evo and MODX in main feature

**Comment by fourroses666** [comment]
I would like to keep that yes. But I like to see the main menu below the content-site-tree and be able to collapse the content-tree. Only on mobile show the sidebar small.

**Comment by fourroses666** [comment]
Its just an idea. Just needs to look good. 
Don't know if I will like it more than topmenu. At the moment I do think so.
