### ISSUE TITLE
[Evo 3.0 RC] Impossible to install ClientSettings (Error 500)

### ISSUE THREAD

**Issue by Neoziox** [evolution-cms/evolution#1623]
Hi everybody!

New install of Evo 3.0 RC. I tried to install ClientSettings but it didn't work.
In the inspector: Failed to load resource - Error 500
`/manager/?id=1&a=112&method=fast&action=install&cid=233&name=ClientSettings`

Of course, I tried to install another Extra and it's work.

**Comment by Dmi3yy** [comment]
fixed
