### ISSUE TITLE
[3.0 RC2] Error saving execution order in plugin

### ISSUE THREAD

**Issue by masco123** [evolution-cms/evolution#1639]
Hi

This is an error report.

**error message**
Using $this when not in object context

**file**
../core/vendor/illuminate/database/Eloquent/Model.php

**line**
604

**Backtrace**
Illuminate\Support\Facades\Facade::__callStatic('handle', array $var2)manager/index.php on line 205
EvolutionCMS\ManagerTheme->handle(100)core/vendor/illuminate/support/Facades/Facade.php on line 261
EvolutionCMS\Controllers\PluginPriority->process()core/src/ManagerTheme.php on line 394
Illuminate\Database\Eloquent\Model::update(array $var1)core/src/Controllers/PluginPriority.php on line 66

thank you

**Comment by Dmi3yy** [comment]
check in 3.1.2 all ok
