### ISSUE TITLE
Cannot Expand folders after upgrade from 1.1 to 1.3.3

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#165]
Clicking on a folder does not unfold it. It instead opens the container doc. And then, in the right in the tabs there is "View Children" to access the children documents.

I assume this is not by purpose but the container should show there containing documents when clicking on them?

**Comment by Nicola1971** [comment]
you must click on the arrow near the folder
![download](https://user-images.githubusercontent.com/7342798/29069329-dacd7b28-7c3a-11e7-80c4-276e4586da51.png)

**Comment by 64j** [comment]
This can happen if these parameters are selected

![image](https://user-images.githubusercontent.com/4653189/29069269-e949efda-7c42-11e7-84db-862a3d0b58af.png)

![image](https://user-images.githubusercontent.com/4653189/29069351-542e2d3e-7c43-11e7-96d8-314a13ec6d41.png)

**Comment by q2apro** [comment]
Still no luck. 

Neither with the settings above, nor with my previous settings: 

![former](https://user-images.githubusercontent.com/6764548/29069435-ab4b4764-7c43-11e7-88a2-8ef900d97d4a.png)

This happens: 

![recording](https://user-images.githubusercontent.com/6764548/29069442-aef87ce2-7c43-11e7-8ac5-3a9e38712e11.gif)

**Comment by 64j** [comment]
Or so

![image](https://user-images.githubusercontent.com/4653189/29069443-af1dd870-7c43-11e7-90bd-2f73ebbc7bf6.png)

**Comment by 64j** [comment]
Clear browser cache
Ctrl + F5 or Ctrl + Shift + R

**Comment by q2apro** [comment]
Tried all you said. Nothing. 

![settings](https://user-images.githubusercontent.com/6764548/29069493-de15c2be-7c43-11e7-8995-5c70706eaf97.png)

That's weird.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/29069567-2309c334-7c44-11e7-8876-c128c32fa69a.png)

**Comment by Nicola1971** [comment]
@64j ..why? 
I do not understand why hiding childrens with Enable Stats Tracking disabled

**Comment by q2apro** [comment]
I sum up my settings, which do not work: 

1. Interface & Features: Page Click Behavior - Edit Resource

2. Sort Tree: Folder, Descending, Default, View children (enabled)

3. For all containers that "Enable Stats Tracking" is turned off

I also did a hard reload. I further went into private mode (browser) to have no cache/cookie problems etc.

Still not working.

**Comment by Nicola1971** [comment]
@q2aproyou must enable "Enable Stats Tracking"

**Comment by 64j** [comment]
@Nicola1971 incorrect translation

RU: Показывать дочерние ресурсы
EN: Show child resources

![image](https://user-images.githubusercontent.com/4653189/29069788-12466934-7c45-11e7-91ca-ae211876d3cd.png)

**Comment by q2apro** [comment]
@Nicola1971 Thanks. That was it!

**Comment by Nicola1971** [comment]
@q2apro thanks to @64j :)

**Comment by Nicola1971** [comment]
> @Nicola1971 incorrect translation
@64j ok, but ...where is Enable Stats Tracking ? :D

**Comment by 64j** [comment]
@Nicola1971  Yes.
Need to change the translation
Enable Stats Tracking => Show child resources

( $ph['donthit'] )

https://github.com/evolution-cms/evolution/blob/develop/manager/frames/nodes.functions.inc.php#L353

**Comment by Nicola1971** [comment]
we need two separated options "Enable Stats Tracking" AND "Show child resources"
There are some Evo extras and plugins based on "Enable Stats Tracking" option (ie: Google Analytics), and  is not nice hide childrens when you just want to disable stats tracking.

**Comment by 64j** [comment]
@Nicola1971 
So it turned out that this parameter was not used by anyone

**Comment by Nicola1971** [comment]
is used :)

and is in the system settings too 
![download](https://user-images.githubusercontent.com/7342798/29070393-6e3f8a3c-7c3f-11e7-9ac2-f892342d39f7.png)

better ask to the community before doing some kind of changes.

modx evo to evocms trasition must be at 100% easy.... at least for now ;)

**Comment by Nicola1971** [comment]
we need to fix

**Comment by 64j** [comment]
Absolutely agree with you.
We need to look for a solution to this problem.

Enabling the global parameter [(track_visitors)], gives the command to use in their tvars, snippets and plug-ins.

**Comment by q2apro** [comment]
The "fix" is to always have the container open on click. No need to hide this feature that is available for ages already.

**Comment by Pathologic** [comment]
> So it turned out that this parameter was not used by anyone
It's Dmi3yy's hack for his custom build. The right solution is to add column "show_children" and according checkbox.
