### ISSUE TITLE
Suggested Enhancement - auto focus for elementsintree plugin

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#166]
When clicking the various element/tab icons is would be useful if the search box then had focus so typing can begin without the need to click into the search box first.

![untitled](https://user-images.githubusercontent.com/1744687/29082046-487f6e94-7c5c-11e7-83d9-462556f9f3ab.png)

**Comment by pmfx** [comment]
Yes. That make sense :)

**Comment by 64j** [comment]
If you really need, I can do

**Comment by bossloper** [comment]
I don't really need! But I think it would be good :-)

**Comment by 64j** [comment]
@bossloper Maybe, who will it interfere with?

**Comment by bossloper** [comment]
@64j I don't understand

**Comment by Deesen** [comment]
I also think its good. It cannot hurt IMO and will only improve workflow :+1:

**Comment by Deesen** [comment]
I just noticed when clicking on an element/tab icon, and then hitting the tab-key, the search-field is focused too..

**Comment by bossloper** [comment]
@Deesen Good spot, so one step closer! As I said I really don't mind as I personally only occasionally use it, It just seemed to make ergonomic/logical sense to auto-focus the field. Happy to close the issue if there is no real need for it.

**Comment by bossloper** [comment]
going to close this for now
