### ISSUE TITLE
1.4.11 Обновление TinyMCE4 ставится без событий

### ISSUE THREAD

**Issue by Typodin** [evolution-cms/evolution#1666]
После обновления TinyMCE4 до версии 4.9.11 через Extras на страницах исчезает текстовый редактор и отсутствует вариант его выбора в инструментах. Причина - плагин устанавливается без заданных по-умолчанию событий.

**Comment by chernyshovmaksim** [comment]
Поставил все события как на предыдущей версии, у меня все равно не заработало

**Comment by kivamp** [comment]
Там в начале блок комментариев (установочный блок):
начиная со строки ** * @internal    @events** и до конца блока - отсутствуют пробелы в начале строки.
Надо добавить пробелы, поставить галку "Анализировать DocBlock" и сохранить

**Comment by Dmi3yy** [comment]
Спасибо как раз исправил в 4.9.11 в екстрас и вроди как перенес в 1.4.12 но видать тоже сьехало завтра исправлю

**Comment by kivamp** [comment]
да я там вроде как зареквестил

пн, 21 дек. 2020 г. в 23:36, Dmytro Lukianenko <notifications@github.com>:

**Comment by Dmi3yy** [comment]
ага вижу читал письма от старых к новым :) 

перезалил 1.4.12 с принятыми пулреквестами
