### ISSUE TITLE
Mysql Error modx->select limit=0

### ISSUE THREAD

**Issue by 64j** [evolution-cms/evolution#167]
When creating a query
```php
$modx->db->select('*', $modx->getFullTableName('site_content'), '', '', 0);
```

![image](https://user-images.githubusercontent.com/4653189/29086228-94ae73c8-7c7a-11e7-95ae-af3c041b9beb.png)

Error occurs when checking data
https://github.com/evolution-cms/evolution/blob/develop/manager/includes/extenders/dbapi.mysqli.class.inc.php#L167-L169

**Comment by Pathologic** [comment]
```
 if($limit !== '' && stripos($limit,'LIMIT')!==0)     $limit   = "LIMIT {$limit}";
```
