### ISSUE TITLE
Any help would be welcome :) . KCFINDER will not load:  "LOADING FILES........"

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1676]
hi evo experts ?? 

any help would be appreciated. 

kcfinder in evo1.4.11  is  mcpuk, correct?

This kcfinder is stalled on our new evo1.4.11 install. that codebase was copied from another working evo1.4.11 is perfectly fine - we have cloned it a number of times.

we removed all images from /assets/images and the kcfinder still won't load any images or finish loading - it just says "loading files ...." .

any ideas?

we had this issues before when a bad filename was in /assets/images/ - we have had that a few times, and that was fine - we removed the bad filename. but here, we removed all files here and KCFINDER still will not load.

any ideas? anything we could try? 

any help would be much appreciated.

Regards

junior-EVO

**Comment by fourroses666** [comment]
You have an image in the folder which kcfinder doesnt like. Probably some name with an special character. Like ã. That is wat I suspect. Try removing them with FTP and upload within kcfinder you could try.

**Comment by user83743** [comment]
Thanks MARC

i think it is one jpeg file that kcfinder does not like the size of - not
file size, but width and height. it is about 3700PX X 2900PX. I Downsized
the compression to 80% so the file is just 280KB now. i recut the file
(shaved a few px on the edges) so that it was a brand new jpeg file. still
it would not accept it.

i have reuploaded all other image files and they work fine now. but this
one jpeg file is a problem. i am confident now, as I see it, that it is the
width and height that is the problem. if you or one of the other EVO
experts are curious they could upload a file of approx 3900px x 3900px in
size to their /assets/images/ and see if kcfinder will lock up as it can't
process it.

**Comment by fourroses666** [comment]
There are file size limits set on the configuration section. So it resizes files on upload. Maybe if you increase these sizes it will work. And if it is the max upload MB you can increase the numbers somewhere on the configuration tabs but it could also be a limit from the server.

**Comment by user83743** [comment]
thnaks Marc
