### ISSUE TITLE
Sortable Table in Manage Files

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#169]
I think sorting columns in **Manage Files** is a missing feature: it would be useful to see latest modified files (ie: hacking) and files sizes.

Evo use old **tablesort.js**  library for sorting tables in some manager pages (schedule, messages, view children in documents overview (no more works in 1.3x) )

here you can see all manager pages where is used https://github.com/modxcms/evolution/search?utf8=%E2%9C%93&q=tablesort&type=

this old library does not work properly with complex fields like **file sizes** (does not understand b, Kb, Mb...), so in the past we (tried but) never used for Manage Files page.

I want to replace tablesort.js with a better library : **tablesorter** https://github.com/christianbach/tablesorter.

Actually i've only added to manage files and tweaked to work with file size:
![download](https://user-images.githubusercontent.com/7342798/29186586-3cd5fa38-7e0d-11e7-8ed3-250f2b15f4c8.png)

![download](https://user-images.githubusercontent.com/7342798/29186927-41d4d116-7e0e-11e7-87fe-18b6606815db.png)

what do you think? I continue? :)

**Comment by 64j** [comment]
@Nicola1971 
I changed the sorting as an example here **site/manager/#?a=13**
If everything suits you, i can easily replace it with what you offer.

**Comment by 64j** [comment]
@Nicola1971 
View manager logs

![image](https://user-images.githubusercontent.com/4653189/29188520-f9bf4e5c-7e1b-11e7-891b-d9ba2f55604e.png)

**Comment by 64j** [comment]
@Nicola1971 
Can be replaced in a file **manager/actions/files.dynamic.php**

![image](https://user-images.githubusercontent.com/4653189/29188809-0ddc8034-7e1d-11e7-9243-ba5a2610b182.png)

**Comment by 64j** [comment]
@Nicola1971 It is advisable to change the script written in native JS

For example, as here https://github.com/tristen/tablesort

**Comment by Nicola1971** [comment]
@64j 

> Can be replaced in a file manager/actions/files.dynamic.php

yes, It's like I did ;)

> @Nicola1971 It is advisable to change the script written in native JS
For example, as here https://github.com/tristen/tablesort

nice, but need to check if works with filesize

**Comment by 64j** [comment]
@Nicola1971 No, sorting by file size does not work correctly.(((

**Comment by Nicola1971** [comment]
@64j 
Most of sortable table library does not. I've tested various library but still the same issue with file size.

Suggestion: we can use tablesorter.js just for the file manager and styling like other tables in the manager (and move these tables to native js)

**Comment by 64j** [comment]
@Nicola1971 Here it works

http://tristen.ca/tablesort/demo/

**Comment by Nicola1971** [comment]
@64j  Yes! :)
https://github.com/tristen/tablesort/blob/gh-pages/src/sorts/tablesort.filesize.js

i'm not a js master, but looks good to me :)

**Comment by Nicola1971** [comment]
@64 tested http://tristen.ca/tablesort/demo/ in Manage Files

Pros: works with filesize
Cons: date sort not work properly with Manage Files dates (date + hours)

**Comment by 64** [comment]
Looks like you pinged the wrong guy :) @Nicola1971

**Comment by Nicola1971** [comment]
@64 sorry :)

**Comment by Seiger** [comment]
Added to EVO 3.2.1
