### ISSUE TITLE
Old Unresolved Bugs

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#17]
Do we have to bring old issues & bugs into the new GitHub space per hand, or can that be completed through GitHub directly somehow ?

**Comment by dmi3yy** [comment]
I think better do this by hand 
And delete close old. 



Отправлено с iPhone

**Comment by Pathologic** [comment]
Probably it's possible to do automatically using Github API.

**Comment by Pathologic** [comment]
https://github.com/google/github-issue-mover

**Comment by dmi3yy** [comment]
Finished with https://github.com/dmi3yy/modx.evo.custom/issues

**Comment by bossloper** [comment]
closed?

**Comment by modxuser** [comment]
Think so - so will close it.
