### ISSUE TITLE
Ditto partially not working anymore with evolution-cms 1.3

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#170]
I use Ditto on some websites to generate a xml sitemap. Therefore I have following Ditto call which worked fine with evo 1.2.1:
`[[Ditto? &startID=`0` &dateSource=`editedon` &dateFormat=`%Y-%m-%d` &tpl=`google_sitemap` &displayArchive=`0` &summarize=`500` &total=`500` &orderBy=`menuindex ASC` &depth=`5` &showInMenuOnly=`1` &filter=`type,document,1|searchable,0,2`]]`

After update to evolution-cms 1.3.1 to 1.3.4 there are no Ditto results anymore. I get the message: No results found where there should be hundreds.

If I remove both: `&showInMenuOnly=`1` &filter=`type,document,1|searchable,0,2`` it delivers the then expected results but including also the results that I wanted to exclude with the removed filters.

Is there a solution to this issue?

Other sitemap snippets are no viable solution to this issue.

**Comment by modxuser** [comment]
Sounds the same as [this post](https://github.com/evolution-cms/evolution/issues/168)

**Comment by leonie12** [comment]
I have to correct me regarding the version.
The issue exists in the development branch. 1.3 works as expected.

**Comment by yama** [comment]
Which parameter has a problem? Is it "&filter"?

**Comment by leonie12** [comment]
I had to remove both &showInMenu and &filter to get results instead of no results message.
Now I have 1.3.3 master installed and can not easily test with develop.

**Comment by mnoskov** [comment]
On clean develop install this call works fine.
php 7.1.7

**Comment by mnoskov** [comment]
Can you try parameter `&debug`?

**Comment by leonie12** [comment]
I installed develop from today and it works as it should :-). It seems that something got changed in between.
