### ISSUE TITLE
After update to 1.3.3 enable modifiers breaks page, phx calls partially not working when phx activated

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#172]
After update of a website from 1.2.1 to 1.3.3 and also to development version I have following problem (before update everything worked fine with heavy use of phx):

1. If phx is activated and core modifiers are not then some phx calls (especially those which are nested) are not working any more (no output).
2. If phx and core modifiers are both disabled it´s as far as I can see the same.
3. If phx is disabled and core modifiers are enabled it seems to be the same behavior like 1) on first 

page call after clear cache. On every second and following page call (STRG+F5) I get this error message on a otherwise blank screen:
> Parse error: syntax error, unexpected '[', expecting ';' in /manager/includes/extenders/modifiers.class.inc.php(638) : eval()'d code on line 1

Because of the heavy use of phx I can not tell which is triggering the error.

**Comment by leonie12** [comment]
One example of a phx call that worked before update: 
 `				[*id:isnot=`34`:then=`
				<h3>Info &amp; Service</h3>
                <p>
					[*id:isnot=`4`:then=`<a href="[~4~]">Kontakt</a><br />`:else=`<span>Kontakt</span><br />`*]
					[*id:isnot=`5`:then=`<a href="[~5~]">Impressum</a><br />`:else=`<span>Impressum</span><br />`*]
					[*id:isnot=`30`:then=`<a href="[~30~]">Intern</a>`:else=`<span>Intern</span>`*]
                </p>
				`*]`
After update with phx enabled the only output is `<h3>Info &amp; Service</h3>` (the exterior phx call).
With phx and core modifiers disabled no output of the phx calls at all.
With phx disabled and core modifiers enabled no output at all but rest of page o.k. on first page call. On subsequent page calls again blank page with error message: 
> Parse error: syntax error, unexpected '[', expecting ';' in /manager/includes/extenders/modifiers.class.inc.php(638) : eval()'d code on line 1

**Comment by pmfx** [comment]
While this issue is being solved, you can convert phx calls to "if" snippet calls (if it's urgent). You can find examples here https://github.com/evolution-cms/evolution/blob/develop/assets/snippets/if/readme.html 
It would look like this (not tested):

```
[[if? &is="[*id*]:is:34" &then="
  [[if? &is="[*id*]:not:4"  &then="..." &else="..."]]
  [[if? &is="[*id*]:not:5"  &then="..." &else="..."]]
  [[if? &is="[*id*]:not:30" &then="..." &else="..."]]
"]]
```

**Comment by leonie12** [comment]
This is what I did with most phx calls on another website and what I tried before exactly like you wrote it above. But in this case (nested?) it gave no output at all :-(

**Comment by yama** [comment]
I think that I can fix it if reproduce it in my development environment. It is necessary to make it simple for caring out problems.
````
[*id:isnot=`2`:then=`
<h3>ISNOT2</h3>
    [*id:isnot=`4`:then=`isnot4<br />`:else=`is4<br />`*]
    [*id:isnot=`5`:then=`isnot5<br />`:else=`is5<br />`*]
`*]
````
Does this work?

**Comment by yama** [comment]
Maybe, this is delimiters problem

````
[*id:isnot=`2`:then="
<h3>ISNOT2</h3>
    [*id:isnot=`4`:then=`isnot4<br />`:else=`is4<br />`*]
    [*id:isnot=`5`:then=`isnot5<br />`:else=`is5<br />`*]
"*]
````

Does this work?

**Comment by leonie12** [comment]
@yama: Your first variant is exactly what I had, the forum software ate the delimiters I had originally.
Your second variant does not work. Neither with phx nor with modifiers enabled nor with modifiers disabled.
Is there anywhere an explanation which delimiters when to use when using modifiers? I read some time ago that the new modifiers were delimiter free?

I find it strange that all (!) my phx calls that worked with 1.2.1 do not work any more after update to 1.3.x even when using phx. Am I the only one having those problems? 

I understood the introduction of core modifiers so that those should be a solution for problems with phx. It seems to me a bit like there are more problems with the new modifiers than they solved? 
Maybe it is only that I do not really understand (and can not find a useful explanation) what went in the core, what should happen with modifiers enabled/disabled and which syntax where/when to use, especially when further using phx.

**Comment by yama** [comment]
> Your first variant is exactly what I had, the forum software ate the delimiters I had originally.
Your second variant does not work. 

Thanks, ok. I would repair it later.

**Comment by leonie12** [comment]
`[+phx:math=```[+level+]+1```+]` works with phx enabled, does not work with phx disabled and core modifiers enabled.
I replaced it like other phx calls with if snippet: `[[If? &is=```[+level+]+1``` &math=```on```]]`

**Comment by yama** [comment]
````
[+phx:math="`[+level+]+1`"+]
````
Does this work?

**Comment by leonie12** [comment]
Since I changed former [+wf.level+] to [+level+] it works without the `""` delimiters. 
Because it is used in a wayfinder config file its getting complicated with using  `""` delimiters I think.
See also [https://github.com/evolution-cms/evolution/issues/173](https://github.com/evolution-cms/evolution/issues/173)

**Comment by yama** [comment]
Thanks for your information. I'm sorry if I misunderstood, Is this a problem with Wayfinder?
Specifically, how do I reproduce it?

**Comment by leonie12** [comment]
I do not think that it is a problem with Wayfinder because it works with if snippet. `[[If? &is=`[+level+]+1` &math=`on`]].` inside Wayfinder config file.
I tested your 4 variants above. number 1 delivered a syntax error message on blank screen and 2 to 4 an empty result.

**Comment by yama** [comment]
```
[*id:isnot=`34`:then=`
<h3>Info &amp; Service</h3>
<p>
	[*id:isnot=`4`:then=`<a href="[~4~]">Kontakt</a><br />`:else=`<span>Kontakt</span><br />`*]
	[*id:isnot=`5`:then=`<a href="[~5~]">Impressum</a><br />`:else=`<span>Impressum</span><br />`*]
	[*id:isnot=`30`:then=`<a href="[~30~]">Intern</a>`:else=`<span>Intern</span>`*]
</p>
`*]
```
Is this test case? I'll repair this later.

**Comment by Legatissima** [comment]
Where do you get the If snippet?

**Comment by yama** [comment]
Maybe fixed
