### ISSUE TITLE
Wayfinder [+wf.level+] no output any more

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#173]
It seems that since at least evo 1.3.x, but maybe already since evo 1.2.x `[+wf.level+]` does not deliver any output any more. Some evo versions ago it was working correctly. Wayfinder is 2.1.

**Comment by 64j** [comment]
@leonie12 
```
&rowTpl=`@CODE:<li class="item_[+level+]"><a href="[+wf.link+]">[+wf.title+]</a></li>`

**Comment by leonie12** [comment]
Thanks a lot.
Any idea when [+wf.level+] changed to [+level+]?

**Comment by 64j** [comment]
@leonie12 
I do not even remember.
I very rarely used [+wf.level+]

**Comment by 64j** [comment]
@leonie12 

> Any idea when [+wf.level+] changed to [+level+]?

The changes Wayfinder in version 2.1

**Comment by leonie12** [comment]
Backwards compatibility not desired?

**Comment by 64j** [comment]
@leonie12 
You can ask a question @yama

**Comment by 64j** [comment]
@leonie12 
Can I close the issue?

**Comment by leonie12** [comment]
I think yes. Even though it should be made clear somewhere that [+wf.level+] changed to [+level+]. At least in the documentation (whereever this is).
Better would be when [+wf.level+] would also still be usable (backwards compatibility). I think there will be more people using the old syntax in not so obvious places so that they like me do not recognize the malfunction immediately.

**Comment by 64j** [comment]
@leonie12 The changes were a year ago

**Comment by pmfx** [comment]
@leonie12 I have always used `&levelClass` parameter and then placeholder like `<li[+wf.classes+]>`
 (second example by 64j) You can find docs here http://www.evolution-docs.com/extras/wayfinder/#Wayfinder-TemplateParameters

**Comment by leonie12** [comment]
@pmfx: `&levelClass` is in my case of no use because I use [+level+] for ordering the breadcrumbs like this:
`
<script type="application/ld+json">
{
"@context": "http://schema.org/",
"@type": "BreadcrumbList",
"itemListElement": [
{
"@type": "ListItem",
"name": "abc",
"url": "http://abc.de/",
"position": "1"
},      
{
"@type": "ListItem",
"name": "News",
"url": "http://abc.de/news/",
"position": "2"
},
{
"@type": "ListItem",
"name": "2017",
"url": "http://abc.de/news/news-2017/",
"position": "3"
},
{
"@type": "ListItem",
"name": "August",
"position": "4"
}         
]
}
</script>`

**Comment by leonie12** [comment]
That was fast. Thank you for your work at all this.
