### ISSUE TITLE
Emoji Unicode characters cut off the rest of the content when saved

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1735]
This is a bug I face for long but only now report it...

If you edit a document resource, and add an emoji (e.g. 👍 🥇 😀 to the text), then save the document, the content of the document gets saved only until the emoji. All the rest is cut off.

It would be helpful to let survive the rest of the text and just remove the Unicode emoji that does not make it to the mysql unicode.

**Comment by Dmi3yy** [comment]
What charset you use ? 
Need utf8mb4 than all work

**Comment by q2apro** [comment]
Table `modx_site_content` shows `utf8_general_ci`.

This came from a default installation two years ago.

**Comment by Dmi3yy** [comment]
You can change it 
And emoji will work

**Comment by q2apro** [comment]
I will try and hope there are no side effects... :)
