### ISSUE TITLE
weblogin error after login

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#174]
After login I get this error: `Fatal error: Uncaught Error: Call to a member function get() on null in /assets/snippets/FormLister/plugin.userHelper.php:22 Stack trace: #0 /manager/includes/document.parser.class.inc.php(1365) : eval()'d code(13): require() #1/manager/includes/document.parser.class.inc.php(1365): eval() #2/manager/includes/document.parser.class.inc.php(4562): DocumentParser->evalPlugin('/**\n * userHelp...', Array) #3 /assets/snippets/weblogin/weblogin.processor.inc.php(386): DocumentParser->invokeEvent('OnWebLogin', Array) #4 /assets/snippets/weblogin/snippet.weblogin.php(44): include_once(/manager/includes/doc...') #5 /manager/includes/document.parser.class.inc.php(1407) : eval()'d code(1): require('/manager/includes/doc...') #6 ... in /assets/snippets/FormLister/plugin.userHelper.php on line 22`

After reloading the page the page is working and I am logged in but the content text is the before login text not the logged in text.

This happens after update from evo 1.2.1 to 1.3.3.

**Comment by Pathologic** [comment]
Disable userHelper plugin.
