### ISSUE TITLE
After upgrade from EVO 1.4.11 to 1.4.12 the Snapshop (DB-Backup) does not work anymore (freezes)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1742]
After upgrade from EVO 1.4.11 to 1.4.12 the Snapshop (DB-Backup) does not work anymore, it freezes.

And no errors showing up in the error logs.

It freezes not only the admin area but also the entire frontend.

<br>

PS: I found a file `temp.php` of 300 MB in the `assets/backup` folder. Normally a sql backup is 15 MB and a sql-file.

Bug only with 1.4.12 not with 2.0.4.

**Comment by q2apro** [comment]
When opening the `temp.php` file I could see that EVO CMS tried to backup the *entire* database instead just the evo tables.

Since our DB is 1 Gigabyte, it froze the website...

This is the issue.

**Comment by q2apro** [comment]
The problem should be connected to:

    $result = $modx->db->query('SHOW TABLES');

at https://github.com/evolution-cms/evolution/blob/1.4.x/manager/actions/bkmanager.static.php#L574

Which probably gets all DB tables instead of only the ones from EVO CMS.

I fixed it by adding a LIKE to the query: 

` $result = $modx->db->query('SHOW TABLES LIKE "modx\_%"');`

But `modx` is only for my setup. So this is just a hack.

**Comment by bossloper** [comment]
You could try (not tested):

`$result = $modx->db->query('SHOW TABLES LIKE "'. $modx->db->escape($modx->db->config['table_prefix']) . '%"');`

**Comment by Dmi3yy** [comment]
check in 1.4.12 all work
