### ISSUE TITLE
Can't add link to image in tinymce

### ISSUE THREAD

**Issue by terrybarth** [evolution-cms/evolution#175]
I've got a couple of Evo sites where I'm unable to add a link to an image in TinyMCE. With the image selected, I click on the link button to add a URL, type in the URL, then click on OK and nothing happens. The dialogue box just stays there.

tinymce 4.3.7.2 
Modx Evo 1.2

I googled around and found mention of this issue on other CMSs and it seems the bug has been fixed in the tinymce source but I don't know how to fix this in Modx

My clients use this quite often so I really need a fix for this. 

Alternatively, is there is another editor that I could use? Where do I find one?

I've just read about the evo mgmt change and this issues list. So I apologize if this appears to be a double posting, but after several days on the modx forum no one has responded. I'm hoping you can help.

Thank you!

**Comment by nick0** [comment]
A very similar issue was raised with Evo 1.2.1 (https://github.com/modxcms/evolution/issues/1324
), where I couldn't:

- add a wrapper div to images
- add a link to an image
- add a class to an image

Perhaps the same thing is happening here?

**Comment by fourroses666** [comment]
https://github.com/modxcms/evolution/issues/1348

**Comment by terrybarth** [comment]
So no resolution? 

I have to be very careful with this site in terms of "trying things" to fix a bug. It's a big site, 1000+ pages, and they are coming into their busy season. If their site is down, they start losing money fast. I'll do what I need to do, but I have to be be able to quickly revert if something doesn't work.

Thanks.

**Comment by Pathologic** [comment]
I've checked this issue with TinyMCE 4.6.3, it works as expected.

**Comment by terrybarth** [comment]
The version installed with EVO 1.2 is tinymce 4.3.7.2. 

Is there an upgrade available somewhere?

**Comment by Pathologic** [comment]
Unfortunately, it wasn't released as separate package. Try to copy assets/plugins/tinymce4/ folder and assets/lib/class.modxRTEbridge.php from this repo.

**Comment by terrybarth** [comment]
Wish I could. This is not something I can "try". The site is huge and approaching the height of their site traffic and revenue.

Is there an alternative editor?

**Comment by fourroses666** [comment]
I have uploaded the latest plugin/tinymce4 folder and the lib/class.modxRTEbridge.php file and it works as expected. Thanks @Pathologic 

You can just rename the folder as backup @terrybarth
