### ISSUE TITLE
EVO2 bug: file_put_contents(/core/storage/cache//.htaccess): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1752]
I updated to EVO2. Now one snippet is not working. The code of the snippet is the following:

```
$content = $modx->runSnippet( $snippetname ); // could also be other content, does not matter

include_once(MODX_BASE_PATH."assets/lib/MODxAPI/modResource.php");
$doc = new modResource($modx);
$doc->edit($docid);
$doc->set('content', $content);

$id = $doc->save(false, true);
```

The error message I get now:

> file_put_contents(/public/public/core/storage/cache//.htaccess): failed to open stream: No such file or directory

Error information:

> ErrorType[num] | WARNING[2]
> File | /core/src/Legacy/Cache.php
> Line | 423
> Source | file_put_contents($this->cachePath . '/.htaccess', "order deny,allow\ndeny from all\n");

It seems that the cache root path (`/public/public`) is set two times?!

How to fix this?

<br>

https://github.com/evolution-cms/evolution/tree/2.0.x/core/storage/cache

**Comment by fourroses666** [comment]
I think you need to check your .htaccess file.
