### ISSUE TITLE
Error message when using PHP8.0 - Fatal error: Uncaught TypeError: ReflectionProperty

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1761]
I just tried PHP 8.0 instead of PHP 7.4 and EVO CMS 2.0 does not work.

It shows this error message:

> Fatal error: Uncaught TypeError: ReflectionProperty::getValue(): Argument #1 ($object) must be of type ?object, string given in /core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php:62 Stack trace: #0 /core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php(62): ReflectionProperty->getValue('Illuminate\\Data...') #1 /core/vendor/agelxnash/modx-evo-database/src/AbstractDatabase.php(295): AgelxNash\Modx\Evo\Database\Drivers\IlluminateDriver->__construct(Array) #2 /core/vendor/agelxnash/modx-evo-database/src/Database.php(13): AgelxNash\Modx\Evo\Database\AbstractDatabase->setDriver('AgelxNash\\Modx\\...') #3 /core/src/Database.php(14): AgelxNash\Modx\Evo\Database\Database->__construct(Array, 'AgelxNash\\Modx\\...') #4 /core/src/Providers/DatabaseServiceProvider.php(24): EvolutionCMS\Database->__construct(Array, 'AgelxNash\\Modx\\...') #5 /core/vendor/illuminate/container/Container.php(799): EvolutionCMS\Providers\DatabaseServiceProvider->EvolutionCMS\Providers\{closure}(Object(DocumentParser), Array) #6 /core/vendor/illuminate/container/Container.php(681): Illuminate\Container\Container->build(Object(Closure)) #7 /core/vendor/illuminate/container/Container.php(638): Illuminate\Container\Container->resolve('DBAPI') #8 /core/src/AbstractLaravel.php(586): Illuminate\Container\Container->get('DBAPI') #9 /core/src/AbstractLaravel.php(599): EvolutionCMS\AbstractLaravel->getService('DBAPI') #10 /core/src/ExceptionHandler.php(340): EvolutionCMS\AbstractLaravel->getDatabase() #11 /core/src/ExceptionHandler.php(510): EvolutionCMS\ExceptionHandler->messageQuit('ReflectionPrope...', '', true, '', '/srv/users/serv...', 'Parser / Reflec...', '', 62, '', Array) #12 [internal function]: EvolutionCMS\ExceptionHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #13 {main} thrown in /core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php on line 62

Just to report.

**Comment by Dmi3yy** [comment]
Support php8 only in Evo 3.0

**Comment by fourroses666** [comment]
Is this being fixed in near future? After a while 7.4 is getting old.

**Comment by Dmi3yy** [comment]
We focus on EVO 3 

Evo 2 and 1 only critical bugfix and security.

For support php8 for evo1 and 2 need or donation for that, or do that some one from community

**Comment by fourroses666** [comment]
Oke (probably will update all sites to v3)

**Comment by Dmi3yy** [comment]
Not see any sense update 2.0 for 8.0, need use 3.0 for that, better spent time for 3.0 )

**Comment by q2apro** [comment]
Thanks. 

Your video shows update from 1.4.12 to 3.0 https://www.youtube.com/watch?v=RjOiq35FgW4&t=1s

What would be the steps from 2.0 to 3.0?

Can this be done with the "auto update" feature? :)
