### ISSUE TITLE
No update button on EVO 2.0.3

### ISSUE THREAD

**Issue by Bahbv** [evolution-cms/evolution#1762]
I'm updating some websites to 2.0.4 but i found an inconsistency with the Updater.

On a EVO install on 2.0.1 it's like how its supposed to be:
https://drive.google.com/file/d/1B3mlrOzRb63fE-Ze47OBZ36qLkmEtjFp/view?usp=sharing

But on 2.0.3 the update button doesn't show:
https://drive.google.com/file/d/1_6NW1aHRQtMzQliC26tKGOCjsY4MbSxP/view?usp=sharing

Is there a way i can fix this?

**Comment by fourroses666** [comment]
Maybe updater Extra update. Or clear cache folder. You can probeer that.

**Comment by fourroses666** [comment]
Or use https://github.com/evolution-cms/installer

**Comment by Bahbv** [comment]
@fourroses666 Thank's marc, updating the plugin was the fix, inderdaad.
