### ISSUE TITLE
3.0 RC3 – SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous 

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1763]
After succesful updating to 3.0 RC3 I get this error:
``SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id`, `pagetitle`, `longtitle`, `description`, `alias`, `createdby` from `modx_site_content` left join `modx_document_groups` on `modx_document_groups`.`document` = `modx_site_content`.`id` where `modx_site_content`.`id` = 35 and `modx_site_content`.`deletedon` = 0 limit 1)``

This seems to be caused by the file /assets/snippets/maxigallery/maxigallery.php on line 277.

Deactivating maxigallery snippet solves the issue but is of no help as I need this snippet urgently and can not replace it the way I use it with another gallery snippet. This is outside of my competence. Also there will be other users of maxigallery who will happen to have the same problem.

In Evo 1.4.12 and 2.0.4 everything works as expected.

Any advice to solve the issue is welcome.

**Comment by Dmi3yy** [comment]
What version of maxigallery you use ? 
and what version php on site1,4 and 2.0? and 3.0

**Comment by leonie12** [comment]
Sorry I forgot:

PHP everywhere 7.3.11 (test server local), Evo 1.4.12 on PHP 7.4.7 (production)
maxigallery 0.6

**Comment by leonie12** [comment]
db37a2e fixes the error to be visible.
Unfortunately now the galleries are empty …

**Comment by Ser1ous** [comment]
MaxiGallery use old method for get table prefix. Now i add that method https://github.com/evolution-cms/evolution/pull/1765/commits/9a74461c82075e0a5b84462fb46df302b8327bc1
