### ISSUE TITLE
Incorrect image path in latest dev

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#177]
When adding new image through TinyMCE image path is missing "assets"

![screenshot_1](https://user-images.githubusercontent.com/10888055/29374533-fe1fbad2-82b1-11e7-8d59-4331da9eff10.png)

When I manually add "assets" to image path, image is displayed.

**Comment by 64j** [comment]
@pmfx  See in the configuration

![image](https://user-images.githubusercontent.com/4653189/29375950-8e240004-82bf-11e7-95ef-8da5e06b5e37.png)

**Comment by pmfx** [comment]
Ah! You're right. All good, thanks.
