### ISSUE TITLE
[3.0 RC3] Editor language settings changes nothing

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#1773]
Despite the admin language or chosen option in dropdown for editor language TinyMCA always in EN
![Снимок экрана 2021-01-18 в 18 24 17](https://user-images.githubusercontent.com/5689796/104933898-8714ab80-59ba-11eb-87d4-a459bd89ed90.png)

Could be done only using custom parameters:
![Снимок экрана 2021-01-18 в 18 29 03](https://user-images.githubusercontent.com/5689796/104934368-19b54a80-59bb-11eb-9374-2d59af3ad80a.png)

**Comment by sashabeep** [comment]
Still present on RC3

**Comment by fourroses666** [comment]
Should pick manager language somewhere

**Comment by sashabeep** [comment]
@fourroses666 tried manager default language and other languages from dropdown without result. Only custom param works

**Comment by fourroses666** [comment]
Yes, I mean its a bug. Somehow it needs to choose the correct manager language automaticity like it does in previous versions.

**Comment by Dmi3yy** [comment]
recomend use TinyMCE 5 from console extras
