### ISSUE TITLE
Evolution CMS on localhost with existing DB

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#178]
I was updating my MODX 1.1 to the latest Evo 1.3.3 on my server. Later on I copied all files to my localhost. 

Problem is that after the manager login, the admin interface is overloaded with those messages: 

> A possible CSRF attempt was detected from referer: http://localhost/matheretter/public/manager/index.php

Why is this happening and how to fix it? Thanks

PS: I know I can go to >Configuration and under >Security deactivate "Validate HTTP_REFERER headers". But maybe other users do not have this idea.

**Comment by 64j** [comment]
@q2apro 
assets/cache/siteHostnames.php

```php
<?php
define('MODX_SITE_HOSTNAMES', '');
```
