### ISSUE TITLE
How to include the PHP code of a snippet in another snippet without executing it?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1783]
I have a snippet with 2000 lines of code. I would like to split it.

For this I would like to use PHP's `include`. 

But not to include a PHP file, but a snippet code.

I tried: `$modx->runSnippet('snippet_code_one');` but it does not work. It executes the snippet.

Similar question in the [old forum](https://forums.modx.com/thread/31218/how-to-include-a-snippet-in-a-snippet), not solved.

<br>

Update: 

I have also tried `$modx->getSnippetFromDatabase('edu_builder_path')['content']` which gives me the content of the snippet as text. But `include` cannot be used on a string.

**Comment by Pathologic** [comment]
Rewrite your snippets using classes. https://www.w3schools.com/php/php_oop_what_is.asp
