### ISSUE TITLE
Можно удалить админа из админки

### ISSUE THREAD

**Issue by Ruslan-Aleev** [evolution-cms/evolution#1788]
В админке можно удалить админ-пользователя, даже если вы залогинены под ним :)
И уже не получится ни восстановить ни создать админа заново, хотя при этом админка визуально работает. А при выходе из админки она упадет.

Вряд ли кто-то будет удалять админа, но, наверное, стоит запрещать удалять админ-пользователя, если нет другого админа. А также стоит запрещать удалять пользователя, если ты залогинен под ним.

Evo 3.0

**Comment by Dmi3yy** [comment]
Исправили а то можно было удалить самого себя и последнего админа :)  Ну это не врядли был прецедент :)
