### ISSUE TITLE
Ditto sorting by pub_date leads to no results

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#179]
After commit https://github.com/evolution-cms/evolution/commit/8ff87f09ef88f3d36d0a42707cc6881a13ee4910 this call not working:
```
[!Ditto? &parents=`2` &orderBy=`pub_date ASC`!]
```
because ditto generates query with `LIMIT 0`:
```
SELECT DISTINCT sc.id,sc.published,sc.pub_date,sc.createdon 
FROM `testevo`.`evo_site_content` AS sc 
LEFT JOIN `testevo`.`evo_document_groups` dg on dg.document = sc.id 
WHERE sc.id IN (9,18) AND sc.published=1 AND sc.deleted='0'  AND (sc.privateweb=0) 
GROUP BY sc.id  
LIMIT 0
```
Is this correct behaviour?

**Comment by pmfx** [comment]
Confirmed. Tested latest dev today. No results when using `pub_date` in `orderBy` parameter.

**Comment by pmfx** [comment]
Looking good. Thanks @dmi3yy !

**Comment by dmi3yy** [comment]
Now check. some issue and realize 1.3.4
