### ISSUE TITLE
Problem with <li> in a pagebuilder block + YAMS. 

### ISSUE THREAD

**Issue by Bahbv** [evolution-cms/evolution#1800]
Not sure where to ask this question. So i hope it's not a problem I post it here, otherwise let me know.

I've got a weird problem with YAMS in combination with pagebuilder. If my content has an `<li>` element the output in my pagebuilder block is totally empty.

I use the following in my pagebuilder block TPL:
```[[YAMS? &get=`text` &from=`en::<p>[+txt_en+]</p>||nl::<p>[+txt_nl+]</p>`]]```
If `[+txt_nl+]` or `[+txt_en+]` contains a list with a `<li>` element the output is empty.

I think it has to do with YAMS but I'm not sure how I would troubleshoot/debug this..

If I dont use  YAMS in the TPL like `[+txt_nl+]` it works. Also if I try this in the TPL ```[[YAMS? &get=`text` &from=`en::<p>[+txt_en+]</p>||nl::<p><ul><li>test</li></ul></p>`]]``` it also works.

Any suggestions how to debug this? Someone knows whats up?

**Comment by fourroses666** [comment]
Maybe better to ask here:
https://github.com/Deesen/YAMS/issues or https://github.com/mnoskov/pagebuilder

YAMS is up to date?

**Comment by Bahbv** [comment]
My YAMS is @ 1.2.0 RC4 so upgrading it to the latest on github might work, i will try that first.
And I already asked the same question in /Deesen/YAMS but it doesn't look very active there.
Thanks marc.

**Comment by Bahbv** [comment]
Upgrading didn't work. No reaction on the issue so i just made my own snippet and that works like a charm. I guess the ```[[YAMS? &get=``]]``` works a little weird.

My snippet 'lang'
```
<?php
$en;
$nl;
$lang;

if ($lang == 'nl'){
	echo $nl;
} else if ($lang == 'en'){
	echo $en;
}
```

Usage
```
[[lang? &lang=`(yams_id)` &nl=`[+txt_nl+]` &en=`[+txt_en+]`]]
```

This is enough for my usecase.
