### ISSUE TITLE
Updating 2.0.4 -> 3.0 -> SQLSTATE[42S01]: Base table or view already exists

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1809]
When I would like to upgrade my website from 2.0.4 -> 3.0 I get the following error:

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'evo_active_user_sessions' already exists (SQL: 
create table `evo_active_user_sessions` (`sid` varchar(32) not null default '', `internalKey` int not null default '0', `lasthit` int not null default '0', `ip` varchar(50) not null default '') default character set utf8mb4 collate 'utf8mb4_general_ci')
```

The installer does say:
```
Versie van MYSQL nakijken:WAARSCHUWING!  Uw MySQL versie is:5.5.5-10.4.17-MariaDB-log
When you use version oldest then 5.7.6 engine will be MyISAM in newest version use engine InnoDB.
We recommend that you update your MySQL
```

But the server is very new. Running: MySQL 10.4.17

All the table types before update are InnoDB but when I delete one and use installer to upgrade the type will be MyISAM.

Can anyone tell me what I need to do to fix this?

**Comment by fourroses666** [comment]
On the same server I do have a running 3.0 CMS so I think there is an issue with the installer?

**Comment by Dmi3yy** [comment]
Need use migration script 

today will video

**Comment by Dmi3yy** [comment]
yes for update for 1.4 or 2.0 to 3.0 need use migration script
