### ISSUE TITLE
How to get Save with Continue Editing as Default

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#181]
Enhancement / Request for new admin option: 

Needed: 
- Clicking a page or chunk or snippet, then having "Continue editing" activated by default 

![capture](https://user-images.githubusercontent.com/6764548/29521258-62ff401a-868d-11e7-9c11-87b28812f9ac.PNG)

In old modx evo versions I could add `$_REQUEST['stay'] = '2';` to the ManagerManager Plugin and I got this default behaviour. Does not work anymore. 

It would be a great time saver if this could be implemented. 

Where to put which code to get it working now? Thanks!

**Comment by 64j** [comment]
@q2apro 
Yes, it stopped working after all the buttons were taken out to the style file **style.php**

As a solution, I can suggest an improvement.
Make the default value "remember the last selection" in the configuration,
and add two more values, "Save and close," "Save and continue".

**Comment by q2apro** [comment]
Thanks for your answer. 

I cannot find `remember the last selection` under >System configuration. 

Can you give some more details/instruction? Thanks.

**Comment by 64j** [comment]
@q2apro 
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/style.php#L243

```php
$stay = isset($_REQUEST['stay']) ? $_REQUEST['stay'] : '2'; // default stay = 2
```

**Comment by 64j** [comment]
@q2apro 

> I cannot find remember the last selection under >System configuration.

This I can do and add to the configuration, in next releases

**Comment by Nicola1971** [comment]
@64j I did not notice you moved action buttons in style.php, I really like it! :thumbsup:
it's a nice feature for custom manager themes

but, again, **please announces new relevant changes to the rest of the team**! :smiley:

- To allow developers to use the new features in the development of evo and their extras
- To allow developers to collaborate or pursue your work
- To allow developers and users to discuss the new changes and express any doubts
- To avoid future questions and complaints

I love your work but, please: more communication! 
are you on SLACK?

**Comment by 64j** [comment]
@Nicola1971 
In the change list everything is there

https://github.com/evolution-cms/evolution/pull/4/commits/b48f800646dd154052f59d0490acda3523799e3c

or

https://github.com/evolution-cms/evolution/pull/4

SLACK is, but I do not use it

**Comment by q2apro** [comment]
@64j Maybe I am stupid but I updated to the latest 1.3.6 and still cannot find the admin option to continue editing a resource/snippet.

**Comment by 64j** [comment]
@q2apro As you can see, your Issue did not close, so it has not been done yet

**Comment by q2apro** [comment]
Ah sorry, then I misunderstood. Thanks for the quick reply.

**Comment by q2apro** [comment]
PS: It would be nice if this could be implemented soon. I clicked about 1000 times on this button over the last two weeks :/

**Comment by 64j** [comment]
@q2apro 
Check up, whether all so works?

**Comment by q2apro** [comment]
It works, however, after each new login I need to change it again one time. Would be better to have it persistent.

So I am still using the solution above, changing the file: 

https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/style.php#L243

    $stay = isset($_REQUEST['stay']) ? $_REQUEST['stay'] : '2'; // default stay = 2

Which, however, gets void after each update :/ 

---

Every time I am editing a document I want to save and continue. And I am sure this is for *most users* this way. Why not have this as default?

**Comment by q2apro** [comment]
This tiny issue still p*ss*s me off...

Can we have "Continue" as default please. Everyone saves in between and continues working on the document. After each login, however, it is back to "Save and close".

So annoying... and after each update I need to change the file above.

Request:

1. Please have "Save and Continue Edit" as default.
2. Keep "Save and Close" when user changes to it, as default for the session.

*Thanks*

**Comment by 64j** [comment]
@q2apro 
plugin
```php
$e = &$modx->Event;
if ($e->name == 'OnDocFormRender') {
	$output = "
		<script>
			var stay = document.getElementById('stay');
			for(var i = 0; i < stay.children.length; i++) {
				stay.children[i].selected = false;
			};
			stay[1].selected = true;
		</script>
	";
	
	$e->output($output);
}
```
