### ISSUE TITLE
[3.0] Using migration script: Error: some manager conflict with web user 

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1813]
PHP7.4

Trying to update from well functioning 1.4.12 or also 2.0.4 website using migration script from @Ser1ous I get everytime this error:

> Some manager conflict with web user.

Manager Id | Manager username | Web User Id | Web user username
-- | -- | -- | --
7 | testadmin | 24 | testadmin

The interesting part is that in this case the only existing manager user is testadmin (Id 7). Before running migration script there was no web user testadmin (Id 24). This is everytime newly created when I have deleted this web user either by web user management or by phpmyadmin. This way no update is possible.
This happens also when I delete the only existing manager user and replace him with a newly created one (which has of course no belonging web user).

**Comment by Dmi3yy** [comment]
Need rename web user or manager before update 

Script can merge with same name

**Comment by risingisland** [comment]
Please add extra steps to instructions.

**Comment by leonie12** [comment]
I can' t rename the webuser because he is not existing before running script. There are no conflicting users /emails/names before. The conflicting user is produced by running the upgrade script. Everytime I delete the conflicting webuser (no web user/web user attributes of this user any more in database) I have the exact same user new in the database with a higher id after running upgrade script ending with above error.

**Comment by Dmi3yy** [comment]
https://www.youtube.com/watch?v=RjOiq35FgW4

try few time all work correct
