### ISSUE TITLE
formlister file upload 

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1821]
Hi Evolution pros :)

i looked for "formlister upload " in this https://github.com/evolution-cms/evolution but there is nothing and nothing on google and nothing on http://www.evolution-docs.com/extras/formlister/ . can you give show me a link to an example of Formlister using a file upload setup?  how do we operate file upload size limits? i want to keep the file size limited to 5MB. can  we have 3 file uploads on the same form , each with a limit of 5MB? do we need to change the Evolution file upload limit setting to 5MB too?

thanks in advance for your help

G.

**Comment by Dmi3yy** [comment]
here sample with upload files 

https://docs.evo.im/04_extras/formlister/500_examples/003_otpravka_fajlov.html

**Comment by fourroses666** [comment]
I use this so visitors can upload files in the form.

```
[!FormLister?
&attachments=`image1,image2,image3,image4`
&formTpl=`@CODE:[+form.messages+]
	<form action="[~[*id*]~]" method="post" enctype="multipart/form-data">
		<div class="form-group file">
			<input type="file" class="form-control" id="image1" name="image1" value="[+image1.value+]" />
			<input type="file" class="form-control" id="image2" name="image2" value="[+image2.value+]" />
			<input type="file" class="form-control" id="image3" name="image3" value="[+image3.value+]" />
			<input type="file" class="form-control" id="image4" name="image4" value="[+image4.value+]" />
		</div>
	</form>`
&reportTpl=`@CODE:
...
		[+image1+]<br>
		[+image2+]<br>
		[+image3+]<br>
		[+image4+]<br>`
!]
```

**Comment by user83743** [comment]
thanks @fourroses666 @Dmi3yy . if i try your example @Dmi3yy , the form works, but if the web-form user forgets to enter a required field, and the form reminds them with an error message on the screen, the other fields *keep* their value, but the 2 "attach-file" form elements loose their file values that were attached. i tried adding " value="[+first.value+]"   and   value="[+second.value+]"  "  as that is what works for other textboxes in the form, but that will not work for attach-file form elements.  do you know how to make the attach-files form elements remember their files, while the form error messages are being displayed?

**Comment by user83743** [comment]
thanks @Dmi3yy and @fourroses666 . the form works with file upload now and if an error in the form submission is made by the form user, then all fields remember their previous form data except the attach-files form elements, but that is expected behaviour because of browser security defaults.

**Comment by user83743** [comment]
hi. that form works fine, but can you explain how the "max file size" works? 

we have set the file size to 1000KB but it allows in files that are 1950KB - how is that?

,
    "maxSize" : {
        "params": 1000,
        "message": "Max file size: 2MB"
}

also, if we add a few files of 2MB each, we then reach the server file upload limit, which we are raising currently. but the fail for that was a huge big php error and the css got distorted. any way of having a 'controlled event' if the total files added is great that the server max file upload size?

**Comment by fourroses666** [comment]
Thats too advanced for me.
Maybe Google can help you out on this. 
https://jsfiddle.net/7bjfr/808/

**Comment by Bahbv** [comment]
@user83743 Hi, maxSize works fine for me this is how i use it:
```
&fileRules=`{
		"cv": {
			"maxSize": {
				"params": 1500,
				"message": "Bestand is te groot."
			},
			"allowed": {
				"params": [
					["jpg", "png", "jpeg", "pdf"]
				],
				"message": "Bestandstype wordt niet ondersteund."
			}
		}
	}`
```
