### ISSUE TITLE
[3.0] Middleware

### ISSUE THREAD

**Issue by varelkka** [evolution-cms/evolution#1822]
Возможно, я не правильно что-то понимаю, но если в routes.php прописать

Route::middleware(['isMenagerAccess'])->group(function ($data) {
    dd($data);
});

Такое впечатление, что отрабатывает в любом случае, даже, если прописать вместо 'isMenagerAccess' любой текст, все равно отрабатывает, даже если нет такого класса и ошибок не выдает.

**Comment by Dmi3yy** [comment]
`
Route::middleware(['EvolutionCMS\\Middleware\\CheckAuthToken'])->group(function () {
            Route::get('/sendcode', [UserCodes::class, 'sendcode']);
            Route::get('/usercodes', [UserCodes::class, 'usercodes']);
        });
`

вот так надо тоесть не просто имя мидлваре а с учетом неймспейса иначе да оно не видит такой мидлвар и игнорит его

**Comment by varelkka** [comment]
Не очень хорошо, что не вызывается исключение, если мидлваре не найден.
Со стандартным из примера понятно.

Поясните пожалуйста, как тогда прописывать путь к кастомному мидлаваре, например здесь он живет:
core/custom/packages/main/src/Middleware/IsMenagerAccess.php
То что нужно прописать при вызове в роуте?

Route::middleware(['EvolutionCMS\\Main\\Middleware\\MenagerAccess'])->group(function ($data) {
    dd($data);
});
не срабатывает

**Comment by varelkka** [comment]
увы, даже если вставить ваш пример в чистом виде:

Route::middleware(['EvolutionCMS\\Middleware\\CheckAuthToken'])->group(function () { Route::get('/sendcode', [UserCodes::class, 'sendcode']); Route::get('/usercodes', [UserCodes::class, 'usercodes']); });

и изменить файл CheckAuthToken.php, причем не важно что в нем прописать, хоть return false, хоть что угодно - ничего не происходит, просто выполняется вложенный роут

**Comment by Ser1ous** [comment]
У нас в ядре есть три middleware EvolutionCMS\Middleware\CheckManagerAuth, EvolutionCMS\Middleware\CheckAuthToken и EvolutionCMS\Middleware\VerifyCsrfToken 
Все три только что проверил. И все работают, вот в качестве примера первый из middleware https://testevo4.ser1ous.com/helloworld 
По сути middleware должен возвращать ответ или пробрасывать дальше или выполнять какой-нибудь другой код который вызывает прерывание выполнения.  В качестве примера посмотрите вариант из ядра https://github.com/evolution-cms/evolution/blob/3.x/core/src/Middleware/CheckManagerAuth.php или вот пример из доки где вызывается редирект https://laravel.com/docs/8.x/middleware#defining-middleware
