### ISSUE TITLE
EVO 2.0.4 wrong value for [(site_url)] - correction in evo possible? 

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#1824]
Hello,
after a new installation of EVO 2.0.4 I get a wrong value for [(site_url)].
I think there is a server problem here, but is it also possible to set the correct value (URL) in EVO?

Thank you

**Comment by fourroses666** [comment]
Maybe you need to do some restrictions in .htaccess so when people visit by “wrong” url its being redirected.

manually replace <base href=“Https://my-site.com” /> should work

**Comment by ArnoNymeier** [comment]
Hi Marc,
I will ask the provider ...
At the moment I have set the entries manually - everything works as expected.
The problem was that siteurl directed to a completely different domain although everything is installed in the correct one.
In earlier versions the entry could be set in the config. In the current EVO version (2.0.4) I did not find the option.
Or overlooked? :-)

**Comment by fourroses666** [comment]
I had the same on an other domain. When visiting the site from the "wrong" URL made the site_url change into that.
Maybe 301 redirect. I solved it by manually add the domain in base href.

**Comment by modxuser** [comment]
Maybe as in Evo 1.4.12 => Configuration => Security => Valid Hostnames

**Comment by modxuser** [comment]
Another solution is using the .htaccess file in the root

```
# Non WWW to WWW
RewriteCond %{HTTP_HOST} ^YOURDOMAINNAME.com [NC]
RewriteRule ^(.*) https://www.YOURDOMAINNAME.com/$1 [R=301,L]

# For SSL
RewriteCond %{HTTPS} !^on$
RewriteRule (.*) https://www.YOURDOMAINNAME.com/$1 [R,L]

RewriteCond %{SERVER_PORT} !=443
RewriteRule (.*) https://www.YOURDOMAINNAME.com/$1 [R=301,L]
```

The above takes into consideration that you are on a Secure Server - HTTPS

**Comment by ArnoNymeier** [comment]
@ Marc & modxuser
Setting the page URL in the base href helps. I set that up first.
Unfortunately I didn't find an option to set a valid hostname in the settings.
I do the settings in the .htaccess by default anyway.
OK, I think the hoster configured something wrong.
The site is now running as desired, I'll contact the hoster's support when I get the chance ...
Thanks for your input

**Comment by fourroses666** [comment]
I think you can close the issue, its not really an EVO issue.
