### ISSUE TITLE
Doclister not showing Pagination

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#1825]
I've given it my best for the last 2 days getting a site converted from Ditto to Doclister, have read tons of English and badly translated Russian by Google, so please no answers with "Read the docs" I have :)

I have gotten everything else to work, other than the paginated navigation that Doclister should in theory be showing.

I have a top level category with currently 5 subcategories / pages

The top level category should show the subcategories via a paginated Doclister call in the document body

For testing I have set Doclister to only display one page at a time, which should in my opinion force the pagination to show, it doesn't show :(

I have also set the PREVNEXT to always show, but that's not happening either :(

Here my code:

```
[[DocLister? 
&parents=`[*id*]` 
&showParent=`0` 
&display=`1` 
&depth=`0` 
&sortBy=`menuindex` 
&sortDir=`ASC` 
&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>` 
&tpl=`@CODE:<li><a href="[+url+]">[+menutitle+]</a></li>` 
&paginate=`pages` 
&PrevNextAlwaysShow=`1` 
&pageLimit=`10` 
&pageAdjacents=`2` 
&TplWrapPaginate=`@CODE:<nav class="pagination"><ul>[+wrap+]</ul></nav>` 
&TplFirstP=`@CODE:<li><a href="[+link+]">First</a></li>` 
&TplFirstI=`@CODE:<li>First</li>` 
&TplPrevP=`@CODE:<li><a href="[+link+]">Prev</a></li>` 
&TplPrevI=`@CODE:<li>Prev</li>` 
&TplNextP=`@CODE:<li><a href="[+link+]">Next</a></li>` 
&TplNextI=`@CODE:<li>Next</li>` 
&TplLastP=`@CODE:<li><a href="[+link+]">Last</a></li>` 
&TplLastI=`@CODE:<li>Last</li>` 
&TplPage=`@CODE:<li><a href="[+link+]">[+num+]</a></li>`  
&TplCurrentPage=`@CODE:<li>[+num+]</li>` 
&TplDotsPage=`@CODE:<li>...</li>`]]
[+list.pages+]
```

With the above code the single document is shown, but the pagination doesn't show

Here the tree from the control panel:
![treemenu](https://user-images.githubusercontent.com/1859868/106389129-25086d00-63e2-11eb-868c-2fcda21c13e2.jpg)

The Doclister call is in ID 16, it should show the child documents one at a time. Those not shown in the page should be navigated via the paginated navigation that Doclister should create.

Any and all help is much appreciated :)

**Comment by fourroses666** [comment]
Maybe with CSS you can show PREVNEXT, or custom TPL for that. Display=1?

**Comment by modxuser** [comment]
@fourroses666 

Display 1 is set for testing only, as I currently only have 5 pages

Not sure what CSS can do to help, as the prevnext navigation is not being rendered by Doclister

**Comment by fourroses666** [comment]
debug=1?

Ah thought maybe it was hidden with css but no. I have the same on my test site.
I do see: https://docs.evo.im/en/04_extras/doclister/06_examples.html
But don't know if that will help. I never use pagining except on one test site.

```
&TplNextP=`` 
&TplPrevP=``
```

**Comment by modxuser** [comment]
@fourroses666 

My templates are taken from the default code which can be found in assets/snippets/DocLister/config/core/paginate.json

**Comment by fourroses666** [comment]
Sorry, didn't test myself. Thought it might show some more info. Don't know how to help.

**Comment by modxuser** [comment]
@fourroses666 

Do you have a working solution / call at hand ?

**Comment by risingisland** [comment]
I just tried your call from above, and paginate didnt show for me either, but here is what I was testing earlier, and it works for me:

`[[DocLister? 
	&jotcount=`1`
	&parents=`2` 
	&display=`1`
	&dateSource=`pub_date`
	&tvPrefix=``
	&tvList=`image`
	&prepare=`prepareBlog`

	&summary=`notags,len:260`
	&contentField=`content`
    &introField=``
	
	//&tplOdd=``
	&tplEven=`@CODE:
		<div class="dl_summaryPost" style="margin:-10px;padding:10px;background-color:lightgrey;">
			[+blog-image+]	
			<h3 ><a href="[~[+id+]~]" title="[+e.title+]">[+e.title+]</a></h3>
			<div class="dl_info">
				By <strong>[+author+]</strong> on [+date+].
				<a href="[+url+]#commentsAnchor">Comments <span class="badge">[+jotcount+]</span></a>
			</div>
			[+summary+]
			<p class="dl_link">[+link+]</p>
		</div>` 
		
	&tplFirst=`@CODE:
		<div class="dl_summaryPost">
			[+blog-image+]	
			<h3 ><a href="[~[+id+]~]" title="[+e.title+]" style="color:red;">[+e.title+]</a></h3>
			<div class="dl_info">
				By <strong>[+author+]</strong> on [+date+].
				<a href="[+url+]#commentsAnchor">Comments <span class="badge">[+jotcount+]</span></a>
			</div>
			[+summary+]
			<p class="dl_link">[+link+]</p>
		</div>` 
	&tpl=`@CODE:
		<div class="dl_summaryPost">
			[+blog-image+]	
			<h3><a href="[~[+id+]~]" title="[+e.title+]">[+e.title+]</a></h3>
			<div class="dl_info">
				By <strong>[+author+]</strong> on [+date+].
				<a href="[+url+]#commentsAnchor">Comments <span class="badge">[+jotcount+]</span></a>
			</div>
			[+summary+]
			<p class="dl_link">[+link+]</p>
		</div>` 
	
	&paginate=`pages` 
	&TplWrapPaginate=`@CODE: <div class="pagination"><ul>[+wrap+]</ul></div>`
	&TplPage=`@CODE: <li><a href="[+link+]">[+num+]</a></li>` 
	&TplCurrentPage=`@CODE: <li class="active" ><a href="[+link+]" style="color:red;">[+num+]</a></li>`

	&pageAdjacents=`1`
	&TplDotsPage=`@CODE: <li> ... </li>`
	&TplFirstP=`@CODE: <li><a href="[+link+]" style="color:red;"> (First) </a></li>`
	&TplNextP=`@CODE: <li><a href="[+link+]"> Next > </a></li>` 
	&TplPrevP=`@CODE: <li><a href="[+link+]"> < Previous </a></li>`  
	&TplLastP=`@CODE: <li><a href="[+link+]" style="color:red;"> (Last) </a></li>`
]]

<p style="padding-top:30px;">Showing <strong>[+current+]</strong> of <strong>[+totalPages+]</strong> Pages</p>
<div id="dl_pages">
	[+pages+]
</div>`

See if that is of any help.

**Comment by fourroses666** [comment]
```
	<div class="products">	

		[!DocLister?	
		&display=`4`
		&depth=`2`
		&PrevNextAlwaysShow=`1`
		&pageAdjacents=`1`
		&pageLimit=`1`
		&tpl=`product-tpl`
		&tvList=`price,image`
		&renderTV=`price,image`
		&parents=`7,8`
		&id=`list`
		&showParent=`0`
		&sortBy=`menuindex`
		&paginate=`pages`
		!]

	</div>
	
	<div class="pages">[+list.pages+]</div>
	
	<style>
		.pages{padding:40px 0; text-align:center;}
		.pages a{display:inline-block; padding:4px; width:30px; margin:0 5px; border:1px solid #ccc; text-align:center; color:#ccc;}
		.pages b, .pages a:hover{display:inline-block; padding:4px; width:30px; margin:0 5px; border:1px solid #000; text-align:center; color:#000;}
	</style>
```


&PrevNextAlwaysShow=`1` worked on my testsite. EVO 2.0.4

**Comment by risingisland** [comment]
I think your problem is because you forgot to add the "=" before the @code for all of the Tpl

**Comment by modxuser** [comment]
@risingisland 

Yes, sorry, my bad - have updated my first code block - but still doesn't work

**Comment by fourroses666** [comment]
maybe: &id=`list` and yes you have : and need =
		
		```
		[!DocLister? 
		&parents=`[*id*]` 
		&showParent=`0` 
		&display=`1` 
		&depth=`0` 
		&sortBy=`menuindex` 
		&sortDir=`ASC`
		&id=`list`
		&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>` 
		&tpl=`@CODE:<li><a href="[+url+]">[+menutitle+]</a></li>`  
		&paginate=`pages`
		&PrevNextAlwaysShow=`1` 
		&pageLimit=`10` 
		&pageAdjacents=`2`
		&TplWrapPaginate=`@CODE:<nav class="pagination"><ul>[+wrap+]</ul></nav>` 
		&TplFirstP=`@CODE:<li><a href="[+link+]">First</a></li>` 
		&TplFirstI=`@CODE:<li>First</li>`  
		&TplPrevP=`@CODE:<li><a href="[+link+]">Prev</a></li>`  
		&TplPrevI=`@CODE:<li>Prev</li>` 
		&TplNextP=`@CODE:<li><a href="[+link+]">Next</a></li>` 
		&TplNextI=`@CODE:<li>Next</li>` 
		&TplLastP=`@CODE:<li><a href="[+link+]">Last</a></li>` 
		&TplLastI=`@CODE:<li>Last</li>` 
		&TplPage=`@CODE:<li><a href="[+link+]">[+num+]</a></li>` 
		&TplCurrentPage=`@CODE:<li>[+num+]</li>
		&TplDotsPage=`@CODE:<li>...</li>`
		!]
		
		```

**Comment by fourroses666** [comment]
This works with me:
		
		[!DocLister?	
		&PrevNextAlwaysShow=`1`
		&display=`4`
		&depth=`2`
		&pageAdjacents=`1`
		&pageLimit=`1`
		&tpl=`product-tpl`
		&tvList=`price,image`
		&renderTV=`price,image`
		&parents=`7,8`
		&id=`list`
		&showParent=`0`
		&sortBy=`menuindex`
		&paginate=`pages`
		!]
		
<img width="269" alt="x copy" src="https://user-images.githubusercontent.com/523389/106390317-19b84000-63e8-11eb-8ba7-f5503fd91145.png">

**Comment by risingisland** [comment]
What does the &id=`list` do?

**Comment by fourroses666** [comment]
Good question, I do know. Just happen to need it to show pagination.
Maybe has to do with the pages call: `[+list.pages+]` for multiple paging.

**Comment by modxuser** [comment]
Thanks @fourroses666 

The ID=list did the trick

I think its because "list.pages"

**Comment by modxuser** [comment]
So, just tested

If you have "list.pages" you need id=list

if you have "pages" you don't need id=list

**Comment by risingisland** [comment]
OK, that explains it then. I just use `[+pages+]`

**Comment by modxuser** [comment]
Both produce the same for me

![pagination](https://user-images.githubusercontent.com/1859868/106390700-f1c9dc00-63e9-11eb-8596-b5fbea201430.png)

**Comment by risingisland** [comment]
Maybe "id=" is used if there is more than one call on a page, to distinguish between them?

**Comment by modxuser** [comment]
My output using "page" + "list.pages"

```
<ul>
  <li><a href="#">ID 16</a></li>
</ul>
<nav class="pagination">
  <ul>
    <li>First</li>
    <li>Prev</li>
    <li>1</li>
    <li><a href="">2</a></li>
    <li><a href="">3</a></li>
    <li><a href="">4</a></li>
    <li><a href="">Next</a></li>
    <li><a href="">Last</a></li>
  </ul>
</nav>
```

**Comment by modxuser** [comment]
So just changed this:
`
&paginate=`pages` 
`
to
`
&paginate=`1` 
`

and it still works, so have no idea whats going on LOL, but it works

**Comment by modxuser** [comment]
"list" is refered to from the "id"

so having:
``
&id=`myid`
``
with:
``
[+list.pages+]
``

won't work.

The "id" must be the same as the call at the bottom, so:

```
[[DocLister? 
&id=`myid`
..`]]
[+myid.pages+]
```

**Comment by modxuser** [comment]
Thanks for the help guys :)

I don't suppose anyone has a DLMENU call solely for child documents

A sidebar menu just for the child documents is what I am after, haven't got there yet, but a short cut would be great if available

**Comment by nick0** [comment]
Hi @modxuser,

Not sure if this helps...

Here is a call for a submenu that I use to also show the parent.
```
[!DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&disablePHx=`1`
	&maxDepth=`3`
	&hideSubMenus=`1`
	&showParent=`1`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&parentRowTpl0=`sub-menu-starter`
	&outerTpl=`sub-menu-wrapper`
	&innerTpl=`sub-menu-inner-wrapper`	
	&rowTpl=`sub-menu-row`
	&categoryFolderTpl=`sub-menu-category`
	&orderBy=`c.menuindex ASC`
!]
```

Change &showParent=`1` to &showParent=`0` and remove the parentRow tpl call. The call would look something like this:

```
[!DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&disablePHx=`1`
	&maxDepth=`3`
	&hideSubMenus=`1`
	&showParent=`0`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&outerTpl=`sub-menu-wrapper`
	&innerTpl=`sub-menu-inner-wrapper`	
	&rowTpl=`sub-menu-row`
	&categoryFolderTpl=`sub-menu-category`
	&orderBy=`c.menuindex ASC`
!]
```

**Comment by modxuser** [comment]
@nick0 

Sorry for the late response :)

Thanks for the feedback - got it running with your help

**Comment by nick0** [comment]
No probs @modxuser. Happy to help, Great to hear
