### ISSUE TITLE
[3.0] What happened to DocManager?

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1829]
I often used doc manager. After a fresh install of evo I can't find it anymore. Also I can't find a download possibility?
Did I miss anything? Is it still  somewhere or is there a successor?

**Comment by Dmi3yy** [comment]
Today all to extras. We remove from core but forgot add extras :(

**Comment by fourroses666** [comment]
Its back in Extras

**Comment by modxuser** [comment]
Just to make sure I understand - the docmanager will still work and be supported in all future releases to 100% in Evo 3xx ?

**Comment by modxuser** [comment]
What snippets will be to 100% supported in Evo 3x and will they be supported and or developed in for future releases ?

**Comment by Dmi3yy** [comment]
All snippets work in 3.0 exept snippets who work with webusers.

**Comment by Dmi3yy** [comment]
Some maybe not work but problem not in Evo, php version )

**Comment by scendstudio** [comment]
I've just tried Doc Manager in Evo 3 and it's not working, it's looking for an old language file:
Error : include(/public/manager/includes/lang/english.inc.php): failed to open stream: No such file or directory

**Comment by Dmi3yy** [comment]
fixed, update Doc Manager from extras
