### ISSUE TITLE
[3.0] Code mirror no function

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1832]
In 3.0 neither CodeMirror 1.2b nor 1.5 seem to work. No syntax highlighting happens. In 2.0.4 and 1.4.12 it works.

**Comment by Dmi3yy** [comment]
after update from 1.4.12 all work: 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/669491/106453328-cac6e500-6491-11eb-8602-c2331c5ea89c.png">

**Comment by fourroses666** [comment]
I have no issues too woth codemirror. I have 1.5.

**Comment by fourroses666** [comment]
Maybe clean up Plugins or check other plugins like UserHelper if it interrupts

**Comment by leonie12** [comment]
UserHelper is still deactivated and there are no old/double plugins. On the same server CodeMirror works in the same website and a completely different website in evo 2.0.4 and 1.4.12 but not in both websites in 3.0.
Any further suggestions?

**Comment by fourroses666** [comment]
Maybe something not uploaded correct, overwrite the Codemirror folder? 
https://github.com/evolution-cms/evolution/tree/2.0.x/assets/plugins/codemirror

Set of other plugins to check, try different browser.
Check plugin Events tab if all correct checkboxes selected, clear cache files /assets/cache. I dunno. Just try to debug it.

**Comment by leonie12** [comment]
Thanks for your help. After resetting the system events for this plugin everything works. No idea why they were not as they should.

**Comment by fourroses666** [comment]
Think I had that issue too after upgrading EVO. I think resetting the settings was the solution too or UserHelper, not sure.
Anyway, I'm glad its sorted.
