### ISSUE TITLE
Doclister - Can't get [+count+] to work

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#1835]
I am trying to figure out how to get "count" to display the correct total amount of documents, in this case 65.

As can be seen in the image, the count amount is wrong - it states "1 to 12 of 2", it should have "1 to 12 of 65"

![rendered-call](https://user-images.githubusercontent.com/1859868/106516646-a42b9d00-64d7-11eb-817d-cb06262e42be.jpg)

Everything else works as expected (thanks again go out to those who helped in my other post: @fourroses666, @risingisland, @nick0)

Am I doing something wrong ? 

Here my call:

```
<p>[*longtitle*]: Page [+current+] of [+totalPages+]</p>

[!DocLister? 
&parents=`[*id*]` 
&showParent=`0` 
&display=`12` 
&depth=`0` 
&sortBy=`menuindex` 
&sortDir=`DESC` 
&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>` 
&tpl=`@CODE:<li><a href="[+url+]">[+pagetitle+]</a></li>` 
&paginate=`pages` 
&PrevNextAlwaysShow=`1` 
&pageAdjacents=`2` 
&TplWrapPaginate=`@CODE:<nav class="pagination"><ul>[+wrap+]</ul></nav>` 
&TplFirstP=`` 
&TplFirstI=`` 
&TplLastP=`` 
&TplLastI=``
&TplPrevP=`@CODE:<li class="previous"><a href="[+link+]"><i class="fas fa-chevron-left"></i></a></li>` 
&TplPrevI=`@CODE:<li class="previous"><i class="fas fa-chevron-left"></i></li>` 
&TplNextP=`@CODE:<li class="next"><a href="[+link+]"><i class="fas fa-chevron-right"></i></a></li>` 
&TplNextI=`@CODE:<li class="next"><i class="fas fa-chevron-right"></i></li>`  
&TplPage=`@CODE:<li><a href="[+link+]">[+num+]</a></li>`  
&TplCurrentPage=`@CODE:<li class="active">[+num+]</li>` 
&TplDotsPage=`@CODE:<li>...</li>`!]
[+pages+]

<p>Viewing [+from+] - [+to+] of <strong>[+count+]</strong></p>
```

The old Ditto call is as following:
```
<p>Viewing [+start+] - [+stop+] of <strong>[+total+]</strong></p>
```

**Comment by risingisland** [comment]
Try this and see if it works:
`<p>Showing <strong>[+current+]</strong> of <strong>[+totalPages+]</strong> Pages</p>`

**Comment by modxuser** [comment]
@risingisland 

Totalpages gives the amount of pages the pagination creates - in this case = 6

Have tried that :)

**Comment by modxuser** [comment]
I spent 7 hours looking through extremely badly translated Russian posts in the Russian forum last night and found the following:

Using "Doclister Prepare" to count the amount of child documents.

Snippet created called "counters", snippet content:

```
<?php
$data['count'] = count($modx->getChildIds($data['id']));
return $data;
```

Added the following to my Doclister call:

```
[!DocLister? 
&prepare=`counters` 
..`!]
```

According to the user "webzic" it worked, but I can't get it to work

He / she also noted that the snippet gets all children, whereas it should only get published children, a reference to the api docs was provided, but that's a dead link.

If anyone else can test this that would be great, or if @AgelxNash could possibly shed light into this problem that would also be great.

**Comment by Dmi3yy** [comment]
All work but if you want only published  use https://docs.evo.im/03_develop/03_api/04_getactivechildren.html

**Comment by fourroses666** [comment]
If I add &debug=`2` I do see some result;
`count placeholder: 10`

Where 10 is the amount of pages. Don't know how to preview it.

**Comment by modxuser** [comment]
Thanks for the reply @Dmi3yy my prepare code doesn't output "65", it still only shows "2"

The active children link is great, but I am not a PHP developer, as such I don't know where to add / change the code

**Comment by modxuser** [comment]
@fourroses666

``
<p>Viewing [+from+] - [+to+] of <strong>[+count+]</strong></p>
``

**Comment by fourroses666** [comment]
Ah wanted to help you but you need some other counting as I thought :x

**Comment by modxuser** [comment]
Here part of the debug:

```
 action time: 0.00049 · total time: 0.00361

    Load language paginate.english

action time: 0.00245 · total time: 0.00167

    Load Extender paginate

action time: 0.00064 · total time: 0.00422

    Load Extender prepare

action time: 0.00338 · total time: 0.00152

    Check DocLister parameters

action time: 3.0E-5 · total time: 0.00512

    Load Extender cache

action time: 5.0E-5 · total time: 0.00524

    Run extender cache_DL_Extender

action time: 3.0E-5 · total time: 0.00543

    clean IDs 17 with separator ,

action time: 0.00017 · total time: 0.00535

    set ID list 17

action time: 7.0E-5 · total time: 0.00578

    Load Extender tv

action time: 0.00319 · total time: 0.00637

    SELECT 
      count(*) 
    FROM 
      (
        SELECT 
          count(*) 
        FROM 
          `DBNAME`.`evodb_site_content` as `c` 
        WHERE 
          c.deleted = 0 
          AND c.published = 1 
          AND c.parent IN ('17') 
          AND c.id NOT IN('17') 
        GROUP BY 
          `c`.`id`
      ) as `tmp`

action time: 6.0E-5 · total time: 0.00967

    count placeholder: 65

action time: 5.0E-5 · total time: 0.00986

    current placeholder: 1

action time: 5.0E-5 · total time: 0.00994

    from placeholder: 1

action time: 5.0E-5 · total time: 0.01001

    to placeholder: 12
```

As can be seen above the count placeholder has a number of "65", but it doesn't display it in the rendered placeholder, it still display "2" on-screen

**Comment by fourroses666** [comment]
I have no idea, never needed this. Just to make clear what you need is;
Show the total amount of all pages listed in the results which are 65 in your case?

**Comment by modxuser** [comment]
Yes, correct - my Ditto call is in my first post, which uses "total", Doclister uses "count"

It shows the amount of published docs in a parent - the idea is simple, you show how many per page, whilst showing the full amount

Eg.
page 1: 1-12 of 65
page 2: 13-24 of 65
page 3: 25-36 of 65
etc..

**Comment by modxuser** [comment]
Just a side note:

I found the following on a page in Russian, but I can't remember where I foiund it, I have looked at so many sites and pages in the last couple of weeks, I sadly didn't note all with relevant information

```
 [+from+] - [+to+] of [+count+]
```

To note is, I can't find any documentation, either Russian or English about "from" + "to" as shown here

**Comment by fourroses666** [comment]
It works on my site:
```[!DocLister?	
&id=`list`

<div class="pages">[+list.pages+] [+list.from+] - [+list.to+] of [+list.count+]</div>```

**Comment by modxuser** [comment]
Seems to work Marc

But only when an ID is applied - without an ID it only gives out the number "2"

Seems to be sorted now, many thanks

Will add this to the new Evo Forum as a tutorial

**Comment by fourroses666** [comment]
Maybe you have another DocLister call on the page?
Anyway great its solved.

**Comment by modxuser** [comment]
No, its the only call in the page

But as noted, seems to work :)

**Comment by risingisland** [comment]
Are either of you on Telegram yet?

**Comment by fourroses666** [comment]
I use telegram allot if I need help. Like to be updated although its mainly Russian on the evo group

**Comment by modxuser** [comment]
No, I don't have telegram

The forum should now be enough, so long as the other communities are also willing to help

**Comment by modxuser** [comment]
@fourroses666 

I now know why the [+count+]  placeholders wasn't working

DLmenu + DLcrumbs are also called in the same page - the problem is, they share placeholders, so you have to give them an ID

**Comment by modxuser** [comment]
The full working call:

```
<p>[*longtitle*]: Page [+childlist.current+] of [+childlist.totalPages+]</p>

[!DocLister? 
&id=`childlist` 
&parents=`[*id*]` 
&prepare=`countchilddocs` 
&showParent=`0` 
&display=`12` 
&depth=`0` 
&sortBy=`menuindex` 
&sortDir=`DESC` 
&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>` 
&tpl=`@CODE:<li><a href="[+url+]">[+pagetitle+]</a></li>` 
&paginate=`pages` 
&PrevNextAlwaysShow=`1` 
&pageAdjacents=`2` 
&TplWrapPaginate=`@CODE:<nav class="pagination"><ul>[+wrap+]</ul></nav>` 
&TplFirstP=`` 
&TplFirstI=`` 
&TplLastP=`` 
&TplLastI=``
&TplPrevP=`@CODE:<li class="previous"><a href="[+link+]"><i class="fas fa-chevron-left"></i></a></li>` 
&TplPrevI=`@CODE:<li class="previous"><i class="fas fa-chevron-left"></i></li>` 
&TplNextP=`@CODE:<li class="next"><a href="[+link+]"><i class="fas fa-chevron-right"></i></a></li>` 
&TplNextI=`@CODE:<li class="next"><i class="fas fa-chevron-right"></i></li>`  
&TplPage=`@CODE:<li><a href="[+link+]">[+num+]</a></li>`  
&TplCurrentPage=`@CODE:<li class="active">[+num+]</li>` 
&TplDotsPage=`@CODE:<li>...</li>`!]
[+childlist.pages+]

<p>Viewing [+childlist.from+] - [+childlist.to+] of <strong>[+childlist.count+]</strong></p>
```

![end-result](https://user-images.githubusercontent.com/1859868/106613640-b4408c80-656a-11eb-8011-9b627693a75f.jpg)


To add the total number of published child documents (seen in the above image as "64") you need to carry out the following:

Create a snippet called "countchilddocs" (only used for this example - can be what you want) and add the following to it:

```
<?php
$data['count'] = count($modx->getActiveChildren($data['id']));
return $data;
```

Add the "prepare" parameter (with the name of the snippet you made) to your Doclister call:

```
[!DocLister? 
&prepare=`countchilddocs` 
..`!]
```

Then add the placeholder, where the amount of child docs will be displayed, to your page:

```
[+childlist.count+]
```
