### ISSUE TITLE
[3.0] Update from 3.0.0RC3 

### ISSUE THREAD

**Issue by varelkka** [evolution-cms/evolution#1838]
**1. При обновлении из консоли artisan make:site update 3.x ошибка:**
 - Upgrading roave/security-advisories (dev-master db043e1 => dev-master f7d723a)
  - Upgrading tracy/tracy (v2.8.2 => v2.8.3): Extracting archive
 28/28 [============================] 100%
In FilesystemRepository.php line 206:
file_get_contents(/core/vendor/composer/composer/src/Composer/Repository/../InstalledVersions.php): failed to open stream: No such file or directory  
Run Migrations
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /core/vendor/symfony/string/Resources/functions.php on line 14
Remove Install Directory

После чего сайт и админка отдают HTTP ERROR 500.

**2. При обновлении из админки по кнопке "Update toversion 3.0.1"** 
Процесс проходит по шагам нормально, админка и сайт работают, но теряются все кастомные пакеты

**Comment by Dmi3yy** [comment]
Это проблема на стороне композера, попробуйте сам композер обновить
