### ISSUE TITLE
[3.1.1] Doc Manager 1.1/1.12.2 Error : strstr() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#1839]
PHP 7.4

After having Doc Manager fresh installed from extras I get above error:

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /core/src/Support/DataGrid.php
Line | 153
Source | $this->ds = explode((strstr($this->ds, "\|\|") !== false ? "\|\|" : ","), $this->ds);

Backtrace
--
Illuminate\Support\Facades\Facade::__callStatic('handle', array $var2)manager/index.php on line 205
EvolutionCMS\ManagerTheme->handle(112)core/vendor/illuminate/support/Facades/Facade.php on line 261
Illuminate\View\View->render()core/src/ManagerTheme.php on line 383
Illuminate\View\View->renderContents()core/vendor/illuminate/view/View.php on line 91
Illuminate\View\View->getContents()core/vendor/illuminate/view/View.php on line 122
Illuminate\View\Engines\PhpEngine->get(string $var1, array $var2)core/vendor/illuminate/view/View.php on line 139
Illuminate\View\Engines\PhpEngine->evaluatePath(string $var1, array $var2)core/vendor/illuminate/view/Engines/PhpEngine.php on line 38
Illuminate\Filesystem\Filesystem->getRequire(string $var1, array $var2)core/vendor/illuminate/view/Engines/PhpEngine.php on line 58
Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()core/vendor/illuminate/filesystem/Filesystem.php on line 108
require(string $var1)core/vendor/illuminate/filesystem/Filesystem.php on line 107
include_once(string $var1)manager/views/page/112.php on line 5
evalModule(string $var1, array $var2)manager/processors/execute_module.processor.php on line 71
eval()core/functions/processors.php on line 23
DocManagerFrontend->getViews()core/functions/processors.php(23) : eval()'d code on line 18
DocManagerFrontend->renderTemplates()assets/modules/docmanager/classes/dm_frontend.class.php on line 14
EvolutionCMS\Support\DataGrid->render()assets/modules/docmanager/classes/dm_frontend.class.php on line 36
strstr(Doctrine\DBAL\Driver\PDO\Statement $var1, '\|\|')core/src/Support/DataGrid.php on line 153

**Comment by leonie12** [comment]
Problem persists with evo 3.1.1 and Doc Manager 3.0 updated from extras.

**Comment by Dmi3yy** [comment]
installed all ok, can you send more info

<img width="558" alt="image" src="https://user-images.githubusercontent.com/669491/108475109-55388280-72a1-11eb-85d3-175bc83292d5.png">

**Comment by scendstudio** [comment]
I've also just upgraded Doc Manager to 3.0 (in Evo 3.1.1) and getting the same error. This is an upgraded site from Evo 2 and not a fresh install. I'll try deleting Doc Manager all together and reinstalling.


Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /core/src/Support/DataGrid.php
Line | 153
Source | $this->ds = explode((strstr($this->ds, "\|\|") !== false ? "\|\|" : ","), $this->ds);

**Comment by leonie12** [comment]
Also here after upgrade from 1.4 and 2.0. Tried deinstalling  and reinstalling Doc Manager but with the same error.

**Comment by Dmi3yy** [comment]
fixed
