### ISSUE TITLE
[MultiTV] Button wrong float styles

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#184]
When MultiTV in horizontal mode, button for open filemanager floating at the right side:
<img src="https://monosnap.com/file/zBoWnte78UjqWFoYBrXoXOyPAif0Ia.png">

After removing float styles it becomes normal
<img src="https://monosnap.com/file/VWXVOXeUCoI0DWtTpUHsUwx8meeOe1.png">

**Comment by 64j** [comment]
@mnoskov 
Maybe you forgot to update EVO develop

**Comment by mnoskov** [comment]
I just replaced this file with the new one, but no luck.

<img src="https://monosnap.com/file/8TTu6eoZOfoAn4wtEPCBvVgTwLdsPX.png">

**Comment by 64j** [comment]
@mnoskov 
![image](https://user-images.githubusercontent.com/4653189/29605384-50be9d6c-87f3-11e7-9881-64d8d3b79c94.png)

**Comment by mnoskov** [comment]
Thanks, now it better, but not enough:

<img src="https://monosnap.com/file/8CpsnKhD5Wvzt9RfKB1YGfNNmTzCvq.png">

**Comment by 64j** [comment]
@mnoskov So I separated the multitv styles from the general theme styles.
Next question is already in the styles of multitv))

What version of multitv?

**Comment by mnoskov** [comment]
2.0.12 from extras
