### ISSUE TITLE
[2.0.4] Evo Error when including extras in istallation

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1850]
In v1.4x you could include Modules, Snippets, etc. in the "\install\assets\" to include during installation.

Doing so in v2.x (and I assume in v3x too) results in the following errors. Is there a way to correct this?

![photo_2021-02-03_21-34-50](https://user-images.githubusercontent.com/6113504/107142475-144a8080-6927-11eb-80ca-a9fd09ed844a.jpg)

![photo_2021-02-03_21-37-01](https://user-images.githubusercontent.com/6113504/107142479-1ca2bb80-6927-11eb-850a-da678fa9b3ad.jpg)

@Dmi3yy @Ser1ous

**Comment by Dmi3yy** [comment]
need more info what file you add

**Comment by risingisland** [comment]
Updated module header in .tpl of extra that was being added. All works as intended.
