### ISSUE TITLE
[3.0.1] DocLister не устанавливается из Extras

### ISSUE THREAD

**Issue by cabra** [evolution-cms/evolution#1851]
![doclister01](https://user-images.githubusercontent.com/6485753/107152814-14746b80-697b-11eb-8f63-ba7ec5cd8795.png)
![doclister02](https://user-images.githubusercontent.com/6485753/107152817-150d0200-697b-11eb-8b3f-9206f94bcf0e.png)
И висит при попытке загрузки...

**Comment by Dmi3yy** [comment]
Fixed in 3.0.2 will released in next 2 days

**Comment by fourroses666** [comment]
Can it be closed?
