### ISSUE TITLE
[3.0.1] Не обрабатываются ошибки в контроллере

### ISSUE THREAD

**Issue by varelkka** [evolution-cms/evolution#1855]
Если вызывать методы контроллера напрямую через роутинг, то в случае любых ошибок, возникающих в методе они не обрабатываются, а просто идет редирект  на страницу 404.

**Comment by Dmi3yy** [comment]
Можно пример

**Comment by varelkka** [comment]
Например, есть контроллер PaymentsController с методом pay() в кастомном пакете (не main).

Есть роут:
Route::post('/payments/{method}/{id}', [PaymentsController::class, 'method']);

Если я перейду

**Comment by varelkka** [comment]
Сорри, вопрос снят... в коде не увидел, а когда сюда написал понял, что в роуте post запрос, а проверяю get. Вот на 404 и перекидывало.
