### ISSUE TITLE
Uploadable Flash Types (System Config.)

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#1858]
"Uploadable Flash Types" Should be removed from System Configuration as Flash elements have become obsolete. 

![My_Evolution_Site_Evolution_CMS_Manager_](https://user-images.githubusercontent.com/6113504/107750685-46d3ef00-6d14-11eb-9479-28bea61c14c8.png)

**Comment by fourroses666** [comment]
And Uploadable file types, remove .fla, .flv, .swf
