### ISSUE TITLE
Something went wrong message Evo 1.3.4

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#186]
Using top Navigation and click on Chunks/Teplates/Plugins/Snippets. Getting message: Something went wrong.
Chunks where empty but adding a chunk also gives the same message.

Evo 1.3.4

![oops](https://user-images.githubusercontent.com/523389/29672197-d844fe2c-88eb-11e7-84ea-c03a1cad0108.jpg)

**Comment by pmfx** [comment]
"Something went wrong" what a detailed message ;) 
Can't reproduce it in Firefox and Chrome. Maybe try clearing browser cache?

**Comment by fourroses666** [comment]
Will check tomorrow.

**Comment by fourroses666** [comment]
Hmm don't see whats wrong. With a different browser never used on the domain still have the same issue. Maybe I'm the only one with this issue. Its on a test domain started with evo 1.3.0 and updated every new version and I don't think I have changed any settings beside friendly url. Don't see any reports/system happenings. After clicking OK it all works thow. Cleared cache on FTP too.

**Comment by Nicola1971** [comment]
It also happened to me

**Comment by Nicola1971** [comment]
happened to click on home link,  trying to get out from a module error or plugin error. I'm not sure but seems related to the "previous action" (that goes wrong before you click on a menu item).

**Comment by fourroses666** [comment]
*Clean install doesn't have the issue.

**Comment by 64j** [comment]
I fixed in next releases.
After adding a server availability check, this is alert no longer necessary

**Comment by fourroses666** [comment]
Oké thanks 64j 👍
