### ISSUE TITLE
.htaccess overwritten on update

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1861]
If possible, can there be added a check if there is already a .htaccess file in the root?
I noticed the file was overwritten on update and prefer to not have that on update.

**Comment by Dmi3yy** [comment]
Need remove we have th.access and if havent it rebuld from file

**Comment by fourroses666** [comment]
Yes should be renamed to ht.access

**Comment by fourroses666** [comment]
I have added a pull request
