### ISSUE TITLE
[3.0.2] Content/Media type not working

### ISSUE THREAD

**Issue by Bahbv** [evolution-cms/evolution#1862]
Content/media types are not working with evolution 3.0.2 (php 7.4.14). When using an empty template, or with some xml (DLSitemap snippet) and a content type of text/plain or text/xml it still returns the template with `<html>`, `<head>` and `<body>` tags.

This is the same with every content-type.

**Comment by fourroses666** [comment]
Wasn't working in older versions too I think.
I use TemplateEdit3 and looks like that works.

**Comment by Bahbv** [comment]
How does TemplateEdit3 change the header type? 

I mean this selection box:
![content-type](https://user-images.githubusercontent.com/12693117/107787410-591f4e80-6d4f-11eb-8bcc-081d95cec398.jpg)

If it is on text/xml the HTTP header response should return: Content-Type | **text/xml**; charset=UTF-8.
But it returns Content-Type **| text/html**; charset=UTF-8 for every selection.

**Comment by fourroses666** [comment]
Yes you are right. Hmm, stopped working..

**Comment by fourroses666** [comment]
It does work only when I look on mobile (apple and safari) then I looks different. Desktop seems to be ok..

**Comment by Dmi3yy** [comment]
fixed #1870
