### ISSUE TITLE
good, useful EVO feature missing? or moved? or renamed?

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1865]
hi Evo experts. I am in evo 1.4.11 with a few sites. 

i just noticed that it appears that the following feature has been removed or deleted.

we used to be able to go to the 'Site' tab in 'Configuration' and select a new template as the default and make it replace all previous/current default-template instances.

now we can just change a default template for all future web pages, not current web pages.

has that feature been deleted or just moved somewhere else? I can't see it anywhere.

instead, now , we have to go page by page in EVO and set the web page template (the default) to the new default, one by one.

thanks.

**Comment by Dmi3yy** [comment]
Its feature work inside module Doc Manager ) 

all time been there

**Comment by bossloper** [comment]
@user83743 - Also, we now have a growing forum, ideal for this sort of question. It has recently started up, and you are welcome to post any questions over there if you wish:
https://forum.evo.im/

**Comment by user83743** [comment]
thnajks
