### ISSUE TITLE
Ditto is missing placeholders when built-in filters are enabled

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#187]
I have a simple Ditto call:

```
[[Ditto? 
&parents=`88` 
&display=`2` 
&tpl=`ditto-tpl-news` 
]]
```

and my `ditto-tpl-news` chunk is:

```
<div class="c-news">
  [[if? &is=`[+article_img+]:notempty` &then=`@TPL:ditto-tpl-news__img`]]
  <h3><a href="[~[+id+]~]">[+pagetitle+]</a></h3>
</div>
```

Chunk `ditto-tpl-news__img` parsed in by `if` snippet has empty placeholders like `[+id+]`.

**This only happens when core built-in filters are enabled.** 
Placeholders in `ditto-tpl-news__img` are back when I disable built-in filters.

Note: It works with filters enabled only if I move code from `ditto-tpl-news__img` directly into `&then` parameter of `if` snippet (no chunk).

**Comment by yama** [comment]
```
(test_chunk_1)
<div>
  [[if? &is=`[+test_tv+]:notempty` &then=`@TPL:test_chunk_2`]]
	<div><a href="[~[+id+]~]">[+pagetitle+]</a></div>
</div>
```


````
(test_chunk_2)
abcde
````

````
(In resource)
[[Ditto? 
    &parents=`15` 
    &tpl=`test_chunk_1` 
]]
````

This worked. Is something different?

**Comment by yama** [comment]
Disable built-in filters?

**Comment by pmfx** [comment]
Thats not a problem. Try using placeholders like `[+id+]` in `(test_chunk_2)` Placeholders will be empty there. For example `[+id+]` in `(test_chunk_2)` have no value. 

It works when I disable built-in filters.

**Comment by yama** [comment]
OK, thanks. I will fix it later.

**Comment by yama** [comment]
ok, I'll fix it later

**Comment by yama** [comment]
hmm...?
Is this problem related to Ditto? Is not it an issue with 'if' snippets?

**Comment by yama** [comment]
Ditto > if > phpthumb
The placeholder values(each docs and tv) obtained by Ditto does not reach phpthumb.
It might be possible to use $ modx-> mergePlaceholderContent () instead of $ modx-> parseText ().

**Comment by pmfx** [comment]
@yama I don't know what happened, but now first item in Ditto list have no placeholder at all. Second list item is OK.

**Comment by pmfx** [comment]
In Ditto item tpl I have:
```
[[if? &is=`[+article_summary+]:notempty` &then=`not empty` &else=`empty`]]
```
"article_summary" TV is empty but "if" is wrong.

If I add to item tpl
```
[[if? &is=`[+article_img+]:notempty` &then=`@TPL:ditto-tpl-news__img`]]
```
All placeholders are lost.

**Comment by dmi3yy** [comment]
plz check now 

https://github.com/evolution-cms/evolution/commit/2c0ad143eb1801314f90b2649d9cfa15e8c27379

**Comment by pmfx** [comment]
Almost perfect! Great job. 

Still have issue with this https://github.com/evolution-cms/evolution/issues/187#issuecomment-324929718

"ditto-tpl-news" chunk:
```
<div class="c-news">
  [[if? &is=`[+article_img+]:notempty` &then=`@TPL:ditto-tpl-news__img`]]
  <h3><a href="[~[+id+]~]">[+pagetitle+]</a></h3>
</div>
```
"ditto-tpl-news__img" chunk:
```
<div class="c-news__img">
  <a href="[~[+id+]~]">
    <img src="[[phpthumb? &input=`[+article_img+]` &options=`w=200,h=200,zc=1,q=80`]]" alt="[+pagetitle:esc+]">
  </a>
</div>
```
**Result: phpthumb shows "noimage" image.**

BUT this works and thumb is displayed:

"ditto-tpl-news" chunk:
```
<div class="c-news">
  [[if? &is=`[+article_img+]:notempty` &then=`
    <div class="c-news__img">
      <a href="[~[+id+]~]">
        <img src="[[phpthumb? &input=`[+article_img+]` &options=`w=200,h=200,zc=1,q=80`]]" alt="[+pagetitle:esc+]">
      </a>
    </div>
  `]]
  <h3><a href="[~[+id+]~]">[+pagetitle+]</a></h3>
</div>
```

**Comment by dmi3yy** [comment]
I think this bug with IF  he is not understand [+article_img+] in @TPL

**Comment by pmfx** [comment]
@dmi3yy I'm not sure.

"ditto-tpl-news__img" chunk:
```
<div class="c-news__img">
  <a href="[~[+id+]~]">
    [+article_img+]<br>
    <img src="[[phpthumb? &input=`[+article_img+]` &options=`w=200,h=200,zc=1,q=80`]]" alt="[+pagetitle:esc+]">
  </a>
</div>
```

Result:

![screenshot_1](https://user-images.githubusercontent.com/10888055/29814504-dada9ae6-8cad-11e7-96b4-154e8ebe9831.png)

So IF has access to this [+article_img+] placeholder but somehow it is lost in phpthumb there.

**Comment by yama** [comment]
I want simple test case. Perhaps phpThumb and link tags do not matter, right?

"test_chunk_1" chunk:
````
<div>
  [[if? &is=`[+img+]:notempty` &then=`@TPL:test_chunk_2`]]
  <div>[+pagetitle+]</div>
</div>
````

"test_chunk_2" chunk:

````
<div>
    img src="[+img+]"
</div>
````

in resource:
````
[[Ditto? 
    &parents=`15` 
    &tpl=`test_chunk_1` 
]]
````
I will test this. ok?

**Comment by pmfx** [comment]
Sure. This works (no phpthumb call). 
But it don't work when you add phpthumb call to test_chunk_2 like:
```
<div>
  <img src="[[phpthumb? &input=`[+img+]` &options=`w=200,h=200,zc=1,q=80`]]">
</div>
```

**Comment by yama** [comment]
"test_chunk_1" chunk:
````
<div>
  [[if? &is=`[+img+]:notempty` &then=`@TPL:test_chunk_2`]]
  <div>[+pagetitle+]</div>
</div>
````

"test_chunk_2" chunk:

````
<div>
    img src="[[phpthumb? &input=`[+img+]` ]]"
</div>
````

in resource:
````
[[Ditto? 
    &parents=`15` 
    &tpl=`test_chunk_1` 
]]
````
Thanks for reply, I will test this. ok?

**Comment by pmfx** [comment]
OK, I still get path to "noimage" as a result.

**Comment by yama** [comment]
ok, I will repair this later

**Comment by Deesen** [comment]
Hmm I used a fresh install of latest dev and the evo demo-content. In my case it works (Yama´s test-case) so I cannot recreate this issue. `{{test_chunk_2}}` returns correct thumbnails for me.

**Comment by pmfx** [comment]
Hm, thats good news. Is there a way to fix it somehow on working 1.3.6 site?

**Comment by Deesen** [comment]
I am not sure, maybe try replacing `ditto.class.inc.php` ?

**Comment by pmfx** [comment]
Nope, didn't work.

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/issues/187#issuecomment-325648342
It has no problem in my environment. Do you have any other information that might be helpful?

**Comment by pmfx** [comment]
I have this problem on both dev version and 1.3.6. PHP 5.6.31.
But I found that **it works** when I add parameter to "test_chunk_2" in "if" call:
```
[[if? &is=`[+img+]:notempty` &then=`@TPL:test_chunk_2?&img=`[+img+]``]]
```

**Comment by yama** [comment]
Thanks. I want to know the case where a problem occurs. Is there anything else?
