### ISSUE TITLE
Upgrade 3.02 -> 3.1.0

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#1872]
Using System Update from the dashboard it is not upgrading to 3.1.0
Error log shows it is looking for a zip file that does not exist on GitHub:

`PHP Warning: fopen(https://github.com/evolution-cms/evolution/archive/3.1.0.zip): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

**Comment by Dmi3yy** [comment]
Will be tomorrow, need fix one bug with update
