### ISSUE TITLE
В дереве ресурсов отображается pagetitle вместо menutitle

### ISSUE THREAD

**Issue by ultraviolet** [evolution-cms/evolution#1879]
Версия 1.4.12. Конфигурация, интерфейс и представление.
Опция - Название ресурса в дереве [(resource_tree_node_name)]. Задал [*menutitle*], в дереве ресурсов все равно выводится [*pagetitle*].

**Comment by Dmi3yy** [comment]
попробуйте тут поменять: 
https://take.ms/Z3JQa

заменил на другой и вернул по умолчанию теперь все ок

**Comment by ultraviolet** [comment]
Помогло, спасибо.
