### ISSUE TITLE
Ditto in dashboard widget permission issue

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#188]
I have a Ditto call in dashboard widget. 

```
$e = &$modx->Event;
switch($e->name){
	case 'OnManagerWelcomeHome':
		
		$params['id'] = 'widgetBlog';
		$params['parents'] = '253';
		$params['depth'] = '0';
		$params['total'] = '10';
		$params['hideFolders'] = '1';
		$params['showInMenuOnly'] = '0';
		$params['showPublishedOnly'] = '0';
		$params['tpl'] = '@CODE: <a href="index.php?a=27&id=[+id+]">[+pagetitle+]</a><br>';
		$params['orderBy'] = 'pub_date DESC';
		$params['paginate'] = '0';
		$params['language'] = 'polish';

		$output = $modx->runSnippet('Ditto', $params);
		
		$widgets['blog'] = array(
			'menuindex' =>'20',
			'id' => 'blog',
			'cols' => 'col-sm-6',
			'icon' => 'fa-pencil',
			'title' => 'Blog',
			'body' => '<div class="card-body">
				'.$output.'
			</div>'
		);
		
		$e->output(serialize($widgets));
		break;
}
```

In EVO 1.3.3 it was showing latest blog posts (as expected) but now in EVO 1.3.4 Ditto can only display resources that have `Access Permissions` assigned to my `resource group`.

**Comment by yama** [comment]
Thanks, I want a more simpler sample.

**Comment by pmfx** [comment]
OK, here is simple example. 
Plugin to add widget to dashboard with simple Ditto call.
It should display all resources, but somehow it is showing only those that have Access Permissions assigned to my resource group. See screenshot - it is only showing resources with *red lock icon*

And there is a lot of "Resource Array Error" in widget.

**Plugin code:**

```
$e = &$modx->Event;
switch($e->name){
    case 'OnManagerWelcomeHome':
		
    $params['id'] = 'blog';
    $params['parents'] = '0';
    $params['depth'] = '100';
    $params['tpl'] = '@CODE: <a href="index.php?a=27&id=[+id+]">[+pagetitle+]</a><br>';
		
    $output = $modx->runSnippet('Ditto', $params);
		
    $widgets['blogEN'] = array(
      'menuindex' =>'21',
      'id' => 'blog',
      'cols' => 'col-sm-12',
      'icon' => 'fa-pencil',
      'title' => 'Blog',
      'body' => '<div class="card-body">'.$output.'</div>'
    );
		
    $e->output(serialize($widgets));
    break;
}
```

**Result:**

![screenshot_1](https://user-images.githubusercontent.com/10888055/29716651-6c71d406-89ac-11e7-932f-b2d26f8f0d67.png)

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/19cfd3265a38b74adee7f4c9045d194c0abf7fb7
Maybe fixed

**Comment by pmfx** [comment]
Better. No more "Resource Array Error" error and it is respecting hideFolders=1 parameter, but still showing only resources that have Access Permissions assigned to my resource group. Public resources are still hidden.

**Comment by yama** [comment]
ok, I'll fix it later

**Comment by yama** [comment]
Access Permissions have frontend or backend. Which one?

**Comment by pmfx** [comment]
Backend.

**Comment by yama** [comment]
[ditto.class.inc.zip](https://github.com/evolution-cms/evolution/files/1261939/ditto.class.inc.zip)
Would you overwrite this file into assets/snippets/ditto/classes/ ?

**Comment by pmfx** [comment]
Tested. Nothing changed.

**Comment by yama** [comment]
[ditto.class.inc.zip](https://github.com/evolution-cms/evolution/files/1262125/ditto.class.inc.zip)
Try again

**Comment by pmfx** [comment]
Looks good - documents showed up.
But now Ditto tagging don't work. When I click a tag I see blank page. 
Request is `?posts_tags=tag test 2&posts_start=0`

**Comment by yama** [comment]
ok, would you post a new issue? and I also want a example case.

**Comment by pmfx** [comment]
Why new issue? This is directly connected to the last zip file. Something was changed there that breaks basic Ditto tagging.

**Comment by pmfx** [comment]
Now tags works too :) Thanks @yama 👍
