### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#189]
Sorry.. i only tested local
Upgrade from evo 1.3.3 to 1.3.4

sort menuindex:
Parse error: syntax error, unexpected end of file in C:\.....\manager\actions\mutate_menuindex_sort.dynamic.php on line 184

an under Systeminfo:
Parse error: syntax error, unexpected end of file in C:\.....\manager\actions\sysinfo.static.php on line 153

**Comment by 64j** [comment]
@cimt 
What version PHP ?

**Comment by cimt** [comment]
PHP: 5.6.20

**Comment by 64j** [comment]
@cimt 
need enabled short_open_tag in php.ini
```
short_open_tag = on
```

**Comment by cimt** [comment]
Ah. Okay, thank you!

**Comment by yama** [comment]
![2017-08-30 1](https://user-images.githubusercontent.com/73999/29871487-e5a16cce-8dc6-11e7-9245-3f34e9f8c041.png)
My development environment is PHP 7.1, but short_open_tag is "off".
I do not know the reason.

**Comment by 64j** [comment]
@yama 
but how do this work here then?
![image](https://user-images.githubusercontent.com/4653189/29871926-356d49c0-8d96-11e7-806e-192eb3344550.png)


https://github.com/evolution-cms/evolution/blob/develop/manager/actions/mutate_tv_rank.dynamic.php#L127

**Comment by 64j** [comment]
**Note**:
In PHP 5.2 and earlier, the parser does not allow the <?php opening tag to be the only thing in a file. This is allowed as of PHP 5.3 provided there are one or more whitespace characters after the opening tag.


http://php.net/manual/en/language.basic-syntax.phpmode.php

**Comment by yama** [comment]
@64j 
Thanks. I understand that. The PHP official development team certainly states that. Nevertheless, there are cases where short_open_tag is not "on" in the latest environment. Why?

**Comment by 64j** [comment]
@yama here is such a php )

http://php.net/manual/ja/ini.core.php

**Comment by yama** [comment]
Yes, I knew it. Because I am an expert, understand that, but there are may be a lot of beginner users confused.
