### ISSUE TITLE
[3.1.1] [*pagetitle@1*] not working on Error page

### ISSUE THREAD

**Issue by scenduk** [evolution-cms/evolution#1892]
Evo 3.1.1
Using [*pagetitle@1*] to get the title from another resource ID doesn't work on the site error page (404). Using [*pagetitle@1*] shows the current [*pagetitle*] instead. [*pagetitle@1*] works on every other page.

These were introduced in MODX Evolution 1.1 (Feb 29, 2016) so not sure if they're deprecated now?

Using DocInfo works.

**Comment by fourroses666** [comment]
I had some weird issue with that too. Showed the current pagetitle. After clearing cache it looked like it worked again. I did remove it just to be sure is wouldnt happen again

**Comment by fourroses666** [comment]
I did check it on my errorpage with EVO 3.1.2 and it seems to work. 
I have added a Chunk in the Template and placed [*pagetitle@4*] which gave the correct pagetitle of ID 4 and not the current.

**Comment by fourroses666** [comment]
I think the issue could be [(cache_type)] in Config.
When I select $_GET it stops working. With default it does work.

**Comment by fourroses666** [comment]
There is some weird behaviour.. I really don't understand what's happening. 
It works now but a couple of times it didn't. Playing with "clear cache" and "saving / playing with configuration" made it work again..

**Comment by scenduk** [comment]
I've tried changing the cache type, clearing the cache etc. but nothing makes it work for me. [*pagetitle@1*] is always the [*pagetitle*] on the error/404 page - I'll just stick to using DocInfo for now.

**Comment by Dmi3yy** [comment]
Will check this issue

**Comment by Dmi3yy** [comment]
For info: it's not work on 1.4 it can't be work :)i i found why and fix in 3

**Comment by fourroses666** [comment]
Yea seems to be and old issue nobody noticed probably. 
Good find ScendUK.
