### ISSUE TITLE
Ditto does not recognize &dateSource parameter any more

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#190]
Since update to 1.3.4 Ditto seems to use publishedon or another date (for some pages even some years before publishedon) date instead of editedon which it should and did before.

Ditto call:
```
[[Ditto? 
&startID=`0` 
&dateSource=`editedon` 
&dateFormat=`%Y-%m-%d` 
&tpl=`google_sitemap` 
&displayArchive=`0` 
&summarize=`500` 
&total=`500` 
&orderBy=`menuindex ASC` 
&depth=`5` 
&showInMenuOnly=`1` 
&showPublishedOnly=`1` 
&filter=`type,document,1|searchable,0,2`
]]
```
Ditto tpl:
```
<url>
    <loc>[(site_url)][~[+id+]~]</loc>
    <lastmod>[+date+]</lastmod>
    <priority>[+priority+]</priority>
    <changefreq>[+changefreq+]</changefreq>
</url>
```

**Comment by sashabeep** [comment]
Quick solution - move to DLsitemap
I think, nobody check Ditto for compatiblity to current version :(

**Comment by yama** [comment]
Thanks, I want a more simpler sample.

**Comment by leonie12** [comment]
@sashabeep: DLsitemap is not usable for me because I have to include also the pic pages of a gellery with separate MaxiGallery calls.
I need Ditto only for the rows not for the head.

@yama: Reducing the Ditto call to `   [[Ditto? &startID=`0` &tpl=`google_sitemap`]]` delivers the date 1970-01-01 for all pages. Including `&dateSource=`editedon`` delivers the same weird dates as in my first report above.

**Comment by dmi3yy** [comment]
Its no problem use prepare for add pics

Отправлено с iPhone

**Comment by leonie12** [comment]
@dmi3yy: I have no clue what you mean with use prepare? Before Evo update everything functioned fine for years. I think there is a bug with Ditto and this should be fixed.

**Comment by pmfx** [comment]
Confirmed. 

@yama 

1. Ditto is ignoring this

```
$params['orderBy']='pub_date DESC';
$params['dateSource']='pub_date';
```

It is always using createdon date and ASC order.

2. Also `[+date+]` placeholder in item tpl is always using createdon date.

3. Also something like ```[+pub_date:date=`%d.%m.%Y`+]``` in item tpl don't work when phx plugin is deleted from filesystem (built-in filters enabled).

**Comment by Jako** [comment]
An updated site shows strange dates like `26.08.9947` in pub_date for some reason. The DB table contains `1435599947` which is `29.06.2015`

**Comment by leonie12** [comment]
@Jako: Same problem here. This is what I mentioned with weird dates.

**Comment by yama** [comment]
@pmfx 
````
[!Ditto?orderBy='pub_date DESC'&parents=2&tpl='<a href="[+url+]">[+pagetitle+]</a><br />'!]
````
I wrote such a snippet call and tried it, but it seems to work correctly according to the value of pub_date.

**Comment by pmfx** [comment]
I tested blog list on dev version sample site. It doesn't work. 
```
&dateSource=`pub_date` &orderBy=`pub_date DESC`
&dateSource=`pub_date` &orderBy=`pub_date ASC`
```
Always using createdon date.
Sorting ASC is ignored.
[+date+] placeholder in ditto_blog chunk is using createdon date even though &dateSource is set to pub_date

**Comment by pmfx** [comment]
Also in "sample site" blog, there is a Reflect snippet call under Ditto pagination:
```
[[Reflect? &config=`wordpress` &dittoSnippetParameters=`parents:2` &id=`wp` &getDocuments=`1`]]
```
But it is showing error on page:
`The Ditto object is invalid. Please check it.`

**Comment by yama** [comment]
If the "&dateSource" parameter exists, will it not work?
Or is there problem loading pub_date field or chunk?

**Comment by pmfx** [comment]
If "&dateSource" is empty, I think editedon is used (should be created on).
If "&dateSource" is pub_date, createdon is used (should be pub_date).
"&orderBy" set to pub_date is ignored in both examples.

**Comment by leonie12** [comment]
Also if "&dateSource" is editedon it seems that pub_date is used (although this seems sometimes to be empty).

**Comment by dmi3yy** [comment]
Fixed. plz tests
code:
http://take.ms/x9C6h
results:
http://take.ms/lpedP

**Comment by pmfx** [comment]
@dmi3yy looks good, dates and sorting works correct for me.

**Comment by pmfx** [comment]
@dmi3yy I'm not sure if it is related to this commit but if I add `$params['tagData']='documentTags';` to the call I get error.

> Trying to get property of non-object
> « MODX Parse Error »
> Error : array_multisort(): Array sizes are inconsistent
> File assets/snippets/ditto/classes/ditto.class.inc.php(508) : eval()'d code

![screenshot_1](https://user-images.githubusercontent.com/10888055/29779260-4a5bf5e6-8c12-11e7-80c4-da3d6643d369.png)

**Comment by dmi3yy** [comment]
Not the same but i know how fix it. 
Do this tomorow

Отправлено с iPhone

> 28 авг. 2017 г., в 18:00, Piotr Matysiak <notifications@github.com> написал(а):
> 
> array_multisort(): Array sizes are inconsistent

**Comment by leonie12** [comment]
With actual develop version one problem solved, new issue produced :-(.

&dateSource=`editedon` seems to work.

But now I have with following Ditto tpl:
`<url>
    <loc>[(site_url)][~[+id+]~]</loc>
    <lastmod>[+date+]</lastmod>
    <priority>[+priority+]</priority>
    <changefreq>[+changefreq+]</changefreq>
</url>`

the issue that 1. priority and changefreq output is empty and 2. startpage is included twice. One times as it should with correct date. One times with this output:
 `<url>
<loc>http://siteurl/[~~]</loc>
<lastmod>1970-01-01</lastmod>
<priority/>
<changefreq/>
</url>`

**Comment by pmfx** [comment]
@leonie12 it may have to do smth with missing placeholders: https://github.com/evolution-cms/evolution/issues/187

**Comment by dmi3yy** [comment]
test this on demo site: 
http://take.ms/j3wpU
http://take.ms/Kbrz9i

results: http://take.ms/qFvYP


test with on modifiers and with ofа modifiers all ok 
and test with PHx  all ok

**Comment by dmi3yy** [comment]
test with @CODE in tpl work too

http://take.ms/cyGdjY

**Comment by leonie12** [comment]
@dmi3yy: In your screenshot priority and changefreq are empty/have no output. I would not tell that "everything o.k."

**Comment by dmi3yy** [comment]
yes i havent this tv. 

but now test #187 and see error with tv

**Comment by dmi3yy** [comment]
plz check now 
https://github.com/evolution-cms/evolution/commit/2c0ad143eb1801314f90b2649d9cfa15e8c27379

**Comment by leonie12** [comment]
Works :-)

**Comment by pmfx** [comment]
Date works! :)

**Comment by yama** [comment]
@dmi3yy Thanks!
