### ISSUE TITLE
@Dmi3yy - formlister data being passed back into the form

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1906]
Hi @Dmi3yy . would you mind sharing some of your experience here please 🙂 . i tried your formlister form examples and i tried https://docs.evo.im/en/04_extras/formlister/500_examples/002_elementy_upravleniya.html and for the "RADIO BUTTONS" and "TICK BOXES" neither form works - they will not **remember** the selected radio button or tickbox values, if there is an error in the form , for example, when the form user forgets to fill in a required field or forgets the recaptcha . The forms DO remember the values of textboxes but not radio buttons or tickboxes. do you know how to fix that? A formlister form with radio buttons and tickboxes is not very useful if it always forgets the values in the radio-button/tickbox selection blocks. thanks in advance.

i tried those formlister form examples on a few browsers and none of them have a working form example where the form will remember the radio button or tickbox data being passed back into the form. so it's not browser specific. all browsers are the same. all browsers pass back the values entered into textboxes but none pass back radio button data or tickbox data. any ideas? any advice would be much appreciated.

**Comment by fourroses666** [comment]
Do you have examples of sites where it does work? Because AFAIK a browser only remembers textfields. So you will need a validation before submitting, use ajax or use cookies/localstorage to store the states.

**Comment by user83743** [comment]
:) i didn't see what I was to try to make the formlister form work

**Comment by user83743** [comment]
do you have any examples of formlister forms that have a radio button, checkbox or dropdown list where the form remembers that data if the form has to resubmit itself?

**Comment by modxuser** [comment]
This issue has been resolved.

See the tutorial on the forum: https://forum.evo.im/d/83-formlister-remember-inputs-options-on-form-re-submission
