### ISSUE TITLE
FormLister Filling up Event Log since update to 1.8.1

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#1908]
Since updating to Evo 1.4.13 with FormLister 1.8.1, Formlister has been filling up the event log

![error-log-overview](https://user-images.githubusercontent.com/1859868/110494598-0b9ac500-80f4-11eb-983c-cfd28be9c795.png)

![error-report](https://user-images.githubusercontent.com/1859868/110494625-12293c80-80f4-11eb-8564-fa2d991f8a2f.png)

Every time a form is shown in the front-end, an event is added to the event log

If I understand correctly, in the Formlister Docs the "controller" is set to "form" as default, as such, it doesn't need to be added to the call

So the error I am getting shouldn't be there, or have I understood this wrong ?

**Comment by Pathologic** [comment]
It's the error, update FormLister from Extras.

**Comment by modxuser** [comment]
@Pathologic 

Thanks for your help :) it's much appreciated
