### ISSUE TITLE
Still unhappy with Updater

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#191]
After hitting the button Update to 1.3.4 :)

Blank page with
/home/CUT/temp/evolution-1.3.4/manager
Warning: Cannot modify header information - headers already sent by (output started at /home/CUT/update.php:114) in /home/CUT/update.php on line 120

Manually typed /install/ like in previous issues :)
When it will be work as expected?

**Comment by FeAlSe** [comment]
Hello, neighbors. Chunks and snippets also disappeared?

**Comment by sashabeep** [comment]
@FeAlSe in my case they are right in place, just minor changes in CSS, maybe you have browser cache issues?

**Comment by dmi3yy** [comment]
Cannot modify header information - its bug with server setting  better solution use https://github.com/evolution-cms/installer for update
