### ISSUE TITLE
Ошибка в функции evo.checkConnectionToServer function (manager/includes/header.inc.php) - EVO v.1.3.4

### ISSUE THREAD

**Issue by mib1001** [evolution-cms/evolution#192]
Если на локальном сервере заходим в панель администрирования типа "localhost:8008/mysite/manager" всплывает сообщение - "Сервер недоступен...."
Устранить ошибку можно изменением строки 292 в файле "manager/includes/header.inc.php":
Исходный текст:
xhr.open('HEAD', '//' + window.location.**host** + window.location.pathname.replace('index.php', 'includes/version.inc.php') + '?time=' + new Date().getTime(), false);
Исправленный текст:
        xhr.open('HEAD', '//' + window.location.**hostname** + window.location.pathname.replace('index.php', 'includes/version.inc.php') + '?time=' + new Date().getTime(), false);

**Comment by 64j** [comment]
посмотрите повнимательнее, возможно у вас старая версия?
https://github.com/evolution-cms/evolution/blob/develop/manager/includes/header.inc.php#L292

**Comment by 64j** [comment]
@mib1001 
может быть заменить надо на "**window.location.host**", чтобы порт тоже указывался?
