### ISSUE TITLE
Configuration small improvements and defaults

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1922]
When installing EVO 3.1.2 some default settings needs to be changed.

1. latest feed links updates are from 2018 (also not https). These needs to be replaced or removed. If so the dashboard widgets needs to be removed too. (I remove them on default thow)
2. --is oke-- Document cache type `[(cache_type)]` -> shouldn't that be the default selected one? I don't know the differences but I always set it to default and not `$_GET parameters`
3. Using .html as url suffix `[(friendly_url_suffix)]` after is so 2000, that should be removed/blank.

**Comment by fourroses666** [comment]
Seems that using $_GET is faster. 
You can use all snippets and plugins like: [[ .. ]] instead of [! .. !]. 
There is an exception for FormLister which does needs to have [!ForrmLister!].

**Comment by bossloper** [comment]
If it matters just watch out for the size of your cache, it can get very large depending on the parameters and bots.

**Comment by fourroses666** [comment]
> c

Would this file get large? siteCache.idx.php

**Comment by bossloper** [comment]
I don't know how much the cache has changed under 3.x. You might have multiple cache files per resource page, one for each parameter value(s)

**Comment by fourroses666** [comment]
Oke thanks for explaining.
