### ISSUE TITLE
[3.1.2] some errors

### ISSUE THREAD

**Issue by masco123** [evolution-cms/evolution#1927]
Hi, error report

### When optimize overhead
 [Tools]->[Backup]
File: .../processors/optimize_table.processor.php:19

> Call to undefined method EvolutionCMS\Database::optimize()

### Can't create new resource
[Configuration]->[Site]->[Increment Resource ID method]->Selected 'Minimum missed ID'
File: .../illuminate/database/Connection.php:678

> Illuminate\Database\QueryException #42S22
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'evo_site_content.id +1' in 'on clause' (SQL: select min(`evo_site_content`.`id`) as aggregate from `evo_site_content` left join `evo_site_content` as `irjn_t1` on `evo_site_content`.`id +1` = `evo_t1`.`id` where `evo_t1`.`id` is null)

### When preview of unpublished resource
be rendered Error page.
Is this normal function?

thank you :)

**Comment by Ser1ous** [comment]
Optimize table function https://github.com/evolution-cms/evolution/pull/1944

**Comment by Ser1ous** [comment]
upbulished resource https://github.com/evolution-cms/evolution/pull/1945
