### ISSUE TITLE
[3.1.2] Manager Language defaults to BG

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#1932]
Every time I visit the configuration page the Manager Language defaults to BG.

**Comment by Dmi3yy** [comment]
not see problem 
https://take.ms/A5Iac

**Comment by BBloke** [comment]
🙄 damn. Must be something else unique to me.

Definitely changes that drop down to BG on access to configuration.

The site was installed and updated over many years.

It's something I can live with but wasn't sure if anyone else has experienced it.

**Comment by fourroses666** [comment]
https://github.com/evolution-cms/evolution/issues/1934#issuecomment-882041300
