### ISSUE TITLE
Maxigallery and sort

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#194]
Evo:1.3.4 / php 7

i use this: [https://github.com/Nicola1971/maxigallery](url)
**after sorting and safe nothing has change!**

and this: [https://github.com/yama/MaxiGallery](url)
**the "sorting popup" will not open!**

**what is the future from Maxigallery in evolotion???**
or is there another one Gallery for evo (with englisch description!!)

**Comment by Nicola1971** [comment]
maybe something related to mootools?

i will check soon

**Comment by bossloper** [comment]
If maxigallery is to live on then replacing the drag sort with a jquery version (is tv order in core using jquery?) would be the way to go. It would remove the conflict between jquery and mootools.

I still like maxigallery because of the option to store images on a per resource basis folder rather than uploading to the central resource area. Makes sense for temporary news type resources where the image can be automatically removed when the news item is old and deleted.

**Comment by dmi3yy** [comment]
We want fully remove mootols from EVO. Then correct way remove motools from maxigallery

**Comment by pmfx** [comment]
Best thing about MaxiGallery is that it can be used on frontend by webusers :) It would be cool to have plugin or MM widget, to manage MG in manager on resource edit.  Like EvoGallery. And module too, but thats off topic ;)

**Comment by dmi3yy** [comment]
i use SimpleGallery for all this 

add images from frontend and webusers no problems 

here my site : http://velodom.com.ua

**Comment by Nicola1971** [comment]
maxigallery seems using prototype as default js library

**Comment by Nicola1971** [comment]
tested in evo 1.2.2 maxigallery works, so is something related to 1.3.x

**Comment by pmfx** [comment]
@dmi3yy thanks, I will give SimpleGallery a try.

**Comment by dmi3yy** [comment]
What the last version on MaxiGallery ?

**Comment by pmfx** [comment]
Last was 0.6 https://github.com/extras-evolution/MaxiGallery
BTW @dmi3yy SimpleGallery is very nice - thanks. I may replace EvoGallery with it :)

**Comment by dmi3yy** [comment]
You can use this code for move image from EvoGallery to SimpleGallery
http://modx.im/blog/fast-solution/5247.html

**Comment by dmi3yy** [comment]
I think better  create issue here: 
https://github.com/extras-evolution/MaxiGallery

@Nicola1971 can you get me access to site with maxigallery on 1.3 i test for work and fix

**Comment by yama** [comment]
https://github.com/extras-evolution/MaxiGallery
The repository is here. Maybe, this also has problems.
The included Javascript libraries are too old. MaxiGallery can not be maintained.

**Comment by Nicola1971** [comment]
@dmi3yy sorry, tested only on localhost. I do not use maxigallery for years in my projects.

this is the error in console 
![2017-08-29](https://user-images.githubusercontent.com/7342798/29813185-91a61fa2-8ca9-11e7-8c09-93fbffc24870.png)

I agree with @yama , scriptaculous and other maxigalley Javascript libraries are too old.
Probably, we can fix for 1.3, but not mantain

**Comment by dmi3yy** [comment]
turn off Quick Manager+

EVO no add any to frontend and may be only conflict with 2 plugins

**Comment by Nicola1971** [comment]
@dmi3yy  I had thought the same but QM is disabled.
need to test with another frontend template (maybe a conflict with bootstrap.js?)

**Comment by dmi3yy** [comment]
need test without any js libи 

comments all js exept gallery in template and test )

**Comment by Nicola1971** [comment]
opening the sort image popup still cause the same error, with or without template javascripts.

**Comment by Nicola1971** [comment]
Maybe I found a trick

@cimt try 

``` &disable_js_libs=`1`  ``` in your maxigallery call
this parameter makes MaxiGallery not include mootools, scriptaculous, prototype js libraries

seems working for me

**Comment by Nicola1971** [comment]
@cimt any news?

**Comment by cimt** [comment]
@ Nicola1971...Thanks for your efforts.
Sorry for late replay!
I tested many scripts and now, i'm not sure which script i have in use, but it works.
I Test your script again and i will reply as soon as possible.

**Comment by dmi3yy** [comment]
https://github.com/extras-evolution/MaxiGallery/issues

**Comment by cimt** [comment]
Sorry, my mistake! maxigallery 0.7  and 0.6 works!!! (In 0.6 "mootools" must be reactivated)
**In my case, i use js before the closing body tag**.
Some time ago, i changed "regClientStartupScript" to "regClientScript"
in "maxigallery.php"
