### ISSUE TITLE
Evo2: Is it safe to update all tables from "MyISAM" to "InnoDB"?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1941]
Running Evo2 - Is it safe to update all tables from "MyISAM" to "InnoDB"?

Can I do this before a migration? 

I guess the migration from EVO2 to EVO3 will still work. Even if I change the database tables manually to "InnoDB"?

**Comment by Dmi3yy** [comment]
All been ok, change type in db not broke any

**Comment by q2apro** [comment]
Thank you 👍 I did the change. Seems to run without problem.
