### ISSUE TITLE
parseText - не заполняются плейсхолдеры, если в массиве они переданы как NULL

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#195]
Имеем ситуацию - ассоциативный массив, в котором содержится информация из строки базы данных.
Если в строке базы данных какие-то поля выставлены в NULL, то и при операции fetch_....() при обработке запроса получим значения NULL в соответствующих элементах массива.

И если такой массив передадим далее в функцию $modx->parseText(), то плейсхолдеры с соответствующими ключами не распарсятся (хотя в более старых версиях ModX (нарпимер, 1.1) они заменялись пустыми значениями).

Все дело в том, что существование индекса массива проверяется функцией isset(), а не array_key_exists(), которая даже если элемент массива задан, но имеет значение NULL - выдает false.

**Comment by dmi3yy** [comment]
принял

**Comment by Dreamer0x01** [comment]
Дмитрий, я все правильно сделал с pull request? А то я что-то запутался в репозиториях..

**Comment by dmi3yy** [comment]
Да все правильно )

**Comment by Dreamer0x01** [comment]
Спасибо.
