### ISSUE TITLE
Backup section in manager can't optimize tables

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1950]
Call to undefined method EvolutionCMS\Database::optimize()

Error information |  
File | /home/user/domains/mysite.nl/public_html/manager/processors/optimize_table.processor.php
Line | 19

**Comment by ArnoNymeier** [comment]
the same error message was given when optimizing the overhead at this point: System Info -> Database Tables -> Overhead

File | `...manager/processors/optimize_table.processor.php`

[64j](https://github.com/64j) has posted the info about a fix [https://github.com/evolution-cms/evolution/issues/1971](https://github.com/evolution-cms/evolution/issues/1971)
