### ISSUE TITLE
[3.1.3] [~id~]  и friendlyUrl

### ISSUE THREAD

**Issue by altlc** [evolution-cms/evolution#1963]
Обновился с 2 на 3.1.3 сломалась генерация ссылок 
` [~id~]`
  при включенном friendly_alias_urls. Если псевдоним страницы прописан, то ссылка генерируется правильно с псевдонимом, если псевдоним путой, то раньше подставляло id, а теперь пустота.

**Comment by Seiger** [comment]
It works in 3.2.x
