### ISSUE TITLE
maxiGallery link to css included on all pages

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#197]
I am not sure since when this is the case but link to maxiGallery css in site head should be included only on gallery pages. Actually it is included on every page.

**Comment by dmi3yy** [comment]
i think  need write issues on maxigallery repositories.

**Comment by leonie12** [comment]
And these are actually where?

**Comment by dmi3yy** [comment]
here 
https://github.com/extras-evolution/MaxiGallery

**Comment by leonie12** [comment]
Any ideas where I can find a possibility to report issues there?

**Comment by pmfx** [comment]
Good question :) @dmi3yy there is no way to add issues in that repository

**Comment by leonie12** [comment]
Now there is: https://github.com/extras-evolution/MaxiGallery/issues/1

@dmi3yy: Thanks.
