### ISSUE TITLE
"configuration"-->"system info" error messages

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1979]
i am on 3.1.5 evo.

go to "configuration"-->system info" screen.

if i go to delete any spare mysql drive/space (clicking on the red 'DATA-SIZE' links), a popup error box appears saying "Field username is required" .

also, i clicked on one of the "overhead" memory amounts (red link to number of memory bytes that can be released) and i get an error screen:

"
« Evolution CMS Parse Error »
Call to undefined method EvolutionCMS\Database::optimize()
"

**Comment by user83743** [comment]
on 3.1.5 evo

if i click on the "Doc Manager" link in the left side CMS menubar under "Modules",

i get another appearance of the:

"
 Evolution CMS Parse Error »
Error : include(/home/ggmservices/public_html/bwd-services.com/manager/includes/lang/english.inc.php): failed to open stream: No such file or directory
"

which comes from 

/home/ggmservices/public_html/bwd-services.com/assets/modules/docmanager/classes/docmanager.class.php   line 27

any idea how i can fix that or hack it even? ;)

**Comment by BBloke** [comment]
@user83743 I had a similar missing file when I upgraded a site from v1.4 to v3.1.4.  My main production site is still on v2 so the lang folder in managers/include still contained the lang files.

You can get them by downloading v2.0.4 Evo (in v3 that folder is empty in the source files) and uploading the necessary into the lang folder.

**Comment by user83743** [comment]
thanks @BBloke
