### ISSUE TITLE
Evo 3.0.0-3.1.5 Bug

### ISSUE THREAD

**Issue by anvanio** [evolution-cms/evolution#1980]
English:
when you insert the image symbols directly, the template is erased exactly to the point where the image is inserted. example: 🚗 Some text. Call us! ☎ +7 (800) 555 35 35.
Any code, html,css, everything after the typewriter and phone is erased, the template becomes empty. It is necessary to insert html tags analogs, in my case &#128663; and & #9742;
--------------------------------------------------------
Russian:
при вставке символов-картинок напрямую, шаблон стирается ровно до того момента где вставлена картинка. пример: 🚗 Какой-то текст. Звоните! ☎ +7 (800) 555 35 35.
Любой код, html,css, все после машинки и телефона стирается, шаблон пустым становится. Необходимо вставлять html тэги, в мое случае &#128663; и &#9742;

**Comment by anvanio** [comment]
codes: &#_128663; и &#_9742;
remove _

**Comment by Dmi3yy** [comment]
its not is Evolution bug,  change db encode form utf8 to utf8mb4
