### ISSUE TITLE
This will mess up a lot of EVO websites......

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1981]
Hi

i upgraded our test website (evo 1.4.14)  to evo 3.1.4 to see how it goes. a few issues have been dealt with thanks. One issue i noticed is below and this will mess up a lot of evo sites:

--- since the start of modx, you could have a chunk call like "{{teambox}}" , and while you are testing this you could disable this chunk call by just renaming that chunk call (instead of deleting the chunk call)  for a few minutes or forever e.g.   "{{teambox7}}".

---in EVO 1.4.14, the snippet calls work as always (non existent chunk calls are ignored by the EVO processor) , but on evo 3.1.4, that above 'dead' snippet call to  "{{teambox7}}" gets printed to the screen in raw text!! instead of being ignored by the EVO processor. that means that any sites we upgrade to evo 3.1.4 are going to have some old (dead) snippet calls or chunk calls, displayed on the screen e.g. "{{teambox7}}" .

--we just edited a number of places on our test website but to upgrade old client sites means doing the same again - going page to page to see if old chunk calls and old snippet calls are being displayed in raw text on the screen. this is not a good idea for EVO :) . hopefully this will be removed? @Dmi3yy

**Comment by BBloke** [comment]
I started the same issue  https://github.com/evolution-cms/evolution/issues/1978

**Comment by user83743** [comment]
Thanks BBloke

**Comment by BBloke** [comment]
Here's a very simple plugin which may help

`// RemoveChunks from display
// C Hunton 
// Date: 15-6-21
//
// This plugin should remove unwanted chunk names rendered to the output which should be cleared when the document is process

// System Events: OnWebPagePrerender

$showMatches = false;

$re[] = '/({{[[:alnum:]]*}})/mix';				// Chunks
$re[] = '/(\[\+[[:alnum:]]*\+\])/mix';			// Placeholders

$output = $modx->documentOutput; // get the parsed document

foreach ( $re as $search )
{
	preg_match_all($search, $output, $matches, PREG_SET_ORDER, 0);
	$output = preg_replace($search, ' ' , $output);
}

// Print the entire match result
if ( $showMatches ) var_dump($matches);

$modx->documentOutput = $output;`
