### ISSUE TITLE
evo 3.1.4  --- formlister::   "You may send message again in 1 min"

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#1984]
Hi Evos.

on evo 3.1.4 and formlister (using smtp with gmail) the emails are sent out every time, but every time i get this error message on the formliister form "You may send message again in 1 min" . anyone come across that before or any ideas how oi could debug it? no errors are displayed in 'system events' in evo.

i enabled formlister 'debug' and again the form sends out email using gmail smtp, but i still get the above error message and the 'system events' says:

[data] => Array
(
[formid] => ContactForm
[name] => rrrrrrrrrr
[email] => rrrrrrrr@rr.rr
[phone] => rrr
[message] => rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
[AgreeToPrivacyPolicy] => 1
[g-recaptcha-response] => 03AGdBq25jNzcNN4dLQzNkVIHGPezGgq1MDs-cbTNU6_hatsWsGQNyrJnIPUrAx0LFu0j9ExoqgR2jpS9Q7chgh7obZBksO4GSL0OK2X4QNX8nP61wiyhAJQ3GRDf9RbNgg0rspuz1VrRbwKC89c89QzaI1ugeu4lQiaBpaPliZwWUfFTTPn0qUiuzoSjs1UKUK_OTCIk4t4EkgqsasNoYfQZww58JJX3TVJGtTHHIBEAn1qgguGFuehl_ZFLjBKFKr1dTf1RXnjdWXe_n04yr0o3Dd8ebopGmI3T63t-glXlLTZvyz3hjpI6Hj7WnBIOGP9ntCfylXrezEqw72buPorVrLorh1hM91hMF6AAgJxj1BzoK7G_wAIaEjBT8MPuLvW9fDSLApS0Hc3msCYXhR3zb5OQhJrFJSmt-65deePijvb2V_ABb7Xs1uE_1UFxF-tWfkDQFy-7hrHLv_dJlNwzT7Ho91GRwew
[formid.value] => ContactForm
[name.value] => rrrrrrrrrr
[email.value] => rrrrrrrr@rr.rr
[phone.value] => rrr
[message.value] => rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
[AgreeToPrivacyPolicy.value] => 1
[g-recaptcha-response.value] => 03AGdBq25jNzcNN4dLQzNkVIHGPezGgq1MDs-cbTNU6_hatsWsGQNyrJnIPUrAx0LFu0j9ExoqgR2jpS9Q7chgh7obZBksO4GSL0OK2X4QNX8nP61wiyhAJQ3GRDf9RbNgg0rspuz1VrRbwKC89c89QzaI1ugeu4lQiaBpaPliZwWUfFTTPn0qUiuzoSjs1UKUK_OTCIk4t4EkgqsasNoYfQZww58JJX3TVJGtTHHIBEAn1qgguGFuehl_ZFLjBKFKr1dTf1RXnjdWXe_n04yr0o3Dd8ebopGmI3T63t-glXlLTZvyz3hjpI6Hj7WnBIOGP9ntCfylXrezEqw72buPorVrLorh1hM91hMF6AAgJxj1BzoK7G_wAIaEjBT8MPuLvW9fDSLApS0Hc3msCYXhR3zb5OQhJrFJSmt-65deePijvb2V_ABb7Xs1uE_1UFxF-tWfkDQFy-7hrHLv_dJlNwzT7Ho91GRwew
[captcha] => <div id="ContactForm-recaptcha" class="g-recaptcha" data-sitekey="6LeG_XEUAAAAAAOdDAOi-PzSDOhEmZrR_0LrooFr" data-type="image" data-tabindex="0" data-size="normal" data-theme="light" data-callback="" data-expired-callback="" data-badge="bottomright"></div>
[form.messages] => <div><ul><li>You may send message again in 1 min.</li></ul></div>
)

##################
i tried the above smtp settings on evo 1.4.14 and they work fine. the ""&successTpl"" text is displayed and no error message is displayed. so there is something up on evo 3.14 with formlister. if you use php-mail the formlister form works fine. if we use smtp settings (gmail) the form send the email but it always displays the error message "You may send message again in 1 min" and the ""&successTpl"" text is never displayed.

**Comment by sashabeep** [comment]
@user83743 this is not FAQ section. RTFM https://docs.evo.im/en/04_extras/formlister/050_otpravka-pisem.html
