### ISSUE TITLE
Parse error: Sort menu index

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#199]
Hi,
I can't sort menu index .
![download 42](https://user-images.githubusercontent.com/9032715/29866565-c4f06a16-8d9e-11e7-8569-28870357f5e2.png)

**Comment by yama** [comment]
Do you know the version of PHP?

**Comment by 64j** [comment]
@mgzawlinoo 
https://github.com/evolution-cms/evolution/issues/189
