### ISSUE TITLE
Сбивается https EVO 3-3.1.6

### ISSUE THREAD

**Issue by anvanio** [evolution-cms/evolution#1997]
При редактировании страниц/при прохождении определенного времени, не понятно при каком условии, сбивается https, в консоли рисует http, помогает только очистка кэша.
![image](https://user-images.githubusercontent.com/43257940/126881012-179c7a51-f987-42fc-bb47-8659edeb98d2.png)
![image](https://user-images.githubusercontent.com/43257940/126881022-5ef7e224-7636-4bba-99e7-ef8cc66239d1.png)

**Comment by oawebdev** [comment]
Мне помогла очиста кеша в админке. В процесе обновления надо чистить кеш всегда.
