### ISSUE TITLE
PHP8 and EVO 3.1.6 - Error : Undefined array key "_token"

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#1998]
Error : Undefined array key "_token"

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /home/.../domains/....nl/public_html/core/src/Middleware/VerifyCsrfToken.php
Line | 9
Source | if ($_SESSION['_token'] !== $request->input('_token')) {

Some issue with: core/src/Middleware/VerifyCsrfToken.php

**Comment by BBloke** [comment]
It's the same with PHP v7.4 as far as Tracy shows.

**Comment by fourroses666** [comment]
The systemlog was full of these warning issues.

Somehow I don't get these anymore.

What I did where a couple of things and don't know which helped; 
- Fullname for Administrator changed from "1" to "Myname" 
- Disabled all Plugins (and after setting back to PHP 8.0.10 that enabled them all again)
- Cleared cache

Somehow the manager is accesable again in PHP 8.0.10

**Comment by fourroses666** [comment]
On 3.1.7 its fixed.
