### ISSUE TITLE
Ошибка при обновлении на 3.1.8 -  syntax error, unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by oawebdev** [evolution-cms/evolution#1999]
При обновлении на 3.1.8 через php artisan make:site update возникает ошибка.

syntax error, unexpected 'static' (T_STATIC)

File: /core/vendor/symfony/string/UnicodeString.php
Line: 44
Source: Parser / syntax error, unexpected 'static' (T_STATIC)

-----
php 7.4
Evo 3.1.5

**Comment by sashabeep** [comment]
php artisan make:site update 3.x ?

**Comment by oawebdev** [comment]
Я запускал просто php artisan make:site update.
Прошлый раз composer update не помог. 
Попробую еще раз с указанием версии.
