### ISSUE TITLE
Page Click Behavior system setting not respected in View Children tab

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#200]
When "Page Click Behavior" setting is set to "View Resource data", clicking on resource in "View Children" tab still opens edit page.

**System setting:**

![screenshot_1](https://user-images.githubusercontent.com/10888055/29872024-2ca11d24-8d8e-11e7-9bd5-fadf81a827e9.png)

**View children tab:**

![screenshot_2](https://user-images.githubusercontent.com/10888055/29872025-2ca1bc2a-8d8e-11e7-9641-0e82791f8f27.png)

**Click result:**

![screenshot_3](https://user-images.githubusercontent.com/10888055/29872095-6c8a1760-8d8e-11e7-8a87-00b81efd4b0d.png)

Should be resource overview, not edit page.

**Comment by 64j** [comment]
@pmfx did not quite understand
It seems everything works

https://monosnap.com/file/jfAzhCBgkRHEdvTPBntoIm0cjRRbky

**Comment by pmfx** [comment]
Click one of those in "View children" tab.

![screenshot_4](https://user-images.githubusercontent.com/10888055/29872504-2d25a538-8d90-11e7-9d4d-e11456504848.png)

Always edit page, despite the system setting.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/29872597-f4aa64ec-8d98-11e7-8ecd-1cf8c72703be.png)

tree_page_click
tree_page
tree
tree ! ))))

**Comment by pmfx** [comment]
Hm, so it is only applied to tree? OK. Maybe let's add there on the resources list "overview" action then? Like on welcome screen:

![screenshot_5](https://user-images.githubusercontent.com/10888055/29872674-dd4bfeda-8d90-11e7-9855-fb7cecb31d7f.png)

Welcome screen "Recently edited":

![screenshot_6](https://user-images.githubusercontent.com/10888055/29872675-dd72329e-8d90-11e7-8b28-32f4277804f0.png)

**Comment by pmfx** [comment]
Actually I would change default behavior to "resource overview" when clicking items on "View children" tab. What do you think?

**Comment by 64j** [comment]
@pmfx and so many options for managing a tree made

https://monosnap.com/file/YPfRPThyC94YdoxE7IAo3gp1FtHojc

**Comment by pmfx** [comment]
Yes, I know about it ;) Thats cool. I'm only talking about resources list in "View children" tab. 
I think "resource overview" as default action (when clicking resource on that list) makes sense.

Maybe let's change it so:

![screenshot_1](https://user-images.githubusercontent.com/10888055/29873560-0027f000-8d94-11e7-865f-ecbc82c54b72.png)

What do you think?

**Comment by 64j** [comment]
@pmfx 
I have 2-3 thousand resources in one folder. This will be an additional load(((

**Comment by 64j** [comment]
@pmfx 
And already thousands of people are used to this logic of behavior, that it will stir up a lot of discontent

**Comment by pmfx** [comment]
Agree. I would add system setting for this in the future. Anyway all good, closing issue.

**Comment by 64j** [comment]
@pmfx it is not comfortable
https://monosnap.com/file/5IlXS1dizOQTIrdEtrJ9AoeKE9CmVq

**Comment by pmfx** [comment]
You can add &tab=0 to the link, right? To always land on first tab.

**Comment by 64j** [comment]
@pmfx 
Yes. But we do not have a "go back" button )

**Comment by pmfx** [comment]
Yes, "Back to list" button would be useful.
