### ISSUE TITLE
Extras auto update possible?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#201]
All the Extras are not being updated automaticly.

For example: 
I noticed that PageBuilder was updated to 1.1.0. See here: https://github.com/mnoskov/pagebuilder 

When I check the Extras: Extras > Package Manager > PageBuilder --> this has version 0.6.3
PageBuilder isn't even listed at: https://github.com/extras-evolution

How does it work?
Is it possible to directly update it on the Extras?
The way it now is, is probably not the best way to do it.
Is it possible to link the Extras directly to the main user repository?
Only added when its fully tested?

We also need to have a good look at all the Extras.
For example the Google Analytics Widget doesn't work anymore but its still downloadable.

I think we need to rethink the Extras and also when there is an update available get a message on the dashboard / autoUpdater?

**Comment by dmi3yy** [comment]
On 90% in extras take  files from Master 

I want rewrite all extras for use releases from git and description from git 

 

Отправлено с iPhone

**Comment by fourroses666** [comment]
Oke, 

You have to manually check/update Extras when a Master is updated?
Because I see an old version for PageBuilder.

**Comment by dmi3yy** [comment]
Install last version but 
Set version need manual

Отправлено с iPhone

**Comment by fourroses666** [comment]
Oke

**Comment by Nicola1971** [comment]
@dmi3yy 
> I want rewrite all extras for use releases from git and description from git

i have a snippet for that:
![download](https://user-images.githubusercontent.com/7342798/29890355-9cbc39f2-8dc7-11e7-96ac-0b91b0c49fc2.png)

check working here:
http://www.tattoocms.it/extras/modules/evobackup.html
