### ISSUE TITLE
Ошибка на последнем этапе установки 3 версии

### ISSUE THREAD

**Issue by ZetxKS** [evolution-cms/evolution#2011]
![image](https://user-images.githubusercontent.com/85649735/132230331-6d77f6da-b9ac-4bf6-96d0-805fcc3f4704.png)

**Comment by sashabeep** [comment]
@ZetxKS стереть все группы пользователей и ресурсов. Удалить все ресурсы из групп. Потом запустить из extras скрипт миграции, и потом установить

**Comment by Dmi3yy** [comment]
Это уже исправили теперь с группами обновляет нормально
