### ISSUE TITLE
Parse error: syntax error, unexpected end of file , when Sort Menu Index

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#202]
Parse error: syntax error, unexpected end of file , when Sort Menu Index

![download 42](https://user-images.githubusercontent.com/9032715/29881624-2055c9b4-8dd1-11e7-8a08-f1586734144c.png)

**Comment by 64j** [comment]
https://github.com/evolution-cms/evolution/issues/199
