### ISSUE TITLE
v3 QuickManager+ language error

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#2023]
Hi All,

The above throws an error when being used as the /manager/includes/lang files are removed in v3 installation.

Here's a thread which has the error:
https://forum.evo.im/d/161-various-issues-after-updating-1415-to-3117-with-the-migration-plugin

**Comment by nick0** [comment]
I also get the following error relating to Quick Manager regarding a missing manager file
```
Plugin - Quick Manager+ / PHP Parse Error - Saving - System Events

Event Id: 	0 	Source: 	Plugin - Quick Manager+ / PHP Parse Error - Saving

« Evolution CMS Parse Error »

Error : include(/home/my-site/public_html/my-custom-manager/includes/secure_mgr_documents.inc.php): failed to open stream: No such file or directory

Error information 	
ErrorType[num] 	WARNING[2]
File 	/home/my-site/public_html/assets/plugins/qm/qm.inc.php
Line 	102
Source 	include MODX_MANAGER_PATH."includes/secure_mgr_documents.inc.php"; 
```
I can confirm that in my installations of Evo:
1.4.15 - etc/my-custom-manager/includes/secure_mgr_documents.inc.php exists.
3.1.17 - etc/my-custom-manager/includes/secure_mgr_documents.inc.php exists.

Is the file missing or does Quick Manager need a rejig for Evo 3.1.17?
