### ISSUE TITLE
Add ElementsInTree plugin to the core

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#203]
Previously discussed here #142 
ElementsInTree is a very fast and convenient way to manage elements. Would be great to have it in the core.

**Comment by 64j** [comment]
This is an external plug-in and in many respects it contradicts the work of the system.

Incorrect blocking of resources.

Incorrect update of the tree (if modx.js not corrected for it).
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/js/modx.js#L1259-L1321

The style of design in the main theme, which no one wants to transfer to the plugin.
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/css/page.css#L48-L70

**Comment by Nicola1971** [comment]
Can we fix? Makes my job really faster.

**Comment by 64j** [comment]
If you have time for this, then of course do)
https://monosnap.com/file/gOKBi9wosrylGTlopmYS8R0DQNzS5z

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/29901621-af1c134e-8e01-11e7-895d-854ad3e31b96.png)
![image](https://user-images.githubusercontent.com/4653189/29901672-f0953f26-8e01-11e7-943d-49e05d201333.png)

**Comment by pmfx** [comment]
Is this EIT style from screenshot/screencast (fluid tabs width looks good) ready somewhere or it is just an example of how it should look? I can update EIT css if needed and maybe @Deesen can help solve JS issues?

**Comment by 64j** [comment]
@pmfx This is an example, how you can do it ))

**Comment by Nicola1971** [comment]
a small issue regarding EIT plugin: 
does not have DocBlocks in the code, so you cant parse if you need :(

**Comment by pmfx** [comment]
@Nicola1971 https://github.com/evolution-cms/evolution/blob/develop/install/assets/plugins/ElementsInTree.tpl

**Comment by Nicola1971** [comment]
@pfmx, yes but just in the installer tpl, not in the code, so you cant parse.
All other bundled plugin have it
![eit](https://user-images.githubusercontent.com/7342798/29923381-a4e06706-8e59-11e7-9ae6-aee793e5f042.png)
![qm](https://user-images.githubusercontent.com/7342798/29923383-a8c3392a-8e59-11e7-861a-d91bd6bc3df3.png)

**Comment by pmfx** [comment]
@64j restyled https://github.com/evolution-cms/evolution/commit/f171c5239a813f6f4b487b9ec0bbecb2dcf43d54

**Comment by 64j** [comment]
@pmfx You added them in wrong file
https://github.com/modxcms/evolution/blob/master/assets/plugins/elementsintree/assets/css_treeButtonsInTab.tpl

The plugin has nothing to do with the main theme of the design!

**Comment by pmfx** [comment]
Correct, fixed https://github.com/evolution-cms/evolution/commit/16fe348150ac876c221d47275aa801b24cbe8d88

**Comment by 64j** [comment]
@pmfx is cool )))

**Comment by Nicola1971** [comment]
@pmfx much better

**Comment by dmi3yy** [comment]
if site with. https not show icon: 
![image 2017-09-04 12 50 17](https://user-images.githubusercontent.com/669491/30021301-9b1a4412-916f-11e7-8824-ce18b6e2efdc.jpg)
