### ISSUE TITLE
Update 3.1.8 doesn't work: Symfony error

### ISSUE THREAD

**Issue by sirfranz** [evolution-cms/evolution#2048]
Hi there,

when I try to update to 3.1.8 I get this error:

**https://www.this-domain-is-hidden.de/install/index.php?action=install**
`Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string File: /var/www/web301/html/core/vendor/symfony/translation/TranslatorInterface.php Line: 69 Source: Parser / Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string - Idle (unknown) #1. EvolutionCMS\ExceptionHandler->handleShutdown(), on line #2. EvolutionCMS\ExceptionHandler->fatalExceptionFromError(array $var1, 0), core/src/ExceptionHandler.php on line 50 `

**Comment by sirfranz** [comment]
Here are more details:

1. This problem occures on installation-step 4 (after accepting the GNU GPL).
2. And it only occurs if an admin is logged in.
3. After deleting all cookies: the frontend is working.
4. But if I login as admin the error occures agin. So I can not login as admin.

The error at login is:
<b>Fatal error</b>:  Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string in <b>/var/www/web301/html/core/vendor/symfony/translation/TranslatorInterface.php</b> on line <b>69</b><br />
<!DOCTYPE html><html><head><title>Evolution CMS Content Manager  &raquo; </title>
                 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                 <link rel="stylesheet" type="text/css" href="http://www..de/manager/media/style/default/style.css" />
                 <style type="text/css">body { padding:10px; } td {font:inherit;}</style>
                 </head><body>
                 <b>Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string</b><br />
<h2 style="color:red">&laquo; Evolution CMS Parse Error &raquo;</h2><h3 style="color:red">Declaration of Symfony\Component\Translation\TranslatorInterface::getLocale() must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::getLocale(): string</h3>
<table class="grid">
	<thead>
	<tr class="">
		<th width="100px" >Error information</th>
		<th></th>
	</tr>
	</thead>
	<tr class="gridItem">
		<td>File</td>
		<td>/var/www/web301/html/core/vendor/symfony/translation/TranslatorInterface.php</td>
	</tr>
	<tr class="gridAltItem">
		<td>Line</td>
		<td>69</td>
	</tr>
</table>
<br />
<table class="grid">
	<thead>
	<tr class="">
		<th width="100px" >Basic info</th>
		<th></th>
	</tr>
	</thead>
	<tr class="gridItem">
		<td>REQUEST_URI</td>
		<td>http://www..de/manager/?a=0</td>
	</tr>
	<tr class="gridAltItem">
		<td>Referer</td>
		<td>http://www..de/manager/</td>
	</tr>
	<tr class="gridItem">
		<td>User Agent</td>
		<td>you do not have to know</td>
	</tr>
	<tr class="gridAltItem">
		<td>IP</td>
		<td>you do not have to know</td>
	</tr>
	<tr class="gridItem">
		<td>Current time</td>
		<td>2022-01-06 15:07:09</td>
	</tr>
</table>
<br />
<table class="grid">
	<thead>
	<tr class="">
		<th width="100px" >Benchmarks</th>
		<th></th>
	</tr>
	</thead>
	<tr class="gridItem">
		<td>MySQL</td>
		<td>0.0000 s (0 Requests)</td>
	</tr>
	<tr class="gridAltItem">
		<td>PHP</td>
		<td>0.1367 s</td>
	</tr>
	<tr class="gridItem">
		<td>Total</td>
		<td>0.1367 s</td>
	</tr>
	<tr class="gridAltItem">
		<td>Memory</td>
		<td>7.60269165039 mb</td>
	</tr>
</table>
<br />
<table class="grid">
	<thead>
	<tr class="">
		<th>Backtrace</th>
	</tr>
	</thead>
	<tr class="gridItem">
		<td><strong>EvolutionCMS\ExceptionHandler->handleShutdown</strong>()<br /> on line </td>
	</tr>
	<tr class="gridAltItem">
		<td><strong>EvolutionCMS\ExceptionHandler->fatalExceptionFromError</strong>(array $var1, 0)<br />core/src/ExceptionHandler.php on line 50</td>
	</tr>
</table>
</body></html>

**Comment by fourroses666** [comment]
I wonder how you updated. I don't seem to have that issue after updating from 3.1.7 and with the manager Update button.

**Comment by sirfranz** [comment]
I have used the manager update-button, too.

Which manager-language do you use?

**Comment by fourroses666** [comment]
Netherlands / NL.

**Comment by fourroses666** [comment]
Hey I have the same issue now on an other server..

**Comment by fourroses666** [comment]
On front I see Error and also when trying to log in. Manager loginpage is visible.

**Comment by sirfranz** [comment]
Could this be a plugin problem?

**Comment by fourroses666** [comment]
I can try on a very clean version I have without many plugins.

**Comment by fourroses666** [comment]
I have talked with a developer about this and he sees the issue. Tomorrow it will be fixed. Don't know whats the issue thow.

Strangely it worked on a site I updated yesterday on a different host.

**Comment by sirfranz** [comment]
Many thanks!

**Comment by Dmi3yy** [comment]
Try install fresh 3.1.8 on php 7.4. all ok 
Install fresh 3.1.7 and  after update to 3.1.8 (by click abate button) all ok 

Can you write more info about server

**Comment by fourroses666** [comment]
```
Notice: Undefined index: installmode in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 35
Notice: Undefined index: databasehost in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 39
Notice: Undefined index: database_type in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 40
Notice: Undefined index: database_collation in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 43
Notice: Undefined index: database_connection_charset in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 45
Notice: Undefined index: database_connection_method in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 46
Notice: Undefined index: database_name in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 47
Notice: Undefined index: cmsadmin in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 48
Notice: Undefined index: cmsadminemail in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 49
Notice: Undefined index: cmspassword in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 50
Notice: Undefined index: managerlanguage in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 51
Notice: Undefined index: database_type in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 79
Notice: Undefined index: databasehost in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 79
Notice: Undefined index: database_name in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 79
Notice: Undefined index: database_name in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 857
Notice: Undefined index: database_name in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 857
Notice: Undefined variable: output in /home/xxx/domains/xxx.nl/public_html/install/src/controllers/install.php on line 858

mislukt! could not find driver
```

**Comment by fourroses666** [comment]
ps. Did a downgrade with the installer to 3.1.7 and the site works again.

**Comment by sirfranz** [comment]
> Try install fresh 3.1.8 on php 7.4. all ok Install fresh 3.1.7 and after update to 3.1.8 (by click abate button) all ok
> 
> Can you write more info about server

Many thanks. Here are some of my server-data (3.1.7 working; 3.1.8 does not work):

EVO-Version  3.1.7
Veröffentlichungsdatum  Oct 06, 2021 (evo published date)
PHP Version  7.4.3
Zugriffsberechtigung   Aktiviert (access privileg atctive)
Server-Zeit  16:48:32 (server time)
Ortszeit 16:48:32 (locale time)
Server-Zeitverschiebung 0 h (server time shift)
Datenbank-Name xxxx (db name)
Datenbank-Server localhost (db hoset)
Datenbank-Version 5.7.25 (db version = mysql version)
Datenbank-Zeichensatz latin1 (charset)
Datenbank-Kollations-Zeichensatz latin1_german1_ci (collation)
Tabellen-Präfix  modx_ (table prefix)
MODX_BASE_PATH  /var/www/xyz/html/
MODX_BASE_URL  /
MODX_MANAGER_URL  https://www.xyz.de/manager/
MODX_MANAGER_PATH /var/www/xyz/html/manager/
MODX_SITE_URL https://www.xyz.de/

<html><body>


System | Linux alfa3202 4.9.44-040944-generic #201708161731 SMP Wed Aug 16 21:34:20 UTC 2017 x86_64
-- | --
Build Date | Feb 25 2020 17:21:29
Server API | CGI/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/php7.4/cgi
Loaded Configuration File | /etc/apache2/confixx_phpini/web3707/1/php.ini
Scan this dir for additional .ini files | /etc/php7.4/cgi/conf.d
Additional .ini files parsed | /etc/php7.4/cgi/conf.d/alfa.ini, /etc/php7.4/cgi/conf.d/ext.ini, /etc/php7.4/cgi/conf.d/loader.ini, /etc/php7.4/cgi/conf.d/timezone.ini
PHP API | 20190902
PHP Extension | 20190902
Zend Extension | 320190902
Zend Extension Build | API320190902,NTS
PHP Extension Build | API20190902,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | php, file, glob, data, http, ftp, compress.bzip2, https, ftps, compress.zlib, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters | string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*, zlib.*


</body>
</html>


<h2><a name="module_core">Core</a></h2>
<table>
<tr><td class="e">PHP Version </td><td class="v">7.4.3 </td></tr>
</table>
<table>
<tr class="h"><th>Directive</th><th>Local Value</th><th>Master Value</th></tr>
<tr><td class="e">allow_url_fopen</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">allow_url_include</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">arg_separator.input</td><td class="v">&amp;</td><td class="v">&amp;</td></tr>
<tr><td class="e">arg_separator.output</td><td class="v">&amp;</td><td class="v">&amp;</td></tr>
<tr><td class="e">auto_append_file</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">auto_globals_jit</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">auto_prepend_file</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">browscap</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">default_charset</td><td class="v">UTF-8</td><td class="v">UTF-8</td></tr>
<tr><td class="e">default_mimetype</td><td class="v">text/html</td><td class="v">text/html</td></tr>
<tr><td class="e">disable_classes</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">disable_functions</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">display_errors</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">display_startup_errors</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">doc_root</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">docref_ext</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">docref_root</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">enable_dl</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">enable_post_data_reading</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">error_append_string</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">error_log</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">error_prepend_string</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">error_reporting</td><td class="v">22519</td><td class="v">24567</td></tr>
<tr><td class="e">expose_php</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">extension_dir</td><td class="v">/opt/php/7.4.3/lib/php/20190902</td><td class="v">/opt/php/7.4.3/lib/php/20190902</td></tr>
<tr><td class="e">file_uploads</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">hard_timeout</td><td class="v">2</td><td class="v">2</td></tr>
<tr><td class="e">highlight.comment</td><td class="v"><font style="color: #FF8000">#FF8000</font></td><td class="v"><font style="color: #FF8000">#FF8000</font></td></tr>
<tr><td class="e">highlight.default</td><td class="v"><font style="color: #0000BB">#0000BB</font></td><td class="v"><font style="color: #0000BB">#0000BB</font></td></tr>
<tr><td class="e">highlight.html</td><td class="v"><font style="color: #000000">#000000</font></td><td class="v"><font style="color: #000000">#000000</font></td></tr>
<tr><td class="e">highlight.keyword</td><td class="v"><font style="color: #007700">#007700</font></td><td class="v"><font style="color: #007700">#007700</font></td></tr>
<tr><td class="e">highlight.string</td><td class="v"><font style="color: #DD0000">#DD0000</font></td><td class="v"><font style="color: #DD0000">#DD0000</font></td></tr>
<tr><td class="e">html_errors</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">ignore_repeated_errors</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">ignore_repeated_source</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">ignore_user_abort</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">implicit_flush</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">include_path</td><td class="v">.:/opt/php/7.4.3/share/pear</td><td class="v">.:/opt/php/7.4.3/share/pear</td></tr>
<tr><td class="e">input_encoding</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">internal_encoding</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">log_errors</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">log_errors_max_len</td><td class="v">1024</td><td class="v">1024</td></tr>
<tr><td class="e">mail.add_x_header</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">mail.force_extra_parameters</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">mail.log</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">max_execution_time</td><td class="v">30</td><td class="v">30</td></tr>
<tr><td class="e">max_file_uploads</td><td class="v">20</td><td class="v">20</td></tr>
<tr><td class="e">max_input_nesting_level</td><td class="v">64</td><td class="v">64</td></tr>
<tr><td class="e">max_input_time</td><td class="v">60</td><td class="v">60</td></tr>
<tr><td class="e">max_input_vars</td><td class="v">1000</td><td class="v">1000</td></tr>
<tr><td class="e">memory_limit</td><td class="v">128M</td><td class="v">128M</td></tr>
<tr><td class="e">open_basedir</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">output_buffering</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">output_encoding</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">output_handler</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">post_max_size</td><td class="v">64M</td><td class="v">64M</td></tr>
<tr><td class="e">precision</td><td class="v">12</td><td class="v">12</td></tr>
<tr><td class="e">realpath_cache_size</td><td class="v">4096K</td><td class="v">4096K</td></tr>
<tr><td class="e">realpath_cache_ttl</td><td class="v">120</td><td class="v">120</td></tr>
<tr><td class="e">register_argc_argv</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">report_memleaks</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">report_zend_debug</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">request_order</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">sendmail_from</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">sendmail_path</td><td class="v">/usr/sbin/sendmail&nbsp;-t&nbsp;-i&nbsp;-f&nbsp;web3707@www.b30neu.de</td><td class="v">/usr/sbin/sendmail&nbsp;-t&nbsp;-i&nbsp;-f&nbsp;web3707@www.b30neu.de</td></tr>
<tr><td class="e">serialize_precision</td><td class="v">100</td><td class="v">100</td></tr>
<tr><td class="e">short_open_tag</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">SMTP</td><td class="v">localhost</td><td class="v">localhost</td></tr>
<tr><td class="e">smtp_port</td><td class="v">25</td><td class="v">25</td></tr>
<tr><td class="e">sys_temp_dir</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">syslog.facility</td><td class="v">LOG_USER</td><td class="v">LOG_USER</td></tr>
<tr><td class="e">syslog.filter</td><td class="v">no-ctrl</td><td class="v">no-ctrl</td></tr>
<tr><td class="e">syslog.ident</td><td class="v">php</td><td class="v">php</td></tr>
<tr><td class="e">track_errors</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">unserialize_callback_func</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">upload_max_filesize</td><td class="v">64M</td><td class="v">64M</td></tr>
<tr><td class="e">upload_tmp_dir</td><td class="v">/var/www/web3707/phptmp/</td><td class="v">/var/www/web3707/phptmp/</td></tr>
<tr><td class="e">user_dir</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">user_ini.cache_ttl</td><td class="v">300</td><td class="v">300</td></tr>
<tr><td class="e">user_ini.filename</td><td class="v">.user.ini</td><td class="v">.user.ini</td></tr>
<tr><td class="e">variables_order</td><td class="v">EGPCS</td><td class="v">EGPCS</td></tr>
<tr><td class="e">xmlrpc_error_number</td><td class="v">0</td><td class="v">0</td></tr>
<tr><td class="e">xmlrpc_errors</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">zend.assertions</td><td class="v">1</td><td class="v">1</td></tr>
<tr><td class="e">zend.detect_unicode</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">zend.enable_gc</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">zend.exception_ignore_args</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">zend.multibyte</td><td class="v">Off</td><td class="v">Off</td></tr>
<tr><td class="e">zend.script_encoding</td><td class="v"><i>no value</i></td><td class="v"><i>no value</i></td></tr>
<tr><td class="e">zend.signal_check</td><td class="v">Off</td><td class="v">Off</td></tr>
</table>

**Comment by Dmi3yy** [comment]
> > Try install fresh 3.1.8 on php 7.4. all ok Install fresh 3.1.7 and after update to 3.1.8 (by click abate button) all ok
> > Can you write more info about server
> 
> Do you need direct access? I can grant you access to an test installation, so you can see it live.

Send plz to dmi3yy@gmail.com will test tomorrow

**Comment by Dmi3yy** [comment]
> > Try install fresh 3.1.8 on php 7.4. all ok Install fresh 3.1.7 and after update to 3.1.8 (by click abate button) all ok
> > Can you write more info about server
> 
> Do you need direct access? I can grant you access to an test installation, so you can see it live.

Hi will try update see some problem with files in core folder. 

Just delete folder core/vendor and upload from GitHub by hand and all work 

this happens if the archive on the server is not unpacked correctly

**Comment by sirfranz** [comment]
Many Thanks to you!
All works!
