### ISSUE TITLE
Bug when deleting a resource with resource Delete button 3.1.8

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#2051]
Seems when I delete a resource with the resource delete button I get a warning I don't have the rights to do so.
While I'm an admin. Delete from the left resource tree does work.

**Comment by nick0** [comment]
Same here. 
That issue was reported here 16-Nov-21 as issue number 1 in #2032
[v3 Manager actions with parse errors - admin Resource delete issue, editor can't open Resource #2032](https://github.com/evolution-cms/evolution/issues/2032)
