### ISSUE TITLE
PHP8.0 add new manager user (evo 3.1.8) openbasedir error

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#2052]
When adding a new user (editor) I get an "openbasedir" error.
Setting it back to PHP7.4 all oke.

**Comment by sashabeep** [comment]
@fourroses666 Have you tried to do the same witv v3.1.9 on PHP8?

**Comment by fourroses666** [comment]
I can't reproduce anymore.

Maybe openbasedir on the server was the issue or a different PHP8.0 version.

Will close for now..
