### ISSUE TITLE
Ditto &tagData=`keywords` Parse Error

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#206]
A strange issue:
After update to 1.3.4 dev, some ditto call cause a 500 error, i've tried removing some parameters and the issue was in &tagData.

After some tests seems that happen only with tv named "keywords" ```&tagData=`keywords ` ```

you can try with a clean 1.3.4 install: change ``` &tagData=`documentTags` ``` to ``` &tagData=`keywords` ``` in Blog page ditto call:

`Error : in_array() expects parameter 2 to be array, null given`

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | D:\UwAmp\www\evo13\assets\snippets\ditto\classes\ditto.class.inc.php
Line | 59
Source | if(!in_array($name,$this->fields['backend'][$type])) $this->fields['backend'][$type][] = $name;
Current Snippet | Ditto

Basic info |  
-- | --
REQUEST_URI | http://localhost/evo13/blog.html
Resource | [2] Blog
Referer | http://localhost/evo13/manager/index.php?a=27&amp;id=2&amp;r=1&amp;stay=2&amp;dir=&amp;sort=createdon&amp;page=0
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
IP | ::1
Current time | 2017-09-01 10:35:21

`

**Comment by dmi3yy** [comment]
Its not a bug. 
you need adв TV keywords  then will be work )

**Comment by dmi3yy** [comment]
for tagData you can use only exists fields )

**Comment by Nicola1971** [comment]
ah ok sorry, seems i had renamed to MetaKeywords some time ago :D :D

is not important, but with old evo this did not cause any error on frontend, probably the wrong parameter value was just ignored/skippet.
