### ISSUE TITLE
[1.4.17] login.processor.php

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#2073]
manager/processors/login.processor.php
Line 8: `include_once(__DIR__ . '/../../manager/index.php');`

"manager/" has been added. Will this effect admin for people who have custom manager folder name?

**Comment by modxuser** [comment]
As mentioned in the forum approx. 12 days ago:

https://forum.evo.im/d/195-evo-php-version-support/37

**Comment by 64j** [comment]
Ok. Fixed later
