### ISSUE TITLE
1.3.5 beta - global tabs - issue with home tab

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#208]
@64j 
I use to add a plugin configuration icon in my widgets and dashboard plugins to access quickly to the configuration page (same in all my modules).
![download](https://user-images.githubusercontent.com/7342798/29994932-5018d1de-8fdc-11e7-946b-1944996a6911.png)

Click on this icon on the dashboard with the new Global Tabs, open the page inside the Home tab

![gt](https://user-images.githubusercontent.com/7342798/29994933-553277ba-8fdc-11e7-9c70-8e2500d67a0b.png)

at this point you cant go to the dashboard untill you refresh the whole tab

video:
https://youtu.be/9BM6nt-huXI

**Comment by pmfx** [comment]
![obraz](https://user-images.githubusercontent.com/10888055/29995765-42c0ebb0-8ff1-11e7-8cbf-41a31421a038.png)

Looks like the same issue happens when clicking those icons. 
Should open new tabs, but it opens in home tab.
