### ISSUE TITLE
Странная картинка при обновлении до 3.1.10

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#2080]
При обновлении до 3.1.10 портится прежняя фоновая картинка на странице входа в админку, вместо нее показывается картинка с кораблём и матерной надписью.

У ряда заказчиков из-за такого может возникнуть недоверие к данной CMS, когда без их желания в их сайты встраиваются столь провокационные вещи.

**Comment by Dmi3yy** [comment]
Все клиенты которым обновлял до 3.1.10 были довольны новой картинке, как в моей родной стране так и за рубежом. 

Единственные кому может не нравится картинка это тем кто поддерживает военное вторжение в Украину.  

Ну а те кто поддерживает рашизм может смело идти за русским военным кораблем. 

P.s. Картинка соответчтвует тому что происходит в мире, будет мир будет другая картинка. 

Я за мир и свободу а так же за развитие, а не за разрушения и боль.

**Comment by Dreamer0x01** [comment]
Не поддерживаю военные действия, как и заказчики. Картинкой тем не менее довольными быть не можем,  так как  в русскоязычном сегменте фраза с картинки является нецензурной. И например, категорически не подходящей для сайтов с детской аудиторией. 
Кроме того, есть же элементарный деловой этикет  и разделение вопросов политики и вопросов разработки.

**Comment by Dmi3yy** [comment]
Деловой этикет заканчивается там где начинается война и необоснованные смерти людей. 

Данной картинкой я высказываю свой протест против военной агрессии страны оккупанта. 

Так же замечу что мой протест мирный: 
- картинка выводится только для менеджеров, клиенты сайта не страдают 
- картинка заменяется в пару кликов через админку (но уверен что большенство про это даже не догадывается)

А на предмет: 
**- Не поддерживаю военные действия, как и заказчики.**

- 1 как минимум тем что вы граждане рф а значит платите налоги в свое государство вы и поддерживаете военное вторжение, так что можете себя сколько угодно переубеждать в обратном но факт есть факт. 
- 2 решение о вторжении приняли не вы лично, а ваше правительство которое вы лично выбрали на голосовании
- 3 замечу что никого из вашего правительства нет на нашей земле, а вот армия которая состоит из граждан рф как раз и воюет на нашей земле. 

Так что продолжайте и дальше быть вне политики...... Успехов и удачи.

**Comment by bossloper** [comment]
@Dreamer0x01 you can permanently override the login image here:
![Untitled](https://user-images.githubusercontent.com/1744687/160588735-41ad49ba-a707-4112-987b-15c6b69ceb87.png)

**Comment by Dreamer0x01** [comment]
Этикет и порядочность не заканчиваются никогда, это одна из основ, кторая позволит в непростой обстановке помочь друг другу выжить. 

> А на предмет: **- Не поддерживаю военные действия, как и заказчики.**
> 
>     * 1 как минимум тем что вы граждане рф а значит платите налоги в свое государство вы и поддерживаете военное вторжение, так что можете себя сколько угодно переубеждать в обратном но факт есть факт.
> 
>     * 2 решение о вторжении приняли не вы лично, а ваше правительство которое вы лично выбрали на голосовании
> 
>     * 3 замечу что никого из вашего правительства нет на нашей земле, а вот армия которая состоит из граждан рф как раз и воюет на нашей земле.

1. Граждане РФ не могут отказаться от уплаты налогов, это принудиловка, поэтому обвинять их в этих платежах как минимум некорректно. Кроме того, нет никакой связи между уплатой налогов гражданами и сайтами, которые они администрируют/разрабатывают. Многие могут и "мимо кассы" их делать вообще. Или делать бесплатно. 
2. Это правительство не единогласно избранное. Миллионы граждан его не выбирали. 
3. Те, кто занят мирными делами вроде разработки сайтов, нигде не воюет и никуда не вторгается, это обычные мирные трудяги. 

Картинку я убрал у тех заказчиков, у которых она появилась. Возмутителен сам факт - мат на официальном ресурсе, вставляемый в сайты заказчиков без их ведома при случайном обновлении. Предупреждения о том, что при обновлении люди получат провокационную картинку с матом, нет нигде.  
Посетители сайта может и действительно не страдают, но вот репутация у CMS за счет таких обновлений снижается моментально, а она и без того не лучшие дни переживала.

**Comment by Dmi3yy** [comment]
Почему меня должно заботить то как вам помочь выжить ? помогайте себе сами я буду помогать тем кто за мир и развитие а не за войну и разрушение. 

1. Граждане РФ не могут отказаться от уплаты налогов - **ну вот по той же причине они соучастники в войне....** 
2 Это как бы демократия когда меньшинство соглашается с большинством, все логично и закономерно за вас приняли решение даже если лично вы против. Да и почему я должен разбираться кто из вас за а кто против??? Сами решайте внутренние ваши проблемы, у нас и своих хватает. 
3. Ну как бы да в стране каждый занимается своим делом но ответственен за то что делает его страна. Я понимаю что в рф все права отдали в руки маленькой группы людей, но я тут при чем это ж ваша проблема а не моя. 

Моя проблема в том что на мою страну напали и я делаю все что в моих силах что б исправить ситуацию, и так же участвую в защите своей страны (да это можно делать не с оружием в руках, а донося инофрмацию другим, или помогая что то созидать или еще кучей способов)

**Предупреждения о том, что при обновлении люди получат провокационную картинку с матом, нет нигде.** - есть чего ж нет ? то что вы не нашли это, вопрос к вам а не ко мне в релизах всегда описаны изменения, да в текущем релизе вместо слов картинка но думаю все понятно и без слов тут (если что коммиты все видны так что понятно что меняли) 

собственно перейдя на страничку релиза сразу бы все поняли: 
https://github.com/evolution-cms/evolution/releases/tag/3.1.10

Я понимаю что политика всех кто в росии что это мир плохой а они самые хорошие, но вот как видим за этой политикой скрывается рашизм, за что собственно и прилетает сейчас ответка. Если у тебя есть член то это не значит что тебя заранее можно садить за изнасилование.... А именно по такому принципу расия ввела войска в Украину.

**Comment by Dmi3yy** [comment]
> Нет, люди не ответствены за то, что делают их правители
хочешь сказать что все населения росии это крепостные?  В целом да соглашусь, так как у счетом того что можно у нас в стране и что можно у вас могу сказать с уверенностью что мы свободные люди а вы нет. Но это никак не противоречит тому что вы виноваты в этом сами, так как по вашим законам вы свободные люди, а по факту крепостные.... 

> Информацию, подаваемую такими способом, обычно игнорируют 
Кто хотел меня услышал, кто то кто не хотел возможно обратит на эту информацию внимание и она станет той последней каплей

> А мы и есть те, кто за мир. Многие. 
Сами себе противоречите как вы можете быть за мир если у вас нет права голоса? За мир могут быть только те у кого есть право выбора, а в первом предложении ваши же слова что у вас нет права голоса и выбора

> Многие эту кнопку жмут по привычке
Очень плохая привычка, так как нужно читать что же там изменилось хотя бы мельком, так как могут быть вещи которые нужно к примеру перепроверить или поправить в определенных условиях или к примеру что то устарело и рекомендуется обновить, а не читая информацию что занимает пару минут потом попадаешь в ситуации когда тратишь много времени, вообщем настоятельно рекомендую менять привычку эту

**Comment by Dreamer0x01** [comment]
> За мир могут быть только те у кого есть право выбора

За мир могут быть все, у кого есть соответствующее мировоззрение. Которое никак не связано с юридическими, фактическими и прочими правами. Это вопрос именно личного выбора каждого. Который совершенно не обязательно учитывается государством, часто еще и подавляется всеми силами. Мы не хотим этой войны, но нас и не спрашивает никто. 

> это никак не противоречит тому что вы виноваты в этом сами

Опять обвинения... Не может быть человек виноватым в том, что он родился в определенном месте в определенное время, и жил в определенных условиях.

**Comment by milkamil93** [comment]
@Dreamer0x01 в дальнейшем советую использовать эту ссылку https://github.com/evocms-community/evolution для обновлений

**Comment by Dmi3yy** [comment]
Отлично я вашу позицию понял, не понимаю только почему вы считаете что другой позиции быть не может?

**Comment by kuklofon** [comment]
Ну чё, как там нынче? Пошёл корабль на хуй или нет?

**Comment by Seiger** [comment]
> 

Тот что на картинке пришвартовался к дну Чёрного моря уже давно. Скоро вся московия пойдет нахуй.

**Comment by kuklofon** [comment]
> > 
> 
> Тот что на картинке пришвартовался к дну Чёрного моря уже давно. Скоро вся московия пойдет нахуй.

Ты бы со своего сайта Русский язык удалил бы, а то не комильфо...

**Comment by Seiger** [comment]
> Ты бы со своего сайта Русский язык удалил бы, а то не комильфо...

Русский язык не пренадлежит росиянам.

как только нас москалей хоть чутка сыкни, так вы вой подымаете. Зато когда ваши ракеты летят по нам то скачете и радуетесь что в нас стреляют.

Так что военный корабль, знаешь место приписки.
