### ISSUE TITLE
Cannot install Evo CMS 3.1.8 - HTTP Error 500

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#2083]
What I did:

1. Dowload https://github.com/evolution-cms/evolution/archive/3.1.8.zip
2. Install on server

Error message appears:

![screenshot 2022-04-05](https://user-images.githubusercontent.com/6764548/161693191-98547fd7-980e-4a8d-91f7-85392a87d4dc.png)

Click "Close" button.

Next I see a page with:

![image](https://user-images.githubusercontent.com/6764548/161693295-142f5309-1b77-4f6f-aab2-223faea57577.png)

> is currently unable to handle this request.
> HTTP ERROR 500

How to fix this? And where can I find the error?

<br><br>

Note: I checked `/manager/includes/config.inc.php` the file is empty after the installation. Is that one of the problems?

Also: The installation was with "SET CHARACTERS" to `utf8mb4_0900_ai_ci` and not `utf8mb4_unicode_ci` which I used before with other EVO installations.

**Comment by fourroses666** [comment]
It says, writing configuration file not found.

You need to check .2: https://forum.evo.im/d/5-how-to-upgrade-evo-1-to-evo-2

**Comment by q2apro** [comment]
But it is a fresh installation. It is no upgrade.

**Comment by Dmi3yy** [comment]
It look like php can’t create config file.

check access to filesystem from php

**Comment by q2apro** [comment]
I created the file `/core/config/database/connections/default.php` manually. It is there now, with the code/config above. Still not working.

**Comment by fourroses666** [comment]
Looks to me like a server thing. Like Dmi3yy says, php can’t create config file, check access to filesystem from php.

**Comment by Dmi3yy** [comment]
500 error, its need to check on error.log file on server or turn on display error in php

**Comment by q2apro** [comment]
I tried to do the installation again, but now there is this error showing up when calling the install script:

> Notice: Constant MGR_DIR already defined in /var/www/html/install/src/controllers/install.php on line 13

> Fatal error: Uncaught Exception: The bootstrap/cache directory must be present and writable. in /var/www/html/core/src/ProviderRepository.php:169 Stack trace: #0 /var/www/html/core/src/ProviderRepository.php(146): EvolutionCMS\ProviderRepository->writeManifest() #1 /var/www/html/core/src/ProviderRepository.php(54): EvolutionCMS\ProviderRepository->compileManifest() #2 /var/www/html/core/src/AbstractLaravel.php(300): EvolutionCMS\ProviderRepository->load() #3 /var/www/html/core/src/AbstractLaravel.php(175): EvolutionCMS\AbstractLaravel->registerConfiguredProviders() #4 /var/www/html/core/src/Core.php(215): EvolutionCMS\AbstractLaravel->__construct() #5 /var/www/html/core/src/Core.php(253): EvolutionCMS\Core->__construct() #6 /var/www/html/core/functions/preload.php(20): EvolutionCMS\Core::getInstance() #7 /var/www/html/index.php(112): evolutionCMS() #8 /var/www/html/install/src/controllers/install.php(194): include('/var/www/html/i...') #9 /var/www/html/install/index.php(85): require('/var/www/html/i...') #10 {main} thro in /var/www/html/core/src/ProviderRepository.php on line 169

How can I do the installation anew (clean)?

**Comment by q2apro** [comment]
I want to reinstall but it always says: "Upgrade Existing Install". But there is no data in the database.

![image](https://user-images.githubusercontent.com/6764548/161713155-93cacdd8-4ede-45a4-a384-0eee31589e1e.png)

Which files do I need to delete to get a fresh installation (dialog)?

**Comment by fourroses666** [comment]
Place a blank config file or rename it.

(this location is not being used in EVO 3 ->  /manager/includes/config.inc.php)

**Comment by q2apro** [comment]
Okay, I tried a fresh installation:

![screenshot 2022-04-05](https://user-images.githubusercontent.com/6764548/161713896-e2a1de32-4cee-4f4c-a139-821d7623727f.png)

After hitting "Okay" I get this error again:

    Notice: Constant MGR_DIR already defined in /var/www/html/install/src/controllers/install.php on line 13

    Fatal error: Uncaught Exception: The bootstrap/cache directory must be present and writable. in /var/www/html/core/src/ProviderRepository.php:169 Stack trace: #0 /var/www/html/core/src/ProviderRepository.php(146): EvolutionCMS\ProviderRepository->writeManifest() #1 /var/www/html/core/src/ProviderRepository.php(54): EvolutionCMS\ProviderRepository->compileManifest() #2 /var/www/html/core/src/AbstractLaravel.php(300): EvolutionCMS\ProviderRepository->load() #3 /var/www/html/core/src/AbstractLaravel.php(175): EvolutionCMS\AbstractLaravel->registerConfiguredProviders() #4 /var/www/html/core/src/Core.php(215): EvolutionCMS\AbstractLaravel->__construct() #5 /var/www/html/core/src/Core.php(253): EvolutionCMS\Core->__construct() #6 /var/www/html/core/functions/preload.php(20): EvolutionCMS\Core::getInstance() #7 /var/www/html/index.php(112): evolutionCMS() #8 /var/www/html/install/src/controllers/install.php(194): include('/var/www/html/i...') #9 /var/www/html/install/index.php(85): require('/var/www/html/i...') #10 {main} thro in /var/www/html/core/src/ProviderRepository.php on line 169

**Comment by q2apro** [comment]
After trying more and more things, I would say that the main problem is this error message (from the error.log):

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: The bootstrap/cache directory must be present and writable. in /var/www/html/core/src/ProviderRepository.php:169"
Stack trace:"
#0 /var/www/html/core/src/ProviderRepository.php(146): EvolutionCMS\ProviderRepository->writeManifest()"
#1 /var/www/html/core/src/ProviderRepository.php(54): EvolutionCMS\ProviderRepository->compileManifest()"
#2 /var/www/html/core/src/AbstractLaravel.php(300): EvolutionCMS\ProviderRepository->load()"
#3 /var/www/html/core/src/AbstractLaravel.php(175): EvolutionCMS\AbstractLaravel->registerConfiguredProviders()"
#4 /var/www/html/core/src/Core.php(215): EvolutionCMS\AbstractLaravel->__construct()"
#5 /var/www/html/core/src/Core.php(253): EvolutionCMS\Core->__construct()"
#6 /var/www/html/core/functions/preload.php(20): EvolutionCMS\Core::getInstance()"
#7 /var/www/html/index.php(112): evolutionCMS()"
#8 {main}"
  thrown in /var/www/html/core/src/ProviderRepository.php on line 169"
```

How to fix this?

**Comment by q2apro** [comment]
I uploaded a `services.php` from another installation, now I get those errors:

```
NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/core/storage/cache//35/6a/356a192b7913b04c54574d18c28d46e6395428ab): failed to open stream: No such file or directory in /var/www/html/core/vendor/illuminate/filesystem/Filesystem.php on line 187

sh: 1: /usr/sbin/sendmail: not found

NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/core/storage//sessions/HA92PfjZlQwZE4ztp5ZBP3FanDV2R4pUinYIqqJv): failed to open stream: Permission denied in /var/www/html/core/vendor/illuminate/filesystem/Filesystem.php on line 187
```

**Comment by q2apro** [comment]
**SOLUTION:**

Obviously the rights of the server-user I had were not sufficient.

So the PHP script could not create files and folders.

See solution at https://stackoverflow.com/q/28806196/1066234
