### ISSUE TITLE
Do clearCache in modal Window

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#21]
Вот идея: раздражает порой, что находясь на каком-то из ресурсов, или чанке, или модуле (неважно где) нужно бывает очистить кеш.
Но после очистки хотелось бы увидеть либо модальное окно, либо просто алярм что кеш успешно очищен. Чтобы он обновлялся в фоне и не сбрасывал менеджера со страницы, на которой он находится.
Кеш обновился в фоне, модальное окно всплыло, менеджер его закрыл,остался на редактировании сниппета, документа,или еще чего....))
http://take.ms/h8s3n

**Comment by 64j** [comment]
#90 resolved
