### ISSUE TITLE
How to hide error reporting to users with EVOCMS? Security vulnerability.

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#2105]
When there is an error in the code of a snippet, it throws an error report frontend.

Example:

![image](https://user-images.githubusercontent.com/6764548/179554421-4b03a1bb-7d17-42b6-99f3-0d6b3293a22a.png)

This SHOWS all the server paths and more details.

And this is also shown to anonymous users.

How to hide these error reports?

Only the CMS user should see them, not others!

In my point of view, this is a security vulnerability of Evolution CMS.

**Comment by Dmi3yy** [comment]
Error you see only if login to manager, if not you see just one word 'Error'

**Comment by Dmi3yy** [comment]
This code do that: 
https://github.com/evolution-cms/evolution/blob/3.x/core/src/ExceptionHandler.php#L413-L429

or if you turn on debug mode then will show for All ) 


by default show only for Managers

**Comment by q2apro** [comment]
Thanks for your reply. But it really shows all errors. Even when not logged in to the manager. That is why I am reporting this problem.

I am running Evo CMS 2.0.x

How to disable it there?

**Comment by q2apro** [comment]
In Evo 2 there is the file `core/src/ExceptionHandler.php`

There you have: `if ($this->shouldDisplay()) {`

```
    protected function shouldDisplay()
    {
        return isset($_SESSION['mgrValidated']) || $this->container['config']->get('app.debug');
    }
```

I ran one PHP snippet with error ... and there was really only `Error` showing up.

Maybe I had a session cookie in the browser or so that the error was displayed beforehand. 

Case closed.
