### ISSUE TITLE
evocms 1.4; error saving system settings when manager folder is renamed

### ISSUE THREAD

**Issue by FYL99** [evolution-cms/evolution#2106]
after install, when the manager folder is renamed; everything seems to be working except the system settings cannot be saved,
when pressing the save button goes into 403 forbidden error. When renamed back to "manager" it works.

Far as I can tell, it does not reach the "case 30:" from the manager/index.php

**Comment by AndrewMInsk** [comment]
> 

Hi. Did you try disable mod_security?
