### ISSUE TITLE
Manager partially no icons, no working checkbox-styles

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#211]
Missing icons:
![2017-09-04_20 48 28](https://user-images.githubusercontent.com/24967436/30037011-3f7dcd74-91b8-11e7-81b4-54c06f9aefc3.jpg)

How it should be and is in some other installs:
![2017-09-04_20 49 28](https://user-images.githubusercontent.com/24967436/30037026-6113d96a-91b8-11e7-84ba-8f0e41e2a09c.jpg)

Checkboxes no state visible:
![2017-09-04_20 47 55](https://user-images.githubusercontent.com/24967436/30037042-73249fcc-91b8-11e7-949d-5f603bc6ea55.jpg)

**Comment by 64j** [comment]
Go into the configuration of the plugin ElementsInTree and save.
Log into the system configuration and save

**Comment by leonie12** [comment]
Did both. Now tree icons are showing. Should I or someone else have known this solution?

Checkbox states still not showing anywhere in manager.

**Comment by 64j** [comment]
Does not show only the status of the site?

**Comment by leonie12** [comment]
Not only status but all checkboxes everywhere in manager.

Seems to be a result of following entry in root htaccess:`# Content-Security-Policy
<IfModule mod_headers.c>
Header always set Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self' env=HTTPS
</IfModule>`.

**Comment by bossloper** [comment]
I also do not see checkbox styles in the manager, but it is only when using Edge browser. Chrome and Firefox are ok.

**Comment by fourroses666** [comment]
Is it CSS? Something like; `-webkit-appearance: none;` or `input[type=checkbox]
{
  -webkit-appearance:checkbox;
}`

**Comment by Nicola1971** [comment]
i always have issue on update with EIT plugin that does not parse docblocks (need copy properties from old version), not understand why

**Comment by bossloper** [comment]
@fourroses666 - yes you are right about the reason for the missing checkboxes/radio button states using Edge browser.

If '-webkit-appearance: none' is removed, or the 'input' element removed from this line: 
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/css/forms.css#L14
Then they are displayed correctly.

**Comment by 64j** [comment]
what is the relationship between WebKit and Edge ?
-webkit- has nothing to do with Microsoft browsers

**Comment by bossloper** [comment]
Looks like edge checks for webkit and converts them if it can?

see here for one thread:
https://www.reddit.com/r/webdev/comments/3zv5sg/how_does_microsoft_edge_use_webkit/?st=j77kbj18&sh=5412feff

and here (EdgeHTML) if you believe wikipedia :-)

https://en.wikipedia.org/wiki/Microsoft_Edge

**Comment by 64j** [comment]
Edge tries to show WebKit styles, but can not cope. Is this our problem? :)

**Comment by bossloper** [comment]
Browser incompatibility... sigh... it never ends!

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/30061277-6dc151be-924f-11e7-9f78-9ea713ee15f7.png)

**Comment by 64j** [comment]
@leonie12 @bossloper 
The arrow shows at the selections?


![image](https://user-images.githubusercontent.com/4653189/30061447-0c1dca40-9250-11e7-9177-534666b581ef.png)

**Comment by bossloper** [comment]
But that is an emulator?
The real Edge browser (+ does not show arrow selections)
![untitled](https://user-images.githubusercontent.com/1744687/30061516-8f407ec4-923f-11e7-8a28-40dff4cdd2ba.png)
:

**Comment by bossloper** [comment]
then with  '-webkit-appearance: none' removed and an F5 refresh... magic:
![untitled](https://user-images.githubusercontent.com/1744687/30061642-0d1b2ee8-9240-11e7-90d1-3fa7230fd79f.png)

**Comment by bossloper** [comment]
I had the arrows showing on the sections until I did a few F5 Ctrl/F5 cache clears, tabded to anther tab and back then a couple more cache clears. It is very strange, they did not disappear straight away.

**Comment by 64j** [comment]
@leonie12  @bossloper 
You can independently find a solution for the browser Edge and send corrections

Here, try
https://jsfiddle.net/rsr7ny5n/3/

**Comment by bossloper** [comment]
I think I have a fix, but need to go out of the office right now. I will check it later....

**Comment by leonie12** [comment]
My issue is with firefox, not edge, and seems to be caused by content security policy.
CSP should be common today. Checkbox states should work also with CSP.

Removing -moz-appearance: none from forms.css imported by page.css shows browser default checkbox styles also with CSP in place. Better solid function than nice styles that are not visible.

**Comment by bossloper** [comment]
So two separate issues with the same symptom.
@leonie12 - Looks like this might be your issue, related to the definition of the images?: https://pokeinthe.io/2016/04/09/black-icons-with-svg-and-csp/
... but all getting beyond my understanding!

**Comment by 64j** [comment]
@leonie12 
change your htaccess
add **img-src 'self' data:;**
```
<IfModule mod_headers.c>
Header always set Content-Security-Policy "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self' env=HTTPS
</IfModule>
```
also show errors on tinymce 4
**frame-ancestors 'self' env=HTTPS**
![image](https://user-images.githubusercontent.com/4653189/30076600-12a37f90-9282-11e7-94f0-a2e4be0a6882.png)

**Comment by leonie12** [comment]
adding img-src 'self' data:; to .htaccess in manager folder does the trick without allowing data: for frontend
