### ISSUE TITLE
Manager User- Photo

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#212]
For 'Security' -> 'manager users':
- edit a manager account
- select 'Photo' tab
- click insert for the 'User Photo' causes a 404 error:

''The requested URL /manager/media/browser/default/browser.php was not found on this server."

Does anyone use 'photo' for managers or members? I cannot imagine storing individual photos in the centralised/shared file resource area, it is just asking for someone to switch a photo :-)

**Comment by 64j** [comment]
select file browser for manager

![image](https://user-images.githubusercontent.com/4653189/30092040-5c8e81f2-92c5-11e7-9470-d7d18391c128.png)

**Comment by bossloper** [comment]
What is the logic here? Surely if it is left as 'default'it should pick up the system default browser and not need to specifically be set for all manager accounts?
It does state underneath:
 To use the System´s default Browser, leave it on "Default".... and my default browser in 'system configuration' is set to 'mcpuk'

**Comment by 64j** [comment]
@bossloper 
If your problem is solved, you can close the question

**Comment by bossloper** [comment]
Didn't realise @Deesen had put a fix in. Yes, looks good, thanks. Closing....
