### ISSUE TITLE
WARNING is displayed when "Input type" is set to "Date" in "Template variables" of "Elements"

### ISSUE THREAD

**Issue by sbwe7** [evolution-cms/evolution#2122]
When the "Input type" was set to "Date" in "Template Variables" of "Elements", WARNING was displayed on the screen for creating a new resource or editing a resource.

> Error : Trying to access array offset on value of type null

It seems that `$_style["icon_calendar_close"]` on line 760 of the core/functions/actions/mutate_content.php file is the cause.

Changing `$_style["icon_calendar_close"]` to `ManagerTheme::getStyle('icon_calendar_close')` will make the WARNING disappear.
However, when I clicked on the displayed icon, the Datepicker did not appear.

Confirmed this issue with Evolution CMS version 3.1.10.

**Comment by Seiger** [comment]
Could not confirm the problem in EVO version 3.2.2

**Comment by sbwe7** [comment]
Thank you.
It was confirmed that there was no problem.
