### ISSUE TITLE
readme screenshots need update

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#214]
We need to update EVO repository readme screenshots with new theme and without MODX logo.
Replacements:
![evo-login](https://user-images.githubusercontent.com/7342798/30128617-a74d689c-9343-11e7-9ef5-5a37c3b94cf1.jpg)
![evo-home](https://user-images.githubusercontent.com/7342798/30128635-b34fa2a4-9343-11e7-9d87-13d0e17fb69e.jpg)
![evo-edit](https://user-images.githubusercontent.com/7342798/30128638-b5b2cdc8-9343-11e7-8c75-0864d00fe28a.jpg)

do we want a screenshot with the new menu? 
menu + home
![evo-menu](https://user-images.githubusercontent.com/7342798/30128677-d1988d3e-9343-11e7-9c4e-03eb264eb317.jpg)

or
menu+elements
![evo-menu-elements](https://user-images.githubusercontent.com/7342798/30128689-de10f7cc-9343-11e7-99a9-1cc8fcb52958.jpg)

**Comment by dmi3yy** [comment]
Will be great with gif video 


Отправлено с iPhone

**Comment by fourroses666** [comment]
I was thinking of animated gif / video. but also pimp it up below that.

Can't find exactly what I was looking for but looks like this: (images)
https://themeforest.net/item/ovitahealth-onepage-multipurpose-wordpress-theme/20524866?s_rank=2
https://themeforest.net/item/lookz-wordpress-ecommerce-theme/7307521?s_rank=1

**Comment by Nicola1971** [comment]
> Will be great with gif video
@dmi3yy  yes but what focus in the video?

@fourroses666  agree. more cool.

**Comment by dmi3yy** [comment]
new menu, tabs, move docs in tree.


От 7 сентября 2017 г. в 13:34:47, Nicola (notifications@github.com) написал:

Will be great with gif video
@dmi3yy <https://github.com/dmi3yy> yes but what focus in the video?

@fourroses666 <https://github.com/fourroses666> agree. more cool.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/214#issuecomment-327761635>,
or mute the thread

**Comment by Nicola1971** [comment]
for now, i've just replaced the old ones, only to replace modx logo and avoid confusions to users with the new manager look :D

**Comment by fourroses666** [comment]
![test3](https://user-images.githubusercontent.com/523389/30167722-94b0002e-93e7-11e7-9a34-9b9de8eb6058.gif)

**Comment by fourroses666** [comment]
We should center the manager login screen horizontally as vertically for better looks

**Comment by Nicola1971** [comment]
@fourroses666 
![evo-login2](https://user-images.githubusercontent.com/7342798/30167975-5ec146c0-93e8-11e7-8cf8-b324c2b09477.jpg)

**Comment by fourroses666** [comment]
Yes :)

Only on mobile to top.

Here some other example _( used http://ami.responsivedesign.is )_

![example](https://user-images.githubusercontent.com/523389/30168298-46758dbe-93e9-11e7-975d-125f3604059a.jpg)

**Comment by Nicola1971** [comment]
very cool Marc

**Comment by dmi3yy** [comment]
Nice

**Comment by bossloper** [comment]
I wish my office setup looked like that!

**Comment by fourroses666** [comment]
I'm missing a laptop but the others I have :P
