### ISSUE TITLE
Chunks and Snippets are not listet and every elements cannot be saved

### ISSUE THREAD

**Issue by Thaars** [evolution-cms/evolution#215]
After an upgrade from 1.0.14 to 1.3.4, all chunks and snippets are not listet in their tabs. I can see and edit them through the top menu only. 
All elements cannot be saved or better, they can be saved without any errors, but nothing will be persisted to the database.

Other stuff can be saved. Configuration and pages are editable and the changes will be persisted to the database. So it is writable.

An upgrade to 1.3.6 today doesn't fixed anything.
My PHP Version is 7.1.8.

**Comment by Deesen** [comment]
I had the same issue but had no time to find out the exact reason. In my case re-running the installer, without any checkboxes ticked, helped to solve this issue.

**Comment by Thaars** [comment]
Thanks for the fast reply, this solved my issue!

**Comment by dmi3yy** [comment]
Its or browser cache or not all files are copied. Rerun install helped

Отправлено с iPhone
