### ISSUE TITLE
Если авторизоваться менеджером с ролью Editor, показывается сообщение об ошибке.

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#220]
В блоке "Добро пожаловать в систему управления сайтом" показывается следующее сообщение:

> Parse error: syntax error, unexpected ';' in D:\Dreamer\OpenServerFiles\OpenServer\domains\golledge\public_html\manager\includes\document.parser.class.inc.php(1267) : eval()'d code on line 1

Показывается только при авторизации в админке менеджером с ролью editor, у которого не полные админские права.

**Comment by 64j** [comment]
@Dreamer0x01 
Да, такая ошибка есть в последних правках, надеюсь скоро починим.

https://github.com/evolution-cms/evolution/commit/4b6c3946746af6aa42b4cefc1b9d60420c71e264
