### ISSUE TITLE
Сортировка по позиции меню не открывается, если на данном уровне есть ресурсы с ограниченными правами

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#221]
Скрыл от менеджеров с ролью  Editor доступ к некоторым ресурсам, таким, как страницы оформления заказов и др., чтобы они случайно их не удалили/испортили.

Но теперь, если менеджер с ролью Editor пытается отсортировать ресурсы с помощью кнопки "сортировать по позиции в меню", и на этом уровне есть закрытые от него ресурсы - система выдает Alert со следующим содержимым:

> У вас недостаточно прав для просмотра данного ресурса.

И отсортировать такой уровень без админских прав не получается.

**Comment by 64j** [comment]
всё верно, у эдитора нет прав изменять защищённые ресурсы, а при сортировке ресурсы изменят свой menuindex. Вот и показывает предупреждение. Ошибки здесь нет.

**Comment by Dreamer0x01** [comment]
Да, но если требуется при этом изменить порядок у незащищенных ресурсов, находящихся на том же уровне вложенности, как это ему сделать?

**Comment by 64j** [comment]
@Dreamer0x01 если разрешить, то он в любом случае поменяет индекс и защищённых ресурсов, а это противоречит его правам.
Можно зайти в ресурсы у которых нужно поменять индекс изменить в каждом, не затронув защищённые.

На то они и защищённые, что их запрещено изменять.

**Comment by Dreamer0x01** [comment]
Это путает менеджера. Он ведь не видит защищенных ресурсов, и визуально у него список ресурсов конкретного родителя не отличается никак от списка ресурса другого родителя, у которого нет защищенных ресурсов внутри. И сообщение "У вас недостаточно прав для просмотра данного ресурса" получается не понятным, так как для просмотра родительского ресурса у него как раз-таки права есть.

 

> если разрешить, то он в любом случае поменяет индекс и защищённых ресурсов
Можно же при сортировке их просто не показывать и не затрагивать. Будет равносильно вот этому:

> Можно зайти в ресурсы у которых нужно поменять индекс изменить в каждом, не затронув защищённые.

Только, более понятно и наглядно.

**Comment by 64j** [comment]
@Dreamer0x01 
Не совсем конечно понимаю. Возможно мы говорим немного про разные версии Ево.
В релизе, кнопка есть, но поменять нельзя если у эдитора ограниченные права.
В девелоп уже этой кнопки у эдитора нет, если права не позволяют редактировать и сохранять ресурс.

Покажите какие права есть у роли Эдитора.

**Comment by Dreamer0x01** [comment]
Версия 1.3.6, релизная. 

Смотрите, я наделал скриншотов.
https://yadi.sk/d/PRnpOFF-3MjoSn

Первый скриншот - это то, как видит менеджер. Он в общем-то и знать не знает, что там есть еще и какие-то системные ресурсы, которые трогать нельзя, они ему и не показываются. Но если на верхней панели иконок щелкнуть кнопку сортировки (чтобы отсортировать ресурсы корневого уровня) - то система выдаст ругательство. 

На втором скриншоте то же дерево, но из аккаунта админа. 

Но нужно как-то дать возможность заказчику самому менять последовательность вывода этих разрешенных для него ресурсов, так как из них строятся менюшки на сайте. 
Вполне логично было бы сортировку осуществить только среди ресурсов, которые ему доступны, не затрагивая при этом закрытые. 

На следующих скриншотах - настройки прав для ресурсов и групп.

**Comment by 64j** [comment]
@Dreamer0x01 
> Но если на верхней панели иконок щелкнуть кнопку сортировки (чтобы отсортировать ресурсы корневого уровня) - то система выдаст ругательство.

Тут дело не в сортировке (этой кнопки у менеджера без прав создать и сохранить док - уже нет), дело в доступе к корневому разделу, это в конфигурации уже задаётся.
Надстройка так и называется - **Разрешить доступ к корневой папке** (по умолчанию нет).

**Comment by Dreamer0x01** [comment]
Да, насчет корневой папки вы правы, все исправилось этой настройкой.

Но выявилась другая проблема, хотя и не критичная - когда перехожу в режим сортировки внутри какого-то ресурса - то в дереве закрытые ресурсы не показываются, а в сортируемом списке - показываются. Тут нужно тогда либо чтобы вообще нигде не показывалось, либо показывалось везде. Хотя и не влияет на работоспособность.

**Comment by 64j** [comment]
> ...а в сортируемом списке - показываются
да это в будущем поправим?

**Comment by Dreamer0x01** [comment]
Ну тут уже вам виднее :)

**Comment by 64j** [comment]
@Dreamer0x01 если вопрос решён, вы можете его закрыть.

**Comment by Dreamer0x01** [comment]
Да, спасибо. Пунктик с различным отображением вынес в отдельную ветку.
