### ISSUE TITLE
Several display issues

### ISSUE THREAD

**Issue by Neoziox** [evolution-cms/evolution#223]
I have just update to 1.3.6 my website and I have several display issues. First, on my desktop computer (Safari on an iMac):
- duplicate area of the Code source (in the Ressource content, in **Snippet code too**)
<img width="820" alt="capture d ecran 2017-09-13 a 08 24 22" src="https://user-images.githubusercontent.com/13981358/30362647-49a9a33a-985d-11e7-8c4a-e39044966e35.png">
<img width="573" alt="capture d ecran 2017-09-13 a 08 26 29" src="https://user-images.githubusercontent.com/13981358/30362650-4cde8ebc-985d-11e7-96ce-bedf8c123819.png">

- where is the WYSIWYG display?
<img width="799" alt="capture d ecran 2017-09-13 a 08 23 28" src="https://user-images.githubusercontent.com/13981358/30362562-dc00a86a-985c-11e7-8572-0e6072161b21.png">

On my iPad:
- cannot scroll completly in a code source area
**Edit**
I found the solution for the iPad: when I select the a snippet, I cannot scroll to the bottom of the code (ex. stop at the line 31 on 177). I lock the iPad. I open it and then I can scroll all the snippet.

**Comment by dmi3yy** [comment]
Hi sorry for long answer 

try resave tinymce4 and turn off previous verion if have 
and check in evo settings for enable tiny4

For ipad try to check. have only iphone. and there all ok
