### ISSUE TITLE
Snippet if stopped working

### ISSUE THREAD

**Issue by F1fanatik** [evolution-cms/evolution#224]
After snippet changes IF stopped working structure (После последней правки сниппета if перестала работать конструкция) :
[[if? &is=`[*parent*]:=:5` ...   or (или)   [[if? &is=`[*parent*]:is:5` ..  , 
So works (Так работает) ..
[[if? &is=`[*parent*]:in:5` ..

**Comment by Deesen** [comment]
Related to https://github.com/evolution-cms/evolution/commit/a2023bcb5f3c2cc91a2a570df43c393fd5d05f0d I guess. For me a simple case like the following returns `false`:

```
[[if?&is=`inner:is:inner`&then=`true`&else=`false`]]
```

**Comment by yama** [comment]
Does this work?

[snippet.if.zip](https://github.com/evolution-cms/evolution/files/1295273/snippet.if.zip)

**Comment by F1fanatik** [comment]
Yes..

**Comment by Deesen** [comment]
For me too :+1:

**Comment by yama** [comment]
thanks, I'll commit it later
