### ISSUE TITLE
Ditto pagination issue

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#225]
1.3.6/1.4beta: using pagination with ditto, all **&start** pages are empty
i cant replicate on all my servers, but happened with a live site with php 5.5.32 and with my local UWAMP php 7.1.2 (clean evo install)

on a default install, just changing ```&display=`2` ``` to ``` &display=`1` ``` to enable pagination
![download](https://user-images.githubusercontent.com/7342798/30317880-c6042502-97ab-11e7-8ee4-2e1703ffde27.png)

**Comment by Nicola1971** [comment]
note: ditto object error is related to reflect snippet (not the same issue)

**Comment by modxuser** [comment]
Being an experienced user of Evo I don't think this will be relevant, but I will post it anyway:

The page where the pagination is being called has to be set to "uncached", if it's cached the pages won't show in the pagination

**Comment by Nicola1971** [comment]
@modxuser is not the classic pagination/cache :(  
tried any combination of page and ditto call caching

**Comment by yama** [comment]
Is this solved?

**Comment by Nicola1971** [comment]
@yama can not test on the live site (moved to doclister), but just tested last dev with two local server : **Wamp** (php5.5.1.2) and **uWamp** (php 7.1.2 ) still the same issue

**Comment by Nicola1971** [comment]
tested on the same local server 
- 1.3.3 no pagination issue
- 1.3.5 pagination issue

**Comment by yama** [comment]
ok, could you please show me the test case? (snippet call)

**Comment by Nicola1971** [comment]
on demo content, just change display to 1 to enable pagination: second pagination page (blog.html?start=1)  is empty
```[[Ditto? &parents=`0` &display=`1` &removeChunk=`Comments` &tpl=`ditto_blog` &paginate=`1` &extenders=`summary,dateFilter` &paginateAlwaysShowLinks=`1`]]```

**Comment by yama** [comment]
thanks, I'll fix it later

**Comment by BBloke** [comment]
I have the same issue.  I did a quick test.  

I have a ditto pagination set at 20 with a page containing 27 in total.  Visiting it normally I get a debug result that says Summarize: 20, Total: 27, Start: 0; Stop: 20.

When I click on the second page ?start=20 the debug changed to Summarize: 20, Total: 27, Start: 20; Stop: 7.

Everything else in the debug is the same for either page visited with the exception there is no output for page 2.

Checking a previous version of Evo I think the debug should read Summarize: 20, Total: 27, Start: 20; Stop: 27.

I hope this helps.

**Comment by yama** [comment]
Probably I think that it works correctly. Very thanks.

**Comment by BBloke** [comment]
Well.  I decided to look around my site.  I have two pages using Ditto.  Surprisingly one works and one doesn't.

I added the snippet parameters that were missing between the two pages and wow, it worked.  I rolled it back and added the following 2 params and it now works!

&sortBy=`createdon` 
&sortDir=`DESC`

Very very strange!

**Comment by yama** [comment]
thanks, There seems to be a problem still.

https://github.com/evolution-cms/evolution/commit/7bd9df4959bc69655537a0b51eee80ebfe62838d#diff-32bb636196f91ed59d7a49190e26b42c
This is the part that I modified this time. It is a part that has no direct relation with page processing.
With this fix, page processing now works correctly.

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/8bd2518d54ceb5b842ab7264f369fb8c9c876f41#diff-96333af4856c4f9b489aa25de1ddafec
maybe since this commit
$inputs = array_filter(array_map('trim', explode(',', $orderBy['unparsed'])));

**Comment by BBloke** [comment]
Thanks Yama.  It looks like when there are no sort parameters it wouldn't produce the correct output.

**Comment by BBloke** [comment]
@yama I guess migrating to DocLister would be a better way forward?

**Comment by yama** [comment]
If run the benchmark, Ditto is lighter on usually case. However, DocLister is lighter on big sites. I think that it is good to use properly as necessary.

**Comment by Nicola1971** [comment]
@yama  seems working now, have you fixed?

**Comment by BBloke** [comment]
Yes.  My Ditto snippet works but it needed the two additional params in the snippet to ensure pagination.

**Comment by user83743** [comment]
similar situation here - i needed to specifically add the 'display' parameter to the Ditto call, but i can set the 'display' parameter to any value 1,2,3,4,5... and it works. it is the "summarize" parameter that actually controls the number of elements that are displayed on each page.  This is our evo-1.3.6 on php7 and ditto pagination was broken. this evo-1.3.6 is an upgrade from modx-1.2.1 .  Then i added  " &display=`2` " and the pagination works - but it also works for display=`5`.  and it has to be uncached   [!dittocallhere!] .

**Comment by Nicola1971** [comment]
This issue can be closed.

NOTE: @user83743 and @BBloke  &display = &summarize  are the same parameter:
Number of documents to display (per page if pagination is on) 

from Ditto Cheatsheets:
![download](https://user-images.githubusercontent.com/7342798/34868894-862942f2-f785-11e7-8486-769839ff4485.png)
