### ISSUE TITLE
Document tree - no submenu on 1&1 Server

### ISSUE THREAD

**Issue by evo136** [evolution-cms/evolution#226]
After hours of searching now i ask the forum,
i have big trouble with the document tree - there is no submenu for the pages displayed - but when i select a folder/site i can see the resourses of this document (folders and sites).

This problem is only on my websites (3) i hoste on 1&1 servers. All my other websites are running perfectly - the document tree menu is working fine.

![screenshot](https://user-images.githubusercontent.com/31884869/30319983-9e2b8bdc-97b1-11e7-990d-e69ed1843a1b.jpg)

**Comment by dmi3yy** [comment]
Try on this checkbox 
http://take.ms/SuU7W

**Comment by evo136** [comment]
Many thanks ;) it works.

Von: Dmytro Lukianenko [mailto:notifications@github.com]
Gesendet: Dienstag, 12. September 2017 12:02
An: evolution-cms/evolution
Cc: Dirk Bulda; Author
Betreff: Re: [evolution-cms/evolution] Ducument Tree - no submenu on 1&1 Server (#226)


Try on this checkbox
http://take.ms/SuU7W
