### ISSUE TITLE
MultiTV + Richtext problem

### ISSUE THREAD

**Issue by kulmjens** [evolution-cms/evolution#228]
Hi there,

first of all, why can't I submit an issue directly at the multitv respository at evolution extras?

I'm running MODX 1.2.1 and MultiTV 2.0.12. I have a richtext field in my config. In the vertical list all richtext fields are displayed correctly:
```
item 0
-- title [text]
-- content [richtext]
item 1
-- title [text]
-- content [richtext]
item 2
-- title [text]
-- content [richtext]
```
When I hit save, only the value of the last richtext field is saved correctly. All other remain at the value they had before.
I added a `console.log` in the file `multitv.js` at the function `saveMultiValue` and everytime I wrote something in a richtext field that was not the last, the values in that function did not update.
And while inspecting the HTML code I noticed that `item 0` has 3 tinymce-DIVs inserted before the textarea, the `item 1` has 2 and only the last item has only one tinymce-DIV added before the textarea. Maybe that is the issue?

**Comment by Deesen** [comment]
So I guess this is related with #227 .. hmm ..

**Comment by kulmjens** [comment]
Okay, I found a workaround:
Starting at line 342 of `multitv.js`
```
//Dmi3yy add inline tinyMCE
if (typeof tinyMCE !== 'undefined' && this.options.mode == 'vertical') {
  $('.inlineTabEditor', _this.fieldEditArea).each(function () {
    var editorId = $(this).attr('id');
    var theme = $(this).data('theme');
    if (tinyMCE.majorVersion == 4) {
      if (modxRTEbridge_tinymce4 != undefined && $(this).data('tiny-init') != 1) {
        var configObj = theme != undefined ? window['config_tinymce4_'+theme] : window[modxRTEbridge_tinymce4.default];
        configObj['selector'] = '#' + editorId;
        configObj['setup'] = function(ed) { ed.on("change", function(e) { documentDirty=true; tinymce.triggerSave(); jQuery('#'+_this.tvid).transformField("saveMultiValue"); }); };
        tinyMCE.init(configObj);
        $(this).attr('data-tiny-init',1);
      } else {
        //tinyMCE.execCommand('mceAddEditor', false, editorId);
      }
    } else {
      tinyMCE.execCommand('mceAddControl', false, editorId);
    }
    tinyMCE.DOM.setStyle(tinyMCE.DOM.get(editorId + '_ifr'), 'height', '200px');
    tinyMCE.DOM.setStyle(tinyMCE.DOM.get(editorId + '_tbl'), 'height', 'auto');
    tinyMCE.DOM.setStyle(tinyMCE.DOM.get(editorId + '_ifr'), 'width', '100%');
    tinyMCE.DOM.setStyle(tinyMCE.DOM.get(editorId + '_tbl'), 'width', '100%');
  });
} else if (typeof CKEDITOR !== 'undefined' && CKEDITOR.version.substr(0,1) == 4) {
  $('.inlineTabEditor', _this.fieldEditArea).each(function () {
    var editorId = $(this).attr('id');
    var theme = $(this).data('theme');
    var configObj = theme != undefined ? window['config_ckeditor4_'+theme] : window[modxRTEbridge_ckeditor4.default];
    CKEDITOR.replace(editorId, configObj);
  });
}
```
So first I added ` && $(this).data('tiny-init') != 1` to the third IF-condition. After the `tinyMCE.init(configObj);` I added `$(this).attr('data-tiny-init',1);` so that I know if this richtext is already initialized. And finally I commented out `tinyMCE.execCommand('mceAddEditor', false, editorId);` in the ELSE-Block directly after the `tinyMCE.init(configObj);`
Don't ask me why this is working. At least it solves my problem. Maybe @dmi3yy can have a look at this block, because he added it. :-)

**Comment by Deesen** [comment]
In my case this did not help.

**Comment by Deesen** [comment]
Maybe https://github.com/evolution-cms/evolution/issues/227#issuecomment-329102512 is helpful?

**Comment by dmi3yy** [comment]
tested on 1.4.7 and 2.0.14 all ok
