### ISSUE TITLE
More global TinyMCE settings in user

### ISSUE THREAD

**Issue by kulmjens** [evolution-cms/evolution#229]
Hi there,

in the user settings there are setting for TinyMCE. I think there should also be buttons with "use global value" for "custom plugins", "custom buttons" and "block formats" like there are for the setting above.

Problem: I've edited the global settings for the TinyMCE buttons in the configuration tab. But all the other users don't see the changes and their TinyMCEs render with the setting from before.
I have to edit the user, delete all content from the "custom buttons" field and save the user. Only now the TinyMCE renders with the global settings. And furthermore when I edit the user once more, the "custom buttons" field is filled with the standard settings, not the new global ones. :-(

Or is there a trick that I don't know?

- MODX 1.2.1, TinyMCE 4.3.7.2

**Comment by Deesen** [comment]
Those "global settings"-checkboxes should work independently from values you set in any custom setting. No matter if you tick this checkbox or not, any value you enter should be saved and reloaded correctly.

Just to assure: A user must log out and login again for new settings to take effect. But this does not explain why your settings change to "standard" when you edit a user again. Hmm..

**Comment by kulmjens** [comment]
Hmmm... the thing is that there are no "global settings"-checkboxes for "custom plugins", "custom buttons" and "block formats".

**Comment by Deesen** [comment]
Oops ok, they have been added with https://github.com/modxcms/evolution/commit/6230c969d03a334c656ef2964fda9e8c6ebe27b7#diff-b74a444a8cb45b761e6074e4ff9d9f39 which was merged first in MODX 1.2.2.

**Comment by kulmjens** [comment]
Aha! Okay, my fault. I should have updated the thing first... :-D
