### ISSUE TITLE
Transferring a resource to the folder of its own child (Перенос ресурса в папку собственного потомка)

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#23]
Now changing the parent of the resource, you can specify one of its descendants.
After this procedure, the site falls, because it can not build a tree of aliases (looped).
It would be nice to check whether the new parent is the document itself or one of its descendants, in order to avoid such situations.

Сейчас меняя родителя ресурса, можно указать одного из своих потомков.
После такой процедуры сайт падает, так как не может построить дерево алиасов (зацикливается).
Хорошо бы сделать проверку, не является ли новый родитель самим документом или одним из его потомков, что бы избежать таких ситуаций.

**Comment by Dreamer0x01** [comment]
Теперь из-за этой правки не работает перенос ресурса внутрь "соседа". 
Проверять на наличие среди множества идентификаторов родителей нужно не oldparent, а сам id.

Отправил pull_request.
