### ISSUE TITLE
Renaming Folder "assets" for better Security

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#230]
I would like to suggest an enhancement to make Evolution CMS more secure. 

We already have the option to rename the `manager` folder. The other standard folder that comes with the installation is `assets`. When we could add an option to rename this folder as well, no bot could easily infiltrate, in my opinion. 

There were recent incidents that bots captured several evo/modx websites in Lithuania. The bot just searched for the assets path and a vulnerable module. If the path would be different, the bot had never found it. 

Thanks for your consideration. And great work, I love the new Evolution CMS!

**Comment by Deesen** [comment]
I think the idea is great, but I guess the problem is that many many addons use hard-coded paths to "assets/.../component". So all those addons will need an update.

**Comment by q2apro** [comment]
Which is good, then all developers would notice that the *new* Evolution CMS is there. Good from my point of view to raise awareness!

**Comment by dmi3yy** [comment]
we do it with manager folder and can do with assets but we are ned one static folder of file with  settings new name.  Now it in assets/cache/

**Comment by dmi3yy** [comment]
Now i have some work after have time want finish docs.evo.im and then refactor extras for normal work and after this return for work on core

**Comment by Pathologic** [comment]
It would be better not to use vulnerable components or fix them than to hide. And I agree with Deseen, that a lot of sites and components will be broken after renaming assets folder. So the whole cms conception need to be changed, but today we even have no any established scheme of storing component assets as well as clear directory structure.
