### ISSUE TITLE
Modifier usage throws syntax error

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#232]
1.3.3 -> 1.3.6

Parse error: syntax error, unexpected '||' (T_BOOLEAN_OR) in /home/....../manager/includes/extenders/modifiers.class.inc.php(350) : eval()'d code on line 1

Condition that produces this warninig
```
[*green_design:is(`1`):then(`<link rel="stylesheet" href="/css/green.css">`)*]
```

**Comment by sashabeep** [comment]
Another one call which works in 1.3.3 but not in 1.3.6:
```
[!Breadcrumbs[*template:is(`7`):or:is(`17`):then=`?&showCurrentCrumb=0`*]!]
```
@yama WHYYYY..... :(

**Comment by yama** [comment]
Is this fixed?

**Comment by dmi3yy** [comment]
[!Breadcrumbs[*template:is(`7`):or:is(`17`):then=`?&showCurrentCrumb=0`*]!]. 1.4.0.b work fine
