### ISSUE TITLE
replace does not work in the 1.3.6

### ISSUE THREAD

**Issue by skMikhail** [evolution-cms/evolution#234]
#This is work fine:
```[+img-gallery49:replace=`small,medium`+]```
,but this does not work anymore:
```[*img-gallery49:replace=`small,medium`*]```

**Comment by yama** [comment]
It works in my development environment(1.3.6dev). Is there any other more info?

**Comment by skMikhail** [comment]
The example:
I have the TV parameter "img-news". TV type: image. Visual component: image.
At the target page, the value of the TV is set to "assets/images/small/image.jpg"

I have a chunk "testChunk" with the following code
``` 
[*img-news:replace=`small,medium`*]
[*img-news*]
``` 

I call this chunk in the main content of the target page
``` {{testChunk}} ```

I receive the following output:
```
<img src="assets/images/small/image.jpg" alt="image" />		
```

As you can see, the first string, with the "replace" method, does not shown. In the version 1.2.1 all work fine, but in the version 1.3.6 I have this issue.

**Comment by yama** [comment]
Thanks, I tried reproducing the composition, but it worked. Hove you any other information?

**Comment by skMikhail** [comment]
Well, I don't know what to say. The provided example does not work in all of my sites. I am using the PHP Version 5.5.38, PHx 2.2.2. Could you provide a link to the source code, where the "replace" method is implemented, please? I'll try to compare the current version of the source code with the version in the 1.2.1 release.

**Comment by yama** [comment]
Is this fixed?

**Comment by skMikhail** [comment]
I don't see any new releases. As I can see, the last release is 1.3.6 so far. The issue is still present. I did not fix this issue.

**Comment by dmi3yy** [comment]
Test on 1.4.0b 
[*longtitle:replace=`Blog,medium`*] - work fine
