### ISSUE TITLE
don't work Friendly URL alias path

### ISSUE THREAD

**Issue by Grinyaha** [evolution-cms/evolution#235]
Check Friendly URL alias path. In 2 sites don't work.

**Comment by yama** [comment]
Could you give me more information?

**Comment by Grinyaha** [comment]
If to activate "aliaslistingfolder" -> don't work "use_alias_path"

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/5efed9f787271b33c600a088142079c5dfe49308
Thanks. maybe fixed

**Comment by dmi3yy** [comment]
tested now all ok
