### ISSUE TITLE
Modifiers Issue with ddGetMultipleField

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#236]
I'm using ddmultiplefield for populating slider item with some columns
```
<div class="orbit-slide" style="background-image:url([+col0+])">
	<div class="row align-middle align-center">
		<div class="medium-12 small-12 large-6 columns">
			<h3>[+col1+]</h3>
			<p>[+col2+]</p>
			<a href="[+col4+]" class="button mb0">[+col3+]</a>
		</div>
		[+col5:isNot(''):then('<div class="columns shrink show-for-large"><a href="[+col4+]"><img src="[+col5+]" alt=""></a></div>')+]
	</div>
</div>
```
If i have an additional image in [+col5+] i need to display it
condition i've tried 
```
[+col5:isNot(''):then('<div class="columns shrink show-for-large"><a href="[+col4+]"><img src="[+col5+]" alt=""></a></div>')+]
```
doesn't work as expected
but it works with
```
[+col5:isNot(''):then('column 5 is not empty')+]
```
—HTML is totally stripped from output
also tried <@IF><@ENDIF> with same result

**Comment by yama** [comment]
Is the latest develop branch?

**Comment by sashabeep** [comment]
@yama 1.3.6 current from Updater plugin

**Comment by yama** [comment]
Is this fixed?

**Comment by yama** [comment]
ok?

**Comment by sashabeep** [comment]
NOPE
Call:

```
[[ddgetmultiplefield?
&inputString_docField=`photos`
&rowTpl=`rowTpl`
]]
```

rowTpl:
```[+col1:isNot(''):then('<div class="banner"><a href="[+col1+]"><img src="[+col0+]" alt=""></a></div>')+]

<@IF:[+col1:isNot('')+]>
	COL1 is not empty!
<@ENDIF>
	
<@IF:[+col1:isntEmpty+]>
	COL1 is not empty! using isntEmpty
<@ENDIF>
```

no one of this conditions works in 1.4 RC1 in ddgetmultiplefield item chunk.
Of course, if i use just [+col0+] and [+col1+] without conditions column showed as needed.
OR [[if? &is=`[+col1+]:not:` &then=`COL1 is not empty! using IF`]] - works as expected

**Comment by sashabeep** [comment]
Possible not the core issue, maybe, ddgetmultiplefield uses their own parser for placeholder-like syntax

**Comment by Dmi3yy** [comment]
not in core now can discus here  https://code.divandesign.ru/modx/ddgetmultiplefield
