### ISSUE TITLE
Request: Admin option for trailing slash to all (friendly URLs)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#237]
We already have the option `End Container URL with Slash` and I would like to go one more further, to get a new option `End all Document URL with Slash`. 

From https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

> Choose one URL as the preferred version. If your site has a directory structure, it’s more conventional to use a trailing slash with your directory URLs (e.g., example.com/directory/ rather than example.com/directory),

Good info on https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url 

#enhancement

**Comment by Pathologic** [comment]
Try to set url suffics as "/".

**Comment by q2apro** [comment]
I am using a snippet to return the URL for the canonical HTML tag. 

    return $modx->makeUrl($docid, '', '', 'full'); 

So I should just change this to: 

    return $modx->makeUrl($docid, '', '', 'full').'/'; 

Is that really a prefered solution? Thanks.

**Comment by Pathologic** [comment]
makeUrl respects system settings, so there's no need to add slash manually.

**Comment by q2apro** [comment]
As stated, there is no system setting in the configuration where you can enable ending slashes.

**Comment by bossloper** [comment]
@q2apro - try here:
![untitled](https://user-images.githubusercontent.com/1744687/30693761-e93e97f4-9ec8-11e7-85d7-40cd932aa1e6.png)

**Comment by q2apro** [comment]
That's a great idea! Thanks, it should work.
