### ISSUE TITLE
Can't modify templates content

### ISSUE THREAD

**Issue by jczeledonp** [evolution-cms/evolution#238]
After upgrading to 1.3.6. changes not saved after saving templates

**Comment by 64j** [comment]
@jczeledonp 
Try to reinstall and save the configuration

**Comment by jczeledonp** [comment]
Hi 64j,
Thanks for helping.. i reinstalled and now I receive a 'Something went wrong' alert message anytime i try to open a template.  At least I can change/modify templates but the alert is annoying

**Comment by dmi3yy** [comment]
one more time replace files and clear cache and all will ok
