### ISSUE TITLE
KCFinder Image size

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#239]
I thought it had been mentioned before but I cannot find it.
If I try to upload an image to KCFinder greater than approx. 1MB it fails and just gives an 'Attention' dialog box.
I don't get that issue on an old MODX install using KCFinder 2.5.1
Anyone else getting this issue?

![untitled](https://user-images.githubusercontent.com/1744687/30587175-26bd1bc8-9d2a-11e7-8b11-7cc3bf25da59.png)

(Evo 1.3.6 dev / php 5.6.31 with MariaDB 10.1)

**Comment by dmi3yy** [comment]
maybe limit in php ? max file size?  or max post size

http://take.ms/RV3uO

**Comment by bossloper** [comment]
Strange, it is now working!
