### ISSUE TITLE
the "edit resource" drop down screen at top of site

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#242]
Hi

just went from modx evo-1.2.1 to evolution-1.3.6 and all is well! i can't find where i can disable that "edit resource" 1cm tall floating bar dropping down from the top of the browser. can we disable that? i always had it disabled in modx so would definitely like to disable it now. i looked in all the evolution control panel settings screens but i can't see it. any help would be appreciated.

**Comment by user83743** [comment]
also, i then used WHM to make it use php7 and it produced a ream of errors in the error_log like:

[20-Sep-2017 15:17:21 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /home/ggmservices/public_html/domain.com/manager/includes/extenders/dbapi.mysqli.class.inc.php:30
Stack trace:
#0 /home/ggmservices/public_html/domain.com/manager/includes/document.parser.class.inc.php(2081): DBAPI->connect()
#1 /home/ggmservices/public_html/domain.com/index.php(128): DocumentParser->executeParser()
#2 {main}
  thrown in /home/ggmservices/public_html/domain.com/manager/includes/extenders/dbapi.mysqli.class.inc.php on line 30


i thought it was going to be php7 compatible?

**Comment by Nicola1971** [comment]
> i can't find where i can disable that "edit resource" 1cm tall floating bar dropping down from the top of the browser. can we disable that? 

you mean this toolbar?
![quickmanager](https://user-images.githubusercontent.com/7342798/30689338-f898079c-9ec0-11e7-8725-1392cae34150.png)

disable the QuickManager plugin

**Comment by user83743** [comment]
thanks Nicola. sorry for being thick :) . i had it disabled before but the new 1.3.6 brought in a new quickmanager and that installed itself beside the old one. so now i have 2 quickmanager plugins in there and both are disabled. thanks a million. have you upgraded any evolution-1.3.6 sites to php7?

**Comment by Nicola1971** [comment]
> have you upgraded any evolution-1.3.6 sites to php7?

no live sites with 1.3.6 and PHP7 yet (only 5.5x 5.6x), but i'm using locally with 7.1.2 on uWamp without issues

**Comment by user83743** [comment]
thanks. chances are your uWAMP has updated mysqli files and the 1.3.6 does not?

**Comment by fourroses666** [comment]
Could be your configfile has mysql in it instead of mysqli. When you update from "really old" versions. It should be there 2x if I'm right, just add the i.

**Comment by user83743** [comment]
which config file? :) there's load of 'em :) . i just upgraded from modx-1.2.1 to evolution-1.3.6 and php7 has been supported in modx for a number of versions.

**Comment by fourroses666** [comment]
/manager/includes/config.inc.php

**Comment by user83743** [comment]
thanks four** but there is only one mention of 'mysql' on that page and it's already:

$database_type     = 'mysqli';

**Comment by fourroses666** [comment]
Poah, then I don't know. Maybe a server setting but I'm not really into this.

**Comment by bossloper** [comment]
@user83743 - I don't think your php7 server setup has the mysqli library installed.

**Comment by user83743** [comment]
we'll check that. thanks

**Comment by fourroses666** [comment]
https://stackoverflow.com/a/666824/1537613

**Comment by user83743** [comment]
if (function_exists('mysqli_connect')) {
  //mysqli is installed
  echo "we have mysqli";
}

and that comes back with "we have mysqli"

**Comment by user83743** [comment]
thnaks four**.

mysqli is installed so i added:

$database_type     = 'mysqli';

to [root]/user.ini

AS PER:

http://php.net/manual/en/mysqli.installation.php

but that didn't work.

**Comment by user83743** [comment]
it suggest here: https://stackoverflow.com/questions/666811/fatal-error-class-mysqli-not-found

if (!function_exists('mysqli_init') && !extension_loaded('mysqli')) {
    echo 'We don\'t have mysqli!!!';
} else {
    echo 'Phew we have it!';
}

and this returns a positive for the presence of mysqli too

**Comment by bossloper** [comment]
... and you are definitely running that script on the same php7 setup you used for Evo? Each php version will have its own separate set of installed extensions.

**Comment by user83743** [comment]
Hi Boss. what does that mean? how would i get 'into' the php7 setup? when you go to linux terminal and do php, what version are you in there and how do you get to other versions? and in the above scripts, how would we make them use php7 versus 5.6 in a script?

**Comment by bossloper** [comment]
You said you used WHM to select php7. If that was using the 'MultiPHP Manager' then you are probably setting the php version on a domain by domain basis. So Just wanted to check you ran that test script on the same domain as the Evo install. e.g. you created a test.php file in the root of your Evo installation and ran it there.

You could add another line to the test script :-)

echo 'Current PHP version: ' . phpversion();

**Comment by user83743** [comment]
thanks for the explanation Boss**. yes, we ran the above code in the same domain as above.  i'm working with the server support with the last comment on https://stackoverflow.com/questions/666811/fatal-error-class-mysqli-not-found/666824#666824 so if we find the issue i'll report back.

**Comment by user83743** [comment]
thanks for all your help. mysqlnd was not loaded for php7.  the above scripts did run in the domain in question and returned 'mysqli is loaded' but mysqlnd was not loaded for php7 - so the linux sysadmin told me. so it was loaded now and is now loaded in WHM for all sites that choose php7. each php version in whm can have different modules loaded and the very basic mysqlnd was not loaded for php7 as we had no sites running on php7 on that server yet, so no one checked in there. i presumed we could check in a script if mysqli was loaded, but somehow no. thanks for all your help. i didn't know where that issue was going to end up or how long it was going to take:). the site is fine, all pages loading perfectly.

**Comment by bossloper** [comment]
Glad you got it sorted!
Don’t forget to close the issue if everything is resolved.
