### ISSUE TITLE
no captcha image on the evolution-cms 1.3.6 login screen

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#245]
Hi

we upgraded from modx-1.2.1 to evolution-1.2.6 and that was fine. we moved to php7 and we have that going now. but the /manager login screen has no captcha image now - any ideas? we had to add the iconv module to php7 in WHm to get anything to appear on domain.com/manager and now we have a login screen but no captcha image.  thanks  in advance for any help you can give.

**Comment by Nicola1971** [comment]
> anyone know where in the evolution database i can disable the captcha image displaying in /manager login screen? 

table evo_system_settings > use_captcha

**Comment by user83743** [comment]
thanks Nicola!

**Comment by bossloper** [comment]
@user83743 - following on from your previous php7 troubles there is a chance this issue is also php7 setup related. Check you have the GD library installed for php7 as I think it might be needed for CAPTCHA to work.

**Comment by user83743** [comment]
thnaks Nicola. that was it. no on whm for php7 we have the following modules:

libc-client
pear
php-bcmath
php-calendar
php-cli
php-common
php-curl
php-devel
php-exif
php-fpm
php-ftp
php-gd
php-gettext
php-iconv
php-imap
php-ioncube6
php-litespeed
php-mbstring
php-mcrypt
php-mysqlnd
php-opcache
php-pdo
php-posix
php-sockets
php-xml
php-zip
runtime

and the /manager captcha is working and the eform captcha.  

thanks Nicola - we won't have these issues for each site we change to php7 as they will all use the same php7 setup.
