### ISSUE TITLE
No option to hide errors frontend in production mode?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#246]
I have googled and found only one hint: 

> It happens because the PHP error_reporting level and the display_errors settings are set to hide PHP errors. ... Go to System (Gear Icon) -> System Settings in the MODX Manager, put debug in the search box at the upper right, and press enter.

Source: https://bobsguides.com/blog.html/2015/11/16/the-modx-white-screen-of-death/

Still I cannot find the option to disable the display of error messages frontend. I searched for "error", "report", "debug", "display" etc. on the admin configuration sites. 

Can somebody help?

**Comment by Deesen** [comment]
Your "hint" is about MODX Revolution, not Evo. 

You can try creating the file `/vendor/autoload.php` and add this content:

```
<?php
display_errors(0);
?>
```

**Comment by q2apro** [comment]
So there is no admin option to just enable/disable this?

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/9b2935db3f34daf70534c40a4e7dddefc154de26#diff-b91fad0266a33c1d4d87dff876939692
this?

**Comment by bossloper** [comment]
can close?

**Comment by q2apro** [comment]
Can close in case an admin option is added, no? Or most users say not needed. I'd suggest the option to opt-out for security reasons.

**Comment by dmi3yy** [comment]
In EVO work the same like in REVO 

You can creating the file `/vendor/autoload.php` and add this content:

```
<?php
display_errors(0);
ini_set('display_errors', 'Off');
?>
```
