### ISSUE TITLE
Missing explanation in the docs how to use $modx->sanitize()

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#247]
I got a visit of a Russian hack bot this morning. As a consequence I want to use no custom stuff but the built-in methods to secure the incoming $_POST and also the queries I do. It is hard to find any information about this. 

From the docs: http://www.evolution-docs.com/documentation/developers-guide/api-reference/dbapi/dbapi-escape

     $modx->db->escape($input);

when - as I understand - using this in a mysqli query. 

However, regarding `$modx->sanitize()` I could not find anything. When to use and some examples.

**Comment by yama** [comment]
maybe $modx->strip_tags()

**Comment by q2apro** [comment]
No, strip_tags() does not help. The bot used: 

     /mysite?id=\"><script%20>alert(String.fromCharCode(88,83,83))</script>

which went through and led to a mysqli error. 

With `$modx->db->escape($input);` this can be prevented. However, I am still wondering in what cases to use `$modx->sanitize()`.

**Comment by yama** [comment]
If sql sanitizing, it is $modx->db->escape().

**Comment by yama** [comment]
```
$where = sprintf("pagetitle='%s'", $modx->db->escape($_POST['input']) );
$rs = $modx->db->select('*','modx_site_content',$where);
```

**Comment by q2apro** [comment]
At https://forums.modx.com/thread/?thread=20171 they say you should sanitize all posts like this: 

    $sanitizedPosts = $modx->sanitize($_POST);

But when using $modx->sanitize() like this: 

   $array = ['hello', 1,2,3,4,5];
   $array = $modx->sanitize($array);
   var_dump($array);

I get `NULL`. So how to use it right then?

**Comment by dmi3yy** [comment]
$modx->sanitize not exist 
use function: modx_sanitize_gpc()
