### ISSUE TITLE
weblink redirects appends to URL rather than replaces it

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#248]
I'm currently running 1.3.6 on PHP 7.0.22 Apache 2.4.
I've created 2 containers which contains some weblinks which redirect to other pages in my installation.

When I click on preview to check that the redirect works the URL is being appended instead of replaced.

For instance.
> Test
 > test2
  > Page1 redirects to

 > products
  > best

So the first url is test/test2/page1 which should end up being products/best what I end up with is test/test2/page1/products/best.

This is with Friendly URLs on.  If I turn FURLs off then the index.php reflects the correct page number and end result as expected.

I've searched and looked at the options to see if I'm missing something but for the life of me I cannot find anything.

An equally frustrating situation is I have a site which has the 2 containers and a weblink resource and that works fine (for absolutely no reason).

I'm not sure whether this has been introduced in 1.3.6 as I have no older installations to test it with.

Chris

**Comment by BBloke** [comment]
I think I'm actually chasing demons.  I'm closing this as I think it's only relating to my installation.  I have created a snippet to redirect and on some pages the same problem persists.  I'm thinking host caching!

**Comment by BBloke** [comment]
After replicating the issue on another site I think this is best investigated.

I tried a modx weblink document as well as creating a simple snippet to sendRedirect. The end result is the same.  URL appending creating a 404 rather than creating and redirecting to the same page.

**Comment by dmi3yy** [comment]
How to reproduce ?
