### ISSUE TITLE
no image thumbnails for Template Variables attached to regular website resource pages

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#255]
Hi

we have a demo site on evolution-1.3.6 on php7 and all is well. we have been all over the site and control panel and no issues or error_log entries. I did notice that Template Variables for images are not displaying thumbnails when you go to a resource page ( a web page) in the evolution cms using the  document tree.

this upgrade was on modx 1.2.1 and there were thumbnails for all those images and now the thumbnails are gone. the images still display in the live web pages but it is very useful to be able to see thumbnail images in the cms too. any ideas?  is this a new setting which i need to enable in the cms? or a "thumbnail" php module i need to add? we have the same php7 php modules as we had for php5.6 and that fixed a captcha image issue were were having.

any help would be much appreciated.

Gerard

**Comment by Nicola1971** [comment]
maybe the ManagerManager plugin is disabled after update

**Comment by user83743** [comment]
100% - thanks Nicola. sorry for the simple issues, but these are the ones I am coming across.
