### ISSUE TITLE
Admin: History could not be written. Error: QuotaExceededError

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#257]
After working a while, I ran into this error when editing documents in the admin panel: 

> History could not be written. Error: QuotaExceededError: Failed to set the 'history_634ffb59092e7229ad12f97b1497b6d5' property on 'Storage': Setting the value of 'history_634ffb59092e7229ad12f97b1497b6d5' exceeded the quota.

I found this http://modx.im/blog/dmi3yy/5265.html and went to Chrome >Developer Tools >Application, then right mouse click on the website >Clear. 

This seemed to fix it. 

Just letting this fall into the issue tracker, because I am sure others will run into the same problem.

Chrome Version 61.0.3163.100

EVO Version 1.3.6

**Comment by dmi3yy** [comment]
It browser limit in local storage size

Отправлено с iPhone
