### ISSUE TITLE
Styling the webAlertAndQuit page

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#26]
After the webAlertAndQuit event is called, a white page with text is loaded. Looks shameful and long time it seems to connect the styles from the file manager / includes / header.inc.php

После вызова события webAlertAndQuit загружается белая страница с текстом. Смотрится позорно и давно напрашивается подключение стилей из файла manager/includes/header.inc.php

**Comment by bossloper** [comment]
@dmi3yy  fixed now?
