### ISSUE TITLE
How to sort tree by doc alias in Evolution CMS?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#260]
I got used to display the site tree with aliases of the documents. Now the goal is to sort all alphabetically, which seems not possible. 

![image](https://user-images.githubusercontent.com/6764548/30846074-bcaf05b4-a29e-11e7-83f6-b0f40f6f073b.png)

What hack or option do I need to get the alphabetic sort? 

Thanks a lot.

**Comment by Deesen** [comment]
Add after line 372 in file /manager/frames/1.php

    <option value="alias" <?= $_SESSION['tree_alias'] == 'alias' ? "selected='selected'" : "" ?>>Alias</option>

**Comment by q2apro** [comment]
Beautiful, beautiful! Please add this to the core :)
