### ISSUE TITLE
Enhancement - 'Developer Upgrade'

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#261]
It would be great like we now have a system upgrade notice to the latest production release there was also a more hidden link (maybe in the system info page next to the version number?) to upgrade to latest development release... With the usual warning that this is "for developers only, and not to be used in production".

**Comment by pmfx** [comment]
Yea., I would add it inside user dropdown to. Like this:

![obraz](https://user-images.githubusercontent.com/10888055/30848864-c1da7404-a2a0-11e7-87f3-94bf72b45fab.png)

**Comment by bossloper** [comment]
Maybe also only available to admin (1).

**Comment by bossloper** [comment]
Or maybe just as another plugin like Updater. then it can be disabled/removed on a live site.

**Comment by Nicola1971** [comment]
we can just add a new **Updater Plugin** settings to choose who to show the widget (not just the button)

In my **EvoAutoBackup** plugin i've used this options:

- All
- AdminOnly // run backup only for Admin role 1
- AdminExcluded // run backup for all manager users excluded Admin role 1 (not needed for updater widget)
- ThisRoleOnly // run backup only for "this" role id
- ThisUserOnly // run backup only for "this" username

Admin Only
![admin](https://user-images.githubusercontent.com/7342798/30860148-68260402-a2c6-11e7-951d-f48b529f83ce.png)

ThisRoleOnly (set the role number)
![role](https://user-images.githubusercontent.com/7342798/30860166-7f757548-a2c6-11e7-9b44-cf0f24218391.png)

ThisUserOnly (set the username)
![username](https://user-images.githubusercontent.com/7342798/30860485-896dd1de-a2c7-11e7-9ce3-e887416122d2.png)


I can add this option to the updater plugin if you like it

**Comment by bossloper** [comment]
Yes, that could work. Could the existing Updater plugin have 'branches/develop' added as a configuration 'type'? I think it would need a bit of extra coding to get the last commit date for develop branch and store it somewhere to compare against as the actual Evo version number is not altered at every develop commit.

**Comment by dmi3yy** [comment]
on develop branch havent releases 
we can publish prereleses or use file with version )

**Comment by bossloper** [comment]
For develop could just we use the last commit date from here: https://api.github.com/repos/evolution-cms/evolution/branches/develop

Then just for branches/develop store that date somewhere in Evo to check against for a new develop version? That way any commits would flag as a new version of develop without any manual publishing required.

**Comment by dmi3yy** [comment]
yes good idea

**Comment by Nicola1971** [comment]
added show widget settings to updater plugin 
![updater](https://user-images.githubusercontent.com/7342798/30869958-d533aeac-a2e2-11e7-9b86-12e4efd9acd7.png)

https://github.com/evolution-cms/evolution/commit/e1d4f5021f4bcff5c7f132b1d6803fd4c81b5f68

https://github.com/evolution-cms/evolution/commit/460a4cb6290008ad508954d9e7034201993358af

**Comment by bossloper** [comment]
I have started on adding develop as an option for the updater, but stopped at the point where storing/comparing the develop timestamp to somewhere stored on the installation. I have it to this point:
![untitled](https://user-images.githubusercontent.com/1744687/30872619-a1901054-a2e2-11e7-9cc5-8413f4f36bdc.png)
I can continue, but my coding might not be the best! Shall I continue or does someone more efficient want to take over?!? :-)

**Comment by Nicola1971** [comment]
@bossloper share the code so we can help you to finish. 😃

**Comment by bossloper** [comment]
For development the code currently comments out checks against current install version so button always displays and always installs:
https://github.com/evolution-cms/evolution/compare/develop...bossloper:patch-21
Probably best to add this as a new plugin for now rather than replacing the existing Updater.
Also added new type to plugin configuration of 'branches/develop'. 

Few points I had though about, and why I got stuck(!):

1) General (major!?) issue -  Does the existing updater run the install and fully install plugins? It does not seem to. i.e. rename a plugin and run the update and the missing plugin is not added back in. If this is the case then that is not so useful.

2) The develop install will need to store the datetime stamp for the develop install last commit so it can work out if to display the upgrade notice. Not sure where to store this.

3) How will it allow install back to latest release as version after develop will be greater than latest release after a dev install? Not sure it can as plugins/snippets would not be rolled back.

4) When a new release is newer than a dev install it should be able to install and remove the stored dev datetime stamp - point 2.

5) Add install folder cleanup?

Feel free to take from here! :-)

**Comment by Nicola1971** [comment]
Is not the solution, but can be usefull for someone: 
For my local dev Evo i use this widget to get info about new commits:

![download](https://user-images.githubusercontent.com/7342798/32271052-8e9da678-bef8-11e7-81ce-ad340ce0bab1.png)


```
/**
 * DashboardEvoDevRSS
 * RSS widget Recent Commits to evolution:develop
 * @author    Nicola Lambathakis
 * @category    plugin
 * @version    1 rc1
 * @license	   http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)
 * @internal    @events OnManagerWelcomeHome
 * @internal    @installset base
 * @internal    @modx_category Dashboard
 * @author      Nicola Lambathakis http://www.tattoocms.it/
 * @internal    @properties &wdgVisibility=Show widget for:;menu;All,AdminOnly,AdminExcluded,ThisRoleOnly,ThisUserOnly;All &ThisRole=Run only for this role:;string;;;(role id) &ThisUser=Run only for this user:;string;;;(username) &wdgTitle= Widget Title:;string;Commits to evolution develop  &wdgicon= widget icon:;string;fa-github  &wdgposition=widget position:;text;1 &wdgsizex=widget width:;list;12,6,4,3;12 &FeedUrl=Rss url:;string;http://feeds.feedburner.com/RecentCommitsToEvolutiondevelop &rssitemsnumber=Feed items number:;string;3 &WidgetID= Unique Widget ID:;string;RSSdev-widget
****
*/

/* Configuration
---------------------------------------------- */
// Here you can set the urls to retrieve the RSS from. Simply add a $urls line following the numbering progress in the square brakets.

$urls[0] = $FeedUrl;

// How many items per Feed?
$itemsNumber = $rssitemsnumber;

/* End of configuration
NO NEED TO EDIT BELOW THIS LINE
---------------------------------------------- */

// include MagPieRSS
require_once('media/rss/rss_fetch.inc');

$feedData = array();

// create Feed
foreach ($urls as $section=>$url) {
	$rssoutput = '';
    $rss = @fetch_rss($url);
    if( !$rss ){
    	$feedData[$section] = 'Failed to retrieve ' . $url;
    	continue;
	}
    $rssoutput .= '<ul>';

    $items = array_slice($rss->items, 0, $itemsNumber);
    foreach ($items as $item) {
        $href = $item['link'];
        $title = $item['title'];
        $pubdate = $item['pubdate'];
        $pubdate = $modx->toDateFormat(strtotime($pubdate));
        $description = strip_tags($item['description']);
        if (strlen($description) > 199) {
            $description = substr($description, 0, 200);
            $description .= '...<br />Read <a href="'.$href.'" target="_blank">more</a>.';
        }
        $rssoutput .= '<li><a href="'.$href.'" target="_blank">'.$title.'</a> - <b>'.$pubdate.'</b><br />'.$description.'</li>';
    }

    $rssoutput .= '</ul>';
	$feedData[$section] = $rssoutput;
}

// get manager role
$internalKey = $modx->getLoginUserID();
$sid = $modx->sid;
$role = $_SESSION['mgrRole'];
$user = $_SESSION['mgrShortname'];
// show widget only to Admin role 1
if(($role!=1) AND ($wdgVisibility == 'AdminOnly')) {}
// show widget to all manager users excluded Admin role 1
else if(($role==1) AND ($wdgVisibility == 'AdminExcluded')) {}
// show widget only to "this" role id
else if(($role!=$ThisRole) AND ($wdgVisibility == 'ThisRoleOnly')) {}
// show widget only to "this" username
else if(($user!=$ThisUser) AND ($wdgVisibility == 'ThisUserOnly')) {}
else {
// get language
global $modx,$_lang;
// get plugin id
$result = $modx->db->select('id', $this->getFullTableName("site_plugins"), "name='{$modx->event->activePlugin}' AND disabled=0");
$pluginid = $modx->db->getValue($result);
if($modx->hasPermission('edit_plugin')) {
$button_pl_config = '<a data-toggle="tooltip" href="javascript:;" title="' . $_lang["settings_config"] . '" class="text-muted pull-right" onclick="parent.modx.popup({url:\''. MODX_MANAGER_URL.'?a=102&id='.$pluginid.'&tab=1\',title1:\'' . $_lang["settings_config"] . '\',icon:\'fa-cog\',iframe:\'iframe\',selector2:\'#tabConfig\',position:\'center center\',width:\'80%\',height:\'80%\',wrap:\'evo-tab-page-home\',hide:0,hover:0,overlay:1,overlayclose:1})" ><i class="fa fa-cog" style="color:#fff;"></i> </a>';
}
$modx->setPlaceholder('button_pl_config', $button_pl_config);
//events
$EvoEvent = isset($EvoEvent) ? $EvoEvent : 'OnManagerWelcomeHome';
$output = "";
$e = &$modx->Event;

/*Widget Box */
if($e->name == ''.$EvoEvent.'') {
			$widgets['DevRSS'] = array(
				'menuindex' =>''.$wdgposition.'',
				'id' => 'DevRSS'.$pluginid.'',
				'cols' => 'col-md-'.$wdgsizex.'',
                'headAttr' => 'style="background-color:#24292E; color:#FFFFFF;"',
				'bodyAttr' => 'style="background-color:#FFFFFF; color:#24292E;"',
				'icon' => ''.$wdgicon.'',
				'title' => ''.$wdgTitle.' '.$button_pl_config.'',
				'body' => '<div class="card-body">'.$feedData[$section].'</div>',
				'hide' => '0'
			);	
            $e->output(serialize($widgets));
}
}

```

**Comment by bossloper** [comment]
@Nicola1971 - Having though further on the developer install I am thinking it might be best not to add the develop option to the existing updater as it is only really for developers and probably should not be in the core installation.

How about extending your dashboard widget? There could be an 'install to this commit link' next to each feed item. That would then pull https://github.com/evolution-cms/evolution/archive/{sha}.zip 
It could then use the same installation code from the updater plugin. There would be no need to check which version is installed (which I think is problematic anyway), but it would allow more flexibility by installing any of the last n commit versions.

**Comment by Nicola1971** [comment]
nice idea, an "install this Dev version/update" button that run the Updater function, 
But don't know much about the Updater install code/function, need to check and learn the code.
maybe @dmi3yy can help?

**Comment by bossloper** [comment]
FYI - I have a working upgraded version of the updater plugin. Basically I bolted on the logic of RSS reading from DashboardRSS with various modifications. It uses this feed: https://github.com/evolution-cms/evolution/commits/develop.atom
When updater is set to list commits it always displays on the dashboard. It does (for me at least) need the updated Snoopy as per: https://github.com/evolution-cms/evolution/pull/345 . Just a bit more testing to do.

![untitled](https://user-images.githubusercontent.com/1744687/32668862-a6d82ec6-c636-11e7-929e-adbb07723789.png)

**Comment by Nicola1971** [comment]
Looks nice to me.
Share, so we can test together .

I love system widgets: I'm working on a EvoBackup widget that alert when your latest db snapshot backup is older than X days 😄

**Comment by bossloper** [comment]
Will do. I just have a couple of tweaks to do.

**Comment by bossloper** [comment]
@Nicola1971 - https://github.com/evolution-cms/evolution/pull/352

**Comment by bossloper** [comment]
Closed via https://github.com/evolution-cms/evolution/commit/dbd114e30cad4748f834d03107746ce409520223
