### ISSUE TITLE
Outdated packages in Extras

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#263]
Not a technical issue.
Many packages in extras didn't updated even with patches.
Some packages is very old and forked just once, some just didn't work on the versions 1.3 and up

As i remember:
- MultiFiles
- SimpleFiles
- SimpleGallery
- SimpleTube
- Shopkeeper
- Global Placeholders (there is an type error in name in Extras - pla**S**eholders)

I think some users will add something to this list.
So Extras slowly becames unusefil.
Maybe another team is needed for maintaining Extras?

@dmi3yy is not the Shiva at last :)

**Comment by Pathologic** [comment]
I don't know about SimpleFiles but other Simple* have links to their master branches and work in 1.3. Though version numbers are not correct.

**Comment by bossloper** [comment]
DocLister and CodeMirror versions in Extras are also behind the core installation versions.

**Comment by dmi3yy** [comment]
MultiFiles not supported. Use MultiTV ) 
SF, SG, ST all work fine 
Shopkeeper https://github.com/evolution-cms/evolution/issues/256 - i will test and fix 
Global Placeholders - fixed name
