### ISSUE TITLE
With PHP 7.2 RC - Errror : count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#264]
With PHP 7.2 RC there is a new error: 

> Errror : count(): Parameter must be an array or an object that implements Countable

    if (count($idnames) == 0) {

Line: https://github.com/evolution-cms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L4680

Guess we need to check if not null or if isset.

**Comment by 64j** [comment]
replace
```php
if (empty($idnames)) {
```

**Comment by dmi3yy** [comment]
Plz test if all ok push this to code)

**Comment by q2apro** [comment]
`if (empty($idnames)) {` seems to fix it. 

I was searching in all files for `count(… == 0)` and discovered in those files: 

 - document.parser.class.inc.php with `if (count($ids) == 0){` and `… || count($idnames) == 0){` 
 - plugin.forgotmanagerlogin.php
 - modx.ddtools.class.php
 - ddselectdocuments.php
 - mm_renamefield.php
 - mm_requirefields.php
 - ditto.class.inc.php 
 - modxDebugConsole.class.php
 - tagging.extender.class.inc.php
 - onetable.php

Just search for `) == 0)` to find the lines.

I would say all are possible triggers to cause the PHP 7.2 warning message.

**Comment by dmi3yy** [comment]
Test files in core seem all ok. 

if get new bugs open new issues. 
but in old extras like eForm many work for correct work in 7.2
