### ISSUE TITLE
Page load speedup after disabled <@> tags

### ISSUE THREAD

**Issue by 64j** [evolution-cms/evolution#265]
After making [changes](https://github.com/evolution-cms/evolution/commit/3b99b143a6c5c6c82b90fc6e3b4105bcfb523ec0) @Deesen , the speed of page load increased significantly. I have also made minor changes to speed up the download.

**Tags <@> ON database / cache**
![image](https://user-images.githubusercontent.com/4653189/30932967-d256c21a-a3d1-11e7-9687-7244a23a806f.png)
![image](https://user-images.githubusercontent.com/4653189/30932977-db33c536-a3d1-11e7-8b31-298287debce4.png)

<hr>

**Tags <@> OFF database / cache**
![image](https://user-images.githubusercontent.com/4653189/30933037-0122cc56-a3d2-11e7-95ca-efea5345c1eb.png)
![image](https://user-images.githubusercontent.com/4653189/30933047-080b0196-a3d2-11e7-8225-e891a9ec0532.png)

**Comment by yama** [comment]
The Japanese package uses more <@> tags. However, it works much more lightly than evocms 1.3.6. I can understand your claim, but it probably is not a problem for itself.
Rather than simply disabling the function and making it "settled", you should examine the cause firmly.

**Comment by 64j** [comment]
You can learn all this yourself, because this is your development.
But after your edits the system began to work 10 times slower, maybe you are optimizing your scripts.
All data in the screenshots !

**Comment by yama** [comment]
You said so many times in chat, but that has not become root cause investigation.

**Comment by yama** [comment]
Because the problem can not be reproduced in this environment, your cooperation is necessary. First, please remove DocLister and etc.. . It is necessary to acquire benchmark data in a simple state.

**Comment by 64j** [comment]
@yama 
Why do not you figure it out yourself.
All the data I gave you in Slack

**Comment by yama** [comment]
I offered there, but you received "screenshot" only.
You have no answer to my question.

**Comment by yama** [comment]
After all, you only do about "to disable the function". Rather, let's think logically.
If it is true to become heavy, there is always a cause.

**Comment by 64j** [comment]
If after turning off the function everything works well, then the thing is that they have disabled

**Comment by yama** [comment]
You only say that.....

**Comment by yama** [comment]
ok. discussion is unnecessary this time. It's can disable.

**Comment by dmi3yy** [comment]
Its easy to test 

Try on off in settings @ in dev version 


Отправлено с iPhone

**Comment by dmi3yy** [comment]
And need test for site with 1000+ docs 

For small sites with 10 docs no metter 0,02 or 0,04 

Отправлено с iPhone
