### ISSUE TITLE
Enhancement -  Menu Colour Switcher

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#266]
An addition to the dark/light theme switcher 
video: https://youtu.be/X8JEP_eOll8

![menu-color-switch](https://user-images.githubusercontent.com/7342798/30933591-49327318-a3cb-11e7-93ee-e6e99e7ac2e2.png)
![menu-color-switch-more](https://user-images.githubusercontent.com/7342798/30933675-89f089b2-a3cb-11e7-9a69-d201a56c716c.png)

**Comment by dmi3yy** [comment]
Where saved ? better in db or cache file for work from diff user/pc 
cool )

**Comment by Nicola1971** [comment]
@dmi3yy 

Actually use localstorage. Where is saved dark/light toggle option?

I'm open to any suggestion, but in my experience:

- like the dark/light toggle, the menu picker work as a "**personal view option**"

- for "**all users**" and "**brand colours**" is better use [ManagerColors](https://github.com/Nicola1971/ManagerColors-Plugin) plugin (works together) , so:
 user can set his menu colour with the picker, but the default color is set by the admin with ManagerColors
 and when the user reset the picker, get the back the default color set with plugin:

https://youtu.be/-V-6x2ruNoA

is just my point of view
what do you think?

**Comment by bossloper** [comment]
@Nicola1971 - would QM+ be able to hook into this too? It is already out of date again visually with the manager.

**Comment by dmi3yy** [comment]
Localstorage its good but need set up all time on new devise 
and i cant set theme for my client :( 

its like order widgets in previous version )

**Comment by Nicola1971** [comment]
@bossloper 
QM was restyled for MODxRE2 theme and now needs a new restyle :D 

It could be possible, but need to check the QM html markup

**Comment by Nicola1971** [comment]
> Localstorage its good but need set up all time on new devise
and i cant set theme for my client :(
its like order widgets in previous version )

because you dont use my dummy plugins! :D :D 
1)  old widget could be ordered by EvoDashboard  
2)  the new manager theme color by ManagerColor
3)  new default dashboard widgets can be ordered and hidden with [Widget Manager plugin] (https://github.com/Nicola1971/Widget-Manager)

i always develop plugins for this little useful things :D

**Comment by dmi3yy** [comment]
Yes some time need check you repos :)))

**Comment by Nicola1971** [comment]
@bossloper 

> It is already out of date again visually with the manager.

check https://github.com/evolution-cms/evolution/issues/268
![qm159](https://user-images.githubusercontent.com/7342798/30981477-c500b3a6-a484-11e7-92e4-1b00f176d9f4.png)

**Comment by dmi3yy** [comment]
Nice QM+

**Comment by Nicola1971** [comment]
need two new language strings for "more" and "less" buttons

**Comment by Nicola1971** [comment]
or just "+" and "-"
![plus](https://user-images.githubusercontent.com/7342798/30992989-e3fa2d28-a4ac-11e7-8bbb-1133c686dbf3.png)
![minus](https://user-images.githubusercontent.com/7342798/30992990-e6ffc8c0-a4ac-11e7-8ba6-61ee9e130ce2.png)

**Comment by Nicola1971** [comment]
just found useful this picker for my dev workflow:

with new evo you can reload the page without lost anything, 
so when i'm working on a resource (document, snippet..) i can set the menu color as an "alert" for my work progress:

- **red**: dont close this page!
- **blue**: saved, but not completed
-  **green**: saved and completed.. you can cose 

useful when you come back from coffee break
😄

**Comment by 64j** [comment]
@Nicola1971 
Color switching is a fun thing, but not everyone needs it.
You can move the color selection from topmenu in the user menu

![- -2](https://user-images.githubusercontent.com/4653189/31013835-9d0aad38-a520-11e7-8c7e-744845d92a80.jpg)

Then at the first press we have a demonstration

![- -3](https://user-images.githubusercontent.com/4653189/31013860-bdf522c6-a520-11e7-9a4f-b9c5a4a619a1.jpg)


And then you can already change both the text color and the background color in the top menu, in the document tree and in the mainframe

![- -4](https://user-images.githubusercontent.com/4653189/31013924-05ff3c6e-a521-11e7-978f-8baceae2d665.jpg)


To finish editing, just click on the icon with the palette.

**Comment by Nicola1971** [comment]
@64j 
I was just thinking about add the same feature to the tree and main, your solution (with overlay) looks 
very cool, but maybe complicated if we need to add a lot of js.
do we have any tools we can use in your updated modx.js?
ie: the new modal/popup can help?

About the menu: i dont think a small icon takes space to something, but if we can improve in your way , we can move in a submenu (settings or user)

**Comment by Nicola1971** [comment]
Added in system settings (as disabled)
![picker_settings](https://user-images.githubusercontent.com/7342798/31077050-568fa778-a77d-11e7-872c-98b426c97074.png)

**Comment by Nicola1971** [comment]
@64j  Refactored the Color Switcher:
https://www.youtube.com/watch?v=tHtQRDl1dWA

- Removed from menu, now is a small button that open a Toggle-able Sidebar (if enabled in system settings)
![cw-button](https://user-images.githubusercontent.com/7342798/31661148-fd54f208-b339-11e7-8633-d05fd2d99267.png)

- Moved the code to theme folder so anyone can customize/improve for custom theme
- Styled for light and dark theme
![color-switcher-light](https://user-images.githubusercontent.com/7342798/31661156-04d33878-b33a-11e7-98b6-d0a7768bee10.png)
![color-switcher-dark](https://user-images.githubusercontent.com/7342798/31661159-087468a8-b33a-11e7-976a-2cb57530262a.png)
![cw-open](https://user-images.githubusercontent.com/7342798/31661201-1db05baa-b33a-11e7-9fd4-b863a4fd5836.png)
![cw-picker](https://user-images.githubusercontent.com/7342798/31661206-20dccfa2-b33a-11e7-82cc-35367ec22304.png)


I want improve functionallity in next future
