### ISSUE TITLE
Error when auto-updating: headers already sent by

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#267]
Just used the auto-updater from within the admin panel and got: 

    /temp/evolution-1.3.4/qpman
    Warning: Cannot modify header information - headers already sent by (output started at /update.php:114) in /update.php on line 120

That was the update to v1.3.4.

I am using a renamed manager folder, could this be the reason?

PS: Where is the `update.php` in this repo?

**Comment by dmi3yy** [comment]
update php auto generate in this code: 
start from this point 
https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/updater/plugin.updater.php#L146

i havent server where can reproduce this bug :( 

if you can send me access i try fix it

**Comment by dmi3yy** [comment]
maybe fixed plz test on 1.4.0b if the same then reopen

**Comment by q2apro** [comment]
Clicked the Update button, got the same error: 

`/temp/evolution-1.4.0.RC/manager
Warning: Cannot modify header information - headers already sent by (output started at /update.php:114) in /update.php on line 120`

However, I forgot to apply the fix. If it appears again with the upcoming update, I will post it here.

**Comment by q2apro** [comment]
Tried it with 1.4.0 RC2. Works now. Thanks!
