### ISSUE TITLE
[Enhancement] QuickManager Restyle for new default theme

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#268]
As mentioned by @bossloper here: https://github.com/evolution-cms/evolution/issues/266#issuecomment-332779940

QuickManager still use modxre2 styles and need a restyle to fit evo 1.3 default theme

working on 

![qm159](https://user-images.githubusercontent.com/7342798/30981341-57bf6396-a484-11e7-8bd1-a47786f9e898.png)

**Comment by 64j** [comment]
you can make it an iframe, or page in iframe
```php
<html>
<body>

    echo $QM;

<iframe>

    echo $page;

</iframe>

</body>
</html>
```
and then there will be no conflicts in the scripts.

But because of this, will have to rewrite the entire plugin :)))

**Comment by Nicola1971** [comment]
> ..But because of this, will have to rewrite the entire plugin :)))

@64j nice idea, maybe in the future  :smile:

**Comment by Nicola1971** [comment]
the close animation is still a bit ugly,, better than previous version but still ugly 😄
