### ISSUE TITLE
Главное горизонтальное меню перестало работать

### ISSUE THREAD

**Issue by ultraviolet** [evolution-cms/evolution#271]
При наведении мыши на какой-либо пункт главного меню стало появляться модальное окно "Подтвердите действие" с содержимым "Что-то пошло не так.". Соответственно, главным меню стало невозможно пользоваться.

Чистка кеша/куки не решает проблему. Также, как и полное восстановление сайта из резервной копии (файлы + база данных) - сделанной пару дней назад, когда проблема не наблюдалась.

Что можно попытаться сделать ещё, чтобы восстановить работоспособность?

**Comment by 64j** [comment]
посмотрите в консоли, скорее всего ошибку даёт какой то кастомный плагин, а сообщение это будет выводиться, если есть ошибки. Просто так оно не выводится.
Либо вы профилируете свои скрипты и ставите точки остановки, что тоже может вызвать ошибку.

Если обновиться до последней версии 1.4, ошибки уже не будет

**Comment by ultraviolet** [comment]
Спасибо, попробовал, что смог.

> посмотрите в консоли

В консоли Javascript браузера? Если да, то вот такое выскакивает после каждого взаимодействия с упомянутым модальным окном ("ОК" или "отмена"):
`
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover
    at Function.ga.error (VM440 jquery.min.js:2)
    at PSEUDO (VM440 jquery.min.js:2)
    at ya (VM440 jquery.min.js:2)
    at ga.compile (VM440 jquery.min.js:2)
    at eval (VM440 jquery.min.js:2)
    at PSEUDO (VM440 jquery.min.js:2)
    at ya (VM440 jquery.min.js:2)
    at ga.compile (VM440 jquery.min.js:2)
    at ga.select (VM440 jquery.min.js:2)
    at Function.ga [as find] (VM440 jquery.min.js:2)
`

> скорее всего ошибку даёт какой то кастомный плагин

Отключил все плагины (кроме TransAlias - его не получилось), ничего не поменялось. 

> Либо вы профилируете свои скрипты и ставите точки остановки, что тоже может вызвать ошибку

Тут даже не знаю, куда копать. По-моему, использую только стандартные решения "из коробки" (и/или из Extras). Один самописный сниппет есть, да на этом и всё, вроде.

> Если обновиться до последней версии 1.4, ошибки уже не будет

К сожалению, обновление не получается сделать. Скачиваю дистрибутив, распаковываю через файл-менеджер С-панели поверх старой установки (как и всегда обновляюсь). И после этого открывается только путь /install , сам сайт и путь к manager отдают 500 ошибку (не могу в логах сервера найти, о чём это).

**Comment by 64j** [comment]
у вас случайно плагин гугл аналитики и яндекс аналитики в админке не установлен?
(вы можете присоединиться к чату в телеграмм, на modx.im чат слева)

**Comment by ultraviolet** [comment]
Эти плагины не ставил. 
Пока избавился от 500 ошибки (вот [точно такой же случай](https://github.com/modxcms/evolution/issues/617)), обновился повысив версию PHP с 5.4 на 5.5. После обновления меню не выдаёт ошибок, но не реагирует вообще. Также пропали документы в дереве документов (чистка кэша не помогает).
PS: Телегу не очень воспринимаю, неудобно с телефона

**Comment by dmi3yy** [comment]
Телега есть и под десктоп и под веб :) 

на текущий момент самый приятный мессенжер ))

**Comment by ultraviolet** [comment]
> Телега есть и под десктоп

Ну) Надо будет как-нибудь испытать.

**Comment by ultraviolet** [comment]
После обновления в консоли браузера вроде те же ошибки остались (появляется эта партия ошибок по клику на любом элементе меню):
`
modx.js?v=1.4.0.b:52 
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover
    at Function.ga.error (/manager/media/script/jquery/jquery.min.js:2)
    at PSEUDO (/manager/media/script/jquery/jquery.min.js:2)
    at ya (/manager/media/script/jquery/jquery.min.js:2)
    at ga.compile (/manager/media/script/jquery/jquery.min.js:2)
    at eval (/manager/media/script/jquery/jquery.min.js:2)
    at PSEUDO (/manager/media/script/jquery/jquery.min.js:2)
    at ya (/manager/media/script/jquery/jquery.min.js:2)
    at ga.compile (/manager/media/script/jquery/jquery.min.js:2)
    at ga.select (/manager/media/script/jquery/jquery.min.js:2)
    at Function.ga [as find] (/manager/media/script/jquery/jquery.min.js:2)
`

**Comment by 64j** [comment]
а как вы обновили систему?
такое ощущение, что у вас старый /manager/media/script/jquery/jquery.min.js

**Comment by ultraviolet** [comment]
> а как вы обновили систему?

Как всегда - в файл-менеджере С-панели распаковал дистрибутив новой версии поверх файлов сайта. Потом установка и удаление папки install. Сейчас сравнил файлы jquery.min.js 1.3.6 и 1.4.0 -- контрольная сумма одинаковая показывается (то есть, вроде этот файл и не менялся?).

**Comment by 64j** [comment]
загрузил файлик в корень сайта и следовал инструкциям
https://github.com/evolution-cms/installer

**Comment by ultraviolet** [comment]
Спасибо, попробовал. Восстановил копию сайта, установился с этого файлика. Результат - опять модальное окно "Что-то пошло не так." при клике на пунктах меню.

**Comment by 64j** [comment]
больше угадать не могу(

**Comment by dmi3yy** [comment]
Скиньте доступ но лучше в личку глянем 

Отправлено с iPhone

**Comment by ultraviolet** [comment]
Только зашёл в админку, проблема исчезла. Ребята, это кто-то из вас исправил?

**Comment by 64j** [comment]
neutron ?

**Comment by ultraviolet** [comment]
> neutron ?

Да

**Comment by 64j** [comment]
зайти напрямую не получилось, но по базе данных прошёлся, показалась такая побитая админка.
ревизию не плохо бы было сделать.
Напишите в телеграме, просто в чате проявитесь. Здесь как таковой лички нет.

**Comment by ultraviolet** [comment]
Всем спасибо, и особенно @64j , который, собственно и решил проблему.

**Comment by ultraviolet** [comment]
Опять столкнулся с проблемой, описанной в первом посте. Оказалось, что здесь это 100% всегда происходит, когда в панели управления Cloudflare включён модуль Rocket loader, и только в Хроме (в ИЕ 11, например, проблема не наблюдается). 
Причём, перевод этого Rocket loader в ручной режим не помогает, надо полностью отключать. На прежних версиях Evo такого не наблюдалось (Cloudflare тут вроде всегда работал с этим Rocket loader на борту).

Вообщем, похоже, что какая-то несовместимость Хрома и Cloudflare при определённых условиях (кое-что об этом и похожем прочитал [тут](https://stackoverflow.com/questions/39610829/a-parser-blocking-cross-origin-script-is-invoked-via-document-write-how-to-ci), [тут](https://bugs.chromium.org/p/chromium/issues/detail?id=640844) и [тут](https://support.cloudflare.com/hc/en-us/articles/115004370247-Why-do-I-see-A-Parser-blocking-cross-origin-script-is-invoked-via-document-write-in-my-browser-console-)).

**Comment by 64j** [comment]
всё оптимизируете и разгоняете всё тот же сайт?

**Comment by 64j** [comment]
@ultraviolet 
обновитесь до версии 1.4 (develop)

**Comment by ultraviolet** [comment]
На версии 1.4.0.b тут это наблюдается. Ну всё равно, проблема получается не относится к Evo, инфы добавил на тот случай, если кто-то ещё будет жаловаться на подобное (может пригодится).

> всё оптимизируете и разгоняете всё тот же сайт?

Уже не особо) Был он добавлен давно ещё в Cloudflare
