### ISSUE TITLE
Unable to save in Elements > Manage Categories

### ISSUE THREAD

**Issue by Aharito** [evolution-cms/evolution#276]
An **Error** occured when sorting elements (etc. snippets) with **Categories Manager**

Evo 1.3.6, OpenServer, PHP 5.6, MySQL 5.5

![image](https://user-images.githubusercontent.com/6253807/31139624-54757f9c-a89c-11e7-89a7-30831087184d.png)

**Comment by dmi3yy** [comment]
fixed in 1.4.0b
