### ISSUE TITLE
Install fails. "Fatal error"

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#277]
Trying to install the the latest dev branch, but during last step, I am presented with an un-styled white screen that shows that it went ok, but no buttons to go any further.
When I try to view the front-end or manager I am presented with this error:

> Fatal error: Can't use function return value in write context in D:\xampp-portable\htdocs\xx\manager\includes\document.parser.class.inc.php on line 1681

(xampp with php5.4.7)

![localhost xx install index php action install](https://user-images.githubusercontent.com/6113504/31170408-d786e572-a8f3-11e7-8577-0df273fb23b9.png)

**Comment by Nicola1971** [comment]
i just had a similiar issue after an upgrade to latest 1.4 dev:

- same white un-styled page
- with a refresh i can see an error (cant write config file.)
- error 500 on frontend and /manager

Replaced **document.parser.class.inc.php** with the one from **1.3.6** > **Issue solved**.

@yama can you check?

**Comment by yama** [comment]
ok. I'll fix it later.

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/archive/ab5e39d4f592175f87838433ec0ac4e3b993b02a.zip
I tried most recently package. In my dev environment, I could install without problems.
Are there other hints? or, already fixed?

**Comment by dmi3yy** [comment]
Its bug with windows i think

**Comment by yama** [comment]
http://www.wampserver.com/
I tested windows wampserver

**Comment by Nicola1971** [comment]
i had this issue with a live linux server . 
no issue in my local windows10  wamp/Uwamp servers

**Comment by yama** [comment]
hmm...?
https://github.com/evolution-cms/evolution/blob/c9076bebbc98c68a2e869167175a0b171b195965/manager/includes/document.parser.class.inc.php#L1680-L1684
Line 1681 is here.

**Comment by yama** [comment]
@risingisland @Nicola1971
In my development environment (Windows 10 / PHP 7.1), this problem can not be reproduced. Do you have other information?

**Comment by yama** [comment]
https://www.google.com/search?q=Can't+use+function+return+value+in+write+context
Maybe, problem before PHP 5.4

**Comment by risingisland** [comment]
My localhost version is 5.4.7

**Comment by yama** [comment]
> My localhost version is 5.4.7

Thanks for your information.

**Comment by Nicola1971** [comment]
just tested with UwAmp, switching to php 5.4.45:

> Fatal error: Can't use function return value in write context in D:\UwAmp\www\evodev\manager\includes\document.parser.class.inc.php on line 1681

**Comment by Deesen** [comment]
When changing line 1681 from

    $cmd = empty(trim($cmd)) ? 0 : 1;

to

    $cmd = trim($cmd);
    $cmd = empty($cmd) ? 0 : 1;

does it work?

**Comment by Nicola1971** [comment]
@Deesen  yes :)

**Comment by Nicola1971** [comment]
note: with all 5.4 /5.5 tests on my local UwAmp i got this error on dashboard:

> Warning: strftime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in D:\UwAmp\www\evodev\manager\includes\document.parser.class.inc.php on line 4370

**Comment by Deesen** [comment]
You can set default timezone via .htaccess

    php_value date.timezone 'Europe/Berlin'

or if not allowed by hoster, create file `/vendor/autoload.php` with

    <?php
      date_default_timezone_set('Europe/Berlin');
    ?>

**Comment by Nicola1971** [comment]
@Deesen thanks, fixed with htacces - was just a bad configuration of my UwAmp (a portable local server)

**Comment by Nicola1971** [comment]
@yama or @Deesen can you apply the fix to the document.parser? so we can close the issue.

**Comment by yama** [comment]
@Nicola1971 
https://github.com/yama/evolution/commit/16d6bc4075328fe601227b6ef33c059bf2d3896b
Thanks, already fixed.

**Comment by yama** [comment]
@Deesen ok, thanks.
