### ISSUE TITLE
Minor installer issue showing ÂÂ

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#278]
I see ÂÂ after Select a language (dutch).

![select-a-language](https://user-images.githubusercontent.com/523389/31220128-baf258ca-a9bf-11e7-8eb2-8cd47dade31e.jpg)

**Comment by fourroses666** [comment]
And on the installer: 

`Install /Update DocInfo - 1 Ð‘ÐµÑ€ÐµÐ¼ Ð»ÑŽÐ±Ð¾Ðµ Ð¿Ð¾Ð»Ðµ Ð¸Ð· Ð»ÑŽÐ±Ð¾Ð³Ð¾ Ð´Ð¾ÐºÑƒÐ¼ÐµÐ½Ñ‚Ð° (Ð¼ÐµÐ½ÑŒÑˆÐµ Ð·Ð°Ð¿Ñ€Ð¾ÑÐ¾Ð² Ð¿Ð¾ ÑÑ€Ð°Ð²Ð½ÐµÐ½Ð¸ÑŽ Ñ GetField)`

**Comment by Nicola1971** [comment]
> And on the installer...

in latest dev?
![fireshot capture 224 - evo installazione - http___localhost_evo14_install_index php_action options](https://user-images.githubusercontent.com/7342798/31238911-a73dd818-a9fb-11e7-9119-650100a43b09.png)

i've translated few days ago

**Comment by Nicola1971** [comment]
found and fixed the strange character in step one  ":"
https://github.com/evolution-cms/evolution/commit/bf962d245be71059c4d8468e93767ced051cc22c
