### ISSUE TITLE
Parse error in Welcome Page (v1.3.6)

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#279]
For any additional user added, the "Welcome to your EVO Content Manager " displays a Parse Error:
![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/31221076-67fd7640-a9ba-11e7-85f6-44a0dc05490b.png)

> Parse error: syntax error, unexpected ';' in D:\xampp-portable\htdocs\xx\manager\includes\document.parser.class.inc.php(1267) : eval()'d code on line 1

The default admin login does not display this.
I dont know if this has been fixed in the recent dev, as I am unable to install that version.

**Comment by dmi3yy** [comment]
This bug only on windows (

**Comment by ProjectSoft-STUDIONIONS** [comment]
https://github.com/evolution-cms/evolution/pull/286/commits/a2fbec4a7c673af6f9cef9cbc099e956759971d4

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/pull/286
Already fixed.
