### ISSUE TITLE
OnFileBrowserUpload

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#28]
On the OnFileBrowserUpload event, when multiple files are loaded, not an array of $ filepath and $ filename of the downloaded files is returned, but only $ filepath and $ filename of the first downloaded file.

need refactor code to all time will be array )

**Comment by Pathologic** [comment]
It needs to change js-uploader and upload files via ajax one by one. I've done it yet, but it was broken during kcfinder update.

**Comment by pmfx** [comment]
Is this fixed and can be closed?

**Comment by Pathologic** [comment]
Still not.
