### ISSUE TITLE
Error in API getTemplateVar, getTemplateVars with a field value of '$fields' is different from '*'

### ISSUE THREAD

**Issue by Rising13** [evolution-cms/evolution#280]
There are API request $modx->getTemplateVars(array('MyParameter','Separater'),'name,value', 99);
Produces bool(false)
And here is the query with $modx->getTemplateVars(array('MyParameter','Separater'),'*', 99); - works, it produces an array of values.
This problem exists for all API settings, where there is a field '$fields'.

Есть API запрос $modx->getTemplateVars(array('МойПараметр','ЕщеПараметр'),'name,value', 99);
Выдает bool(false)
А вот такой запрос с $modx->getTemplateVars(array('МойПараметр','ЕщеПараметр'),'*', 99); - работает, выдает массив значений.
Эта проблема есть для всех параметров API, где есть поле '$fields'

**Comment by AgelxNash** [comment]
At now, you can also use array fields
```php
$modx->getTemplateVars(array('tv1', 'tv2'), 'name, value', 99);
$modx->getTemplateVars(array('tv1', 'tv2'), array('name', 'value'), 99);
$modx->getTemplateVars(array('tv1', 'tv2'), 'name', 99);
$modx->getTemplateVars(array('tv1', 'tv2'), array('name'), 99);
```

This calls will return an identical result.
