### ISSUE TITLE
Drag and drop in Resource Tree leads to Mysql error

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#281]
Just used the mouse to drag one resource into a container resource and got an alert that "something went wrong". In the system events I found the following error: 

> « MODX Parse Error »
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
SQL > UPDATE `mytable`.`modx_site_content` SET menuindex=0 WHERE id =

Probably it is necessary to check if an ID is set, and if not just return?

**Comment by 64j** [comment]
what version of evo and which browser ?

**Comment by q2apro** [comment]
Evo 1.3.6 and Chrome 60.0.3112.113 (Official Build) (64-bit)

Note: Maybe there was an ajax request during the time I was dragging the resources. Not sure.

**Comment by 64j** [comment]
Is the error every time, or occasionally?

**Comment by q2apro** [comment]
It was only occasionally.

**Comment by 64j** [comment]
very strange, because all checks work

**Comment by dmi3yy** [comment]
tested all ok
