### ISSUE TITLE
Friendly URLs error! (special For Yama)

### ISSUE THREAD

**Issue by Grinyaha** [evolution-cms/evolution#283]
simply plugin that show error
`if ($e->name == 'OnWebPageInit') {
    $_GET['mobileversion'] = 1;
}`

if friendly_urls  -> ok then my links from site not works, show one page for all urls. 

This part of plugin MibileSwitcher for demostration and fixed error. Evo before 2017.09.10 have not this bug.

**Comment by Grinyaha** [comment]
problem in parser in function makePageCacheKey()

**Comment by 64j** [comment]
if you return a function as it was, then everything works
this commit need revert
https://github.com/evolution-cms/evolution/commit/d80528d7f25dd3f928297d5947e7eafba91b3af3

@yama 
work function in parser
```php
    public function makePageCacheKey($id){
        $hash = $id;
        $tmp = null;
        $params = array();
        if(!empty($this->systemCacheKey)){
            $hash = $this->systemCacheKey;
        }else {
            if (!empty($_GET)) {
                // Sort GET parameters so that the order of parameters on the HTTP request don't affect the generated cache ID.
                $params = $_GET;
                ksort($params);
                $hash .= '_'.md5(http_build_query($params));
            }
        }
        $evtOut = $this->invokeEvent("OnMakePageCacheKey", array ("hash" => $hash, "id" => $id, 'params' => $params));
        if (is_array($evtOut) && count($evtOut) > 0){
            $tmp = array_pop($evtOut);
        }
        return empty($tmp) ? $hash : $tmp;
    }
```

**Comment by yama** [comment]
@Grinyaha thanks for your information.  Where can I get MobileSwitcher? I'll fix it later.

@64j Before reverting, we need to find out where the cause is. If we can not solve it, revert it.
evo is still a problematic system. It is also important to protect the compatibility of old plugins, but there is also a need to clean up the system cleanly.

**Comment by 64j** [comment]
@yama 
if you go to the page with the get parameter (for example ?page=2).
the page is cached, and then all subsequent pages with the same parameter show the first cached page.

To check this, just create a plugin with the code

```php
$e =&$modx->event;
if ($e->name == 'OnWebPageInit') { 
    $_GET['any_request'] = 1; 
}
```

**Comment by yama** [comment]
I thought for a while, This revert. This problem will be solved in the next release.

**Comment by yama** [comment]
@64j thanks, for your good hints.
