### ISSUE TITLE
Manager action "sort menuindex" does not work anymore

### ISSUE THREAD

**Issue by kabachello** [evolution-cms/evolution#284]
It worked fine in MODx 1.2, but it seems it had been rebuilt introducing lot's of changes.

Parse error: syntax error, unexpected end of file in C:\wamp\www\evolution\manager\actions\mutate_menuindex_sort.dynamic.php on line 173

**Comment by 64j** [comment]
https://github.com/evolution-cms/evolution/issues/189

**Comment by kabachello** [comment]
Thanks for the hint. See PR above for a quick solution.

**Comment by 64j** [comment]
@kabachello 
yes merged changes
