### ISSUE TITLE
Unable to upload images from EvoGallery - will pay for time spent fixing issue

### ISSUE THREAD

**Issue by GavinBaylis** [evolution-cms/evolution#287]
After having spend a lot of time/attempts to upgrade to Evo 1,2.1 I could not get the image uploader to work and thought it was an upgrade issue.

I then restored the site back to an earlier date (last week) before I attempted the update but even with the old site the image uploader was still not working.

The client confirmed that she was updating images earlier last week - so I've tried restoring the whole site back to the beginning of October and now as far back as 27 Sept and am met with the same issue.

Like I say I'm willing to pay for a fix to this as it is quite urgent. It could well be soemthing as simple as a caching or version issue, but I have spent far too much time going round in circles on this as I've been upgrading upwards of 20 accounts and upgrading a VPS and transferring accounts.

**Comment by BBloke** [comment]
I've never used that before. Wow. Nice extra.  I can confirm it worked for me in 1.3.6 but I sadly don't have 1.2.1.  Not much help I know.

**Comment by pmfx** [comment]
@GavinBaylis If there is no "Browse" button, then probably browser is blocking Flash player plugin. EvoGallery depends on that unfortunately.  If thats the case then there is no fix for this other than changing gallery snippet to similar but more modern (no Flash dependency) SimpleGallery.

Also, please use current Evo repository for issues https://github.com/evolution-cms/evolution

**Comment by GavinBaylis** [comment]
@pmfx correct Sir that was indeed the issue.

Enabled Flash for the site and it worked
