### ISSUE TITLE
Adding a minify option to the resource settings (for CSS and JS resources)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#288]
Evolution CMS is awesome and I am happy that it is continued in development. 

Today I thought we could use a resource to define CSS and JS directly within the CMS, by simply setting the "Resource Type" in the Settings tab to "text/javascript" or "text/css", and then specifying an alias like "script.js" or "styles.css". 

However, it would directly output the CSS/JS instead of a minified version. 

That is why I would like to suggest to add a **"minify" option** to such resources. Actually this could be also used for HTML minification. 

![image](https://user-images.githubusercontent.com/6764548/31489876-777ea584-af42-11e7-8ee6-c03e67b7772e.png)

This would bring advantages of: 
1. No FTP client more needed to upload CSS and JS files (okay, SCSS is still an issue). 
2. Edit such resources on the go in Evolution CMS. 
3. Dynamic links in case you change the path later, which update in the entire CMS. 
4. No need for jscompress.com or other websites to use, minification directly within the CMS.

Thanks for consideration. It would be a fantastic new feature!

**Comment by pmfx** [comment]
Hi @q2apro I think there is no need for that since it can be done with plugins.

Minify CSS/JS: https://github.com/AgelxNash/MinifyX-for-Evolution
Minify HTML: https://github.com/extras-evolution/HtmlInLine

From what I know MinifyX can use resources as CSS/JS data (CSSdoc and JSdoc parameters).

**Comment by fourroses666** [comment]
I always use:
https://github.com/Jako/MinifyRegistered

Just install it and you can minify your files without using Snippets, just add /min/f=
`<link href="/min?f=/assets/templates/site/css/style.css,/assets/templates/site/font/stylesheet.css" rel="stylesheet" type="text/css" />`

And CSS when developing I make a resource "text/css" and add a chunk `{{-css}}` in the content field. Alias: style.css with the .css. Head has <link src="/style.css" />
When going live it is placed in a normal css file and minified. /min/?f=/assets/...

**Comment by pmfx** [comment]
I believe purpose of https://github.com/Jako/MinifyRegistered is to minify REGISTERED files :)
So:
1. Install plugin
2. Upload "min" folder, quote: "The Plugin needs a working installation of minify (https://github.com/mrclay/minify) in the folder /min in the webroot (the path could be changed in plugin configuration)."
3. Register CSS files and JS files with EVO api in custom snippet for example [[siteRegClient]] (place on top of html) like this:

```
<?php
$modx->regClientCSS($tplPath.'css/styles.css');
$modx->regClientCSS($tplPath.'css/another-1.css');
$modx->regClientCSS($tplPath.'css/another-2.css');

$modx->regClientScript($tplPath.'js/scripts.js');
$modx->regClientScript($tplPath.'js/another-1.js');
$modx->regClientScript($tplPath.'js/another-2.js');
return;
```

Anyway, there one issue with this great plugin. Final file path is not pretty `<link href="/min?f=/assets/templates/site/css/style.css,/assets/templates/site/font/stylesheet.css" rel="stylesheet" type="text/css" />` Same for JS files. And this lowers page speed score a little in tools like gtmetrix. Thats why I moved to MinifyX.

**Comment by dmi3yy** [comment]
I use  light snippets for thats: 
https://github.com/dmi3yy/CssJs

`
[!css? &files=`assets/templates/tpl/css/bootstrap.css,
			   assets/js/prettify/prettify.css` 
	   &minify=`1`!]

[!js? &files=`assets/js/jquery-1.8.3.min.js,
			  assets/templates/tpl/js/modernizr.custom.28468.js,
			  assets/js/jquery.validate.js,
			  assets/js/jquery.form.min.js,
			  assets/js/prettify/prettify.js` 
	  &minify=`1`!]
`

**Comment by pmfx** [comment]
@dmi3yy this is nice! I have modified it a little to use regClientCSS / regClientScript and to write HASH value in the file name instead of query (better speed score). Example (snippet.css.php:32):

```
$min = $minified->merge( MODX_BASE_PATH.$folder.'styles.min.'.substr(md5(max($v)),0,20).'.css', 'css', $filesForMin );
return $modx->regClientCSS($folder.'styles.min.'.substr(md5(max($v)),0,20).'.css');
```

So now I'm using your solution. Fast and simple. Good work!

I think this issue can be closed.

**Comment by bossloper** [comment]
@pmfx - "write HASH value in the file name instead of query"
Will this result in multiple js and css files building up each time the hash changes and needing manually deleting?

**Comment by Nicola1971** [comment]
I use the module version of MinifyX (by AgelxNash). 
With version 2 you can minify and compress in jgz with gzip 

here you can see 342 kb of minified css, compressed in only 45kb in jgz
![download](https://user-images.githubusercontent.com/7342798/31537693-54c2e228-b003-11e7-9b04-54d12fc4ab2b.png)

**Comment by fourroses666** [comment]
Both looks great CssJs and MinifyX.
Big compression with .jgz :o

**Comment by q2apro** [comment]
Still, having a core option would be the golden grail for many.

**Comment by Nicola1971** [comment]
another nice feature of the module: you can use evo documents as additional Js and css.
... and minify and compress with other css and js files
![config](https://user-images.githubusercontent.com/7342798/31540086-e5dee138-b00a-11e7-9885-c43aa286f5b6.png)
![min](https://user-images.githubusercontent.com/7342798/31540093-eb2e71da-b00a-11e7-8dbd-af15e577aeb1.png)

**Comment by Nicola1971** [comment]
> Still, having a core option would be the golden grail for many.

I agree. could be a nice feature for  "text/javascript" and "text/css"  documents

**Comment by pmfx** [comment]
@bossloper yup, exactly.

@Nicola1971 Is there really a need to generate gz/jgz files since compression can be set globally with htaccess? That is what I usually do. Inspecting network in browser dev tools shows that 118kb css file was compressed to 19kb.

![obraz](https://user-images.githubusercontent.com/10888055/31540261-7ba0d910-b00b-11e7-9b30-bc1bc42b8b8d.png)

![obraz](https://user-images.githubusercontent.com/10888055/31540327-a1ac588c-b00b-11e7-91b0-a3f03ca3e07a.png)

**Comment by Nicola1971** [comment]
@pmfx  yes you need htaccess rules with the module too.. anyway I really don't know 😄 , but https://gtmetrix.com/ gives much better results ...and my clients are happy  😄

**Comment by bossloper** [comment]
@pmfx - here is an article discussing zipping and minifying: https://css-tricks.com/the-difference-between-minification-and-gzipping/
It seems to suggest doing both will give slightly better results.

**Comment by dmi3yy** [comment]
i think its not dificult add gzip for ccsjs snippets ) 
but i like  lighter for use ) 
its simple add snippet. and hard add module, plugin and setting all this

**Comment by fourroses666** [comment]
I have "difficulties" with CssJs.

When using _font-awesome_ I need to change the paths, also for my webfonts.
And it didn't process some js file. Don't know why. The script:

```
// slick slider
	$(document).ready(function(){			
		$('.foto-slider').slick({	
```

minifyX drops its code above the </head> but what if I'd like to seperate it and add a tab :(

**Comment by bossloper** [comment]
@dmi3yy - Agree, I would not add gzip as part of Evo. I was just indicating compressing and minifying is a valid combination.
I do the zipping by setting in htaccess that way all text files can be compressed including .js and .php. It makes a huge reduction to bandwidth usage.
For Apache:
```
<ifModule mod_deflate.c>
  <filesMatch "\.(css|js|x?html?|php)$">
    SetOutputFilter DEFLATE
  </filesMatch>
</ifModule>
```
