### ISSUE TITLE
P3P Header

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#291]
I just put an Evo site through https://redbot.org
It indicates 'The P3P header is deprecated.'

Is this something we can remove from the header now?
https://github.com/evolution-cms/evolution/blob/develop/index.php#L76

**Comment by fourroses666** [comment]
Also: `The Keep-Alive header is deprecated.`

**Comment by fourroses666** [comment]
Maybe it can be set on Configuration settings; Validate HTTP_REFERER headers?
Don't know what it does.

**Comment by fourroses666** [comment]
Dunno if this does something :0

```<IfModule mod_headers.c>
  <FilesMatch "\.(js|css|xml|gz)$">
    Header append Vary: Accept-Encoding
  </FilesMatch>
</IfModule>```

**Comment by bossloper** [comment]
I'm not exactly sure what the P3P header is for, other than on modern browsers it is depreciated. At some point it can be removed but if there is no interest to do so now I will just close this. There are more important issues to address :-)
