### ISSUE TITLE
Restore missing Menu > Site > New Resource / New WebLink?

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#294]
With the new default theme and menu, there is no more 
Menu > Site > New Resource / New WebLink
![newresource-menu](https://user-images.githubusercontent.com/7342798/31667574-21b13650-b350-11e7-8029-9c8787707856.jpg)

I had never thought about it, but some of my clients ask me why they can only create resource from the tree.

Maybe, for the most important action for a CMS, tree's small buttons are  not the best

note: on mobile devices, working with the tree is not very easy

What do you think?

Can we restore this feature in any way?

In my custom theme i've added a new dropdown icon next the search:
![new-res-menu](https://user-images.githubusercontent.com/7342798/31668609-f35d1014-b352-11e7-816c-e9c3c851cb9e.png)

I think can improve the mobile usability

**Comment by bossloper** [comment]
Personally after the initial top level resources are set up (which are usually quite static in nature) I never use those create resource buttons. I always add child pages via the tree - Setting the resource parent option means visiting the tree anyway. I even hide the resource parent field for most of my clients.
But yes not the best on a mobile device.

**Comment by Nicola1971** [comment]
Same for me but:

- Most of my sistes are based on complex directory structures, but 30% use a "all documents in root" :) structure (coming from previous wordpress or drupal). 
These clients often creates documents from main menu

- We need to improve mobile experience = mobile alternatives to the tree

About "Setting the resource parent" check this issue:
https://github.com/evolution-cms/evolution/issues/296

with add resource button + better resource parent setting we can allow full and easy creation of resources without the tree

**Comment by Nicola1971** [comment]
i think i will add with a system settings, so we can disable if not needed

**Comment by pmfx** [comment]
Maybe like this?

![screenshot_1](https://user-images.githubusercontent.com/10888055/31711593-f327469a-b3f8-11e7-832e-8085959dd797.png)

![gafsxhpfq_mwdm11j__rig](https://user-images.githubusercontent.com/10888055/31711602-fd2a1334-b3f8-11e7-9189-ecaa10396b29.png)

**Comment by Nicola1971** [comment]
nice, but a "content" menu just for two items  (resource and links)?
with a more anonymous "+" button , we could expand its functionality in the future with something else.
![download](https://user-images.githubusercontent.com/7342798/31713051-416afdf2-b3fd-11e7-8f25-278961fbb444.png)

ie: this from dotcms
![1](https://user-images.githubusercontent.com/7342798/31713027-28d1cba4-b3fd-11e7-9228-71240862758f.png)

it would be nice to have a new event (OnNewMenuRender) to add custom items (ie: Add Blog Post)
