### ISSUE TITLE
Weblink improvement?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#298]
Using a resource as Weblink isn't very logical. That can be done better. Don't know how exactly thow. When you select a resource as Weblink a client doesn't know you can add an ID to redirect to. There also is no option to redirect to First Child.

Is it a 301 redirect? Can we clear is easy from the cache somehow? 
(When using [[FirstChildRedirect]] it works very good but its hard to clear its cache)

Don't you guys think it can be improved?

Maybe the Weblink field as dropdown? 
- to a new internal page
- to a new external page
- to a file
- to first child

**Comment by bossloper** [comment]
[[FirstChildRedirect]] used to use a 302 redirect by default. That was changed to 301 at some point (not sure that was a good desision).
You can override it back to 302 using the respcode option.
Don't think you can clear the FirstChildRedirect 301 redirect cache as it is cached by the client browser.

I found we discussed this some years ago :-) : https://github.com/modxcms/evolution/issues/180

**Comment by fourroses666** [comment]
Thanks, I will use ```[[FirstChildRedirect? &responseCode=`302`]]```
Not tested yet.
