### ISSUE TITLE
QuickManager includes jQuery 3.1.1, which is incompatible with included bootstrap javascript

### ISSUE THREAD

**Issue by DisobedientMedia** [evolution-cms/evolution#299]
Hi,

Fresh install of 1.3.6 with all extras installed, using Bootstrap template.

The quickmanager plugin (version 1.5.8) includes a reference to jQuery 3.1.1, so when you are logged into the admin area and preview your site frontend this version gets loaded.

I then get errors in the web console:
`Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`
and
`TypeError: $(...).modal is not a function` in ` jquery-2.2.3.min.js%20line%202%20%3E%20eval:1:1`

This seems to stop the Ajax Search from working, plus probably other javascript errors I havent found yet.

Disabling QuickManager solves problem, but then what's the point of including it?

Thanks,
Robin

**Comment by bossloper** [comment]
Instead of disabling QuickManager, try changing the QuickManager plugin Configuration for 'Load jQuery in front-end' to false.

**Comment by DisobedientMedia** [comment]
Ok, done that, cleared site cache & browser cache.
Now getting `TypeError: $ is not a function[Learn More]` in jQuery 2.2.3. 
Site search still not working.

I think a fresh install should work out of the box, even if changing this parameter did fix it.

**Comment by DisobedientMedia** [comment]
Also tried no conflict mode for jQuery in front end

**Comment by bossloper** [comment]
"I think a fresh install should work out of the box, even if changing this parameter did fix it."
Not sure it will. I think the default install setup has QuickManager set for 'Load jQuery in front-end' as true.
https://github.com/evolution-cms/evolution/blob/develop/install/assets/plugins/qm.tpl#L10
Maybe this should be changed to false as default?

**Comment by DisobedientMedia** [comment]
yes, default seemed to be 'Load jQuery in front-end' as true.
The whole plugin was also disabled by default. Enabling it, with default configuration, results in the errors.

I think this is my point - it doesn't seem to work in the front end regardless of configuration settings. 

I just wanted to report the issue, not currently intending to use it at the moment.

**Comment by bossloper** [comment]
If you also set 'jQuery noConflict mode in front-end' to false on QuickManager then it should make AjaxSearch work.

**Comment by yama** [comment]
https://www.google.co.jp/search?q=jquery+document+write+fallback
I think that it is good to use this solution together.

**Comment by Nicola1971** [comment]
i will update default QM settings soon. @yama suggestion is a good solution too.
Anyway QM is a bit old and outdated, we need something better. ;)

**Comment by Nicola1971** [comment]
Fixed default settings on install

**Comment by Nicola1971** [comment]
@DisobedientMedia  can we close?

**Comment by DisobedientMedia** [comment]
Yes, thanks
