### ISSUE TITLE
evalSnippets parse error - System Events

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#301]
Have this error on 3 sites with 1.4 beta, seems related to nested IF snippet calls
![download](https://user-images.githubusercontent.com/7342798/31834146-51398a92-b5cd-11e7-9721-4876d33cdf58.png)
on frontend no errors.

on 1 site (with php7.2) disable filters in system settings , solve this issue

**Comment by 64j** [comment]
Yes, now this is considered an error.
Used
```
[!if?is=``&then=`
[[snippet]]
`!]
```
@yama This you have added.
https://github.com/evolution-cms/evolution/commit/21cfd88872b0eb4acae78de8ecb4e84b63a812fd

**Comment by Nicola1971** [comment]
Need uncached IF snipppet? Ok , thanks I will try.

Can we have a better error report? :D :D 
- no snippet name
- no resource Id

got headaches trying to understand the error 😄

**Comment by Nicola1971** [comment]
Question: is a bug or a beahaviour ? Because seems bad for If snippet performance

**Comment by Nicola1971** [comment]
uncached IF snippet solved the error

**Comment by yama** [comment]
@64j
thanks, I abort this error recording. I will fix it later.

@Nicola1971 
>Because seems bad for If snippet performance

Yes, it is.
https://github.com/evolution-cms/evolution/blob/1.3.6/manager/includes/document.parser.class.inc.php#L934-L941
Perhaps it would be nice to delete this block, but there seems to be some problem.

Although Tim of ClipperCMS was also pointed out, parse logic of MODX (Evo) has a problem.
https://github.com/evolution-cms/evolution/blob/1.3.6/manager/includes/document.parser.class.inc.php#L2032-L2062
That's this block.
Tim pointed out security issue, but there are performance problems as well.

I will consider this problem in a future release.

**Comment by Nicola1971** [comment]
@yama can you fix for 1.4? most of evo sites are based on this kind of IF snippet calls (with other nested snippets inside)
Thanks.

**Comment by yama** [comment]
@Nicola1971 
https://github.com/evolution-cms/evolution/pull/292/commits/2ead7dc20ae30dd5c511b21b0ce5c7787ff655df
Yes, it's already fixed.

**Comment by 64j** [comment]
@yama 
Check, please.
And look in the error log.
You did not fix anything
As there was an error with nested snippets "evalSnippets parse error" and remained!

**Comment by yama** [comment]
@64j 
of course, I checked it. Is there any other specific information?

**Comment by yama** [comment]
Sorry, I had not committed yet. I'll fix it later.

**Comment by dmi3yy** [comment]
all time use [[.  [[]] ]]. its correct work and need work all tipes of nested snippets

**Comment by dmi3yy** [comment]
i stiil not Understand why need this warning 
all time we neeв for work 

[!  [[]] !]
[[ [[]] ]]
[[ [!!] ]]

not metter what inside we see only on top Snippets and cache or not cache all
