### ISSUE TITLE
latest phpmailer-6.0.1 and EVO-1.3.6

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#302]
QUESTION / SUGGESTION:

the structure of the new phpmailer 6.x.x is different to the old  pre-version-6 structure so we (SIMPLETONS) can't just "drop in" the latest phpmailer version like we used to.  The phpmailer version in evo-1.3.6 is    5.2.23 and that was released in March https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md . Do you intend to get the phpmailer version up to 6.x.x with the next EVO-1.3.7  or   EVO-1.4?    THANKS.

**Comment by dmi3yy** [comment]
Yes will be add

**Comment by user83743** [comment]
cool. thanks

**Comment by dmi3yy** [comment]
Not update yet )

**Comment by user83743** [comment]
ok :)

**Comment by dmi3yy** [comment]
done

**Comment by user83743** [comment]
great work dmi3yy. thanks
