### ISSUE TITLE
Modifiers only working on first page call

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#303]
Evo 1.4.0 b
PHP 7.0

I use this modifier called filename:

 `<?php
$filename = pathinfo($output, PATHINFO_FILENAME);
echo $filename;
?>`

in this maxigallery template:

 `<img src="[(base_url)][+maxigallery.path_to_gal+]tn_[+maxigallery.picture.filename+]" srcset="[(base_url)][+maxigallery.path_to_gal+]tn_[+maxigallery.picture.filename:filename+]-420x315.[+maxigallery.picture.filename:extension+] 420w, [(base_url)][+maxigallery.path_to_gal+]tn_[+maxigallery.picture.filename:filename+]-210x158.[+maxigallery.picture.filename:extension+] 210w, [(base_url)][+maxigallery.path_to_gal+]tn_[+maxigallery.picture.filename+] 145w" sizes="10.4em" class="[+maxigallery.picture_width_thumb:gt=`[+maxigallery.picture_height_thumb+]`:then=`th_horiz`:else=`th_vert`+]" title="[+maxigallery.picture.title:striphtml+]" alt="[+maxigallery.picture.title:striphtml+]" />`

With phx plugin enabled everything works fine.
With phx plugin disabled and core modifiers either enabled or disabled on first page call after clearing site cache everything works. On subsequent page calls the filename modifier does not work any more. Every other modifier works as it should.

**Comment by yama** [comment]
Core modifier supports [*docvar*] [*tv*] {{chunk}} [(siteconfig)] [[snippet]] [!uncache!] .
At the moment [+placeHolder+] is not supported.

https://github.com/extras-evolution/MaxiGallery/blob/master/assets/snippets/maxigallery/chunkie/phx.parser.class.inc.php
MaxiGallery needs to use PHx that is included in MaxiGallery itself.

https://github.com/evolution-cms/evolution/blob/develop/assets/snippets/ajaxSearch/classes/asPhxParser.class.inc.php
https://github.com/evolution-cms/evolution/blob/develop/assets/snippets/jot/includes/chunkie.class.inc.php
AjaxSearch and Jot are the same.
In a future release, I want to solve this problem.
Exceptionally, Ditto and DocLister can work on core modifiers.

**Comment by yama** [comment]
There is a problem that maxigallery does not behave as intended with Core modifier enabled sites.
I will fix it.
