### ISSUE TITLE
After upgrading from MODx 1.2.1 to Evo 1.3.6 I can't edit resources

### ISSUE THREAD

**Issue by Tourist4Life** [evolution-cms/evolution#304]
When clicking the "Edit" button in manager a blank page appears as seen here:

https://cl.ly/21301y2U2z06

I'm not able to see anything in the error log.

**Comment by Nicola1971** [comment]
active plugins?

**Comment by Deesen** [comment]
Did you run /install without issues? Maybe run again? Sure that all files have been uploaded correct?

**Comment by Tourist4Life** [comment]
No active plugins other than TinyMCE and the GetField snippet.  I ended up downgrading to 1.2.1.  I will try again now with a different site.
