### ISSUE TITLE
AjaxSearch Pull Request

### ISSUE THREAD

**Issue by ricardo-lewis** [evolution-cms/evolution#305]
Which repository is the official place to propose and alteration to AjaxSearch?

**Comment by dmi3yy** [comment]
Here:
https://github.com/extras-evolution/ajaxSearch


Отправлено с iPhone

**Comment by Breezer** [comment]
A good working example of how to search custom tables would be greatly appreciated as well.

**Comment by Deesen** [comment]
Maybe this helps to start? Related to https://github.com/evolution-cms/evolution/blob/develop/assets/snippets/ajaxSearch/classes/ajaxSearchCtrl.class.inc.php#L120

```
/*

[!AjaxSearch?
  &withTvs=`tv_name`
  &config=`custom`
!]

Form contains (will be passed as $form) :
<input type="hidden" name="asf" value="xxx" />

*/

// File "assets/snippets/ajaxSearch/configs/custom.config.php" contains:
if(!function_exists('asfConfig')) {
    function asfConfig($form, &$get) {
        switch($form) {
		case 'xxx':
			$extraField = strip_tags($_POST['extra']);
			$get['extra'] = $extraField;
			$where = '(`tv_name` REGEXP \'' . $extraField . '\')';
			break;
	}
	return $where;
    }
}

```
