### ISSUE TITLE
[Enhancement] Restyle mcpuk file browser

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#306]
Old Oxygen Skin
![oxygen](https://user-images.githubusercontent.com/7342798/32102281-ecaf8fbe-bb1b-11e7-9662-7c508b447aa9.png)

New Evo Skin (refactored with font awesome)
![evo](https://user-images.githubusercontent.com/7342798/32102565-35cfe422-bb1d-11e7-9968-b4563bd91312.png)

**Comment by risingisland** [comment]
Awesome indeed! Nice work.

**Comment by fourroses666** [comment]
Cool, wanted to do this but needed to find some time.

**Comment by fourroses666** [comment]
We need an extra theme select dropdown tablerow :)

![select-kcfinder-theme](https://user-images.githubusercontent.com/523389/32105543-21347ada-bb29-11e7-903f-c45956e49fda.jpg)

**Comment by Nicola1971** [comment]
> We need an extra "Theme" select dropdown tablerow :)

No, should be better move styles to manager theme

**Comment by Nicola1971** [comment]
I decided to continue and edit the template for more customizations:

### Moved thumbs/list view radio buttons from "Settings" to the main "toolbar"**
and styled radio label to look like buttons.
easy to switch views and looks better.

![moved-settings](https://user-images.githubusercontent.com/7342798/32114365-a1d5ddae-bb43-11e7-9a61-06f843d7b023.png)
![list](https://user-images.githubusercontent.com/7342798/32114372-a761592e-bb43-11e7-97c5-0be7e87181cf.png)
![thumbs](https://user-images.githubusercontent.com/7342798/32114384-ac76d3b2-bb43-11e7-9302-85b21e5d649c.png)

**Comment by Nicola1971** [comment]
### Added a Collapse-sidebar function and button 😃 
![collapse-sidebar](https://user-images.githubusercontent.com/7342798/32114497-08c88854-bb44-11e7-9c81-13a8c9312113.png)

**Comment by Nicola1971** [comment]
### Popup mode from Tinymce
![popup](https://user-images.githubusercontent.com/7342798/32114720-76210192-bb44-11e7-81dc-5719a690e493.png)

with collapsed sidebar

![popup-collapsed](https://user-images.githubusercontent.com/7342798/32114737-7ef9257e-bb44-11e7-95da-22bf64510e1e.png)

**Comment by pmfx** [comment]
@Nicola1971 good work, looks much better.

**Comment by Nicola1971** [comment]
it's on dev , you can test (add styles, improve..) now :)

**Comment by 64j** [comment]
Good works:)

**Comment by Nicola1971** [comment]
Thanks, now look more integrated in the system.
Note: I've tried to hide maximize button with media query, when opened from tree button, because brokes the layout and is useless, but is not the perfect solution.

**Comment by Nicola1971** [comment]
Question: remove old Oxygen theme?

**Comment by 64j** [comment]
It's better to leave the old subject, but by default make a new one

**Comment by Nicola1971** [comment]
Note: For a better "mobile" (treeless) experience, we should add manage images and a manage files to the main manu: maybe in "elements"  or the new "+" (add resource) button?

**Comment by Nicola1971** [comment]
@64j ok, but old theme need update for new buttons and sidebar toggle
