### ISSUE TITLE
Inconsistent Title/Icon for Security / Manager Users

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#311]
The Home dashboard icon/naming seems inconsistent with the menu.

There is top level menu item called security which uses the 'web users' icon.
Then the dashboard item named 'security' with a padlock takes you to the 'manager users' page.

Maybe the top level menu should have the padlock icon?
Then the dashboard 'security' should be renamed to 'manager users' with the same icon as in the dropdown menu?
![untitled](https://user-images.githubusercontent.com/1744687/32394238-55a442fe-c0d4-11e7-832a-d674a769bbc7.png)

**Comment by dmi3yy** [comment]
What lang used?

**Comment by risingisland** [comment]
All langs, it is the icon that doesnt match...
![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/32444968-3d0b8ac0-c2fc-11e7-83ed-cb8fb06f446b.png)

**Comment by bossloper** [comment]
Default 'English' or 'English British', but not sure it matters(?) and the icons will be independent of language?

**Comment by dmi3yy** [comment]
yes now see )

**Comment by bossloper** [comment]
I still think the icons are not correct. Plus it was the dashboard title that was not correct, not the top menu title. In the dashboard it has 'security' but links to 'manager users'.

**Comment by dmi3yy** [comment]
done http://take.ms/UWVrv

**Comment by bossloper** [comment]
nearly. the icons for 'users' are not the same on the menu and the dashboard.

**Comment by dmi3yy** [comment]
done

**Comment by bossloper** [comment]
Should 'users' on the dashboard not be titled 'manager users' as to goes to the manager users settings?

**Comment by dmi3yy** [comment]
Users go to manager users 
Web users go to web users )

**Comment by bossloper** [comment]
I would also suggest 'users' on the menu be put back as 'security' with the padlock icon as it refers to user /manager users and roles so is more than 'users'

**Comment by bossloper** [comment]
This is not correct yet, please re-open for now.

**Comment by Nicola1971** [comment]
Does not look good.
I think is better use 
- lock icon for security
- user icon for users
- users icon for web users

**Comment by dmi3yy** [comment]
What not incorrect? 
http://take.ms/XObHe 

we hawent security items in menu )  for users and web users i fix

**Comment by bossloper** [comment]
The top menu dropdown also has 'Roles', 'Manager permissions' and 'web permission' so I would suggest the top level menu title be called 'Security' not 'Users' and have the lock icon.

**Comment by dmi3yy** [comment]
Yes but its menu called Users and its correct 

users with icons security not correct for me

**Comment by bossloper** [comment]
"Yes but its menu called Users and its correct" - that is the confusing part to me.

You use the top level title of 'users' to refer to both 'web users' and 'manager users' but have the same 'users' title in the dashboard to refer to 'manager users'

**Comment by dmi3yy** [comment]
then correct write  on dashboard: 
Managers / Web Users.
