### ISSUE TITLE
1.4.0.RC Home page error

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#314]
After install, tried visiting home page, received blank page and this error:

`Fatal error: Can't use method return value in write context in D:\xampp-portable\htdocs\evolution-develop\assets\snippets\DocLister\core\controller\site_content_menu.php on line 46`

**Comment by dmi3yy** [comment]
What version php ?

**Comment by 64j** [comment]
@risingisland 
Show the call to the snippet?

**Comment by risingisland** [comment]
@dmi3yy On localhost, 5.4.7
@64j Default install, unable to see any front-end pages. Manager works fine.

**Comment by 64j** [comment]
@risingisland 
up to version PHP 7 (min 5.6)

**Comment by modxuser** [comment]
@64j 

This statement (from the README.md) is wrong then, or not:

> Evolution CMS requires PHP >= 5.4, but snippet FormLister need PHP >=5.6

With your statement it should now be 5.6, or am I getting confused somehow ?

**Comment by 64j** [comment]
@modxuser 
For Evolution CMS, it is advisable to use PHP 5.6.
Officially, PHP 5.6 is no longer supported

**Comment by modxuser** [comment]
@64j 

Thanks - the README.md should by rights be updated then

**Comment by 64j** [comment]
@modxuser long ago fixed
