### ISSUE TITLE
Modifiers only working in else part of if snippet

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#315]
Evo 1.4.0 RC
PHP 7.0

Since 1.3.? following constellation is not working correctly any more:

On the startpage I have a tv called season with two options: summer | winter.
On another page I use multitv for the header image of this page. In the image selection field of this multitv I have this:`[!If? &is=`[*season*]:is:summer` &then=`assets/images/header/image-summer.jpg` &else=`assets/images/header/image-winter.jpg`!]` (In this If call are stars around season, but they are eaten by the board software).

The corresponding multitv config is `this:`
<?php
$settings['display'] = 'vertical';
$settings['fields'] = array(
    'image' => array(
        'caption' => 'Image',
        'type' => 'image'
    ),
    'thumb' => array(
        'caption' => 'Thumbnail',
        'type' => 'thumb',
        'thumbof' => 'image'
    ),
    'legend' => array(
        'caption' => '(alt="")',
        'type' => 'text'
    ),
    'title' => array(
        'caption' => '(title="")',
        'type' => 'text'
    ),
    'author' => array(
        'caption' => 'Author',
        'type' => 'text'
    )
);

$settings['templates'] = array(
    'outerTpl' => '[+wrapper+]',
    'rowTpl' => '<img src="[+image+]" srcset="[+image+] 730w, [+image:pathFilename+]-1280x395.[+image:extension+] 1280w, [+image:pathFilename+]-1700x524.[+image:extension+] 1700w, [+image:pathFilename+]-2560x790.[+image:extension+] 2560w" sizes="(max-width: 15em) 150vw,(max-width: 20em) 135vw,(max-width: 25em) 130vw, (max-width: 30em) 125vw, (max-width: 40em) 112.5vw, (max-width: 53.125em) 100vw, 45.625em" alt="[+legend+]" title="[+title+]" />'
`);`

If I choose option winter (&else in If call) on startpage everything works and srcset paths are complete and functioning. If I choose option summer (&then in If call) srcset paths are not modified and the same for every image size. It looks as if modifiers are not working in &then part of If snippet. Some versions ago (maybe before update to 1.3.x?) everything worked correctly.

Above behaviour occurs with phx or core modifiers either enabled or disabled.

**Comment by dmi3yy** [comment]
can you write code in tag code plz cant read config corectly

**Comment by leonie12** [comment]
Config is in code tag. I tried everything to get the config displayed correctly. But board software seems to be more clever than I am.

**Comment by dmi3yy** [comment]
better way send file ) with config

**Comment by leonie12** [comment]
@dmi3yy: You got an email.

**Comment by dmi3yy** [comment]
yes, got it. Tomorrow will be test. now want sleep

**Comment by dmi3yy** [comment]
Can you write simple sample what not work 
i get your multiTV config and its cant work without dop extras in basic mode [+image:pathFilename+] cant work

**Comment by dmi3yy** [comment]
and not understend how you use if + multiTV

**Comment by leonie12** [comment]
What is dop extras in basic mode?

I have a modifier called pathFilename(.php.phx): 

`<?php
$path_parts = pathinfo($output);
echo $path_parts['dirname'] . '/' . $path_parts['filename'];
?>`

and another modifier called extension(.phx.php):
`<?php
$extension = pathinfo($output, PATHINFO_EXTENSION);
echo $extension;
?>`

Those work as expected in the else part of the If snippet i.e. I get 
`srcset="assets/images/header/winter.jpg 730w, assets/images/header/winter-1280x395.jpg 1280w, assets/images/header/winter-1700x524.jpg 1700w, assets/images/header/winter-2560x790.jpg 2560w" sizes="…"`
This does not work in the same way in the &is part of If snippet. There I get 
`srcset="assets/images/header/summer.jpg 730w, assets/images/header/summer-1280x395.jpg 1280w, assets/images/header/summer-1700x524.jpg 1700w, assets/images/header/summer-2560x790.jpg 2560w" sizes="…"`

I use If snippet in MultiTV input field for image (type=image) like this: 

`[!If? &is=`[*season*]:is:summer` &then=`assets/images/header/summer.jpg` &else=`assets/images/header/winter.jpg`!]`

Before I used If snippet I had: `[*phx:if=`[*season*]`:is=`summer`:then=`assets/images/header/summert.jpg`:else=`assets/images/header/winter.jpg`*]`

Both variants (phx and if snippet) worked before 1.3.x. and do not function correctly any more now.

**Comment by dmi3yy** [comment]
if you use IF 
then : work like separatior and instide modifiers all broken 

test snipet if with separator  n ot : 

&separator=`~~`

**Comment by leonie12** [comment]
I do not understand what I have to do. Can you explain a bit more precise? I have no clue where to use the separator.

Is it intended that it no longer works as it did before?

**Comment by 64j** [comment]
@leonie12 
```
[[if?
&separator=`~~`
&is=` `
&then=` `
&else=` `
]]
```

**Comment by leonie12** [comment]
Yes I see how to declare the separator. But where do I use it.

**Comment by leonie12** [comment]
I tried it like this: `[!If? &is=`[*season*]~is~summer` &then=`summer.jpg` &else=`winter.jpg` &separator=`~~`!]`

The result is that I get always summer.jpg. If TV season is summer or winter. And it is not modified to be summer-1280x395.jpg etc. in both cases. Do I anything wrong or does it not function as it should?

I do not see why this bug has been closed.
