### ISSUE TITLE
[Demo site] Profile page unavailable

### ISSUE THREAD

**Issue by dukeRD** [evolution-cms/evolution#319]
На демосайте  не открывается корневая страница профиля profile.html
Сначала выдаёт 500 ошибку, если обновить страницу пишет:
```
Fatal error: Call to undefined function FormLister\str_pos() in /home/d/dukerd/reezoq.dukerd.ru/public_html/assets/snippets/FormLister/core/controller/Login.php on line 27
```
Дочерние страницы открываются.

**Comment by dmi3yy** [comment]
Use php 5.6 or High

**Comment by 64j** [comment]
@dukeRD 
in file assets/snippets/FormLister/core/controller/Login.php on line 27
replace **str_pos** to **strpos**

**Comment by dmi3yy** [comment]
ага таки опечатка поправил
