### ISSUE TITLE
Latest Dev Install - No css

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#321]
Just updated to the latest dev version and the manager has no style.
The new styles.min.css file is empty except for a few comment lines:

`/* bootstrap.min.css */

/* font-awesome.min.css */

/* fonts.css */

/* forms.css */

/* mainmenu.css */

/* tree.css */

/* custom.css */

/* tabpane.css */

/* contextmenu.css */

/* index.css */

/* main.css */`

**Comment by 64j** [comment]
@bossloper 
Tell me more.
PHP Version
Domain / Subdomain
File permissions

(very little information to guess)

**Comment by bossloper** [comment]
PHP 5.6.32
database:  5.5.5-10.1.28-MariaDB
sub-domain and in a sub-folder
file permissions 644 (and have not had any other file permission issues)

**Comment by dmi3yy** [comment]
work on local ? or in web ? can you get access?

**Comment by bossloper** [comment]
On the web. 

I think the file paths are ok. If I look at one of the files to be included, e.g.
`MODX_MANAGER_URL . 'media/style/' . $modx->config['manager_theme'] . '/css/fonts.css'`
then the resolved path is correct.

**Comment by dmi3yy** [comment]
found where bug  now wii fix it

**Comment by 64j** [comment]
@bossloper 
try to replace **MODX_MANAGER_URL** to **MODX_MANAGER_URL**
https://github.com/evolution-cms/evolution/blob/develop/manager/frames/1.php#L82-L92

It's a mistake, I'll fix it now.

**Comment by 64j** [comment]
@bossloper Corrected, so should work
https://github.com/evolution-cms/evolution/commit/81fe96ae566ffc68874e7037d35257a88a781354

**Comment by bossloper** [comment]
Yes, that works. The problem is you need to delete the old 'manager/media/style/default/css/styles.min.css' file to get it to update. I can see that being an issue going forward. If during development any of the css files are updated e.g. tree.css etc then how is the styles.min.css file going to get updated? 
Because this line
https://github.com/evolution-cms/evolution/blob/develop/manager/frames/1.php#L79
will stop new css file being created after the first time.

**Comment by 64j** [comment]
@bossloper 
To update the file styles.min.css, you just need to re-save the configuration

**Comment by bossloper** [comment]
Ah, ok! Think we can close this now?
