### ISSUE TITLE
Стиль всплывающего окна

### ISSUE THREAD

**Issue by 0test** [evolution-cms/evolution#324]
Возможно ли в будущем сделать стиль всплывающего окна так, чтобы оно не терялось на фоне админки и было понятно, что это действительно окно? Открыв первый раз, подумал, что у меня проглючила видеокарта и "съехали" пиксели окон.
Допустим нечто такое:
![- -2](https://user-images.githubusercontent.com/10080727/32495528-10706bbc-c3d7-11e7-9123-e6c0fd01df4a.png)

**Comment by dmi3yy** [comment]
Симпатично получилось кидай пул )

**Comment by 64j** [comment]
@0test 
если нажимаете контекстное меню, значит знаете для чего вы это делаете, и знаете что всплывающее окно выглядит именно так))
Если вы не привыкли с первого раза, попробуйте открыть всплывающее окно несколько раз, пока ваши глаза не привыкнут к новому виду))
