### ISSUE TITLE
Bug after update to 1.4.0 RC: No Character encoding available

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#326]
Bug: No Character encoding available via dropdown: 

![01](https://user-images.githubusercontent.com/6764548/32499056-1c176eea-c3da-11e7-86d6-b6b24a5d5c86.PNG)

**Comment by dmi3yy** [comment]
what php? server ?  
test local and on hosting all ok

**Comment by q2apro** [comment]
Directly upgraded on hosting. 

EVO version |   | 1.4.0.RC
Release date |   | Nov 06, 2017
PHP Version |   | 7.1.11

System	Linux 4.4.0-97-generic #120-Ubuntu SMP x86_64

**Comment by 64j** [comment]
@q2apro 
you did not install the system, but simply uploaded the folder manager over the old one

**Comment by q2apro** [comment]
I actually just clicked the red button "Update" on the home screen …

How to perform the "real update"?

**Comment by 64j** [comment]
@q2apro 
Re-save the settings

**Comment by q2apro** [comment]
Thanks @64j After the manual update, the encoding is showing up again.
