### ISSUE TITLE
Recommendation for Warnings after installation/update

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#327]
This was shown after the update: 

![02](https://user-images.githubusercontent.com/6764548/32499059-1e3a60ec-c3da-11e7-9b43-f352bb198bfe.PNG)

I could quickly find the "File Manager Path" in the Admin settings. However, I could not find the "File Base Path"... just after a while I realized that it is hidden under "File Browser" (which is always "No" in my installation, so settings are hidden). 

I would really like to see those two warnings on top linked to the option, the underlined words. 

Thanks!

**Comment by sashabeep** [comment]
That's amazing! wait for this message for 10 years, so glad to see this in any form 👍 So links is not the main goal, reset paths is the first step after moving site to another place http://www.evolution-docs.com/documentation/administration/moving-site

**Comment by q2apro** [comment]
FYI, I did not move the site to another place. I just ran the update.

**Comment by fourroses666** [comment]
Or add the text; 

Please check and update your Evo system configuration. `You can reset the file base path under Tools > Configuration > File Browser`.    

and for manager .... `File Manager`

**Comment by Nicola1971** [comment]
@fourroses666 
```/manager/#?a=17&tab=5``` for File Manager
```/manager/#?a=17&tab=6``` for File Browser

should work, if you don't have additional tabs (ie: plugin tabs in settings)

**Comment by fourroses666** [comment]
All lang files need to be changed like this;

`<u>`File Manager path`</u>` 
`<u>`File base path`</u>` needs to be

`<a href="/manager/#?a=17&tab=5">`File Manager path`</a>`
`<a href="/manager/#?a=17&tab=6">`File base path`</a>`

https://github.com/evolution-cms/evolution/blob/develop/manager/includes/lang/english.inc.php#L129 
https://github.com/evolution-cms/evolution/blob/develop/manager/includes/lang/english.inc.php#L142

Maybe someone can add the pull?

**Comment by Nicola1971** [comment]
@fourroses666, A link to system settings is not a solution, if you have hidden file browser tab like @q2apro 
Better solution: add a "reset path" button to the alert, like the reset in the alert of modified system files

**Comment by dmi3yy** [comment]
Done but,  not manager ) [+MGR_DIR+]

Its in 99% show after Update or Move site then first login is Admin )
