### ISSUE TITLE
Modules / Module Icons

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#329]
I see fa-cubes is now the modules icon.
I though it might be nice to use fa-cube to represent a single module.
So something like this.
![untitled](https://user-images.githubusercontent.com/1744687/32507599-c8a4d42c-c3df-11e7-8b98-19b94745214f.png)
Good or bad?
+ in some places there are hardcoded overrides for Doc Manager and Extras icons - I think they should be removed.

**Comment by Nicola1971** [comment]
100% agre for fa-cube for single module ;)

for next 1.4.1 1.4.2 release i want move all hardcoded font-awesome icons to theme/style.php to allow faster fix of this kind of issues and use of different icon font sets (ie: material icons) in custom themes

**Comment by bossloper** [comment]
Thanks Nicola.

I also see the module 'Icon	(32x32)' field does not work with an image so the 'insert' button can be removed:
![untitled](https://user-images.githubusercontent.com/1744687/32509301-d5a2d610-c3e4-11e7-93c7-5e143848ed66.png)
. But if you put 'fa fa-someicon' in the field then it does render in the 'Manage Modules' page. This really needs extending so if an icon is defined for a module it is used on any other lists (top menu dropdown, ElementsInTree plugin etc). That way the hardcoded icons for doc manager and extras can be replaced with conventional icon overrides.

**Comment by Nicola1971** [comment]
![1](https://user-images.githubusercontent.com/7342798/32510299-6c856862-c3f0-11e7-93af-0879f1f3161c.png)
![2](https://user-images.githubusercontent.com/7342798/32510306-6eeed7b4-c3f0-11e7-82f7-8032c74196d9.png)

**Comment by Nicola1971** [comment]
> needs extending so if an icon is defined for a module it is used on any other lists (top menu dropdown, ElementsInTree plugin etc). That way the hardcoded icons for doc manager and extras can be replaced with conventional icon overrides.

agree, but dont think we have the time for 1.4 - but for next relase ;)

**Comment by Nicola1971** [comment]
just noticied in your first screenshot something wrong with EIT buttons
i have the same issue
![download](https://user-images.githubusercontent.com/7342798/32510472-00084758-c3f1-11e7-880f-1706ab9551b5.png)

**Comment by bossloper** [comment]
yes they need styling better.
