### ISSUE TITLE
Change to Categories Manager Icon

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#330]
Suggest changing 'categories manager' icon to fa-object-group so it is more distinct to 'manage files':
![untitled](https://user-images.githubusercontent.com/1744687/32510641-2d5c4180-c3e9-11e7-9a90-b06ec377ae6c.png)

**Comment by Nicola1971** [comment]
yes , the folder icon si not the right icon

**Comment by Nicola1971** [comment]
done.
stop now with icons 😄

**Comment by bossloper** [comment]
lol
