### ISSUE TITLE
Action buttons - Missing dropdown arrow

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#335]
Did the 'save type' dropdown button have an arrow at some point? If so it is not there now. Missing across the system. 
![untitled](https://user-images.githubusercontent.com/1744687/32541532-d3c12c88-c467-11e7-8a7b-9c2dd9894ba8.png)

**Comment by Nicola1971** [comment]
maybe related to this commit https://github.com/evolution-cms/evolution/commit/ad954965ae3e54f0f2bffcdc9998f949a9db0dd4

@64j ?

**Comment by bossloper** [comment]
Looks like something to do with the style.min.css update. If I force the manager to user page.css then the arrow is displayed correctly.

**Comment by dmi3yy** [comment]
style.min.css - no need change.  its autoupdate with settings save )

**Comment by bossloper** [comment]
I just did another install and it is showing again. Not sure what was going on. Some caching somewhere maybe. But looks fine again so I will close unless I see it again.
