### ISSUE TITLE
Баг со вставкой ссылки в Tiny

### ISSUE THREAD

**Issue by 0test** [evolution-cms/evolution#337]
Если выбрать поле "Адрес ссылки" и нажать слева в дереве ресурсов на документ, в поле вставлялся его айди. Теперь не работает, точно не скажу с какой версии, но в 1.3.6 и 1.4 точно.
![- -1](https://user-images.githubusercontent.com/10080727/32549258-d20cafde-c499-11e7-8356-7e06292ae01e.png)

**Comment by 64j** [comment]
Если выбрать поле "Веб-ссылка" это всегда работало, 
![image](https://user-images.githubusercontent.com/4653189/32549569-04f325e4-c49b-11e7-8a4c-cd13553d4634.png)

а то что на скрине, никогда такого не было, то есть никогда не брался документ из дерева, а всегда открывался менеджер файлов

**Comment by Nicola1971** [comment]
has always worked this way

google transl:   всегда работал таким образом

**Comment by 0test** [comment]
Какая нафиг веб-ссылка? Речь про Тини и админку. Работало как минимум до версии 1.12.1 включая её. И продолжает работать там. Ну не видео же мне записывать?

**Comment by 64j** [comment]
@0test запишите видео если не трудно.
Но чтобы такое было из коробки, не помню

**Comment by 0test** [comment]
Прошу https://yadi.sk/i/YY2KCZ053PWty9
