### ISSUE TITLE
[phpThumb] - Error : escapeshellarg() has been disabled for security reasons

### ISSUE THREAD

**Issue by yama** [evolution-cms/evolution#340]
https://github.com/modxcms/evolution/issues/754
This issue already Fixed on Evo products

https://github.com/JamesHeinrich/phpThumb/issues/25
https://github.com/JamesHeinrich/phpThumb/commit/b54fbc36a3b71c7039a01875834c32245d5d24df
phpThumb v1.7.14 (latest version) has been fixed as well. (suggest by Tim)
In other words, we can update it.

**Comment by dmi3yy** [comment]
This fixed by this line: 

https://github.com/evolution-cms/evolution/blob/1.4.x/assets/snippets/phpthumb/phpthumb.class.php#L4292-L4296
