### ISSUE TITLE
Tinymce link to document from tree not working

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#343]
When trying to link to a document by selecting item from tree, link adds `[~node6~]` instead of `[~6~]`
![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/32601295-0c72d7f2-c53a-11e7-9517-7b4b0333142b.png)

**Comment by 64j** [comment]
#337

**Comment by dmi3yy** [comment]
fixed
