### ISSUE TITLE
new 1.4.0 release announcements and placeholders on dashboard

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#348]
Hi

we're on 1.3.6 EVOLUTION on php7. it's perfect that a new release is on the dashboard for 'admin' users, but i logged into a 'Publisher' account and it displayed the "MUST UPGRADE" WARNINGS, plus some garbled PLACEHOLDER data, below.  any ideas?:

"
[[@OnManagerWelcomePrerender]]
 SYSTEM UPDATE
Content management system is outdated. To update contact the site developers. Current version 1.4.0.RC 

We strongly recommend making a backup before upgrading the system, the update is performed at your own risk !! 
 [%WELCOME_TITLE%]
[%elements%]
"

we tried this on php 5.6 and php7 and the same placeholders appear.

**Comment by user83743** [comment]
also, should RC releases be flagged like that or should that be reserved for "LATEST RELEASE" ON https://github.com/evolution-cms/evolution/releases  and not  "PRE-RELEASE"?

**Comment by dmi3yy** [comment]
will be check

**Comment by Nicola1971** [comment]
@dmi3yy if you set the widget for AdminOnly and login as publisher, there is an error too:
``Parse error: syntax error, unexpected ';' in D:\UwAmp\www\evo13\manager\includes\document.parser.class.inc.php(1267) : eval()'d code on line 1``

dont understand the cause

**Comment by Nicola1971** [comment]
@dmi3yy Upgrading 1.3.6 to 1.4 **RC1** and login as publisher the issue disappears: placeholder and the updater widget are displayed correctly.

I think this issue was solved in 1.4 RC1 and we can close.
