### ISSUE TITLE
User Icon Standardisation Suggestion

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#349]
For consistency, differentiation etc, I suggest.
General reference to users (both web users and manager users): http://fontawesome.io/icon/users/
For Manager users (a halo :-) of importance): http://fontawesome.io/icon/user-circle-o/
For web users: http://fontawesome.io/icon/user/
??

**Comment by Nicola1971** [comment]
@bossloper ....Icons ...again! 😄 😄
I agree, but I want move all manager pages icons to style.php for next 1.4.x release, to allow change these  icons in a single file.

**Comment by bossloper** [comment]
I think I am nearly over my icon  addiction...
Agreed on putting them in style.php.

**Comment by dmi3yy** [comment]
done
