### ISSUE TITLE
System Settings - Missing Save and Continue

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#350]
The new behaviour on System Settings, when you save, is close the page and go the dashboard - does not work well.
There are  are many situations when you need remain on Settings page:

- You're editing the **site offline message** and want to preview your work
- You're editing registration **users messages** - is a long task and you want save many times during editing
- You want to see/test **new Evo1.4  features** (ie: new interface feature like Global Tabs, breadcrumbs, group tv..)
- You're a completely **new evo user** and you're learning/discovering CMS settings

Note: with Global Tabs we can keep System Settings opened in tab and easy check/test the results of settings changes in the whole manager - why lose this comfortable feature?

We need : 
1) Restore old behaviour (sabve and stay) and add a button "close"
or
2) Add the new Save and Continue dropdown button

**Comment by 64j** [comment]
@Nicola1971 
If you do so that saving the configuration does not close all global tabs, then all changes on these tabs will not be accepted.
And you will not see any changes until you open new global tabs.

Updating the entire admin panel window while saving the configuration is made for good reason.
The cache is reset, a new style file is generated, all the tabs are cleared.
It's like hard reset.

**Comment by 64j** [comment]
@Nicola1971 
Perhaps this is what you need?

replace to
```php
$header="Location: index.php?a=17&r=10";
```

https://github.com/evolution-cms/evolution/blob/develop/manager/processors/save_settings.processor.php#L153

**Comment by Nicola1971** [comment]
@64j 
> Updating the entire admin panel window while saving the configuration is made for good reason.

I understand the reason, but is there a way to reset and reload The System Settings page?

**Comment by 64j** [comment]
@Nicola1971 
Yes, but the rest of the global tabs will need to be closed

**Comment by Nicola1971** [comment]
@64j even now, global tabs need are closed after save settings.
so, if you can change, reload The System Settings is still the better solution
