### ISSUE TITLE
Modifiers only working in else part of if snippet when used in multiTV input

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#351]
Evo 1.4.0 RC
PHP 7.0

See also #315. The issue persists even if it was closed by @dmi3yy.

To make the issue more clear I have taken screenshots:

This is the MultiTV input in which the if snippet called is used: The TV season with the options summer|winter is above.

![if-snippet-in-multitv-input](https://user-images.githubusercontent.com/24967436/32698899-dbe60a26-c7ac-11e7-8737-effa8f2b1889.png)

This is the belonging multiTV config:

![multitv config](https://user-images.githubusercontent.com/24967436/32698498-6cc09a08-c7a7-11e7-9bee-03bb0dada18a.png)

This is the modifier 'pathFilename' which is used in multiTV config *and works in &else part of if snippet* (season is winter):

![modifier-pathfilename](https://user-images.githubusercontent.com/24967436/32698531-b718ab86-c7a7-11e7-9cb9-4e697c2c8171.png)

This is the modifier 'extension' which is used in multiTV config *and works in &else part of if snippet* (season is winter):

![modifier-extension](https://user-images.githubusercontent.com/24967436/32698535-d2e65318-c7a7-11e7-8bf4-1e8bb62bdc42.png)

The issue is following: Depending of TV 'season' *the correct image is delivered* by if snippet: summer.jpg for 'summer' and winter.jpg for 'winter'. If snippet works correctly so far …

If 'season' is 'winter' (**&else** part of if snippet) the imagepath is modified to winter-1280x395.jpg, winter-1700x524.jpg, winter-2560x790.jpg how it is expected to function. **&else works correctly** in this use case.

If If 'season' is 'summer' (**&then** part of if snippet) the imagepath is **not modified** to summer-1280x395.jpg etc. but stays always summer.jpg. **&then does not work correctly** in this use case.

**Comment by leonie12** [comment]
I tried also the suggestion of @dmi3yy: [!If? &is=`[*season*]~~is~~summer` &then=`summer.jpg` &else=`winter.jpg` &separator=`~~`!]` This did not change anything.

**Comment by dmi3yy** [comment]
Thanks for detailed. will be test

**Comment by 64j** [comment]
@leonie12 
All modifiers must be in the folder

**assets/plugins/phx/modifiers**

multiTV config for **season-img**

```php
<?php
$settings['display'] = 'vertical';
$settings['fields'] = array(
    'image' => array(
        'caption' => 'Image',
        'type' => 'image'
    ),
    'thumb' => array(
        'caption' => 'Thumbnail',
        'type' => 'thumb',
        'thumbof' => 'image'
    ),
    'title' => array(
        'caption' => 'Title',
        'type' => 'text'
    ),
    'alt' => array(
        'caption' => 'Alt',
        'type' => 'text'
    ),
    'author' => array(
        'caption' => 'Author',
        'type' => 'text'
    )
);
$settings['templates'] = array(
    'outerTpl' => '<div class="images">[+wrapper+]</div>',
    'rowTpl' => '
    <div class="image">
	    <img src="[+image+]" srcset="[+image+] 730w, [+image:pathFilename+]-1280x395.[+image:extension+] 1280w, [+image:pathFilename+]-1700x524.[+image:extension+] 1700w, [+image:pathFilename+]-2560x790.[+image:extension+] 2560w" sizes="" alt="[+alt+]" title="[+title+]" />
	    [+author:ne=``:then=`<p class="copyright">[+author+]</p>`+]
	    [+alt:ne=``:then=`<p class="legend">[+alt:nl2br+]</p>`+]
	</div>
	'
);
```

![image](https://user-images.githubusercontent.com/4653189/32700371-1a5d9116-c7d5-11e7-80ee-f6268b7e1731.png)


**assets/plugins/phx/modifiers/extension.phx.php**

```php
<?php

$extension = pathinfo($output, PATHINFO_EXTENSION);
echo $extension;
```

**assets/plugins/phx/modifiers/pathFilename.phx.php**

```php
<?php

$path_parts = pathinfo($output);
echo $path_parts['dirname'] . '/' . $path_parts['filename'];

```


![image](https://user-images.githubusercontent.com/4653189/32700389-74dacf1e-c7d5-11e7-8c0b-df4ef6685835.png)


## Everything is working !

**Comment by 64j** [comment]
@leonie12 
Any errors you can write here
https://github.com/extras-evolution/multiTV

**Comment by leonie12** [comment]
@64j: Did you change anything in your setup?
I have all modifiers in the told folder.

Does it really work for you? What I see in your screenshot seems to be the &else case (winter) which works also for me. The issue is with the &then part (summer), which should deliver evo-logo-1280x395.jpg etc in your setup.

**Comment by leonie12** [comment]
Issue is confirmed by @64j and happens not only with if snippet but also when if snippet call is replaced with phx call:
```[*phx:if=`[*season*]`:is=`summer`:then=`assets/images/header/summer.jpg`:else=`assets/images/header/winter.jpg`*]```

Also here only the else case is working correctly.

**Comment by 64j** [comment]
code phx modifier
add **$output = $modx->evalSnippets($output);**

pathFilename
```php
<?php

$output = $modx->evalSnippets($output);
$path_parts = pathinfo($output);
echo $path_parts['dirname'] . '/' . $path_parts['filename'];
```

extension
```php
<?php

$output = $modx->evalSnippets($output);
$extension = pathinfo($output, PATHINFO_EXTENSION);
echo $extension;
```
