### ISSUE TITLE
Папки в линию

### ISSUE THREAD

**Issue by warchild1** [evolution-cms/evolution#353]
![2017-11-13_15-24-41](https://user-images.githubusercontent.com/17488086/32716238-cf7a3b46-c887-11e7-94e1-288d30004e41.png)
Прошу выровнять папки в левом поле по левому краю. Сейчас они зигзагом стоят.

**Comment by dukeRD** [comment]
Мне кажется, что это показывает иерархию, 3 папки верхнего уровня, 3 вложенные, а в линию будет менее понятно.  Скорее наоборот, стоит чуть правее вложенные сдвинуть, чтобы иконка была на уровне родительской.

**Comment by warchild1** [comment]
Это не вложенные. 
![s1](https://user-images.githubusercontent.com/17488086/33115762-c21c2ea0-cf94-11e7-82e0-fb204b491ac0.png)
Вот пример того, как это в админке. в kcfinder иконки расположены по другому.
