### ISSUE TITLE
Small screen touch device menu dropdown issues

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#354]
When on a screen less than 840px the text for top menu items is hidden as expected.
However for a touch device the dropdown menus do not always display, though fine on a desktop PC.
It can be any dropdown menu, but not always the same one!

![image-1](https://user-images.githubusercontent.com/1744687/32719477-71d06684-c858-11e7-9c8c-318f2484bef9.jpg)

If I comment out this line: https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/css/mainmenu.css#L90
...then the dropdown does work reliably on these small screens (though obviously not fit the screen!).

Tested on iPhone 6s, Galaxy A5 and iPad Air2

**Comment by CatOstrovsky** [comment]
```
#mainMenu.show .nav>li.hover>a + .dropdown-backdrop + ul {
    opacity: 1;
    visibility: visible;
}
```

Вызвано тем, что автоматически добавляется элемент dropdown-backdrop после event trigger - элемента и не срабатывает правило #mainMenu.show .nav>li.hover>a + ul

**Comment by bossloper** [comment]
@CatOstrovsky - that does not seem to fix it. The menu sometimes does display correctly, just not always. And it can even display correctly for one dropdown while at the same time not display for another dropdown.

**Comment by 64j** [comment]
@bossloper 
on the developer version there are the same problems?

**Comment by bossloper** [comment]
@64j - yes, latest developer from today.

**Comment by 64j** [comment]
@bossloper 
I previously had the same problem (Samsung Galaxy Alpha).
But after cleaning the cache in the browser Chorme, everything became normal.

**Comment by bossloper** [comment]
@64j - Just tried that on both iPhone Safari and Samsung browser and same issue. It looked like it was going to be ok, but after a second/third try the issue is still there.

**Comment by bossloper** [comment]
@64j - I might be onto something. If I disable the 'ElementsInTree' plugin then the top menus behave correctly on smartphone. No idea why this might be though!

**Comment by 64j** [comment]
@bossloper 
ok
I'll see what the dependency on this plugin is

**Comment by bossloper** [comment]
@64j - it seems to be the bootstrap line here:
https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/elementsintree/assets/txt_content.tpl#L485

If removed then it works correctly.

**Comment by 64j** [comment]
@bossloper 
Check, please

replace to
```css
#mainMenu.show .nav > li.hover > a ~ ul,
```

https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/css/mainmenu.css#L27

**Comment by bossloper** [comment]
Yes, that as fixed it.

**Comment by 64j** [comment]
@bossloper 
Check, please.
Added displacement of the third level of the menu when you click.

**Comment by bossloper** [comment]
@64j - yes working but a couple of issues
1) On mobile there is now no way to get to the level two 'Manage Elements', 'Manager Users' or 'Web Users' pages from the menu.
2) On desktop (Edge browser) the graying of background when menu dropdown is selected does not work. Sometimes it even grays after closing the menu instead of opening it. This is not a problem on desktop with Chrome.
+ Would be nice if clicking anywhere in the grayed background could close the dropdown menu.

**Comment by 64j** [comment]
@bossloper 
1. Okay, I'll think about it.
2. Can this patch affect the behavior in Edge?
https://github.com/evolution-cms/evolution/commit/7090383360100e7dfe3ce38720f1837339ae4ea7

- Clicking anywhere on the background closes the menu. (checked by Samsung)

**Comment by bossloper** [comment]
2. Can this patch affect the behavior in Edge?
- no I tried reverting that patch and still have the same issue on Edge browser. The background sometimes displays after lots of clicking. When it does it is in the correct position, it just does not display very often.

+ Clicking anywhere on the background closes the menu. (checked by Samsung)
- yes looks like it works on my Samsung too, but not always on my iPhone (Safari or Chrome) There seem parts of the background where it will activate close other parts of the background where it does not.

p.s. I will not be able to do any more testing today :-)

**Comment by Nicola1971** [comment]
> ...still have the same issue on Edge browser. The background sometimes displays after lots of clicking. When it does it is in the correct position, it just does not display very often.

I dont have this issue with Edge. Which version of Edge browser?

**Comment by bossloper** [comment]
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063
Just checked again on latest dev and still do not get the modal style grayed/dimmed background to the manager page when I select top menu dropdown items. Yes, cleared browser cache and saved Evo configuration to reset the minified css. Works on Firefox and Crome.

**Comment by Nicola1971** [comment]
this grey background?
![screenshot 2017-11-27 11 45 28](https://user-images.githubusercontent.com/7342798/33263019-89faeb9c-d368-11e7-880c-9a50ff8ae83a.png)

**Comment by Nicola1971** [comment]
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Maybe, You need to update your Edge browser

**Comment by bossloper** [comment]
@Nicola1971 - thanks! Updating Edge fixed the model issue. Wow Edge browser really is messed up, but I think we all know that! :-)

So only issues left on this thread are:
1) On mobile there is now no way to get to the level two 'Manage Elements', 'Manager Users' or 'Web Users' pages from the menu.
2) On iPhone, clicking anywhere on the model background does not 'often' close the dropdown menu.

**Comment by 64j** [comment]
@bossloper 
Yes, I will correct it, so I do not close the question.
I'll make the transition only by the arrows

**Comment by Nicola1971** [comment]
@bossloper Edge is still a nightmare, but this update seems fixed a lot of issue

**Comment by 64j** [comment]
@bossloper 
Check, please.
I maked the transition only by the arrows

**Comment by bossloper** [comment]
@64j - yes that works. Is quite precise on a small screen to click just the arrow vs text. For mobile would it be easier to click for third menu if the arrow was on the right side as it was before?

**Comment by 64j** [comment]
@bossloper 
Did not quite understand.
There is also an arrow on the third level.

![screenshot_2017-12-04-17-30-35](https://user-images.githubusercontent.com/4653189/33557728-1333f2c2-d919-11e7-88f0-3c37cc8be3a4.png)

**Comment by bossloper** [comment]
Ah, yes my configuration did not re-save to refresh the css. I see it like you do now. Working fine.

There seem times on an iPhone when clicking the save on system configuration does not always trigger the save. I think this is because on iPhone the save/cancel buttons do not float correctly and are far over to the right, needing scrolling right to see them:
![thumbnail_image-1](https://user-images.githubusercontent.com/1744687/33558233-3f8255d4-d901-11e7-90a1-fb8265c03198.jpg)

**Comment by 64j** [comment]
@bossloper 
This is a completely different matter.
The layout on the configuration tab did not appear, so the content does not fit in the screen.

Problems with the dropdown menu solved??

**Comment by bossloper** [comment]
Yes dropdown solved.
RE: The layout on the configuration tab did not appear, so the content does not fit in the screen. - Yes, but does not give the same issue on Galaxy, where save cancel icons always show top right even when scrolling right on a wide screen. Shall I open another issue for this?

**Comment by 64j** [comment]
@bossloper 
On the configuration tab, a lot of information.
I think this is not considered a problem. 
This problem is already coding. And in the future will be fixed for mobile devices.

**Comment by bossloper** [comment]
That is not the issue here. Issue is save/cancel do not honour viewport correctly and so are not showing/floating at top right of configuration page viewport.... they do show always at top right on Galaxy phone.

**Comment by 64j** [comment]
@bossloper 
How does this relate to the drop-down menu?

**Comment by bossloper** [comment]
@64j - it does not relate to drop-down. 
I was just asking previously if I should add it as another issue... but you suggested 'this is not considered a problem' - which I do think it is as per my last post of images?

**Comment by 64j** [comment]
@bossloper 
I do not consider this a problem.
It is necessary to change the layout for mobile and everything.

**Comment by bossloper** [comment]
ok, but there are definitely iPhone related clicking and layout issues that to not occur on Galaxy phones...
