### ISSUE TITLE
Question: DocLister & Tags

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#356]
Is it possible to use tags for blogs with DocLister as was previously done with Ditto?
I would like to have posts include tags/key-words in both the listing as well as the main article.
Are there any examples or chunks available?

**Comment by pmfx** [comment]
Create snippet called "resourceTags" to display tags from TV "documentTags" linked to page with DocLister.

```
<?php
$output = '';

if ($tags != '') {
  $tagsArray = explode(',', $tags);

  $i = 0;
  $len = count($tagsArray);

  while(list($key,$val)=each($tagsArray)){
    $tpl = '<a href="[~'.$tagsLanding.'~]?tags='.trim($val).'">'.$val.'</a>';
    
    // remove comma from last item
    if ($i == $len - 1) {
      $output .= $tpl;
    }
    
    // other item
    else {
      $output .= $tpl.', ';
    }
    
    $i++;
  }
}

return $output;
```
Call example:
```
[[resourceTags? &tags=`[*documentTags*]` &tagsLanding=`123`]]
```

Add this in your DocLister call to filter results basing on the value of tags in GET:
```
$params['tvList']='documentTags';

// tags
$get_tags = $_GET['tags'];
if($get_tags != ''){
  $params['filter_delimiter']=',';
  $params['filters']='AND(tv:documentTags:containsOne:'.$get_tags.')';
}

// generate list
$output = $modx->runSnippet('DocLister',$params);
```

**Comment by risingisland** [comment]
@pmfx Thank you for the info.
Unfortunately I am not receiving any output.
Using the demo, id 2, is this correct, or am I not understanding correctly?

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/32754432-94981854-c8c8-11e7-8648-366a62624e65.png)

**Comment by pmfx** [comment]
Your snippet call is inline. You can't just paste my code into it :)
Instead try this (not tested):
1. Remove what you added (my code).
2. Change 
```
&tvList=`image`
```
into

```
&tvList=`image,documentTags`
```
3. Add to parameters
```
&filter_delimiter=`,`
&filters=`AND(tv:documentTags:containsOne:[[$_GET['tags'] ]])`
```

**Comment by dukeRD** [comment]
start inline DocLister template with `@CODE:` 
```
[[DocLister? &tpl=`@CODE: <div class="item">[+placeholder+]</div>` ]]
```

**Comment by risingisland** [comment]
@pmfx 
This line causes a parse error:

>  &filters=`AND(tv:documentTags:containsOne:[[$_GET['tags'] ]])`
