### ISSUE TITLE
Ошибка при клике по ресурсу

### ISSUE THREAD

**Issue by planerr** [evolution-cms/evolution#357]
Версия Evo 1.4
При клике левой кнопкой мыши по любому ресурсу выдается такая ошибка - "Увы. Эта функция ещё не используется данной версией EVO. Logging error: action not set.". Если нажать правой кнопкой по ресурсу, а потом нажать "редактировать", то все ок, ресурс открывается для редактирования.
Это проявляется только на хостинге, локально такой ошибки не возникает.
[скриншот](http://vizitkansk.ru/test/error_modx_evo.jpg)

**Comment by 64j** [comment]
Ошибку не удалось повторить.

Error failed to repeat.

**Comment by Nicola1971** [comment]
maybe a plugin on OnManagerNodePrerender
