### ISSUE TITLE
Chunks included twice at install

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#358]
The chunks "mm_rules" & "header" are installed twice at install, once via "install/assets/chunks/..."
and again from "install/setup.data.sql"

https://github.com/evolution-cms/evolution/blob/be0cea4b8113b0fcfbb2f77f00c3f74c98bb8d84/install/setup.data.sql#L70
https://github.com/evolution-cms/evolution/blob/be0cea4b8113b0fcfbb2f77f00c3f74c98bb8d84/install/setup.data.sql#L74

![chunksx2](https://user-images.githubusercontent.com/6113504/32771515-d1cd5e8a-c91a-11e7-977a-58bf6543eeaa.png)

**Comment by dmi3yy** [comment]
fixed thanks
