### ISSUE TITLE
Extras - Package Manager not installing

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#359]
The extras store no longer seems to work. There are no visible errors, the message indicated 'Installed', but nothing actually installs.
It seems that the downloaded zip files to assets/cache/store used for installing are all empty.
Php5.6 / 5.5.5-10.1.28-MariaDB and any browser.

**Comment by Nicola1971** [comment]
just tested on 2 live sites and 2 local sites - no install issue with Extras Module.
maybe a broken extra? which package have you tried to install?

**Comment by bossloper** [comment]
Any extra, all the same result for me.
mydownloaded files just have the following content:
`<html><body>You are being <a href="https://codeload.github.com/AgelxNash/DocLister/zip/master">redirected</a>.</body></html>`

My server has allow_url_fopen disabled so uses curl. Looks like the follow redirects is not getting set here:
https://github.com/evolution-cms/evolution/blob/develop/assets/modules/store/core.php#L170

**Comment by bossloper** [comment]
Not sure what open_basedir is all about but my server has a value set for that so the condition is not true:
https://github.com/evolution-cms/evolution/blob/develop/assets/modules/store/core.php#L169
If I comment out the condition and allow curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
then it works fine.

**Comment by bossloper** [comment]
I believe the check for open_basedir and safemode are no longer required in php 5.6+ so can be removed? 
https://bugs.php.net/bug.php?id=65646

**Comment by bossloper** [comment]
ref: https://github.com/evolution-cms/evolution/pull/361
