### ISSUE TITLE
Weblogin error / Unable to login

### ISSUE THREAD

**Issue by yanqpl** [evolution-cms/evolution#360]
Hi guys! After last update 1.4.0 RC, i jave a problem with Weblogin snippet. After insert login and password site not redirect to private subpage but only i see blank page with error

`Fatal error: Call to a member function get() on null in /assets/snippets/FormLister/plugin.userHelper.php on line 22`

Everything works fine till now, please help :)

**Comment by 64j** [comment]
@yanqpl 
disable plugin **userHelper**

**Comment by yanqpl** [comment]
Thanks a lot. Work correct now.
