### ISSUE TITLE
Weird referer from Admin site to "site not found"

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#362]
Weird referer found in my custom referer logger: 

    From: manager/index.php?id=4&a=112

    Tried: manager/%3Ci%20class='fa%20fa-file-o'%3E%3C/i%3E

Obviously the HTML block `<i class='fa fa-file-o'></i>` has some influence on evolution cms. I have used Doc Finder but could not find a single occurence of "fa-file-o". It seems not to be in the database.

Can anyone tell me how I can track down this error?

And what is action `a=112` doing?

---

Update: I found `fa-file-o` in those files: 

 - /manager/actions/files.dynamic.php
 - /manager/media/style/default/style.php

**Comment by Deesen** [comment]
`a=112` is used for "executing modules", in your case the module with ID 4.

**Comment by q2apro** [comment]
Then it is the Doc Finder.

**Comment by dmi3yy** [comment]
move to Doc finder
