### ISSUE TITLE
Ditto orderBy not working

### ISSUE THREAD

**Issue by yanqpl** [evolution-cms/evolution#363]
Hi!
I was trying to sort my news by **createdon** but when i change **pub_date** i have too see the news on a list in right place, but Ditto not working good.

Please take a look at screenshot, and look on a date, sorting is wrong
https://screenshots.firefox.com/Wgc3O9Ar8b8wPc4a/lions-quest.org.pl

My snippet call:
`[!Ditto? &parents=`29,21` &depth='0' &hideFolders='1' &display=`30` &tpl=`news-subpage` &dateSource=`pub_date` &dateFormat=`%d - %m - %Y` &orderBy=`pub_date DESC, pub_date DESC` &showInMenuOnly=`1` &paginate=`1`!]`

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/archive/develop.zip
It may have been fixed. Have you tried the latest development package?

**Comment by yanqpl** [comment]
I use a new version Evolution 1.4.0.RC
So maybe my code have some errors?

And also i try with DocLister
```
[[DocLister? 
&parents=`21,29` 
&tpl=`news-subpage`
&dateFormat=`%d - %m - %Y`
&dateSource=`pub_date` 
&sortBy=`pub_date`
&sortDir=`ASC`
&depth=`3`
]]
```
But it works exsactly as Ditto and dont sort documents.

**Comment by yama** [comment]
ok, i'll fix it later.

**Comment by dmi3yy** [comment]
`
[[DocLister? 
&parents=`21,29` 
&tpl=`news-subpage`
&dateFormat=`%d - %m - %Y`
&depth=`3`
]]

`

If use like this all work correct

**Comment by dmi3yy** [comment]
And the same correct work with Ditto if remove  params 

but its not correct for backward compatibility

**Comment by JuliaCherri** [comment]
Привет! В новой версии ditto опечатка.
assets/snippets/ditto/classes/ditto.class.inc.php, строка 809:
`$left_join_tvc = 'LEFT JOIN [+prefx+]site_tmplvar_contentvalues AS tvc ON sc.id = tvc.contentid';`
Должно быть:
`$left_join_tvc = 'LEFT JOIN [+prefix+]site_tmplvar_contentvalues AS tvc ON sc.id = tvc.contentid';`

Опечатка в слове [+prefx+]
