### ISSUE TITLE
Ломаются инлайн-шаблоны Дитто

### ISSUE THREAD

**Issue by Aharito** [evolution-cms/evolution#365]
Обновлялся с **1.0.13** через **1.3.0** до **1.4.0 RC**.

Всё обновилось Ок, но старый Дитто **перестал** работать, писал «Ничего не найдено».

Обновил я Дитто через Экстрас на **последнюю** версию, и пошли ошибки (**сломалась** верстка и т.п.).

Оказалось, что в инлайн-шаблонах Дитто слово `@CODE:` (с двоеточием)заменилось на `@CODE` без двоеточия, то есть вместо например

```
&tpl=`@CODE:<li>[+pagetitle+]</li>`
```

стало
```
`&tpl=`@CODE<li>[+pagetitle+]</li>``
```

Я через БД **вернул** двоеточие — и все стало Ок.

**Comment by dmi3yy** [comment]
Дитто больше нет в ядре, а эту ошибку уже исправили там
