### ISSUE TITLE
Remove FormLister Docs from Evo package

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#366]
Dont know much about Form Lister but, do we really need all FormLister documentation in Evo package?
https://github.com/evolution-cms/evolution/tree/develop/assets/snippets/FormLister/docs
I dont think is useful inside the core 

@dmi3yy  and @Pathologic  Can we move to evo docs?

**Comment by Pathologic** [comment]
Yes. By the way I've added some English docs.

**Comment by Nicola1971** [comment]
@Pathologic thanks for English docs anyway ;)

but i dont think is usefull inside the snippet folder.
for now, better add link to evodoc FormLister documentation in the snippet Information Tab
![download](https://user-images.githubusercontent.com/7342798/32951043-c3b82f38-cba8-11e7-98a4-f0afc13c032b.png)

Should be nice improve the Information tab to include and show documentation .md files from the snippet/plugin/module folder, maybe creating sub tabs using tabpane js

**Comment by pmfx** [comment]
very nice idea @Nicola1971

**Comment by dmi3yy** [comment]
Yes a will add this in docs.evo.im

Отправлено с iPhone

**Comment by Nicola1971** [comment]
> Should be nice improve the Information tab to include and show documentation .md files from the snippet/plugin/module folder, maybe creating sub tabs using tabpane js

i think it can be done: 
- (maybe) adding a new tab documentation 
- a check if extra doc files exist
- format with tabpanes or with an accordian (@64j has added to the theme features)
- use the number prefix (ie: 010_Controllers.md )  to sort the order 
- and use the manager language setting to show the documentation in the right language, if exist (else show english docs)

**Comment by Nicola1971** [comment]
I think we must add for 1.4 to all core snippets and plugins, it will be useful for the transition and to learn new ones (formlister, doclister, Dlcrumbs, DLmenu..)

![download](https://user-images.githubusercontent.com/7342798/33186354-1df22ff0-d089-11e7-84cc-a6f9d7316a66.png)

we have this feature from a long time, but used only with few extras

```
/**
 * FormLister
 *
 * Form processor
 *
 * @category    snippet
 * @version     1.7.11
 * @license     http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)
 * @internal    @modx_category Content
 * @internal    @installset base, sample
 * @author      Pathologic (https://github.com/pathologic)
 * @documentation EN http://docs.evo.im/en/03_extras/formlister.html
 * @documentation RU http://docs.evo.im/03_extras/formlister.html
 * @reportissues https://github.com/Pathologic/FormLister
 */
```

**Comment by pmfx** [comment]
That would be a great and very helpful move.

**Comment by ricardo-lewis** [comment]
I'd vote to have the docs removed for one reason: the Russian files cause nothing but trouble for my operating system and SVN. 

`assets/snippets/FormLister/docs/examples/ru/009_?????????????_???????????_????+????.md
        Illegal byte sequence`

I always have to manually delete the files before they get into SVN and now in the case of 1.4.4 it seems that the macOS unzip command line utility no longer wants to handle those multi byte characters.
