### ISSUE TITLE
TinyMCE4

### ISSUE THREAD

**Issue by jean179** [evolution-cms/evolution#367]
В настройках по умолчанию стоит высота плагина 400 px. Визуальный редактор сворачивается до 3 строк. На нормальном мониторе нужна настройка 700-750 px

**Comment by Nicola1971** [comment]
![download](https://user-images.githubusercontent.com/7342798/33187814-ddd1b542-d094-11e7-9d97-3d864b64111c.png)

does not seems too small.
maybe something wrong with the plugin parameters, try to **Parse DocBlock**

**Comment by Nicola1971** [comment]
@jean179 have you tried to  Parse DocBlock? 
can we close this issue?

**Comment by jean179** [comment]
What is "try to Parse DocBlock"?
I was fix problem: Plugin-TinyMCE4-Configuration-Height-750px.
In big monitor 27" 1920*1080px editor draw normal for me, but in my notebook so big.

If I change  Plugin-TinyMCE4-Configuration-Height-100% in big monitor that piture
![2017-11-29_19-51-47](https://user-images.githubusercontent.com/4946765/33387620-cd82a9e0-d53e-11e7-82ce-0f2c7b82c5e7.png)

**Comment by Nicola1971** [comment]
this my monitor at 1920*1080px -  TinyMCE4 height:400px
![download](https://user-images.githubusercontent.com/7342798/33389121-23c5d42e-d532-11e7-9863-996f0fe39a6d.png)

**Comment by bossloper** [comment]
Personally I would leave it at 400px. On a low res screen (e.g. iPad) it already fills the vertical space available. Instead make sure you have the TinyMCE 'Fullscreen' toolbar button, then it is just a quick toggle in the editor to use the TinyMCE 'Fullscreen' toolbar button if you need more editing space.
![untitled](https://user-images.githubusercontent.com/1744687/33389972-6d6a90f2-d52c-11e7-9036-b8502e1b362d.png)

**Comment by jean179** [comment]
Yes, 400 or 100% is the same. But in the old skin, the editor's height was excellent and very comfortable. I would like the same convenience.

**Comment by Pathologic** [comment]
According to [Documentation](https://www.tinymce.com/docs/configure/editor-appearance/#height) height value has to be set just as number, without px or %. 400px or 100% don't work, but 400 does.

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/issues/367#issuecomment-348224139 is a solution.
