### ISSUE TITLE
Проблема со скопированными сниппетами

### ISSUE THREAD

**Issue by jean179** [evolution-cms/evolution#368]
Скопировал сниппет aDate и назначил ему другое имя MyDate. Когда стал править один, после сохранения в другом ровно тоже самое. Меню aDate, сохраняю, смотрю MyDate = сниппет изменился.

Решил проблему удалением полностью сниппета и созданием его заново.. Тогда дублирование прекратились

**Comment by dmi3yy** [comment]
На второй вкладке есть привязка к файлу 
Вот оно не копируется и по факту разные сниппеты но содержимое одинаковое

Отправлено с iPhone

**Comment by bossloper** [comment]
can close?

**Comment by Pathologic** [comment]
Я думаю, что это поведение исправимо.
