### ISSUE TITLE
TinyMCE4(OnLoadWebDocument) error

### ISSUE THREAD

**Issue by Aharito** [evolution-cms/evolution#37]
Поставил макс. уровень обнаружения ошибок, пхп 5.6.19, modx 1.3.0b
Появилась такая ошибка, не знаю, важна она или нет, судить вам.

![image](https://user-images.githubusercontent.com/6253807/28239058-cfff2158-698c-11e7-8a88-80ef9a6f80e2.png)

**Comment by dmi3yy** [comment]
Fixed https://github.com/evolution-cms/evolution/commit/cd35be244ded2a1e56ecff95b869b8d0269ec90a
