### ISSUE TITLE
Баги в верстке админки

### ISSUE THREAD

**Issue by Typodin** [evolution-cms/evolution#373]
Монитор 29", разрешение 2560*1920, масштабирование 100%

http://prntscr.com/hd7s3g
http://prntscr.com/hd7unz

**Comment by 64j** [comment]
@Typodin 
Какая версия Ево?
В последних версиях всё нормально.
Монитор 42 дюйма, 3840x2160.

![image](https://user-images.githubusercontent.com/4653189/36354229-286e7716-14e2-11e8-8d42-ba39afa3d8d9.png)
![image](https://user-images.githubusercontent.com/4653189/36354232-35b0d464-14e2-11e8-9426-a2613d40be7d.png)
