### ISSUE TITLE
Custom Manager Theme is not loading

### ISSUE THREAD

**Issue by eire69k** [evolution-cms/evolution#374]
After installing the new Update of Evolution 1.4.0.RC2, my Custom Manager Theme that I made for one of my customer is not working any longer. Only the manager login screen is still sown up.
The [(manager_theme)] is selected but the url to the style.css is still linked to the „default“ manager theme folder.

**Comment by dmi3yy** [comment]
I write about this. 
all old theme now work from 1.3.0 

we do many work with manager theme

**Comment by eire69k** [comment]
спасибо!!!! Many Thanx!
