### ISSUE TITLE
Вложенные сниппеты постоянно дают ошибку в протокол событий

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#376]
Однако работают снаружи. Вложение кэшированного сниппета в кэшированный сниппет в шаблоне выдает в протоколе событий предупреждение evalSnippets parse error

Например такой вызов

```
[[if? &is=`[*image*]:!empty` &then=`
    <div class="qodef-tour-gallery-item">
        <a href="[*image*]" data-rel="prettyPhoto[gallery_excerpt_pretty_photo]">
            <img width="550" height="550" src="[[phpthumb? &input=`[*image*]` &options=`w=550,h=550,zc=1`]]" class="attachment-getaway_qodef_square size-getaway_qodef_square" alt="a" sizes="(max-width: 550px) 100vw, 550px" />
        </a>
    </div>
`]]
```
срабатывает на сайте, но в админке видим предупреждение evalSnippets parse error следующего вида

```
[[if? &is=`:!empty` &then=`
 a
`]]
```

Раньше вроде такие конструкции без проблем отрабатывали.

**Comment by webber12** [comment]
Аналогично при вложении в [[if]] других сниппетов - [[aDate]], [[DocInfo]] - т.е. проблема не в конкретном сниппете, а во вложенности друг в друга, что в чанках, что в шаблоне.

**Comment by dmi3yy** [comment]
Они работают. В rc2 поправили же ж

Отправлено с iPhone

**Comment by webber12** [comment]
Насколько я понял вот это решение - https://github.com/yama/evolution/commit/ebe2dfba53a494476834d773cc29a558d12eb07b - просто убрать запись из логов? :) А то пришлось все переделать на один сниппет в самой шапке шаблона, в котором все проверки делать и вставлять в шаблон уже готовыми плейсхолдерами, чтобы эти ошибки не сыпались в протоколе.

**Comment by dmi3yy** [comment]
Да все верно. 

Отправлено с iPhone

**Comment by webber12** [comment]
Все равно откуда-то эта ошибка иногда вываливается. Редко, но бывает по неустановленным причинам. Может в каких-то еще файлах есть этот evalSnippets parse error? :) Или при каких-то условиях может срабатывать $this->debug?

**Comment by dmi3yy** [comment]
больше не ловил багу после отключения лога от Ямы
