### ISSUE TITLE
Верстка в KCfinder

### ISSUE THREAD

**Issue by warchild1** [evolution-cms/evolution#378]
Сейчас вот так:
![s11](https://user-images.githubusercontent.com/17488086/33116324-ec21951c-cf96-11e7-812c-a08a4436b0d0.png)
Должно быть вот так:
![s12](https://user-images.githubusercontent.com/17488086/33116328-eed16a80-cf96-11e7-8f49-fb7bf8680fc0.png)

**Comment by Nicola1971** [comment]
don't see this issue 
![download](https://user-images.githubusercontent.com/7342798/33185416-bea5f320-d082-11e7-919a-cb7892ff7102.png)

**Comment by Nicola1971** [comment]
1.4 RC1 or 1.4 RC2?

i have in RC1 , but not in RC2

**Comment by Nicola1971** [comment]
Upgrade your 1.4 RC ;)
was fixed by @64j 6 days ago

https://github.com/evolution-cms/evolution/issues/353

https://github.com/evolution-cms/evolution/commit/78bd9c44bf4bbd3f6eaa9d38368dbc18f9a1e2f5
