### ISSUE TITLE
Пользователь с усеченной ролью не может открыть модуль

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#382]
1.4.RC2
На 1.4 RC1 были установлены такие права:
![2017-11-27 13 37 27](https://user-images.githubusercontent.com/5689796/33262679-279b2e7a-d378-11e7-9915-4eb01de19039.jpg)
И пользователь мог открыть модули

На 1.4 RC2 кнопка "модули" есть, но она не кликается.
Не кеш, одинаково во всех браузерах
![2017-11-27 13 36 47](https://user-images.githubusercontent.com/5689796/33262710-50520e2e-d378-11e7-9cf8-5d417e8aaa1b.jpg)

Права доступа у нужных модулей "Все группы"
![2017-11-27 13 40 25](https://user-images.githubusercontent.com/5689796/33262802-9ea13f0a-d378-11e7-9c11-7758c5e5fdca.jpg)

Если выставить
"Создание новых модулей " и "Редактирование модулей" то можно только открыть подменю 
"Управление модулями"
![2017-11-27 13 42 33](https://user-images.githubusercontent.com/5689796/33262922-f8fe2e90-d378-11e7-8aec-623d57fbd76e.jpg)
сами модули только в таблице редактирования, но не в меню

**Comment by sashabeep** [comment]
UPD: Никто, кроме администраторов не видит список модулей в выпадающем меню

**Comment by sashabeep** [comment]
UPD: Разделение модулей по группам доступа не работает

**Comment by bossloper** [comment]
Struggling to translate some of it, but if I follow what you are describing I just did a test creating a manager with 'publisher' role.
Created a new permission 'security group' and assigned that test manager to the group.
Then set 'access permissions' for the module to the new security group, all others set to admin group. Test user can see that module only and has no access to manage modules:
![untitled](https://user-images.githubusercontent.com/1744687/33264388-3bb54214-d365-11e7-8f5b-5e9bf6775374.png)

**Comment by sashabeep** [comment]
@bossloper too many rights for this particular user with role "Publisher"
Rolled down to 1.4.0 RC1 where permissions work as expected

**Comment by sashabeep** [comment]
Еще неплохо было бы модули, невидимые менеджеру вообще скрывать из списка, а не просто давать предупреждение, что для запуска недостаточно прав

**Comment by bossloper** [comment]
too many rights for this particular user with role "Publisher"
- I set my publisher role to the same as your screenshot and it still worked for me (though I am on latest dev)

Еще неплохо было бы модули, невидимые менеджеру вообще скрывать из списка, а не просто давать предупреждение, что для запуска недостаточно прав
(It would also be nice to have modules that are not visible to the manager at all from the list, and not just give a warning that there is not enough rights to run)
- that is already possible using access permissions as I described above. E.g. my 'doc manager' and 'extras' are hidden from the test account in my previous screenshot
For example set the security group for a module to 'admin', then if the manager only has 'run module' role and is not in the admin permission group it will not list in the dropdown menu:
![untitled](https://user-images.githubusercontent.com/1744687/33266643-6016979e-d36e-11e7-8d51-3e612264e8da.png)

**Comment by sashabeep** [comment]
@bossloper sadly, i cannot swith this project to dev channel, will try later this week on the blank project

**Comment by bossloper** [comment]
@sashabeep - I just tried 1.4.0RC2 and I see the same issue as you described. It does all seem to be fixed in the latest dev release.

**Comment by dmi3yy** [comment]
Check on dev version 
only run module active for role http://take.ms/mWyli
