### ISSUE TITLE
at install some error 140RC2

### ISSUE THREAD

**Issue by Cipa** [evolution-cms/evolution#383]
<img width="1003" alt="screen shot 2017-11-27 at 8 34 34 am" src="https://user-images.githubusercontent.com/293377/33277597-e31d6a6c-d34d-11e7-9559-dd24f0102c91.png">

**Comment by Cipa** [comment]
<img width="975" alt="screen shot 2017-11-27 at 8 38 47 am" src="https://user-images.githubusercontent.com/293377/33277790-723f1f4c-d34e-11e7-9c48-aa3932da1194.png">

**Comment by Cipa** [comment]
Maybe a fix although I am not entire sure what that code does
```
if (is_array($preset[8])) {
            $ph['class'] = !in_array('sample', $preset[8]) ? 'toggle' : 'toggle demo';
        }else{
            $ph['class'] = 'toggle demo';
        }

```

**Comment by dmi3yy** [comment]
yes it will be work thanks
