### ISSUE TITLE
DocLister vs Ditto - DocLister showing hidden content

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#385]
I've tried to search, so I apologise if this has been asked and answered.

I changed over to DocLister sometime ago but didn't give it enough attention.  I've noticed that DocLister displays a lot more articles than Ditto.  The extra articles should not be seen as they are restricted.  The user cannot access them.  I would have thought that DocLister should not display articles that are not in the users permissions to see?

Any help or explanation would be appreciated.

**Comment by BBloke** [comment]
Here's two screenshots to show what I mean.  
![dittolist_nologin](https://user-images.githubusercontent.com/24464015/33309916-bf56b352-d417-11e7-969a-0a9b807a7df0.png)

![doclister_nologin](https://user-images.githubusercontent.com/24464015/33309919-c31cdea8-d417-11e7-840b-6a7b4b51d61a.png)

**Comment by fourroses666** [comment]
Might be handy to post your snippet calls.
https://github.com/Nicola1971/Ditto-to-DocLister-Reference-Tables

Maybe display=`4` or total=`4`

**Comment by BBloke** [comment]
Good Idea.

`[[DocLister? &amp;parents=`114,145,432` &amp;display=`20` &amp;dateFormat=`%d-%m-%Y %H:%M` &amp;summary=`len:500` &amp;tvList=`2ColumnSpan`&amp;commentschunk=`NewsComments` &amp;tpl=`dl_news_home` &amp;paginate=`0` &amp;alwaysshow=`1` &amp;orderBy=`createdon DESC` &amp;emptyText=`You must be logged in to view News` &amp;noResults=`You must be logged into view News.` ]]`

**Comment by Pathologic** [comment]
If you want to take user permissions into account, then use the according filter:
```
&filters=`private`
```

**Comment by BBloke** [comment]
Argh! I've been through the params over the last few days and completely missed it.  I think it is a little too easy to overlook to be honest.  I would think the default would always be to private filter the results but maybe a little more information on the documentation may be worth it.

Thanks @Pathologic. That's sorted my trouble out.
