### ISSUE TITLE
Upgrade latest develop

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#386]
> Unknown column 'manage_metatags' in 'field list'tijdens de uitvoering van de SQL-statementREPLACE INTO `evo_user_roles` (id,name,description,frames,home,view_document,new_document,save_document,publish_document,delete_document,empty_trash,action_ok,logout,help,messages,new_user,edit_user,logs,edit_parser,save_parser,edit_template,settings,credits,new_template,save_template,delete_template,edit_snippet,new_snippet,save_snippet,delete_snippet,edit_chunk,new_chunk,save_chunk,delete_chunk,empty_cache,edit_document,change_password,error_dialog,about,file_manager,save_user,delete_user,save_password,edit_role,save_role,delete_role,new_role,access_permissions,bk_manager,new_plugin,edit_plugin,save_plugin,delete_plugin,new_module,edit_module,save_module,exec_module,delete_module,view_eventlog,delete_eventlog,manage_metatags,edit_doc_metatags,new_web_user,edit_web_user,save_web_user,delete_web_user,web_access_permissions,view_unpublished,import_static,export_static,remove_locks,assets_images,assets_files,change_resourcetype,display_locks,category_manager) VALUES (1, 'Administrator', 'Site administrators have full access to all functions',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1).

> Unknown column 'manage_metatags' in 'field list'tijdens de uitvoering van de SQL-statementUPDATE `evo_user_roles` SET bk_manager=1, new_plugin=1, edit_plugin=1, save_plugin=1, delete_plugin=1, new_module=1, edit_module=1, save_module=1, delete_module=1, exec_module=1, view_eventlog = 1, delete_eventlog = 1, manage_metatags = 1, edit_doc_metatags = 1, new_web_user = 1, edit_web_user = 1, save_web_user = 1, delete_web_user = 1, new_chunk = 1, edit_chunk = 1, save_chunk = 1, delete_chunk = 1, web_access_permissions = 1, view_unpublished = 1, publish_document = 1, import_static = 1, export_static = 1, empty_trash = 1, remove_locks = 1, display_locks = 1, assets_images = 1, assets_files = 1, change_resourcetype = 1 WHERE `id`=1.

**Comment by Nicola1971** [comment]
upgrading from? previous dev or older version?

**Comment by fourroses666** [comment]
Hmm other one didn't had any issues. I'm not sure what version it had. 1.3.x I think.

**Comment by dmi3yy** [comment]
It will be in 1.4.0 first dev   we depricate old columns in sql
