### ISSUE TITLE
SHK + Robokassa

### ISSUE THREAD

**Issue by jorjik** [evolution-cms/evolution#387]
для файла - paykeeper.inc.php в строке 395 походу надо закоментить
`$payTest='true' ? $h_inputs.= '<input type="hidden" name="IsTest" value="1" />' : '';`
или проверить условие (кажется там должно быть ==)

**Comment by Nicola1971** [comment]
if is related to ShopKeeper extra, please open an issue here:
https://github.com/extras-evolution/Shopkeeper/issues
