### ISSUE TITLE
Different menu after upgrade and after log out and in

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#388]
I've updated to 1.4.0 RC2 and upon completion everything with a logged in user looks good.

![userloggedin_without_logging_out_140rc2](https://user-images.githubusercontent.com/24464015/33310474-a2b6a138-d419-11e7-9382-2777582689ee.png)

But after logging out and logging in again the menu is different.

![userloggedin_after_logging_out_140rc2](https://user-images.githubusercontent.com/24464015/33310484-ac4917f8-d419-11e7-8551-f4421f3f786c.png)

Upon first login the screen is blank. Upon refresh I get the content.

As far as the home screen looks I cannot click on the links which are restricted pages which are within my web permissions.  All links are DocLister provided.

The wayfinder menu is also incorrect.  It's as though I'm actually not logged in.

**Comment by BBloke** [comment]
Looking into this a little further.  There seems to be something between logging in on the provided template using WebLogin and my template page using WebLoginPE.

Clearing cookies and logging in via the default template gives me what I need although after log in the home page is blank.

Using my login page with webloginpe gives the same blank home page but no full menu as though I'm not logged in at all.

**Comment by pmfx** [comment]
Check if plugin "userHelper" exists and if it's active. If yes, try to disable it.

**Comment by BBloke** [comment]
Found this in my php error. userHelper.

[28-Nov-2017 09:02:59 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in \assets\snippets\FormLister\plugin.userHelper.php:22
Stack trace:
#0 \manager\includes\document.parser.class.inc.php(1355) : eval()'d code(14): require()
#1 \manager\includes\document.parser.class.inc.php(1355): eval()
#2 \manager\includes\document.parser.class.inc.php(4540): DocumentParser->evalPlugin('/**\n * userHelp...', Array)
#3 \assets\snippets\webloginpe\webloginpe.class.php(3043): DocumentParser->invokeEvent('OnWebLogin', Array)
#4 \assets\snippets\webloginpe\webloginpe.class.php(225): WebLoginPE->OnWebLogin()
#5 \manager\includes\document.parser.class.inc.php(1397) : eval()'d code(334): WebLoginPE->Login('simple', Array)
#6 \manager\includes\document.parser.class.inc.php(1397): eval()
#7 \manager\includ in \assets\snippets\FormLister\plugin.userHelper.php on line 22

I've disabled userHelper Plugin and things have returned to normal.

**Comment by Nicola1971** [comment]
userHelper causes problems with many sites. 
Actually i always remove from the install list option

**Comment by BBloke** [comment]
I'll close it. 👍
