### ISSUE TITLE
Быстрое создание/редактирование чанков в шаблоне

### ISSUE THREAD

**Issue by sergey-yabloncev** [evolution-cms/evolution#389]
ПКМ в шаблоне сайта на чанке {{chunkName &param=`value`}} определяется не верное значение https://yadi.sk/i/-Qg70XYV3Q8MnV

**Comment by intersel** [comment]
could you please write your report in english?

**Comment by dmi3yy** [comment]
Quickly create / edit chunks in a template
incorrect work chunk with &params with context menu

**Comment by scorN17** [comment]
https://yadi.sk/i/_AQgxwTA3QqrRs

**Comment by dmi3yy** [comment]
Done
