### ISSUE TITLE
Close Issues When Solved

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#39]
The issues list keeps growing for no reason - when an issue is resolved, please close it yourself.

Placing this extra work on the admins costs time, their time is better spent resolving issues and not closing the resolved posts

The editor has a button "Close Issue", all you have to do is press the button and the issue will be closed.

https://github.com/modxcms/evolution/issues/1213

**Comment by bossloper** [comment]
close lol ?!
