### ISSUE TITLE
Ошибка при сохранении плагинов без выбора системного события

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#390]
Warning: Invalid argument supplied for foreach() in /home/user556/www/krugosvetka.by/_manager/processors/save_plugin.processor.php on line 179

Сам плагин сохраняется, понятно, что и события должны быть у плагина отмечены. Но все-таки если они не отмечены, то эта надпись постоянно пугает даже меня, не говоря уж про какого-нибудь новичка, который и запаниковать может :)
Лучше бы заиметь какое-то предупреждение вроде "вы не выбрали для своего плагина ни одного системного события и он скорее всего не будет работать так, как это задумано", чем эта ошибка foreach :)

**Comment by dukeRD** [comment]
подтверждаю, тоже встречал такое на на паре сайтов с 1.4RC2
У меня такое было на локальном openserver, те же сайты на таймвебе ошибки не выдавали.

**Comment by webber12** [comment]
Скорее всего к моменту переноса на таймвеб у плагинов уже были заполнены системные события :) Чует мое сердце, что обойти пытаются именно их и если ни один чекбокс не отмечен, то и обходить нечего, а значит Invalid argument supplied for foreach()
:)

**Comment by dukeRD** [comment]
не, я специально создал новый плагин для проверки. 
![2017-11-29_12-32-23](https://user-images.githubusercontent.com/419459/33378540-3371b8ae-d526-11e7-91f5-7b9a9c115dae.png) на опенсервере ошибка, на таймвебе просто создаётся плагин, сайты одинаковы

**Comment by 64j** [comment]
@dukeRD 
ошибка есть, что вы мучаетесь.
ошибка сохранения с пустыми событиями!

**Comment by webber12** [comment]
А кто сказал, что мы мучаемся? Сказали сюда ошибки писать, а не размазывать по форумам - вот и пишем :)))
