### ISSUE TITLE
not clear cache on edit documents

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#391]
for this we have  check in all docs if we dont need clear cache need unset checkbock 
now all time  not cleared cache if edot docs. its incorrect

**Comment by scorN17** [comment]
В чем баг подскажите подробнее?
Сейчас состояние галочки Очистить кэш в базу не сохраняется, да?

**Comment by dmi3yy** [comment]
Баг в том что что бы ты не делал в админке после нужно чистить кеш. К примеру изменил шаблон и все раньше это чистило кеш. Сейчас этот кеш не чистится приходиться заходить и кликать очистить кешь в ручную. 
в 1.3.6 работает еще как нужно. Это нужно найти и вернуть назад один из Комитов Ямы

**Comment by scorN17** [comment]
@dmi3yy ошибка не воспроизводится.
Установил из ветки develop. Делаю правки в шаблоне, в ресурсе - кэш чистится.

**Comment by Nicola1971** [comment]
same. I can not replicate this error. 
maybe did not understand the issue

**Comment by dmi3yy** [comment]
maybe already fixed in dev version
