### ISSUE TITLE
Is english the common language to share our reports? or not anymore?

### ISSUE THREAD

**Issue by intersel** [evolution-cms/evolution#393]
As 1 report out of 2 seems to be written in another language than english...
Or perhaps I'm at the wrong place for Modx Evo and the followup?
So, could you please tell me where is the international one?

**Comment by dmi3yy** [comment]
You in correct place. 

But it is better to get a report in any language than not to get at all, 
so it was decided to write in Russian, too, since the Russian-speaking community is the largest on eve, I when have time translate issues into English.

**Comment by dmi3yy** [comment]
now have some work but in future plan start new site evo.im with 2 langs and with actual info about Evo

**Comment by intersel** [comment]
I'm sure that it's always a good idea to include people and english is the easiest way to share ideas with the planet...
and so writing in russian actually exclude pleople that could or want to help...
Whatever the importance of the russian community or of any other community... I was unaware that Modx should become a russian project... or a whatever country project...

**Comment by 64j** [comment]
@intersel 
If people do not know English, can not they now ask in their own language?

Use google translate

**Comment by Nicola1971** [comment]
people must write in english . if they dont know - can use google translator

**Comment by Nicola1971** [comment]
i think we need a forum for multilanguage issues, anyway we have the **Slack channel** and **Telegram group** (in russian)

**git issues must be in english**.

**Comment by intersel** [comment]
@64j <юмор>c'est vrai... pourquoi faire un effort pour communiquer dans une langue commune?
d'ailleurs, je n'ai qu'à discuter qu'avec des français pour résoudre mes problèmes modx... 
Ras le bol de l'uniformisation des langues vers l'anglais...
Vive la diversité :-) mais seulement entre soi ;-)
</юмор>
Well... not sure it's a good way to share ideas and fun... and the english translation of my french words is quite... well... inacurate in the meaning... could be fun perhaps to read it in russian... !?
это правильно ... зачем прилагать усилия для общения на общем языке?
кроме того, мне нужно только обсудить с французским языком решение моих проблем modx ...
Чаша стандартизации языков на английском языке ...
Да здравствует разнообразие :-) но только между вами ;-)I

**Comment by 64j** [comment]
@intersel 
Malheureusement, je ne connais pas la langue française comme vous.
Ma langue maternelle, le russe et je ne demande pas à tout le monde, traduit dans ma langue, ce qu'ils ont écrit.

Si vous voulez comprendre le problème, vous allez certainement traduire, et si non, alors vous n'en avez pas besoin)

**Comment by 64j** [comment]
@intersel 
How often do you answer questions on github and are looking for solutions to problems?

À quelle fréquence répondez-vous aux questions sur github et cherchez-vous des solutions aux problèmes?

**Comment by bossloper** [comment]
Keeping as much of github in a single language (or at the very least with the translation paste in) helps when searching issues to make sure I do not double post or in looking for a solution. If languages are mixed this is more difficult.

**Comment by 64j** [comment]
@bossloper 
Do not say nonsense.
People do not want to look for anything, they just eat everything.
How many times already closed the same questions.
And it even happened that the questions were from the same people, and all the questions were in English.

**Comment by Nicola1971** [comment]
@64j  not all people do the same :)

I always use the search for issues and @bossloper and lot of other people use github in the right way.

but, there are people who do not want to translate their questions, do not want to search before ask, do not help to test a release
 ... we know.

**Comment by 64j** [comment]
@Nicola1971 
(as an example)
People do not want to seek anything and read

https://github.com/evolution-cms/evolution/issues/245
https://github.com/evolution-cms/evolution/issues/255

**Comment by Nicola1971** [comment]
:smile:

again, we need a forum. 

- github is not the place for basic questions. is for issues (maybe verified issues)
- Slack and Telegram does not have a good search and no archive
- we cant create a documentation for any stupid questions on evo docs :smile:

**Comment by dmi3yy** [comment]
I think need translate all into english and Add Coments 
http://docs.evo.im/en/

**Comment by Nicola1971** [comment]
@dmi3yy  doc.evo is great for documentation , but not for dummy user questions  :smile: 
the same for github

**Comment by dmi3yy** [comment]
Then oк like modx.im  or real forum  use for this 
but many info on russian and hove all this translate ?:(

**Comment by 64j** [comment]
@intersel 
Often questions on github are addressed to developers or active participants.
But why is the question in Russian, did not like you.

**Comment by 64j** [comment]
@intersel 
And if you want to help, here's a real question for you, from a Russian man written in English.
Can you figure it out?

https://github.com/evolution-cms/evolution/issues/394

**Comment by intersel** [comment]
actually I dont see your point...
Let's close the issue as it appears there is no issue and let's continue to talk in russian as it helps you to solve the modx bugs... as it appears too that you're the only developer on earth to do such a job...
Anyway... thanks for your investment...

**Comment by 64j** [comment]
@intersel 
There are more than 7.5 billion people in the world, and not all speak English.
Not even many people remember Esperanto.
Be lenient to those who do not know English, and can not translate their messages.

**Comment by Nicola1971** [comment]
> can not translate their messages.

@64j they cant access to google translator?  :smile:

I understand is hard and boring to translate the full issue description, but they can translate the **title**. https://github.com/evolution-cms/evolution/issues/270

I often use google translator, because my english is very bad and.. dont talk me about other lazy countries :  I'm **50% italian** and **50% greek**, so a mix of **the most lazy people around the world**!  :smile:  :smile:

**Comment by bossloper** [comment]
...that was all I was suggesting too, nothing more, Google translator seems to have got a bit better, or at least provides less amusing translation attempts! Not expecting those that cannot speak English to figure it out with their language teacher! 😄

**Comment by 64j** [comment]
@Nicola1971 
And this should ask a question, to the one who created this topic.
He himself did not look for such a theme.

**Comment by Nicola1971** [comment]
i understand both points of view, but we need use one language for issues titles, also for people that knows only their native language.

just another example:

When i access to modx.im or modx.jp or in any language sub forum on modx.com,  i can automatically translate the full page and titles and choose what i want to read:

With a mixed language, like now on github i cant use this browser function and i need translate titles, one by one.

**Comment by intersel** [comment]
Why not continuing this exciting discussion on https://forums.modx.com/thread/103247/guidelines-for-reporting-issues-on-evo-github... 
I called it "Guidelines for reporting issues on evo github" ... Actually, that's the real object of this discussion...

**Comment by pmfx** [comment]
+1 for English titles. Description can be any language, but lets have all titles in English. I think that would improve our daily GitHub experience as a worldwide community ;)

**Comment by dmi3yy** [comment]
I think let them write at least in what language they write
because many did not write just because they do not know the language.
I or who knows Russian will just follow and translate the headlines :)
it's faster and more convenient than writing out the tasks from the chat

**Comment by Nicola1971** [comment]
@dmi3yy if you want you can do, but I think you have better things to do. ;)

I don't see as a **Russian issue** - we are working on an **international project**
 #### if other people starts to open issue in their native language? Who translate them?

Actually the team: 
- develop new features on evo
- test bugs
- fix bugs
- Help questions on github
- work on extras
- work on docs

And we still need to do the evo site and extras site

**we need a community site**, like modx.im (works nice for me) or a forum **as a filter before github**

## do you have an issue?

1) post the issue on the community site in your language, if you need
2) the community can test and verify the issue
3) if the issue is verified you can open an issue on github in english
4) if you don't know English, don't worry - just ask to the community team to open an issue on github (in English)

### The results:

1) no more false issues
2) no more dummy questions on github
3) less work for developers, because they only need to fix real issues
4) more informations about the issue for devs
5) no more multilanguage issues (..)
6) no more 200000 issues on github that looks like our cms is the most bugged cms in the world :smile:

**Comment by dmi3yy** [comment]
What better russian issue? with real bug ? or no issue? 

And we are need basic template for issue like in REVO

**Comment by Nicola1971** [comment]
@dmi3yy of course, Russian (or any other language) issue. NOW.

Again, is not something about Russian, is about any native language.

I see a bigger future for evo :) and I'm talking about next steps for evo.

**Comment by dmi3yy** [comment]
Yep, we need do rules for this.

**Comment by 0test** [comment]
if i found a bug and wrote it in my language, would it be better than if I had not written it?

**Comment by Nicola1971** [comment]
@0test and I tried to help you in Russian and English , using google translator  :)  https://github.com/evolution-cms/evolution/issues/337

you wrote the issue in Russian
but... you can write here in english  :smile:

**Comment by 0test** [comment]
I won't do it again =)
