### ISSUE TITLE
Cookies mess in startCMSSession

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#396]
There's no need to create session cookie manually because session_start() call does it, cookie parameters can be passed to session_start() as well.

**Comment by dmi3yy** [comment]
А что тут не так ? 

http://take.ms/uyPrv

**Comment by Pathologic** [comment]
То, что кука отправляется в session_start(), туда и нужно передавать параметры, а не создавать вручную после. При этом в session_start() создается с /, потом еще одна создается с MODX_BASE_URL - ты же сам показывал глюки сессии на сайте, который в папку установлен.
