### ISSUE TITLE
Multiple admin sessions

### ISSUE THREAD

**Issue by 0test** [evolution-cms/evolution#399]
> Information: Multiple active user sessions (total 7) found for user admin.
Evolution 1.4.0.RC2

**Comment by Fr3ddy7** [comment]
авторизация на сайте есть? был раньше конфликт

**Comment by leonie12** [comment]
Same here.

**Comment by 0test** [comment]
> авторизация на сайте есть? был раньше конфликт
Да. Скорей всего в ней и проблема.
