### ISSUE TITLE
Create backup of core files on Updater plugin

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#40]
https://github.com/modxcms/evolution/issues/1215

**Comment by AgelxNash** [comment]
What is the full list of necessary files? Only the **/manager/** folder or anything else?

**Comment by AgelxNash** [comment]
@Nicola1971 Where can I see this module?

**Comment by Nicola1971** [comment]
https://github.com/Nicola1971/EvoBackup
I want to improve with cloud storage (dropbox, googledrive..)
 
check the autobackup snippet too - works with the same template method (light, medium, full)
https://github.com/Nicola1971/AutoEvoBackup

you can download both from extras module

there is a basic scheduler too (very alpha)
https://github.com/Nicola1971/JobScheduler

**Comment by Nicola1971** [comment]
the module is always updated to work with latest EVO, because it is a fixed component of my live sites and my development tools

for now I think we can close. In a future, we could think of improving the internal backup system in a similar way and connecting it to the update system
