### ISSUE TITLE
Upgrade to 1.2.1 and when editing resources I get an error about mm_widget_showimagetvthumbs() 

### ISSUE THREAD

**Issue by Tourist4Life** [evolution-cms/evolution#402]
I'm getting the below error the first time I edit a resource and then once I try again it goes away.....but alas it keeps coming back.

`Fatal error: Call to undefined function mm_widget_showimagetvthumbs() in /home/**********/public_html/assets/plugins/managermanager/mm.inc.php(192) : eval()'d code on line 7`

**Comment by pmfx** [comment]
I'm just guessing, but maybe try to edit you mm_rules chunk and change 
**mm_widget_showimagetvthumbs** 
to
 **mm_widget_showimagetvs**

**Comment by Tourist4Life** [comment]
thanks @pmfx !  i think that's done it.....I'm still wondering why out of the box this is an issue?
