### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#403]
Font Awesome 5 is out
https://fontawesome.com/

the free set
https://fontawesome.com/icons?d=gallery&m=free

Very cool but not easy to update from v4 :
base class is no more "fa", but
fas = solid
fal = light
far = regular
fab = brand
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by bossloper** [comment]
Sounds like even more reason for the icon standardisation https://github.com/evolution-cms/evolution/issues/349
