### ISSUE TITLE
Two errors with PHP 7.2: count() and sizeof()

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#404]
Has to be fixed for PHP 7.2: 

	Error : count(): Parameter must be an array or an object that implements Countable
	File	/includes/document.parser.class.inc.php
	Line	4691
	Source	if (count($idnames) == 0) {

	Error : sizeof(): Parameter must be an array or an object that implements Countable
	File	/includes/document.parser.class.inc.php(1832) : eval()'d code
	Line	9

Thanks.

**Comment by user83743** [comment]
no. the count() issue is still there. i upgraded to evo 1.4.5 on php 7.2 and the contact form is dead and displaying:

Error : count(): Parameter must be an array or an object that implements Countable
Error information
ErrorType[num]	WARNING[2]
File	/home/xxxxxxxxxxxx/public_html/xxxxxxxxxxxxx.com/assets/snippets/eform/eform.inc.php
Line	700
Source	$lastitems[count($lastitems)]="[+$name+]";

Backtrace
DocumentParser->executeParser()
index.php on line 139
DocumentParser->prepareResponse()
manager/includes/document.parser.class.inc.php on line 2862
DocumentParser->parseDocumentSource(string $var1)
manager/includes/document.parser.class.inc.php on line 2971
DocumentParser->evalSnippets(string $var1)
manager/includes/document.parser.class.inc.php on line 2713
DocumentParser->_get_snip_result(string $var1)
manager/includes/document.parser.class.inc.php on line 2025
DocumentParser->evalSnippet(string $var1, array $var2)
manager/includes/document.parser.class.inc.php on line 2113
eval()
manager/includes/document.parser.class.inc.php on line 1962
require(string $var1)
manager/includes/document.parser.class.inc.php(1962) : eval()'d code on line 1
eForm(DocumentParser $var1, array $var2)
assets/snippets/eform/snippet.eform.php on line 114
formMerge(string $var1, array $var2)
assets/snippets/eform/eform.inc.php on line 659

any ideas?

**Comment by bossloper** [comment]
eForm is not maintained as part of the core installation now so no Evo would fix this. It is an 'Extra' so someone would need to fix it here: https://github.com/extras-evolution/eForm  . Then you could update eForm from the Extras module.

**Comment by user83743** [comment]
thanks Mr B for the quick reply. like Dymtro - we'll try and get formlister
working. we tried it months ago and gave up as it was too complicated
compared to eform and we couldn't find real world examples and some
parameters did not exist in formlister .  do you know if there are new docs
now and new examples?

**Comment by bossloper** [comment]
http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/create-a-form-report

**Comment by user83743** [comment]
thanks Mr B. i think we tried these example before. thnaks for your help
