### ISSUE TITLE
Codemirror update

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#410]
Can we update the codemirror files for the next Evo release? http://codemirror.net

Currently they are at 5.33.0, Dec. 2017.

The codemirror in the EVO repo is from 2 years ago (some addons 4 years ago): https://github.com/evolution-cms/evolution/tree/develop/assets/plugins/codemirror/cm/lib

Thanks!

**Comment by Deesen** [comment]
v5.33 seems to work: https://github.com/Deesen/evolution/tree/codemirror-533

I have created a script that can take care of future CM-updates for Evo. The script has 3 lists which can be modified: Addons, Themes and Modes. so it adds all required CM-files automatically and compresses them with JShrink.

Right now all addons are added (addon-compressed.js has now 183kb..), but not sure if all of them are useful. If not, I can remove them easily.

**Comment by Deesen** [comment]
For testing: [codemirror.zip](http://s000.tinyupload.com/index.php?file_id=06013753097150840514)
