### ISSUE TITLE
TinyMCE4 не редактируется исходный код, вставка ссылок.

### ISSUE THREAD

**Issue by ctac22** [evolution-cms/evolution#413]
При выводе TinyMCE4 в модальном окне (через Colorbox) невозможно редактировать исходный код, вставлять ссылки  и еще некоторые функции. В консоли ошибок нет.  
`$(document).on('focusin', function(e) {
    if ($(e.target).closest(".mce-window").length) {
        e.stopImmediatePropagation();
    }
});`
Не помогает.

**Comment by Deesen** [comment]
Maybe you need to add `trapFocus: false` to the colorbox-call -> https://stackoverflow.com/a/33764553/2354531

**Comment by ctac22** [comment]
Thanks a lot! It worked.
