### ISSUE TITLE
Публикация документов.

### ISSUE THREAD

**Issue by sergey-yabloncev** [evolution-cms/evolution#414]
При заполненном параметре "Дата публикации"  (pub_date) невозможно убрать чек с параметра "Публиковать" после сохранения документа он снова проставляется

**Comment by scorN17** [comment]
Если дата стоит например 20.12.2017 (прошедшая дата) - логично же, что галочка выставляется автоматически.
Попробуйте дату в будущем (или вообще очистите поле).
Или выставите дату отмены публикации.

**Comment by sergey-yabloncev** [comment]
Не логично что снять документ с публикации без танцев возможно только при вызове меню в дереве, а при редактировании документа не потанцуешь не снимешь

**Comment by scorN17** [comment]
С другой стороны, конечно, автоматические действия админки должны быть явно обозначены визуально.
