### ISSUE TITLE
Warning: mysqli::mysqli(): Headers and client library minor version mismatch.

### ISSUE THREAD

**Issue by ProstoSanya** [evolution-cms/evolution#415]
Сразу после установки в админке пишет предупреждение:
Warning: mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /home/u823691207/public_html/manager/includes/extenders/dbapi.mysqli.class.inc.php on line 30

При открытии главной возникает ошибка:
« Evo Parse Error »
Error : mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50173 Library:50312

Скрины:
http://prntscr.com/hsenqh
http://prntscr.com/hseorm

**Comment by Deesen** [comment]
This is probably a local problem -> https://stackoverflow.com/a/10768766/2354531
