### ISSUE TITLE
Доступ к запуску модулей, ограничение ролью

### ISSUE THREAD

**Issue by helgispbru** [evolution-cms/evolution#417]
Проблема: при создании роли с правами "run module" - у пользователя с этой ролью вообще нет доступа к модулям.

Что предшествовало: обновление с 1.3.6 на 1.4.0.RC2

На версиях между 1.3.6 и 1.4.0.RC2 не проверял.
На версии 1.3.6 ещё работало.

Как повторить:
1. Сделана отдельная роль user_role1, в её настройках в блоке module management проставлена только галочка run module.
2. Сделан пользователб user1, у него в настройках ставится User's role: user_role1
3. Вход в админку сайта как user1 - кнопка modules сверху доступна, но при нажатии на неё ничего не происходит.

Если у пользователя права Administrator - модули доступны, всё работает.

Проблема повторяется стабильно - уже 3 сайта обновил и везде так.

**Comment by bossloper** [comment]
Have you checked the access permissions on the module(s) you want to be able to run as user1? Just having 'run module' role does not necessarily mean the manager can run a particular module.
e.g.
![untitled](https://user-images.githubusercontent.com/1744687/34639105-40399656-f2d1-11e7-98ce-176c28bd289b.png)

**Comment by helgispbru** [comment]
Yes, I did.
I checked twice - first time I just look, after that I created a new manager group "group1", add user1 to this group, put a tick on that group in module editor and after I logged in as a user1 - it was the same. I press Modules and nothing happens.

After I published this issue I found #382 with the same situation. Maybe it's better to merge this issue with #382

**Comment by bossloper** [comment]
There have been quite a few commits to the dev branch since 1.4.0.RC2 so I believe it has already been addressed. Running latest dev and it works as expected for me.
But yes looks same as #382 so maybe this can be closed and #382 tested again when the next official release comes out?

**Comment by helgispbru** [comment]
Yes, I will try dev and close this for now.
Let the first issue #382 stay opened.
