### ISSUE TITLE
Managing Roles - Disabled checkboxes do not have any 'disabled' styling

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#418]
When editing manager roles many of the General role options are required and so disabled from removing the check - which is fine. However these 'disabled' checkboxes are visually the same as normal checkboxes, whereas normally they would have some sort of 'graying' or other distinctive styling.

![untitled](https://user-images.githubusercontent.com/1744687/34639233-01554c70-f2d4-11e7-837e-4010fadac808.png)

Tested on Chrome and Edge

**Comment by Nicola1971** [comment]
![download](https://user-images.githubusercontent.com/7342798/34640135-762a7836-f2ed-11e7-9a9a-da1dee74a300.png)

better?

**Comment by bossloper** [comment]
Yes, looks good to me.
