### ISSUE TITLE
FormLister (account request)

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#422]
I have a clean install 1.4 RC2 with **example template** on my webserver (php7).
When I use FormLister (account request), after successful registration no e-mail is sent to the user.
With FormLister (reminder / password forgotten) the sending of emails works without problems!
Can someone tell me why this is so please... Thank you!!

**Comment by Pathologic** [comment]
Show the FormLister call.

**Comment by cimt** [comment]
is the same as in the Basic installation!
**I have not changed anything!**
again: FormLister (reminder / password forgotten) the sending of emails works without problems!

**Comment by dmi3yy** [comment]
Fixed

**Comment by Pathologic** [comment]
```
&ccSender=`1`
&ccSenderField=`email`
&ccSenderTpl=`@CODE:Hi, [+fullname.value+]!`
```
