### ISSUE TITLE
Ditto documents doesn't work correctly

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#424]
[[Ditto? &documents=`[+id+]` &tpl=`@CODE:[+id+] or something else [+pagetitle+]`]]
same here:
[!Ditto? &documents=`[+parent+]` &tpl=`@CODE:[+id+] or something else [+pagetitle+]`!]

the result is blank page with:    Illegal value of &documents: [+id+] or Illegal value of &documents: [+parent+]

Evolution CMS version 1.4RC2

**Comment by dmi3yy** [comment]
turn off PHx or modifiers and will work

**Comment by modwebpl** [comment]
well ok, but how can I disable phx ?

**Comment by dmi3yy** [comment]
turn off plugin

**Comment by modwebpl** [comment]
![zrzut ekranu 2018-01-09 o 13 36 33](https://user-images.githubusercontent.com/35030936/34721219-365eac34-f542-11e7-9f60-438d787593db.png)

Well.. I think I do not have ?

**Comment by pmfx** [comment]
Maybe try `[*id*]` and `[*parent*]`?

**Comment by modwebpl** [comment]
Well I can't because I need to something like this:

[[DocLister? &tpl=`

<div id="product_[[Ditto? &documents=[+parent+] &tpl=`@CODE:[+product_category+]`]]

&parents=`[*id*]`
&display=`1`
`]]

And i get: Illegal value of &documents: [+parent+]

I have clean install of Evolution CMS 1.4 RC2 without plugins nad PHX, filters and Syntax are disabled in CMS configuration.

**Comment by dmi3yy** [comment]
With clean all work Correct  you can install demo Site and check this

**Comment by dmi3yy** [comment]
[[DocLister? &tpl=<div id="product_[[Ditto? &documents=[+parent+] &tpl=@code [+product_category+]]] &parents=[ id ]&display=1`]]

this can't work
if need snippet inside snippet use  &tpl=`chunk_name` or use preparу шт DocLister

**Comment by dmi3yy** [comment]
in @CODE: you can use only placeholders like [+ +] 

&tpl=`@CODE: [[snippet]]` -- this still work but 
&tpl=`@CODE: [[snippet? &param=`[+param+]`]]` - can't work  

inside snippet in @CODE parsed first and [+param+] is empty

**Comment by modwebpl** [comment]
Ok, thx 4 your advice. I will figure it out : )
