### ISSUE TITLE
Question regarding security

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#427]
At some point in the past, I think it was before the migration to the current github, there was a thread regarding an addition to .htaccess [6G Firewall](https://perishablepress.com/6g/)

Does anybody find this necessary or have any other recommendations?

**Comment by bossloper** [comment]
Depending on your server you could also have CSF firewall?
But don't think this issue is Evo specific?

**Comment by bossloper** [comment]
can close?
