### ISSUE TITLE
How get current doc ID like in MODX Evo 1.2.1 ??

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#428]
Hello, In new clean install of 1.4 RC2 I have a big problem with getting current ID of child document. In MODX Evolution 1.2.1 I do something like this:

`[[Ditto? &parents='[*id*]' &tpl='@CODE:<div class="slider" style="background-image: url( [[Ditto? &documents='[+id+]' &tpl='@CODE:[+img+]']] )"></div>']]
`

And its works on 1.2.1, now in 1.4 RC2 getting the error: Illegal VALUE of [+id+] .. it work only if I write manual id like: &documents='2' <-- but this is not solution what im looking for :/.

So how I can take current ID of child document in ditto parent root and get their TV ?

**Comment by Nicola1971** [comment]
is the same issue you opened here?  https://github.com/evolution-cms/evolution/issues/424

**Comment by dmi3yy** [comment]
Yes its the same problem :)
