### ISSUE TITLE
[BUG] Checking if /assets/images, [...] exists: FAILED! (but they exists!)

### ISSUE THREAD

**Issue by qcol** [evolution-cms/evolution#431]
When tried to upgrade my old MODX site, I got error:

`Sprawdzanie, czy istnieją foldery /assets/images, /assets/files, /assets/flash oraz /assets/media: NIE POWIODŁO SIĘ!`
`Sprawdzanie, czy foldery /assets/images, /assets/files, /assets/flash oraz /assets/media są zapisywalne: NIE POWIODŁO SIĘ!`

I checked many times - directories exists with 777 permissions... 

After all, something made me change my language (Polish to English). 

What was my surprise when I received a completely different message (different folders!)

`Checking if /assets/images, /assets/files, /assets/backup and /assets/.thumbs directories exists: FAILED!`
`Checking if /assets/images, /assets/files, /assets/backup and /assets/.thumbs directories are writable: FAILED!`

In the installer, the folder names depend on the selected language. It's big BUG!

Of course I created new folders from english message and all is OK now (but I lost half a day searching for a cause with a wrong message in Polish earlier. )

**Comment by Nicola1971** [comment]
flash and media folder are no more included in evo, so does not exist a check for these folders.

> In the installer, the folder names depend on the selected language. It's big BUG!

No. Folder names are coded in the installer not in the language
https://github.com/evolution-cms/evolution/blob/develop/install/actions/action_summary.php#L91-L98

and you can seee there is no check for flash or media 
```
// File Browser directories writable?
echo "<p>".$_lang['checking_if_images_writable'];
if (!is_writable("../assets/images") || !is_writable("../assets/files") || !is_writable("../assets/backup") || !is_writable("../assets/.thumbs")) {
    echo "<span class=\"notok\">".$_lang['failed']."</span></p>";
    $errors += 1;
} else {
    echo "<span class=\"ok\">".$_lang['ok']."</span></p>";
}

```

i think it is only an issue with **not updated Polish Installer Language**
https://www.transifex.com/evolutioncms/evolution/dashboard/

![download](https://user-images.githubusercontent.com/7342798/34915404-6462795c-f926-11e7-8aa5-fff33c756115.png)

@pmfx Can you check?

**Comment by qcol** [comment]
yes, this section:
`Checking if 1/assets/images1, 2/assets/files2, 3/assets/backup3 and 4/assets/.thumbs4 directories exists:`
was not translated (I translated it on transifex now).... but it should be replaced by english version in this case (fallback locale), not any old existing polish version (with wrong directories).

**Comment by qcol** [comment]
But the problem is that the installer doesn't let the user go forward because he reports a bug of non-existent folders. The user is looking for other folders than should and cannot locate the cause of the error.

**Comment by Nicola1971** [comment]
> but it should be replaced by english version in this case (fallback locale)

I agree. Never noticied that missing installer language strings are not replaced by english strings.

Actually only Italian and German language are 100% updated.
i'm italian and always update my language, so i never noticied the issue
Strange that no one else has encountered this mistake (no Russian installer issue?).

We need more help on Transifex 😃

**Comment by Nicola1971** [comment]
i've updated the language from transifex (with your additions)  - to fix the issue,  but there are still 14 strings untranslated in your language.
