### ISSUE TITLE
ajax.php issue on some (maybe old) servers with onBeforeMoveDocument and onAfterMoveDocument

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#432]
I've a couple of clients websites on shared hosting, with no access to php.info, but i suspect on php5.4.

Latest edditions from 1.2 RC2 on ajax.php (i think with this commit https://github.com/evolution-cms/evolution/commit/8d4f7953c546aea852888cf4056fd0b6ed026147) brokes the site tree (does not load).
![screenshot 2018-01-14 14 17 14](https://user-images.githubusercontent.com/7342798/34916279-e44e2d00-f935-11e7-96b8-c383d60a0cbc.png).

Swiching to my custom theme EvoFLAT (actually use the ajax.php from RC1), everything works

Seems related to the new events **onBeforeMoveDocument** and **onAfterMoveDocument**
Adding comment to these lines , solve the issue

https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/ajax.php#L497-L513

https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/ajax.php#L573-L577

I know they probably should update the php, but i dont see any issue in this code and i want try to fix untill they update (as i hope).
Any idea?

@mnoskov
@64j 

just a note : why 
**onBeforeMoveDocument** and **onAfterMoveDocument** 
and not 
**OnBeforeMoveDocument** and **OnAfterMoveDocument**  like all other Events?

I think we should correct it

**Comment by mnoskov** [comment]
Can you show errors log?

**Comment by Nicola1971** [comment]
hi @mnoskov thanks for reply. 😃 
actually i have not access to the domain/server control panel and to error logs: both are single domain on shared hosting with a very limited access to the configuration (php.info is disabled).

There are no error in System Events.
Tried to set "Detection level of PHP errors" to "Detect all", but still no errors.

Cant understand how your commit cause this issue.

NOTE: **onAfterMoveDocument** seems an intersting event for **SEO purposes** ...i'm dreaming a plugin for automatic 301 😄

**Comment by mnoskov** [comment]
Are there any plugins on these events?

You can see php version there - http://\<your domain>/manager/#?a=200
If version is 5.3, you can try to change array definition from `[]` to `array()`.

**Comment by Nicola1971** [comment]
Yes! it's the array!!! Thank you very much 😄 
So it's a 5.3x
