### ISSUE TITLE
mm_moveFieldsToTab

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#433]
Trying to move a TV above Resource content,
`mm_moveFieldsToTab('Main-Image', 'general');` no longer seems to work.

Am I missing something?

**Comment by 64j** [comment]
MainImage

**Comment by risingisland** [comment]
@64j That is the same as I posted, does not seem to be working. 
"Main-Image" is the TV name.

Tried with another TV "thumbnail" and used `mm_moveFieldsToTab('thumbnail', 'general');`
But it does nothing.

**Comment by bossloper** [comment]
It works for me BUT the moved field is placed after the resource content field.... check it is not further down the page? Previously the moved fields would be placed after the resource parent field and before the resource content.

**Comment by risingisland** [comment]
Yes, below the Resource Content is the default location if you do not use MM, so it does not seem to be working any more.

**Comment by bossloper** [comment]
My simple test (not a tv) was:
`mm_moveFieldsToTab('published', 'general', '', '');`
On old installs it placed the published check above the resource content, on new installs it is now below. So I think it is technically 'working' but the insert placement may have changed for mm_moveFieldsToTab?

**Comment by bossloper** [comment]
... it looks like the changes to the html structure means resource content (id=content_body) has moved into the main table of the general tab sectionBody which in turn means as mm is inserting at the last td of the table it is now after the resource content instead of before.

**Comment by bossloper** [comment]
Can you get around it by adding:
`mm_moveFieldsToTab('content', 'general');`
after you move the tv?

Though I cannot seem to move the which_editor with:
`mm_moveFieldsToTab('which_editor', 'general');`

And attempting to hide it with
`mm_hidefields('which_editor');`
now does not hide the label for it.

**Comment by risingisland** [comment]
My results were the same, I could move Content below, but not Which_Editor.
So, for me this is not a solution as it could become an issue for a client having both buttons so close together...
![insert](https://user-images.githubusercontent.com/6113504/35034696-f2ec75a0-fb66-11e7-8d51-4f33bd28d4f1.png)

**Comment by risingisland** [comment]
Also, I think it would be preferred to move "which_editor" with Content field instead of hiding it, as Codemirror comes in handy.

**Comment by bossloper** [comment]
I agree about moving which_editor along with the content.
For now I have put a fix patch request in https://github.com/evolution-cms/evolution/pull/436 for not being able to completely hide the which_editor as that should be fixed regardless.

**Comment by 64j** [comment]
@risingisland 
Move the TV to the desired categories and in the configuration, select the TV grouping in the new tabs.
Without any use of MM

![image](https://user-images.githubusercontent.com/4653189/35041810-209817d6-fb97-11e7-9eb2-5c729ef71c13.png)

**Comment by risingisland** [comment]
I had hoped to have one TV above content, like it had been possible in past versions, but I think I can get by with this.

**Comment by fourroses666** [comment]
Oh no, mm_rules like: `mm_hideFields('content','','3');` or `mm_moveFieldsToTab('published', 'general');` don't work anymore?

**Comment by bossloper** [comment]
Presume you mean after the last dev commit #448 ? Your above examples still works for me. Maybe there  is another line in your mm_rules file that is causing a js error?

**Comment by risingisland** [comment]
I think he is probably referring to the same as I had mentioned, it no longer move above the Content field as it did before, it now places it below.

**Comment by fourroses666** [comment]
No the removing/hiding doesn't work. 
But I have no issue with that on an other install also 1.4.0 RC3 _(without that commit)_
The mm_rules are oke.
Need to find out whats the problem on this install.

**Comment by fourroses666** [comment]
The only differences are the Content field is normal height on the working version.
On the not working one its only about 100px height.
Its not listening to the 400px height placed in the plugin settings.
But I don't see any errors.

Could be the development versions are different.
Hmm

**Comment by fourroses666** [comment]
Oke, it works again.. after re-saving the plugins ManagerManager and TinyMce.
I seem to have some weird issues on this install..

Some days ago also CodeMirror stopped working, so I opened the plugin and saved it again (without any changes) and it worked again.

It works but the Content field is still 100px in height.

**Comment by risingisland** [comment]
This happens to me as well from time to time, I think it is some sort of cache issue, as I have done the same. Open a plugin and save without making changes. 
I wish there was some sort of clear cache for the admin too.

**Comment by fourroses666** [comment]
If you ask me: Publish checkbox should be on General tab as default.
Its an important checkbox while the others in that tab are not.
I change it on every install

**Comment by bossloper** [comment]
@fourroses666  I think that has been discussed before over the years, probably more than once. But for whatever reason the consensus is it is still on the settings tab. :-) but yes my MM always moves it to the General tab. I also thing there are too many fields on the General tab showing above the resource content by default. Many of those I think should be on a separate tab to clean up the main edit.

**Comment by fourroses666** [comment]
Would be nice to have a different template for the resources, where you can choose whatever you want to place where, and have a sidebar on wide screens. Or going crazy and have somekind of dashboard where you can drag fields to other positions. 🙏

**Comment by fourroses666** [comment]
Is there any way to get the Publish checkbox above the content? (without touching the core)

**Comment by dmi3yy** [comment]
need test with mm and fix it for this

**Comment by fourroses666** [comment]
Just to make this visual;
`mm_moveFieldsToTab('published', 'general');`

Results in:
![go-up](https://user-images.githubusercontent.com/523389/35446984-b52c2f92-02b6-11e8-80a5-6aa2836261ea.png)

**Comment by bossloper** [comment]
@fourroses666 You can get published above content by using two rules together:
```
mm_moveFieldsToTab('published', 'general');
mm_moveFieldsToTab('content', 'general');
```

**Comment by risingisland** [comment]
It would be nice to be able to move any field above content, as was possible in all previous versions, not only the Publish option.

**Comment by fourroses666** [comment]
Ah didn't think of that @bossloper 

Double line but works.

**Comment by bossloper** [comment]
Yes the double line is because the content field has a hardcoded hr tag at the top. 
Not sure if in the new look of the manager that it is really necessary at all and could possibly be removed? Even for the default look, without using MM.

**Comment by risingisland** [comment]
How is it to move the "Which Editor" block ?

**Comment by fourroses666** [comment]
Isn't the which editor on a nice place?

![which ed](https://user-images.githubusercontent.com/523389/35447894-1bc979ec-02b9-11e8-952e-3c9e4d0ae242.png)


Furure plans looks very good, if I understand correct we can sort this in 1.5

`Appearance of the admin area: Updating Bootstrap to version 4, as well as fontAwesone + making it possible to use. Create a basic template in which all the elements of the admin area are given, so you can create and use your own themes, to allow custom concepts of the admin area.

Also planned: Rebuild the admin on a twig template that will give even more flexibility, for example, change the look of the page without using ManagerManager, which can slow down performance in case there are too many TV parameters. Let´s see how it works out.`

https://github.com/evolution-cms/evolution/releases

**Comment by risingisland** [comment]
Yes, it belongs above the content, but if the content area is moved via:
```
mm_moveFieldsToTab('published', 'general');
mm_moveFieldsToTab('content', 'general');
```
Then the which editor is no longer above content.

**Comment by bossloper** [comment]
It is moved correctly in the latest version
https://github.com/evolution-cms/evolution/commit/da5b0533d251c02b95321263bfc0b36de17918f2

**Comment by risingisland** [comment]
My bad. It is working as intended. 
My MM was not updated.
Thanks for pointing this out.

**Comment by bossloper** [comment]
@fourroses666  Just put a fix in for the double line issue
https://github.com/evolution-cms/evolution/commit/6df0e1c3359d769753593e28f31b618979356ea1

**Comment by fourroses666** [comment]
Works 👍
