### ISSUE TITLE
rules FormLister

### ISSUE THREAD

**Issue by ProjectSoft-STUDIONIONS** [evolution-cms/evolution#434]
После обновления на 1.4.0.RC3 перестал работать rules в FormLister.
У меня любое поле должно проходить проверку.
В prepareProcess всё собираю и вношу в базу.
В базу вносятся пустые значения, если отправлена пустая форма.
Примерный код условий
```
&rules=`{
	"email":{
		"custom": {
			"function": "\\MyClass\\FormValidator::emailValid",
			"params": [0],
			"message": "Email введён не корректно"
		}
	},
	"phone": {
		"custom" : {
			"function": "\\MyClass\\FormValidator::phoneValid",
			"params": [0],
			"message": "Телефон введён не корректно"
		}
	}
}`
```

**Comment by Pathologic** [comment]
\\MyClass\\FormValidator видимо не загружен.

**Comment by ProjectSoft-STUDIONIONS** [comment]
@Pathologic как он может быть не загружен, если это пакет composer?
Ещё раз - в 1.4.0.RC2 всё работает. В 1.4.0.RC3 - нет

**Comment by 64j** [comment]
@ProjectSoft-STUDIONIONS 
а после обновления до RC3, Formlister обновляли из Экстрас?

**Comment by ProjectSoft-STUDIONIONS** [comment]
Чистая установка + updater.
Т. е. сайт разрабатывался уже на Evolution CMS и всё обновлялось через updater.
C Экстрас ни чего нет.

**Comment by 64j** [comment]
@ProjectSoft-STUDIONIONS 
релиз мог не включать в себя все изменения в Формлистере

**Comment by ProjectSoft-STUDIONIONS** [comment]
@Pathologic  Обновил с Экстрас. Тот же результат.

**Comment by dmi3yy** [comment]
Формлистер последний на момент релиза 

Отправлено с iPhone

**Comment by ProjectSoft-STUDIONIONS** [comment]
Правила есть. Код в старттопике.
В дебаге их нет
![FormLister](https://monosnap.com/file/dRGnbeB82VoYZ8YOkEBotIhsWzRxt5.png "FormLister")

**Comment by ProjectSoft-STUDIONIONS** [comment]
Ошибка была в Config.php
https://github.com/evolution-cms/evolution/commit/5eff19cac0b0471ff9bf0ea88ca43d9f49b60096
