### ISSUE TITLE
Internationalization: New Language issues categorization Labels

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#435]
I've started a new categorization for language files related issues for better managment:
. All language issues use label color #fbca04

with 3 levels

- **main language issue label** https://github.com/evolution-cms/evolution/labels/lang
- **installer/manager issue label**: 
https://github.com/evolution-cms/evolution/labels/install-lang
https://github.com/evolution-cms/evolution/labels/manager-lang
https://github.com/evolution-cms/evolution/labels/extras-lang

- **native language issue label**: examples:
https://github.com/evolution-cms/evolution/labels/polish-lang
https://github.com/evolution-cms/evolution/labels/japanese-lang
https://github.com/evolution-cms/evolution/labels/russian-lang
https://github.com/evolution-cms/evolution/labels/spanish.lang
https://github.com/evolution-cms/evolution/labels/nederlands-lang
https://github.com/evolution-cms/evolution/labels/german-lang
https://github.com/evolution-cms/evolution/labels/italian-lang

# Full Example:
https://github.com/evolution-cms/evolution/issues/431

**Comment by Nicola1971** [comment]
hoping it was read. I close

**Comment by fourroses666** [comment]
How do you add the label to an issue?

**Comment by Nicola1971** [comment]
i think only the staff can add labels. :(

I'm adding labels for better categorization to all open issues, excluded issues with no english title.
