### ISSUE TITLE
PHP-controlled CronJobs like Wordpress

### ISSUE THREAD

**Issue by Dmi3yy** [evolution-cms/evolution#44]
Anyone want to try?
https://github.com/Nicola1971/JobScheduler

Just install with Package Manager and try

https://github.com/modxcms/evolution/issues/1099

**Comment by Nicola1971** [comment]
just updated this module a bit and fixed for new evo - tested  with 1.4

added a new feature to CronEvoBackup snippet to send email with download link of backup created
