### ISSUE TITLE
TinyMCE4 4.7.4 update after RC3

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#442]
@Deesen @dmi3yy 

About: https://github.com/evolution-cms/evolution/pull/437
I appreciate any update, but really don't think is the right moment **at the last state of Release Candidate**.

TinyMCE4 always cause a lot of issues in any update and we still have some small TinyMCE4 issues to fix from the last update
https://github.com/evolution-cms/evolution/issues?q=TinyMCE4+is%3Aopen

evo 1.3.6 was 4 Sep 2017.. i think it's the time to get evo1.4 fixed out and not add more features or updates to check.

NOTE:  just installed latest DEV on two sites and new TinyMCE4 default skin does not work  and does not load the richtext editor (switch back to "modern" skin solve the issue)

``` Uncaught Error: inlite theme only supports inline mode. ```

EVO 1.4 is 99,9% ready and we don't have the time to discover and fix any new TinyMCE4 issues.

**Sorry, but Please revert TinyMCE4 Update and postpone to the next version**.

**Comment by dmi3yy** [comment]
ок i do revert this issue and and in 1.5.0и

**Comment by bossloper** [comment]
@Deesen - last dev updates shows this error again. Default theme needs changing to modern from Inlite.

**Comment by Deesen** [comment]
Ok hopefully fixed it.
