### ISSUE TITLE
File permissions after update to EVO

### ISSUE THREAD

**Issue by mplavala** [evolution-cms/evolution#446]
Hello, after updating my site to EVO CMS I have a problem in the manager view. In the panel on the left side of the screen, where my pages should be listed, there is instead this:

Forbidden
You don't have permission to access /manager/media/style/default/ajax.php on this server.

The file permissions for the mentioned ajax.php are 640. I tried changing them up to 755 and it did not help. I tired seearching for the answer but the statement is too common to provide any hint. 
Do you know how to solve this issue? (except for that the whole page works and the new EVO looks great and is way faster than the old one).

My system info:
EVO version |   | 1.4.0.RC3
Release date |   | Jan 18, 2018
PHP Version |   | 7.1.10
phpInfo() |   | View
Access permissions |   | Enabled
Server Time |   | 11:09:17
Local Time |   | 11:09:17
Server offset |   | 0 h
Database name |   | db_modx
Database server |   | localhost
Database Version |   | 5.5.5-10.0.32-MariaDB-1~wheezy
Database Charset |   | utf8
Database Collation Charset |   | utf8_general_ci
Table prefix |   | modx_
MODX_BASE_PATH |   | /home/html/pepeelektro.sk/public_html/
MODX_BASE_URL |   | /
MODX_MANAGER_URL |   | https://www.pepeelektro.sk/manager/
MODX_MANAGER_PATH |   | /home/html/pepeelektro.sk/public_html/manager/
MODX_SITE_URL |   | https://www.pepeelektro.sk/

**Comment by 64j** [comment]
@mplavala 
Change the permissions on the ajax.php file to 777.
It often happens on servers that the files are downloaded not from the server administrator's name, but from the user, and the rights of 755 are not at all

**Comment by mplavala** [comment]
I did change the file's permissions to 777 and it did not help. Also before the update from ModX Evo, this worked just fine (and still works on a webpage that runs the old ModX Evo) hence I guess this could be more complicated.

**Comment by Deesen** [comment]
Could it be a security-setting on your server or .htaccess-file? Maybe ask your hoster/admin?

For example you should see a blank page, instead of a 403-error when calling `https://www.yourdomain.sk/manager/media/calendar/datepicker.inc.php`.

**Comment by mplavala** [comment]
@Deesen probably not. I am sure I left the .htaccess intact during update. I tried using the new ht.access created during the update instead, but it did not change anything. The site
`https://www.yourdomain.sk/manager/media/calendar/datepicker.inc.php`
gives 403 error. Also, it worked before with the same .htaccess file.
Can you think of some kind of change that happened that could influence this?

**Comment by Deesen** [comment]
No, but your hoster could check server log-files to see what is the reason for this 403-response.

**Comment by mplavala** [comment]
I am closing this issue as it was a problem on the side of the hosting of the server. They fixed it and it works now.
Thank you all for providing your help and for your time.
