### ISSUE TITLE
Double File Management tabs and can't remove one

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#450]
Don't know how I did it but happened a couple of times;
I have 2x the tab "File Management". _(Bestandsbeheer in my language)_
Can't remove or see the first one. (without full page refresh).

<img width="658" alt="filemanager-tab-2x" src="https://user-images.githubusercontent.com/523389/35222735-27f0c46a-ff7f-11e7-810a-63170a1cb0ce.png">

**Comment by 64j** [comment]
@fourroses666 
How to repeat this error?

**Comment by fourroses666** [comment]
When I find out I let you know, can't reproduce at the moment.

**Comment by fourroses666** [comment]
I have the 2 Filemanagement Tabs open again but now I can click on both. Still no idea how it happened..

https://www.youtube.com/watch?v=qc0us0SDAxw&feature=youtu.be&hd=1

**Comment by fourroses666** [comment]
I will close this. Its a really minor issue which I can't reproduce anymore.
Probably when doing really allot of stuff and switching from tabs and pages etc. this could happen.
When I do see it again and know how to reproduce I will open again.

**Comment by fourroses666** [comment]
Have it again, File Management tab not selectable. Can't delete it.
Can open a new File Management (bestandsbeheer) tab which does work.
I think it happens only after a long time having the manager open.

Maybe this helps debugging it?
<img width="936" alt="tabs" src="https://user-images.githubusercontent.com/523389/35472894-cfb1cf68-0377-11e8-939f-0e5ea06f8fe2.png">

**Comment by fourroses666** [comment]
Might be an issue when using multiple browser tabs and manager tabs, or working on same subdomain and cookies/local storage. Don’t know how it works, but will close the issue again. When I’m able to reproduce I reopen the issue.
