### ISSUE TITLE
Migrate from Evo 1.0.13

### ISSUE THREAD

**Issue by dennis-f** [evolution-cms/evolution#451]
Since the project is not in the hands of modxcms i was wondering if it is still upgradable and what would be best practice.

I have a very old 1.0.13 MODx Evolution site. Can i directly upgrade to 1.3.x or do I have to take additional steps in between?

--- Update
I upgraded without any hazzle up to 1.4 rc thx for all the quick responses! **This issue can be set to solved**

**Comment by fourroses666** [comment]
That shouldn't be a problem, no need to take other steps.
Just make sure you have an backup.

**Comment by dennis-f** [comment]
Thanks for the quick response. So that means I can jump directly up to 1.3?

**Comment by fourroses666** [comment]
Yes, not sure about minimum system requirements. PHP 5.6 or later would be advisable.

**Comment by pmfx** [comment]
I would go for 1.2.1 first. Then 1.3.6 or wait for 1.4 (should be released soon).
Note: 1.3 and later works better with PHx disabled and Filters enabled (in sys config). You should also think about converting Ditto calls to DocLister. More complex Ditto calls may not work in some cases.

**Comment by modxuser** [comment]
@pmfx 

Does that mean Ditto has now been officially binned, will there now be no more backward compatibility with newer Evo versions

Although it's been claimed many a time, DocLister does not do everything Ditto does

**Comment by pmfx** [comment]
It is not binned. Ditto is being maintained a lot to be as much as possible compatible with new EVO and latest PHP. But Ditto code is old and dev team is focused on DocLister. It should be used instead of Ditto where possible to get best compatibility and performance results. 

I've been playing with DocLister for a few months and it is very powerful and rather easy to make a transition from Ditto. And now I'm not that sure if it cannot do all that Ditto does :)

We still need to work on better, more detailed (english) documentation though, but DocLister should be your choice in new projects.

**Comment by modxuser** [comment]
As I am not a PHP'r it is hard for me to understand why it's not possible to make DocLister do exactly what Ditto can - that would make the choice of moving over easy

I fully appreciate that NEW in some cases is better, but backward compatibility has been and always should be a priority

Evo isn't just used by those who post here in GitHub, but I get the feeling that that is forgotten a lot nowadays

In my opinion what should also be taken into consideration is people have custom code built around the default snippets and plugins that came with Evo for many many years - there is a cost factor that should be taken into consideration, having to re-code custom code is costly

**Comment by 64j** [comment]
@modxuser 
You are not prevented from staying on version 1.3.6 and everything will work on all the old sites.

Show me what Ditto can and what DocLister can not?

**Comment by modxuser** [comment]
Tagging - this discussion has already been mentioned

**Comment by 64j** [comment]
@modxuser 
```
[!DocLister?
&controller=`site_content_tags`
&tagsData=``
&tagsSeparator=`,`
&tagsTV=`1`
```

**Comment by modxuser** [comment]
Your call uses a bespoke table - Ditto doesn't

**Comment by 64j** [comment]
@modxuser 
example:

```php
	$out = $modx->runSnippet('DocLister', array(
		'debug'=>'0',
		'id'=>'sidebar',
		'display'=>'7',
		'depth'=>'3',
		'tpl'=>'Posts_sidebar',
		'controller'=>'site_content_tags',
		'summary'=>'notags,len:65',
		'parents'=>'150',
		'tvList'=>'CatLists,img',
		'showParent'=>'0',
		'addWhereList'=>'template IN (11)',
		'paginate'=>'pages',
		'tagsTV'=>'7',
		'TplWrapPaginate'=>'@CODE: ',
		'orderBy'=>'id DESC',
		'offset'=>'2',
		'tagsData'=> $modx->documentObject['id'] != 1 ? 'then=`static:'.$modx->documentObject['id'] : '',
		'prepare' => function($data, $modx){
			$data['CatLists'] = $modx->runSnippet('CategoryList', array(
				'sep' => '||',
				'data' => $data['tv.CatLists'],
				'outSep' => ', ',
				'tpl' => '@CODE: <a href="[+url+]" title="[+e.title+]">[+title+]</a>',
			));
			return $data;
		}
	));
```

**Comment by 64j** [comment]
@modxuser 
**site_content_tags** - is controller

**Comment by modxuser** [comment]
and whats a controller ?

Can Doclister now replicate all the following:
http://www.evolution-docs.com/tutorials/extras-how-to/ditto-tutorials/category-tagging-with-ditto
http://www.evolution-docs.com/tutorials/extras-how-to/ditto-tutorials/tagged-blogging-with-ditto-ex-1
http://www.evolution-docs.com/tutorials/extras-how-to/ditto-tutorials/tagged-blogging-with-ditto-ex-2

**Comment by 64j** [comment]
>>> and whats a controller ?
Read the documentation
http://www.evolution-docs.com/extras/doclister/main-parameters

>>> Can Doclister now replicate all the following
Yes, the example above is written

**Comment by modxuser** [comment]
Your answer is nice - I have read the docs, but still dont understand what is implied with it

site_content_tags
    output Evo documents filtered by tags, in conjunction with the TagSaver plugin

So you need a seperate plugin, or do I see that false ?

**Comment by modxuser** [comment]
Can you also translate this:

		'tagsData'=> $modx->documentObject['id'] != 1 ? 'then=`static:'.$modx->documentObject['id'] : '',
		'prepare' => function($data, $modx){
			$data['CatLists'] = $modx->runSnippet('CategoryList', array(
				'sep' => '||',
				'data' => $data['tv.CatLists'],
				'outSep' => ', ',
				'tpl' => '@CODE: <a href="[+url+]" title="[+e.title+]">[+title+]</a>',
			));
			return $data;
		}

**Comment by 64j** [comment]
@modxuser 
TagSaver - Need for convenient tagging, more advanced options

**Comment by 64j** [comment]
>Can you also translate this:

Read the documentation, еverything is written
http://www.evolution-docs.com/extras/doclister/main-parameters

**Comment by modxuser** [comment]
Obviously you dont want to understand me - the docs are not fully comprehensive for someone who isnt a developer

And I have also mentioned it, not once, not twice, multiple times - I am not a PHP developer, you have code in the call that I can not understand let alone write and I guarantee you, I am not the only one

**Comment by 64j** [comment]
@modxuser 
Well, sorry, I can not help you here.
Either read and learn the documentation, or do not use tags.

**Comment by modxuser** [comment]
Very helpful indeed

**Comment by 64j** [comment]
@modxuser 
You do not want to read anything

**Comment by modxuser** [comment]
Can you not read ? I have read the docs

I actually re-wrote them when I re-built the whole English documentation site

**Comment by 64j** [comment]
@modxuser 
Then if you know all the parameters of DoclIster, what's the question?

**Comment by modxuser** [comment]
I give up

**Comment by nick0** [comment]
> I fully appreciate that NEW in some cases is better, but backward compatibility has been and always should be a priority. Evo isn't just used by those who post here in GitHub, but I get the feeling that that is forgotten a lot nowadays. In my opinion what should also be taken into consideration is people have custom code built around the default snippets and plugins that came with Evo for many many years - there is a cost factor that should be taken into consideration, having to re-code custom code is costly

I cannot agree more with this statement. There certainly was no vote or referendum on ditto usage - if there was I know what I would have voted for. For new sites, sure DocLister could be learnt and used instead. But for existing Evo sites that have come from 1.2.1 previously, it is not time / cost feasible to replace Ditto with DocLister for every single site. Working backwards compatibility has got to be a priority or the usage / community is going to shrink even more. Please consider and engage the Evo user community before making wholesale changes that have the potential to leave many sites stranded.

What if there is a critical security update that needs to be done? Doing those updates for client sites is time consuming and stressful enough to turn around in a timely manner without also having to test / fix / replace Ditto calls that aren't working and breaking the site. Who absorbs that forced time cost? The web designer or our clients? And why should either?

I think we need a "Ditto to DocLister converter plugin" to help transition existing sites to DocLister for older sites.

The improvements, enhancements and maintenance by the EvolutionCMS developers is to be applauded with the utmost gratitude. You're doing an amazing job. But please keep in mind that existing users need backwards compatibility as a priority and engage your userbase on these big decisions.

Out of interest: Is there another fork from 1.2.1 that is being maintained and more mindful of backwards compatibility?

**Comment by dmi3yy** [comment]
Ditto work on 1.4 not see problems. But by default move from core to extras. 

Last year i use DocLister and not see case where need Ditto. 

We start new site for docs :  docs.evo.im - is multilangs and build on files from github if you want you can with translate and add question if some not understand we help ;) 



Отправлено с iPhone

**Comment by Nicola1971** [comment]
I've updated about 15 sites to 1.4, without replace Ditto with Doclister.
#### **You just need to update Ditto from Extras module** and everything will work as before.

But I understand the issue and personally I would have preferred to keep Ditto for a couple of versions, to make updates easier.

**ABOUT TAGS**

Just to check  if it was possible, a few months ago I did a test on a test site (tattoocms) to **replace Ditto with Doclister** with the main goal of **keeping everything as it was before**.

Why? because my clients they would not accept a change in URL that affects SEO _just for an upgrade_.

With a couple of modification to the nice code posted by @pmfx  here https://github.com/evolution-cms/evolution/issues/176#issuecomment-325036799

Results:
I've fully replaced Ditto and Ditto tags and kept all the Ditto Urls formats, including tags and pagination and works with TvTagCloud too.

**Comment by dmi3yy** [comment]
Yes, you can use Ditto but install from Extras and no problems i not see any problems. 
We will maintain backward compatibility for as long as possible. But keep the old components in the kernel do not see the point.

**Comment by Nicola1971** [comment]
The main issue is Doclister parameters does not fit Ditto parameters.

I think, most recent evo/modx users does not know, but originally there was **NewsListing** snippet before **Ditto**.

**Ditto replaced NewsListing about 10 years ago**.
Ditto was much powerful than NewsListing but, at the time, it was only necessary to replace the name of the snippet (NewsListing > Ditto), the parameters remained the same.
The update was simple and opened up new possibilities for developers and designers, thanks to the new features of Ditto.

The same happended with **DropMenu** snippet that was replaced by **WayFinder**.
and with **FlexSearch** snippet that was replaced by **AjaxSearch**.

#### I believe this is what the users expected from Doclister, FormLister and DLMenu: an easy update

New components are always welcome when the upgrade is painless ;)

**Comment by risingisland** [comment]
@Nicola1971 Tags and TvTagCloud have been my hangup too. Do you have a plug-n-play package to get these working? This is making me dizzy.

**Comment by Nicola1971** [comment]
@risingisland  I did it some time ago. it's 99% @pmfx code, with some modifications

I will try to move and replicate on a localhost site with a clean demo content.

So i can try to do a "package" in some way, maybe with a small How To.

**Comment by Nicola1971** [comment]
Hope this help :)
https://github.com/Nicola1971/Doclister-Tags-in-Ditto-Style

Feel free to improve or fix

@pmfx @risingisland @bossloper

**Comment by Nicola1971** [comment]
@dmi3yy - Just an idea before go to bed:

- for a good upgrade user experience, we can create an "updater extras widget" or a "system alert"  for 
 **previously bundled extras**

At least for critical extras like Ditto, eform.
Something like:

> Alert: Ditto snippet (version xxx) is outdated and no more bundled in EVO package (version zzz).
> Please update to Ditto version yyy from Extras Module soon

We can bundle in next releases for some times (from 1.4 to 2.0) and help all users to have a nice upgrade experience. 😃

**Comment by Nicola1971** [comment]
i dont know how to do it, but i dont think is too much complicated:  just a check if version < X
  for most critical previously bundled extras

**Comment by Nicola1971** [comment]
or

> Alert: Ditto snippet (version xxx) is outdated and no more compatible with EVO (version yyyy).
> Please update Ditto to latest version from Extras Module or move to DocLister

**Comment by Nicola1971** [comment]
Done :)

![download](https://user-images.githubusercontent.com/7342798/35332692-201740aa-010c-11e8-8d72-bd5bf4ee4293.png)

**Comment by Nicola1971** [comment]
https://github.com/evolution-cms/evolution/issues/458

**Comment by Nicola1971** [comment]
> --- Update
> I upgraded without any hazzle up to 1.4 rc thx for all the quick responses! This issue can be set to solved

- doclister tags are partially solved
- info for upgrade ditto too

we can close 😃

**Comment by modxuser** [comment]
@Nicola1971 

> Hope this help :)
https://github.com/Nicola1971/Doclister-Tags-in-Ditto-Style

Bookmarked and thank you for the work you have shared, I will, as soon as I have time, look into this again
