### ISSUE TITLE
[I] Feature drag & drop images

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#452]
Is building in an Drag & Drop for images (and files) a good idea?

Script something like: 
github.com/enyo/dropzone
github.com/CreativeSDK/web-image-editor-drag-and-drop

**Comment by Pathologic** [comment]
Check my FastImageTV is for images

**Comment by fourroses666** [comment]
Thx, will have a look.

The File Manager "should" have this drag & drop option.

**Comment by Nicola1971** [comment]
> The File Manager "should" have this drag & drop option.

The File Manager "should" be changed/improved a lot:

- sorting
- file search
- remember last position/folder 
- drag and drop upload
