### ISSUE TITLE
eval() mergeConditionalTagsContent()

### ISSUE THREAD

**Issue by scorN17** [evolution-cms/evolution#455]
В методе ничем не прикрытый eval.
В шаблоне (и не только) можно выполнить PHP-код.
`str_replace(array('<?php', '?>'),`
не выручит, потому что есть, например,
![01](https://user-images.githubusercontent.com/7474329/35276061-16d15242-0053-11e8-9ff0-29a137379eb4.PNG)

**Comment by Pathologic** [comment]
Seems to be solved, reopen if not.
