### ISSUE TITLE
[enhancement] Outdated Extras Check

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#458]
I think this can be a good solution for a lot of recent discussions about ditto/doclister and help all users to have a nice upgrade experience.

Of course, not all extras can be checked, but we can do for more important and critical.

Is just a plugin, easy to config and update in any new evo version and remove it when we do not need it anymore.

We can bundle in next releases for some times (from 1.4 to 2.0)

![alerts](https://user-images.githubusercontent.com/7342798/35334023-32354ce6-0111-11e8-8ae1-7ca6848743d0.png)

Config:
![config](https://user-images.githubusercontent.com/7342798/35334027-35f2c476-0111-11e8-960e-a54bc50f3e8a.png)

https://github.com/Nicola1971/OutdatedExtrasCheck

**Comment by Nicola1971** [comment]
or widget version
![ch-wdg](https://user-images.githubusercontent.com/7342798/35335810-d3d686dc-0116-11e8-8bd5-347612cc84dd.png)

**Comment by dmi3yy** [comment]
widget better

**Comment by Nicola1971** [comment]
OK.
Do you think need translation language?  (do we have the time to translate?)

Actually i only added Ditto and Multitv (both needs to be updated in 1.4.0)

Any other important broken extras that need update (from extras) for evo 1.4.0?

**Comment by Nicola1971** [comment]
regards MultiTV - can you update the Extras Module version? is older than the one on extras repository (and bugged) :smile:

**Comment by Nicola1971** [comment]
Added Multi language support and 2 languages (english and italian).

Tested - works fine for me

![extras-check](https://user-images.githubusercontent.com/7342798/35346454-9609b7e0-0132-11e8-96fd-472dac0567fd.png)

**Comment by pmfx** [comment]
This is cool. Good work @Nicola1971

**Comment by Nicola1971** [comment]
thinking about security: 

What happen if you upgrade to 1.4 an old modx evo 1.0.12, 1.2RC1 or 1.2.2, **not patched** with
**Security FIX for 1.0.12 - 1.2RC1** or **Security FIX for 1.2.2**? 

With EVO1.4 there is no patch for eform or ajax search files (moved to extras). 
We should add an alert to update/remove these snippets too

**Comment by modxuser** [comment]
@Nicola1971 

Good work :) Just a heads up:

`$_oec_lang['isoutdated'] = 'is <b>outdated</b> and no more compatible with';`

Maybe the following would be better

`$_oec_lang['isoutdated'] = 'is <b>outdated</b> and no-longer compatible with';`

**Comment by Nicola1971** [comment]
just checked Ajax search versions: the bugged and fixed version have the same release number 1.4.8 WTF?

**Comment by Nicola1971** [comment]
I think we can update just the version on extras - ok is not a real update :smile:, bud is better make sure all people have patched and secure version of old snippets, when they start with new Evo.

**Comment by Nicola1971** [comment]
I think we can update just the version on extras - ok is not a real update :smile:, bud is better make sure all people have patched and secure version of old snippets, when they start with new Evo.i

**Comment by Nicola1971** [comment]
Updated: added check to index-ajax, old default themes, ajax search and eform

![check14](https://user-images.githubusercontent.com/7342798/35390889-3500a9d0-01dd-11e8-841c-b267f94f3a8b.png)

**Comment by Nicola1971** [comment]
Added WebLogin, WebSignup, WebChangePwd, Breadcrumbs, Reflect and Jot.
Now i think is completed - all old snippets from are checked except:
- Personalize, 
- Ultimate Parent, 
- MemberCkeck 

because are not changed/updated from evolution 1.1

**Comment by Nicola1971** [comment]
easy update and config in next releases
![check-config](https://user-images.githubusercontent.com/7342798/35395240-1bad6358-01ea-11e8-8f8d-34e1650cbcdf.png)

**Comment by bossloper** [comment]
great stuff here @Nicola1971 !

**Comment by Nicola1971** [comment]
Thanks. I think will help many people who will have to update old evo installations.

During the update of some sites to 1.4, I had created a checklist: 
- update ditto
- update multi tvs
- remove old manager themes...

I do not need it anymore 😄

**Comment by Nicola1971** [comment]
NOTE: **Jot** is missing in extras repository or module. 
There is Jotx, but i think is better add latest updated Jot version (1.1.5) from evo 1.3.6

**Comment by bossloper** [comment]
@Nicola1971 I think you need to change the version check code. I had a MultiTV version of 2.0.8. This failed to trigger the update warning for MultiTV as mathematically 2.0.8 is not less than 2.0.12.
I think if you use something like this instead then it should work:

`if (version_compare($curr_mtv_version,$minMtvVersion,'lt')){`]

http://php.net/manual/en/function.version-compare.php

**Comment by Nicola1971** [comment]
@bossloper  thanks - never noticed , because tested with 2.0.11  😄

**Comment by Nicola1971** [comment]
fix and improvements:
- version_compare (credits: @bosslooper #458 (comment))
- added suggest update to Formlister to:  Weblogin, WebChangePwd, WebSignup
- updated Multitv min version to 2.0.13

**Comment by Nicola1971** [comment]
- Added modx 0.9x manager themes : MODxLight,MODxGreen,MODx
- Added check to oudated assets folders. ie : media, flash (alert info)
- Refer to WebLogin for WebSignup and WebChangePwd alerts - #489

![check-extras](https://user-images.githubusercontent.com/7342798/35747237-d7884eac-0849-11e8-9e43-0e749110e2f6.png)

**Comment by bossloper** [comment]
@Nicola1971 - can close now?

**Comment by fourroses666** [comment]
Maybe the red is a bit too agressive? Just thinking about it, had a client with admin rules and it scared her. Maybe info/message color?

Or maybe leave as is?

**Comment by Nicola1971** [comment]
added MODx rss url check 
check only modx feed url not custom url
![rss-check](https://user-images.githubusercontent.com/7342798/45565924-7fc2bd80-b855-11e8-93e5-9c0291d1c142.png)

> Maybe the red is a bit too agressive? Just thinking about it, had a client with admin rules and it scared her. Maybe info/message color?

@fourroses666 chenged a bit the red

**Comment by fourroses666** [comment]
I have set it visible for admin only.
I always thought it was only visible for me untill some client asked me about it.

While its a warning I don’t think it needs to be red-ish. I’m also oke with light “notice” yellow.

And default set to admin only visible.

I manually have set “all” sites to admin only already.

**Comment by Nicola1971** [comment]
>I have set it visible for admin only.
I always thought it was only visible for me untill some client asked me about it.

100% agree - default should be AdminOnly 
I will fix in this update

Just a red title?
![rss-check](https://user-images.githubusercontent.com/7342798/45568254-6a9d5d00-b85c-11e8-899b-84877d1c43ba.png)

**Comment by fourroses666** [comment]
Yea thats probably the nicest way to do it Nicola!

Verstuurd vanaf mijn iPhone

**Comment by AgelxNash** [comment]
I can close this ticket?
