### ISSUE TITLE
DocLister Extra install gives warning

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#463]
Just to let you know:

Installed fresh Evo (dev) and installed DocLister, did some checkmarks for;
  DDocInfo: Installed
  DLCrumbs: Upgraded
  DLMenu: Upgraded
  DocLister: Upgraded
  DLSitemap: Upgraded

It installed them but also got a warning;

`Warning: in_array() expects parameter 2 to be array, boolean given in /home/xxx/domains/xxx.nl/public_html/xxx/assets/modules/store/installer/instprocessor.php on line 409`

![extra](https://user-images.githubusercontent.com/523389/35392894-8dbc2922-01e3-11e8-8924-5a1adf2659b0.png)

**Comment by fourroses666** [comment]
Can we safely delete the tests root folder?

**Comment by dmi3yy** [comment]
root of DocLister?  yes

**Comment by Pathologic** [comment]
Hope this quick-n-dirty fix helps :smile_cat:
