### ISSUE TITLE
PHP 7.1.13

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#464]
I have a basic install with PHP 7.
Made a copy and moved it on an other server.
Now it seems there is some issue with it.
Cleared browsercache, paths and all.

The home resource is not visible. Can reach it (last edited resource) but the tree isn't showing.
No time to find out whats wrong but I think its an issue with the PHP 7.1.13 and the manager tree

![hmm](https://user-images.githubusercontent.com/523389/35397624-3d75e52c-01f0-11e8-8af3-020740d21552.png)

**Comment by fourroses666** [comment]
Well, was able to use PHP 7.0.27 on the server and still have the problem.
No time to find out at the moment whats wrong.

**Comment by Nicola1971** [comment]
empty tree with php7+ seems this issue https://github.com/evolution-cms/evolution/issues/446

**Comment by fourroses666** [comment]
Correct, now it works.. Thx
