### ISSUE TITLE
Moving forward.  DLMenu and ajaxSearch

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#467]
Hi All,

I've upgraded to 1.4.0 as I've kept up with the RC releases and I like the new compatibility check.

I notice the declaration of index-ajax.php which I use.  What is the preferred method to use ajax within the frontend?  My current ajax is via this file and I've tried to remove the code from my programs but alas it fails!

DLMenu - is declared the replacement for Wayfinder and does what it does.  I've checked the documentation and I cannot find out where there is a "config" parameter.  All of my Wayfinder calls use the config file method so I can keep things clean with out overloading chunks.  Does DLMenu have such a parameter?  I've searched but not found much.

Thanks,
BBloke

**Comment by BBloke** [comment]
Also forgot to ask what is set to replace ajaxSearch? if anything?

**Comment by Pathologic** [comment]
DLMenu is DocLister based, so it supports most parameters of it. DocLister configs are stored in json format, you can see examples in assets/snippets/DocLister/config/core folder.

> config
> 
> Loads parameters from json file.
> 
> Possible values - filename:folder, several values are separated by the semicolon.
> 
> Example
> 
> myparams:core - loads parameters from assets/snippets/DocLister/config/core/myparams.json file; myparams - loads parameters from assets/snippets/DocLister/config/custom/myparams.json file; myparams:assets/myfolder - loads parameters from assets/myfolder/myparams.json file.
> 
> Default value - none.

It's impossible to implement support of Wayfinder configs as is, because of their format. It should be changed even if to array .

**Comment by Pathologic** [comment]
If you prefer to send ajax requests to php file, then the correct way is:
```
define('MODX_API_MODE', true);
include_once(dirname(__FILE__)."/index.php");
$modx->db->connect();
if (empty ($modx->config)) {
    $modx->getSettings();
}
$modx->invokeEvent("OnWebPageInit");

if(!isset($_SERVER['HTTP_X_REQUESTED_WITH']) || (strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) != 'xmlhttprequest')){
        $modx->sendErrorPage();
}
$out = $modx->runSnippet('test');
$return = array('message' => $out);
echo json_encode($return);
```

In simple cases I prefer to create documents with _blank template and put snippet calls there.

**Comment by BBloke** [comment]
Additional to DLMenu above.  I'm having an issue when using my own TPL's.  My current call shows no output of a menu structure apart from the ajaxsearch call.

[[DLMenu?
			&debug=`0`
			&parents=`0`
			&filters=`private`
			&parentClass=`hideentry`
			&selfClass=`current`
			&innerTpl=`@CODE:<ul [+classes+]>[+wrap+]</ul>`
			&outerTpl=`@CODE:<nav id="topnav" role="navigation">
				<div class="menu-toggle">Menu</div>
				<ul class="srt-menu" id="menu-main-navigation">
					
					[+wrap+]
					
					[[AjaxSearch? &tplInput=`asInput` &ajaxSearch=`0` &landingPage=`124` &moreResultsPage=`124` &addJscript=`0` &extract=`0` &showResults=`0` &grabMax=`20` &mbstring=`1` &asLog=`2:1:0` &showIntro=`0` &_debug=`-3` &whereSearch=`content|maxigallery|jot` ]]
				</ul>
			</nav>`
			&parentRowTpl=`@CODE:<li [+classes+]><a href="[+url+]" title="[+title+]">[+longtext+]</a>[+wrap+]</li>`
			&rowTpl=`@CODE:<li [+classes+]><a href="[+url+]" title="[+title+]">[+longtext+]</a>[+wrap+]</li>`
		]]

If I remove Tpl parameters then I get a list of documents which would make up my menu. I removed all but "outerTpl" and still there is no document showing in the menu.  It seems that the [+wrap+] placeholder is not populating at all. 

What am I missing?

**Comment by Pathologic** [comment]
You cannot use snippet calls in inline templates. And there's no longtext placeholder, maybe you mean longtitle.

**Comment by BBloke** [comment]
Thanks @Pathologic 

That's helpful. My error on the longtext.  I changed things around and removed the snippet call.  Still the same output of nothing.

Here's what the above call generates.

`
<nav id="topnav" role="navigation">
				<div class="menu-toggle">Menu</div>
				<ul class="srt-menu " id="menu-main-navigation">
					<li>
	<form id="ajaxSearch_form" action="search-results" method="post">
		<input type="hidden" name="advsearch" value="oneword">
		  <input id="ajaxSearch_input" class="cleardefault" type="text" name="search" value="Search here..." onfocus="this.value=(this.value=='Search here...')? '' : this.value ;">
				<input id="ajaxSearch_submit" type="submit" name="sub" value="Go!" class="ui-button ui-corner-all ui-widget" role="button">
	</form>
</li>
				</ul>
			</nav>
`

**Comment by Pathologic** [comment]
As you are using "private" filter I can suppose that you have no permissions to view 1st level documents. In general, the snippet call is correct (except not existing &selfClass parameter), but it should be uncached because it depends of user type.

**Comment by BBloke** [comment]
Home page is always unrestricted access.  It does seem that is something to do with the Tpl codes.  When I use them in the snippet [+wrap+] doesnt get populated.  If I remove all Tpl code and use the default then everything works as I would expect even with or with "filters".

I think there is a bug somewhere but I don't know where to look for it. I will continue to try though.

**Comment by Pathologic** [comment]
I've tested your snippet call and it works as expected.

**Comment by Pathologic** [comment]
Are you using PHx? Maybe it removes placeholders from DLMenu call.

**Comment by BBloke** [comment]
Mmmmm.. I'm lost then. LOL

I tested:

[!DLMenu?
			&debug=`0`
			&parents=`0`
			&filters=`private`
			&parentClass=`hideentry`
			&selfClass=`current`
		!]

and I got a list correctly populated.
![image](https://user-images.githubusercontent.com/24464015/35439853-924100c4-0294-11e8-89ca-8eee7b68db6d.png)


I then tried:

[!DLMenu?
			&debug=`0`
			&parents=`0`
			&filters=`private`
			&parentClass=`hideentry`
			&selfClass=`current`
			&innerTpl=`@CODE:<ul [+classes+]>[+wrap+]</ul>`
			&parentRowTpl=`@CODE:<li [+classes+]><a href="[+url+]" title="[+title+]">[+menutitle+]</a>[+wrap+]</li>`
		!]

yields the following:
![image](https://user-images.githubusercontent.com/24464015/35439869-b069ac90-0294-11e8-8d2a-2a23ffa2a928.png)

Thats what is odd.

**Comment by Pathologic** [comment]
Try to use chunks instead of @CODE:

**Comment by BBloke** [comment]
Thanks again @Pathologic 

Changing to chunks sees it work as needed.  I do prefer to keep things in a config file as it keeps the chunks section from becoming over populated.  I find it's hard to know what is in use and what I've made redundant over time.

Cheers,

**Comment by Pathologic** [comment]
As for AjaxSearch - just install it from Extras.
