### ISSUE TITLE
DocLister summary length issue

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#469]
In default install the Blog (id 2) has **&summary=`notags,len:350`**
Which results in: 
![screenshot-2018-1-26 blog](https://user-images.githubusercontent.com/6113504/35438616-2176a5d8-028f-11e8-87e6-c2fe354453aa.png)

Setting this to anything larger seems to make no difference (ie. 500)
And setting this to anything below 318 (ie. 317) results in:
![screenshot-2018-1-26 blog2](https://user-images.githubusercontent.com/6113504/35438721-900af9cc-028f-11e8-8a01-8f287c9621df.png)

There seems to be no real control.
Am I missing something?

**Comment by 64j** [comment]
@risingisland 
```
&contentField=``
&introField=`content`
```

**Comment by risingisland** [comment]
Adding this now displays full content, not a summary.

**Comment by 64j** [comment]
```
&summary=`len:500`
```

**Comment by risingisland** [comment]
OK, figured it out. 
Adding **&contentField=`content`** 
Seems to work when not using introtext field
Thanks for the hint.
