### ISSUE TITLE
ditto, eform are not going to be updated in upcoming EVO releases?

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#474]
Hi Dmytro,

well done on 1.4.0 release . Can you confirm that ditto, eform etc are not going to be updated in upcoming EVO releases? we have lots of clients with modx 1.2.1 and some with EVO 1.3.6 .  We don't know what to do with them now. we don't want to move the modx 1.2.1 to evo 1.3.6 as that kills our chance of running a transfer tool which works for modx 1.2.1 to move to modx revo.   For the EVO 1.3.6 , they all need to be rebuilt  now - all the ditto, eform etc are being replaced with your doclister and eformlister so there is a clock ticking on those sites now when they will not be secure and no new updates. any advice?

**Comment by Deesen** [comment]
Maybe this helps reg. support of old snippets:

https://github.com/evolution-cms/evolution/issues/466#issuecomment-360780341
https://github.com/evolution-cms/evolution/issues/466#issuecomment-360781967

If you plan using the new snippets and you still want to be able to use GoRevo for them in future, you need to ask Bob Ray to update GoRevo to support those new snippets.

**Comment by user83743** [comment]
thnaks Deesen.

in your first link:   that developer   risingisland   https://github.com/risingisland   put it very well:

"
From my understanding, the problem is that for the past 5+ years, from Modx v.95 all the way up to Evo v1.36, Ditto, Wayfinder, etc. have been an essential part of the program with support and documentation in English.

A new and improved replacement for these is more than welcome, but there was no transition period nor information in English to help with this transition.

We were only offered a take it or leave it decision.

I dont think anyone is arguing that the new DL replacements aren't better, only that there was no clear information on how to migrate, or a transition period to do so.

At least that has been my take on the original portion of this thread.
"

**Comment by dmi3yy** [comment]
If you look at REVO, you'll see that there all the add-ons are developed separately from the kernel. We are doing the same thing now in EVO.

At the moment, all add-ons work on version 1.4.0 of Ditto eForm Wayfindek and others. Nobody talks about the fact that they need to be thrown away and not updated. Simply in the same REVO new more convenient tools also appear and there is no sense not to use them.

I wrote in the next topic that https://github.com/extras-evolution/ is the official add-on repository for EVO, and support continues in it. If you have questions and suggestions on what that additions, then write there and that's it.

I myself have a lot of client sites on the Ditto eForm Wayfinder where it is not advisable to spend time transferring to other snippets, but you need to update the kernel.

I have already explained more than once that EVO develops not worse than REVO and that the number of children involved in development is nothing less. Simply REVO has more marketing here is an example: 
http://take.ms/PIiPW

If you are worried that we will abandon the development of the EVO and will need to move on to REV then I want to say that I have more than 500 projects behind me and if I abandon the EVO I will need to transfer them all to REVO, which means that I will not do it by hand and I'll have to write a tool that will automate the process :) I also want to note that website development is my main activity. Ie I develop EVO not only as a hobby but also as my working tool due to which I live and my team in which there are already more than 10 people.

Still very interesting statistics on runetu
http://www.cmsmagazine.ru/catalogue/?sk=_works&box=&st=&bt=&ctl=&cpp=40&&so=desc

Evolution CMS -  4 place 
MODX - 8 Place

**Comment by user83743** [comment]
thanks again Dymtro.

i can name 6+ developers in the earlier threads who would love to have seen your email above at the top of the release docs :) . the release docs were a bit confusing, but I am happier you have added the above. here is where the confusion started I believe:

In github entry #465 it says:

"
< 1.3 not support
1.3.* only security support
1.4.* security and bug fix
1.5.0 new develop version
"

and on https://github.com/evolution-cms/evolution/releases it says:

"
The main emphasis of this release is stability of the system, as well as updating and replacing old snippets by new ones.
"


that gives off a strong signal of "by by old - hello new snippets". thanks for adding your comments above. the non Dymtro-standard website builders (~~designers) need those ditto, wayfinder, eform etc to be kept (as an extra) in the EVO 1.4.0 and 1.5.0 etc so that we can take some time to get used to using the new snippets on a test website, find docs and then use the new snippets just as we used the use the old snippets. i'll gladly say by by to all old snippets over a ~~2 years period. i have a test site and it has EVO 1.3.6 so i will gladly put 1.4.0 on it and try the new snippets - but we can't do that all of a sudden. we need a good lead in timeframe. for some client websites we will have to wait for the next "website upgarde" and then try the new snippets with EVO 1.4.0.  those are my thoughts :) .  thanks again for all your intergalactic code work! :)

**Comment by risingisland** [comment]
Hello @user83743, 
Basically what dmi3yy is saying is that extras like Ditto, Wayfinder, etc. all currently work with the current Evo 1.4 and should continue to work with future releases, but are no longer being bundled with the package. Much like Revo, they will be separate (`https://github.com/extras-evolution/`), and supported in there respective channels.

**Comment by dmi3yy** [comment]
This mean: 
< 1.3 not support.   => no more new version like 1.2.3 
1.3.* only security support  => if found security bug will be new version 1.3.7 
1.4.* security and bug fix => if found any bugs will be new version 1.4.1 + 
1.5.0 new develop version => now we start work on next version

**Comment by dmi3yy** [comment]
about extras i want do like in October CMS: 
- separate  CODE and Extras 
- add Extras on install page were you can select what install with core. (And add favorite list of extras by default  i think this better then now in REVO, where need prepare own package or instal one by one) 
- add Widget like Updater but for Extras

**Comment by user83743** [comment]
@dmi3yy 

but that updated above only refers to the **CORE** - no mention of OLD or NEW snippets.............

"
This mean:
< 1.3 not support. => no more new version like 1.2.3
1.3.* only security support => if found security bug will be new version 1.3.7
1.4.* security and bug fix => if found any bugs will be new version 1.4.1 +
1.5.0 new develop version => now we start work on next version
"

**Comment by user83743** [comment]
thanks @risingisland 

 all snippets need to move with the EVOLUTION 1.3.* --->  1.4.0 --> 1.5.*  releases for the next 2 years, if possible, to give everyone time to get some documentation, try out the snippets )most of use have never used any of the new snippets) and keep all evo/modx cores upgraded and at the same time slowly start to use the new snippets.  eventually using nothing but the new snippets.  this allows us all of have a security upgraded core all the time and security upgraded set of snippets (old and new). is that possible? :)

**Comment by dmi3yy** [comment]
> but that updated above only refers to the CORE - no mention of OLD or NEW snippets.............
Yes, support for add-ons is simply separate for there is no point in updating the whole core if we find and fix the error in Ditto. This will give more freedom + easier to update sites will be.

**Comment by user83743** [comment]
@dmi3yy 

THAT IS THE PERFECT SETUP THAT YOU SUGGESTED: 

---separate CODE and Extras
---add Extras on install page were you can select what install with core. (And add favorite list of extras by default i think this better then now in REVO, where need prepare own package or install one by one)
---add Widget like Updater but for Extras

BUT CAN YOU ADD TO THAT THAT SECURITY UPDATES (not added functionality) WILL be maintained for eform, ditto, wayfinder etc so that we have time to start using doclister , formlister etc and the migration will be smooth for everyone?

**Comment by dmi3yy** [comment]
> BUT CAN YOU ADD TO THAT THAT SECURITY UPDATES (not added functionality) WILL be maintained for eform, ditto, wayfinder etc so that we have time to start using doclister , formlister etc and the migration will be smooth for everyone?

Yes!

**Comment by user83743** [comment]
@dmi3yy 

perfect. no need to update the core if ditto or doclister is where the new code is. and no need to update doclister or ditto if it's the EVOLUTION 1.4.* or 1.5.* CORE THAT IS being updated. 

and you confirmed my other questions about keeping ditto, wayfinder, eform etc security updated (no new requirements or features) as we all move from old snippets to new snippets.  and at the same time keep the core upgraded.

much appreciated Dymtro - for taking the time to confirm those details which are important to all of us. have a good Saturday.

**Comment by Deesen** [comment]
I have also modified the release-info at https://github.com/evolution-cms/evolution/releases/tag/1.4.0 and added a "(**don´t worry, old snippets will still be supported** via Evolution Extras)" to it.

**Comment by user83743** [comment]
Thanks @Deesen . much appreciated.
