### ISSUE TITLE
Missing hover style for TV Insert

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#475]
The insert button for File and Image TVs is missing any sort of style feedback for hover.
Maybe 'btn btn-secondary' class as used on the Menu Index decrease/increase buttons?

![untitled](https://user-images.githubusercontent.com/1744687/35471288-06799904-0350-11e8-9071-17300b000731.png)

**Comment by 64j** [comment]
@bossloper 
Ok, I'll fix it a little later.
