### ISSUE TITLE
Some minor upgrade issues

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#476]
I noticed a couple of things when upgrading / using EVO 1.4;

- Quick Manager is set on as default. _(site scripts stopped working because of it, I don't use QM)_
- Doesn't remember your latest position after saving. _(filemanager when editing a css/js file for instance)_

- If I'm right, when upgrading eForm from Extras it creates default chunks like `eFeedback`. Is that needed?

**Comment by Nicola1971** [comment]
1) I use QM, but i agree - is better disabled as default  (easy conflicts with front end themes)
2) worked before? Never noticed.
3) i think we need extras install options (select/deselect componentents) in upgrade process.
When you need to upgrade a complex package you don't want to install/overwrite chunks, tv ... just package core snippets, modules and plugins

**Comment by fourroses666** [comment]
1. Indeed, thats what happened on a site and took a while to know what was happening. :(
I set it disabled in the previous version but the options/settings where overwritten, now on every update I need to disable it..
2. Well not working with me, after saving its back to the top. Doesn't remember my last position. (iMac and Firefox)
3. Yea, DocLister does have the options / checkboxes.

**Comment by Nicola1971** [comment]
In every upgrade I always do a plugin check to:
1) codemirror - if codemirrow does not work a lot of plugins does not work 
2) tinymce 
3) manager manager - to restore the chunk name (I always use sitename-mmrules )
4) quick manager - used or not - always check to configuration

**Comment by leonie12** [comment]
Since at least  some minor versions userHelper is reenabled after every update. I have to disable it after every update manually again because here it does not work with using weblogin. I think the update of plugins should respect the enabled/disabled setting and not change it.

**Comment by Nicola1971** [comment]
Just checked - both quick manager and userHelper are disabled as default, i think is related to plugin config issue:
https://github.com/evolution-cms/evolution/issues/477

**Comment by bossloper** [comment]
I have noticed TinyMCE4 always gets disabled after an update even if it was enabled before.

**Comment by fourroses666** [comment]
So basicly it needs to remember last setting (enabled/disabled) on upgrades.
On new install its a different story. Enable all plugins (except QM?)

**Comment by dmi3yy** [comment]
No need use Legacy name same the  name ) then all work correct ) 

Enable all exept QM and ElementsTree

**Comment by fourroses666** [comment]
Will close for now.
