### ISSUE TITLE
Upgrade causes plugin configuration issues

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#477]
I have upgraded a site from modx 1.0.15 to evo 1.4 latest dev
Issue I have is the added plugins do not seem to be returning the plugin configuration values correctly to the code. I had the issue with ManagerManager first. It would not pick up the mm_rules file. Accidentally fixed it by altering a MM config setting and resaving the plugin.

Now CodeMirror seems to have a similar issue. I.e. although an active plugin it is not working.
I see a js error and it is not placing the properties correctly into the code and so failing:
![untitled](https://user-images.githubusercontent.com/1744687/35475365-2d906da2-0395-11e8-92c8-01e63168bfab.png)
... note the missing true/false values for matchingBrackets, lineWrapping,styleActiveLine and indentWithTabs.
I have not tried altering the plugin properties and resaving yet as it may well then work again. So if there is anything else I can check to help debug it first?

I also suspect it is the same issue @fourroses666 mentioned here (about needing to resave): https://github.com/evolution-cms/evolution/issues/433#issuecomment-359400029

**Comment by Nicola1971** [comment]
I think is the old "plugin upgrade" issue, never really solved.
normally happen when you update to the same version of the plugin (ie: when you move from evo beta > rc1 > rc2..), rarely when you ugrade to a different version.

In this recent period happened very often also when i test updates of my "extras" with Package Manager.

**Comment by fourroses666** [comment]
Might be you are on to something bossloper :o

**Comment by bossloper** [comment]
If it means anything to anyone I dumped the event params array for CodeMirror.
This is for a working plugin:
`Array ( [theme] => default [darktheme] => one-dark [fontSize] => 14 [lineHeight] => 1.3 [indentUnit] => 4 [tabSize] => 4 [lineWrapping] => true [matchBrackets] => true [activeLine] => false [emmet] => true [search] => false [indentWithTabs] => true [undoDepth] => 200 [historyEventDelay] => 1250 [id] => 5 ) 1`
This is the failing one from an upgraded install:
`Array ( [{"theme":[{"label":"Theme","type":"list","value":"default","options":"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light","default":"default","desc":""}],"darktheme":[{"label":"Dark Theme","type":"list","value":"one-dark","options":"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light","default":"one-dark","desc":""}],"fontSize":[{"label":"Font-size","type":"list","value":"14","options":"10,11,12,13,14,15,16,17,18","default":"14","desc":""}],"lineHeight":[{"label":"Line-height","type":"list","value":"1.3","options":"1,1.1,1.2,1.3,1.4,1.5","default":"1.3","desc":""}],"indentUnit":[{"label":"Indent unit","type":"int","value":"4","default":"4","desc":""}],"tabSize":[{"label":"The width of a tab character","type":"int","value":"4","default":"4","desc":""}],"lineWrapping":[{"label":"lineWrapping","type":"list","value":"true","options":"true,false","default":"true","desc":""}],"matchBrackets":[{"label":"matchBrackets","type":"list","value":"true","options":"true,false","default":"true","desc":""}],"activeLine":[{"label":"activeLine","type":"list","value":"false","options":"true,false","default":"false","desc":""}],"emmet":[{"label":"emmet","type":"list","value":"true","options":"true,false","default":"true","desc":""}],"search":[{"label":"search","type":"list","value":"false","options":"true,false","default":"false","desc":""}],"indentWithTabs":[{"label":"indentWithTabs","type":"list","value":"true","options":"true,false","default":"true","desc":""}],"undoDepth":[{"label":"undoDepth","type":"int","value":"200","default":"200","desc":""}],"historyEventDelay":[{"label":"historyEventDelay","type":"int","value":"1250","default":"1250","desc":""}]}] => [configs] => event_log [id] => 133 ) 1`

Looks like the failing one is returning the raw install string instead of the actual parameters??

**Comment by Nicola1971** [comment]
Not to me, sorry :smile:

Wait for serious coders like @Pathologic or @64j.

**Comment by Deesen** [comment]
I will look into it as I updated Codemirror, thanks @bossloper !

**Comment by bossloper** [comment]
Great. The fact I see the same parameter problem with ManagerManager too might suggest an issue with the install code rather than the plugins themselves??

**Comment by Deesen** [comment]
I think so too because I made no changes at all at param "matchBrackets" or any else. So I will test a 1.0.15 default installation, and update it to latest dev, and hope I can recreate this issue that way.

**Comment by bossloper** [comment]
@Deesen If it helps I took a database snapshot of the system after upgrade and while CodeMirror was not working.
I then resaved the plugin, which made it work, and took an new snapshot. The only significant change (as you would expect) was on the modx_site_plugins table.
Here is the row before (not working):
`(72, 'CodeMirror', '<strong>1.5</strong> JavaScript library that can be used to create a relatively pleasant editor interface based on CodeMirror 5.33 (released on 21-12-2017)', 0, 21, 0, '/**\r\n * CodeMirror\r\n *\r\n * JavaScript library that can be used to create a relatively pleasant editor interface based on CodeMirror 5.33 (released on 21-12-2017)\r\n *\r\n * @category    plugin\r\n * @version     1.5\r\n * @license     http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)\r\n * @package     evo\r\n * @internal    @events OnDocFormRender,OnChunkFormRender,OnModFormRender,OnPluginFormRender,OnSnipFormRender,OnTempFormRender,OnRichTextEditorInit\r\n * @internal    @modx_category Manager and Admin\r\n * @internal    @properties &theme=Theme;list;default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light;default &darktheme=Dark Theme;list;default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light;one-dark &fontSize=Font-size;list;10,11,12,13,14,15,16,17,18;14 &lineHeight=Line-height;list;1,1.1,1.2,1.3,1.4,1.5;1.3 &indentUnit=Indent unit;int;4 &tabSize=The width of a tab character;int;4 &lineWrapping=lineWrapping;list;true,false;true &matchBrackets=matchBrackets;list;true,false;true &activeLine=activeLine;list;true,false;false &emmet=emmet;list;true,false;true &search=search;list;true,false;false &indentWithTabs=indentWithTabs;list;true,false;true &undoDepth=undoDepth;int;200 &historyEventDelay=historyEventDelay;int;1250\r\n * @internal    @installset base\r\n * @reportissues https://github.com/evolution-cms/evolution/issues/\r\n * @documentation Official docs https://codemirror.net/doc/manual.html\r\n * @author      hansek from http://www.modxcms.cz\r\n * @author      update Mihanik71\r\n * @author      update Deesen\r\n * @author      update 64j\r\n * @lastupdate  08-01-2018\r\n */\r\n\r\n$_CM_BASE = \'assets/plugins/codemirror/\';\r\n\r\n$_CM_URL = $modx->config[\'site_url\'] . $_CM_BASE;\r\n\r\nrequire(MODX_BASE_PATH. $_CM_BASE .\'codemirror.plugin.php\');', 0, '{\r\n  \"theme\": [\r\n    {\r\n      \"label\": \"Theme\",\r\n      \"type\": \"list\",\r\n      \"value\": \"default\",\r\n      \"options\": \"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light\",\r\n      \"default\": \"default\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"darktheme\": [\r\n    {\r\n      \"label\": \"Dark Theme\",\r\n      \"type\": \"list\",\r\n      \"value\": \"one-dark\",\r\n      \"options\": \"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light\",\r\n      \"default\": \"one-dark\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"fontSize\": [\r\n    {\r\n      \"label\": \"Font-size\",\r\n      \"type\": \"list\",\r\n      \"value\": \"14\",\r\n      \"options\": \"10,11,12,13,14,15,16,17,18\",\r\n      \"default\": \"14\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"lineHeight\": [\r\n    {\r\n      \"label\": \"Line-height\",\r\n      \"type\": \"list\",\r\n      \"value\": \"1.3\",\r\n      \"options\": \"1,1.1,1.2,1.3,1.4,1.5\",\r\n      \"default\": \"1.3\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"indentUnit\": [\r\n    {\r\n      \"label\": \"Indent unit\",\r\n      \"type\": \"int\",\r\n      \"value\": \"4\",\r\n      \"default\": \"4\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"tabSize\": [\r\n    {\r\n      \"label\": \"The width of a tab character\",\r\n      \"type\": \"int\",\r\n      \"value\": \"4\",\r\n      \"default\": \"4\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"lineWrapping\": [\r\n    {\r\n      \"label\": \"lineWrapping\",\r\n      \"type\": \"list\",\r\n      \"value\": \"true\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"true\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"matchBrackets\": [\r\n    {\r\n      \"label\": \"matchBrackets\",\r\n      \"type\": \"list\",\r\n      \"value\": \"true\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"true\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"activeLine\": [\r\n    {\r\n      \"label\": \"activeLine\",\r\n      \"type\": \"list\",\r\n      \"value\": \"false\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"false\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"emmet\": [\r\n    {\r\n      \"label\": \"emmet\",\r\n      \"type\": \"list\",\r\n      \"value\": \"true\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"true\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"search\": [\r\n    {\r\n      \"label\": \"search\",\r\n      \"type\": \"list\",\r\n      \"value\": \"false\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"false\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"indentWithTabs\": [\r\n    {\r\n      \"label\": \"indentWithTabs\",\r\n      \"type\": \"list\",\r\n      \"value\": \"true\",\r\n      \"options\": \"true,false\",\r\n      \"default\": \"true\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"undoDepth\": [\r\n    {\r\n      \"label\": \"undoDepth\",\r\n      \"type\": \"int\",\r\n      \"value\": \"200\",\r\n      \"default\": \"200\",\r\n      \"desc\": \"\"\r\n    }\r\n  ],\r\n  \"historyEventDelay\": [\r\n    {\r\n      \"label\": \"historyEventDelay\",\r\n      \"type\": \"int\",\r\n      \"value\": \"1250\",\r\n      \"default\": \"1250\",\r\n      \"desc\": \"\"\r\n    }\r\n  ]\r\n}', 0, 'Â ', 0, 1517149251),` 

and here is row after (working):
`(72, 'CodeMirror', '<strong>1.5</strong> JavaScript library that can be used to create a relatively pleasant editor interface based on CodeMirror 5.33 (released on 21-12-2017)', 0, 21, 0, '\r\n/**\r\n * CodeMirror\r\n *\r\n * JavaScript library that can be used to create a relatively pleasant editor interface based on CodeMirror 5.33 (released on 21-12-2017)\r\n *\r\n * @category    plugin\r\n * @version     1.5\r\n * @license     http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)\r\n * @package     evo\r\n * @internal    @events OnDocFormRender,OnChunkFormRender,OnModFormRender,OnPluginFormRender,OnSnipFormRender,OnTempFormRender,OnRichTextEditorInit\r\n * @internal    @modx_category Manager and Admin\r\n * @internal    @properties &theme=Theme;list;default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light;default &darktheme=Dark Theme;list;default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light;one-dark &fontSize=Font-size;list;10,11,12,13,14,15,16,17,18;14 &lineHeight=Line-height;list;1,1.1,1.2,1.3,1.4,1.5;1.3 &indentUnit=Indent unit;int;4 &tabSize=The width of a tab character;int;4 &lineWrapping=lineWrapping;list;true,false;true &matchBrackets=matchBrackets;list;true,false;true &activeLine=activeLine;list;true,false;false &emmet=emmet;list;true,false;true &search=search;list;true,false;false &indentWithTabs=indentWithTabs;list;true,false;true &undoDepth=undoDepth;int;200 &historyEventDelay=historyEventDelay;int;1250\r\n * @internal    @installset base\r\n * @reportissues https://github.com/evolution-cms/evolution/issues/\r\n * @documentation Official docs https://codemirror.net/doc/manual.html\r\n * @author      hansek from http://www.modxcms.cz\r\n * @author      update Mihanik71\r\n * @author      update Deesen\r\n * @author      update 64j\r\n * @lastupdate  08-01-2018\r\n */\r\n\r\n$_CM_BASE = \'assets/plugins/codemirror/\';\r\n\r\n$_CM_URL = $modx->config[\'site_url\'] . $_CM_BASE;\r\n\r\nrequire(MODX_BASE_PATH. $_CM_BASE .\'codemirror.plugin.php\');', 0, '{\"theme\":[{\"label\":\"Theme\",\"type\":\"list\",\"value\":\"default\",\"options\":\"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light\",\"default\":\"default\",\"desc\":\"\"}],\"darktheme\":[{\"label\":\"Dark Theme\",\"type\":\"list\",\"value\":\"one-dark\",\"options\":\"default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,one-dark,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light\",\"default\":\"one-dark\",\"desc\":\"\"}],\"fontSize\":[{\"label\":\"Font-size\",\"type\":\"list\",\"value\":\"14\",\"options\":\"10,11,12,13,14,15,16,17,18\",\"default\":\"14\",\"desc\":\"\"}],\"lineHeight\":[{\"label\":\"Line-height\",\"type\":\"list\",\"value\":\"1.3\",\"options\":\"1,1.1,1.2,1.3,1.4,1.5\",\"default\":\"1.3\",\"desc\":\"\"}],\"indentUnit\":[{\"label\":\"Indent unit\",\"type\":\"int\",\"value\":\"4\",\"default\":\"4\",\"desc\":\"\"}],\"tabSize\":[{\"label\":\"The width of a tab character\",\"type\":\"int\",\"value\":\"4\",\"default\":\"4\",\"desc\":\"\"}],\"lineWrapping\":[{\"label\":\"lineWrapping\",\"type\":\"list\",\"value\":\"true\",\"options\":\"true,false\",\"default\":\"true\",\"desc\":\"\"}],\"matchBrackets\":[{\"label\":\"matchBrackets\",\"type\":\"list\",\"value\":\"true\",\"options\":\"true,false\",\"default\":\"true\",\"desc\":\"\"}],\"activeLine\":[{\"label\":\"activeLine\",\"type\":\"list\",\"value\":\"false\",\"options\":\"true,false\",\"default\":\"false\",\"desc\":\"\"}],\"emmet\":[{\"label\":\"emmet\",\"type\":\"list\",\"value\":\"true\",\"options\":\"true,false\",\"default\":\"true\",\"desc\":\"\"}],\"search\":[{\"label\":\"search\",\"type\":\"list\",\"value\":\"false\",\"options\":\"true,false\",\"default\":\"false\",\"desc\":\"\"}],\"indentWithTabs\":[{\"label\":\"indentWithTabs\",\"type\":\"list\",\"value\":\"true\",\"options\":\"true,false\",\"default\":\"true\",\"desc\":\"\"}],\"undoDepth\":[{\"label\":\"undoDepth\",\"type\":\"int\",\"value\":\"200\",\"default\":\"200\",\"desc\":\"\"}],\"historyEventDelay\":[{\"label\":\"historyEventDelay\",\"type\":\"int\",\"value\":\"1250\",\"default\":\"1250\",\"desc\":\"\"}]}', 0, '', 0, 0),`

Seems to be a lot of \r\n in the not working version, which after a resave are removed?

**Comment by bossloper** [comment]
@Deesen one last bit of investigation.

PropUpdate is used when adding plugins (if one already exists) here:
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L569
and here:
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L584
... which cause the failed plugin until resaved.

but for a fresh install it will use this line where propUpdate is not applied:
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L592
... which plugins do work as expected.

... and propUpdate involves json_encode function ... which includes \r\n after which I am out of my depth again, but think I am close! :-)

**Comment by Deesen** [comment]
\r\n is a line-break, and it looks like your "none-working" json-configuration was saved using JSON_PRETTY_PRINT (so its human-readable with line-breaks and indents). JSON_PRETTY_PRINT is only applied through Javascript, when opening a plugin for edit. When saving a plugin these \r\n will occur in the DB. But the \r\n should not lead to errors, at least for me it was never case.

As 1.0.15 did not have the JSON-config-feature, and \r\n only occurs when editing and saving a plugin, I am wondering why your none-working config example is in JSON-Format with \r\n?

**Comment by bossloper** [comment]
My only thought is why is adding a new plugin not using parseProperties but adding a replacement plugin does used parseProperties ... which ultimately causes an issue until the plugin is re-saved.

**Comment by Deesen** [comment]
For a new installation of plugins etc only parseProperties() is necessary, but to update existing ones propUpdate() is used to add new options of a plugin that might not exist in the previous versions config: 
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L783-L795

If really propUpdate() is the reason, maybe a `&& isset($newArr[$k]['0']['options'])` helps?
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L787

Ormaybe something weird is going on here but I´m not sure:
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L791

Is it possible you prepare a small SQL-dump only of table "site_plugins" BEFORE an update and send it to me? Maybe I can recreate the issue that way here.

**Comment by bossloper** [comment]
For the plugin before any upgrade (modx 1.0.15) the parameters are not in json format? Maybe that is the key to this:
`(54, 'CodeMirror', '<strong>1.2b</strong> JavaScript library that can be used to create a relatively pleasant editor interface based on CodeMirror 3.13', 0, 21, 0, '$_CM_BASE = \'assets/plugins/codemirror/\';\r\n\r\n$_CM_URL = $modx->config[\'site_url\'] . $_CM_BASE;\r\n\r\nrequire(MODX_BASE_PATH. $_CM_BASE .\'codemirror.plugin.php\');\r\n\r\n', 0, '&theme=Theme;list;default,ambiance,blackboard,cobalt,eclipse,elegant,erlang-dark,lesser-dark,midnight,monokai,neat,night,rubyblue,solarized,twilight,vibrant-ink,xq-dark,xq-light; &indentUnit=Indent unit;int;4 &tabSize=The width of a tab character;int;4 &lineWrapping=lineWrapping;list;true,false;true &matchBrackets=matchBrackets;list;true,false;true &activeLine=activeLine;list;true,false;false &emmet=emmet;list;true,false;true &search=search;list;true,false;true &indentWithTabs=indentWithTabs;list;true,false;true', 1, 'Â '),`

**Comment by Deesen** [comment]
If so I don´t understand how it is related because parseProperties() handles old format 
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L806

as well as new JSON-format
https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L835

Maybe there is some special characters in your site_plugins-table / plugin-config causing issues? For example I am wondering where the `'Â '` comes from.

**Comment by bossloper** [comment]
Just done some more tests and it is not just updated plugins that have the issue.
For example OutdatedExtrasCheck does not exist on 1.0.15 but after the upgrade it is not doing the correct checks because it is not reading the properties with the version numbers in. Again after resaving the plugin it is fine.

I am going to do some more tests to see if I can narrow it down, but I suspect all plugins are affected but depending on how it handles default values and properties it might not be obvious a plugin is not picking up the properties.

**Comment by Nicola1971** [comment]
@bossloper you are right **this happen with all plugins**.
As i said before - i encoutered this issue everytime i update my extras in development.
You can see some examples of related issues:

https://github.com/Nicola1971/DashboardListDoc-widget/issues/5#issuecomment-353585645

https://github.com/Nicola1971/EvoFLAT-SystemSettings/issues/1#issuecomment-344721970

**Comment by bossloper** [comment]
Wow, spent most of the day on this and still no idea. I can clear out the database properties field on a working version and it still works. But also clear out the database properties field on a not working version and it still does NOT work, so there is something else about a new install vs an update that I cannot identify...

**Comment by Deesen** [comment]
Thanks for your big efforts! Really strange... what if you manually delete `assets/cache/siteCache.idx.php`. Does a plugin work then, without resaving it?

**Comment by bossloper** [comment]
no deleting file did not help :-(
There is something deep inside an early install that is causing the issue.
Been checking database charsets but still not a clue...

**Comment by Deesen** [comment]
I just had another idea.. I replaced the parseProperties() of instprocessor.php with the one of document.parser, which is also used when resaving a plugin. Maybe this helps?

[instprocessor.zip](https://github.com/evolution-cms/evolution/files/1674886/instprocessor.zip)

**Comment by bossloper** [comment]
you might be onto something! That seemed to have worked!! ... but early days and late nights. Will recheck tomorrow...

**Comment by bossloper** [comment]
Hmmm. Think it was a little late last night. Does not seem to work. :-(

**Comment by Deesen** [comment]
I have no more ideas except a DB-dump at least of your site_plugins before an upgrade, so I can try to recreate the issue on my localhost this way.

**Comment by bossloper** [comment]
I don't think that will help as I can even truncate the site_plugins table, run the upgrade and they still do not pick up the properties until the plugin is resaved. Bizarre!

I'm sure this is very significant: https://github.com/evolution-cms/evolution/issues/477#issuecomment-361011148

**Comment by bossloper** [comment]
Getting somewhere. It is to do with the 'Â ' value in moduleguid field. But just a value needs to be there for it to work in my 1.0.15 installation. 
I.e. I can edit the moduleguid database field direct, add in any value (except space) e.g. x or even a . to that field and the plugin then works and picks up the parameter values (being careful to clear siteCache.idx.php each time).
For a clean install it makes no difference what is in moduleguid plugins always works.

**Comment by Deesen** [comment]
How often does this 'Â ' occur in your whole DB as moduleguid? Only for plugins or also for other components?

**Comment by risingisland** [comment]
@Deesen Where are you finding this 'Â ' located? I would like to take a look at mine to see if this is the reason it is happening to me too.

**Comment by Deesen** [comment]
In the EVO-DB, table "site_plugins", column "moduleguid".

Also I found out after a clean fresh 1.0.15 install the moduleguid of Codemirror is a single space.

**Comment by bossloper** [comment]
@Deesen I see it in site_snippets too after saving a snippet. Also see same in a clean 1.4 dev install.

**Comment by risingisland** [comment]
OK, going to create a clean install with the latest dev and look at the before and after to see if it is the same problem on mine.

**Comment by bossloper** [comment]
@Deesen do you know where $modx_manager_charset is defined?
https://github.com/evolution-cms/evolution/blob/develop/manager/frames/1.php#L108

If I hardcode in Latin1 here then I believe (more tests to do!) it fixes things for my setup.

**Comment by Deesen** [comment]
What a strange issue... I don´t know exactly what I am doing. Just guessing and try & error.

I found out that cache_sync for plugins does not handle json-format correctly (no use of parseProperties etc):
https://github.com/evolution-cms/evolution/blob/develop/manager/processors/cache_sync.class.processor.php#L312

while it does correctly for snippets:

https://github.com/evolution-cms/evolution/blob/develop/manager/processors/cache_sync.class.processor.php#L288-L293

So I fixed that part. But I am almost sure this is not the solution.

[cache_sync.class.processor.zip](https://github.com/evolution-cms/evolution/files/1677773/cache_sync.class.processor.zip)

**Comment by Deesen** [comment]
$modx_manager_charset is defined in language-files like https://github.com/evolution-cms/evolution/blob/develop/manager/includes/lang/english.inc.php#L17

**Comment by bossloper** [comment]
ok thanks. Scrap that as a fix though, I must not have cleared the site cache at one test.

**Comment by bossloper** [comment]
I am cautiously optimistic that the cache_sync fix has done the job...

**Comment by bossloper** [comment]
I have changed so much on this test setup I think I will test again from scratch just to be sure ;-). But it does look like that works. Great work @Deesen !!

Also the virtually unrelated issue of 'Â ' is fixed by changing the $modx_manager_charset to 'Latin1' for my particular database configuration.
Should $modx_manager_charset be a system option that can be configured on the manager interface?

**Comment by Deesen** [comment]
That would be fantastic and unexpected!

Reg. charset, I am not 100% sure. Maybe a "default" (taking setting from lang-file) and "custom"-setting could make sense to be flexible in situations like yours. But I guess it can lead to issues with umlauts when switching on a live-site? Probably @dmi3yy or somebody else knows better.

**Comment by bossloper** [comment]
The unexpected is tested again and confirmed working.
Fresh copy of my 1.0.15 site. Updated with 1.4dev (and modified cache_sync.class.processor file). Plugins all working fine without any re-saving needed. I think it is ready for a commit.

**Comment by Deesen** [comment]
Ok then I will commit. Thanks for your big efforts!

**Comment by bossloper** [comment]
Thanks @Deesen . And I think what you ultimately found that solved it will help greatly with stability and kill off some unpredictable system behaviour.
