### ISSUE TITLE
Постоянная блокировка при попытке sql-запроса Инструмента "Резервное копирование"

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#479]
Через раз, а то и 2 раза их 3 при попытке отправить sql-запрос в "инструменты - резервное копирование - восстановить - Выполнить произвольную команду SQL" выскакивает alert, что ресурс редактируется. Приходится постоянно сбрасывать блокировки. Видимо что-то не так в этих строках
https://github.com/evolution-cms/evolution/blob/develop/manager/actions/bkmanager.static.php#L707-L709

**Comment by dmi3yy** [comment]
Все логично если есть хоть 1 елемент который редактируется, то есть с него не корректно вышли или не закрыли то не дает выполнить что либо в резервном копировании. 

Это актуально если 2 человека параллельно работают в админке поэтому и стоит такая защита
