### ISSUE TITLE
EVO 1.4 - added new(first) TV but doesn't show up in the tree (ElementTree)

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#480]
Added a new TV but doesn't show up in the tree.
After logout and login the manager again it was there.
So I think it needs an automatic tree update?
(I used the + sign in the tree to add the (first) TV.)

BTW: It does work when there already is a TV in the tree.

![tv](https://user-images.githubusercontent.com/523389/35506250-f863e12c-04e8-11e8-9f9f-52aa0c0b027c.png)

**Comment by Nicola1971** [comment]
happened when you started with no tvs?

try to add the tv to a category.

**Comment by fourroses666** [comment]
correct, when having no TVs it happens.
adding to category didn't work.

when removing all TVs (did that to test again) I got an message.
the seo-omschrijving was deleted here and then this:
![delete](https://user-images.githubusercontent.com/523389/35515162-b1702d78-0508-11e8-842c-a580db885c4e.png)

**Comment by fourroses666** [comment]
btw. reload button didn't work, full page refresh did work. after that the TVs where visible. (cleared cache in the manager but don't know if thats needed
minor thing but it is a tiny bug.

**Comment by dmi3yy** [comment]
Now all work correct test on 1.4.2
