### ISSUE TITLE
Пользователь с ограниченными правами

### ISSUE THREAD

**Issue by kivamp** [evolution-cms/evolution#482]
Evo 1.4
Пользователь с ограниченными правами в админке (/manager)
console.error:
SyntaxError: expected expression, got '}' manager:320:11

**Comment by kivamp** [comment]
manager/frames/1.php:529

**Comment by pmfx** [comment]
Fixed with https://github.com/evolution-cms/evolution/commit/6a754cc4bf2e4635536b389b0ef43dbae60435be

**Comment by dmi3yy** [comment]
Fix like this need pull in develop and 1.4.bugfix brunch

**Comment by pmfx** [comment]
Ah, right, done https://github.com/evolution-cms/evolution/commit/f00cd32f051cd4eb5d497086c2f2ecddcdf920a3
