### ISSUE TITLE
Tinymce plugin question

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#483]
I am trying to add a new plugin that requires image path to be set in the config.
I have added the following to the TinyMCE4 plugin "Custom Parameters":

`bootstrapConfig: {
                   'imagesPath': '[(base_path)]assets/images/',
                    'type': 'dropdownMenu',
					'dropdownText': 'Custom Button Text',
					'bootstrapElements': { 
						'btn': true,
						'snippet': false,
            'image': true,
					}
                },`

But I dont know what to add in "imagesPath" to get it to work?

**Comment by Deesen** [comment]
You need to download and replace
https://github.com/evolution-cms/evolution/blob/develop/assets/lib/class.modxRTEbridge.php

and then use [+base_path+] instead of [(base_path)] . Not tested but should work.

**Comment by risingisland** [comment]
Unfortunately, this does not seem to be working for me.

**Comment by Deesen** [comment]
Which tinymce-plugin do you want to use? Is there a documentation?

**Comment by risingisland** [comment]
Its a [Bootstrap toolbar](http://tinymce-bootstrap-plugin.creation-site.org/index.html), but there doesnt seem to me much in the way of documentation.
I think I have it almost working now, by entering the full address instead of using base_path.

**Comment by risingisland** [comment]
Contacting developer, I dont think this is an Evo issue.
