### ISSUE TITLE
WebSignup and WebChangePwd not in Extras

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#489]
On an updated site 'Extras compatibility check' is showing WebSignup needs updating to 1.1.2 from Extras. But it is not in Extras?

**Comment by Nicola1971** [comment]
WebSignup and WebChangePwd are part of Weblogin package
https://github.com/extras-evolution/Weblogin/blob/master/install/assets/snippets/

**Comment by Nicola1971** [comment]
Updated Weblogin description and readme on 
https://github.com/extras-evolution/Weblogin

And Updated Weblogin description on extras 
![weblogin](https://user-images.githubusercontent.com/7342798/35741362-e72b7a80-0837-11e8-9dfa-0a936b47d464.png)

**Comment by Nicola1971** [comment]
maybe we need to update the extrascheck message - what do you think ?
![check-weblogin](https://user-images.githubusercontent.com/7342798/35741787-fac7fac2-0838-11e8-95c3-f7542c2d0cc8.png)

**Comment by Nicola1971** [comment]
updated issue title

**Comment by dmi3yy** [comment]
They all in WebLogin
