### ISSUE TITLE
Show value $_GET, $_POST, $_COOKIE, $_SERVER and $_SESSION

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#49]
need add in docs 
https://forums.modx.com/thread/99775/output-value-of-get-post-cookie-server-session
Show value $_GET, $_POST, $_COOKIE, $_SERVER and $_SESSION

[!$_GET['username'] !]
[!$_GET['username']:ifempty=<form><input name="username"></form>!]
[!$_SERVER['REQUEST_TIME']:dateFormat='Y-m-d'!]
[!$_SERVER['HTTP_USER_AGENT']:find='Chrome':then='Chrome':else='Other'!]

http://mng.demo.modx.jp/pack_list/Evolution/modx1015j.html
Sample

https://github.com/modxcms/evolution/issues/621

**Comment by AgelxNash** [comment]
:ru: https://github.com/evolution-cms/docs/blob/master/ru/03_%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/02_%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/09_%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5.md

:us: https://github.com/evolution-cms/docs/blob/master/en/03_Develop/02_Elements/09_Predefined_variables.md
