### ISSUE TITLE
can't move the Content to another tab

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#491]
Hi,

I can't move the Content to another tab
mm rules like this : 
mm_createTab('About us', 'aboutus'); 
mm_moveFieldsToTab('post-image,content', 'aboutus');

**Comment by Nicola1971** [comment]
i don't use to move content, but just tested - does not work

**Comment by Nicola1971** [comment]
there are some issue with mm_moveFieldsToTab
see https://github.com/evolution-cms/evolution/issues/433

**Comment by bossloper** [comment]
This should fix it:
https://github.com/evolution-cms/evolution/pull/492

**Comment by Nicola1971** [comment]
@bossloper yes!
