### ISSUE TITLE
Can't load new dashboard welcome screen

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#494]
Hi guys. I have this weird issue with dashboard. 
Instead of using new theme welcome screen, it is loading an old 
`/manager/media/style/common/welcome.tpl`

![screenshot_2](https://user-images.githubusercontent.com/10888055/35861767-7d41bcf0-0b49-11e8-87df-454331a0e054.png)

Configuration is set to `default` theme.

![screenshot_3](https://user-images.githubusercontent.com/10888055/35861820-b241bd4c-0b49-11e8-8072-b21c67774d2a.png)

On dev server it was OK but after moving to client server this issue appeared.

After some searching I found this in `/manager/actions/welcome.static.php` line 387:
https://github.com/evolution-cms/evolution/blob/bb415270547de6d74a85fac5053a3b6f78ef567c/manager/actions/welcome.static.php#L387-L390

New dashboard works fine after commenting out those lines.
Do we have `manager_welcome_tpl` system setting? Is this a server issue or EVO bug?

**Comment by Nicola1971** [comment]
> Do we have manager_welcome_tpl system setting?
**manager_welcome_tpl**  is for Custom Dashboards

Example from EvoDashboard:

```
$e = &$modx->Event;
		if($e->name == 'OnManagerPageInit') {
		$modx->config['manager_welcome_tpl'] = '@FILE: '.$WelcomeUrl.'';
    }
```

**Comment by Nicola1971** [comment]
> Instead of using new theme welcome screen, it is loading an old /manager/media/style/common/welcome.tpl

this is very strange

**Comment by pmfx** [comment]
@Nicola1971 I've created a plugin and it works! Thanks!
```
$e = &$modx->Event;
switch($e->name){
  case 'OnManagerPageInit':
    $theme_name = $modx->config['manager_theme'];
    $modx->config['manager_welcome_tpl'] = MODX_MANAGER_PATH . 'media/style/'.$theme_name.'/welcome.tpl';
    break;
}
```
But it is strange why it doesn't work without it (on this specific server).

**Comment by Pathologic** [comment]
Is your dev server running on Windows?

**Comment by pmfx** [comment]
phpinfo says its Linux and PHP 5.6.32.
