### ISSUE TITLE
BUG ? Folder not editable when "view children" deactivated

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#496]
**Note:**

This does not affect all folders

Steps I took:
1 - Deactivated view children in sidebar

![01-deactivate-view-children](https://user-images.githubusercontent.com/1859868/36000438-371f4c98-0d23-11e8-9ec7-b65329221726.jpg)

2 - Wanted to edit the folder documentation, so clicked the folder and all it did was expand the children. The Documentation page content does not open in the right pane, it's not editable

![03-documentation-not-editable](https://user-images.githubusercontent.com/1859868/36000440-37559d98-0d23-11e8-9dbd-16e170fdfe69.jpg)

3 - So to test this I reactivated the view children option

![04-reactivate-view-children](https://user-images.githubusercontent.com/1859868/36000441-3775e38c-0d23-11e8-984f-7ce20f20b168.jpg)

4 - Re-clicked the documentation folder and now it's editable

![05-documentation-now-editable](https://user-images.githubusercontent.com/1859868/36000442-379c96f8-0d23-11e8-80a5-8c071f3854fc.jpg)

**Comment by 64j** [comment]
@modxuser 
I do not understand.
Everything is working.

https://monosnap.com/file/SmNZrbfijCd28ISAGTxIicCuCi34eV

**Comment by modxuser** [comment]
Sorry, but I can't demonstrate better than what the images already show

**Comment by Deesen** [comment]
Seems to me it is no bug. With de-activated "View Children" only resources marked as containers will be listed in the resource-tree. To see their children when clicked on "Documentation" i.e., on the right side you can open the tab "View Children", or click the Edit-button to edit the "Documentation"-resource itself. Did you miss that button?

**Comment by modxuser** [comment]
@Deesen 

Hi Dennis, I think you misunderstand

Es ist so, wenn ich auf Documentation geklickt habe muss es bearbeitbar sein, ist es aber nicht

Es geht mir hier nicht darum das child dokumenten angezeigt werden, es geht darum das ich momentan nur mit active children das documentation file bearbeiten kann

Sorry das mein Deutsch eingerostet ist, kann auch auf anrufen um es besser zu erklaeren

**Comment by Deesen** [comment]
You mean you even cannot edit resource "Documentation" using the edit-button?

![image](https://user-images.githubusercontent.com/8569221/36630209-f5650918-1962-11e8-90e9-4c236e6f5b8c.png)

**Comment by modxuser** [comment]
Correct - its not shown

Example:

Click on home button (top left in black bar)
Then click on documention folder

The same right panel stays - the right panel does not change

**Comment by modxuser** [comment]
@Deesen 

Dennis, do you have skype ?

**Comment by 64j** [comment]
@modxuser 
Is it resolved?
