### ISSUE TITLE
BUG ? Child documents not being shown after update

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#498]
I am having problems viewing child documents in the tree.

The following image shows my original 1.2.1 install:

![tree-backup](https://user-images.githubusercontent.com/1859868/36028822-ccf41604-0da0-11e8-85da-8a6355f7a34f.png)

This is what it looks like after updating to 1.4.0:

![no-dropdown-arrows](https://user-images.githubusercontent.com/1859868/36028834-df996534-0da0-11e8-9f0e-683cb4af9e81.png)

As can be seen - the arrows that indicate that a folder has children are no-longer there.

Also, when the folders are clicked, they don't expand the child documents

**Here the settings**
Main config:

![show-child-resources-config](https://user-images.githubusercontent.com/1859868/36028864-fa5c7f50-0da0-11e8-8d70-4e95ede183b5.png)

Tree options:

![view-children-tree-option](https://user-images.githubusercontent.com/1859868/36028882-0f37e4fa-0da1-11e8-8cef-50436b2e3ca6.png)

Cache etc. has been cleared, multiple times but no difference.

This is on a local Windows WAMP server - latest version.

**Comment by fourroses666** [comment]
Maybe remove files in cache folder, or try resaving plugin/snippet tree something ( i’m nog on mobile and cant look)

**Comment by modxuser** [comment]
All browser cache has been cleared, siteCache.idx.php deleted and I dont have the extra snippet installed that creates the Revo styled tree

**Comment by modxuser** [comment]
I have now updated my second large site and the exact same is happening - on both local and live servers

**Comment by Pathologic** [comment]
Do you use donthit column? It's now represented with checkbox named "Show child resources".

**Comment by modxuser** [comment]
I am not sure, but I presume it's one of the images I added to my the first post:
https://user-images.githubusercontent.com/1859868/36028864-fa5c7f50-0da0-11e8-8d70-4e95ede183b5.png

**Comment by Pathologic** [comment]
No, you should check the document properties.

**Comment by modxuser** [comment]
OK, thanks, now I understand

Between 1.2.1 and 1.4.0 the "Enable Stats Tracking" has been removed / changed and that is now causing this problem

Per default, all pages in my sites have the stats tracking to "0", meaning, now that this element has been changed, the setting is incorrect

Also, looking at the config - the config shows [(track_visitors)]

The "page settings" help button for this element has: Log each visitor's visit to this page

**Comment by modxuser** [comment]
The solution would be to update the DB directly, but I am not sure how to do that.

Via PHPMyadmin I just changed one page to "1" and the code it used was:

`UPDATE `XXXX_site_content` SET `donthit` = '1' WHERE `XXXX_site_content`.`id` = 3`

Would it be possible to do all pages in one go like this, by modifying the call ?

**Comment by Pathologic** [comment]
```
UPDATE `modx_site_content` SET `donthit`=1
```

**Comment by modxuser** [comment]
Thanks, my call was:

`UPDATE `modx_site_content` SET `donthit`=0`

That updated 3821 resources in this particular site :)

**Comment by modxuser** [comment]
I just changed the setting in the config and the pages still show child documents

Should the main setting in the configuration not overwrite the page settings ?

**Comment by modxuser** [comment]
Just deactivated the show children in the tree via the sort option and now the main folder no-longer shows the edit panel in the right column, basicaly, I now get the result found here: https://github.com/evolution-cms/evolution/issues/496#issuecomment-366559841

**Comment by Pathologic** [comment]
Probably this setting doesn't work now, so it will be deleted soon,
