### ISSUE TITLE
PrevJumpNext Snippet not working in 1.4.0

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#501]
I updated one of my larger sites over the weekend and the majority works.

One main problem though is the PrevJumpNext Snippet doesn't work.

I get the following:

![error](https://user-images.githubusercontent.com/1859868/36091773-3ab171c8-0fe5-11e8-95ac-6d9dd5c96980.png)

I am aware that Doclister can probably reproduce this, but at the moment I need to get the site back online ASAP, once its online I can go back and convert all the site to the new snippets

All help is welcome and appreciated, this is a snippet that was used by thousands over the years, but I wasn't able to find it in the new repository whilst checking for updated versions

The snippet code can be found in the attached zip

[snippet.PrevJumpNext.zip](https://github.com/evolution-cms/evolution/files/1715950/snippet.PrevJumpNext.zip)

**Comment by Nicola1971** [comment]
try to change line 20

```$children = $etomite->getActiveChildren($parentid, $sortBy, $sortHow, $fields); ```

to

```$children = $modx->getActiveChildren($parentid, $sortBy, $sortHow, $fields); ```

**Comment by Nicola1971** [comment]
a bit **outdated** snippet  😄 😄

**Comment by modxuser** [comment]
@Nicola1971 

That worked :) thanks

Yes, maybe outdated, but it works perfectly OK and to date, I haven't seen or heard of a replacement other than Doclister

**Comment by modxuser** [comment]
I have just found another Etomite problem, but with a different snippet: GoogleSiteMap

**Comment by Nicola1971** [comment]
> I have just found another Etomite problem, but with a different snippet: GoogleSiteMap

Wow! another prehistoric snippet  😄 

I have many memories of these old snippets ❤️ 

But all these snippets are from etomite or 0.9.x era - you know that we can't support code from 12 years ago 😄 .
and probably most of these old snippets need to be updated to msqli

about prevnext
> I haven't seen or heard of a replacement other than Doclister

there is a snippet on extras https://github.com/extras-evolution/prevnextPage

and i always use 
https://github.com/Nicola1971/Navigator

**Comment by modxuser** [comment]
Prehistoric - maybe, but works perfectly OK - just changed the etomite call to modx and works

I have always used snippets that came with or were taken care of by the core team, old doesn't necessary mean bad :) if that was true, then what am I ROFL

**Comment by Nicola1971** [comment]
> old doesn't necessary mean bad :) if that was true, then what am I ROFL

yes i agree, but old things need continuous maintenance 😄 ...at least i need  😄 

Anyway i don't think GoogleSiteMap and PrevJumpNext were developed by the old modx core team. 
If I remember correctly were developed by forum users for modx 0.9.6.1 ...so 2006? 

if even I'm not too old to remember 😄

**Comment by modxuser** [comment]
Yes correct - they were built by third parties, but due to the amount of users, they were kept up-to-date via the Dev team

If I remember rightly PJN was re-built by Jako a few years back, he added Yams functionality to it, not sure exactly what he changed :)

As already mentioned - it's just important for me at the moment to get the site back online, the transition to new code can take place as soon as that happens, as that's not a 5 minute job.
