### ISSUE TITLE
Question / Bug: Vendor Folder

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#503]
Can someone tell me what the vendor folder is for please and whether or not it can be deleted

The only references I have been able to find are:

Root - index.php:
`$autoloader = __DIR__.'/vendor/autoload.php';`

**And**

Manager - index.php
`$autoloader = realpath(__DIR__.'/../vendor/autoload.php');`

But there is no autoloader.php file in the folder, so I presume this is outdated ?

**UPDATE:**

Just searched the whole system - there isn't an "autoloader.php" file anywhere to be found

**Comment by dmi3yy** [comment]
Its for future. If not use you can delete this folder

**Comment by modxuser** [comment]
Thanks @dmi3yy
