### ISSUE TITLE
Не работает ограничение доступа к модулям по группам пользователей для менеджеров

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#505]
1.4. Если убрать пользователя с ролью Editor(базовая роль из коробки) из группы пользователей, к которой принадлежит тот или иной модуль - он всё равно видит его в выпадающем меню и может запустить без ограничений. 

Using basic Editor role (which has permission to run modules) is possible to run any modules despite the user group for particular user and module, even if user is not in user group assigned to the module

**Comment by 64j** [comment]
Видит он его как и другие модуле так же в общем списке, но запустить не сможет.
После изменения привилегий, пользователю нужно выйти, а потом опять зайти в панель управления.

He sees it like other modules in the same list, but can not start.
After changing the privileges, the user needs to exit, and then go back to the control panel.

**Comment by sashabeep** [comment]
Неизвестно, что произошло, но теперь всё работает как положено. Хотя и не на одном пользователе проверял - теперь вообще не видно модуля, если пользователь не состоит в группе
