### ISSUE TITLE
Добавьте спецтег для отмены обработки вызова кода сниппетов, плейсхолдеров в текстовом редакторе

### ISSUE THREAD

**Issue by cristalex** [evolution-cms/evolution#506]
Есть сайт база знаний, куда выкладываются некоторые решения. В текстовом редакторе кроме описаний часто вставляются вызовы сниппетов, Естественно парсер модекса пытается их выполнить, в итоге на сайте чаще всего в месте вставки кода пустое место, поскольку результат работы сниппетов пустой. 
Оборачивание кода в теги CODE и PRE не помогает. Можно конечно удалять квадратные скобки в вызовах сниппета, то на сайте виден код или вставлять скрины кода, но это не самый лучший вариант.
Было бы неплохо добавить тег (на подобии @IF), с помощью которого можно было отменить обработку парсером вызовов сниппетов, плейсхолдеров и т.д. в текстовом редакторе, если это конечно возможно.

**Comment by dmi3yy** [comment]
Документация которая docs.evo.im работает без всяких @if ;) 

Просто плагин и все. Скину позже пример кода 

Отправлено с iPhone

**Comment by Pathologic** [comment]
```
/**
 * sanitizeMODXtags
 * 
 * Plugin to sanitize MODX tags in content
 * 
 * @category    plugin
 * @internal    @events OnAfterLoadDocumentObject
**/
$e = &$modx->event;
if ($e->name == 'OnAfterLoadDocumentObject') {
        include_once(MODX_BASE_PATH . 'assets/lib/APIHelpers.class.php');
        $documentObject['content'] = APIHelpers::sanitarTag($documentObject['content']);
        $e->_output = $documentObject;
}
```
