### ISSUE TITLE
Unicode 10 characters filtered out?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#508]
Here is a bunch of nice new emoticons: 

happy ☺ ☻ 😃 😄 😅 😆 😊 😎 😇 😈 😋 😏 😌 😁 😀 😂 🤣 🤠 🤡 🤑
flirting 😳 😉 😗 😚 😘 😙 😍 🤤 🤗 😛 😜 😝
neutral 🙃 😐 😑 🤔 🙄 😮 😔 😖 😕
hush 😶 😯 🤐 😷
tired 😩 😫 😪 😴 😵

Should render to:

![image](https://user-images.githubusercontent.com/6764548/36253566-9303624c-1250-11e8-8d88-c98508b89014.png)

But after submit in Evo CMS, most of the emojis are gone.

Is that a bug?

Update: I realized that it also happens with another software: http://www.question2answer.org/qa/62412/unicode-10-characters-filtered-out

**Comment by saniock** [comment]
MySql Unicode Support
https://dev.mysql.com/doc/refman/5.7/en/charset-unicode.html

**Comment by saniock** [comment]
in html:
😏
&#128527;
&#x1f60f;
in php Surrogates
`echo json_decode('"\uD83D\uDE0F"');`
