### ISSUE TITLE
Refactor Extras in 1.5.0 

### ISSUE THREAD

**Issue by Dmi3yy** [evolution-cms/evolution#510]
TODO:
- full separate core and extras 
- select what extras needed in EVO installer 
- install/uninstall rules for 
- add more info about elements and use it in Manager (like list of default params in snippet in context menu, link on documentation)
- Widget with Extras Update info (what new and what change)
- composer support
===============

For a part of the new extras so that everything would work beautifully you need all the packages to take with extras
and accordingly there should be infa:

- Author
- Title
- Version
- A type
- Tags
- Description
- logo
- Documentation reference
- Possible parameters + default parameters
- rules for the installation aninstall (here you need to think how to do better)

This all needs to be done multilanguage

on the mind add to the folder in the folder extras where to put files of type elementname.json

the same json can be stored in the database immediately in the snippet, this will make it possible to add a link button to the same context menu, the possible parameters of inserting the parameter immediately into the snippet.

-----------

Further all the extras are tied to
https://github.com/extras-evolution/
Ie take a list of all that is here it will be a free part of extras + you can add an exception for DocLister FormListek but I would also render them here so that everything would be in one place.

======================================================

По части нового extras  для того что б все красиво работало нужно все пакеты брать с extras 
и соответственно там должна быть инфа: 

- Автор 
- Название 
- Версия
- Тип 
- Теги 
- Описание 
- логотип
- Ccылка на документацию 
- Возможные параметры + параметры по умолчанию 
- правила для инстал анинстал (тут надо подумать как сделать лучше)

Это все нужно делать мультиязычным 

по уму добавить в папку инстал папку extras где ложить файлики типа elementname.json

этот же json можно хранить в базе данных сразу же в сниппете это даст возможность в то же контекстное меню добавить кнопку линк на докментацию, возможные параметры вставку параметра сразу в снипепет. 

-----------

Далее весь екстрас завязываем на 
https://github.com/extras-evolution/ 
тоесть берем список всего что есть тут это будет фри часть extras + можно добавить искючения для DocLister FormListeк но я бы и их вынес сюда же что б все было в одном месте.

**Comment by dmi3yy** [comment]
Just as soon as this is done, we install:
- by default in the system we delete all the components, and in the instal we add a new page where the entire list of add-ons is displayed and the add-ons recommended for installation are selected. But if
we note something as not necessary, respectively, the addition is not only not put in the database, but also does not load its files. In this way, we can better monitor the state of the files and not load unnecessary. Also, when we have order in extras-evolution and each add-on has its own releases, we can make the update extras plug-in which will show which additions to the system are outdated and require updates. It also gives you the opportunity to specify the dependencies. If one of the plug-ins requires another, it will be automatically installed.

=========================================

Так же сразу же с этим переделываем и инстал: 
- по умолчанию в системе удаляем все компоненты, а в инстале добавляем новую страничку где выведен весь список дополнений и выбраны рекомендованные к установке дополнения. Но если 
мы что то отмечаем как не нужное то соответственно дополнение не только не ставиться в базу но и не загружаются его файлы. Таким образом мы сможем лучше контролировать состояние файлов и не загружать лишние. Так же когда у нас будет порядок в extras-evolution и у каждого дополнения будут свои релизы мы сможем сделать плагин update extras который будет показывать какие дополнения в системе устарели и требуют обновлений. Так же это все даст возможность указывать зависимости. Если для одного из плагинов требудется другой он будет автоматически установлен.

**Comment by dmi3yy** [comment]
Now the main task is to determine the format of storage configuration for add-ons
well, and where to store it, what not to rework in the future.

==============

Сейчас основная задача это определиться с форматом хранения конфигурации для дополнений
ну и где его хранить что б не переделывать уже в дальнейшем.

**Comment by dmi3yy** [comment]
Так же в идеале сразу подумать о том чтобы это все работало с помощью composer

=====

It is also ideal to immediately think about how it all worked with composer

**Comment by dmi3yy** [comment]
C учетом того что все равно прийдется перебирать все дополнения то очень логично завязать все на композер. Так же добавить поле какая версия дополнения к какой версии evo подходит

**Comment by sazanof** [comment]
простите, что только на русском

файл json можно создавать уже потом, когда дополнение установится.
Я могу предположить: например можно же "сканировать" папку extras-evolution на предмет нахождения в ней дополнений. Если да, то можно всегда выводить список актуальных.получаем title url img например и выводим их с чекбоксами для установки. Отмечаем, устанавливаем, создаётся файл json, или может composer.json, с нужными зависимостями и содержимым. Или для каждого дополнения уже потом автоматически создавать файлик json ,как тут предложили, чтобы потом его использовать в дальнейшем

**Comment by Tornek** [comment]
elementname.json → manifest.json?

**Comment by Tornek** [comment]
Часто забываю синтаксис TV, как задать варианты для выпадающего листа, радиокнопок, чекбокса и тд. Может быть стоит добавить подсказки или дефолтные значение при выборе «Тип ввода»?

———

I often forget the syntax of TV, how to set options for a DropDown list menu, Radio, Checkbox, etc. Maybe you should add some hints or default values for «Input Type»

**Comment by keslo** [comment]
Устанавливаемые дополнения из Extras могут быть завязаны на другие дополнения. Может использовать что-то похожее на package.json? А вообще формат JSON вполне годный.
