### ISSUE TITLE
Evolution Docs - Updates

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#511]
Hi @dmi3yy 

Sorry to address you this way; I sent you a mail at the end of last week reference adding FormLister documentation and a couple of examples / tutorials to the "Evolution Docs" website

Any chance you could take a look at the mail please and get back to me

I now have all of the docs ready (tutorials still in work), including the pages that aren't officialy translated, I have used Google to translate them, the result isn't bad, @Pathologic might be able to rectify / improve on it once online

**Comment by modxuser** [comment]
Example page:
![formlister-docs](https://user-images.githubusercontent.com/1859868/36397726-351f0f10-15c4-11e8-9a12-e147e2e74130.png)

**Comment by dmi3yy** [comment]
Better way work with 

http://docs.evo.im/en/ 

All docs in one place and based on github

**Comment by Pathologic** [comment]
Good work, though alphabetical sorting looks strange.

**Comment by modxuser** [comment]
@dmi3yy 

I appreciate you are trying to get the docs in GitHub, but for me at the moment it's easier and quicker to go this way.

I don't know markdown and at the moment I have too much on my hands to start learning it

I have 15 pages of docs finished and 4 tutorials - so it's down to you.

@Pathologic possibly - should I rename them to suit your page numbering ?

Here an example of a tutorial:

![anatomy](https://user-images.githubusercontent.com/1859868/36400202-d47513d8-15cf-11e8-9310-d55a9f6296e6.png)

**Comment by Pathologic** [comment]
The order of document files has some meaning because main snippet conceptions and common parameters should be the first. It's a bit strange to start with Authorizing Users (: 

By the way, DLMenu snippet allows to use different sort orders for different menu levels:
```
[[DLMenu?
...
&orderBy1=`pagetitle ASC`
&orderBy2=`menuindex ASC`
]]
```

**Comment by dmi3yy** [comment]
Write your email i give access

**Comment by modxuser** [comment]
rob.diana@freenet.de

**Comment by dmi3yy** [comment]
I sent 2 day ago
Maybe in spam folder ;(

**Comment by dmi3yy** [comment]
Or click forgot password

**Comment by modxuser** [comment]
not in spam - will try with the reset password

**Comment by modxuser** [comment]
when trying to use the rest function it gives me: **Could not find user**

**Comment by dmi3yy** [comment]
See email 
Send password

**Comment by modxuser** [comment]
Got it - it works, thanks

**Comment by modxuser** [comment]
@dmi3yy 

I am having problems uploading images for the tutorials - everytime I try to manage files it states: Can not read this directory

![directory-error](https://user-images.githubusercontent.com/1859868/36418140-3736a488-162e-11e8-8d41-76b3f6eba7fb.png)

**Comment by dmi3yy** [comment]
In configuration need reset path ;;)

**Comment by modxuser** [comment]
:) OK, I have everything else in the system now

I have also updated the homepage with the new links

**Comment by modxuser** [comment]
@dmi3yy I keep getting the notice that Admin is editing the config and as such I cant access it

**Comment by dmi3yy** [comment]
fixed

**Comment by modxuser** [comment]
Cool :) will give it a try in a mo

**Comment by modxuser** [comment]
Works :)

http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-v.2

**Comment by modxuser** [comment]
@Pathologic 

The [Formlister docs](http://www.evolution-docs.com/extras/formlister/) are now live, but the ordering is still set as alpha - as I don't have any experience with DocLister maybe you could update the second tier updating the Wayfinder call to DocLister ?

Please could you take a look at the translated docs when you have some spare time:

085_Deleting_Users_Profiles
http://www.evolution-docs.com/extras/formlister/editing-user-profiles/deleting-user-profiles

090_Reminding_Passwords
http://www.evolution-docs.com/extras/formlister/reminding-passwords

100_Creating_And_Editing_User_Documents
http://www.evolution-docs.com/extras/formlister/creating-and-editing-user-documents/

**Comment by bossloper** [comment]
Anyone else see strange hover behaviour on the home page links for http://www.evolution-docs.com/? If I hover over 'Upgrading' then sometimes part of Interface and Discussions get the hover style too. Also sometimes not the whole link is underlined. Only seems to be an issue when using Chrome.
Also a JavaScript error:
`Uncaught TypeError: Cannot read property 'replace' of undefined`

![untitled](https://user-images.githubusercontent.com/1744687/36422707-2ee66014-1635-11e8-83a7-f257182b0e5f.png)

![untitled](https://user-images.githubusercontent.com/1744687/36422507-3a499ee0-1634-11e8-8126-3651202dea42.png)

**Comment by modxuser** [comment]
@bossloper 

I am using Firefox and don't experience any problems

![evo-docs](https://user-images.githubusercontent.com/1859868/36423285-99e24928-163f-11e8-89d1-060f57a2da70.png)

**Comment by bossloper** [comment]
Yes same for me with Firefox and Edge. Just Chrome is not quite right for me.

**Comment by modxuser** [comment]
As the site is now updated I will close this issue - thanks for all the help everyone :)
