### ISSUE TITLE
TinyMCE ability to add class to hyperlink

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#512]
I would like to give a class to a hyperlink in TinyMCE. 
Would that be possible to add that field? (Maybe its already possible where I'm not aware of.)

----

Also have a less important thing I'd love to be able to do;
That is being able to give a hyperlink to an image instead of a File on the server.

![tiny](https://user-images.githubusercontent.com/523389/36417203-8e3c9eca-162b-11e8-9bf1-204f88d1ee9e.jpg)

My aim is to add a popup to a link which shows an image of video in a lightbox.
I can do that when the link has a class (popup or video).

**Comment by modxuser** [comment]
Not sure but this might be what you are looking for:
https://www.tinymce.com/docs/plugins/link/#link_class_list

**Comment by fourroses666** [comment]
Yes, any idea if this can be added in the Plugin configuration?
In the Custom Parameters?

Maybe @Deesen knows?

**Comment by Deesen** [comment]
Yes just add to the theme you want:

```
$this->set('link_class_list', '[
    {title: 'None', value: ''},
    {title: 'Dog', value: 'dog'},
    {title: 'Cat', value: 'cat'}
]', 'json' );
```

**Comment by fourroses666** [comment]
I have choosen a custom theme and added the link class but I guess I'm missing something?
TinyMCE stops working after adding that.

/assets/plugins/tinymce4/theme/theme.tinymce4.new.inc.php

**Comment by Deesen** [comment]
Sorry, " and ' need to be switched, so the right code is

```
$this->set('link_class_list', '[
    {title: "None", value: ""},
    {title: "Dog", value: "dog"},
    {title: "Cat", value: "cat"}
]', 'json' );
```

**Comment by fourroses666** [comment]
Works, thanks :))

-----

Adding a switch in KCFinder from Files to Images would solve my "problem".
Than its possible to link to images instead of only files.

**Comment by Deesen** [comment]
Maybe a new button like this helps? It will copy the image-src to the URL-input.

![image](https://user-images.githubusercontent.com/8569221/36555640-e355923a-1802-11e8-93b8-32e3f4ee3afd.png)

**Comment by risingisland** [comment]
I like this idea. 
I just added this to tinymce, but the new button is not showing up for me.

**Comment by Deesen** [comment]
Maybe a browser-cache issue?

**Comment by fourroses666** [comment]
Is it possible to select an other image from the images folder? Because that would be the best situation in some cases. :-0 

So place a thumb and then link to a large image (add class for the lightbox is already possible with the custom theme so thats great) Or when you would like to add a image “lightbox popup” on a hyperlink.

So thats why I thought adding the Files/Images switch in KCFinder was perfect. Some dropdown switch.

But I’m kinda oke with this too. It would help a bit.
