### ISSUE TITLE
Information: Formlister Documentation & Tutorials

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#513]
Thanks to the help of @dmi3yy and @Pathologic the Formlister documentation is now in the Evolution Docs website

The Formlister docs can be [found here](http://www.evolution-docs.com/extras/formlister/)

I have also added a few [tutorials / examples](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/) of how to use Formlister to create a basic contact form with validation in the site as well.

There is also an [anatomy of a contact form](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/anatomy-of-a-contact-form) tutorial, which I strongly suggest all new users to Formlister read and digest

I will add another tutorial shortly based on those already in the docs, adding Google Recaptcha and the standard Evo captcha to code thats already available

**Comment by modxuser** [comment]
@Pathologic 

The [Formlister docs](http://www.evolution-docs.com/extras/formlister/) are now live, but the ordering is still set as alpha - as I don't have any experience with DocLister maybe you could update the second tier updating the Wayfinder call to DocLister ?

Please could you take a look at the translated docs when you have some spare time:

085_Deleting_Users_Profiles
http://www.evolution-docs.com/extras/formlister/editing-user-profiles/deleting-user-profiles

090_Reminding_Passwords
http://www.evolution-docs.com/extras/formlister/reminding-passwords

100_Creating_And_Editing_User_Documents
http://www.evolution-docs.com/extras/formlister/creating-and-editing-user-documents/

**Comment by Pathologic** [comment]
http://docs.evo.im/en/03_extras/dlmenu.html - english docs are here. I've forgot Wayfinder already, but template parameters are similiar in general, startId becomes parents, level becomes maxDepth.

**Comment by modxuser** [comment]
Thanks @Pathologic , but it will have to wait for the moment, I am still updating my sites :) but when I have some spare time I will look into it

**Comment by nick0** [comment]
Thanks for preparing the docs @modxuser. This is going to help a lot of long time Modx Evo users.

**Comment by modxuser** [comment]
**Update:**

All of my testing has now come to an end - it's back to Work and my BA

My testing / updating resulted in the following tutorials / examples being written:

    Anatomy of a Contact Form
    Basic Contact Form - V.1
    Basic Contact Form - V.2
    Basic Contact Form - V.3
    Basic Contact Form With reCAPTCHA
    Basic Contact Form With modxCaptcha
    Add Multiselect Options
    Create a Form Report
    Anti BOT Field
    Processing Snippets
    Custom Languages

I strongly suggest anyone using FormLister reads the "Anatomy of a contact form" before diving in at the deep-end

The majority of examples can be used "as is" - copy + paste the code and give them a try

**Comment by pmfx** [comment]
Great work. Thanks!

**Comment by modxuser** [comment]
Thanks @pmfx 

My personal thanks go out to @Pathologic for helping me make the transition from eForm to FormLister, the examples / tutorials are the result, without his help it wouldn't have happened

**Comment by signalfeuer** [comment]
I need a tutorial for Formlister as a replacement for WebloginPE oder Weblgin.
At the moment WebloginPE doesn't work anymore with PHP7+ and EVOLUTION 1.4.6
