### ISSUE TITLE
Question: Formlister "anti BOT field"

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#514]
Susan Ottwell came up with a solution for eform many years ago that uses "eformOnValidate" to check a field to see if it has been filled with information or not

If it was filled out the form just dies, as the form field is hidden from normal view and only bots would fill it.

**So my question:**

Is something like this possible with Formlister ?

**The relevant code**

The eform call looks something like this:

```
[!checkField!]
[!eForm? ...... &eformOnValidate=`checkField`!]
```

The rendered HTML looks something like this

```
<form method="post" action="">
  BLAH BLAH....
  <input type="text" name="antispam" id="antispam" autocomplete="off" value="">
  <input class="button" type="submit" value="Submit">
</form>
```

And the snippet code
```
<?php
function checkField(&$fields,&$vMsg,&$rMsg) {
    if(!empty($fields['antispam'])) {
        return false;
    } else {
    return true;
    }
}
?>
```

**Comment by Pathologic** [comment]
Everything is possible with FormLister, especially when reading docs.
```
&rules=`{
"!antispam":{
    "required":""
}
}`
```

**Comment by modxuser** [comment]
@Pathologic 

Thanks, thats great, now I can delete another snippet :)

I will add this to a further tutorial

**Comment by modxuser** [comment]
A tutorial has been added to Evolution Docs, it can be [found here](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/anti-bot-field)
