### ISSUE TITLE
Question: Formlister Recaptcha

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#515]
@Pathologic 

I have found out how to use Recaptcha on localhost with keys set down by Google, but when I attempt to send the form I get an error:

The error is displayed in Russian, as it is hardcoded in the wrapper.php
```
$out = \APIhelpers::getkey($captcha->cfg, 'errorCodeFailed', 'Вы не прошли проверку');
```

Is it possible to change the notification text somehow, other than hard coding it into the wrapper.php ?

I have tried both the following, but they dont work:

```
&errorCodeFailed=`Test`
&errorCodeFailed=`@CODE:Test`
```

**Comment by Pathologic** [comment]
All captcha parameters are set as json array in the captchaParams parameter. Please, read the docs.

**Comment by modxuser** [comment]
OK, thanks

Obviously I added the "errorCodeFailed" in the wrong place

I think I will add a better example in the docs, for those, who like me, are not so tech savvy :)

**Comment by modxuser** [comment]
I have added a tutorial to the Evolution Docs site, it can be [found here](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-with-recaptcha)

**Comment by fourroses666** [comment]
Thanks @modxuser
