### ISSUE TITLE
Rename ht.access file to .htaccess after install CMS

### ISSUE THREAD

**Issue by AgelxNash** [evolution-cms/evolution#517]

**Comment by AgelxNash** [comment]
```php
if(!file_exists(MODX_BASE_PATH.'.htaccess') && file_exists(MODX_BASE_PATH.'ht.access')){
	rename(MODX_BASE_PATH.'ht.access', MODX_BASE_PATH.'.htaccess');
}
```

**Comment by Nicola1971** [comment]
Nice - of course, only if you enable friendly url

**Comment by modxuser** [comment]
I may have a wrong understanding of the code (not being a developer), but doesn't this already happen ?

I just installed multiple test sites and in every site the ht.access file was dynamically changed by Evo to .htaccess, when FURLs were activated

**Comment by Deesen** [comment]
This feature already exists https://github.com/evolution-cms/evolution/blob/develop/manager/processors/save_settings.processor.php#L33
