### ISSUE TITLE
Custom folders for "Image" and "File" Template Variables 

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#52]
Question and idea for a new feature.
Would it be possible for "Image" and "File" Template Variable to have/use its own/private folders inside "assets" folder? I see it like this:

When creating new Image or File TV, a new option (checkbox) is visible called "Use private folder for uploaded files".
When this option is selected two new options appear. First "Auto folder name" (checkbox). Second "Enter path maually" (text input). "Auto folder name" would create folders like "assets/images_tv/tv_22" or "assets/files_tv/tv_22" where 22 would be TV ID.
Visuals ;)

screenshot_2

I think it would be very useful in many scenarios.
What do you think?

https://github.com/modxcms/evolution/issues/770

**Comment by pmfx** [comment]
@dmi3yy I found a great Custom Template Variable that does exactly what I proposed. I think this issue can be closed. https://github.com/Pathologic/FastImageTV
