### ISSUE TITLE
Formlister - Sanitize

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#520]
@Pathologic 

I used the code in one of your examples for the message report
```
[+message:strip_tags:nl2br+]
```
After adding adding HTML, javascript etc. to the message field I got the sanitize text in the report, found in the [FormLister.abstract.php](https://github.com/evolution-cms/evolution/blob/develop/assets/snippets/FormLister/core/FormLister.abstract.php#L1212-L1213) file:
```
$value = str_replace('sanitized_by_modx<s cript', '<script', $value);
$value = str_replace('sanitized_by_modx& ', '&', $value);
```
Can this message be added as a  custom parameter ?

If not, as the LLC are no-longer running Evo, would it be better to use:

```
$value = str_replace('sanitized_by_Evo<s cript', '<script', $value);
$value = str_replace('sanitized_by_Evo& ', '&', $value);
```

Thanks for your help + time

**Comment by modxuser** [comment]
Further experimenting:

I manualy changed the text but was still getting the sanitized_by_modx, so searched the whole system and found that the same code is in the protect.inc.php file, as can be [seen here](https://github.com/evolution-cms/evolution/blob/develop/manager/includes/protect.inc.php#L43-L44)

**Comment by Pathologic** [comment]
This message is added by CMS, but you can remove it with FormLister if you understand possible consequences.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/020_Parameters.md#removegpc

**Comment by modxuser** [comment]
Thanks, I have hardcoded the new text in for the time being and made a note of the change for the future
