### ISSUE TITLE
System Update - config.inc.php

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#523]
Running a system update to the latest dev. I get a FAILED against config.inc.php
This is an update not a fresh install, do I now need to change the permissions on config.inc.php manually each time to 666 to allow the update to run or is this a bug?

![untitled](https://user-images.githubusercontent.com/1744687/36548963-7688e8c8-17e9-11e8-8c53-9876a04f7105.png)

**Comment by Deesen** [comment]
I guess this has to do with more strict security-settings on your server? Maybe this file belongs to a different user (for example FTP-user), and is not allowed to be changed by another user (root / php)?

**Comment by bossloper** [comment]
It was fine up until now. After an upgrade the file is set to 404, presumably part of the Evo install?

**Comment by Deesen** [comment]
Indeed there has been a change yesterday. Maybe you want to try to add to line 175 https://github.com/evolution-cms/evolution/blob/develop/install/actions/action_summary.php#L175

```
 else {
	chmod($tmp, 0666);
}
```

**Comment by bossloper** [comment]
Yes, that fixes it.
