### ISSUE TITLE
Question: Formlister Language Lexicon

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#524]
I have this partialy working, but thinking about updates, I think the better solution is to add the values to the call itself

I have read the documentation [found here](http://www.evolution-docs.com/extras/formlister/lexicons), but I am still not getting the expected result.

What does work is to duplicate the original English lang folder, rename it and make my modifications, then call it in the FormLister call as such:

```
&lang=`english-gb`
```

But I would prefer to add the text in the call as it can be modified on the fly and won't get deleted by accident on an update.

I have tried both the following, but neither of them work:

**Attempt 1**
```
&lang=`english-gb`
&lexicon=`{
    "english-gb":{
        "form.protectSubmit":"Your message has already been sent, there is no need to send it again",
        "form.submitLimit":"You may send your message again in ",
        "form.minutes":"min",
        "form.seconds":"sec",
        "form.dateFormat":"d.m.Y \a\t H:i:s",
        "form.default_successTpl":"@CODE:Your message was sent successfully on the [+form.date.value+]",
        "form.form_failed":"Your message could not be sent."
    }
}`
```
**Attempt 2**
```
&lang=`english-gb`
&lexicon=`{
    "english-gb":{
        "protectSubmit":"Your message has already been sent, there is no need to send it again",
        "submitLimit":"You may send your message again in ",
        "minutes":"min",
        "seconds":"sec",
        "dateFormat":"d.m.Y \a\t H:i:s",
        "default_successTpl":"@CODE:Your message was sent successfully on the [+form.date.value+]",
        "form_failed":"Your message could not be sent."
    }
}`
```
When I submit the form and create the mistakes for the text to appear, it still displays the default English file, so I presume I am doing something wrong here :(

**Comment by Pathologic** [comment]
Update FormLister via Extras, probably it's outdated here. I've fixed a bug with custom lexicons some time ago.

**Comment by Pathologic** [comment]
And your json is not correct because of slashes. It should be \\\\, not \\

**Comment by Pathologic** [comment]
You can store your language files in custom folder, so they won't be overwritten.

**Comment by modxuser** [comment]
@Pathologic 

I updated the snippet as you said, via extras, but that shows 1.7.17, whereas your release page says the latest version is 1.7.16

After updating via extras I checked the files in the updated version (1.7.17) and there are some weird things going on with the russian file names:

![md-filenames](https://user-images.githubusercontent.com/1859868/36566277-4aaedbd8-1823-11e8-8dab-bb024318857d.jpg)

So I decided to do a manual install from your release - 1.7.16

With the change in the json call and the updated files, my second call now works :)

This is what I now have:

```
&lang=`english-gb`
&lexicon=`{
    "english-gb":{
        "form.protectSubmit":"Your message has already been sent, there is no need to send it again",
        "form.submitLimit":"You may send your message again in ",
        "form.minutes":"min",
        "form.seconds":"sec",
        "form.dateFormat":"d.m.Y \\a\\t H:i:s",
        "form.default_successTpl":"@CODE:Your message was sent successfully on the [+form.date.value+]",
        "form.form_failed":"Your message could not be sent."
    }
}`
```

This gives for a second solution, so the user can in reality choose how they want to do things - much more versatile than eForm

Thanks again for your time.

This will certainly be an eye-opener for all those who do not speak / use Russian or English, great stuff

**Comment by modxuser** [comment]
Added to Evolution Docs, it can be [found here](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/custom-languages)
