### ISSUE TITLE
Community Help Request - FormLister Translators

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#525]
This is a call-out to all those who wish to use FormLister in their own language and who have a few spare moments to translate the language files.

Currently FormLister can be used in Russian and International English

If you have a little time and would like to help improve the flexibility of FormLister, please download a copy of the language files and translate them

I know that we have at least the following languages in the community:
- [x] Polish
- [x] German
- [x] Dutch
- [x] UK English
- [x] Spanish
- [x] Italian
- [ ] French

Language files can be [found here](https://github.com/Pathologic/FormLister/tree/master/assets/snippets/FormLister/core/lang)

So any and all help is highly appreciated - please remember, if you're not a programmer, you can still help to make Evo a better system by helping where you can.

**Comment by pmfx** [comment]
Good idea! Polish translation added.

**Comment by fourroses666** [comment]
Will add Dutch language soon

**Comment by Pathologic** [comment]
Who knows French and Italian?  @Nicola1971 ?

**Comment by Nicola1971** [comment]
Sorry I'm very busy these days.
I will add italian Lang soon

**Comment by risingisland** [comment]
@modxuser Here is Spanish...
[spanish.zip](https://github.com/evolution-cms/evolution/files/1796253/spanish.zip)

**Comment by modxuser** [comment]
@risingisland that's great stuff - @Pathologic can you download and add it to your repo ?

**Comment by fourroses666** [comment]
Can be closed?

**Comment by modxuser** [comment]
@fourroses666 

Marc, in theory yes, but there are still languages missing

@Nicola1971 said he will add Italian, but that's 27 days ago, so don't know

**Comment by Nicola1971** [comment]
Sorry :) here is italian 
[italian.zip](https://github.com/evolution-cms/evolution/files/1879588/italian.zip)

**Comment by modxuser** [comment]
@Pathologic https://github.com/evolution-cms/evolution/files/1879588/italian.zip

**Comment by modxuser** [comment]
Closed, as no-one seems to be interested in translating into French
