### ISSUE TITLE
Question: FormLister Multiple Select

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#529]
I am trying to rebuild a multiple select item from eForm into FormLister but I am sadly failing miserably.

This is my eForm select item
```
<select name="multisel[]" id="multisel[]" multiple="multiple"eform="multisel:listbox:1">
  <option value="1">Test 1</option>
  <option value="2">Test 2</option>
  <option value="3">Test 3</option>
  <option value="4">Test 4</option>
  <option value="5">Test 5</option>
</select>
```
This call lets the end-user select multiple fields and all the selected fields are displayed in the form report

I have tried the following

Solution 1
```
<label>Multiple Select</label>
<select name="multisel" id="multisel" multiple="multiple">
  <option value="1">Test 1</option>
  <option value="2">Test 2</option>
  <option value="3">Test 3</option>
  <option value="4">Test 4</option>
  <option value="5">Test 5</option>
</select>
```
Solution 2
```
<label>Multiple Select</label>
<select name="multisel" id="multisel" multiple="multiple">
  <option value="1" [+s.multisel.1+]>Test 1</option>
  <option value="2" [+s.multisel.2+]>Test 2</option>
  <option value="3" [+s.multisel.3+]>Test 3</option>
  <option value="4" [+s.multisel.4+]>Test 4</option>
  <option value="5" [+s.multisel.5+]>Test 5</option>
</select>
```
Solution 1 + 2 both give me the same result - they always **only** output the last item selected

After researching the net a little and finding old references to eForm, I found a thread mentioning that you need to add "[]" to the name for an array (which I have in my original call)

So, this is what I came up with

Solution 3
```
<label>Multiple Select</label>
<select name="multisel[]" id="multisel[]" multiple="multiple">
  <option value="1">Test 1</option>
  <option value="2">Test 2</option>
  <option value="3">Test 3</option>
  <option value="4">Test 4</option>
  <option value="5">Test 5</option>
</select>
```
Solution 4
```
<label>Multiple Select</label>
<select name="multisel[]" id="multisel[]" multiple="multiple">
  <option value="1" [+s.multisel[].1+]>Test 1</option>
  <option value="2" [+s.multisel[].2+]>Test 2</option>
  <option value="3" [+s.multisel[].3+]>Test 3</option>
  <option value="4" [+s.multisel[].4+]>Test 4</option>
  <option value="5" [+s.multisel[].5+]>Test 5</option>
</select>
```
Both solution 3 + 4 don't output anything

I have gone through the documentation + examples found in the docs folder, but I can't find a reference to multiple select elements

Any and all help is appreciated :)

**Comment by Pathologic** [comment]
http://www.evolution-docs.com/extras/formlister/general-parameters#formlisterformcontrols

**Comment by modxuser** [comment]
@Pathologic 

Thank you for answering, but I can't understand what is meant with the parameter and I don't know where or how to implement or start with it

**Comment by Pathologic** [comment]
Your friend should eat his own hat:
```
&formControls=`multisel`
&formTpl=`@CODE:
...
<label>Multiple Select</label>
<select name="multisel[]" id="multisel" multiple="multiple">
  <option value="1" [+s.multisel.1+]>Test 1</option>
  <option value="2" [+s.multisel.2+]>Test 2</option>
  <option value="3" [+s.multisel.3+]>Test 3</option>
  <option value="4" [+s.multisel.4+]>Test 4</option>
  <option value="5" [+s.multisel.5+]>Test 5</option>
</select>
...
`
```

**Comment by modxuser** [comment]
Obviously you know the code in and out, my friend doesn'y know the code and secondly doesnt work with Evo

Anyway, it would have been easier if you had simply added the call in the first place, instead of simply adding a link to documentation that is not comprehensive / fully understandable

As can be seen in my initial post - the code in the form was correct

I will pass this on to my friend, if it interests him, I am sure he will accept that it can work

**Comment by Pathologic** [comment]
The problem is not in FormLister or documentation (though I supposed that you didn't use formControls parameter), because I cannot find where it says to write such constructions as [+s.multisel[].1+] or even id="multisel[]"

**Comment by modxuser** [comment]
Exactly - it doesnt say that anywhere, there are no examples of this in your docs, not in the russian or english docs, not even in the russian examples

It doesnt state anywhere in the docs how this needs to be written

**Comment by Pathologic** [comment]
Ok, I'll add notice about arrays of checkboxes and so on.

**Comment by modxuser** [comment]
Why do you think I have created a tutorial / example for everything that I have done with FormLister so far ?

**Comment by Pathologic** [comment]
I don't know, maybe you like to create tutorials (I don't like) :smile_cat:

**Comment by modxuser** [comment]
being sarcastic is not welcome

**Comment by modxuser** [comment]
The tutorials are for all non-programmers who have been told the FormLister is the replacement for eForm, they are there to make life easier and to hopefully drop the learning curve somewhat

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/040_Data_Output.md

**Comment by modxuser** [comment]
OK, will update the Evolution Docs site in the morning and add a short tutorial / example with the content here

**Comment by Pathologic** [comment]
You can use this example https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/examples/ru/002_%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F.md or this https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/examples/ru/003_%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0_%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2.md

**Comment by modxuser** [comment]
@Pathologic 

I have added the new code, as [shown here](https://github.com/evolution-cms/evolution/issues/529#issuecomment-369392224), but I am not getting the information in the report

I presume the output is the same as usual, I currently have this in the report:
```
multiselect options: [+multisel+]
```

Am I doing something wrong here ?

**Comment by modxuser** [comment]
I now have it working, **BUT**

Please could you tell me why all of my other elements work without using "value"

All of the elemenets in the report are based on this:
```
[+FIELDNAME+]
```
And they all work, so, what is the 100% correct way to write the values in the report

**Looking at this code:**

```
&reportTpl=`@CODE:
<p>Имя: [+name.value+]</p>
<p>Телефон: [+phone.value+]</p>
<p>Email: <a href="mailto:[+email.value+]">[+email.value+]</a></p>
<p>Продукты: [+products.value+]</p>
<p>Сообщение: [+message:strip_tags:nl2br+]</p>
`
```
The message doesnt have "value", so a little more clarity on what should be added is appreciated

**Comment by Pathologic** [comment]
.value is for sanitized value (or array converted to string).

**Comment by modxuser** [comment]
So in theory it can be used all of the time ?

**Comment by modxuser** [comment]
**Or should I say:**

Is it best practice to use it all of the time ?

As it ensures that all elements are outputted to the report - betting for non-programmers

**Comment by Pathologic** [comment]
It's better to always sanitize values you get from user.

**Comment by modxuser** [comment]
Cool, thanks for the feedback

**Comment by modxuser** [comment]
**arraysplitter**

I am not able to add HTML example:

```
<br>
```

Is this normal ?

I have tried:

```
&arraySplitter=`<br>`

results in:

1<br>2<br>3
```
Attempt 2
```
&arraySplitter=`@CODE:<br>`

results in:

1@CODE:<br>2@CODE:<br>3
```

There is no [mention in the docs](http://www.evolution-docs.com/extras/formlister/general-parameters#formlistertemplates) saying that HTML can't be used

**Comment by Pathologic** [comment]
It's a bug.

**Comment by modxuser** [comment]
bug removed here and added to [FormLister Repo](https://github.com/Pathologic/FormLister/issues/93)
