### ISSUE TITLE
Не работают «Общие праметры» в плагине

### ISSUE THREAD

**Issue by mediakot** [evolution-cms/evolution#531]
Добрый день! Не работают "общие параметры", когда нужно брать параметры из модуля в плагине. Такое поведение при использовании eFilter.
Проблема в том, что если параметры  у плагина не заполнены, то в пустую строку подставляются кавычки {}. 
Если удалить эти кавычки и сохранить, то плагин работает, но до повторного сохранения, когда снова подставленные кавычки записываются в базу.
http://skrinshoter.ru/s/250218/IndYGVFs

**Comment by 64j** [comment]
@mediako"
Вы же пишете...
.. удалить эти кавычки и сохранить, то плагин работает...
возможно это к автору плагина надо обратиться?

а скобки подставлялись всегда, если параметры не заполнены.

**Comment by mediakot** [comment]
Нет, дело в том, что есть общие параметры, которые должны из модуля подхватываться плагином, но если эти кавычки есть, то не подхватываются. Я специально тестил с помощью logEvent, Плагин тут не причём.

На старой версии modx evo там пусто http://skrinshoter.ru/s/250218/xQ9e6f5A

**Comment by dmi3yy** [comment]
Эта проблема была в 1.3.2 в 1.3.3 пофиксили 

Отправлено с iPhone

**Comment by mediakot** [comment]
Версия 1.4.0
http://skrinshoter.ru/s/250218/g5tzJugl

**Comment by mediakot** [comment]
В общем, в файле mutate_plugin.dinamic.php в функции ShowParameters (107строка) нет проверки на пустоту объекта, который содержит параметры плагина. Таким образом, в конце ShowParameters функция implodeParameters() вставляет в поле параметров плагина пустой объект, эти самые кавычки {}
Для себя, как временное решение, перед implodeParameters() вставил `if(JSON.stringify(currentParams) === '{}')return;`

**Comment by dmi3yy** [comment]
Можно пулом сразу ;) 
А то все для себя да для себя

Отправлено с iPhone

**Comment by webber12** [comment]
Скорее всего дело не в версии evo - похоже, эта проблема была уже давно. Просто я несколько дней назад начал ставить плагин выключенным https://github.com/webber12/eFilter/commit/56c4712dcba5a0c6514696bfdb94d7591333df81 . Соответственно, для включения, он требовал пересохранения, и вот тут эти пустые {} и стали мешать. Теперь вернул со своей стороны все назад https://github.com/webber12/eFilter/commit/2da8b4bbe8e429b990e4d42330e96ed59b1b4377

**Comment by mediakot** [comment]
Да нет. Если кто-то в своёй разработке захочет использовать общие параметры, то из-за этих скобок будет долго тупить, почему общие параметры не подхватываются. А при отладке ещё каждый раз стирать их придётся. 
А если CodeMirror отключить, то вообще скобки {} по onchange на поле вставляются.

**Comment by webber12** [comment]
Ну с другой стороны я этот плагин миллион раз пересохранял на 1.3.6 и ни разу у меня параметры не пропадали. Так что возможно дело все-таки в версии evo

**Comment by webber12** [comment]
Вот, кстати, на 1.4.0b  у меня те же скобки - https://yadi.sk/i/4_FQgPz73SmfUr и при сохранении ничего не теряется вроде. Если только с тех пор там что-то опять поменялось :)

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/pull/536
