### ISSUE TITLE
The variable $context does not exist in startCMSSession function

### ISSUE THREAD

**Issue by AgelxNash** [evolution-cms/evolution#533]
https://github.com/evolution-cms/evolution/commit/ae6c8412b3b09ff30ead86f90359e521a1165f95#diff-20a2fab802895005f2251f9360243dd6

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/commit/bb183dd25e906459c55d33e72314179f83ba4b37

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/commit/dd48c10476ef175d50a640a716590ceded45f20a
