### ISSUE TITLE
"Tree sort" changes on Password change

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#541]
Strange behaviour !

When a password is changed, the tree sorting changes back to the default install settings

Is this supposed to happen ? if yes, why ?

**Comment by 64j** [comment]
This happens when the user session is updated.
When you change the password, the new session is created.

**Comment by modxuser** [comment]
Ah, ok, thanks

If the user session is deleted from the DB, surely the same should happen as well then ?
