### ISSUE TITLE
PSR 0,1,2

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#544]
Почему бы хотя бы все правки и новые методы, файлы, функции не оформлять сразу по стандарту PSR . Это же реально намного улучшает читабельность, не говоря уж о том, что выглядит опрятнее и приятнее :)
```
$c .= $a . $b;
function foo($bar1, $bar2, $bar3)
{
    ...
}
if ($a == '2') {
    ....
} elseif {
    ....
} else {
    ....
}
```

Ну и т.п.

**Comment by 64j** [comment]
#183
