### ISSUE TITLE
Upgrade to latest dev gives Internal Server Error

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#548]
Just upgraded a dev install to latest dev https://github.com/evolution-cms/evolution/commit/d17f771aae6c3b195089156bc5e5826b030ccfbc.
Install runs and ends with a page not found error. Then log into manager and the main frame is blank:
![untitled](https://user-images.githubusercontent.com/1744687/36738831-69c3430e-1bd6-11e8-8d6f-37a2b0a63407.png)
Server log shows an error in config.inc.php:
`Uncaught exception 'RuntimeException' with message 'Please, define MODX_BASE_PATH and MODX_BASE_URL on cli mode'`

(php 5.6.33)

**Comment by AgelxNash** [comment]
rel #540

**Comment by AgelxNash** [comment]
I can't repeat. Show me
```php
echo php_sapi_name();
echo $_SERVER['argc'];
```

**Comment by bossloper** [comment]
php_sapi_name() = apache2handler
$_SERVER['argc'] = 1

This installation is in a sub-folder if that makes a difference?

**Comment by 64j** [comment]
@bossloper 

Replace in file https://github.com/evolution-cms/evolution/blob/develop/install/config.inc.tpl#L28

```php
define('MODX_CLI', (php_sapi_name() == 'cli' && (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)));
```

Check, please.

**Comment by bossloper** [comment]
Yes @64j that change works.
