### ISSUE TITLE
No sort by date in DocLister

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#549]
1.  No sort by date in DocLister 
Example:
(TV datum is typ unixtime)
```
[[DocLister?  
&parents=`5` 
&display=`all`
&tvList=`datum`
&dateSource=`tv.datum`
&tpl=`content-termine` 
&dateFormat=`%d.%m.%Y` 
&sortBy=`datum`
]]
```

Chunk  content-termine:
`[+date+]<br> 	`

Output:
16.01.2018
10.07.2018
09.06.2018
The Ouput is not sort by TV datum.

2. I have a filter in ditto. It filter out documents, that older as the current date. 

```
[[Ditto? 
&parents=`13` 
&display=`all` 
&orderBy=`datum ASC` 
&dateSource=`tv.datum` 
&dateFormat=`%d.%m.%Y - %H:%M` 
&filter=`isfolder,0,1|datum,@EVAL return strtotime('-0 day');,3` 
&tpl=`content-termine` &noResults=` Zur Zeit keine weiteren Informationen!` ]]
```

How I can realize it with DocLister?

**Comment by webkarli** [comment]
Question1:
I found a solution myself. With  parameter tvSortType it works correct:
```
[[DocLister?  
&parents=`5` 
&display=`all`
&tvList=`datum`
&tvSortType=`TVDATETIME`
&dateSource=`tv.datum`
&tpl=`content-termine` 
&dateFormat=`%d.%m.%Y` 
&sortBy=`datum`
]]
```

Question 2: I believe, I need a filter...

**Comment by Pathologic** [comment]
https://gist.github.com/Pathologic/0090d821b2aa3e87061c7b00d87873aa

**Comment by webkarli** [comment]
Thanks to Pathologic
I have needed some time to understand that tvdate.filter.php must be copied to the folder DocLister\core\filter. Now the filter works with given date. 
How can I replace the date with the date from the current system time (get_date) or one day back?

**Comment by Pathologic** [comment]
Create a snippet to get the needed date.

**Comment by webkarli** [comment]
You're right. I can do that with a little knowledge in PHP.
Snippet myday:
```
<?php
$mydaybefore = date('Y-m-d', time()-(60*60*24));
return $mydaybefore;
```
DocLister:
```
[[DocLister?  
&parents=`5` 
&display=`all`
&tvList=`datum`
&tvSortType=`TVDATETIME`
&dateSource=`tv.datum`
&tpl=`content-termine` 
&dateFormat=`%d.%m.%Y` 
&orderBy=`datum ASC`
&filters=`tvdate:datum:>:[[myday]]`
]]
```

**Comment by Pathologic** [comment]
Myday snippet will not work right if it's called cached.
