### ISSUE TITLE
DocLister (crop + notempty)

### ISSUE THREAD

**Issue by em-piguet** [evolution-cms/evolution#550]
Hello, I'm not sure it is the right place to ask but I have two questions : 

**1) Image crop**
 i'm making a list of doc with DocLister and i would like to **crop a TV image** on the fly. 

my call  :
`[!DocLister? &display=30 &parents=2 &tvList=myimage &id=trombinoscope &tpl=trombi_item 
`
and my &tpl  :
`<div><img src="[+tv.myimage+]" width="115" height="115" alt="[+pagetitle+]"></div>`

I know in revo i would do `[+tv.myimage:pthumb...+]` but what's the right way to do it now in evolution ?

**2) not empty**
my second question is about the call i use.. i tried to display "only the doc with an image in the TV not null ? " but i didn't get it.. I tried all combination `&filters=AND(tv:image_sagefemme:not:)!]` or `&filters=AND(tv:image_sagefemme:!=:)!]` and other i don't remember.. My final solution was testing if there is the string `assets` in it and of course it works...  but Is there a better way to do it ?

Thanxk you for your hard work 
**Evo Rocks**

**Comment by Pathologic** [comment]
1:
```
[[phpthumb? &input=`[+tv.myimage+]` &options=`zc=C`]]
```
2: try tvd filter, not tv - then &filters=AND(tv:image_sagefemme:not:) should work

**Comment by em-piguet** [comment]
1) of course ! it works fine thx.
2) that's didn't do it. Please note that i'm using DocLister 2.3.0 on evo 1.2.1 . will try to upgrade evo asap.

**Comment by Pathologic** [comment]
I've checked &filters=AND(tvd:image_sagefemme:not:) and it works.
