### ISSUE TITLE
MaxiGallery – No pictures in dragsort view when SVG icons used

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#551]
Evo 1.4
PHP 7.0
MaxiGallery 0.6
In various installations, local and live, there are no more pictures shown in dragsort view, maybe since update to Evo 1.4RC or 1.4.
In developer tools console I get this error:
„TypeError: this.className.test is not a function“ Do not know if this is the reason for no pictures on the page.

Normal gallery view and normal gallery management page are o.k.

See also : [https://github.com/extras-evolution/MaxiGallery/issues/4](https://github.com/extras-evolution/MaxiGallery/issues/4)

**Comment by bossloper** [comment]
You already posted this issue here: https://github.com/extras-evolution/MaxiGallery/issues/4
