### ISSUE TITLE
Weird Chunk Rendering When minifyphp_incache is enabled

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#552]
I was just about to update a live site with my local version and whilst going through the code I see that some chunks that have spaces in them are being rendered without the space.

This problem is not in 1.2.1, it has appeared after updating to 1.4.0

**Example:**
```
&amp; [(site_name)]
```
Renderes as follows:
```
&amp;MYSITENAME
```
Another one:

"word word" renders as "wordword"

**Comment by modxuser** [comment]
Further testing

When using `&` instead of `&amp;` the space is rendered

**Comment by Pathologic** [comment]
Disable minifyphp_incache setting.

**Comment by modxuser** [comment]
@Pathologic 

That worked - thanks

But as mentioned, this only started with 1.4.0 - in 1.2.1 minify is also active, but it doesn't cause a problem

**Comment by Deesen** [comment]
It is happening here:

https://github.com/evolution-cms/evolution/blob/develop/manager/processors/cache_sync.class.processor.php#L486-L487

**Comment by ricardo-lewis** [comment]
This is still occurring in the latest 1.4.4
