### ISSUE TITLE
Zend OPcache API is restricted by "restrict_api" configuration directive

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#559]
This error suddenly appeared in the admin backend when saving a snippet (evo files were not touched, it came out of nowhere):

```
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /manager/processors/cache_sync.class.processor.php on line 97

Warning: Cannot modify header information - headers already sent by (output started at /manager/processors/cache_sync.class.processor.php:97) in /manager/processors/save_snippet.processor.php on line 167
```

Line 97: 

`$opcache = opcache_get_status();`

Possible fix (please check): 

`$opcache = @opcache_get_status();`

**Comment by q2apro** [comment]
I have auto-updated to 1.4.1 and a new error showed up directly after saving the cms settings (after update):

```
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /manager/processors/cache_sync.class.processor.php on line 135

Warning: Cannot modify header information - headers already sent by (output started at /manager/processors/cache_sync.class.processor.php:135) in /manager/processors/save_settings.processor.php on line 156
```

Guess we need `@opcache_get_status()`.

**Comment by dmi3yy** [comment]
Can you check this:
https://github.com/evolution-cms/evolution/commit/4ae239de603d2b69b4abd37b4aef38f490e7227a


we are fix this after 1.4.1

**Comment by AgelxNash** [comment]
ping @q2apro

**Comment by q2apro** [comment]
Fix seems to work! Thanks mates 😉
