### ISSUE TITLE
eForm - hidden fields/arrays not validating like checkboxes

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#56]
Checkboxes validate correct:

```
<input name="products[]" value="1" type="checkbox" eform="Products::1" />
<input name="products[]" value="2" type="checkbox" />
```

"hidden" fields/arrays do not validate the same:

```
<input name="products[]" value="1" type="hidden" eform="Products::1" />
<input name="products[]" value="2" type="hidden" />
```

Hidden-Fields like in above example should validate the same like checkboxes, not?

https://github.com/modxcms/evolution/issues/1385

**Comment by Pathologic** [comment]
Moved https://github.com/extras-evolution/eForm/issues/3
