### ISSUE TITLE
Error when upgrading to 'phpmailer sender property' commit

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#563]
When running install on the latest dev commit: https://github.com/evolution-cms/evolution/commit/e3ce8aaf93d0e08ef546cdeb0657b990bb0410c9

I get a SQL syntax error message:
![untitled](https://user-images.githubusercontent.com/1744687/37025618-18f3f038-2124-11e8-8e89-1708547621db.png)

After closing the install and going to manager login I can not log in.
Rolling back to the commit before (https://github.com/evolution-cms/evolution/commit/ce2fc83131a56ae202e4120b2119b904ca83ad07) works ok.

Strange thing is I can submit those 'REPLACE INTO' lines listed in the screenshot from phpMyAdmin and they run ok.

php 5.6.33
database: 5.5.5-10.1.31-MariaDB

**Comment by Pathologic** [comment]
Yes, it's strange.
