### ISSUE TITLE
Problems with the output of the visual editor in the introtext and the use ManagerManager widget mm_ddMultipleFields.

### ISSUE THREAD

**Issue by Rising13** [evolution-cms/evolution#564]
Problems with the output of the visual editor in the introtext and the use ManagerManager widget mm_ddMultipleFields.
In version 1.4.1 not working.
In version 1.4.0 worked. In this version writes an error about the absence of the file.
"assets/plugins/tinymce4/tinymce/themes/introtext / theme.min.js»

Проблемы с выводом визуального редактора в introtext и при использовании ManagerManager виджета mm_ddMultipleFields.
Не работает в версии 1.4.1
В версии 1.4.0 работало. В данной версии пишет ошибку об отсутствии файла.
«assets/plugins/tinymce4/tinymce/themes/introtext/theme.min.js»

**Comment by dmi3yy** [comment]
fixed
