### ISSUE TITLE
Из псевдонима вырезается точка (sitemap.xml -> sitemapxml)

### ISSUE THREAD

**Issue by ultraviolet** [evolution-cms/evolution#565]
Псевдоним sitemap.xml при сохранении документа становится sitemapxml
То есть, вырезается точка, чего раньше не было. Только у меня так?

**Comment by dmi3yy** [comment]
проверил 1.4.1 все ок

**Comment by Pathologic** [comment]
В настройках плагина TransAlias отключить Remove Periods.
