### ISSUE TITLE
Suggestion - Rename manager 'Home' to 'Dashboard'

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#567]
As it is common to refer to the manager 'home' screen as the 'dashboard' should it be renamed? So title and icon changed on the menu bar. 'Home' also seems quite general and could equally refer to the website frontend home page so is maybe not the best name for this backend manager page?
E.g.
![untitled](https://user-images.githubusercontent.com/1744687/37214380-ce6b80fe-23ac-11e8-9aa1-e25db80191bc.png)

**Comment by fourroses666** [comment]
Agree

**Comment by 64j** [comment]
I do not agree.
In many languages, the "dashboard" takes up too much space.
RU: "Приборная панель"
DE: "Instrumententafel"

**Comment by dmi3yy** [comment]
i think its no problem set in EN: dashboard and in RU: Главная
but icon more correct dashboard

**Comment by bossloper** [comment]
Yes, I can see the menu bar is on the limit for width in Russian lang. So yes if the icon can be changed and then language can be altered if there is space for that particular language?
