### ISSUE TITLE
New Tag "evolution-cms" at Stackoverflow

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#569]
FYI, I posted a [question on stackoverflow](https://stackoverflow.com/questions/49206608/load-resource-content-of-other-document-into-recent-document-and-execute-its-sni) and introduced the new tag [evolution-cms](https://stackoverflow.com/questions/tagged/evolution-cms).

Maybe, since the origin (and code etc.) of Evolution CMS is Modx Evolution, it makes sense to rename the tag "modx-evolution" over at Stackoverflow to "evolution-cms".

This should be possible by a moderator.

**Comment by dmi3yy** [comment]
I think now better use 2  tags:  modx-evolution and evolution-cms 
its better for user who want found info
