### ISSUE TITLE
Не учитываются префиксы таблиц (modx db api)

### ISSUE THREAD

**Issue by Arviona** [evolution-cms/evolution#57]
На новой версии 1.3.0b, php версия 5.6.30 не заработал ContentBlocks (пустая вкладка).

Начала разбираться, ошибка такая (Похоже что в modx db api не учтен переход на новый префикс evo_ , В частности, моя ошибка скорее всего из-за $modx->db->query):

![image](https://user-images.githubusercontent.com/19893155/28240229-aa89f6f8-69a7-11e7-910f-089c6b35b240.png)

**Comment by dmi3yy** [comment]
Недавно обсуждали: 
Исправили 3 дня назад: 
https://github.com/sunhaim/contentblocks/blob/master/assets/plugins/contentblocks/config/all_fields.php.sample#L37-L38
