### ISSUE TITLE
Extras buttons on 1.4.1

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#571]
Just noticed on 1.4.1. These 3 buttons are not translated anymore.

![extras](https://user-images.githubusercontent.com/523389/37349069-defc4d46-26d5-11e8-97b2-49b5dcc259fc.png)

**Comment by dmi3yy** [comment]
need add translatу here https://github.com/evolution-cms/evolution/tree/develop/assets/modules/store/lang

**Comment by fourroses666** [comment]
Hope you don't mind I have translated in this post.

I don't know why there are 2 files.
I think both work but maybe we can remove one and always use UTF-8 for Nederlands/Dutch?
For all language files? Maybe I'm wrong but don't know why both are needed.

```
+/* Installation by file-upload */
+$_Lang['install_file'] = "Установка из архива";
+$_Lang['choose_file_msg'] = "Выберите файл";
+$_Lang['install_file_btn'] = "Установить";
+$_Lang['install_file_success'] = "Установка завершена";


+/* Installatie file-upload */
+$_Lang['install_file'] = "Installatie vanuit archief";
+$_Lang['choose_file_msg'] = "Selecteer een bestand";
+$_Lang['install_file_btn'] = "Installeer";
+$_Lang['install_file_success'] = "Installatie voltooid";
```

**Comment by fourroses666** [comment]
Thanks
