### ISSUE TITLE
Saving system configuration on iPhone

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#572]
On iPhone (6s - Safari or Chrome browser) in **portrait mode** the 'System Configuration' page will not save. Clicking the green save button (which is off the screen to the right) just jumps the display back to the left without saving. Might be related to the tab issue https://github.com/evolution-cms/evolution/issues/566?
No issue on Galaxy (A5) or iPad.

**Comment by bossloper** [comment]
I have found what the iPhone issue is. It is due to the iframe width being set to the iPhone landscape width instead of the portrait width so not acting with the correct responsive page and causing layout issues. Just not sure how it should be solved. And it will be related to this issue too https://github.com/evolution-cms/evolution/issues/566

It is described here:
https://stackoverflow.com/questions/20123960/how-to-get-iframe-width-100-in-iphone-portrait-view/20142280
and here:
https://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari#answer-23083463

**Comment by dmi3yy** [comment]
Thank will be test

**Comment by bossloper** [comment]
This iFrame problem on iPhone also extends to iPad so a general iOS issue. On iPad for example if I have global tabs enabled then the left menu tree is hidden and does not appear. I can also not drag/scroll around the pages reliably. I would save virtually unusable, at best very frustrating on an iOS device :-)

**Comment by bossloper** [comment]
@dmi3yy - have you had chance to check this commit yet? #647? :-) It works both with and without global tabs. Thanks.

**Comment by dmi3yy** [comment]
Nice work. Thanks !
