### ISSUE TITLE
Translation 'de'

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#573]
assets/js/euiuploader/lang/de.js `

_euiuLang = [];
_euiuLang['upload'] = 'Upload';
_euiuLang['file'] = 'Datei';
_euiuLang['size'] = 'Größe';
_euiuLang['progress'] = 'Fortschritt';
_euiuLang['files_upload'] = 'Dateien hochladen';
_euiuLang['cancel'] = 'Abbrechen';
_euiuLang['close'] = 'Schließen';
_euiuLang['uploaded'] = 'Hochgeladen';
_euiuLang['server_error'] = 'Server-Fehler: ';
_euiuLang['parse_error'] = 'Fehler bei der Verarbeitung';
_euiuUploadResult = [];
_euiuUploadResult['upload_failed_1'] = 'Datei ist größer als upload_max_filesize';
_euiuUploadResult['upload_failed_2'] = 'Datei ist größer als erlaubt';
_euiuUploadResult['upload_failed_3'] = 'Die Datei wurde nur teilweise hochgeladen';
_euiuUploadResult['upload_failed_4'] = 'Es wurde keine Datei hochgeladen';
_euiuUploadResult['upload_failed_6'] = 'Es ist kein temporärer Ordner vorhanden';
_euiuUploadResult['upload_failed_7'] = 'Fehler beim Schreiben der Datei auf die Festplatte';
_euiuUploadResult['upload_failed_8'] = 'Eine PHP-Erweiterung hat den Datei-Upload gestoppt';
_euiuUploadResult['unable_to_process_file'] = 'Fehler bei der Verarbeitung der hochgeladenen Datei';
_euiuUploadResult['unable_to_move'] = 'Fehler beim Speichern der Datei';
_euiuUploadResult['forbidden_file'] = 'Upload der Datei unzulässig';
_euiuUploadResult['unable_to_create_folder'] = 'Fehler beim Erstellen des Upload-Ordners';

`

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/6f9009b6700d38e6c678d1d34cc83b1f0f498564
