### ISSUE TITLE
File base path and File Manager path incorrect

### ISSUE THREAD

**Issue by lottaar** [evolution-cms/evolution#574]
After upgrading to Evo 1.4.1 I'm having various issues (e.g. can't save resources and can't install Extras). I suspect it's related to the error message I'm getting in the dashboard:

'The currently set File base path seems incorrect.'
'The currently set File Manager path seems incorrect.'

Where can I change these? I've checked in the System settings but can't find them there, and I've also tried doing an Advanced upgrade, but my database credentials aren't accepted in the final step (when going back it looks like my database password has been changed and I've tried changing it back several times with the same result).

**Comment by pmfx** [comment]
Have tried to reset `File Manager path` and `File base path` in system configuration? It is in file manager and file browser tabs.

**Comment by lottaar** [comment]
I can't find those tabs...? Sorry for the Swedish, I've tried changing Manager language to English but that won't work either...

<img width="1037" alt="skarmavbild 2018-03-16 kl 15 41 19" src="https://user-images.githubusercontent.com/208279/37526769-8a556f18-2930-11e8-9dba-42a5daedd619.png">

**Comment by dmi3yy** [comment]
turn off tinyMCE 3 plugin and check setting again

**Comment by pmfx** [comment]
Looks like after upgrade issue.
Try to disable all TinyMCE plugins.
Go to system settings and save changes.
Remove old (unnecessary) TinyMCE leaving only the latest one.
Go to system settings - interface and select TinyMCE as a editor and save.

**Comment by lottaar** [comment]
I don't think TinyMCE is installed actually, at least I can't find it anywhere. Where would it be if it was installed?

**Comment by pmfx** [comment]
Elements > Plugins

**Comment by lottaar** [comment]
Alright, it wasn't in the Plugins menu but on the actual plugins page I found an instance of TinyMCE that was active. After disabling it lots of new tabs appeared in system settings and after resetting paths etc. and saving things seem much more normal. Phew! Thanks a lot for your help!

**Comment by pmfx** [comment]
No problem :)
