### ISSUE TITLE
iMac Chrome KCFinder no popup

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#575]
When clicking and using CTRL on MAC you see a popup nav.
In KCFinder you see an popup nav when clicking on an image with CTRL.
I noticed the popup is not visible with Chrome.

Evo 1.4.0

![subnav](https://user-images.githubusercontent.com/523389/37594140-afa49550-2b74-11e8-997c-f8e8b694739a.png)

**Comment by fourroses666** [comment]
I don't use Chrome as default browser but its a pritty important bug!

Here it does works; https://kcfinder.sunhater.com/

**Comment by janniconl** [comment]
In windows Firefox no menu here when using CTRL+click on an image.

You can select multiple images with CTRL+click, which is the expected behavior in my opinion.

**Comment by fourroses666** [comment]
For MAC there is no secundairy mousebutton, when using CTRL it acts like it does, but unfortunately it doesn't work with Firefox.

**Comment by fourroses666** [comment]
Thx Nico, I now can. Maybe its not a default setting or else I have set it to off in the past.
Don't know why but it now works in FF (with CTRL too).
Maybe its fixed with an FF update.
