### ISSUE TITLE
Ditto + Cross References [(enable_filter)]

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#578]
@dmi3yy 

Can a developer please verify that the code that @yama added is still there please

So far as I recall @yama fixed Ditto to work with the inbuilt filters / cross references, but I just tried and they don't work

The old post can be [found here](https://github.com/modxcms/evolution/issues/1127) and [the commit](https://github.com/modxcms/evolution/commit/b6f51451477e96940cf0f59d901d6716156f4c28)

**Comment by dmi3yy** [comment]
Migrate to DocLister ) 

https://github.com/Nicola1971/Ditto-to-DocLister-Reference-Tables

**Comment by modxuser** [comment]
@dmi3yy 

At this moment in time I can't

**Comment by dmi3yy** [comment]
What Ditto call you cant move to DocLister  send, i Help )) 

its better way

**Comment by AgelxNash** [comment]
Outdated
