### ISSUE TITLE
Unpredictable work of <@IF> and modifiers if values are empty

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#58]
Есть в шаблоне конструкции вида: 
1) {{TOP_PART? &leftcolumn=`submenu`}}
2) {{TOP_PART? &leftcolumn=``}}
3) {{TOP_PART}}
4) {{TOP_PART? &leftcolumn=`newmenu`}}

В чанке TOP_PART следующий код:

                        [+leftcolumn:isnotempty:then=`не пусто`:else=`пусто`+]<hr>
                        <@IF: [+leftcolumn:isnotempty+] >
                                Не пусто
                        <@ELSE>
                                Пусто
                        <@ENDIF>
                        [[if? 
                                &is=`[+leftcolumn+]:!empty` 
                                &then=`не пусто` 
                                &else=`пусто`
                        ]]
                         [+leftcolumn:is(`submenu`):then=`совпало с submenu`:else=`не совпало`+]
                        <@IF: [+leftcolumn:is(`submenu`)+] >
                                Совпало с submenu
                        <@ELSE>
                                Не совпало
                        <@ENDIF>
                        [[if? 
                                &is=`[+leftcolumn+]:eq:submenu` 
                                &then=`совпало c submenu` 
                                &else=`не совпало`
                        ]]

В результате предсказуемые результат получаем только в случае (1) ({{TOP_PART? &leftcolumn=`submenu`}}), в остальных случаях получаем либо игнорирование условий проверки на значение, либо ошибку проверки на пустоту.
Подробнее было протестировано вот здесь:
http://modx.im/blog/questions/5293.html

**Comment by yama** [comment]
Thanks. It is determined that "variable value is empty" and "variable does not exist". If it is judged that "the value of the variable is empty", it is pointed out that side effects will occur. Since we need to investigate, please keep it on hold for a while.

**Comment by pmfx** [comment]
Has this been investigated/solved?

**Comment by yama** [comment]
Is this solved?

**Comment by Dreamer0x01** [comment]
Добрый день. 
Нет, все еще не работает.
Провел тест - результаты в приложенном архиве по ссылке:
https://yadi.sk/d/5Jzf3BPd3N924q

На картинке - результат вывода, а в текстовых файлах - шаблон и чанк, на котором я это тестировал.
Может быть, я не правильно применяю конструкции <@IF>, но по ним и документации нет. 
А проверка на пустоту вообще теперь корректно не работает ни в модификаторах, ни в сниппете if.

**Comment by yama** [comment]
[testcase.zip](https://github.com/evolution-cms/evolution/files/1324767/testcase.zip)
thanks, I rewrite testcase.
Maybe, this is seem to chunk with parameters issue.
If possible, it is better to set default values as property for chunk like snippets and plugins.

**Comment by Dreamer0x01** [comment]
Дело не только в параметрах умолчания у чанка, хотя было бы замечательно иметь возможность их задать, но как?

Ошибка обработки есть еще и в конструкции `
<@IF: [+leftcolumn:is(`submenu`)+] >
`

В моем тесте видно, что при переданном параметре leftcolumn='submenu' эта проверка на равенство не прошла.

**Comment by yama** [comment]
```
1. Вывод без параметров
```
It can not be solved in this release. Think about the solution with v1.5 or later. Currently, need to set value. It may be empty value.
```
2. Вывод со значением leftcolumn=`left`
3. Вывод со значением leftcolumn=`submenu`
4. Вывод со значением leftcolumn=``
```
Probably, is not so difficult.

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/commit/cbb45b72168bed3647056501979092fb3551bc15
testcase 1 still not fixed
testcase 2-4 maby fixed

**Comment by Dreamer0x01** [comment]
Стало гораздо лучше. 

Проверка значения на пустоту действительно пока еще не правильно работает в сниппете "if", если параметр в чанк вообще не передан. 
Сравнение со значением, если оно передано, теперь во всех конструкциях работает корректно.

**Comment by yama** [comment]
Благодарю вас. I'll consider the behavior when the parameter is not set in future releases.

**Comment by Dreamer0x01** [comment]
:)
Thank you.
どうもありがとう
