### ISSUE TITLE
MySQL strict mode and Parse Error

### ISSUE THREAD

**Issue by devbeta** [evolution-cms/evolution#580]
Execution of a query to the database failed - Expression #16 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.t2.templateid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by:

SQL > SELECT t1.*, IF(t2.templateid,0,1) AS disabled FROM `db`.`modx_site_tmplvars` AS t1 LEFT JOIN `db`.`modx_site_tmplvar_templates` AS t2 ON t1.id=t2.tmplvarid GROUP BY t1.id ORDER BY t1.name ASC LIMIT 20

REQUEST_URI | http://site.org/manager/media/style/default/ajax.php

Solution:

SQL > SELECT t1.*, ANY_VALUE(IF(t2.templateid,0,1)) AS disabled FROM `db`.`modx_site_tmplvars` AS t1 LEFT JOIN `db`.`modx_site_tmplvar_templates` AS t2 ON t1.id=t2.tmplvarid GROUP BY t1.id ORDER BY t1.name ASC LIMIT 20

**Comment by dmi3yy** [comment]
ANY_VALUE work only in mysql 5.7 ) 

fix by remove Group BY

**Comment by dmi3yy** [comment]
not fixed yet

**Comment by devbeta** [comment]
Then so...

SQL > SELECT t1.*, IF(t2.templateid,0,1) AS disabled FROM db.modx_site_tmplvars AS t1 LEFT JOIN db.modx_site_tmplvar_templates AS t2 ON t1.id=t2.tmplvarid GROUP BY t1.id, t2.templateid ORDER BY t1.name ASC LIMIT 20

**Comment by AgelxNash** [comment]
Relevant #560

**Comment by Ser1ous** [comment]
Fixed some time ago.
https://github.com/evolution-cms/evolution/pull/696/commits/e32d25e19fac819d982163d819dffa73f77d13a4
