### ISSUE TITLE
Resource Tree empty after update to 1.4.1

### ISSUE THREAD

**Issue by ael1875** [evolution-cms/evolution#582]
I've updated a site to 1.4.1 from 1.2. However the Resource Tree only displays the site name but none of the resources. The wheel opposite the site name just continually spins. If I click on the arrows above the site name nothing happens. 

![evolution-cms-141](https://user-images.githubusercontent.com/37675289/37801219-a2da28f2-2e1d-11e8-8f49-9fe3bfa297ca.jpg)

I've another site running 1.4.1 on the same host and that works fine. I've updated all the plugins, cleared the cache and reinstalled 1.4.1 but the problem persists. Any ideas please?

**Comment by dmi3yy** [comment]
Send plugins list

**Comment by ael1875** [comment]
Thanks

![plugins](https://user-images.githubusercontent.com/37675289/37805045-b8ea2fc2-2e2f-11e8-9681-a30f864f5701.png)

**Comment by dmi3yy** [comment]
Try turn of resource swither 


Отправлено с iPhone

**Comment by ael1875** [comment]
I disabled the Resource Switcher and it didn't make a different sadly. I then disabled all the plugins, both individually then all together, and still nothing in the resource tree.

**Comment by dmi3yy** [comment]
send screen of browser console or send me access (dmi3yy@gmail.com) i check

**Comment by dmi3yy** [comment]
trouble with file ajax.php 
http://take.ms/znmRU

file exist but return 404. 
test with new theme and now can't understand :(

**Comment by dmi3yy** [comment]
I think its server troube. 
need see what write in server error log

**Comment by ael1875** [comment]
Thanks for looking into my issue. Attached are the only server error logs I
can find.

Regards

Gregg

**Comment by dmi3yy** [comment]
see attached file, but its not help (

**Comment by ael1875** [comment]
Thanks for looking, much appreciated. 

I'll have a look into this tonight. I can always roll it back to 1.2 hopefully. :)

**Comment by dmi3yy** [comment]
The reason is that the answer is not correct through Ajax
I suspect that something is not correctly configured on the server.
I recommend that you try to upgrade the version php to 7

**Comment by ael1875** [comment]
The odd thing is that I've another website running 1.4.1 on the exact same shared server without a problem.
I'll see if version PHP 7 is available.

**Comment by risingisland** [comment]
Just out of curiosity, did you try switching the admin theme?

**Comment by dmi3yy** [comment]
yes i add theme for check 

maybe trouble in php : 
why in eash folder php.ini ?

**Comment by ael1875** [comment]
The php.ini were the only way the site would work on a previous host. It consists of:

pcre.backtrack_limit=200000
magic_quotes = off
magic_quotes_gpc = Off
magic_quotes_runtime = Off
date.timezone = "Europe/London"

**Comment by ael1875** [comment]
Thanks dmi3yy, deleting the php.ini files worked! Resource tree now working. :)
