### ISSUE TITLE
Problem with "web_user" information

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#583]
Hello,

How can I get information about current logged in web_user?

`[*user.email*] or [+user.email+]` <--  this doesn't work.

**Comment by pmfx** [comment]
Hi. This should be helpful:
http://docs.evo.im/en/develop/api/getloginuserid.html
http://docs.evo.im/en/develop/api/getwebuserinfo.html

**Comment by modwebpl** [comment]
Thank you very much!
