### ISSUE TITLE
Blank error page after update to 1.4.2

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#584]
Here example, fresh update from 1.4.1 to 1.4.2 : http://modweb.pl/in-progress/samApp/cms//in-progress/samApp/cms

`Error : strpos(): needle is not a string or an integer`

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /sites/mwb/cms/in-progress/samApp/cms/assets/snippets/FormLister/core/FormLister.abstract.php
Line | 873
Source | $renderErrors = strpos($wrapper, '[+errors+]') !== false \|\| strpos($wrapper, ['+required+']) !== false;
Current Snippet | FormLister

**Comment by dmi3yy** [comment]
Reinstall 1.4.2  i  released first time without update DocLister and FormLister, then remove tag 1.4.2 add, and released one more time )

**Comment by modwebpl** [comment]
Ok, thx.
