### ISSUE TITLE
Добавить отправление email администратору при изменении файлов

### ISSUE THREAD

**Issue by HubraBibik** [evolution-cms/evolution#585]
Добавить отправку сообщения администратору на почту, когда изменяется один из файлов htaccess или index.php, и так выводится сообщение на главной админки, но не каждый день заходишь в админку всех сайтов. Это поможет своевременно отреагировать на заражение сайта.

**Comment by AgelxNash** [comment]
Лучше добавить событие. Кому нужно - плагин состряпает и отправит уведомление куда нужно email/slack/telegram/etc...

**Comment by Pathologic** [comment]
Так ведь файлы и проверяются только при заходе в админку, поэтому толку не будет, что так, что с событием. Но можно вынести отдельно код для проверки, чтобы можно было написать скрипт проверки и повесить его на крон.
