### ISSUE TITLE
After Upgrade TinyMCE4 is always disabled

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#588]
Title says it all. After a system upgrading TinyMCE4 is always disabled even if it was previously enabled. Which means saving system configuration disables TinyMCE editor etc...

**Comment by fourroses666** [comment]
Yup noticed that too. And sometimes QM enabled while it was disabled.

——
Also have very weird “hard cache issues?” in Firefox. Sometimes after update no loaded tree resources, css differences in the tree icons. The dark theme as default? Could be issues when having a custom theme but switching to the Default one didn’t help. Checking in Chrome and the tree is there. Clearing cache and deleting history and cookies in FF didn’t help. 

Really have no clue whats going on. Is this only happening by me? Maybe its server/opcache related. I just don’t know why this weird behaviour. Switching themes didn’t go as should be. 

As if not everything is being reset after clearing manager cache.

**Comment by dmi3yy** [comment]
I will test and fix this

**Comment by dmi3yy** [comment]
fixed

**Comment by bossloper** [comment]
... not sure this is fixed.

**Comment by dmi3yy** [comment]
this fixed but will work on next release 
incorrect use Legasy name like this plugin name )

**Comment by dmi3yy** [comment]
tested with manual update and all ok

**Comment by dmi3yy** [comment]
Reopen but i think i fixed )

**Comment by bossloper** [comment]
:-) not sure I just enabled it, upgraded and it is disabled again.

**Comment by bossloper** [comment]
OK, agree fixed!
