### ISSUE TITLE
Cache issues after upgrading EVO to 1.4.1 / 1.4.2 (Trouble in FF 58)

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#589]
Does anyone else also have very weird “hard cache issues?” (in Firefox)??

Sometimes after update no loaded tree resources, css differences in the tree icons. 
The dark theme as default? 

Could be issues when having a custom theme after upgrade but switching to the Default one didn’t help. Checking in Chrome and the tree is there! 
Clearing cache and deleting history and cookies in FF didn’t help. Tryed allot of options.

Really have no clue whats going on. Is this only happening by me? 
Switching themes didn’t go as should be. Maybe its server/opcache related. I just don’t know why this weird behaviour.

As if not everything is being reset after clearing manager cache.
After having FF closed and after a while the tree was finally back.
It sounds like just cache issues but I find this very weird behaviour, its really hard cached.

I had the issues on 1.4.1 too.
I might make a screenvideo to show it.

**Comment by risingisland** [comment]
I too have been experiencing this problem, but not just on 1.4, but on pretty much all versions.
I think that this is a FF problem personally. I noticed this shortly after one of their updates. Could be wrong though.
Opening the  manager in private window seemed to work.
Also, after clearing cache with [FF plugin](https://addons.mozilla.org/en-US/firefox/addon/empty-cache-button/?src=api) set to reload after clear, and everything seemed to work again.

**Comment by fourroses666** [comment]
Thx, used to have that plugin too.
Private window is something I didn't try yet.
Will check on next upgrade.
Glad its not just me.

**Comment by bossloper** [comment]
@fourroses666 Yes I also see the missing site tree with Firefox on a default installation. If I click the 'Expand site tree' icon then the tree magically displays again. Then if I refresh the browser (F5) it disappears again! No errors showing that I can see. @risingisland - yes 'Private  window' works for me too.

**Comment by fourroses666** [comment]
Oh, haven't tried on a clean/fresh install. Weird it only happens in Firefox.

**Comment by risingisland** [comment]
I am not completely positive this is only in FF. But, as there have not been any other reports, as of yet.
For me, FF is my primary browser, so its logical that there would be cached info, and not any in another browser.

**Comment by bossloper** [comment]
I don't necessarily see it as a caching issue. The dark tree is now the default theme. It seem mostly that it is not initializing the tree when the page is loaded as clicking the'Expand site tree' works, so maybe something going on in https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/js/modx.min.js but I do not see the same issue on Edge or Chrome or Safari (iOS) so looks FF related to me.
The fact it then works for a FF Private window is even more bizarre!

**Comment by 64j** [comment]
@bossloper 
clear cache in FF - Ctrl+Shift + Del

**Comment by bossloper** [comment]
@64j - that does not help. The site tree is blank until either expanding site tree, contracting site tree or refreshing site tree from the buttons at the top of the site tree. Then as mentions previously if I refresh the page (F5) it disappears again. Inspecting page with F12 the #treeRoot is empty.

**Comment by risingisland** [comment]
What version of FF are people using?
Previously I was using 57.0 without any problems. I just upgraded to 59.0.1, and this is when the problem started happening. To double check, I just loaded my previous version, and everything is working as intended. I checked an older site with Evo 1.2.2 up to recent, all ok. But all have problems loading  with the v59 of FF. Both tree and welcome frames seem to hang while loading.

**Comment by fourroses666** [comment]
I have 59.0.1 on Mac.

**Comment by bossloper** [comment]
59.0.1 on Windows 10

**Comment by bossloper** [comment]
Sorry don't use FF regularly, just have it installed for periodic compatibility checks. My FF auto updates so likewise it probably worked ok until the latest version.

**Comment by fourroses666** [comment]
Here auto update too.*

**Comment by risingisland** [comment]
Maybe try to [downgrade](https://ftp.mozilla.org/pub/firefox/releases/)?
[58.0.2](https://ftp.mozilla.org/pub/firefox/releases/58.0.2/) was the previous version (which I have not tried), I can confirm [57](https://ftp.mozilla.org/pub/firefox/releases/57.0/) is working fine.
A few other links that may be of use:

- https://support.mozilla.org/en-US/kb/install-older-version-of-firefox#w_i-still-want-to-downgrade-ae-where-can-i-get-the-previous-version
- https://support.mozilla.org/en-US/questions/1186624

I personally have mine set not to auto-update, and create a backup before I do. First time that it has paid off :wink:

**Comment by bossloper** [comment]
I downgraded to FF 57.0.4 and Evo works fine so yes there is something in FF latest version the broke Evo.

**Comment by modxuser** [comment]
Just to add my 2 cent :)

I have installed 1.4.1 on local and live systems:

- 19 x update
- 2 x full install for testing different stuff

I mainly use FireFox and test in the other browsers

I currently have 59.01 64bit installed and haven't had any problems at all

**Comment by bossloper** [comment]
I just upgraded FF back to 59.0.1 after downgrading to 57.0.4 and now Evo is working fine. So presume something was cached, even though I had cleared everything from the FF cache multiple times. Puzzled, but cannot now reproduce the errors @fourroses666 and @risingisland get.

**Comment by fourroses666** [comment]
Just did an update 1.2.1 > 1.4.2 and there where no issues in FF.
Will report if it happens.

**Comment by fourroses666** [comment]
Well I will close this because its more or less a Firefox cache thing. Reopen if it keeps giving problems.
