### ISSUE TITLE
Edit Resource on iPad/iPhone - Missing Action Buttons

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#59]
RE: https://github.com/modxcms/evolution/issues/1363
I am still seeing issues here.
For iPad Air 2 / Safari browser.
If I now edit a resource by clicking it in site tree the resource opens for edit,
but:
1) the action buttons are missing. 
2) The left site tree also auto collapses, but clicking the show/hide site tree icon does not bring it back.
After that the whole manager does not then show the site tree until I clear browser cache.

I see something similar using Chrome browser with iPad. But here first edit on iPad is ok. Subsequent edits the buttons do not display but if I rotate the iPad 90 degrees and back again then the action buttons appear! Site tree is also auto hiding when editing (is that by design?) but will respond to the show/hide button, unlike Safari.

Using latest evo 1.3 clean install.

![img](https://user-images.githubusercontent.com/1744687/28259110-98180f52-6acc-11e7-93c9-7003276d53d7.jpg)

**Comment by dmi3yy** [comment]
Can you test one more time ?  on iphone now all ok

**Comment by bossloper** [comment]
Still same issues for iPhone and iPad, latest dev install.

**Comment by dmi3yy** [comment]
cant reproduce on iphone 6 ( 
![img_9687](https://user-images.githubusercontent.com/669491/28389783-400f39d2-6ce0-11e7-9817-d2a0eb24a93e.PNG)
![img_9688](https://user-images.githubusercontent.com/669491/28389785-40334dcc-6ce0-11e7-96ed-67043afd6ec4.PNG)
![img_9689](https://user-images.githubusercontent.com/669491/28389786-4036a29c-6ce0-11e7-830a-6f87553adf17.PNG)
![img_9690](https://user-images.githubusercontent.com/669491/28389784-4032bd94-6ce0-11e7-9825-657ee3feeeaf.PNG)

**Comment by bossloper** [comment]
Very strange. I'm looking for reasons why. Your last screen grab does not mach mine. I do not see truncated fields on the right side. Could it be related?
![img_2507](https://user-images.githubusercontent.com/1744687/28407911-c7422e3a-6d2d-11e7-9575-a2b9178195ed.PNG)

**Comment by bossloper** [comment]
Further detail, there is a specific set of steps to reproduce.
- * iPhone in landscape mode (do not alter at any time).
- Close browser (safari) and then open a new browser.
- Click to edit a resource - Action buttons do show correctly this first time editing
BUT
-  Then click to show site tree and click to edit a resource a *second time* (can be same or different resource).
- From this second time onward the action buttons do not show in this landscape mode edited resource.
- They can be made to reappear by rotating phone to portrait (and back again if required)

**Comment by dmi3yy** [comment]
yes now reproduce

**Comment by bossloper** [comment]
For whatever reason this seems to be working correctly on the current develop so I will close issue.
