### ISSUE TITLE
The need for an (English) forum

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#590]
Now EVO is seperated from MODX we need a new forum.

http://modx.im is only Russian. 
There are allot of "English language" EVO users who can't ask questions on a central point.
Some here in Github, some on Slack and some in forums.modx.com.
I don't use the forums.modx for a long time now.

My guesses are MODX is going to remove EVO from their forum or use a totally new forum. 
We need to have a decent forum. EN/RU
I'm not sure what the plans are. 

modx.im --> http://forum.evo.im  and multi-language and restyled?

**Comment by bossloper** [comment]
Agreed, we need a lively progressive forum (presumably default English, but I feel lucky/ashamed/logical that it is English) that can branch out to different languages as appropriate to take the stress from GitHub which should be focused on bug fixes and development rather than day-to-day issues.

**Comment by dmi3yy** [comment]
After realise 1.5.0 i start do evo.im 
Multilang by default ;) 

Need some time can’t do all what i wont now;)

**Comment by fourroses666** [comment]
Oke great D, its important, needs to be on top of the to do list.
