### ISSUE TITLE
Modx evo + TinyMCE4

### ISSUE THREAD

**Issue by MicZoloto** [evolution-cms/evolution#593]
После обновления движка до версии 1.4.2 пропал редактор TinyMCE. Установив его через extras, отображается просто белое окно без кнопок редактирования. Как это можно исправить, спасибо?

**Comment by dmi3yy** [comment]
Исправили уже, будет релиз на днях 1.4.3 или скачайте с гита с девелоп

**Comment by MicZoloto** [comment]
ок, спасибо
