### ISSUE TITLE
phpmailer

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#594]
Hi
thanks for all your great work. in issue 302   https://github.com/evolution-cms/evolution/issues/302   i asked about including phpmailer after version 6 .

in your new EVO-1.4.2 IN:

/manager/includes/controls/phpmailer

in class.phpmailer.php it says the phpmailer version is '5.2.21'

and in PHPMailer.php it says the phpmailer version is '6.0.3'

Does anyone know why we have both and which one is operational ? should the older one be removed if the new one (6.0.30 is being used?

Gerard

**Comment by dmi3yy** [comment]
there no file with name class.phpmailer.php   

https://github.com/evolution-cms/evolution/tree/develop/manager/includes/controls/phpmailer

Its old file and you can delete it

**Comment by user83743** [comment]
thanks Dmytro, i should have checked a clean install. that site was ungraded from modx 1.2.1 so the installer left the old phpmailer files there. thnaks for the quick reply and the amazing work.
