### ISSUE TITLE
https issues?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#596]
I have a website and when trying to upgrade it I see my page not found page, when I look at the source I see the base href is http:// while my site shows https on all pages.

(Now I see 1.4.2 while the site still is on 1.4.0 - Huidige versie = Current version)
![huh](https://user-images.githubusercontent.com/523389/38075309-3a1570e6-3332-11e8-8d50-ace923d3f532.png)

Don't know if its related or just some server setting but I have a site where I can browse with the File Manager but when wanting to edit I also see the page not found. Can't remember if that always was the issue but lately its set to https://

**Comment by bossloper** [comment]
RE: 1.4.2 while the site still is on 1.4.0 
- That probably means the installer did not run to completion. If you go to https://<your-site>/install it might still be there. 
I've updated https sites no problem (though that was the 1.4.2 version).

**Comment by fourroses666** [comment]
No install folder.
And yes it showed 1.4.2 only after pressing the Update button (which didn't work).

But I have this issue only on this host so could be a server restriction or somekind.

----

I can try to manually upload the instal folder and see if the installer then works.
Need to find some time to check.

**Comment by fourroses666** [comment]
Oke so I uploaded the install.php.
After selecting an install I get redirected to the page not found, the URL is:
https://mysite.com/install/index.php

It deleted the install.php file from FTP but no install folder.

**Comment by bossloper** [comment]
That is the wrong file. The /install folder is a whole set of filesfrom here : https://github.com/evolution-cms/evolution/tree/develop/install
Maybe that host is not allowing the original updater process to add the install folder (a file permission issue).

**Comment by bossloper** [comment]
I would probably run the install manually again from 1.4.2 zip file. https://github.com/evolution-cms/evolution/releases

**Comment by fourroses666** [comment]
Yea, just wanted to do a fast update with the install.php file.
The manual update will probably work.

I'm going to blame this issue to the server and close it. Thx!
