### ISSUE TITLE
Dark theme default

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#597]
Dark theme switcher should be a saved setting in the database? 
Even when choosing light theme the next day I see the dark theme.
Or a default choise on Configuration > Interface tab, and/or on the User management set per user?

I have a custom theme and my default theme is already looking pritty much the same as the dark theme. I even don't need the button actually. 

So maybe the best would be add the option to have a theme color switcher, and also add it to the user settings? Default dark or light.

I understand the dark theme is set to default, that one is much better.
Do we even need the light theme?

**Comment by dmi3yy** [comment]
Yes we already move this into settings.  soon will be 1.4.3 with that )

**Comment by fourroses666** [comment]
Ah didn't know :)

**Comment by bossloper** [comment]
@dmi3yy - is this change finished? In latest dev the 'color scheme' option do not seem to be working quite right to me. 
'everything is light' and 'the header is dark' seem to be the same.
'everything is dark' has a light resource tree. 
'Header and sidebar are dark' also uses dark codemirror which I would have though goes with 'everything is dark'?
If 'side bar' refers to the 'resource tree' then the text needs changing as everywhere else it is referred to as the 'resource tree'.
Finally :-) what is 'header' referring to? Is that the top menu, if so it always seems to be dark.

**Comment by dmi3yy** [comment]
now working with this  will be finished soon )
