### ISSUE TITLE
Shrinking browser width results in site tree overlay

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#60]
When shrinking the bowser width at a certain width the right pane snaps to the left and is under the site tree. Then if I click to hide the site tree the whole right pane is then visible. The site tree cannot be redisplayed.

Latest 1.3 clean install using Windows 10 with Chrome browser or Edge browser.

![i](https://user-images.githubusercontent.com/1744687/28259585-e0b32d4e-6ace-11e7-947d-61629eb04b4a.jpg)

**Comment by bossloper** [comment]
Not sure this is fixed yet.

**Comment by 64j** [comment]
Clear cache.

**Comment by bossloper** [comment]
I did already. I cannot see why this would fix it anyway as the issue is when on a desktop PC not a mobile device.

**Comment by bossloper** [comment]
p.,s. it would be better for me to close issues I have created after I have validated them as I now have no way to reopen this issue. Thanks! :-)

**Comment by 64j** [comment]
What is the width of your browser window?

**Comment by bossloper** [comment]
It triggers at 840px or less. From the debugger it seems to be something to do with this:
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/css/page.css#L36

**Comment by bossloper** [comment]
I'm guessing this is designed behavior? It does look a bit strange, particularly for managers not familiar with the show/hide site tree button. Maybe the site tree needs to auto hide when the browser is reduced to 840px?

**Comment by 64j** [comment]
It is made for the manager to see the changes and react to this.

**Comment by bossloper** [comment]
ok, just looks strange that the right pane is hidden and so unusable unless you hide the menu tree. I will see if I can suggest another solution....

**Comment by fourroses666** [comment]
Yea I didn't expected this too, looks a bit like a "bug". Isn't it better to just hide the tree and on clicking the topleft nav button to show it?

**Comment by fourroses666** [comment]
Or even better, make it a push and not overlay?

**Comment by bossloper** [comment]
I'd like this issue to be reopened if we can as something needs changing to make it more intuitive/ergonomic.
