### ISSUE TITLE
Refresh tree icon for TVs not working

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#601]
Minor bug;

When I add some TVs they're not visible in the resource tree.
Also the refresh icon doesn't show them.
With Chunks it does work thow!

For the TVs only on full page refresh.

![refresh-tv](https://user-images.githubusercontent.com/523389/38084216-4b729d9a-334c-11e8-92af-5497f6cae0ec.png)

**Comment by pmfx** [comment]
I've tested latest dev and couldn't replicate the issue. Added TVs shows up fine in the tree.

**Comment by pmfx** [comment]
Does it happen with default theme or custom Manager theme?

**Comment by 64j** [comment]
@fourroses666 
Move the mouse cursor to another item, and then back to the TV
