### ISSUE TITLE
bug for resource tree scrolling.  EVO1.4.2

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#603]
Hi

i have a number of sites on evo1.4.2 now and it's running great thanks. i noticed a bug in the resource tree. if there is a large number of snippets or chunks, you CAN scroll down to the last one. but if there is a large list of resource web pages, or if you expand the tree with that down arrow button "\/" you CANNOT scroll down to see the last 2.  can anyone else see that? i tried a few different sites and they all have that issue. i searched for "scroll" "scroll bar" etc in the search box above and didn't see anyone else mention it.

thanks

G.

**Comment by pmfx** [comment]
Probably related to ElementsInTree plugin. Needs CSS fix.

**Comment by user83743** [comment]
thanks Piotr. you have 1.4.2 installed too and you can see same?

**Comment by bossloper** [comment]
I can also see the same on 1.4.2. If I disable ElementsInTree then all works fine. The css for the manager was adjusted recently and the calculations for the left tree height when using ElementsInTree  are no longer correct: https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/elementsintree/assets/txt_content.tpl#L281

**Comment by user83743** [comment]
THANKS BOSSLOPER.

**Comment by pmfx** [comment]
@user83743 yes, I have the same issue.
