### ISSUE TITLE
Visual bug: Last element in tree cut off

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#604]
With recent Evo CMS 1.4.2.

Visual bug: Last element in tree cut off:

![screenshot 2018-03-31](https://user-images.githubusercontent.com/6764548/38160268-8af33312-34c3-11e8-9f83-4df9cc99a823.png)

Bottom of browser window (latest Chrome).

**Comment by bossloper** [comment]
this has already been logged in the previous issue: https://github.com/evolution-cms/evolution/issues/603
