### ISSUE TITLE
Evo cuts some elements out of the code

### ISSUE THREAD

**Issue by devbeta** [evolution-cms/evolution#605]
Create chunk {{test}}:

<style> div#test{} </style>

In HTML output:

<style> div

**Comment by devbeta** [comment]
This setting breaks the code: minifyphp_incache

**Comment by modxuser** [comment]
Possibly related to [this](https://github.com/evolution-cms/evolution/issues/552)

**Comment by Deesen** [comment]
No clue how to solve it but this issue is happening here:

https://github.com/evolution-cms/evolution/blob/develop/manager/processors/cache_sync.class.processor.php#L486-L487

**Comment by dmi3yy** [comment]
it's the same with https://github.com/evolution-cms/evolution/issues/552

**Comment by dmi3yy** [comment]
#552
