### ISSUE TITLE
path to the file and image manager from the tree menu

### ISSUE THREAD

**Issue by virtualgadjo** [evolution-cms/evolution#606]
Hi,
it seems to be sort of a little bug, when clicking on the camera/iùage icon or the file one on the tree menu (evo 1.4.2) i run into a 404 page
path is manager/media/browser//browse.php?&type=images
instead of, i guess
manager/media/browser/mcpuk/browse.php?&type=images
of course mcpuk selected in the options (actually, not really the choice...)
but it works fine in tinyMCE where it's kcfinder in use

looking into the tree file, too bad, no href, the link must be in a js function i can't find out :)
(id="treeMenu_openimages" and id="treeMenu_openfiles" in tree.php)

all the best
chris

edited to say: forgot to say, fresh install, not an upgrade from an older release

**Comment by dmi3yy** [comment]
tested on dev version all ok
