### ISSUE TITLE
Cancelling a resource edit does not always remove lock (if Page Click Behavior is 'edit')

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#61]
- Edit a resource by left clicking resource in site tree (assuming Page Click Behavior is set to 'edit resource')
- Click the cancel button.
Result: Resource remains locked.

- If the resource is edited by right clicking in site tree and selecting 'edit resource'.
- Then click cancel
Result: The resource is correctly unlocked.

**Comment by Deesen** [comment]
Is it fixed with #101 ?

**Comment by bossloper** [comment]
Unfortunately I am away all week so not able to do further tests until the weekend.

**Comment by bossloper** [comment]
@Deesen - yes that fixes this issue.
