### ISSUE TITLE
new login page 

### ISSUE THREAD

**Issue by dmi3yy** [evolution-cms/evolution#611]
like https://github.com/pmfx/EvoRE3

but with custom in setting: 

form position:  left, right, center 
set logo [input: type image ]
set background [input: type image]

**Comment by janniconl** [comment]
If you use the ManagerColors plugin by @Nicola1971 you can already change a lot of styling (colors, custom css, logo, background)

In roughly 15 minutes I created this example:
![afbeelding](https://user-images.githubusercontent.com/1488614/38318788-807be404-3830-11e8-8cc9-b52297d877ab.png)

Requirements:
- ManagerColors plugin (3.1.9 RC currently)
- Upload a background or use one of the ones provided by the plugin in plugin settings
- Alternatively you can set option `Semi-Transparent login form` in form
- Custom chunk as `Custom Login styles` in settings, with code below inserted
````
a {color: #EE3F7E;}
.btn.btn-success {background-color: #EE3F7E;border-color: #EE3F7E;}
.btn.btn-success:hover,.btn.btn-success:active,.btn.btn-success:focus {background-color: #d32160;}

.page {
	padding: 0;
	height: 100%;
}

.loginbox {
	max-width: 400px;
	height: 100%;
	width: 25%;
	margin: 0;


	display: flex;
	align-items: center;
	justify-content: center;
}
````
(I did not include the responsive styles, but should not be a problem. It will fallback to default.)

So my idea: just write a good tutorial on this and use @Nicola1971's great plugin!

**Comment by janniconl** [comment]
P.s.: add this to your css to your chunk for a nice sideways animation (instead of going up)

````
.loginbox {
	webkit-animation-name: anim-loginbox-sideways;
	-moz-animation-name: anim-loginbox-sideways;
	animation-name: anim-loginbox-sideways;
}

@keyframes anim-loginbox-sideways {
	from { opacity: 0; transform: translateX(-30px); }
	to { opacity: 1; transform: translateX(0); }
}
@-webkit-keyframes anim-loginbox-sideways {
	from { opacity: 0; transform: translateX(-30px); }
	to { opacity: 1; transform: translateX(0); }
}
````

**Comment by pmfx** [comment]
@dmi3yy I think uploaded custom images should go to `/manager/media/style/default/images/login/custom/` Then only users that can change System Configuration will be able to modify those images.
