### ISSUE TITLE
Latest Evo Release 1.3.7 WTF

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#612]
@dmi3yy 

What's happening guys ?

We went from 1.4.1 to 1.4.2 now the release page says the latest release is 1.3.7

but a 1.4.3 has also been released on the same day and is in the list

**Comment by dmi3yy** [comment]
I write about support version ;) 

1.3 support for critical bugfix and security 
Until release 1.5 

Last current version is 1.4.3

**Comment by dmi3yy** [comment]
We are still support 1.2 but only security 

LTC support its good way

**Comment by modxuser** [comment]
You need to change the GitHub tag for 1.4.3 to become "latest release" as this is more than confusing

Also, in the README, the latest version showing is 1.3.7, not 1.4.3

**Comment by dmi3yy** [comment]
Ou thanks will fix tommorow
