### ISSUE TITLE
[O] English translators needed for docs.evo.im

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#614]
Seems we still need to translate allot on the documentation website.
http://docs.evo.im/en/03_extras.html

Maybe some of us can help out to translate.
Using Google translate and just translate some pages when having some free time will help out allot :)

**Comment by modxuser** [comment]
http://www.evolution-docs.com/extras/

**Comment by fourroses666** [comment]
docs.evo.im is the main documentation site.
on evolution-docs.com I see allot of old plugins.

So I think we need to concentrate on the docs.evo.im

**Comment by modxuser** [comment]
@fourroses666 

Marc, to a point you are right, but there are just as many, if not more, outdated plugins / snippets in evo.im

Also, English docs for Doclister and Formlister are in evolution-docs.com

The docs found in evo.im are pulled from GitHub so it's not as simple as just translating in Google and then adding the new text - you need markdown knowledge

As a side note - translating in Google is not as easy as many think, especially translating Russian tech. I found that out whilst I did the FormLister docs in evolution-docs.com and my mother language is English

**Comment by fourroses666** [comment]
For me its simple, docs.evo.im is more up to date but its lacking of translation.
So it needs to be translated. Githubs markdown isn't that hard. You are right about 1 on 1 Google translation but its better that not translated.
