### ISSUE TITLE
"SYSTEM UPDATE" / Upgrade warning message on EVO1.4.2 for editor, publisher and administrator

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#615]
Hi

all EVO1.4.2 sites are now seeing a warning message (which was on old systems too, but there was a mention of this being removed) on the dashboard screen:

"
System Update
Content management system is outdated. To update contact the site developers. Current version 1.4.3 

We strongly recommend making a backup before upgrading the system, the update is performed at your own risk !! 
"

which is a bit strong* for end users. Is there any way of preventing that warning message from being seen by non admins?

thanks

**Comment by risingisland** [comment]
In the manager, go to: Elements/Plugins/Updater
In the Configuration tab, you will see "Show widget for:"
Adjust this to your needs.

**Comment by user83743** [comment]
thanks @risingisland . i didn't think of that. super system and it works perfectly... naturally.
