### ISSUE TITLE
New Computer can't log in to Evolution

### ISSUE THREAD

**Issue by MarkTWIC** [evolution-cms/evolution#626]
I have a very odd problem. I have a new computer and I can't log in to Modx using the right username and password. I can on other computers, although one browser there has stopped working after I changed password. I'm sure it's not due to strange characters.

"Incorrect username or password entered!" is what I get. It's very odd. Never had anything like this before. I have no ideas what to do next.

I had Evolution 1.3x and in order to try and fix this issue I upgraded to 1.4.3 so I am up to date. But still the same issue.

Any ideas?

**Comment by fourroses666** [comment]
Is it saying Wrong password after login? I have one website which can’t get in too. But moving to an other host worked. Copying it back and again can’t login. Its weird. But don’t know if its the same issue you have.

**Comment by MarkTWIC** [comment]
I can login with one machine, but one of those browsers stopped working. Also I don't seem to be getting failed login attempts recorded. It sounds similar.

**Comment by fourroses666** [comment]
Sorry had to read it on mobile and somehow didn't see you have the exact same message. Using the "Forgot password" didn't work either. I got mail but when clicking on the link and try to change it I had the same message.

I'm not 100% sure but I think I changed the username from the client. And also could be right after that it was not able to login again by me or the client. But what I don't get is why its possible on an other host. It was on an 1.4.x version. Updated to 1.4.3 but still the same. "Incorrect username or password entered!"

**Comment by fourroses666** [comment]
I have had contact with the host. They have searched but couldn't find anything.
But now all of a sudden its possible to login again... both me and the client??!!
I think they did change something on the server. So my issue is solved but don't know what caused it.

**Comment by MarkTWIC** [comment]
I can log in with some browsers and not with others.

**Comment by pmfx** [comment]
Can this be related to browser cache/hosting issues? Can be closed?
