### ISSUE TITLE
Any possibility to save own values in Evo CMS?

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#628]
I am using question2answer which gives the option to save own values (text) to self-definied "option" fields. Example:

    qa_opt('myoptionname', $content);  // $content could be an HTML string

Then it is very handy to get this `$content` by calling `qa_opt('myoptionname')`.

I hope there is something similar with Evolution CMS? I could not find it in the docs yet.

My goal is to save some HTML content (that is created dynamically) and store it to such an "option field".

**Comment by Pathologic** [comment]
What is "option" field?

**Comment by pmfx** [comment]
Not sure if I understood you correctly.
Where do you want to store it? In `[*content*]` or a Template Variable? Do you want to pull data from there then? Is this even to be connected with EVO Resource?
I think you need to give us more details of what you are trying to do.

**Comment by q2apro** [comment]
An "option" field is just an arbitrary entry in an "options" table. It is like a **storage place**.

`name | content`

You define the name and the content yourself. You can receive the content at any time from within.

→ Where can I store data globally in EVO CMS using PHP? And then receive it using PHP.

**Comment by pmfx** [comment]
You will probably have to create a custom MySQL table and then use EVO api (PHP) to get and save data. Or just use PHP session if it's to be only for session lifetime.
