### ISSUE TITLE
Manager errors when Server Type is set to https

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#629]
Manager has errors when Server Type is set to https and .htaccess has "Redirect HTTP to HTTPS" un-commented.

Every page change or action seems to create a popup message with:

> This page is asking you to confirm that you want to leave - data you have entered may not be saved.

After clicking OK, the following message pops up briefly, but closes by its self and continues.

> Server isn't available. Check your internet connection!

If .htaccess has these redirects commented out, there are no errors.
Previous versions (previous to v4.x) on this server had no problems.
There are no error logs. Not sure what else can be checked?

![error2](https://user-images.githubusercontent.com/6113504/38628166-a03a6612-3da8-11e8-86a1-1652ece290b0.jpg)

**Comment by Deesen** [comment]
I also faced that issue and it seems it has to do with HTTP2 (or your server-config). When my hoster deactivated HTTP2 it worked without issues.

In my case it helped to replace `HEAD` by `GET` at https://github.com/evolution-cms/evolution/blob/develop/manager/media/script/main.js#L265

**Comment by risingisland** [comment]
Thank you @Deesen , I will try this later on this evening, or in the morning. 
Fighting this all day, and my brain is now fried.

What exactly does the `GET` do, or how did it help you?

**Comment by risingisland** [comment]
@Deesen THANK YOU SOO MUCH!!
I wasnt completely sure if my server was using HTTP2, so I just went ahead and replaced `HEAD` as you suggested, and that seems to have done it! I wish I could invite you for a beer right now.

**Comment by Deesen** [comment]
Very nice 👍
