### ISSUE TITLE
Previous-Next buttons not working in new theme

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#63]
MODX Evolution 1.3.0b
Навигация через работает неправильно при использовании кнопок вперед-назад или клавиатурных сокращений. Путь в адресной строке изменяется при каждом действии, но далеко не всегда происходит переход, примерно в 1 из 3 случаев, например, путь меняется при переходе по табам внутри элементов, но кнопки вперед-назад не работают и табы не переключаются (да пусть они и не переключаются по урлу вовсе, но не мусорят в историю), хотя в адресе меняется id вкладки, приходится нажимать "назад" несколько раз, чтобы вернуться на предыдущую страницу. Включена настройка "Запоминать вкладки". Отключение не меняет ситуацию

**Comment by dmi3yy** [comment]
Есть такой нюанс но тут нужно выбирать 1 из 2-х или у нас есть путь к текущему елементу в урл что дает возможность скопировать ссылку на документ или елемент или вернуть историю браузера 

как по мне текущий вариант удобней + возвращать назад в админке через браузер а зачем? можно ж подтянуть старые данные и перезаписать их :(

**Comment by sashabeep** [comment]
Я - за однозначное действие (переход) в любом случае при нажатии кнопок. Это базовый функционал и он должен работать. 

В предыдущей версии с фреймами было адекватнее, в Revo вроде похожая навигация через историю и она не всегда открывает то, что надо и не всегда копирование ссылки открывает тот самый элемент что нужно, но и там не так криво, ИМХО.

**Comment by dmi3yy** [comment]
А по другому там не сделать ибо мы изменить ссылку можем только после смены iframe 
в REVO нет ифреймов поэтому нет и таких штук. На текущий момент я не вижу как решить вопрос. Пока избавляться от iframe не планируем но при этом запоминать где мы находимся очень хочеться. И проще мириться с лишними нажатиями кнопки назад

**Comment by sashabeep** [comment]
В момент клика до перехода в историю написать какую-то другую ссылку можно, я только пока не могу разобраться как оно работает в новой админке

Делал на нескольких сайтах для полной аяксовости с сохранением пути, то есть если копировать ссылку то загрузится то самое, что пользователь предварительно накликал аяксом. У меня только в историю писалась ссылка после подгрузки, собственно, а тут, как я понимаю, надо ДО перехода записать что-нибудь в историю. Либо через replaceState после загрузки подменять текущий урл

https://developer.mozilla.org/ru/docs/Web/API/History/pushState
https://html.spec.whatwg.org/multipage/history.html#dom-history-replacestate

**Comment by dmi3yy** [comment]
Логика вот: 
https://github.com/evolution-cms/evolution/blob/develop/manager/frames/1.php#L310
на iframe onload выполняется вот это: 
https://github.com/evolution-cms/evolution/blob/develop/manager/media/style/default/js/modx.js#L272

тоесть в момент когда у нас перезагружается iframe мы меняем хеш в урл

**Comment by 64j** [comment]
@sashabeep 
тут дело в том, что всю дорогу, содержимое во фрейме менялось с помощью document.location, если бы меняли frame.src , то возможно было бы проще.
Сделал переходы по истории через window.history.replaceState, позже выложу исправления, надо ещё потетстить
