### ISSUE TITLE
После обнавления до версии 1.4.3, проблемы с редактором TinyMCE4 та и не исчезли.

### ISSUE THREAD

**Issue by MicZoloto** [evolution-cms/evolution#631]
Собственно описание проблемы в самом названии. Плагин установлен, в ресурсе галочка использовать редактор стоит, но в поле на белом фоне нет кнопок редактирования и вставок и т.д. 
Во в кладке "Интерфейс и представление" в разделе "Конфигурация" нет полей настройки плагина.

**Comment by 64j** [comment]
Отключите старый плагин tinyMCE-3
Должен остаться только один.
