### ISSUE TITLE
YAMS and 1.4.3 - veriword.php redirects to "pageNotFound"

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#632]
I use eForm with captcha for a YAMS site.

I noticed when the plugin is set to Disabled I can see the captcha image:
When I browse to: `site.com/manager/includes/veriword.php?rand=727040365`

But when YAMS plugin is enabled then it fails.
It did work on a 1.2.1 site but after update to 1.4.3 that stopped working.

**Comment by Deesen** [comment]
Inside plugin-code add `if(MODX_API_MODE) return;` after line 34:

    case 'OnWebPageInit':
        if(MODX_API_MODE) return;

**Comment by fourroses666** [comment]
Thanks D, that fixes it :)
