### ISSUE TITLE
"javascript:;" in chunks, templates 

### ISSUE THREAD

**Issue by AndreyMyagkov** [evolution-cms/evolution#634]
Если случайно перетянуть кнопку сохранить, отменить, удалить в поле редактирования чанка, шаблона, то в него вставляется строка "javascript:;".
Подробнее на видео
http://take.ms/2hGOR

**Comment by 64j** [comment]
@AndreyMyagkov 
По секрету..
Если выделить любой текст и перетащить его в любое редактируемое поле, эффект будет тот же.

**Comment by AndreyMyagkov** [comment]
Это понятно, но раньше такой проблемы не было, т.е. кнопки нельзя было случайно затащить в редактор, а сейчас у многих клиентов то там, то сям появляется javascript:;  или надписи с кнопок на разных страницах.

**Comment by 64j** [comment]
Это не проблема, а возможность браузера выделять текст у активных элементов
