### ISSUE TITLE
DITTO --> DOCLISTER

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#635]
Hi

i have been through the doclister docs but can't get an old [ditto] call to work for [doclister]. the doclister code runs and displays the data entries but the inner TV values are missing in all of them. for the TV "product-price" i tried [+product-price+] and [+tv.product-price+]  in the &tpl code. any ideas? thanks.

[+pagetitle+]  and [+summary+]   work fine and display data, but   TV values will not display. 

also, pagination does not work either.

**Comment by pmfx** [comment]
Have you defined required TV names in `&tvList` parameter?
```
&tvList=`product-price`
```
in tpl: `[+tv.product-price+]`

**Comment by user83743** [comment]
I DO NOW AND IT'S WORKING. thanks very much. is there anywhere where this kind of stuff is explained? any forum or chat sessions that I don't know about. modx forum is dead now for evo issues and obviously no mention of formlister or doclister there. nothing is explained here:  http://www.evolution-docs.com/extras/doclister/main-parameters   http://www.evolution-docs.com/extras/doclister/output-parameters . no mention of DLMENU anywhere.

**Comment by user83743** [comment]
any idea how pagination works for doclister?

we're shown the following


[+id_parameter.pages+] | Pagination-- | --
[+id_parameter.totalPages+] | Total number of pages
[+id_parameter.isstop+] | 1 if current page is the last
[+id_parameter.isstart+] | 1 if current page is the first

and this is what worked before:

 <p align="center" class="ditto_pages2">Showing xx <span class="ditto_pages2">[+start+]</span> - <span class="ditto_pages2">[+stop+]</span> of <span class="ditto_pages2">[+total+]</span> Products | Page <span class="ditto_pages2">[+currentPage+]</span> of <span class="ditto_pages2">[+totalPages+] xx [+id_parameter.totalPages+]</span></p>   

are there equivalents to the above placeholder values?

**Comment by user83743** [comment]
what is the "id_parameter"?

**Comment by pmfx** [comment]
http://www.evolution-docs.com/extras/doclister/examples
http://docs.evo.im/en/04_extras/dlmenu.html

Regarding pagination. If your snippet call is using `id` parameter like 
```
&id=`news`
``` 
then pagination placeholder will be `[+news.pages+]` 
If not it will be just `[+pages+]`

**Comment by user83743** [comment]
we're using:

[!DocLister?  &amp;id=`doclister55`  &amp;parents=`<?php echo $id55 ?>`   &amp;orderBy=`menuindex DESC, createdon DESC`   &amp;tpl=`blog-story-summary-shop2`   &amp;display=`9`  &amp;paginate = `1`  &amp;paginateAlwaysShowLinks=`1`  &amp;tvList=`product-price,page-right-aligned-image1,total, currentPage,totalPages,stop,start,pages` !]	

and the resources are returned and displayed but we have no pagination counters using:

Showing  [+doclister55.start+]  -  [+doclister55.stop+]  of  [+doclister55.total+]   Products | Page  [+doclister55.currentPage+]  of [+doclister55.totalPages+] 
	
the numbering does work though:

	 [+previous+] [+doclister55.pages+] [+next+]    

any ideas? it's EVO 1.4.3

**Comment by pmfx** [comment]
Maybe call it cached `[[DocLister]]` instead of `[!DocLister!]` and remove `,total, currentPage,totalPages,stop,start,pages` from tvList.

**Comment by user83743** [comment]
thanks Piotr.
unfortunately that makes no difference and we tried it and it does not work. the old ditto didn't have an "include " statement like that:

&amp;tvList=`product-price,page-right-aligned-image1`

and with this new one you can add what you like to it , it still works:

&amp;tvList=`product-price,page-right-aligned-image1,xxxxxxxxxxxx,yyyyyyyyyyyy,zzzzzzzzzzz`

=====================

there placeholders are just now working:

Showing [+doclister55.start+] - [+doclister55.stop+] of [+doclister55.total+] Products | Page [+doclister55.currentPage+] of [+doclister55.totalPages+]

any ideas @dmi3yy ? :)  .sorry for the callout, but we're keen to get one site converted to doclister and formlister and the other new snippets and see if we're happy with that - and disable the old snippets too.

======================
also:

the old ditto had a filter where you could make ditto ignore some documents e.g.

&filter=`id,115,2|id,120,2|id,101,2|id,78,2|id,124,2`

anyone know if the new doclister  "&filters" can do that . been all over the docs and no examples or mentions of it. you can include documents with    "   &amp;documents=`87,125,126,70`  "   but you can't exclude docs which is an equally desirable feature.

**Comment by user83743** [comment]
thnaks again Piotr, you have it. once small typo (for everyone else's benefit):

&amp;filters=`AND(content:c.id:notin:115,120,101,78,124)`  is the one that works to exclude that list of 5 document IDs.

**Comment by user83743** [comment]
cheers Piotr. i'll stick with github, even those the purists wouldn't like too many questions arriving in 'github' :)

**Comment by user83743** [comment]
UPDATE ON THIS question:

Piotr, helped us with the new undocumented syntax for filtering out documents from DOCLIST, but we still have no pagination numbering working as follows:

[!DocLister? &id=doclister55 &parents=<?php echo $id55 ?> &orderBy=menuindex DESC, createdon DESC &tpl=blog-story-summary-shop2 &display=9 &paginate = 1 &paginateAlwaysShowLinks=1 &tvList=product-price,page-right-aligned-image1 !]

and the resources are returned and displayed correctly but we have no pagination counters using:

Showing [+doclister55.start+] - [+doclister55.stop+] of [+doclister55.total+] Products | Page [+doclister55.currentPage+] of [+doclister55.totalPages+]

but the pagination numbering does work though:

 [+previous+] [+doclister55.pages+] [+next+]   
 
any ideas? it's EVO 1.4.3                 @dmi3yy

**Comment by pmfx** [comment]
Is there a good reason why your snippet call is not cached? Try [[ ]]

**Comment by user83743** [comment]
in a live or test scenario there is only one good reason to use cached [[ ]] snippet - when we know the values won't change. here we're trying to get something working for the first time, i'd rather use uncached [! !] so that we're ruling out an issue because of caching.  does that make sense?

**Comment by pmfx** [comment]
Better call it cached. If the values of resource change (resource is saved in backend), cache is always cleared. Also your configuration should have something like this:

![obraz](https://user-images.githubusercontent.com/10888055/38795680-4afa48ac-4159-11e8-8532-e033ffbd25f0.png)

Does missing pagination placeholders shows up when snippet call is cached?

**Comment by user83743** [comment]
thanks for the suggestion. I changed the caching settings as above and no
luck. cleared the cache too........and the placeholders have still no
data.  but the [+doclister55.totalPages+]   one does have data now. the
others do not:

Showing  [+doclister55.start+]  -  [+doclister55.stop+]  of
[+doclister55.total+] [+tv.total+]   Products | Page
[+doclister55.currentPage+]  of [+doclister55.totalPages+]

and the numbering still works:

 [+previous+] [+doclister55.pages+] [+next+]

**Comment by pmfx** [comment]
I'm not sure if there are "start, stop, total" placeholders available in DL pagination.
There is "isstart, isstop":

![obraz](https://user-images.githubusercontent.com/10888055/38796920-31f8087c-415d-11e8-93a1-99cb3d6110de.png)

**Comment by user83743** [comment]
thanks Piotr. yes, i saw those but regular "pagination" needs "start, stop, total" so we all presumed that doclister was going to replace ditto and reproduce those start, stop, total" and not discard them. so, we have no regular pagination in the new doclister?

**Comment by modxuser** [comment]
@user83743 

Did you get the problem with "start, stop, total" sorted ?

I am looking to update one of my major sites with Doclister, but if it doesn't do everything Ditto can, I will hold back a while longer - it supposedly does everything, so I was a little shocked when I read your last post

**Comment by user83743** [comment]
Hi. no, doclister does not appear to be a replacement for ditto. it does now have the placeholders you need - those two in particular :"start , stop" and "isstop and isstart" do not work in any useful way. do you know if ditto will be supported for the next while i.e. year plus? there are no useful docs on doclister and the examples are minimal. the syntax of doclister is completely different to ditto and if it wasn't for @pmfx i would not have even made the body of the doclister work/. all these new, detailed snippets need serious examples and docs. the current docs are not enough.

**Comment by modxuser** [comment]
That doesnt sound good, according to @dmi3yy it can do everything that Ditto does

Maybe @dmi3yy can help out on this

The lack of real world examples and tutorials is one of the reasons I havent updated yet

It took me two full working weeks to get my head around FormLister and I bet I still dont know half of it, I added tutorials & explanatory text at the same time to the docs site, at least for all of the code I used

Thats what I also wanted to do with DocLister, but, if it doesnt do what Ditto can, I see a problem for many users of Ditto, at least in the long term

Ditto is supposedly being supported for security, but not (so far as I know) further developed

**Comment by user83743** [comment]
I LOOKED AT DOCS FOR FORMLISTER TOO AND IT'S SIMILARLY LACKING IN EXAMPLES , so i left it too. SAME FOR dlmenu . i just hope ditto, eform and wayfinder are going to be monitored and updated if required. chances are they won't if they're not the main focus and independent coders are responsible for updating them. i asked about this in a ticket a while back and was assured that all core old snippets would be updated but , we'll see.

i'm fine with no new updates to ditto, wayfinder and eform! i don't want an new features to be honest. i just want them to be secure for a year plus so that doclister, formlister and dlmenu can get to a place, with examples, so that we can use them. we're not programmers and you would need to dedicate a week to go through those large and complicated docs; and still see only a few minimal examples.

**Comment by modxuser** [comment]
As mentioned, FormLister tutorials are now available and can be [found here](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/)

**Comment by user83743** [comment]
thanks @modxuser - i'll try that again when i get some time - http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/

**Comment by dmi3yy** [comment]
I have nice idea for build site with most popular solution. But need some time for this 

I think it’s help for understand how work with new solutions;). Like doclister dlmenu formlister usersettings simplegallery pagebilder

**Comment by user83743** [comment]
thanks for update @dmi3yy . we just need a wise head :) to 'break down' the huge syntax into the basics. maybe doclister does have 'start , stop' placeholders - i don't know. the above developers and us - we can't see it. if there were more examples then that would help. good luck with the work - looking forward to seeing it.
