### ISSUE TITLE
Restrict User to access/edit only one document and its children

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#636]
I need to give others access to my instance of EVO CMS. However, I have to prevent that they edit the main documents (pages). They should have their own document (and its children) to add their content and to edit.

Is that possible?

I could not find such an option in the setup of new users.

**Comment by pmfx** [comment]
Yes, it is definitely possible with User Groups (Users -> Manager Permissions).

**Comment by pmfx** [comment]
This should be helpful http://www.evolution-docs.com/documentation/administration/admin-users/admin-roles-and-groups Check "Document Groups" section there,

**Comment by q2apro** [comment]
Seems that EVO sets: 

> All Resource Groups (Public)

as default for each document...

That means, that you have to go over *all protected documents* and set the access permission to "Admin" (this group you have to create).

Why isn't the default "only admin" and then you create a new user group and assign it to the documents that they can access?!

**Comment by bossloper** [comment]
... correct, that is the way it is. There are no permission restrictions by default.

**Comment by q2apro** [comment]
Wouldn't make it sense "by logic" to do it the other way around?

**Comment by pmfx** [comment]
@q2apro I like it public by default.
Use Doc Manager module, to quickly update permissions of many resources.

![obraz](https://user-images.githubusercontent.com/10888055/38812851-b58a68ee-418d-11e8-8bbd-4a98fe65a9cd.png)

**Comment by qcol** [comment]
I asked similiar question here:
https://forums.modx.com/thread/103799/web-user-vs-manager-user-not-documented-well

The rights in evo are incredibly complicated, and I also think that by default access to all documents should be **disabled** - this is the case in all systems I know (it is anyway more logical and secure).
Only in the next step should the Administrator consciously turn on the access to particular users.

**Comment by pmfx** [comment]
I completely disagree. 

EVO permissions are extremely easy to understand and use. At least when compared to Revolution.

Why do you think access to all documents should be disabled by default? Sorry but it doesn't make sense and no system I know do that. Resources/Users Groups and Permissions are additional feature used when project needs it therefore all documents are public on both ends by default.

If you want to restrict Manager resources to Admins only, make sure they are, before creating non-admin users. At least root resources. You should be able to easily perform bulk actions using Doc Manager module. Simple as that.

**Comment by bossloper** [comment]
I agree with @pmfx on this, particularly where Revo permissions are concerned :-)

If you want to lock down all resources to admins:
1) Under Manager access permissions: Create a 'user group' (e.g. admins_only) and 'resource group' (e.g. admins_only_resource) then link them together.
2) Give your admin manager(s) that 'user group' e.g. admins_only permission.
3) In Doc Manager (Doc Permissions tab) select the doc group, in the range set 0** and submit. All resources will now be locked down... assuming no other permissions applied.

@pmfx - one thing that might help is to rename references for the manager 'user groups' to 'manager user groups'? It has always been slightly confusing that throughout Modx/Evo, Frontend users are 'Web users' but historically backend managers are just 'users'... would be more explicit if everywhere as 'manager users'.... as we now have on the top dropdown menu.

**Comment by pmfx** [comment]
@bossloper yes, I agree. "User groups" should be "Manager user groups" etc.

**Comment by q2apro** [comment]
Is there any way to hide the protected documents from the restricted user group?

Now they still show up:

![image](https://user-images.githubusercontent.com/6764548/72152353-61ba8e00-33b3-11ea-89d5-1f60a9e11dca.png)
