### ISSUE TITLE
Enhancement - Replace gender column on web users

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#638]
Gender column on 'Web User' page could be replaced by something more useful.
E.g. 'Last login Date and IP address'?
![untitled](https://user-images.githubusercontent.com/1744687/38799084-5487b268-415b-11e8-9597-266671adba70.png)

**Comment by pmfx** [comment]
Good idea. No point at all to show gender there.
I vote for **Last login** and **Number of logins**

**Comment by pmfx** [comment]
Similar thing on Manager USer view.
