### ISSUE TITLE
Popup calendar not usable on phone

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#642]
The popup calendar is not completely visible on a phone (Android or iPhone) and so dates cannot be entered on some fields e.g. publish date / unpublish date.
![screenshot_20180417-201504](https://user-images.githubusercontent.com/1744687/38891578-b3a2d062-427c-11e8-9489-c26a290ebf74.png)

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/38898100-20aea710-429d-11e8-9f09-c43a688b51e6.png)

**Comment by bossloper** [comment]
OK, so you need to make sure the field being selected is near the top of the screen. Does that mean the position logic is not quite right for the popup. It should automatically popup below if it does not fit above?

**Comment by 64j** [comment]
No. It always appears from the bottom.
And if I use templateEdit2, then top.

![image](https://user-images.githubusercontent.com/4653189/38899880-08368928-42a2-11e8-8c4c-faee87edabfb.png)
