### ISSUE TITLE
TinyMCE4 editor missing on phone?

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#643]
The TinyMCE4 editor does not seem to display on a phone? Android or iOS11.
TinyMCE4 works as expected on desktop.
TinyMCE3 does still work as expected on phone.

![screenshot_20180417-211342](https://user-images.githubusercontent.com/1744687/38894223-82779b6e-4284-11e8-9fda-a537a7ea478f.png)

**Comment by Deesen** [comment]
Hmm does it help when you remove these lines?

https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.base.inc.php#L97-L101

**Comment by Deesen** [comment]
Seems we need to use remote-debugging to see what the console has to offer: https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

**Comment by bossloper** [comment]
Just checking first :-) ... it is not just me that sees the issue?

**Comment by Deesen** [comment]
Remote-debugging is niiiiice :-)... So, it seems some files are missing like

- https://github.com/tinymce/tinymce-dist/blob/master/skins/lightgray/content.mobile.min.css
- https://github.com/tinymce/tinymce-dist/blob/master/skins/lightgray/skin.mobile.min.css
- https://github.com/tinymce/tinymce-dist/blob/master/skins/lightgray/fonts/tinymce-mobile.woff

But even after adding those files TinyMCE does not work correct for me on Android. It gets initiated but I see no buttons and cannot use it. Hmmm...

**Comment by Deesen** [comment]
But the none-mobile version works for me on Android when removing these lines:

https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.base.inc.php#L97-L101

**Comment by bossloper** [comment]
Agreed. Removing the lines you suggest works for me too.

**Comment by Deesen** [comment]
I guess I solved it, with the latest commit mobile-mode should work now too.

**Comment by Deesen** [comment]
I guess we need a setting like "Apply Mobile-Mode Yes/No" .. but where to add it? In plugin-settings or in Evo-settings? In Evo-settings this mode could be set separately per user.

**Comment by Deesen** [comment]
The point is that TinyMCE has a feature where it automatically switches to mobile-theme on mobile-devices. This mobile-theme does not cover all the buttons we are used to in the default-theme. So when deactivating mobile-mode, even on mobile-devices the default-theme with all buttons can be used again.

https://go.tinymce.com/blog/tinymce-is-going-mobile/

**Comment by Deesen** [comment]
Mobile-theme right now looks like:

![tinymce-mobile](https://user-images.githubusercontent.com/8569221/38920454-9694bfd6-42f3-11e8-8cb4-c4db9957062e.png)

Buttons are set here https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.base.inc.php#L100

**Comment by pmfx** [comment]
Oh, I see. Maybe we should have two new system settings then? One for enabling mobile theme and the other for mobile toolbar?
Or... mobile theme always enabled (no setting) and just setting for mobile toolbar options.

**Comment by Deesen** [comment]
I am not sure if everbody prefers to use the mobile-mode. So maybe even a third setting "plugins" to give freedom of choice ;-) ?

**Comment by bossloper** [comment]
Some sort of toggle is needed. I just checked on an iPad Air 2 and it displays the mobile view. This size screen is more than capable of using the full editor toolbar.

**Comment by Deesen** [comment]
"Live-toogle" is not possible I guess.

**Comment by bossloper** [comment]
Then maybe another 'Editor to use' in the dropdown 'TinyMCE4 Mobile'?

**Comment by bossloper** [comment]
So technically this is fixed, but having the mobile TinyMCE4 only on a tablet device seems wrong to me? So leaving open...

**Comment by Deesen** [comment]
I´m not sure how to solve this issue elegantly, except via user-settings. The selection in "Editor to use"-dropdown is not remembered so for each resource to edit, users need to set "TinyMCE4 Mobile" again.

**Comment by bossloper** [comment]
"users need to set "TinyMCE4 Mobile" again."
- that might be ok... maybe? A mobile edit would probably be an 'on the move' emergency, it would for me anyway! The thought of making a large number of edits on a phone does not appeal!

**Comment by bossloper** [comment]
Any further thoughts? At the very least we definitely need an option somewhere to disable mobile-mode as it is not easy/possible to undo that setting from the Plugin custom parameters field.

**Comment by bossloper** [comment]
Yes, sounds like a good solution to me.

**Comment by Deesen** [comment]
Or maybe a global "mobile/desktop" button, like an icon in the main navbar? So this global setting can be used also by other components like the resource-tree or whatever.

**Comment by bossloper** [comment]
Might be an option too far? :-) It is only needed for 'none dynamic' situations like this, I would have thought most other components will base on screen size and be able to respond dynamically?

**Comment by 64j** [comment]
@bossloper 
Is it decided?

![image](https://user-images.githubusercontent.com/4653189/43735227-cc720912-99c2-11e8-8382-94fcf8b2849c.png)

**Comment by bossloper** [comment]
@64j - not sure it is yet. As an earlier comment:

we definitely need an option somewhere to disable mobile-mode as it is not easy/possible to undo that setting from the Plugin custom parameters field.

Bottom line - On iPad I need the option of a 'normal editor', not a the cut down 'mobile' version.

**Comment by bossloper** [comment]
Generally maybe, but an iPad is more than capable of editing web pages, which several of my clients do use. The old MODX provided a full TinyMCE editor and was easily usable to edit resources.  We are now in the state that iPad editing is severely limited with the mobile editor.
