### ISSUE TITLE
entities like &#9650; only display as &

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#644]
Hello,

Just having a play with a Modx Evolution 1.2.1 site converted to EvolutionCMS 1.4.3. 

EvolutionCMS 1.4.3. is beautiful. Nice and fast and very slick.
The auto update is super, as is the warning about updating Ditto, Wayfinder, eForm, MultiTV etc.
Well done all.

Wondering if someone can please point me in the right direction.

These 3 arrows (I believe called decimal HTML entities) used in back to top and pagination are not displayed properly for me in 1.4.3:
```&#9650;```
```&#9658;```
```&#9668;```

In the front end / page source these show just as "&" and break the layouts:
```&```

They work fine in 1.2.1 and I am unsure what the difference is.

Not sure if this is relevant, but UTF-8 is configured like so:
In: Tools > Configuration = Character encoding [(modx_charset)] - Unicode (UTF-8) - utf-8
In: template head =  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
In: htaccess file = AddDefaultCharset utf-8

Is there a setting I should change somewehere? Any suggestions?

Many thanks.

**Comment by modxuser** [comment]
Do you have the setting "Minify php code in site cache" enabled, as seen in the image

![minify](https://user-images.githubusercontent.com/1859868/38915016-54fb0ed8-42e2-11e8-8620-cab0b84f38d6.png)

If its enabled, disable it.

**Comment by nick0** [comment]
Good call, thanks @modxuser. Disabling Minify fixed all three entities. Cheers!

Hopefully that bug will be fixed - you should still be able to minify arrow entities.

Thanks again.

**Comment by Pathologic** [comment]
#552 related
