### ISSUE TITLE
line spacing in the eForm Email Report not preserved

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#645]
Hello,

Just having a play with a Modx Evolution 1.2.1 site converted to EvolutionCMS 1.4.3.

I updated eForm to 1.4.9 through the Extras module based on the notice on the dashboard.

The form works fine, and the info is emailed through. But now the line spacing in the eForm email Report is not preserved. The report comes through as one long line that wraps like so:
`Name:Nick Company: Phone: Email: Mailing Address:eefefef wwdwd wd Options:Archived Posts, Test 4, Test 9 Vertical Checkboxes:General Enquiry, Other_ tst other vert ch Vertical Checkboxes 2:Option 3 Floating Checkboxes:Option 2 `

With eForm 1.4.8 in Modx Evolution 1.2.1, the exact same report has new items on a new line, as per the html report setup, and the same email report appears like so:
```Name:Nick
Company: 
Phone:
Email: 
Mailing Address:eefefef wwdwd wd
Options:Archived Posts, Test 4, Test 9 
Vertical Checkboxes:General Enquiry, Other_ tst other vert ch 
Vertical Checkboxes 2:Option 3 
Floating Checkboxes:Option 2 
```

I tried using html tags in report but they just come through as the tags themselves, there was no difference to line breaks in the email reports.

Any ideas on what I can do to fix?

Many thanks.

ps its important to me that I get eForm / Ditto / Wayfinder etc working as per 1.2.1 before I look to changing to the new EvolutionCMS equivalent.

**Comment by fourroses666** [comment]
I don’t have that space issue. Many sites are updated. Maybe maybe its configuration > site > minify which is set to on?

**Comment by nick0** [comment]
Backwards compatability is my first focus in this test cloning @modxuser. Once sorted, will then try a clone with changeover to the new snippets - if I find the inspiration and for reasons discussed ad nauseum :)

Good tip @fourroses666 - that was indeed the reason. Turning off Minify, fixed the reports. Many thanks.

Great to have Minify - not in email reports though, that is too much.

Pity it doesn't ignore non-html page source stuff. Surely it ony needs to generate frontend page source code??

Thank to you both.

**Comment by bossloper** [comment]
I must add, any time I tried 'configuration > site > minify' it broke something. My feeling it the algorithm to minify is to crude to use in the real world.

**Comment by fourroses666** [comment]
I also noticed issues when its set to on. I minify it myself.

**Comment by nick0** [comment]
Ah right, thanks for the heads up @bossloper. I will keep minify off until I hear it gets better or for testing bug fixes.

Thanks @fourroses666. Good call. I usually use Cloudflare which does a good job minifying. However I like the idea of doing it via Evo - it just needs to get a bit better / less buggy.

**Comment by Pathologic** [comment]
#552
