### ISSUE TITLE
ManagerManager - how to rename "Template Variables" and "Access Permissions" tabs

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#646]
Hello,

1. In ManagerManager, how do I rename the "Template Variables" and the "Access Permissions" tabs?

![untitled-1](https://user-images.githubusercontent.com/1768308/38922446-54477c38-4337-11e8-8526-bda7b35751a7.jpg)

Using this line actually changes the name of the Template Variables tab - not the Access Permissions tab
`mm_renameTab('access',` 'Permissions');`

In Configuration > Group TV = Sections in new tab 

I want to call
Template Variables - Variables
and
Access Permissions - Permissions

2. Is there a trick in ManagerManager to sorting the TV categories when "Configuration > Group TV = Sections in new tab"? 

It would be nice to have the categories (sub headings) sort alphabetically to match the way it does in Elements > Template Variables. For me it seems kind of randomly sorted, with uncategorised at the top

Thanks.

**Comment by nick0** [comment]
Thanks @pmfx - what a nice feature! Being able to sort and edit categories is super. Love it.

The category values all seem to default at 0 - then on moving one category, (and possibly with saving, I can't remember), they are then numbered sequentially. 

It would be nice if alphabetical dictated the default sort number.
And if you could also sort the category "uncategorised" - that always seems to start at the top of the category list when editing pages, so it must also sort at 0.

That's number 2 sorted, thanks.

How about number 1 - renaming Template Variables and Access Permissions tabs in ManagerManager? Anyone know how to do that?

Thanks.

**Comment by 64j** [comment]
@nick0 

https://github.com/64j/templatesEdit2

**Comment by nick0** [comment]
Thanks @64j. I am not sure what to do with that, all the instructions are in Russian. 
Does that do the job of Manager Manager?

**Comment by 64j** [comment]
@nick0 
https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=ru&ie=UTF8&prev=_t&rurl=translate.google.ru&sl=ru&sp=nmt4&tl=en&u=https://github.com/64j/templatesEdit2&xid=17259,15700023,15700043,15700124,15700149,15700168,15700173,15700186,15700195,15700201&usg=ALkJrhh6KXSUdHjf7W-jXvU_yqu23Tl5hw

**Comment by nick0** [comment]
Thanks @64j. I can read it now but I am still not sure what to do with that :).
Will skip this if it can't be done with Manager Manager as it looks quite complex to change 2 words.

Regardless I think there is a bug if Configuration > Group TV = "Sections in new tab". 
When using this line in Manager Manager...
mm_renameTab('access', 'Permissions');`
The name of the Template Variables tab - not the Access Permissions tab - actually changes

**Comment by 64j** [comment]
@nick0 
So MM does not change the level of access

**Comment by nick0** [comment]
@64j . Sorry, not sure what you mean by that.

**Comment by 64j** [comment]
@nick0 
MM just assigns the property "display: none"
And any manager can see what is being hidden from him.
And in templatesEdit2 if you close access, then you will not look at all.

**Comment by nick0** [comment]
thanks @64j
