### ISSUE TITLE
WAYFINDER --> DLMENU

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#649]
WAYFINDER --> DLMENU

Hi

does anyone have some good examples of how dlmenu is a replacement for wayfinder?

**Comment by fourroses666** [comment]
```
[[DLMenu?
&orderBy=`menuindex ASC`
&hideSubMenus=`1`
&parents=`0`
&maxDepth=`1`
&outerTpl=`@CODE:<ul>[+wrap+]</ul>`
&rowTpl=`@CODE:<li[+classes+]><a href="[+url+]">[+title+]</a></li>`
]]
```

**Comment by user83743** [comment]
thanks @fourroses666 . 

where we normally use  [!Wayfinder?startId=`0`     &amp;outerClass=``      &amp;titleOfLinks=``  &amp;level=`3`    !]   and put that directly into our own menubar systems to produce mobile friendly menubars, can I do the same with a simpler call like:

[[DLMenu?
&orderBy=`menuindex ASC`
&parents=`0`
&maxDepth=`3`
]]

??

to produce a 'clean' 

<ul>
<li>...........</li>
<li>...........</li>
...........
</ul>

with no required classes or IDs inside the <ul>............</ul> . we don't have the skills (or time/money to outsource) to custom build every menu so we do the above in some simple-website cases.

where are all these DLMENU parameters listed and explained? is there a set of docs?

thnaks in advance for your help.

**Comment by fourroses666** [comment]
http://docs.evo.im/en/04_extras/dlmenu.html

Placeholders on the bottom.
I have never worked with titleOfLinks and don't know what it shows.
Maybe [+title+] can be used, something like this?

`&rowTpl=`@CODE:<li class="[+classnames+] [+title+]"><a href="[+url+]">[+title+]</a></li>``

**Comment by user83743** [comment]
if i remember correctly, titleOfLinks = `` prevented little windows browser 'tip' bubbles appearing over all the menubar elements. useless feature and had to be set to empty 11.

thnaks again.

we'll experiment with 

[[DLMenu?
&orderBy=menuindex ASC
&parents=0
&maxDepth=3
]]

and see if that works in a few test sites

**Comment by fourroses666** [comment]
Then you can remove the title out of the row tpl code

**Comment by user83743** [comment]
but that call is not using any tpl code:

[[DLMenu?
&orderBy=menuindex ASC
&parents=0
&maxDepth=3
]]

it will just produce, if it works like wayfinder, a piece of html like:

<u l > 
< l i > .......... < / l i>
< l i > ...........< / l i>
</ u l >

**Comment by user83743** [comment]
thanks @64j @fourroses666 . much appreciated.

we have code that works now :)

a direct replacement for us for:

 [!Wayfinder?startId=`0`     &amp;outerClass=``      &amp;titleOfLinks=``  &amp;level=`3`    !]

is

 [!DLMenu?   &amp;orderBy=menuindex ASC     &amp;parents=`0`     &amp;maxDepth=`3`    !]

**Comment by 64j** [comment]
@user83743 
http://docs.evo.im/en/04_extras/dlmenu.html

**Comment by user83743** [comment]
@64j 
this is where they docs were supposed to be http://www.evolution-docs.com/extras/ and nothing on dlmenu

**Comment by 64j** [comment]
@user83743 
All docs http://docs.evo.im/en/
And what is there evolution-docs.com, ask @modxuser
