### ISSUE TITLE
[(valid_hostnames)] cannot be removed on EVO 1.4.2

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#650]
evo 1.4.2

configuration-->'security' tab.

it is not possible to remove the value in [(valid_hostnames)] and press save. it just keeps reappearing. i checked was it in the "modx_system_settings" table but it isn't. so i can't delete it there. i searched in the siteCache.idx.php file and it's not in there either. i have obviously pressed the clear cache a few times. any ideas? thanks

**Comment by bossloper** [comment]
I see same issue with 1.4.3
Hostnames were stored in siteHostnames.php but maybe not anymore? Something is not quite right.

**Comment by 64j** [comment]
check file siteHostnames.php

**Comment by user83743** [comment]
sorry @64j - where is that?

**Comment by user83743** [comment]
that used to be /assets/cache/   but it's not there in 1.4.2

**Comment by user83743** [comment]
that just says:

<?php
define('MODX_SITE_HOSTNAMES', '');

what do we do with that?

**Comment by user83743** [comment]
<?php
define('MODX_SITE_HOSTNAMES', '');

**Comment by user83743** [comment]
that just says:

<? ph p
defin e('MODX_ SITE_HOSTNAMES', '' )

**Comment by user83743** [comment]
that just says:

< ? ph p
defin e('MOD X_ SI TE_HOST NAMES', '' )

**Comment by 64j** [comment]
@user83743 
The field with the domain name is filled in again if you open the configuration.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/39056178-a32cc500-44be-11e8-8d23-f62fd72baa78.png)

**Comment by bossloper** [comment]
Whenever I have a value showing in siteHostnames.php if I edit the site configuration then 'valid hostnames' is blank. 
If I then save the system configuration when 'valid hostnames' is blank then next time I open the config the value is showing... but now the value in siteHostnames.php is empty!
I can repeat that cycle. It seam the hostname value is either showing in siteHostnames.php or the interface system config field but not both at the same time.

php5.6

**Comment by bossloper** [comment]
can be closed...
