### ISSUE TITLE
Suggestion for manager login page

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#652]
I suggest somewhere on the new manager login page it should display the website title as text?
I realise you can override the logo but not all sites have a logo or would warrant the effort to create an image to replace the default Evolution image.

**Comment by pmfx** [comment]
Honestly I don't see a need for that. I've always used a company logo or a default EVO logo and nobody have ever asked about a website title on the login page.

**Comment by bossloper** [comment]
But with only the default logo there is no obvious indication of the website you are logging into.... compared to how it was before.

**Comment by pmfx** [comment]
Isn't browser address bar and tab title not enough to indicate it?

**Comment by modxuser** [comment]
I agree with @bossloper for a different reason though - security

You can change the manager folder name, but if someone does per-chance find the renamed folder in use by accident, they then see the Evo logo

I for one strip the login form completely of everything, other than the bits needed to login - the result is a plain login form, no logo, no indication of Evo / MODX etc. but it has the website name

**Comment by bossloper** [comment]
It is possible to write a small plugin to add the title to the manager login page:
```
$e = &$modx->Event;
switch($e->name){
	case 'OnManagerLoginFormPrerender':
	$output = '
          <div class="form-group">
            <a href="../">'.$modx->config['site_name'].'</a>
          </div>
	';
	$e->output($output);
	break;	
}
```
... so if it is really not wanted on the default install then it can be added.  Though I still think it should be there by default :-)

**Comment by bossloper** [comment]
Closing this as it can be resolved with a plugin.
