### ISSUE TITLE
Container Field

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#655]
Looking to simplify where possible, so looking at the 'Container' field.
It is no longer auto checked if you create a child resource (it was in ModX) so does it have a use or can it be removed from the interface?

![untitled](https://user-images.githubusercontent.com/1744687/39359806-65ca7ce8-4a13-11e8-967c-a497d935ece5.png)

**Comment by 64j** [comment]
In no case.
For example, you need to create empty folder documents.

**Comment by bossloper** [comment]
I see it is still auto checked if you place a child resource in a parent. I was using global tabs so it had not updated my parent resource window.
But my question stands. If you can still place a resource in a parent when it is not set as a container and it then auto-checks the container field for the parent then what is the value of the container field, I do not see a use for it? What is the functional value in creating an 'empty folder document' vs just an 'empty document'?

**Comment by 64j** [comment]
@bossloper 
```sql
SELECT * FROM site_content WHERE isfolder=1
```

**Comment by bossloper** [comment]
@64j - ok I see what you are saying. 
Though to me it seems to be a setting used by the system but not something the manager needs to alter as it auto-checks when children are added.
If it could auto-uncheck when there were no children then I do not see it needs to be visible on the manager interface?

**Comment by bossloper** [comment]
more important issues, closing...
