### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#657]
if you have a template and you have an image TV attached to that template and it is correctly  populated with an image - how do you make the EVO edit-resource page display the image thumbnail, for reference? it's disabled on a few EVO 1.4.3 sites and I don't know what plugin or snippet will re-enable those thumbnails. any ideas?

**Comment by pmfx** [comment]
Does ManagerManager plugin exist and is enabled?

**Comment by user83743** [comment]
well done Piotr. i saw your suggestion and thought "mm". we had disabled
managemanager. sorry for that! it's working now. much appreciated again.

have you come across the fact that the images in "kcfinder" are quite
blurred?

**Comment by bossloper** [comment]
@user83743  You can increase the thumbnail image size for kcfinder in the manager configuration.
Under 'File browser' tab. 'Max thumbnail width' and 'max thumbnail height'. It is only 150 by default.
You will probably need to clear out the assets/.thumbs folder to regenerate existing image thumbnails.

**Comment by pmfx** [comment]
Check your system settings. There are two that defines generated thumbnails size:
![screenshot_1](https://user-images.githubusercontent.com/10888055/39396207-3e021612-4aea-11e8-9c26-decb3c99a70d.png)
Maybe change it to 250x250.

**Comment by user83743** [comment]
thnaks Piotr. that makes the thumbnail window big - if it set it to e.g.
400px x 400px. and then i uploaded a new image to test it and it created a
clearer image but those thumbnails are huge. so i turned it back to 200px x
200px. thnaks for your help

**Comment by user83743** [comment]
thanks Mr B !!!
