### ISSUE TITLE
multiTV add, remove icon not showing

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#659]
multiTV add, remove icon not showing , 
because of manager/media/style/default/css/custom.css 
{
.multitv .list li.element a.copy,
.multitv .list li.element a.remove {

  background: transparent !important;

}

![download 2](https://user-images.githubusercontent.com/9032715/39409890-6342f146-4c14-11e8-8d01-bfea0582919c.png)
![download 3](https://user-images.githubusercontent.com/9032715/39409904-7fbb976a-4c14-11e8-8ac8-bf3685696e0e.png)

**Comment by pmfx** [comment]
You should upgrade MultiTV to the latest version. Icon images were replaced by font icons some time ago.
https://github.com/extras-evolution/multiTV

**Comment by pmfx** [comment]
https://github.com/extras-evolution/multiTV/archive/master.zip

**Comment by mgzawlinoo** [comment]
thank you

**Comment by fourroses666** [comment]
These buttons don’t always respond that good, sometimes have to click it multiple times to add one. Also not always clear for clients who use it for the first time (my experience). Maybe we need to make them al little bigger some pixels and maybe some restyling css. Heared some complaining too when using a pen as mouse. Don’t know exactly whats wrong. Maybe its the drag on no display block/inline block. Maybe we can look into that?

**Comment by pmfx** [comment]
Sure, improvements are always welcome, but lets post ideas in the correct repo 
https://github.com/extras-evolution/multiTV
