### ISSUE TITLE
Игнорируется капча при входе в админку

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#66]
В настройках выставлено показывание капчи при входе в админку. 
Обновился на двух сайтах до версии 1.3.0 и 1.3.1. 
При переходе на страницу /manager/ капча показывается, но ее значение игнорируется и вход в админку просходит, даже если капча введена не правильно.

**Comment by atomoc** [comment]
Не пользуйтесь вы admin логином и каптчей кодом и будет вам лучше прежнего :)

**Comment by Dreamer0x01** [comment]
Не понял замечания. Что, в админку теперь вообще не заходить?

**Comment by dmi3yy** [comment]
Ну да зачем админка что там делать :) 
там видать проверка на мутулсе была а мы его выпилили )

**Comment by atomoc** [comment]
@Dreamer0x01 Создаёте пользователя с именем, которое боту будет сложно узнать и не нужен будет код ;) Пусть себе ломится по admin, на 3 разе его заблокирует, а твой пользователь будет активен пока его не сможет подобрать бот, но даже когда он это сделает, получится так же как и с admin - блокировка, которую легко разблокирует человек с доступом по фтп ;)

**Comment by dmi3yy** [comment]
@atomoc зачем ftp ?  просто кнопку нажать забыли пароль можно и прийдет письмо в почту :) 
никогда не понимал зачем усложнять 

а капча работала значит и должна работать что логично ) поправим

**Comment by Dreamer0x01** [comment]
А как по ftp блокировку снять? Я обычно через базу данных снимаю...

**Comment by Dreamer0x01** [comment]
>  просто кнопку нажать забыли пароль можно и прийдет письмо в почту
Обычно плагин ForgotManagerLogin на всякий случай удаляю...

**Comment by dmi3yy** [comment]
ага заходим по ftp смотрим доступ к базе если что льем adminer лезем в базу и там снимаем 
но смысла нет если у пользователя указана ваша почта

**Comment by dmi3yy** [comment]
ЗАчем его удалять ? баг с дырой был в нем пару лет назад его закрыли и все работает стабильно и удобно и клиентам проще они любят пароли забывать)

**Comment by Dreamer0x01** [comment]
> баг с дырой был в нем пару лет назад его закрыли и все работает стабильно

Видимо, я это пропустил - с тех пор и удаляю по привычке.
