### ISSUE TITLE
DocLister Query (from Ditto user) - dynamic id for &parents

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#660]
Hello,

I am just having a play with DocLister (looking at converting some Ditto calls in a demo 1.4.3 site).

In Ditto I like using a dynamic id (rather than a fixed resource id eg 33) like so:
```
[[Ditto? 
	&id=`content[*id*]` 
	&startID=`[*id*]` 
	&depth=`0` 
	&outerTpl=`content-menu-wrapper` 
	&tpl=`content-menu-row` 
	&tplLast=`content-menu-row-last` 
	&noResults=` ` 
	&orderBy=`menuindex ASC`
]]
```

How do I achieve the same in DocLister? 

I am trying the following but not getting any results and presume I have something wrong in my call relating to the id parameter.
```
[!DocLister?
	&id=`content[*id*]`
	&idType=`parents`
	&parents=`[*id*]`
	&ownerTPL=`content-menu-wrapper`
	&tpl=`content-menu-row`
	&tplLast=`content-menu-row-last` 
	&noneTPL=`content-menu-NO`
	&noneWrapOuter=`content-menu-NO-wrapper`
	&orderBy=`menuindex ASC`
!]
```

Thanks for any help

**Comment by Pathologic** [comment]
&debug parameter will help to find out what's wrong.

**Comment by nick0** [comment]
Ok thanks. 
I tried debug but not sure what I was looking for. 
Results were returned that looked like it should be working. 
[*id*] seemed to work as the right docs were returned,
Anyway, I removed all templates and put them in one by one.
My mistake was with the wrapper (ownerTPL??) template - I was using [+wrapper+] from the ditto call, when I changed that to [+dl.wrap+] it worked fine.

I think for easier changeover from Ditto to DocLister it would be nice if 

- [+wrapper+] would work as an alias for [+dl.wrap+] in DocLister's outer wrapper (ownerTPL) templates
- if "outerTpl" could be used as an alias for "ownerTPL" in DocLister calls

Then more things would probably just work straight away.

ClipperCMS did something like this for when using Ditto instead of the updated List and it made the transition much easier.

**Comment by nick0** [comment]
In a 1.4.3 EvolutionsCMS site with DocLister 2.3.14, I cannot seem to get the noneWrapOuter parameter working.

Say for example in this DocLister call...
```
[!DocLister?
	&id=`ef[*id*]`
	&idType=`parents`
	&parents=`131`
	&ownerTPL=`emailform-menu-wrapper`
	&tpl=`emailform-menu-row`
	&noneTPL=`emailform-menu-NO`
	&noneWrapOuter=`emailform-menu-NO-wrapper`
	&orderBy=`pagetitle ASC`
	&filters=`AND(content:hidemenu:eq:0)`
!]
```

When there are no results, the ownerTPL chunk "emailform-menu-wrapper" is always used - the noneWrapOuter "emailform-menu-NO-wrapper" chunk is never used.

Is there a trick needed to get noneWrapOuter working?

Thanks.

**Comment by Pathologic** [comment]
noneWrapOuter's values are 0 or 1, not the template - there's an error in docs.

**Comment by nick0** [comment]
Ah great, thanks for advising. Got it thanks @Pathologic.

If anyone is interested, to output blank results in DocLister if empty I am using:
```
&noneTPL=`@CODE `
&noneWrapOuter=`0`
```
