### ISSUE TITLE
broken dashboard when new user logs in

### ISSUE THREAD

**Issue by qcol** [evolution-cms/evolution#661]
just created new user, added role with permissions to edit, save, publish page but when log in and use quick edit or go to manager, everythink is broken (no css? no content?)

![zaznaczenie_135](https://user-images.githubusercontent.com/358993/39417192-d6667c7c-4c52-11e8-8b35-680033c4b73a.png)
![zaznaczenie_134](https://user-images.githubusercontent.com/358993/39417193-d6ad0c46-4c52-11e8-882f-25ab895959f4.png)

**Comment by bossloper** [comment]
If this is 1.4.3 then it looks like that manager is using an old theme? Have you checked the manager 'user' tab and 'manager theme' setting?
![untitled](https://user-images.githubusercontent.com/1744687/39419046-b7b50c14-4c55-11e8-9f2f-ab6a53fc30a1.png)

**Comment by qcol** [comment]
Yes, indeed... It was empty, but then I switched it to MODxLight and still was broken.. now i switched it do default and now it's OK
By the way... "Allowed Days" works completely the opposite way... when not checked, user can login, when checked - user can;t login this day... should it not be the other way round? :)

**Comment by bossloper** [comment]
@qcol - You might want to check the system wide 'system configuration' ->'interface and features' 'manager theme'... if that is not default then it should be. Then any manager theme override can be left blank to pick up the system wide setting.

I think allowed days is correct, if no days selected then it assumes all allowed as there is no sense in having a manager that cannot login on any day.

**Comment by qcol** [comment]
@bossloper but when I checked all days (As I understand - all allowed), I couldn't login with error "you can;t login this time"... when unchecked all days - I can login... so, it looks illogical in my opinion.

**Comment by bossloper** [comment]
@qcol - it is a bug. I have submitted a fix: https://github.com/evolution-cms/evolution/pull/662

**Comment by qcol** [comment]
@bossloper thanks!
