### ISSUE TITLE
DLMenu help for Wayfinder conversion: scrolling achor menu

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#665]
Hello,

I have an anchor menu in Wayfinder that looks like this:
```
[[Wayfinder?
    &startId=`[[UltimateParent]]`
    &level=`3`
    &ignoreHidden=`true`
    &textOfLinks=`menutitle`
    &titleOfLinks=`pagetitle`
    &firstClass=`first`
    &hideSubMenus=`true`
    &displayStart=`true`
    &startItemTpl=`anchor-menu-starter`
    &outerTpl=`anchor-menu-wrapper`
    &rowTpl=`anchor-menu-row
`]]
```
This produces 3 items as expected:
Page 1
* Sub 1 (which has show in menu unchecked)
* Sub 2 (which has show in menu unchecked)

I am trying to convert this to DLMenu but am only getting one result back and need a little help from an experienced user.

My new equivalent DLMenu call looks like so:
```
[!DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&maxDepth=`3`
	&hideSubMenus=`0`
	&showParent=`1`
	&parentRowTpl=`@CODE:<p class="h2"><a href="#anchorTop" title="[+pagetitle+]">[+title+]</a></p>[+wrap+]`
	&outerTpl=`@CODE:<ul>[+wrap+]</ul>`
	&rowTpl=`@CODE:<li[+classes+]><a href="#anchor[+id+]" title="[+pagetitle+]">[+title+]</a></li>`
	&orderBy=`menuindex ASC`
!]
```

This produces 1 item only - I don't get the sub pages, and the starting item is a list item, not a paragraph item as specified in the &parentRowTpl:
*Page 1

I have looked at the docs at docs.evo.im but am totally stuck.

Any ideas?

Thanks in advance.

**Comment by Pathologic** [comment]
```&addWhereList=``
```

**Comment by nick0** [comment]
Thanks @Pathologic. I have no idea what that actually does but it works - adding that one extra line gets the menu working like the wayfinder version. Many thanks.

Here is the finished DLMenu call for anyone who is interested,
```
[!DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&addWhereList=``
	&maxDepth=`3`
	&hideSubMenus=`0`
	&showParent=`1`
	&parentRowTpl=`@CODE:<p class="h2"><a href="#anchorTop" title="[+pagetitle+]">[+title+]</a></p>[+wrap+]`
	&outerTpl=`@CODE:<ul>[+wrap+]</ul>`
	&rowTpl=`@CODE:<li[+classes+]><a href="#anchor[+id+]" title="[+pagetitle+]">[+title+]</a></li>`
	&orderBy=`menuindex ASC`
!]
```

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/snippet.DLMenu.php#L5

**Comment by nick0** [comment]
In DLMenu docs I can't seem to find the parameter needed to show only resources which have show in menu checked (eg don't show resources with show in menu unchecked). 
Any ideas?
Thanks.

**Comment by Pathologic** [comment]
As it's DocLister based, you can use &addWhereList or &filters.

**Comment by nick0** [comment]
Ah ok. This is interesting.

So to include items that have show in menu unchecked I use:
```
&addWhereList=``
```
And to exclude items that have show in menu unchecked I simply exclude that line.

Its not intuitive but works :).

Can you please show me the filter call equivalent @Pathologic just so I can see how that would work? 
A fliter call that excludes items with show in menu unchecked would be great.
Looking in the docs I don't really understand how they work compare to ditto filters which seemed a bit more straight forward.

Thanks.

**Comment by nick0** [comment]
ps the filter docs on this page, with ENG selected, are half in Russian: 
http://docs.evo.im/en/04_extras/doclister/filters.html

**Comment by nick0** [comment]
This might be the filter?? It seems to work. Does it look right?
`
&filters=`AND(content:hidemenu:eq:0)
`

**Comment by nick0** [comment]
Sorry for all the questions. Lots to learn with these new snippets :)

**Comment by 64j** [comment]
link_attributes

**Comment by nick0** [comment]
Yes! That got it working Thanks Serg.
```
<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a></li>
```

**Comment by nick0** [comment]
I have a link to an external website as a sub page in a section of the site I am playing with. Relevant settings...
Weblink = https://www.google.com/
Link Attributes = target="blank"
Resource Type = Weblink
Internet/Media Type = text/html
Content Disposition = Inline

With the DLMenu sub menu active, the whole parent / child section in the front end goes blank (just a white page with nothing at all in the page source). Adding debug to the DLMenu call also does not fix it, the page just loads as the white page.

If I remove that external web link from that section, the page loads and the sub menu works as expected,

Is there a trick to getting external weblink resources working in a DLMenu?

Thanks

**Comment by Pathologic** [comment]
Update DocLister and add &disablePHx=`1` to your snippet call.

**Comment by nick0** [comment]
Thanks Pathologic. I tried Doclister 2.3.15 but that throws a 503 error on every page of the site so having to revert back to DocLister 2.3.14 for now.

(I downloaded the EvoCMS develop zip, then renamed the Doclister 2.3.14 folder in the assets/snippets folder, then uploaded the Doclister 2.3.15 folder and copied in the DocLister.tpl install info into the DocLister snippet in the Manager)

**Comment by Pathologic** [comment]
I've tried it on several sites (PHP 5.6/7) without any problems.

**Comment by nick0** [comment]
Hmmm, wierd one then. 
It doesn't work any differently for me - 2.3.15 still throws the blank page when I activate the external link resource (happens on the sitemap and also the sub menu).
I am using php 7.
Puzzling.

**Comment by Pathologic** [comment]
See error.log on server or ask your provider to enable it if it's disabled

**Comment by nick0** [comment]
Good tip, thanks.

There seem to be 2 errors...
```
[02-May-2018 11:06:33 Australia/Sydney] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /home/the-username/public_html/assets/snippets/DocLister/lib/DLphx.class.php on line 171
```
and
```
2018-05-04 16:33:57.125386 [INFO] [58.178.224.12:52894:HTTP2-81] File not found [/home/the-username/public_html/503.shtml] 
```
Can you make sense of that?
Thanks for your help.

**Comment by nick0** [comment]
Hmmm...

I just ran the entire install process on the develop branch and only installed DocLister 2.3.15. 

It still throws a blank page for me as soon as I activate the external link and visit that section of the site (eg demos (which is the parent resource that has the external link as a child)
.
It does not throw an error when not in that section of the sites (eg about us) - the site looks as normal then.

So it seems whenever I am in the parent or child section that has the external link, the blank page is thrown. Otherwise it works.

Tricky.

**Comment by Pathologic** [comment]
See error.log

-------- Исходное сообщение --------
От: nick0 <notifications@github.com> 
Дата: 05.05.2018  4:52  (GMT+03:00) 
Кому: evolution-cms/evolution <evolution@noreply.github.com> 
Копия: Pathologic <m@xim.name>, Mention <mention@noreply.github.com> 
Тема: Re: [evolution-cms/evolution] DLMenu help for Wayfinder conversion:
&nbsp; scrolling achor menu (#665) 

Hmmm...
I just ran the entire install process on the develop branch and only installed DocLister 2.3.15.
It still throws a blank page for me as soon as I activate the external link and visit that section of the site (eg demos (which is the parent resource that has the external link as a child)

.

It does not throw an error when not in that section of the sites (eg about us) - the site looks as normal then.
So it seems whenever I am in the parent or child section that has the external link, the blank page is thrown. Otherwise it works.
Tricky.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/evolution-cms/evolution","title":"evolution-cms/evolution","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/evolution-cms/evolution"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nick0 in #665: Hmmm...\r\n\r\nI just ran the entire install process on the develop branch and only installed DocLister 2.3.15. \r\n\r\nIt still throws a blank page for me as soon as I activate the external link and visit that section of the site (eg demos (which is the parent resource that has the external link as a child)\r\n.\r\nIt does not throw an error when not in that section of the sites (eg about us) - the site looks as normal then.\r\n\r\nSo it seems whenever I am in the parent or child section that has the external link, the blank page is thrown. Otherwise it works.\r\n\r\nTricky."}],"action":{"name":"View Issue","url":"https://github.com/evolution-cms/evolution/issues/665#issuecomment-386771260"}}}

**Comment by fourroses666** [comment]
Whats your evo and php version, maybe < 5.6?

**Comment by nick0** [comment]
Thanks @fourroses666...
Evo = 1.4.3
PHP = 7.0.30 (tried it as 7.1 and also as 5.6, still get the blank white page when in that section of the site)
Database Version = 10.1.32-MariaDB (I can't change that)

Using this call with templates in chunks its a blank white page still:
```
[[DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&disablePHx=`1`
	&maxDepth=`3`
	&hideSubMenus=`1`
	&showParent=`1`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&parentRowTpl=`sub-menu-starter`
	&outerTpl=`sub-menu-wrapper`
	&rowTpl=`sub-menu-row`
	&categoryFolderTpl=`sub-menu-category`
	&orderBy=`menuindex ASC`
	&filters=`AND(
		content:c.hidemenu:is:0
	)`
]]

sub-menu-starter = 
<p class="h2"><a href="[+url+]" title="[+pagetitle+]">[+title+]</a></p>
[+wrap+]

sub-menu-wrapper = 
<ul>
 [+wrap+]
</ul>

sub-menu-category = 
<li[+classes+]>[+title+]
[+wrap+]</li>

sub-menu-row = 
<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a>
[+wrap+]</li>

```

Using this call with templates and @code calls its also a blank white page still:
```
[[DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&disablePHx=`1`
	&maxDepth=`3`
	&hideSubMenus=`1`
	&showParent=`1`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&parentRowTpl=`@CODE <p class="h2"><a href="[+url+]" title="[+pagetitle+]">[+title+]</a></p>[+wrap+]`
	&outerTpl=`@CODE <ul>[+wrap+]</ul>`
	&rowTpl=`@CODE <li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a>[+wrap+]</li>`
	&categoryFolderTpl=`@CODE <li[+classes+]>[+title+][+wrap+]</li>`
	&orderBy=`menuindex ASC`
	&filters=`AND(
		content:c.hidemenu:is:0
	)`
]]
```

The error types are the same per further above...
```
[02-May-2018 10:41:30 Australia/Sydney] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /home/the-username/public_html/assets/snippets/DocLister/lib/DLphx.class.php on line 171

2018-05-07 12:38:06.699245 [INFO] [58.178.224.12:58876:HTTP2-33] File not found [/home/the-username/public_html/404.shtml] 
```

I am stuck.

**Comment by fourroses666** [comment]
allowed memory size is the issue but I don’t know how to solve it.

**Comment by nick0** [comment]
Ah ok thanks Marc.

Just checked the cpanel. wonder what I might need to change?
memory limit is 256M.

If anything stands out from the screen cap, please let me know:
![untitled-1](https://user-images.githubusercontent.com/1768308/39728818-f94054de-5297-11e8-901a-155acc404b99.jpg)

Otherwise I might have to put this on hold until the 1.4.4 is released.

Thanks for your help.

**Comment by nick0** [comment]
The external link works for me in Evo 1.4.4 with DocLister 2.3.15 and &disablePHx=1 in the DLMenu call. Thanks
