### ISSUE TITLE
Suggestion for small screens

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#671]
On a small screen i.e. mobile (<480px?) it could be better to stack the label and field to make more usable.
E.g. instead of:
![screen2](https://user-images.githubusercontent.com/1744687/39541286-2effa0ca-4e3d-11e8-8a21-7a6ee9037427.png)
Have something like this:
![screen1](https://user-images.githubusercontent.com/1744687/39541294-3719caec-4e3d-11e8-98af-82e282d4c900.png)

**Comment by dmi3yy** [comment]
yes but need change html and then change  mamager manager rules for that but  this better way

**Comment by pmfx** [comment]
#676
