### ISSUE TITLE
Random DocLister and DLMenu Questions

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#674]
Hello,

I have been working through converting Ditto to DocLister and Wayfinder to DLMenu and have some random questions. Would appreciate the assistance of an experienced user.

1. In Ditto there is a very handy filter that allows us to exclude the current document from the results:
```
&filter=`id,[*id*],2`
```
What is the DocLister equivalent of this filter?

2. In Ditto I can use a randomize parameter to randomize the order:
```
&randomize=`1` 
```
What is the DocLister euivalent of this parameter?

3. In DocLister I have managed to get pagination working aok in my testing (displaying 2 items to a page, 3 pages in total). But when I add the pagination code to my DocLister call, the month in the row template changes from English to Russian.
eg
```
October 12, 2017 becomes Октябрь 12, 2017
September 6, 2017 becomes Сентябрь 6, 2017
```
The date call used in the row template is:
```
[+pub_date:date=`%B %e, %Y`+]
```
The parameters I am using for the pagination is as follows:
```
	&paginate=`pages`
	&PrevNextAlwaysShow=`1`
	&TplWrapPaginate=`dl-pagination`
	&TplPage=`dl-pagination-page`
	&TplCurrentPage=`dl-pagination-current`
	&TplNextP=`dl-pagination-next`
	&TplNextI=`dl-pagination-nextOff`
	&TplPrevP=`dl-pagination-prev`
	&TplPrevI=`dl-pagination-prevOff`
```
Relevant chunk code is as follows:
```
	&TplWrapPaginate=`<div class="paging"><ul>[+wrap+]</ul></div>`
	&TplPage=`<li><a href="[+link+]"><b>[+num+]</b></a></li>`
	&TplCurrentPage=`<li><span class="current"><b>[+num+]</b></span></li>`
	&TplNextP=`<li><a href="[+link+]" class="next" title="next"><b>&#9658;</b></a></li>`
	&TplNextI=`<li><span class="next off"><b>&#9658;</b></span></li>`
	&TplPrevP=`<li><a href="[+link+]" class="prev" title="previous"><b>&#9668;</b></a></li>`
	&TplPrevI=`<li><span class="prev off"><b>&#9668;</b></span></li>`
```
How do I keep the dates in English when I use pagination in DocLister?

4. I have a main menu with drop downs using DLMrenu. 

The top level links are meant to have a span around them. This works fine for top level resources that don't have children. 

However, the links for all top level resources that have children are not wrapped in the spans for some reason.

I changed the innerRowTpl code to see if top level links with children get served that template - but they do not so I guess that is good but does not help.

This is my DLMenu call
```
[!DLMenu?
	&id=`menu[*id*]`
	&parents=`0`
	&maxDepth=`2`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&outerTpl=`<ul>[+wrap+]</ul>`
	&rowTpl=`<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]><span>[+title+]</span></a>[+id:is=`14`:then=`{{main-menu-mega}}`:else=`[+wrap+]`+]</li>`
	&innerTpl=`<div class="drop"><ul>[+wrap+]</ul></div>`
	&innerRowTpl=`<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a></li>`
	&orderBy=`menuindex ASC`
	&filters=`AND(content:hidemenu:is:0;content:id:isnot:1;content:id:isnot:4;content:id:isnot:5;content:id:isnot:6;content:id:isnot:7;content:id:isnot:8)`
!]
```
I want all top level links in this menu (whether children or not) to be wrapped in span tags per the code for the rowTpl.

Any ideas?

Thanks in advance for any help

**Comment by Pathologic** [comment]
http://www.evolution-docs.com/extras/doclister/filters

**Comment by nick0** [comment]
Hi @Pathologic, 

I have been looking through both of the docs sites for days. I do not have the answers which is why I posted here. There is nothing in the docs that answers my specific queries 1,2,3 or 4.

There is no forum and not many users that probably know all of the parameters because I don't think they are all documented.

If you don't help us - and when I say us I mean non technical, non developer users of Evolution - we won't be able to help other users with these kinds of questions.

I am trying to embrace and test DocLister and DLMenu but I need some help to specific queries. If you want long term Modx Ditto and Wayfinder users to start using Evolution DocLister and DLMenu please help us.

The questions might seem trivial to technical users but for myself and other users it means being stuck and unable to replace Ditto and Wayfinder without resolving these kinds of queries.

Do any other DocLister and DLMenu know these answers?

Greatly appreciate any specific help.

**Comment by nick0** [comment]
I have a new one...
5. Is it possible to streamline this DocLister filter call (specifically, combining the 7 x templates into one and the 4 x ids into another)?
```
&filters=`AND(
content:template:isnot:6;content:template:isnot:8;content:template:isnot:11;content:template:isnot:24;content:template:isnot:25;content:template:isnot:26;content:template:isnot:27;
content:id:is:6;content:id:is:7;content:id:is:8;content:id:is:88)`
```
If so, please show me how - then I will know.
Greatly appreciate any help.
Thanks.

**Comment by nick0** [comment]
For 3, the month turning to Russian with pagination on, adding this to the DocLister call did not have any effect:
```
&locale=`english`
```
Is that how you meant to use that @Pathologic ?

**Comment by autogen-travel** [comment]
&filters=`AND(content:template:notin:(6,8,11,24,25,26,27);content:id:in(6,7,8,88))`

**Comment by Pathologic** [comment]
I do not understand how you are reading the docs. The whole "filter" chapter is devoted to filters in DocLister, it's enough to build simple filter like content:id:isnot:[*id*] or content:template:notin:1,2,3,4,5:
![image](https://user-images.githubusercontent.com/3012304/39606740-9ca56d5a-4f3f-11e8-8c81-53d511747147.png)

Question 2:
![image](https://user-images.githubusercontent.com/3012304/39606771-c53ff42e-4f3f-11e8-8aa0-d490b6d6d89a.png)

Question 3 needs investigation.

Question 4 - all template parameters are described in docs, maybe you need parentRowTpl or set rowTpl/parentRowTpl for the first level only as rowTpl0 or parentRowTpl0:
![image](https://user-images.githubusercontent.com/3012304/39606860-420269a6-4f40-11e8-8cfd-7176a025d7b7.png)

Why do I spend time to write docs if nobody read them?

**Comment by Pathologic** [comment]
Locale is locale http://php.net/manual/en/function.setlocale.php: en_US or en_US.utf8.

**Comment by nick0** [comment]
Thanks @autogen-travel, very much appreciated.
Now I know how to streamline and combine - without your code example I would not have known how to do it so thank you very much.
This is the code that worked in my situation for number 5:
```
content:c.template:notin:6,8,11,24,25,26,27;
content:c.id:notin:6,7,8,88
```

**Comment by nick0** [comment]
Thanks Pathologic, I didn't know about that seting - I got it working for Australia in the DocLister call like so:
```
&locale=`en_AU`
```
But it definitely seems to be a bug - the language should not change just because pagination is used.
Thank you. 3 is solved with your trick.

**Comment by nick0** [comment]
Thank you @Pathologic. I read the docs and appreciate the time you and @modxuser have put in there but in fairness to non technical users a lot of reading between the lines is required. You are presuming that everyone learns the same way. I learn by seeing working examples and playing with them and then by adding and removing parameters. There really are not many examples in the docs so it hard for my learning style and as a non technical user.

For example for the filter parameter that you showed an image for (that is not an example by the way, it is simply stating the parameter and a very brief description) in and notin - how about adding an inline example so non technical users can see the usage?
eg 
content:template:notin:6,8,11,24,25,26,27 
and
content:id:in:6,8,11

I really do appreciate your help.

**Comment by nick0** [comment]
Thanks @Pathologic for showing me that screencap.
I totally missed that in the docs (I got scared off by the preceding info relating to SQL).

Number 2 is resolved. This is how to randomise the order in DocLister:
```
&orderBy=`rand()`
```
Thanks!

**Comment by nick0** [comment]
Thanks @Pathologic, that really helped me 
I did not realise there was a parentRowTpl (this is all new to me).
Adding that in has solved the issue.

This is the code I used in case anyone interested:
```
&parentRowTpl=`<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]><span>[+title+]</span></a>[+id:is=`14`:then=`{{main-menu-mega}}`:else=`[+wrap+]`+]</li>`
&rowTpl=`<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]><span>[+title+]</span></a></li>`
```

Number 4 is resolved.
Thank you kindly.

**Comment by Pathologic** [comment]
Locale issue is fixed in https://github.com/AgelxNash/DocLister/commit/2f027aa0f331183f144a5b49c49d74e2920e74f9

**Comment by nick0** [comment]
Thanks @Pathologic. 1 is now resolved to.
I tried that call myself the day before but it always threw an error - its why I asked for help.
I had to change it to "c.id" per below:
```
content:c.id:isnot:[*id*];
```
I am not sure why we need the c. sometimes and not others but all good.
Thank you for your help with these questions.

**Comment by nick0** [comment]
Sure thing, understood re the error messages.
Ok thanks for confirming that, have added c. to all relevant content filters.
Thanks.

**Comment by nick0** [comment]
6 Is there a DocLister pagination page count feature?
In Ditto I could use this to exclude the pagination if the count was less than or equal to 2
```
[+repeater_totalPages:el=`1`:then=``:else=`<div class="pager">
 <ul>
  [+wrap+]
 </ul>
</div>`+]
```
I tried these without luck
[+repeater_total:elt=`1`:then=`...`+]
[+repeater_iteration:elt=`1`:then=`...`+]
[+iteration:elt=`1`:then=`...`+]
```
I think I am missing something

**Comment by nick0** [comment]
7 is there an "outer" equivalent in the new modifiers?
```
<?php
/*
* description: surround not empty string with text
* usage: [+string:outer=`before|after`+]
*/
 
$options = explode("|", $options);
if (count($options) == 1) {
    $options[1] = '';
}
if (trim($output) != '') {
    return $options[0].$output.$options[1];
} else {
    return '';
}
;
```
I am looking to upgrade a Ditto call to DocLister that is used inside a MultiTV call - the DocLister call currently looks like so...
[+phx:input=`
{{files-mtv}}
`:outer=`
<a name="anchor[+id+]"></a>
<h2><a href="[~[+id+]~]" title="[+pagetitle+]">[+title+]</a></h2>
`+]
If I get rid of "phx:" in the first line above nothing is output.
Any ideas?
Thanks.

**Comment by Pathologic** [comment]
I haven't used phx for several years. There's initial support, but in general it's deprecated as good guys are using twig 😀

**Comment by Pathologic** [comment]
Pagination is hidden by default if it contains only one page.

**Comment by Pathologic** [comment]
Pagination is hidden by default if it contains only one page.

**Comment by nick0** [comment]
> Pagination is hidden by default if it contains only one page.

G E N I U S !
Thanks, that is awesome :)
6 is resolved because of awesome programming!

> I haven't used phx for several years. There's initial support, but in general it's deprecated as good guys are using twig

Hehe. Ah ok. Maybe it will be fine as is as I read somewhere that MultiTV has its own in built PHx. The PHx plugin is disabled anyway. But the phx:outer call still seems to work. Was just wondering if the new modifiers have an equivalent but may not be required.

Many thanks.
