### ISSUE TITLE
Random FormLister Questions

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#675]
Hello,

I have been playing with FormLister and have some random questions. Would appreciate the assistance of an experienced user.

1. Is there a parameter equivalent to autosenderReplyTo? 

This would be the email of the website (specified in the FormLister call. In my case I would always match that to the TO address, or alternatively I would use noreply@ the domain of the site).

These are my auto sending parameters:
```
&automessageTpl=`contact-form-autoresponder`
&autoSubject=`Automatic Response to Your Enquiry`
&autosender=`[+email.value+]`
&autosenderFromName=`[(site_name)]`
```

In using 
```
&autosender=`[+email.value+]`
```
I am using the email address of the person who submitted the form (entered when the form is submitted). However this also becomes the from email address of the Auto Reply which doesn't seem quite right.

2.  Is it possible to use modifiers in the FormLister reports? 

So that only fields that have been filled and their Labels get included in the reports.
Eg
If company field has content, this is returned...
```
Company: ABC Pty Ltd
```
If company field has NO content, this is returned at the moment...
```
Company: 
```
Would be nice to do something like this in the reports...
```
[+company:is=``:then=``:else=`Company: [+company.value+]`*]
```
At the moment the full modifier line above is returned as is so it doesn't seem to work but I thought worth asking the experts.

Thanks in advance for any help.

**Comment by modxuser** [comment]
@nick0 

If you get this sorted, could you knock-up a short tutorial ? I can then add it to those I made :)

Only if you have the time that is :)

@Pathologic is your best bet to answering your questions ref. FormLister, he was a great help when I started using it.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/050_Mail_Sending.md#automailconfig
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/050_Mail_Sending.md#parsemailerparams

**Comment by nick0** [comment]
Sure thing @modxuser, if I get them sorted.
I think we should add checkboxes and radio buttons to your super helpful examples.

Again thanks for the links @Pathologic. I looked at the links but I do not know what to do with that info or how to set it up or how that affects my queries. I am a non technical user, non programmer, and need a little bit of help with these specific queries.

Greatly appreciate any specific help.

Thanks.

**Comment by Pathologic** [comment]
You should enable parseMailerParams to get &autosender=\`[+email.value+]\` working. But I don't know how to explain autoMailConfig parameter simpler than it's already explained.

**Comment by nick0** [comment]
parseMailerParams=1 in my email form so I think is enabled.

I think there is a misunderstanding.

the autosender=[+email.value+] is actually working.

But on replying to the auto response email, the reply is sent to the email address (eg john@test.com) that the auto response email was sent to (eg john@test.com) - so replying to it involves emailing yourself (eg from john@test.com replies to john@test.com - rather than to a email address of the website (such as noreply@domain.com).

I don't understand how to use autoMailConfig for this instance.

To me it seems like an new parameter is required eg autosenderReplyTo

**Comment by Pathologic** [comment]
Do you know what is json? This should work:
```
&autoMailConfig=`{
    "replyTo":"me@me.com"
}`
```

**Comment by Pathologic** [comment]
Sorry, but I'm tired of trying to guess what you are doing wrong.

**Comment by nick0** [comment]
anyone else that is experienced with FormLister and knows how to get "auto sender reply to" (not the send to - the reply to in case a user clicks reply on the auto message they received)?

presume query 2 in original post is not currently possible.

**Comment by modxuser** [comment]
@nick0 

I didnt know what json was until I used formlister the first time either

Take a look at the following:

```
[!FormLister?
&formid=`ContactForm`
&to=`name@domain.com`
&config=`default:core`
&isHtml=`0`
&protectSubmit=`1`
&rules=`{
"name":{
	"required":"Please enter your full name"
},
"message":{
	"required":"Please enter your message",
	"minLength":{
		"params":100,
		"message":"Your message must have at least 100 characters"
	}
}
}`
&allowedFields=`name,email,phone,subject,message`
```

I just copied the code from one of the tutorials I wrote: [Basic contact form V.1](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-v.1)

Look at the rules section - thats json

As such, I think  you simply add your element to the snippet and add the elements it needs

**Comment by nick0** [comment]
Thanks so much for the help @modxuser. I was using json without even knowing it :)

Actually, I tried that exact autoMailConfig line from @Pathologic in my FormLister call - but around the same time I also made the snippet call cached [[ ]] - the caching is what caused the form not to send for some reason, not the &autoMailConfig json data. So thank you @Pathologic.

Anyway... I tried again with the clear code and with the form uncached [! !], and with that it works fine. The &autoMailConfig from and replyto are both needed.

This is the auto sending code from the FormLister call
```
	&automessageTpl=`contact-form-autoresponder`
	&autoSubject=`Automatic Response to Your Enquiry`
	&autosender=`[+email.value+]`
	&autosenderFromName=`[(site_name)]`
	&autoMailConfig=`{
		"from": "[(emailsender)]",
		"replyTo": "[(emailsender)]"
	}`

NB - [(emailsender)] - in case anyone is not sure what that is - this is the email address specified in the E-mail address setting in the EvolutionCMS Configuration section under the Site tab - saves having to change the email address in the FormLister call for every site.
```

Thank you kindly for the help @modxuser and @Pathologic. We got there in the end :)

Number 1 is resolved.

@modxuser - here is a question for you: do you know why we would use both &rules and &allowedFields in the FormLister? It seems to work fine with only &rules. Is it just extra form protection to say exclude the antibot field for example?

Number 2 re Modifiers in the FormLister report is still of interest - is it possible?

**Comment by modxuser** [comment]
@nick0 

Sorry for the late answer, am extremely busy at the moment, new EU laws ref. privacy driving me crazy

**Ref. your question**

Rules are there to set conditions for the individual fields, if the condition isn't met, then the whole form fails, they are not the same as allowed fields

Allowed fields - I am not sure with this to be honest, @Pathologic told me as I was converting my calls that it may not even be needed in my forms - I think there should be a more detailed explanation to why its there and when it should be used - possibly for more complicated forms with callback etc.

Have no idea ref. modifiers - sorry

**Comment by Pathologic** [comment]
@modxuser The usage of allowed fields list makes sense mostly when saving data to database (or passing it somewhere). For example you create documents using pagetitle and content from form. But user can modify this form and send longtitle or descriptiption as well, so you can decline allowed (or forbidden) fields to avoid unwanted data to be processed. In case of sending forms by email all needed fields are placed in report template, so user cannot break it. I'm not sure, but it seems that allowedFields parameter is not used in Form controller at all :smile:

**Comment by nick0** [comment]
Thanks @modxuser and @Pathologic , good to know re allowedFields

No worries on the modifiers @modxuser - a programming guru may not if that is possible and how to do it.
