### ISSUE TITLE
Formlister - ModxCaptcha

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#677]
I get Error messages in Russian, but my language is German. I think, this is a bug.
Formlister > lib > captcha > modxCaptcha > wrapper.php line
line 83:
`$out = \APIhelpers::getkey($captcha->cfg, 'errorEmptyCode', 'Введите проверочный код');`

line 85-86:
`$out = strtolower($value) == strtolower($captcha->lastValue) ? true : \APIhelpers::getkey($captcha->cfg,
                'errorCodeFailed', 'Неверный проверочный код');`

**Comment by modxuser** [comment]
I have Formlister running in two German sites, bith use the german language files and both work without any problems

You must tell Formlister to use the German language files

I added a couple of tutorial to the docs site a while back:

[Using custom languages](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/custom-languages)

[Using MODXcaptcha](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-with-modxcaptcha)

**Comment by Pathologic** [comment]
It's not a bug, but maybe it's really worth to change this messages to lexicon entries. Create an issue in https://github.com/pathologic/formlister

**Comment by modxuser** [comment]
Just re-read this and see that I made a slight mistake, ref. pre-defining language

@Pathologic in reality this doesn't in my opinion need to be changed as the parameters can be set in the formlister call - this is shown in [the tutorial I made](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-with-modxcaptcha)

example from the tutorial:
```
&captcha=`modxCaptcha`
&captchaParams=`{
    "width":"148",
    "height":"60",
    "errorEmptyCode":"Captcha Code Missing",
    "errorCodeFailed":"Captcha Code is Incorrect"
}`
&captchaField=`captchacode`
```

So for the German language, it could be something like this:
```
&captcha=`modxCaptcha`
&captchaParams=`{
    "width":"148",
    "height":"60",
    "errorEmptyCode":"Bestätigungscode (captcha code)",
    "errorCodeFailed":"Bestätigungscode wurde falsch eingegeben"
}`
&captchaField=`captchacode`
```

**Comment by Pathologic** [comment]
That's right, but it will be tricky to change captcha messages for multilanguage sites.

**Comment by modxuser** [comment]
True, didnt think about that - but to be honest, I dont think it has been a problem to date, due to the fact that the new additional language files have only recently been added.

wouldn't a multi-language site be a problem for FormLister anyway, as you can only define one language, or am I missing something ?

**Comment by webkarli** [comment]
Hallo Pathologic,
thanks for answer. I tried and it works great.

**Comment by Pathologic** [comment]
You can use a wrapper to set language parameter, something like:
```
$params['lang'] = isset($_SESSION['lang']) ? $_SESSION['lang'] : $modx->config['manager_language'];

return $modx->runSnippet('FormLister', $params);
```
