### ISSUE TITLE
Widget for Dashboards (OnManagerWelcomeHome) - remove a default widget

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#68]
Should I be able to remove a widget yet, or is this still work in progress?

From a simplified version of the example code a plugin for the OnManagerWelcomeHome event:

$e = &$modx->Event;
switch($e->name){
    case 'OnManagerWelcomeHome':
        unset($widgets['security']);
    break;
}

But it does not remove the widget. Looking at the code here https://github.com/evolution-cms/evolution/blob/develop/manager/actions/welcome.static.php#L357 it is merging custom widgets, so as far as I can see the default ones will always be on the dashboard?

**Comment by dmi3yy** [comment]
i you use one plugin normal work unset($widgets['security']); but if use more then one better use 
```
$widgets['security']['hide']='1';
```

**Comment by bossloper** [comment]
I only have the default install, and so one plugin, but yes your solution works.... thanks.
Might be good to change the example help text for that.

**Comment by dmi3yy** [comment]
yes i change on pressreleases )

```php
$e = &$modx->Event;
switch($e->name){
    case 'OnManagerWelcomeHome':
        //if($_SESSION['mgrRole']!=='2') return;
                
        //$widgets['welcome']['hide']='1';
        //$widgets['onlineinfo']['hide']='1';
        //$widgets['recentinfo']['hide']='1';
        //$widgets['news']['hide']='1';
        //$widgets['security']['hide']='1';
                
        $widgets['test'] = array(
            'menuindex' =>'1',
            'id' => 'test',
            'cols' => 'col-sm-6',
            'icon' => 'fa-rss',
            'title' => 'test',
            'body' => '<div class="card-body">[+modx_news_content+]</div>',
            'hide'=>'0'
        );
        $e->output(serialize($widgets));
    break;
}
```

**Comment by Nicola1971** [comment]
why does not work for me?
```
$e = &$modx->Event;
switch($e->name){
    case 'OnManagerWelcomeHome':
        //if($_SESSION['mgrRole']!=='2') return;
                
      $widgets['welcome']['hide']='1';
      $widgets['onlineinfo']['hide']='1';
      $widgets['recentinfo']['hide']='1';
      $widgets['news']['hide']='1';
      $widgets['security']['hide']='1';

        $e->output(serialize($widgets));
    break;
}
```
event: OnManagerWelcomeHome

what i'm doing wrong?
all default widgets are still visible

evo v 1.3.1

**Comment by dmi3yy** [comment]
read plz this :)
https://github.com/evolution-cms/evolution/releases/tag/1.3.2
