### ISSUE TITLE
Ошибка при создании копии ресурса

### ISSUE THREAD

**Issue by AntonFix** [evolution-cms/evolution#681]
При копировании документа выдает ошибку:
`Warning: Cannot modify header information — headers already sent by (output started at ...//manager/includes/document.parser.class.inc.php:1054) in .../manager/processors/duplicate_content.processor.php on line 35`

**Comment by 64j** [comment]
Какая версия Ево ?
Версия php ?

**Comment by AntonFix** [comment]
Привет.
PHP 5.6, Modx Evo 1.4.3

**Comment by 64j** [comment]
@AntonFix 
На версии 1.4.4 это наблюдается?

**Comment by 64j** [comment]
Проверил, ошибки нет.
Evo 1.4.4, php 7.1.7
