### ISSUE TITLE
TV for an <img>

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#682]
Hi

when i use a TV like      "[*slideshow-image-1*]"

i get back:

"<img src="assets/images/slider-gg-11.jpg" alt="" />"

whereas , what I want is "assets/images/slider-gg-11.jpg". is there any way of doing that simply?

thanks

**Comment by pmfx** [comment]
Does your TV use output widget "Image"? If so, don't use TV widget if you need just a TV value.

![screenshot_1](https://user-images.githubusercontent.com/10888055/39955141-79caddc4-55ca-11e8-90be-d7fe5079df7d.png)

**Comment by user83743** [comment]
thanks Piotr! and thanks for quick reply
