### ISSUE TITLE
eform --> formlister

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#683]
Hi

been through http://www.evolution-docs.com/extras/formlister/mail-sending#formlistermailerparameters and there are no direct equivalents for :

[[eForm? &formid=`contactform1` &to=`info@xxxxxxx.com` &tpl=`contactform` &report=`contactformreport` &replyto=`email` &thankyou=`contactformthanks` &vericode=`1` &vericodecase=`0` &subject=`CONTACT FORM MESSAGE FROM YOUR WEBSITE`]]

and no explanations or docs to be found. any idea how this works to replace eform for a simple contact form, with some fields and a captcha?

Regards

Gerard

**Comment by pmfx** [comment]
Check http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/

**Comment by user83743** [comment]
thanks Piotr. we tried that page and demo before and it doesn't work. we have EVO 1.4.2 ON PHP7 AND EVERYTHING ELSE WORKS FINE. 

<?php
echo ""; ?>
[!FormLister?
&formid=`Test Contact Form`
&to=`xxxxxxxxxxx@gmail.com`
&config=`default:core`
&isHtml=`0`
&protectSubmit=`1`
&rules=`{
"name":{
    "required":"Please enter your full name"
},
"email":{
    "required":"Please enter your email",
    "email":"Please enter a valid email"
},
"phone":{
    "required":"Please enter your phone number",
    "phone":"Please enter a valid phone number",
    "minLength":{
        "params":5,
        "message":"Please enter a valid phone number"
    }
},
"subject":{
    "required":"Please enter your subject"
},
"message":{
    "required":"Please enter your message",
    "minLength":{
        "params":100,
        "message":"Your message must have at least 100 characters"
    }
}
}`
&allowedFields=`name,email,phone,subject,message`
&messagesTpl=`@CODE:<div><ul>[+required+][+errors+][+messages+]</ul></div>`
&messagesOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesRequiredOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesErrorOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesSplitter=`</li><li>`
&messagesRequiredSplitter=`</li><li>`
&messagesErrorSplitter=`</li><li>`
&errorClass=`error`
&requiredClass=`required`
&captcha=`modxCaptcha`
&captchaParams=`{
    "width":"148",
    "height":"60",
    "errorEmptyCode":"Captcha Code Missing",
    "errorCodeFailed":"Captcha Code is Incorrect"
}`
&captchaField=`captchacode`
&formTpl=`@CODE:
[+form.messages+]
<form action="[~[*id*]~]" method="post">
  <input type="hidden" name="formid" value="ContactForm">
  
  <div class="[+name.errorClass+][+name.requiredClass+]">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" placeholder="Name" value="[+name.value+]">
  </div>
  
  <div class="[+email.errorClass+][+email.requiredClass+]">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" placeholder="Email" value="[+email.value+]">
  </div>
  
  <div class="[+phone.errorClass+][+phone.requiredClass+]">
    <label for="phone">Phone</label>
    <input type="tel" name="phone" id="phone" placeholder="Only Enter Digits" value="[+phone.value+]">
  </div>
  
  <div class="[+subject.errorClass+][+subject.requiredClass+]">
    <label for="subject">Subject</label>
    <input type="text" name="subject" id="subject" placeholder="Subject" value="[+subject.value+]">
  </div>
  
  <div class="[+message.errorClass+][+message.requiredClass+]">
    <label for="message">Message</label>
    <textarea rows="10" name="message" id="message" placeholder="Type your message here">[+message.value+]</textarea>
  </div>
  
  <div class="[+captchacode.errorClass+][+captchacode.requiredClass+]">
    <label for="captchacode" class="compulsory">Captcha Code:</label>
    <img src="[+captcha+]" alt="Captcha Image"><br>
    <br>
    Enter Captcha Code here:<br>
    <br>
    <input type="text" name="captchacode" id="captchacode" value="">
  </div>
  
  <button type="submit">Submit</button>
</form>`
&successTpl=`@CODE:<div>Thank you, we will get back to you ASAP.</div>`
&reportTpl=`@CODE:<div>here is the form submission report</div>`
!]

**Comment by user83743** [comment]
how come the example on http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/all-in-one-form uses very different parameters?

**Comment by modxuser** [comment]
@user83743 

Just a "Heads up", all of the examples in the tutorials work - they have been tried and tested, the tutorials are the result of testing the forms - how do I know LOL I wrote the tutorials

The parameters are not indentical coming from eForm, thats the reason why they are partially different

If you want to use captcha, as I see you have vericode, you need to view the [MODXcaptcha tutorial](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-with-modxcaptcha)

**Comment by user83743** [comment]
Ok ;-) I ran that example and it didn't work at all. Do you have evo 1.4.2
and that code I pasted above works for you?

**Comment by user83743** [comment]
I would gladly run it with no captcha now to get it running. And I can add
captcha layer

**Comment by modxuser** [comment]
I cant copy and paste your code as its not complete due to github changing it

**Comment by modxuser** [comment]
is your code from [BASIC FORM V.1](http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/basic-contact-form-v.1)

**Comment by user83743** [comment]
Yes Piotr. I just changes the email and the report tpl code

**Comment by modxuser** [comment]
I am not piotr LOL can you email me ?

I can show you the form on two live sites running PHP7.x

**Comment by user83743** [comment]
Sorry modxusr.!! Can I cut n paste it into this email or will GitHub edit
that code too?

**Comment by modxuser** [comment]
If you have copied the code from the original tutorial it should work without any problems

let me know youe email and I will contact you now - I dont have much time, so the faster the better :)

**Comment by modxuser** [comment]
TEST:

```
[!FormLister?
&formid=`ContactForm`
&to=`xxxxxxxxxxx@gmail.com`
&config=`default:core`
&isHtml=`0`
&protectSubmit=`1`
&rules=`{
"name":{
    "required":"Please enter your full name"
},
"email":{
    "required":"Please enter your email",
    "email":"Please enter a valid email"
},
"phone":{
    "required":"Please enter your phone number",
    "phone":"Please enter a valid phone number",
    "minLength":{
        "params":5,
        "message":"Please enter a valid phone number"
    }
},
"subject":{
    "required":"Please enter your subject"
},
"message":{
    "required":"Please enter your message",
    "minLength":{
        "params":100,
        "message":"Your message must have at least 100 characters"
    }
}
}`
&allowedFields=`name,email,phone,subject,message`
&messagesTpl=`@CODE:<div><ul>[+required+][+errors+][+messages+]</ul></div>`
&messagesOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesRequiredOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesErrorOuterTpl=`@CODE:<li>[+messages+]</li>`
&messagesSplitter=`</li><li>`
&messagesRequiredSplitter=`</li><li>`
&messagesErrorSplitter=`</li><li>`
&errorClass=`error`
&requiredClass=`required`
&captcha=`modxCaptcha`
&captchaParams=`{
    "width":"148",
    "height":"60",
    "errorEmptyCode":"Captcha Code Missing",
    "errorCodeFailed":"Captcha Code is Incorrect"
}`
&captchaField=`captchacode`
&formTpl=`@CODE:
[+form.messages+]
<form action="[~[*id*]~]" method="post">
  <input type="hidden" name="formid" value="ContactForm">
  <!-- Name -->
  <div class="[+name.errorClass+][+name.requiredClass+]">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" placeholder="Name" value="[+name.value+]">
  </div>
  <!-- Email -->
  <div class="[+email.errorClass+][+email.requiredClass+]">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" placeholder="Email" value="[+email.value+]">
  </div>
  <!-- Phone Number -->
  <div class="[+phone.errorClass+][+phone.requiredClass+]">
    <label for="phone">Phone</label>
    <input type="tel" name="phone" id="phone" placeholder="Only Enter Digits" value="[+phone.value+]">
  </div>
  <!-- Subject -->
  <div class="[+subject.errorClass+][+subject.requiredClass+]">
    <label for="subject">Subject</label>
    <input type="text" name="subject" id="subject" placeholder="Subject" value="[+subject.value+]">
  </div>
  <!-- Message -->
  <div class="[+message.errorClass+][+message.requiredClass+]">
    <label for="message">Message</label>
    <textarea rows="10" name="message" id="message" placeholder="Type your message here">[+message.value+]</textarea>
  </div> 
  <!-- modxCaptcha -->
  <div class="[+captchacode.errorClass+][+captchacode.requiredClass+]">
    <label for="captchacode" class="compulsory">Captcha Code:</label>
    <img src="[+captcha+]" alt="Captcha Image"><br>
    <br>
    Enter Captcha Code here:<br>
    <br>
    <input type="text" name="captchacode" id="captchacode" value="">
  </div>
  <!-- Submit Button -->
  <button type="submit">Submit</button>
</form>`
&successTpl=`@CODE:<div>Thank you, we will get back to you ASAP.</div>`
&reportTpl=`@CODE:
<p>This is the information entered by <b>[+name.value+]</b> in the websites contact form.</p>
<p>The full details are as follows:</p>
 
<p>Name: [+name.value+]</p>
<p>Email: [+email.value+]</p>
<p>Phone: [+phone.value+]</p>
<p>Subject: [+subject.value+]</p>
<p>Message:<br>[+message.value+]</p>
 
<p>Send a Reply: <a href="mailto:[+email.value+]?subject=RE: [+subject.value+]">[+email.value+]</a></p>`
!]
```

**Comment by user83743** [comment]
Thanks. I'll try that when I get back to pc. Thanks for your help

**Comment by fourroses666** [comment]
(Maybe update Doclister) and did you try to install the demo? It has a basic form in it.

**Comment by modxuser** [comment]
That code works 100%, as it is currently being used on a live website

@fourroses666 the demo form didnt help me one bit when I started to converting all my calls

**Comment by user83743** [comment]
Your mean formlister? Or formlister uses doclister? I think I have all
modules up to date

**Comment by modxuser** [comment]
Fomlister is dependant on Doclister

**Comment by user83743** [comment]
Thanks fro your help

**Comment by user83743** [comment]
thanks

**Comment by modxuser** [comment]
@user83743 

Did you get the form working ?

**Comment by Pathologic** [comment]
closed due to lack of response
