### ISSUE TITLE
Multitv

### ISSUE THREAD

**Issue by ivan-smirnyagin-1** [evolution-cms/evolution#69]
Какой то баг с MultiTV
![2017-07-19_17-58-20](https://user-images.githubusercontent.com/24613445/28367866-e0db180c-6cab-11e7-8e15-918aecddb2a8.jpg)

**Comment by dmi3yy** [comment]
ага есть скоро доберусь

**Comment by ivan-smirnyagin-1** [comment]
Спасибо!

**Comment by dmi3yy** [comment]
готово новая версия 2.0.12 
https://github.com/extras-evolution/multiTV/commit/aac34d9d06b96a231773399b86951eda9b776bad

**Comment by Nicola1971** [comment]
I have the same issue but with **EVO 1.3.3** and **MultiTv 2.0.12**.
My issue is caused by a translated language string in italian language

> Uncaught ReferenceError: falso is not defined
    at index.php:931

line 60 
```$language['datepicker.isRTL'] = 'falso';```
should be not translated:
```$language['datepicker.isRTL'] = 'false';```
