### ISSUE TITLE
Latest dev - Upgrade issues

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#690]
Using latest dev I am having trouble upgrading.
It gets to the last screen and displays this (no style or design). Also if I then try to login the manager login does not let me in. It does not indicate wrong password it just reverts back to the login page after clicking login. If I install back to https://github.com/evolution-cms/evolution/commit/946f7f5de0de16fd6683de0decea23ff808d79df then it is fine.

php 5.6.36
Database: 5.5.5-10.1.33-MariaDB
Install is on a sub-domain in a sub-folder

![untitled](https://user-images.githubusercontent.com/1744687/40231404-f22b371a-5a92-11e8-9624-0c3f7611fe77.png)

**Comment by nick0** [comment]
> Also if I then try to login the manager login does not let me in. It does not indicate wrong password it just reverts back to the login page after clicking login.

I had the exact same issue last week. I had to go to a new browser to be able to login, where logging in did work. Then I cleared the cache in the manager and logged out, then restarted the original browser and logged in and things worked as expected.

**Comment by bossloper** [comment]
@Pathologic - think you need to look here: https://github.com/evolution-cms/evolution/blob/develop/install/instprocessor.php#L754

**Comment by bossloper** [comment]
Ref https://github.com/evolution-cms/evolution/commit/2950b760d717ed400453c3edf71a03a3dbaf4f07
