### ISSUE TITLE
DocLister question: use main content field and apply summary rule when introtext text exists

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#698]
Hello,

Just wondering if someone can please help me with how to use the DocLister summary parameter in a 1.4.3 site with DocLister 2.3.14.

How do I tell DocLister to use the content field and apply the notags,len:150 rules like in the call below when text also exists in the introtext field?
```
[[DocLister?
	...
	&summary=`notags,len:150`
	&introField=`content`
	&tvList=`image`
	...
]]
```

My row template looks like so...
```
[+content:is=``:then=``:else=`<p>[+summary+]</p>`+]
````

If I use this in the DocLister call...
```
&introField=`content`
```
...It uses the content field but absolutely all the content and the html from the main content field is returned, It does not follow the len:150 or the notags from the &summary parameter.

if I use this in the DocLister call...
```
&contentField=`content`
```
...the content from the introtext field is used which is not what I want.

When there is no text in the introtext field, "notags,len:150" is followed and the text is taken from the content field.

I am stuck and wondering how to apply the summary parameter to the content field when text also exists in the introtext field.

Many thanks in advance for any help

**Comment by AgelxNash** [comment]
```
&introField=``
&contentField=`content`
&tpl=`@CODE:[+summary+]`
```

**Comment by nick0** [comment]
Ahhhh I see, thanks @AgelxNash!

That works perfectly.

In the DocLister call...
```
	&summary=`notags,len:210`
	&introField=``
	&contentField=`content`
```

In the row template...
```
<p>[+summary+]</p>
```

Many thanks.
