### ISSUE TITLE
Adding badges to the READ.ME?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#70]
Maybe add badges on the READ.ME ?

Like: 
stable version / downloads / etc.
https://poser.pugx.org/

slack count

--

Also new animated gifs or video of the manager (image and clicking on it go to youtube or new evo.im)

We need to add how to install.
-> Uploading install.php and make a database. 
That also has to be explained on the evo.im website.

First things first offcourse but as soon as the new site and default manager style is launched we need to change the READ.ME

**Comment by dmi3yy** [comment]
its for packagist.org need found for GitHub ))

**Comment by dmi3yy** [comment]
add php version and last release version bage

**Comment by fourroses666** [comment]
Oke, I close this. When we have a restyled manager I will replace the images in the readme
