### ISSUE TITLE
Question: using curly brackets from third party script in a chunk

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#703]
Hello,

This is a question relating to the curly brackets used in {{chunks}} and third party providers that also use curly brackets for their placeholders.

I am using cookieconsent and need to make a change to the templating (the privacy policy link opens in a new window by default). I am also hoping to include the code in a chunk rather than an external js file.

cookieconsent use curly brackets for their Layouts and Elements placeholders like so...
```
<script>
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
		"content": {
			"message": "This website uses cookies to ensure you get the best experience on our website.",
			"dismiss": "Got it!",
			"link": "Learn more",
			"href": "/privacy-policy/"
		},
		"layouts": {
			"basic": "{{messagelink}}{{compliance}}",
			"basic-close": "{{messagelink}}{{compliance}}{{close}}",
			"basic-header": "{{header}}{{message}}{{link}}{{compliance}}"
		},
		"elements": {
			"messagelink": "<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a></span>",
			"link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a>"
		}
	})
});
</script>
```

If I include it as is Evolution thinks (rightfully so) I am calling chunks.

Is it possible to escape or do something to the curly brackets above so that for this particular cookie-consent chunk, the curly brackets are not considered as a chunk?

Thanks for any help.

**Comment by Deesen** [comment]
Have you tried to escape them?

```
    "layouts": {
	"basic": "\{\{messagelink\}\}\{\{compliance\}\}",
        ...
    },
```

**Comment by nick0** [comment]
Thanks @Deesen.

I hadn't, I wasn't sure how to do that so thanks for your help. I just tried like that wth the \ escaping but the content does not show. 

My code now looks like so:

```
<script>
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
		"content": {
			"message": "This website uses cookies to ensure you get the best experience on our website.",
			"dismiss": "Got it!",
			"link": "Learn more",
			"href": "/privacy-policy/"
		},
		"layouts": {
			"basic": "\{\{messagelink\}\}\{\{compliance\}\}",
			"basic-close": "\{\{messagelink\}\}\{\{compliance\}\}\{\{close\}\}",
			"basic-header": "\{\{header\}\}\{\{message\}\}\{\{link\}\}\{\{compliance\}\}"
		},
		"elements": {
			"messagelink": "<span id="cookieconsent:desc" class="cc-message">\{\{message\}\} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a></span>",
			"link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a>"
		}
	})
});
</script>
```

Has got me stumped for sure.

**Comment by modxuser** [comment]
Make your life a lot easier: http://www.codingdivas.net/divascookies/

**Comment by Deesen** [comment]
Which version do you use? I tested with latest version and for me it works.

Chunk "issue703":

![image](https://user-images.githubusercontent.com/8569221/40779682-2860f78c-64d6-11e8-82fd-57e6c6aeb38e.png)

--------------------------------

Display in frontend:

![image](https://user-images.githubusercontent.com/8569221/40779652-0e27c440-64d6-11e8-9d12-79a7f8cd6775.png)

**Comment by Deesen** [comment]
I also prepared a plugin for cookie-consent by insites but I am not sure it offers every setting you need out of the box:

[evo-cookie-consent.zip](https://github.com/evolution-cms/evolution/files/2057986/evo-cookie-consent.zip)

It has a parameter "additional javascript" which you can use as follows.

Use file with additional JS: `@FILE:assets/plugins/cookie-consent/js/example_opt-in.js` . 
Use chunk with additional JS: `@CHUNK:cookie-consent-script` .

**Comment by nick0** [comment]
Thanks for your help @Deesen and @modxuser. I got sidetracked by other design elements of the project, will tackle early next week and confirm back. Thanks again and a great weekend to you both.

**Comment by nick0** [comment]
Thanks @Deesen and @modxuser.

The brackets looked correctly escaped in the front end html so EvolutionCMS was correctly escaping.

I found a javascript error in Chrome using developer. It was throwing an “Uncaught SyntaxError: Unexpected identifier” for my cookie consent code – specifically relating to elements.

I narrowed it down to “” within the “” call.

So I changed…
```
                        "elements": {
                                    "messagelink": "<span id="cookieconsent:desc" class="cc-message">/{/{message/}/} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="/{/{href/}/}" target="_self">/{/{link/}/}</a></span>",
                                    "link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="/{/{href/}/}" target="_self">/{/{link/}/}</a>"
                        }
```

to… 
```
                        "elements": {
                                    'messagelink': '<span id="cookieconsent:desc" class="cc-message">\{\{message\}\} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a></span>',
                                    'link': '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a>'
                        }
```

And now it works as expected which is awesome - the Learn More link now opens in the same window. 

Many thanks for your help.

I will check out those links but this is now working as is.

Cheers to you both.

**Comment by nick0** [comment]
ps if anyone is interested this is the working code below...

```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
		"content": {
			"message": "This website uses cookies to ensure you get the best experience on our website.",
			"dismiss": "OK",
			"link": "Learn more",
			"href": "/privacy-policy/"
		},
		"layouts": {
			"basic": "\{\{messagelink\}\}\{\{compliance\}\}",
			"basic-close": "\{\{messagelink\}\}\{\{compliance\}\}\{\{close\}\}",
			"basic-header": "\{\{header\}\}\{\{message\}\}\{\{link\}\}\{\{compliance\}\}"
		},
		"elements": {
			'messagelink': '<span id="cookieconsent:desc" class="cc-message">\{\{message\}\} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a></span>',
			'link': '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a>'
		}
	})
});
</script>
```
