### ISSUE TITLE
Question: Rename Cookies

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#704]
Is it possible to change the session cookie name ?

When I look at the cookies each time I clear cookies, I get "evoxxxxx" where "xxxxx" different numbers etc appear

I ask this due to security, if a hacker looks at the cookies, they can determine that the website is using "EVO" and so, have a head start.

Is it possible to dynamically create the name ?

Not being a developer I have no idea how this works, or even if it's possible

**Comment by AgelxNash** [comment]
There are many other signatures. I don't see anything critical in this.
Read [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity).

**Comment by modxuser** [comment]
@AgelxNash sorry for the late reply

"Security through obscurity" as described in WIKIPEDIA is not my aim

Evo may or may not have security issues, that's irrelevant for what I am asking

Changing the name of the manager folder can be classed as obscurity, but it has nothing to do with the system having or not having issues

The idea is NOT that the system has flaws and they need to be obscured, it is simly to obscure the identity of the system in use, to make things harder for hackers to find out what system if at all is being used

**Comment by AgelxNash** [comment]
Your idea is good. But while the folder **assets** exist!!! Cookie name does not change anything.

> Changing the name of the manager folder can be classed as obscurity, but it has nothing to do with the system having or not having issues

It's not true.  The standard administration folder is a potential type of attack (bruteforce, XSS, CSRF, sql-injection, etc...)

**Comment by risingisland** [comment]
Maybe replace the prifix with  "site_name_xxxxxxx"  instead of "evoxxxxxx"?

**Comment by dmi3yy** [comment]
now prefix on install is random )  but for old site you can change by hands )

**Comment by AgelxNash** [comment]
@modxuser Enjoy
```
curl -d "tplID=4" -X POST https://evo.im/assets/modules/docmanager/tv.ajax.php
```

**Comment by AgelxNash** [comment]
This will be possible in version 2.0
- Create file: [/core/custom/define.php](https://github.com/evolution-cms/evolution/blob/core-extract/core/custom/define.php.example)
- define the constant: [SESSION_COOKIE_NAME](https://github.com/evolution-cms/evolution/blob/core-extract/core/includes/define.inc.php#L14)
