### ISSUE TITLE
[phpthumb] returns error in strict hosting mode

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#705]
After closing access to /home/ directory (which is above/above/above the site root) phpthumb is unable to create thumbnails.

error output:
```
Error : is_link(): ... File(/home) is not within the allowed path(s):
ErrorType[num]   WARNING[2]
File | /home/..../www/....../assets/snippets/phpthumb/phpthumb.class.php
Line | 1125
Source | if (is_link($thispart)) {
Current Snippet | phpthumb
```

**Comment by sashabeep** [comment]
Module that produced this error
https://github.com/Whissi/realpath_turbo

**Comment by AgelxNash** [comment]
You must resolve this issue with the developer phpthumb https://github.com/JamesHeinrich/phpThumb/issues/116
