### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by johnmcgeary** [evolution-cms/evolution#706]
I have been trying to update my website to the latest version and the website is now knackered.  This is my backtrace information - can anyone help?

Fatal error: Uncaught Error: Call to undefined function mysql_query() in /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(1880) : eval()'d code:600 Stack trace: #0 /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(1880): eval() #1 /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(5393): DocumentParser->evalPlugin('//<?php\n\nif(!cl...', Array) #2 /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(958): DocumentParser->invokeEvent('OnWebPagePreren...', Array) #3 /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(2949): DocumentParser->outputContent() #4 /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(2825): DocumentParser->prepareResponse() #5 /home/linweb20/m/mywebsite.net/user/htdocs/index.php(139): DocumentParser->executeParser() #6 {main} in /home/linweb20/m/mywebsite.net/user/htdocs/manager/includes/document.parser.class.inc.php(1880) : eval()'d code on line 600

Using php7, upgraded from 1.0.15 to current version, I have also deleted all my old snippets and I can logo into the manager fine so any ideas?

**Comment by modxuser** [comment]
What snippets / plugins / modules are used in the system and do you have custom code ?

Have you updated all of the snippets / plugins / modules you are using ?

I am not a programmer, but looking at what you have pasted above, you have "mysql_query" - 1.4.3 use "mysqli" which tells me you have outdated code coewhere which is probably causing the site to not load in the front-end

**Comment by johnmcgeary** [comment]
Thanks, yes got it going as it was an old snippet :)
