### ISSUE TITLE
MaxiGallery Snippet dead after site upgrade to Evo 1.4.3

### ISSUE THREAD

**Issue by johnmcgeary** [evolution-cms/evolution#708]
Hi Guys,

Has anyone got MaxiGalley to work on Evo 1.4.3 and PHP 7.

Upgraded my old Evo site to the current version and it killed MaxiGallery.

Any help would be great.

**Comment by leonie12** [comment]
Here MG works with PHP 7.1 as it is expected. One problem with MG that I have is not  PHP version related.

**Comment by Deesen** [comment]
@johnmcgeary Please mention more details about any occuring error-messages (also browser-console)..

**Comment by dmi3yy** [comment]
are you update MG ? maybe problem with this

**Comment by dmi3yy** [comment]
About MaxiGallery write here: 
https://github.com/extras-evolution/MaxiGallery/issues
