### ISSUE TITLE
Names of snippets/roles/chunks etc set as 'null' are not saved correctly

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#72]
If a new snippet, chunk, role etc is set with a name of 'null' then it is created correctly, but if edited and saved then the name is set to blank.
![untitled-1](https://user-images.githubusercontent.com/1744687/28379559-ffa937dc-6cab-11e7-91fc-42cf74f637d1.jpg)

**Comment by dmi3yy** [comment]
@64j  Поставь плз на js что б не сохраняло если пустое :) думаю так быстрее и проще )
