### ISSUE TITLE
Setting "depth" for DLSitemap

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#720]
Hello,

How can I set depth of documents in DLSitemap?
This seems doesn't work: `[[DLSitemap? &depth='2']]`

**Comment by Pathologic** [comment]
Using depth parameter needs idType=parents and parents as well.

**Comment by 64j** [comment]
@modwebpl 
may be quotes ?
```
[[DLSitemap? &depth=`2`]]
```

**Comment by modwebpl** [comment]
Well, this doesn't work :(

![zrzut ekranu 2018-06-11 o 16 06 28](https://user-images.githubusercontent.com/35030936/41236445-72c99f36-6d91-11e8-8f37-524a27433de4.png)

**Comment by 64j** [comment]
@modwebpl 
There is no such parameter, all documents are displayed

**Comment by modwebpl** [comment]
Well ok, so how can i set depth for sitemap ? :/ It it possible ?

**Comment by 64j** [comment]
@modwebpl 
Why put depth?
Displays all permitted documents

**Comment by Pathologic** [comment]
DLSitemap is a wrapper to run Doclister with predefined parameters, idType=documents in particular, to achieve maximum speed. You need to run it with idType=parents if you need depth parameter. See snippet code for details.

**Comment by modwebpl** [comment]
Thank you for your answers.
64j: I need depth=2 because I have many url's from chunks, example here: http://help4skin.modweb.pl/sitemap.xml

...
<loc>http://help4skin.modweb.pl/faq/101</loc> <-- useless blank document from FAQ
<loc>http://help4skin.modweb.pl/faq/102</loc> <-- useless blank document from FAQ
<loc>
http://help4skin.modweb.pl/produkty/kopia-zel-hydrokoloidowy-przyspieszajacy-gojenie-ran2/79/81
</loc> <-- useless blank document from product
...

Of course, I can edit all useless document and set variable as "not searchable". But sometimes there is a lot of documents in CMS so I want to create some kind of "automatic process".

Pathologic: can you write some example? Unfortunately I don't know how to use: "idType=parents"

**Comment by Pathologic** [comment]
:man_facepalming: 
```
[[DLSitemap? &idType=`parents` &parents=`10` &depth=`2`]]
```
BTW, you can use filters or addWhereList parameters to exclude documents.

**Comment by 64j** [comment]
@modwebpl 
Disabled flag Searchable
And then the documents will not be included in the site map

![image](https://user-images.githubusercontent.com/4653189/41285928-7054ffec-6e46-11e8-8c50-9d1e864ac066.png)

**Comment by pmfx** [comment]
I wouldn't recommend disabling Searchable just to exclude document from Sitemap as this can also exlude document from AjaxSearch etc. Better use "sitemap_exclude" Template Variable.

**Comment by 64j** [comment]
@pmfx 
For a long time we do not use
Ditto
Wayfinder
AjaxSearch
eForm
WebLogin
and others...

**Comment by nick0** [comment]
Me too, I guess I will keep using AjaxSearch until "DLSearch" (based on DocLister) is released.

An alternative to DLSitemap is just using DocLister and create the relevant templates (I prefer this)...

```
[[DocLister?
	&id=`xml[*id*]`
	&idType=`parents`
	&parents=`0`
	&depth=`9`
	&showParent=`1`
	&ownerTPL=`sitemap-xml-wrapper`
	&tpl=`sitemap-xml-row`
	&tplFirst=`sitemap-xml-row-first`
	&tplLast=`sitemap-xml-row-last`
	&dateSource=`editedon` 
	&dateFormat=`%Y-%m-%d`
	&tvList=`sitemap_changefreq,sitemap_priority`
	&orderBy=`parent ASC, menuindex ASC, pagetitle ASC` 
	&filters=`AND(
		tvd:xml-sitemap:is:no;
		content:c.template:notin:6,7,8,11,23;
		content:c.id:notin:5,6,7
	)`
]]
```
