### ISSUE TITLE
Issues with managing users

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#722]
Found two issues.

1. User logged in as Publisher (role have user management permissions) can edit users but cannot save changes. Alert appears. This was an attempt to edit user with Publisher role. Same situation when trying to save user with Editor role.

![screenshot_3](https://user-images.githubusercontent.com/10888055/41195671-71b52ecc-6c32-11e8-91b0-139907e0c2d6.png)

2. Second issue is that non-admin user can see Administrators user names in the dropdown menu and he can even edit them. Administrators are not visible in datatable view (thats correct).

![screenshot_4](https://user-images.githubusercontent.com/10888055/41195712-1e3d5b42-6c33-11e8-996c-dc1f5a4cf52c.png)

**Tested in 1.4.3 and 1.4.4**

**Comment by bossloper** [comment]
Confirm I see this issue too.

**Comment by 64j** [comment]
And check "Save roles"

![image](https://user-images.githubusercontent.com/4653189/41221711-8d637f34-6d6d-11e8-8712-875f6b2a369d.png)

**Comment by 64j** [comment]
p.s.
Need to rewrite all the rights for managers

**Comment by pmfx** [comment]
There is a problem still.
- if Publisher don't have Edit/Save role permissions he can't save edited user.
- if Publisher does have Edit/Save role permissions he can save edited user, but now he can also see Administrators accounts and edit them (but can't save changes). 
- I don't want Publisher to be able to edit roles just to be able to edit users accounts.

**Comment by 64j** [comment]
@pmfx 
Has corrected. Check

**Comment by pmfx** [comment]
Hm. Does this fix work with 1.4.3 or 1.4.4? 
I've uploaded files you changed (3 files) to 1.4.4 and have this error when trying to save user:

`
Fatal error: Uncaught Error: Call to undefined function saveManagerUserSettings() in /home/site/domains/site.pl/public_html/dev-evodev/manager/processors/save_user.processor.php:253 Stack trace: #0 /home/site/domains/site.pl/public_html/dev-evodev/manager/index.php(418): include_once() #1 {main} thrown in /home/site/domains/site.pl/public_html/dev-evodev/manager/processors/save_user.processor.php on line 253
`

**Comment by pmfx** [comment]
So we can't have patch for sites on 1.4.3 or 1.4.4? That's really bad as this is rather a big issue for some of my sites... I hope 1.4.5 will be released soon.

**Comment by 64j** [comment]
@pmfx 
https://github.com/evolution-cms/evolution/blob/1.4.4/manager/processors/save_user.processor.php#L59

replace "save_role" -> "save_user"

**Comment by pmfx** [comment]
@64j thanks! Looks like this and updated ajax.php fixed the issue.
