### ISSUE TITLE
TinyMCE4 - no custom plugin template after update to 1.4.4

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#726]
Hi @ all,
after the update to evo cms 1.4.4 via updater the TinyMCE4 (v4.7.4) individual plugins can not be selected anymore.
the text editor displays only one line with buttons. 
the buttons entered in the configuration are not displayed.
all plugins or full plugins for example can be selected and displayed.

in version 1.4.3, this problem did not occur in any of my installations

any ideas?

Thanks Arno

**Comment by ArnoNymeier** [comment]
Problem solved?

I looked at the file "theme.tinymce4.custom.inc.php" 
with the update comes a new version of this TinyMCE file. 
The new file ->

```
if( !empty( $this->modxParams['custom_plugins'])) {
    $this->set('plugins', $this->modxParams['custom_plugins'], 'string' );
};
$this->appendSet('plugins', 'template', ' '); // Assure plugin is loaded / in plugins-list

$this->set('menubar', false, 'bool' ); // https://www.tinymce.com/docs/configure/editor-appearance/#menubar

// Take over global values for each of the 4 rows
if(!empty($this->modxParams['custom_buttons_useglobal'])) {
    $i=1;
    while($i<=4) {
        $this->modxParams['custom_buttons'.$i] = $modx->configGlobal[$this->editorKey.'_custom_buttons'.$i]; 
        $i++;
    }
}

$this->set('toolbar1', $this->modxParams['custom_buttons1'], 'string', false );
$this->set('toolbar2', $this->modxParams['custom_buttons2'], 'string', true );
$this->set('toolbar3', $this->modxParams['custom_buttons3'], 'string', true );
$this->set('toolbar4', $this->modxParams['custom_buttons4'], 'string', true );
```

is different from the "old" of Evo 1.4.3:

```
if( !empty( $this->modxParams['custom_plugins'])) {
    $this->set('plugins', $this->modxParams['custom_plugins'], 'string' );
};
$this->appendSet('plugins', 'template', ' '); // Assure plugin is loaded / in plugins-list

$this->set('menubar', false, 'bool' ); // https://www.tinymce.com/docs/configure/editor-appearance/#menubar

$this->set('toolbar1', $this->modxParams['custom_buttons1'], 'string', false );
$this->set('toolbar2', $this->modxParams['custom_buttons2'], 'string', false );
$this->set('toolbar3', $this->modxParams['custom_buttons3'], 'string', false );
$this->set('toolbar4', $this->modxParams['custom_buttons4'], 'string', false );
```

replacing the new file with the one of Evo 1.4.3 solves the problem, the custom plugins and buttons are now displayed again.

**Comment by bossloper** [comment]
Agreed there is an issue here. TinyMCE4 should pick up custom buttons from 'system config'->'interface and features'. Then optionally override from individual manager ->user settings if 'use the global settings' is unchecked.
It is doing neither in 1.4.4

**Comment by bossloper** [comment]
Now I am not so sure there is an issue. The settings are cached with the manager login so logging out and back in it seems all is ok?

**Comment by fourroses666** [comment]
Agree. Would be nice to have it a bit simplyfied and all settings on the interface page.

**Comment by Deesen** [comment]
@ArnoNymeier User-settings are cached in the session at the time you log in. When changing user-settings that user need to log out and log in again to apply any changed user-settings (related to #616).

**Comment by ArnoNymeier** [comment]
@ all, thanks for the input

for me, replacing the custom file works fine and as it should.
so far, everything worked as expected: configuration -> change -> save and directly use the new settings.
performing a log out and in every time is a very uncomfortable work flow.
For my oppinion these changes in Evo 1.4.4 are a deterioration to previous behavior.

thanks to google translate ;-)

**Comment by Deesen** [comment]
Deterioration to previous? MODX / Evo always handled user-settings like that. Means you need to log out and in again to apply any changed user-settings, while changes in system-settings are applied immediately.

**Comment by ArnoNymeier** [comment]
hmm ... maybe a little misunderstanding?

What I meant: After the update to 1.4.4, when editing a document, the previous custom buttons were no longer displayed.

logged in as admin I have a look at the settings.
in the user settings (global), the custom template was selected as previously set.

but this was not used!

Change to another template e.g. "Full" worked.
After selecting the other template -> save the settings -> back to the document -> the new template (buttons) will be displayed. WITHOUT logout and login!

back to the settings -> selection of the custom templates -> save -> this template is NOT applied.

Changes to the templates (global) have always worked with me so far.
For all installations, whether updated or as a new installation (1.4.3), this behavior was as described.

After the update, the global settings (custom) were retained but not applied.

whether a solution can be achieved by logout and login here, I would have to test once.

but I still believe that the previous behavior is more user friendly.

**Comment by bossloper** [comment]
I think there is an issue here after all.

If I **upgrade an existing website** then if the toolbar (theme) is set to 'custom' the custom toolbar does not show up. Even after login out and back in. If I edit the manager account and alter any setting to force a resave of the manager settings then it works as expected and displays the correct toolbars.

So something to do with existing manager accounts not having the updated settings correct until resaved.

**Comment by dmi3yy** [comment]
I fix it commented this code 

<img width="776" alt="image" src="https://user-images.githubusercontent.com/669491/42537203-db7c9d72-849c-11e8-8db2-e79194c63ecb.png">
and all fine
