### ISSUE TITLE
Ampersand (&) in Site Name escaped infinitely

### ISSUE THREAD

**Issue by ricardo-lewis** [evolution-cms/evolution#727]
If you put an ampersand in the site name (in config) it will get escaped every time you save the config to `&amp;` then every time after that: `&amp;amp;`, `&amp;amp;amp;` etc

Previous versions of EVO and MODX did not do this.

EVO 1.4.4
Ubuntu 14.04 Server
Apache 2.4.7
PHP 5.5.9
MySQL 5.5.59

**Comment by AgelxNash** [comment]
https://github.com/ClipperCMS/ClipperCMS/issues/483

**Comment by ricardo-lewis** [comment]
Nice one, fixed it perfectly!
