### ISSUE TITLE
Upgrade when database password has a double-quote

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#729]
If I upgrade a website that has a database password of for example:
`Ak;&YOP"NMU&543tg`

After the upgrade the config file has the database password set as:
`Ak;&YOP\"NMU&543tg`

i.e the double-quote in the password is escaped and thus the db connection fails until corrected manually.

**Comment by 64j** [comment]
@bossloper 
You know that the quotation mark can not be contained in passwords.
All valid characters are written on the keyboard on numbers from "1" to "="
!@#$%^&*()-_=+
