### ISSUE TITLE
Manager login - remember me?

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#73]
There is no longer any 'remember me' for a manager session?

**Comment by dmi3yy** [comment]
From 1.0.6 not work ;) and no one see this;)

Отправлено с iPhone

**Comment by bossloper** [comment]
I was using it fine on 1.0.15 and I (and my clients will) see it as a major issue if you need to log in every time.

**Comment by bossloper** [comment]
p.s. If server session.gc_maxlifetime is set appropriately and sessions are independent of other sites on a shared server then it works fine... I have been using it for the last several years.

**Comment by dmi3yy** [comment]
On shared hosting lifetime 30 min

Then logout even in check remember 


Отправлено с iPhone

**Comment by bossloper** [comment]
But if not shared hosting, or in control of the server settings then it works. So why remove the option?

**Comment by dmi3yy** [comment]
ok we return back )

**Comment by bossloper** [comment]
Thanks!

**Comment by Pathologic** [comment]
Shared hosting needs a cookie and a regular update of session_id, like modUsers does.
