### ISSUE TITLE
Link Attributes

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#743]
hi

evo 1.4.2

are the "Link Attributes" completely ignored in dlmenu where they were not ignored in wayfinder? no real mention of them here either http://docs.evo.im/en/04_extras/dlmenu.html . we have sites with wayfinder and the "link attributes" are brought into the wayfinder output perfectly. dlmenu just ignores "link attributes". any ideas? no documentation here.

**Comment by user83743** [comment]
[!DLMenu?   &amp;outerClass=`nav navbar-nav`   &amp;orderBy=`menuindex ASC`     &amp;parents=`0`   &amp;maxDepth=`3`      &amp;rowTpl=`@CODE <li[+classes+]><a href="[+url+]" [+link_attributes+]>[+title+]</a></li>` !]       <---- NOT WORKING. NOT USING THE "LINK ATTRIBUTE" DATA FROM THE CMS INTERFACE

**Comment by nick0** [comment]
I think `[+link_attributes+]` in a DLMenu row template like below does actually work fine. 
```
<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a>[+wrap+]</li>
```
Maybe a programmer can confirm but seems to be working for me in 1.4.4

**Comment by user83743** [comment]
thnaks. we tried [!DLMenu? &outerClass=nav navbar-nav &orderBy=menuindex ASC &parents=0 &maxDepth=3 &rowTpl=@CODE <li[+classes+]><a href="[+url+]" [+link_attributes+]>[+title+]</a></li> !]  and it did not produce any link_attributes. any ideas ?

**Comment by nick0** [comment]
Bummer.

You could try and copy and paste this one (a html sitemap) that works for me (change chunk names as relevant)...

{{sitemap}}
```
[[DLMenu?
	&id=`sitemap[*id*]`
	&parents=`0`
	&disablePHx=`1`
	&addWhereList=``
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&outerTpl=`sitemap-html-wrapper`
	&rowTpl=`sitemap-html-row`
	&categoryFolderTpl=`sitemap-html-category`
	&orderBy=`menuindex ASC`
]]

sitemap-html-category = 
<li[+classes+]>[+title+]
[+wrap+]</li>

sitemap-html-row = 
<li[+classes+]><a href="[+url+]" title="[+pagetitle+]" [+link_attributes+]>[+title+]</a>
[+wrap+]</li>

sitemap-html-wrapper = 
<ul>
 [+wrap+]
</ul>

```

Does that work for you? If not, we will need one of the programmers to help out.

**Comment by user83743** [comment]
thanks Nick! much appreciated. we have decided that we've spent enough time on this and it shouldn't' be this difficult to get a simple examle working. docs are minimal , examples are poor and we've just pulled out the [!wayfinder!] and it is working fine :). have a great day.

**Comment by nick0** [comment]
Pleasure @user83743. No worries.
One upside to DLmenu is Ditto style filtering in hierarchical (WayFinder style) lists - worth the changeover pain for that imho but understood and I hear you. Cheers and to you :)
