### ISSUE TITLE
cannot save the "System configuration" within the manager

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#746]
Hello,

I am stuck and need a little help.

I have recently updated a 1.0.14 MODx Evo site that was hacked to clean installs of 1.0.15, then 1.0.21, then Evo 1.4.3. The frontend seems to work fine.

For some reason I cannot save the "System configuration" within the manager. Every time I try it throws the website 404 error page so I see the frontend website 404 in that frame where the settings were. 

I can save and edit elements, resources, run modules like Evo Check etc - just not the "System configuration" settings page. 

And I also cannot access the dashboard because of the message "As this is a new install, you are required to review these settings and change any that you wish to. After you have reviewed the settings, press 'Save' to update the settings database."

I think the issue might be related to TinyMCE but I am not 100% sure as the errors take a while to show up on the server. These are in the logs from this morning when the site was 1.0.21.
```
[28-Jun-2018 08:36:17 UTC] PHP Warning:  require(/home/mmm/public_html/assets/plugins/tinymce/plugin.tinymce.php) [<a href='function.require'>function.require</a>]: failed to open stream: No such file or directory in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php(1352) : eval()'d code on line 1
[28-Jun-2018 08:36:17 UTC] PHP Fatal error:  require() [<a href='function.require'>function.require</a>]: Failed opening required '/home/mmm/public_html/assets/plugins/tinymce/plugin.tinymce.php' (include_path='.:/opt/alt/php53/usr/share/pear:/opt/alt/php53/usr/share/php:/home/mmm/public_html/ma--na--ger--8/includes/') in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php(1352) : eval()'d code on line 1
```

I have access to phpmyadmin though my mysql modification skills are very limited beyond changing numbers in fields etc.

The file permissions of config.inc.php are 404. Changing them to 644 for testing does not resolve the issue for me.

PHP version is 7.0.30.

Any suggestions?

Is there a way to force saving (eg in PhpMyAdmin by changing a field number) the configuration file so I can see the Dashboard?

Greatly appreciate any help.

**Comment by Deesen** [comment]
I guess this is the old TinyMCE-version causing the problem. You can use Evocheck to delete it.

**Comment by nick0** [comment]
Thanks for the assist @Deesen. 
I had actually already deleted the old TinyMCE but triple checked in Evocheck - definitely not there. 
I also deleted TinyMCE4 in Evocheck just in case but it makes no difference (in phpmyadmin I had already changed to none for which_editor,) I still can't save and get the error page.
Any other ideas?

**Comment by bossloper** [comment]
You could try Evo 1.4.4? Maybe you had an incomplete install? 
I run 1.4.4 with both TinyMCE3 and TinyMCE4 running at the same time, no problem. php 5.6, 7.0 and 7.1

**Comment by nick0** [comment]
Thanks for your help Mr B. Good idea. You are lucky :)

I just updated manually to 1.4.4 via ftp - same issue exists. 
(Because I can't reach the dashboard, I can't do the automatic updating)

I have got the nice new login page and the system info says 1.4.4, however in the user drop down in yellow it says 1.2.1 but the hover says 1.4.4. So something wierd is happening (even in different browsers with cache fully cleared)

Also... Interestingly, in the database snapshot, when I download and view system settings, I can see these 3 items of interest...
```
#
# Table structure for table `modx_system_settings`
#

CREATE TABLE `modx_system_settings` (
  `setting_name` varchar(50) NOT NULL DEFAULT '',
  `setting_value` text,
  PRIMARY KEY (`setting_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Contains Content Manager settings.';

#
# Dumping data for table `modx_system_settings`
#

INSERT INTO `modx_system_settings` VALUES ('settings_version','1.2.1');

INSERT INTO `modx_system_settings` VALUES ('use_editor','0');

INSERT INTO `modx_system_settings` VALUES ('which_editor','none');

```
So it says 1.2.1 in there.

Any other ideas?

Thanks so much for any help.

**Comment by Deesen** [comment]
It still says 1.2.1 because you need to save configuration once successfully, before the new version-no appears.

Does your error-msg still mentions "assets/plugins/tinymce/plugin.tinymce.php" even when you deleted it?

**Comment by nick0** [comment]
Ah, that makes sense :)

These are the latest error logs - now saying completely different things...

I am not sure if there is a delay on these errors appearing.
```
in document root...
[29-Jun-2018 08:13:48 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
[29-Jun-2018 08:13:48 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
[29-Jun-2018 08:13:58 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
[29-Jun-2018 08:14:00 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
[29-Jun-2018 08:14:02 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
[29-Jun-2018 08:14:17 UTC] PHP Fatal error:  Uncaught RuntimeException: Call DocumentParser::executeParser on CLI mode in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php:2740
Stack trace:
#0 /home/mmm/public_html/index.php(139): DocumentParser->executeParser()
#1 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/includes/document.parser.class.inc.php on line 2740
```
in manager folder
```
[29-Jun-2018 08:13:48 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function evolutionCMS() in /home/mmm/public_html/ma--na--ger--8/index.php:146
Stack trace:
#0 {main}
  thrown in /home/mmm/public_html/ma--na--ger--8/index.php on line 146

```
Can you make sense of those errors?

**Comment by Deesen** [comment]
It seems to me your `/manager/includes/config.inc.php` has not been updated correctly. Maybe give it file-permission 0777 and then run `/install/` again. After that step the last line of your config.inc.php should show

`include_once(MODX_MANAGER_PATH . 'includes/preload.functions.inc.php');`

If not, something went wrong.

**Comment by nick0** [comment]
Thanks Deesen.. I followed your steps.

The last line of the config.inc.php file seems to match yours, copying below:
```
include_once(MODX_MANAGER_PATH . 'includes/preload.functions.inc.php');
```
Comparing the config file with another succesful 1.4.4 site, there is some extra bit in this problem site
```
/**
 * Preventing the overwrite of the config when updating
 * Here you can
 *  - define manual constants, dedicated specifically for you project
 *  - inject composer
 *  - change predefined variables by the environment variables
 *  - ...
 *  - etc.
 *  - PROFIT!
 */
if (file_exists(__DIR__ . '/config_mutator.php')) {
    require_once __DIR__ . '/config_mutator.php';
}
```
I deleted the above (not sure if that was a good idea), no difference.

Any other suggestions?

Is there a way to trick / force config saving through phpmyadmin?

**Comment by Deesen** [comment]
No there is no such trick. Something else is wrong. Maybe some files have no been uploaded correctly. If you wish and can provide manager-login, I can take a look.

**Comment by nick0** [comment]
Ah ok, bummer.

That would be amazing Deesen, thank you so much, How can I send it to you privately - the email on your website "fuseit" from your GitHub profile? Do you want ftp access too?

By the way... I can bluff my way to the Dashboard if I change 1.2.1 to 1.4.4 but it only last for one viewing.

Thank you Deesen.

**Comment by dmi3yy** [comment]
If ou have some trouble with update you can write to me dmi3yy@gmail.com and i help )

need access to manager and ftp

**Comment by Deesen** [comment]
Yes you can use this email. Incl. FTP-access yes, so I can check some files if nessecary.

**Comment by nick0** [comment]
Thanks so much to you both. 
@Deesen offered first so I have email him the access details. 
Will send to you @dmi3yy if @Deesen can't work it out.
Thank you again, I really appreciate the kind assistance.

**Comment by Deesen** [comment]
@dmi3yy When I try to save configuration, the server returns a 404-error. When saving a chunk, everything works fine. Even with deactivated .htaccess-files, so I have no clue. Maybe you know better.

**Comment by dmi3yy** [comment]
Need see error log on server 
Maybe trouble with php securemod

Отправлено с iPhone

**Comment by fourroses666** [comment]
Indeed looks like a server setting mod_secure

Had the same issues.
You sure its php is 7?

**Comment by nick0** [comment]
It looks like the error logs are totally empty. Just send info to Dennis to have a look.

Its definitely PHP 7.

Do you know what you did to fix it Marc?

**Comment by nick0** [comment]
ps I can't seem to change the category name of Wayfinder - but I can for some of the custom snippets. Weird one. 

Just on the mod_secure... I did try this in the htaccess file earlier in the day but it didn't seem to help
```
doesn't seem to work either...
#hosting mods
<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>
```

**Comment by fourroses666** [comment]
The host didn’t wanted to fix it because of shared hosting. I was able to edit and save pages, only couldnt update configuration stuff. So basicly it was or keep having these issues or move from host. Last one I think we did.

**Comment by nick0** [comment]
Ah I see, ok thanks for confirming.
Moving the hosting at the moment is not an option. 
Hopefully Dennis works out what the issue is, I can then ask the host and hopefully they can tweak something for me.
Thanks Marc.

**Comment by nick0** [comment]
Its late here so am turning off for the night, 
@dmi3yy, I just emailed you access info too. Thanks all and have a great day/night

**Comment by fourroses666** [comment]
Or only use different webhosting (dns) if it just doesn’t work out so e-mail etc stays the way it is. Does have double costs.
