### ISSUE TITLE
evo 1.2.1 tinymce 4 - link to images folder, not only to files

### ISSUE THREAD

**Issue by wishbone-design** [evolution-cms/evolution#750]
before upgrading to tinymce 4, there was a setting somewhere (I don't remember where) and I was able to link to different resource types, i.e. to see in fckeditor options for files, images, media, like so:
![modx-templ-04-mit](https://user-images.githubusercontent.com/3841564/42185305-b2b4c374-7e48-11e8-99ef-756799968775.jpg)

Now, with tinymce 4, I can't find such any more.
How can I insert a link and kcfinder displays the different folders for different types, i.e. "images", "files" etc. E.g. link an image to it's larger version.

thx!

**Comment by Deesen** [comment]
Does it help if "images" get opened instead of "files", when using the link-button? Then you can try changing this line

https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/tpl/tpl.tinymce4.config.html#L9

and replace `type = 'files'` by `type = 'images'`

**Comment by wishbone-design** [comment]
thx. No, in other cases, we need "files". Should be an option to choose between the folders...
I've already thought about that line; but since I don't know php, I can't change to type = files, images, media

**Comment by fourroses666** [comment]
Might be cool, this way you can set a link to the images instead of default to files.

**Comment by Pathologic** [comment]
Update modxlink plugin of tinymce with this one:
https://gist.github.com/Pathologic/e29ea9fffacf25f63ac4f12f3023b03b

![image](https://user-images.githubusercontent.com/3012304/42521139-b8a7de5a-8470-11e8-8f3d-687cc8b71826.png)

**Comment by wishbone-design** [comment]
how can I reopen the issue?
It's not about modxlink. It's the local filebrowser that only directs to "files"-folder.
See screenshot above.
This should be a common problem; how do other people solve it? Link a small image to a larger ist very common.

**Comment by Pathologic** [comment]
I've added additional button to select image for link or what is needed?

**Comment by bossloper** [comment]
I think your solution is good @Pathologic , just the code you committed https://github.com/evolution-cms/evolution/commit/63b229bf35d7278a896dd88b319ec43a21e5bfdd  did not actually add the extra button as your example did https://gist.github.com/Pathologic/e29ea9fffacf25f63ac4f12f3023b03b

**Comment by Pathologic** [comment]
@bossloper sorry, it's fixed now.

**Comment by wishbone-design** [comment]
@Pathologic thx for your work - but where is the fix?

**Comment by wishbone-design** [comment]
(( no button ((

**Comment by bossloper** [comment]
The old js file may be cached, try clearing your browser cache.

**Comment by wishbone-design** [comment]
![grafik](https://user-images.githubusercontent.com/3841564/42584859-76b86b08-8534-11e8-893b-211ebe63628d.png)
(((

**Comment by bossloper** [comment]
How did you upgrade your installation to add the functionality?

**Comment by wishbone-design** [comment]
which functionality? I upgraded to tinymce4 some years ago. Only now I saw that the former options to choose different folders was gone.
replaced with your file - no effect ((

**Comment by bossloper** [comment]
Was not my file, but maybe you updated the wrong file. I installed the latest 1.4.x release from GitHub and it works for me.

**Comment by risingisland** [comment]
I just double checked also, on v1.2.2 and v1.4.3
Both worked as expected.

Rename or backup "assets/plugins/tinymce4/tinymce/plugins/modxlink/plugin.min.js", replace with new.
Not sure what browser you are using, but you could open admin in a private/incognito window to make sure that it is not a cacheing issue.

**Comment by bossloper** [comment]
last thought. If you are 'replacing file' then it is not the file you need to replace as it needs minifyling. Or you need to paste the contents of https://gist.github.com/Pathologic/e29ea9fffacf25f63ac4f12f3023b03b into the existing file: assets/plugins/tinymce4/tinymce/plugins/modxlink/plugin.min.js 
... or wait for the 1.4.5 to be release :-)

**Comment by wishbone-design** [comment]
I'm desperate. What did I do wrong?
Now I get this, with either minified (on bottom of the above site) or normal (on top of that site) js file (I always replaced the contents of the old plugin.min.js file):
![grafik](https://user-images.githubusercontent.com/3841564/42591490-1d17d274-8547-11e8-95d3-eb48f480d3e4.png)

**Comment by Pathologic** [comment]
@wishbone-design Try to add "modxlink" to editor plugins list.

**Comment by wishbone-design** [comment]
there are 2 files at https://gist.github.com/Pathologic/e29ea9fffacf25f63ac4f12f3023b03b . I tried both. May be installation mistake?

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/tree/1.4.x/assets/plugins/tinymce4
https://github.com/evolution-cms/evolution/blob/1.4.x/install/assets/plugins/tinymce4.tpl

**Comment by wishbone-design** [comment]
thx! what do I have to do with this?

**Comment by Deesen** [comment]
Are you sure you have replaced the content of both files, plugin.js and plugin.min.js, located in

`/assets/plugins/tinymce4/tinymce/plugins/modxlink`

with the content of these two? https://gist.github.com/Pathologic/e29ea9fffacf25f63ac4f12f3023b03b

**Comment by wishbone-design** [comment]
yes ... (( there is not even the line "Search in modX" any more...
Installinf of tiny MCE 4 already was a problem, so I don't dare to reinstall it.

**Comment by wishbone-design** [comment]
now I have the reason, but don't know how to fix it:
**TinyMCE4 doesn't find the modxlink plugin.**
When only placed "modxlink" in the "individual plugins list" in the configuration -> user, no link button appears at all. When put "link", the link button appears, showing the simple menu like above [https://github.com/evolution-cms/evolution/issues/750#issuecomment-404263582](url)

**Comment by wishbone-design** [comment]
@Pathologic, pls reopne the issue! 
I have new findings, see above

**Comment by dmi3yy** [comment]
Test on 1.4.7 all work 

<img width="437" alt="1234" src="https://user-images.githubusercontent.com/669491/50695028-31c00880-1044-11e9-97cf-d349e93b654b.png">

**Comment by wishbone-design** [comment]
sry for still bothering... 
modxlink doesn't appear
I replaced both files plugin.js and plugin.min.js
Modxlink is in the list of TinyMCE-plugins
-> I only see the raw "insert link"-window, no line "Search in EVO", no icon for images
![grafik](https://user-images.githubusercontent.com/3841564/50724700-f2e88c00-10f1-11e9-8d23-8be326c959df.png)
modX running v 1.2.1
Where else can I search for the mistake? must be minor

**Comment by dmi3yy** [comment]
Replace all TinyMCE 4

**Comment by dmi3yy** [comment]
And clear cache in browser

**Comment by wishbone-design** [comment]
TinyMCE has been modified and made already big problems installing so I don#t dare
must be something I forgotß everything is working only doesn#t fin modxlink
