### ISSUE TITLE
Any user manual

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#751]
Hi. does anyone have any basic form of a user manual of one of the more recent EVO versions e.g. 1.4.3 ? anything at all would be a help. we had a MODX user manual for the basics e.g. add a page, move a page, create a container - with diagrams but it is just too different from EVO now for a good while. or , is there a web page with some user manual help for end users?

thnaks

Gerard

**Comment by zorgsoft** [comment]
http://docs.evo.im/en/02_for_users/02_contentediting/10_resources.html

**Comment by fourroses666** [comment]
We have a Dutch one for our clients but I rather don't post the url here.

**Comment by AgelxNash** [comment]
You can found docs here http://docs.evo.im/en/ and also contribute here https://github.com/evolution-cms/docs/
