### ISSUE TITLE
Suggestion - Customize the action buttons

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#752]
Would be nice to have plugin event(s) so the action button menus could be customized, in a similar way to we can already alter the top menu with OnManagerMenuPrerender.
![untitled](https://user-images.githubusercontent.com/1744687/42277915-e6d61a2e-7f90-11e8-9177-e0b8f6d7d042.png)

**Comment by Pathologic** [comment]
It's possible with js:
![image](https://user-images.githubusercontent.com/3012304/42511556-dc544412-845a-11e8-81ac-d6ee6d7866b7.png)

**Comment by bossloper** [comment]
Ok. Which event are you using for this?

**Comment by Pathologic** [comment]
OnDocFormRender

**Comment by bossloper** [comment]
Thanks. I will have a go. I prefer server side solutions where possible, hence the new event request, but this will do for now.

**Comment by bossloper** [comment]
Problem is it is the overview page I wanted to alter the menu for not the edit document. There are no plugin events on document_data.static.php ?

**Comment by 64j** [comment]
use event OnManagerMainFrameHeaderHTMLBlock

```php
$e = &$modx->Event;

if ($e->name == 'OnManagerMainFrameHeaderHTMLBlock' && $_REQUEST['id'] && ($_REQUEST['a'] == 3 || $_REQUEST['a'] == 27)) {
	$id = $_REQUEST['id'];
	$output = "
		<script>
			document.addEventListener('DOMContentLoaded', function() {
				var menu = document.querySelector('#actions .btn-group');
				menu.innerHTML = '<a href=\"#\" class=\"btn btn-secondary\">OK</a>';
			});
		</script>
	";
	
	$e->output($output);
}
```

**Comment by bossloper** [comment]
thanks @64j
