### ISSUE TITLE
cookie context and lifetime

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#755]
The session lifetime is no longer context aware. This means a member login that uses a 'remember me' checkbox no longer remembers as only modx.mgr.session.cookie.lifetime is checked here: 
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/preload.functions.inc.php#L56

previously it also used to check for modx.mgr.session.cookie.lifetime
https://github.com/evolution-cms/evolution/blob/afd236cb0fc4e6656a453c79a7d69ed8ba289aed/manager/includes/preload.functions.inc.php#L22-L37

**Comment by Pathologic** [comment]
I don't understand, how it should work?

**Comment by bossloper** [comment]
The weblogin snippet sets a cookie modx.**web**.session.cookie.lifetime
https://github.com/extras-evolution/Weblogin/blob/master/assets/snippets/weblogin/weblogin.processor.inc.php#L345-L349

This is no longer being checked for. You can see the old code here: https://github.com/evolution-cms/evolution/blob/afd236cb0fc4e6656a453c79a7d69ed8ba289aed/manager/includes/preload.functions.inc.php#L23 when it did check for it.
Whereas now here with the current code:
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/preload.functions.inc.php#L56
it does not, it only checks for modx.**mgr**.session.cookie.lifetime.

**Comment by AgelxNash** [comment]
I find it wrong to assign the context of mgr a priority. Maybe we should just use **modx.session.cookie_lifetime**?

**Comment by Pathologic** [comment]
It's still not clear for me why core function should serve outdated WebLogin extra :smirk_cat:

**Comment by bossloper** [comment]
@Pathologic - how does the new login via formlister handle 'remember me' storage?

**Comment by Pathologic** [comment]
FomLister is just a form processor, so all these things are handled by a model class, modUsers is the default one in this case. modUsers class sets (and then updates) a special cookie (https://github.com/AgelxNash/DocLister/blob/master/assets/lib/MODxAPI/modUsers.php#L651), this cookie is checked by UserHelper plugin to perform autologin (https://github.com/AgelxNash/DocLister/blob/master/assets/lib/MODxAPI/modUsers.php#L525).

**Comment by bossloper** [comment]
Ok, if we are not supporting WebLogin going forward, then a couple of suggestions:

1) OutdatedExtrasCheck should not indicate updating WebLogin to be compatible.
2) Could the demo site also have the 'remember me' option added to the profile login page (it would help with a way to provide an easy demo of a full replacement for the old)?
3) Does the demo site 'logout' button work? it does not seem to for me. Or do I need a extra plugin that is not part of demo site?
![untitled](https://user-images.githubusercontent.com/1744687/42735165-48051fc0-8847-11e8-82e1-3631388ddc93.png)

**Comment by Pathologic** [comment]
@bossloper 
I don't know how to update demo site, so here is updated login page (id=4) with "remember me" checkbox:
```
[!FormLister?
&formid=`login`
&controller=`Login`
&loginField=`email`
&redirectTo=`49`
&defaults=`{"rememberme":1}`
&formControls=`rememberme`
&rules=`{
	"email":{
		"required":"Enter your Email",
                "email":"You should enter correct Email"
	},
	"password":{
		"required":"Enter your password"
	}
}`
&formTpl=`@CODE:

<p>In order to comment on blog entries, you must be a registered user of [(site_name)]. If you haven't already registered, you can <a href="[~5~]">request an account</a>.</p>

<form class="form-horizontal" method="post" action="[(site_url)][~[*id*]~]">
	[+form.messages+]
	<input type="hidden" name="formid" value="login">
	<div class="form-group [+email.classname+] row">
		<div class="col-sm-12">
			<label for="email">Email:</label>
			<input class="form-control" name="email" value="[+email.value+]" id="email" placeholder="Email">
		</div>
	</div>
	<div class="form-group [+password.classname+]">
		<div class="col-sm-12">
			<label for="password">Password:</label>
			<input type="password" class="form-control" name="password" id="password" placeholder="Password" value="[+password.value+]">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="rememberme" value="1" [+c.rememberme.1+]> Remember me
				</label>
			</div>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-8 col-xs-8 sign-in-block">
			<a href="[~37~]">Forgot Password</a>
		</div>
		<div class="col-sm-4 col-xs-4 login-button">
			<button type="submit" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-log-in"></i> Login</button>
		</div>
	</div>
	
</form>
`
&skipTpl=`@CODE:
	<div class="text-center">Hello!</div>
	<div class="text-center">
		<a class="btn btn-primary" href="[~49~]"> Edit profile</a> 
		<a class="btn btn-primary" href="?logout"> Logout</a>
	</div>`
&errorTpl=`@CODE:<p>[+message+]</p>`
&messagesOuterTpl=`@CODE:
	<div class="text-danger">[+messages+]</div>`
&errorClass=` has-error` 
&requiredClass=` has-warning`
!]	
```

Logout button works with UserHelper plugin enabled.

**Comment by Pathologic** [comment]
![image](https://user-images.githubusercontent.com/3012304/42752048-64b174ee-88f5-11e8-8781-f524f58caeb2.png)

**Comment by bossloper** [comment]
Thanks @Pathologic that worked. 
One problem. If I log in as a web user and also log in as a manager, then log out of the manager it also automatically logs out of the web user account.

The demo site profile page is set here:
https://github.com/evolution-cms/evolution/blob/1.4.x/install/setup.data.sql

**Comment by Pathologic** [comment]
>  If I log in as a web user and also log in as a manager, then log out of the manager it also automatically logs out of the web user account.

Because https://github.com/evolution-cms/evolution/blob/1.4.x/manager/processors/logout.processor.php destroys session completely.

I know where the demo site code is, but I don't understand how to edit this dump.

**Comment by Pathologic** [comment]
@dmi3yy please, update the demo site as it's mentioned above.
