### ISSUE TITLE
Renaming Manager directory: can't save some documents anymore

### ISSUE THREAD

**Issue by MadeInSwitzerland** [evolution-cms/evolution#759]
When I rename the /manager/ directory for security reason e.g. to /aEZH81264/ I can't change some of the documents anymore. When trying to save, I get an 403 error. If I rename it back to /manager/, everything is working again as expected.

**Comment by dmi3yy** [comment]
You change file ?   assets/cache/siteManager.php ?

**Comment by MadeInSwitzerland** [comment]
No, I just wanted to edit a normal template and when clicking save afterward I get the 403 error.

**Comment by dmi3yy** [comment]
You can send me access i check 

Dmi3yy@gmail.com

I think it will be faster

**Comment by MadeInSwitzerland** [comment]
Yes, I did also change siteManager.php

**Comment by Pathologic** [comment]
Is it solved?
