### ISSUE TITLE
Web Users not showing in Online Users

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#767]
A logged in web user (using DocLister login example from demo site) does not show in the 'Online Users' table, only Manager users are listed:

![untitled](https://user-images.githubusercontent.com/1744687/42943386-81bf063e-8b5a-11e8-99af-8ede9a03b3ea.png)

Is this by design as it used to show both in older MODX versions?

**Comment by Pathologic** [comment]
What's use of seeing web users there? It's possible to do with plugin.

**Comment by bossloper** [comment]
An existing site was upgraded and client asked why they were not listed anymore. But yes I could create a plugin, just wanted to check it was not a bug/omission from the login example.

**Comment by Pathologic** [comment]
I can add this function to UserHelper.

**Comment by Pathologic** [comment]
Done. https://github.com/Pathologic/FormLister/commit/f1c76f75db30b9988a2dda4271a432df0cb11b7f

**Comment by bossloper** [comment]
I don't think this quite works:
https://github.com/Pathologic/FormLister/blob/f1c76f75db30b9988a2dda4271a432df0cb11b7f/assets/snippets/FormLister/plugin.userHelper.php#L41-L46

Yes it adds to session tables, but the record is being overridden in the active_users table by the manager session record as it has the same sid. So if logged in as a manager and user it only displays one record instead of two.

**Comment by Pathologic** [comment]
Yes, it would be better to change the key, though tracking own activity both as a user and a manager looks like a kind of schizophrenia  :cat:
