### ISSUE TITLE
Do we need the evo logo in the images folder?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#771]
I always delete the EVO image in the images folder:
https://github.com/evolution-cms/evolution/blob/1.4.x/assets/images/evo-logo.png

When upgrading the EVO logo is in the images folder again.
Do we need that logo there?

----- 
Same for the "vendor" folder in the root. 
I don't use it and have to delete this every time.

**Comment by Pathologic** [comment]
The logo is used in demo site and vendor folder is used by some developers (like me).

**Comment by fourroses666** [comment]
Ah for the demo. Can we replace the EVO logo to an other location?
I mean, its on every install (150+ sites) on every update back in the images folder again. :(

Personally I think the developers have to add the folder and not an empty folder by default.

**Comment by Pathologic** [comment]
It's not empty, there are .htaccess and index.html (:

**Comment by fourroses666** [comment]
These I can understand although i remove the index.html when I see it.
