### ISSUE TITLE
conversion of the resource alias for german umlauts

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#772]
The automatic conversion of the resource alias does not work without errors. The German umlauts are not converted correctly: for example, ä becomes a, correct would be, ä becomes ae, ö becomes oe, ü becomes ue and ß becomes ss.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/43126745-43176176-8f36-11e8-93b1-3a64f38011c1.png)
