### ISSUE TITLE
Plugin - userHelper / PHP Parse Error

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#773]
Hi,

I use Doclister in one of my web page . (with pagination, uncache call)
Everythings fine. work well. 
But somethimes google search console message me that one of my web page can't crawl .
I checked it and that is the web page that Doclister snippet call include web page . 
And that web page can't access and show Http 500 error.

Check system events and found error like this : 

Plugin - userHelper / PHP Parse Error

![download 21](https://user-images.githubusercontent.com/9032715/43563030-23f8b9c2-9646-11e8-8e55-5fb9b39006d0.png)

**Comment by dmi3yy** [comment]
Check file in file system.

test on 1.4.4 and 1.4.5RC all ok
