### ISSUE TITLE
Slow Backend Login

### ISSUE THREAD

**Issue by rd2000** [evolution-cms/evolution#774]
If work the evolution cms server behind a proxy, the manager login works very slow. In my opinion, is this an issue with the modx security rss feed, because the feed function cannot get rss content from the remote url, if the webserver behind an proxy without direct internet access. For testing I have uncomment the line 75 `//$rss = @fetch_rss($url);` in `/manager/includes/rss.inc.php` and then the login works normal.

It would be an improvement if the backend provided proxy support for some functions like get rss feed content, or other function which need load remote content, or a manager settings whos could disable the RSS feed.

**Comment by dmi3yy** [comment]
You can in setting  delete: news and security url and all be ok 
also you can turn off  plugin updater
