### ISSUE TITLE
Не подключаются тв параметры для ресурсов

### ISSUE THREAD

**Issue by Tilivaldi** [evolution-cms/evolution#775]
Здравствуйте!

Скачал последнюю версию, установил без проблем.
Но вот тв-параметры не прикрепляются к ресурсам. Как будто их нет.
Ссылка на скриншоты
https://dropmefiles.com/PAZSN

Делаю на локальном хостинге XAMPP

**Comment by dmi3yy** [comment]
fix https://github.com/evolution-cms/evolution/pull/776
