### ISSUE TITLE
Roadmap for version 2.0?

### ISSUE THREAD

**Issue by janniconl** [evolution-cms/evolution#778]
Hello all,
Good to see Evo CMS is so activly maintained. Let me start to say I am very gratefull so many developers are still spending their free time for Evo CMS. However there have been a lot of changes recently, especially concerning the default plug-ins and their replacements (FormIt for Eform, DocLister for Ditto, Filters for PHx etc). I'm sure there are good reasons for this. On the other side, these new plugins sometimes lack the extensive documentation the old plug-ins had. (Although this old documentation is sometimes dissapearing aswell). 

And if there is documentation, it's mostly in Russian. Yes, I can use Google Translate, but it is still annoying. And I've seen multiple issues about this topic. It seems to me sometimes new elements/plugins are added faster then docs can be written. Especially code examples are very usefull when developing.
And lastly, most of the time I totally miss why things are changing so rigorously (why is the new plugin better?). Maybe that's because I am not involved enough, or not in the right chats or forums. Is there any place where we can follow the discussions about which path Evo should make? Or is that up to a few select people. (I know Github maybe isnt really the best place to talk about these things)

Occasionally there are discussions about these changes, like https://github.com/evolution-cms/evolution/issues/176

I am also reading about big changes for version 2.0 and rewriting everything with Laravel. Why is this done? And what will become of the support for older installations. Myself - and a lot people with me - maintain multiple installations for a range of clients. If I can expect installations to break heavily in the future, I must reconsider if I am going to keep using Evo CMS in the future.  Especially for new projects.

In #176 @nick0 says:
> I agree wholeheartedly with the sentiments above about maintaining backward compatibility and community involvement / consultation. I am all for progress and improvements and new ways of doing things for new projects, but the new Evolution has to work for existing MODx Evo 1.2.1 websites. Its not progress if the sites break on install. It's evident that many people are really passionate about Evo. Lets keep it that way.

I hope this quote is on everyones mind when working on Evo CMS. If development is done by a small team - who only create and build for their own pleasure of making a hip and fancy CMS (I am not saying people do right now!) and without documentation or transparancy/community support - I foresee a dark future for Evo CMS.

But let's stay on the bright side. :-) The current version of Evo CMS is still a joy to work with, it's very stable and it ables you to make almost everything you can think of.  I am a happy Evo user, have been for many years, and hope to be for even more years to  come. I am not contributing as much as others, it's free software, so I know I can't ask for everything. I can only hope. Hope you guys can take away some of my concerns.

I am wondering, is there any roadmap voor 2.0? (@dmi3yy ?) Why are we changing to Laravel? Will legacy plugins and my own snippets/plugins/customizations still work? So far I've been able to follow versions pretty well. But I fear a bit for the future. Thanks!

**Comment by dmi3yy** [comment]
Now we build new  EVO.im after finish it will be one site for multilang community EVO. 

About laravel components its open for EVO: 
- we can use all exstras from laravel in evo, its lot of ready components.
- we are working to keep them backward compatible and that all old sites could be upgraded to 2.0 without much effort

the evolution does not involve revolutions and complex transitions, so this is one of the most important moments. 

Now you can update any version of Evo from 0.9.6 to 1.4.5 without problems. And this one of the important rule for EVO. 

About why we start 2.0 on Laravel and about roadmap i write on first beta release.

**Comment by dmi3yy** [comment]
Sorry, but now my english not good and this problem and reason why we have bad documentation and description for English. 

After beta realise i will start write new documentation and lesons with new features and will write on English too.

**Comment by pmfx** [comment]
@janniconl there is an EVO Slack here https://evocmf.slack.com/ I can send you an invitation if you want.

**Comment by Cipa** [comment]
I was thinking about writing an Eloquent model for the document data, maybe others, not sure if needed though
Let me know how I can help with 2.0.

**Comment by dmi3yy** [comment]
All models here: https://github.com/evolution-cms/evolution/tree/2.x/core/src/Models

**Comment by AgelxNash** [comment]
@pmfx Send me an invitation modx@agel-nash.ru

@Cipa Models are already available, the relationship is added as necessary. The primary task is to rewrite the administration panel using the blade and models. Next we will optimize the core.

**Comment by AgelxNash** [comment]
## Why there is no documentation in English
My knowledge of English at the level of Google Translate. And this is a huge problem. Possible the community is able to accept this, but I am ashamed to write documentation in such a language. Until now, I hope someone can help with the translation.

## How are new plugins/snippets better than old?
Many old plug-ins and snippets use outdated development methods. New more flexible, but complicated to understand. This is not bad, you only need time to study. If earlier you needed to deal with the MODX syntax, now the emphasis is on PHP. PHP knowledge will be useful to all members of the community more than knowledge of MODX tags.
	
## Why is being rewriting everything with Laravel
- This framework has a large community and is actively developing
- Documenting becomes easier and more with https://laravel.com/docs/5.6
- Framework components work fine separately. This allows us to embed only what we need into the 
Evolution core. If necessary, it will be easy to add the missing component even on a working project (without any conflicts or errors).
- This all will allow you to do small sites and large projects.
- Solve the problem of teamwork development (git, migration, composer, etc...)
	
## What will happen with the support of old installations and compatibility of old plug-ins
- The code is developed to maintain backward compatibility and add support for Laravel. You can check it now by installing branch 2.x
- Some classes have been renamed, but this have backward compatibility patch. For example: [manager/includes/document.parser.class.inc.php](https://github.com/evolution-cms/evolution/blob/2.x/manager/includes/document.parser.class.inc.php#L8) => [core/includes/legacy.inc.php](https://github.com/evolution-cms/evolution/blob/2.x/core/includes/legacy.inc.php#L3-L4)
- We understand that backward compatibility is very important and tried to give maximum attention to this issue. But the help of the community is needed to test and get FeedBack.
- After the release of 2.x, support for the 1.4.x branch will be discontinued. Only bugs and vulnerabilities will be fixed.

**Comment by AgelxNash** [comment]
@Cipa You could help with rewrite the SQL code from DBAPI to Eloquent like PR #835

DBAPI also works throw [agelxnash/modx-evo-database](https://github.com/AgelxNash/modx-evo-database) package. But it's doesn't support the work of observers like this [/core/src/Observers/SiteContentObserver.php](https://github.com/evolution-cms/evolution/blob/2.x/core/src/Observers/SiteContentObserver.php)
