### ISSUE TITLE
Evo 1.4.4 - update message & button

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#781]
Hello,
all my Evo installations are running on version 1.4.4
Now the version 1.4.5 is available.
In some installations the message about the outdatet version is displayed and the update button is displayed. the update can be comfortably started and executed in the manager.

In some installations this message and the button will not be displayed.
the package "updater 0.8.4" is installed in all installations.

is there a setting that needs to be activated additionally?
I have no idea why this different behavior occurs.

Thanks

**Comment by pmfx** [comment]
Try clearing site cache and then go to/reload Dashboard/Welcome page.

**Comment by ArnoNymeier** [comment]
ok, that's it!
thanks for the fast information.

**Comment by pmfx** [comment]
You're welcome :)
