### ISSUE TITLE
File manager path incorrect

### ISSUE THREAD

**Issue by deep-blue81** [evolution-cms/evolution#782]
After updating the website from an older version on Evo, I keep getting the warning:
"File manager path may be incorrect".

Everything works, except when tiying to insert an image or a link to a file from tinymce4: the path of the image or file you pick from KCFinder is malformed, and begins with: 

`%5B(base_path)%5D/assets/images/`  instead of the correct:  `/assets/images/`.

Of course, the resulting URL for images or files wil be broken.

I already tried the following: 
- updated Evolution to the latest version (1.4.5)
- reset the file manager path to the default [(base_path)] 
- removed tinymce (all versions), and reinstalled it (version 4.3.7)
- checked config.inc.php for anomalies (the code part checking for base_path is the same in other websites with same hosting, with no problems)
- in users > user settings I set the file manager path to [(base_path)]

Any help woulfd be greatly appreciated
thanks

**Comment by sashabeep** [comment]
Looks like it must be referenced to https://github.com/evolution-cms/evolution/issues/784
Maybe, some filtering functionality was added to configuration fields to prevent xss or so.
Quick and dirty fix - change it in DB using PHPMyAdmin or provide full path to field using simple script in site root
```php
echo getcwd();
```
db table prefix_system_settings
fields:
- rb_base_dir - assets folder ending with "...assets/"
- filemanager_path - document root ending with "...site.tld/"

**Comment by deep-blue81** [comment]
Thanks for your help. 
In the end, I solved the problem by setting [(rb_base_url)] to "/assets/".
I don't really get what was going on, but now it works.
