### ISSUE TITLE
Template Variable in Menu Bar doesn't render after upgrade to 1.4.5

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#783]
Hi All,
I have a template variable [*Login*] assigned to my template.  It has an EVAL to assess whether the user is signed in or not.

@EVAL if ($modx->getLoginUserID()) return 'Logout'; else return 'Login';

It worked well until I upgraded to v1.4.5.  I dhecked my DLMenu snippet parameters and it shows the code for the menu item along with the TV name.  Unfortunately it just have no text (blank) when rendered to the page.

Is there a setting I'm missing in the new build?

Thanks,
Chris

**Comment by bossloper** [comment]
Try @EVAL in uppercase, though this was not a recent (1.4.5) change it goes back to 1.1.x sometime, I don't remember exactly when. So maybe you upgraded from a very old modx version?

**Comment by BBloke** [comment]
I checked and it is on the site.  Must be copy and past on here which has set it to lowercase.  I keep modx up to date pretty much as soon as the new release hits. Definitely stopped from 1.4.4 to 1.4.5.

`@EVAL if ($modx->getLoginUserID()) return 'Logout'; else return 'Login';`

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/43995212-ba68d13a-9db2-11e8-8aa8-e181f4db9f5e.png)


![image](https://user-images.githubusercontent.com/4653189/43995214-c49d7d4a-9db2-11e8-9b7d-ca392e7bcbb6.png)

**Comment by BBloke** [comment]
Hmmm. Thank you for posting.  That is exactly what I have in my TV and it still doesn't work at my end.

I'm using DLMenu to produce the menu whilst a quick check using Wayfinder works.

DLMenu outputs the link but not the Text in the TV although DLMenu debug shows the TV name in the output to be rendered.  I don't think it's the EVAL code as I replaced the default text with "Login" and it still did not show up.

Here's my DLMenu code:
`[[DLMenu?
			&debug=`0`
			&parents=`0`
			&depth=`1`
			&filters=`private`
			&parentClass=`hideentry`
			&selfClass=`current`
			&innerTpl=`DL_innerTpl`
			&outerTpl=`DL_outerTpl`
			&parentRowTpl=`DL_parentRowTpl`
			&rowTpl=`DL_rowTpl`
		]]`

This gives the HTML code as:

> <li class="menu-item menu-item-type-custom menu-item-object-custom current_page_item menu-item-home menu-item-top-level menu-item-top-level-1 current-menu-item">
	<a href="/login" title=""></a>
</li>

This is consistent on 3 websites. One site was built from scratch starting at 1.4.4 and upgraded to 1.4.5.
2 sites are hosted on a commercial NAS linux box and one site hosted on windows running apache/php.  I've tried cached and uncached. I've ensured the TV is available to the template.  Placing the TV in the template works.

I feel there is something I'm missing.

I don't think this has been answered sufficiently to close?

**Comment by 64j** [comment]
@BBloke 
http://docs.evo.im/en/04_extras/dlmenu.html
use **prepare**

**Comment by BBloke** [comment]
Thank you 64j.  I look in the documents for about a couple of hours.  I got myself in quite a spin! Don't ask but it looks like it is working although I'm really not sure why or how.

Long story short. I tried using `documents` and moved menu items around on one site and it worked when the menu was in a container and listed documents.  Although, if I used parents on the root it wouldn't show! 

I tried it on the last site I built and it's working in both cases, root and subfolder when using `documents`.

I think perseverance wins the day rather than understanding why it works!

Thank you again.

**Comment by BBloke** [comment]
Maybe typed too soon.  Back to the drawing board!

**Comment by BBloke** [comment]
This may help.  
I signed out of my site and the template variable showed the correct "Login" result to the EVAL.
When I sign in the TV doesn't render.  No Text from the EVAL.

**Comment by BBloke** [comment]
Not as would be expected.

When I'm signed out my menu bar shows "Login".  I have a page with a Wayfinder call and a DLMenu call showing the same menu list.

The list reads as I would expect.  "Login" is there for the relevant page. So my menu and 2 page menu options work.

**When I sign in.**
My Menu doesn't show any text from the TV.
My Wayfinder snippet call renders as expected "Logout"
My DLMenu in the page snippet doesn't show any text from the TV.

I tried the following:

TV code: @modx->getLoginUserID();
Result: 
Wayfinder snippet rendered as text "$modx->getLoginUserID();".
DLMenu rendered it empty.

TV code: @EVAL $modx->getLoginUserID();
Result:
All 3 locations rendered it empty.

TV code: @EVAL global $modx; if ($modx->getLoginUserID()) return 'Logout'; else return 'Login';
Result:
Wayfinder rendered correctly
DLMenu rendered it empty.

My pages are uncached and I have called my snippets both via [[ and [!

It would appear that $modx->getLoginUserID() is not getting anything returned at some point!

**Comment by BBloke** [comment]
I added Ditto to my page calls and it renders fine.  Something in DLMenu and/or DocLister is causing the issue?! Surely.

**Comment by bossloper** [comment]
If TV code is just text e.g. abc 
does DLMenu return anything? I added a tv to a text DLMenu and it works ok in 1.4.5.

**Comment by BBloke** [comment]
If I make the TV just text then there is no text in DLMenu but Wayfinder and Ditto display it correctly.

The debug code on DLMenu shows the correct code out put of the menu item.  It has the [*loginName*] TV name I'm using.

When it comes to displaying it on the screen the area that code is in is just blank.

**Comment by BBloke** [comment]
It's all good fun til something comes along and spoils the party.

Here are my 4 calls in my home page:

`[!Wayfinder? &startId=`0` &textOfLinks=`longtitle` &titleOfLinks=`description` !]

[!DLMenu? &documents=`4,37` &filters=`private` &tvList=`loginName,Login`&renderTV=`*` &filters=`private`&textOfLinks=`longtitle` &titleOfLinks=`description` !]

[!DLMenu? &parents=`0` &filters=`private` &tvList=`loginName,Login`&renderTV=`*` &filters=`private`&textOfLinks=`longtitle` &titleOfLinks=`description` !]

[!Ditto? &parents=`0` &depth=`3`!]`

As documented Wayfinder and Ditto work as intended.

Notice the 2 DLMenu calls.  One using parents and one using documents.

Usage of parents parameter doesn't work.

Usage of documents parameter does work.

Odd but I hope it's helpful.

**Comment by BBloke** [comment]
I think I have it.  

Whilst I have upgraded from every release of Evo on my test site and made a new site at 1.4.4 and upgraded it.  It would appear the version of DocLister on the my test site is 2.3.15 whilst the extras shows 2.3.16.  Updating the code has corrected the issue.

There wasn't an out of date plugin warning but I thought I'd check out of curiousity.

Would seem that snippet code not being completely up to date was the issue.

Sorry to have posted so much but maybe v1.4.5 ships with DocLister 2.3.15?

**Comment by bossloper** [comment]
Glad you sorted it. Though my test site is v1.4.5 and runs DocLister 2.3.15 ... and the TV test was rendering correctly. Maybe you had a bad install of DocLister 2.3.15.
Just out of curiosity, if you downgrade to DocLister 2.3.15 does it break it again?

**Comment by BBloke** [comment]
Thanks bossloper.  

Downgrading would appear to be working too.  The only difference I can think of is I used the dashboard updater to upgrade.
