### ISSUE TITLE
site_name without german Character Set 

### ISSUE THREAD

**Issue by mediengaarage** [evolution-cms/evolution#784]
In Evolution 1.4.5, the site_name appears in the backend without any special characters. In the frontend it is shown correctly.
Backend:  f &uuml ;r
Frontend: für

**Comment by sashabeep** [comment]
+1 to this!
utf-8 characters in site_name converted to &mnemonics after update

![2018-08-21 14 54 45](https://user-images.githubusercontent.com/5689796/44399964-2ca96380-a552-11e8-99bb-35fc914f8353.png)

**Comment by AgelxNash** [comment]
It's not funny anymore. We continue #727 :-)

**Comment by sashabeep** [comment]
> It's not funny anymore. We continue #727 :-)
Чтобы понять рекурсию нужно понять рекурсию...
