### ISSUE TITLE
Evo 1.4.5 PHP 7.1.3 what about PHP 7.0

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#785]
Hi All,

I noticed the latest release is required to use PHP 7.1.13 or above.  I'm still using 7.0 with no issue.  Should I really update to 7.1?  I'm happy to keep my install as is and wait until something stops working.  Just thought I'd ask the question.

Thanks,
BBloke

**Comment by 64j** [comment]
@BBloke 
Requirements raised for version Evo 2.x

**Comment by BBloke** [comment]
Thanks @64j

**Comment by 64j** [comment]
@BBloke 
Describe the problem more

**Comment by BBloke** [comment]
When trying to access the home page of my site due to my configuration I get "Error" displayed and the system event shows:


Event Id: | 0 | Source: | Parser - $docgrp = implode(",
-- | -- | -- | --
Date: | 15-08-2018 11:20:37 | User: | chris
Trying to get property of non-object« Evo Parse Error »Error : implode(): Invalid arguments passedError informationErrorType[num]WARNING[2]File \modx\manager\includes\document.parser.class.inc.phpLine2610Source$docgrp = implode(",", $docgrp);Basic infoREQUEST_URIhttp://domain.co.uk/modx/Resource[1] HomeRefererUser AgentMozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36IP10.132.50.10Current time2018-08-15 10:20:37BenchmarksMySQL0.0143 s (2 Requests)PHP0.0581 sTotal0.0724 sMemory3.6318283081055 mbBacktraceDocumentParser->executeParser()index.php on line 139DocumentParser->prepareResponse()manager/includes/document.parser.class.inc.php on line 2862DocumentParser->getDocumentObject('id', 1, 'prepareResponse')manager/includes/document.parser.class.inc.php on line 2933implode(',', 124423323566899891111)manager/includes/document.parser.class.inc.php on line 2610 | ErrorType[num] | WARNING[2] | File | \modx\manager\includes\document.parser.class.inc.php | Line | 2610 | Source | $docgrp = implode(",", $docgrp); | REQUEST_URI | http://domain.co.uk/modx/ | Resource | [1] Home | Referer |   | User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 | IP | 10.132.50.10 | Current time | 2018-08-15 10:20:37 | MySQL | 0.0143 s (2 Requests) | PHP | 0.0581 s | Total | 0.0724 s | Memory | 3.6318283081055 mb | DocumentParser->executeParser()index.php on line 139 | DocumentParser->prepareResponse()manager/includes/document.parser.class.inc.php on line 2862 | DocumentParser->getDocumentObject('id', 1, 'prepareResponse')manager/includes/document.parser.class.inc.php on line 2933 | implode(',', 124423323566899891111)manager/includes/document.parser.class.inc.php on line 2610

ErrorType[num] | WARNING[2]
File | \modx\manager\includes\document.parser.class.inc.php
Line | 2610
Source | $docgrp = implode(",", $docgrp);

REQUEST_URI | http://domain.co.uk/modx/
Resource | [1] Home
Referer |  
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
IP | 10.132.50.10
Current time | 2018-08-15 10:20:37

MySQL | 0.0143 s (2 Requests)
PHP | 0.0581 s
Total | 0.0724 s
Memory | 3.6318283081055 mb

DocumentParser->executeParser()index.php on line 139
DocumentParser->prepareResponse()manager/includes/document.parser.class.inc.php on line 2862
DocumentParser->getDocumentObject('id', 1, 'prepareResponse')manager/includes/document.parser.class.inc.php on line 2933
implode(',', 124423323566899891111)manager/includes/document.parser.class.inc.php on line 2610


That's the error from modx.  I do have DLMenu and DocLister.  I searched the php files for the the line of code but it showed in more locations.

I will try and get a dev site running with 7.1 so I can have a look to see what's what.

BBloke

**Comment by BBloke** [comment]
My current template allows the page to show error free when I'm not signed in.  As soon as I sign in the error appears.

I have removed any snippet, TV, placeholder, chunk.  Disabled any plugin I think could impact the page output.  The error remains.

I've changed the home page template to "blank" and EVO Bootstrap and the error is shown. 

There's nothing I can see in my page/template that is possibly causing the issue but it does appear to be "signed in" relevant.

**Comment by BBloke** [comment]
Our hosts are changing to PHP7.2 this month so I tested the site out with 1.4.5.  It all works on their system.

On our in-house server I got the error until I made the following changes in my http.conf

`#LoadFile libea32.dll
#LoadFile libpq.dll`

**Comment by BBloke** [comment]
Seems my host is advancing to php 7.2.  I have an option in the short term to stick with php 7.0 but a switch over is close.

I've test their 7.2 and our main website performs ok with one exception. eForm. This is due to the way count performs on non-countable entities.

I think a change to 7.2 is going to cause issues for quite a few of us.
I'm still struggling to figure out why my installation does not work on 7.1 or 7.2. The manager is fine.  My website, even with a blank template and no DocLister or DLMenu calls running it is not.

Some help or advice would be appreciated.

Thanks,
BBloke

**Comment by BBloke** [comment]
Would appear WebLoginPE is the cause of the error.

**Comment by BBloke** [comment]
but only after logging in.

**Comment by BBloke** [comment]
Changing line 2610 from 
`$docgrp = implode(",", $docgrp);`
to
`$docgrp = implode(",", (array)$docgrp);`

cures the issue I'm having on that.  eForm "count" still needs attention.

**Comment by user83743** [comment]
Hi

I tried evo 1.4.2 with 7.2 and the site is fine except for eform. i upgraded to 1.4.5 evo and the same thing:

Error : count(): Parameter must be an array or an object that implements Countable
Error information	
ErrorType[num]	WARNING[2]
File	/home/xxxxxxxxxxxx/public_html/xxxxxxxxxxxxx.com/assets/snippets/eform/eform.inc.php
Line	700
Source	$lastitems[count($lastitems)]="[+$name+]";



Backtrace
DocumentParser->executeParser()
index.php on line 139
DocumentParser->prepareResponse()
manager/includes/document.parser.class.inc.php on line 2862
DocumentParser->parseDocumentSource(string $var1)
manager/includes/document.parser.class.inc.php on line 2971
DocumentParser->evalSnippets(string $var1)
manager/includes/document.parser.class.inc.php on line 2713
DocumentParser->_get_snip_result(string $var1)
manager/includes/document.parser.class.inc.php on line 2025
DocumentParser->evalSnippet(string $var1, array $var2)
manager/includes/document.parser.class.inc.php on line 2113
eval()
manager/includes/document.parser.class.inc.php on line 1962
require(string $var1)
manager/includes/document.parser.class.inc.php(1962) : eval()'d code on line 1
eForm(DocumentParser $var1, array $var2)
assets/snippets/eform/snippet.eform.php on line 114
formMerge(string $var1, array $var2)
assets/snippets/eform/eform.inc.php on line 659

**Comment by user83743** [comment]
thanks Dmytro

**Comment by BBloke** [comment]
Thank you
