### ISSUE TITLE
Accessing a restricted page form an external weblink

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#786]
This is something that goes back to the earlier day s of Modx.  I think v0.9.  I think it still occurs whilst I'm not sure whether it has something to do with WebLoginPE now and/or whether WebLogin works better.

I use WebLoginPE for sites which require restricting access.  If I send a link in an email to a restricted page the link always ends up taking the user to the home page.  

I believe the site course of action is to check page access. 
Bounce the access because it doesn't believe the user has logged in.
Redirect to the home page which shows me as logged in.

If I'm already on the site and click the same external URL link I end up going directly to the page I desire.

It as though the log in check occurs after the page request hence the bounce.

Is it something that will remain or has it been something that has been corrected. 

IIRC If I'm logged out and try the page I can log in and it automatically continues to the page I was looking for.

BBloke

**Comment by dmi3yy** [comment]
Use for than System setting for set **Unauthorized page** and in snippet use referal link and do correct redirect )
