### ISSUE TITLE
evo 1.3.2 update + MultiTV issue

### ISSUE THREAD

**Issue by thalegion** [evolution-cms/evolution#79]
After auto-update to 1.3.2 MultiTV on document page stop working.
In console appeared next error: 
![image](https://user-images.githubusercontent.com/16190128/28404180-f959d8fc-6d30-11e7-9205-a0592e87f4f1.png)

**Comment by dmi3yy** [comment]
Its bug on multiTV 
Fixed in last version multiTV

**Comment by dmi3yy** [comment]
https://github.com/extras-evolution/multiTV/commit/aac34d9d06b96a231773399b86951eda9b776bad
