### ISSUE TITLE
Множество одинаковых запросов при отмене "Участвует в URL"

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#790]
Если скрыть ресурс из url, то метод [getHiddenIdFromAlias](url=https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L6481-L6504) генерирует множество одинаковых запросов (их количество равно как минимум количеству вложенных детей первого уровня). В моем случае 28 одинаковых запросов - http://joxi.ru/8AnaERYfj8NvP2 . Одинаковые они потому, что при рекурсии используется $child['id'], а должен, по идее $child['child_id'] - https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L6496 - но это не решает общую проблему, т.к. количество запросов может только вырасти.

**Comment by webber12** [comment]
3 на скрине - это как раз id скрытого из URL ресурса.

**Comment by mnoskov** [comment]
Непонятно, какая структура документов?

**Comment by webber12** [comment]
Тут 2 момента: запросов "много" и запросы "одинаковые".

Пока основная претензия ко второй части, которая от структуры особо зависеть не должна. Т.е. количество запросов определяется количеством вложенных документов, но вот то, что запросы одинаковые - это ошибка логики, при которой вместо $child['child_id'] используется в рекурсии постоянная величина  $child['id'].

При небольшом сайте эта проблема и не заметна и была замечена только когда у меня в папке "товары" оказалось 42 тыс товаров, и эта папка оказалась вложена в папку каталог со скрытым урл. Вот тут-то и посыпались странности в виде очень медленного открытия тестового ресурса в корне с пустым шаблоном.

**Comment by mnoskov** [comment]
Если вместо `id` использовать `child_id`, алгоритм будет перескакивать через ресурсы, это уменьшит кол-во запросов, но проблемы не решит + добавит новых.

Проблему одинаковых запросов можно решить довольно просто - запоминая уже сделанные.

А вот то, что сначала проверяется все дерево вглубь, потребует переделки алгоритма, чтобы он работал "послойно", т.е. сначала первый уровень, затем второй и т.д. - это будет логичнее.

**Comment by mnoskov** [comment]
Вот решение для удаления одинаковых запросов:
https://github.com/mnoskov/evolution/blob/patch-3/manager/includes/document.parser.class.inc.php#L6490-L6499

**Comment by webber12** [comment]
Там логика совершенно не такая, насколько я вижу. Посмотри скрины хоть для начала :)

**Comment by webber12** [comment]
Зачем мне "быстрое решение", если есть баг в логике парсера, когда вместо того, чтобы идти вглубь родителя он гоняет один и тот же запрос столько раз, сколько детей с вложенными ресурсами в нем есть. Если это так и задумано, то пусть так и остается :)

**Comment by Pathologic** [comment]
@webber12 проверь исправление

**Comment by webber12** [comment]
Иногда работает, но чаще глючит :) Мне показалось, срабатывает иногда правильно только из-за вот этого https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L2798 или вот этого https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L6512-L6514 - но когда доходит до самого метода (т.е. конечный документ, который вложен в папку со скрытым урлом и которого нет в documentListing) то сам по себе метод работает неправильно и получается 404

**Comment by mnoskov** [comment]
Если у конечного документа родитель скрыт из урла, то сам конечный документ должен попасть в кеш, и до этого метода не дойдет.

**Comment by webber12** [comment]
Так я про то и говорю - для тех, что попадают в кэш работает нормально и за счет совершенно другого метода. А для тех, кто не попал - перестало работать и именно из-за этих правок в getHiddenIdFromAlias, т.к. со старой версий хоть и дает много левых одинаковых запросов, но хотя бы корректно в итоге выводит страницу. В общем, тут надо продумать логику в принципе, т.к. она какая-то немного корявая, мне кажется.

**Comment by mnoskov** [comment]
Кеш в данном случае - это documentListing.
Видимо имеет смысл еще раз спросить, какая структура документов и какие из них скрытые и нет? И для каких метод не работает?

**Comment by mnoskov** [comment]
Если этот документ есть в documentListing, как он может быть 404? Даже если так, то это значит, что в первую очередь не сработал именно кеш. К слову, у меня такая структура работает без ошибок.

При включенной настройке aliasListingFolder в кеш documentListing попадают документы которые либо являются папкой, либо те, у которых родитель скрыт из урла. Вот что было по этой теме: https://github.com/modxcms/evolution/issues/1326. Было еще развернутое обсуждение, но я уже не смог его найти.
