### ISSUE TITLE
Uncache Doclister + phpthumb call often occur HTTP 500 error

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#795]
I call this snippet from chunk , eg root.

[!DocLister?
&tvList=`post-image`
&display=`3`
&summary=`notags,len`
&dateSource=`pub_date`
&parents=`[*id*]`
&id=`list`
&tpl=`ditto_root`
&sortBy=`id`
&sortDir=`DESC`	
!]

When I call {{root}} from cache page , HTTP 500 error occur often, not always.
But I restart my apache server , problem solve.  
no error  in apache log.
Before Doclister , I used Ditto with no problem.

evo version : 1.4.5
hosting : Digital ocean , ubuntu 14.04 , apache 2.1, php 7.0

**Comment by mgzawlinoo** [comment]
I use phpthumb cache call in Doclister template chunk : ditto_root

<li><a href="[~[+id+]~]">
<img src="[[phpthumb? &input=`[+tv.post-image+]` &options=`w=250,h=175,zc=1,bg=FFFFFF`]]"  width="250px" height="auto" border="0" />
</a>
<b style="display:block">[+pagetitle+]</b>
</li>

**Comment by 64j** [comment]
@mgzawlinoo 
Please make correct code snippets.

```
[[DocLister?
&parents=`0`
&tvList=`image`
&prepare=`dl.prepare`
&tpl=`@CODE:
<img src="[+tv.image.thumb+]"> 
[+pagetitle+]`
]]
```

Snippet **dl.prepare**

```php
<?php
$data['tv.image.thumb'] = $modx->runSnippet('phpthumb', array(
	'input' => $data['tv.image'],
	'options' => 'w=480,h=320,zc=1,bg=ffffff'
));

return $data;
```
