### ISSUE TITLE
Question regarding editing permisions 

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#796]
Is there info somewhere, or can somebody explain how, in the manager I can either hide or make resources only editable by the admin.

There are a few pages that I would prefer a normal user not change.

**Comment by bossloper** [comment]
In Manager access permissions:

- create a user group: e.g. 'Admin Group'
- create a resource group e.g. 'Admin Docs'
- link 'Admin Group' to 'Admin Docs'
- for your admin manager edit and add the 'Admin Group' access permission

then any resource you wish to restrict to admin manager add the 'Admin Docs' access permission to that resource.

**Comment by risingisland** [comment]
Thank you @bossloper , I thought I had tried that, but it made the doc unavailable in the front-end.
Will try again to see which step I missed.

**Comment by risingisland** [comment]
Is it possible to lock a parent, but allow children to be edited?

**Comment by bossloper** [comment]
Make sure you are setting 'Manager access permissions' and not 'Web access permissions'.

RE: Is it possible to lock a parent, but allow children to be edited?
- yes, though resource permissions are inherited so if you later added a new child  resource it would by default be similarly 'locked' unless you change the permission on the new resource.

**Comment by risingisland** [comment]
If I lock a parent/container, it hides it from a normal user, therefor they can not edit its children.
Can it be locked, but not hidden?

**Comment by bossloper** [comment]
Set 'Show protected pages' to yes in 'system config' -> 'interface and features'

**Comment by risingisland** [comment]
Perfect, Thanks for all the info.
