### ISSUE TITLE
CategorizedTabs plugin not working with new dropdown theme

### ISSUE THREAD

**Issue by pmfx** [evolution-cms/evolution#8]
"CategorizedTabs" - one of my all time favorite plugins - works fine with "MODxRE2" but have problems with "MODxRE2 DropdownMenu" theme in 1.2.2. 

Resource page is covered with mask div and TVs are not moved into tabs. 

Would someone be so kind and look into it? This plugin highly depends on Javascript and DOM and there was a lot of changes in new manager dropdown theme. So there is a problem somewhere there with HTML or JS.

**How it should look:**

![screenshot_1](https://user-images.githubusercontent.com/10888055/28091790-864b93c8-6691-11e7-8d4f-091c9164284a.jpg)

**Bug:**

![screenshot_3](https://user-images.githubusercontent.com/10888055/28091801-8edfdeea-6691-11e7-9617-37111ee43a0e.jpg)

**Plugin code:** https://github.com/pmfx/CategorizedTabs

BTW: To be honest it would be cool to have this plugin features in the core as system settings. This was a part of "Categories Manager" by the same author.

**Comment by 64j** [comment]
https://github.com/64j/CategorizedTabs/commit/5f799b0e4b93a50c8adfe821310fbb8dd2e82242

Issues closed?

Вопрос решён, можно закрывать?

**Comment by pmfx** [comment]
Yup. Many thanks for this!
