### ISSUE TITLE
Using PHP 5.5.38  = < 5.6

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#80]
Is it a problem when using PHP 5.5.38 ?
When having a quick look I have allot of websites PHP < 5.6

**Comment by dmi3yy** [comment]
FormLister used 5.6 all other use 5.4  now detailed write on readme

**Comment by dmi3yy** [comment]
this better for understandable )
![img](http://take.ms/xMBNr)

**Comment by fourroses666** [comment]
Yes thanks :)

**Comment by fourroses666** [comment]
Shall we add the Slack channel? 
https://evocmf.slack.com
And how to get invited/account?

**Comment by dmi3yy** [comment]
yes 

https://join.slack.com/t/evocmf/signup

**Comment by fourroses666** [comment]
Slackchannel still needs to be added in the readme :0

**Comment by Nicola1971** [comment]
Besides FormLister (need 5.6), whats new in 1.3x that needs php 5.4.0 instead 5.3? 
what will not work if i force to install on a 5.3? (editing action_summary.php) 
I have a customer on a shared hosting and he cant update now

actually i'm testing on a dev site with 5.3 dont not see any issue

**Comment by Pathologic** [comment]
@Nicola1971 5.6 is the last officially supported version of 5.* branch, and that's the main reason to stop using earlier versions.

**Comment by Nicola1971** [comment]
so, just not tested on previous php version?

**Comment by Pathologic** [comment]
@Nicola1971 yes, it's not tested.
