### ISSUE TITLE
Управление элементами "падает" при большом количестве элементов

### ISSUE THREAD

**Issue by mp3moto** [evolution-cms/evolution#802]
Я обновил CMS с версии 1.0.х. Суммарно у меня 363 элемента (246 чанков, остальное - шаблоны, TV, сниппеты и плагины). При вызове окна "Управление элементами" центральный iframe возвращает Empty responce. Если чанки удалить - проблема уходит.

**Comment by mp3moto** [comment]
Похоже, сначала должно прогрузиться до конца dropdown меню "Элементы". Если подождать около 5 секунд после его открытия - проблема уходит.

**Comment by 64j** [comment]
@mp3moto 
В конфигурации измените параметр **Количество результатов**, например на 10 для начала.
