### ISSUE TITLE
TineMCE4 change file upload max size ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#803]
Hello,

Where I can change max file upload size limit ?
My tinyMCE4 in Evo 1.4.5 can't upload 10 mb PDF file.

**Comment by fourroses666** [comment]
I think its a limit on server side. 

Maybe with the filemanager

**Comment by bossloper** [comment]
There is a setting in Evo 'system configuration' -> 'file manager' -> 'Maximum upload sized'. Default is 10485760 bytes.

**Comment by modwebpl** [comment]
PHP.ini allows to 64 mb upload size.

Why we can't edit this settings " 'system configuration' -> 'file manager' -> 'Maximum upload sized'" via CMS ? : o
