### ISSUE TITLE
What is wrong with EVO DB API  ?

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#805]
Hello,

I'm working on Evo 1.4.5

What is wrong with this code? (I put them as snippet), I have 200+ records in "table2" but this code:

global $table_prefix;
global $modx;

	$sql = "SELECT id, client FROM ".$table_prefix." table2";
	$res = $modx->db->query($sql);

	while($row = $modx->db->getRow($res)) {
		$output .= $row['id'] . '<br>' . $row['client'] . '<br>';
	}
return $output;

it return "NULL"

**Comment by michael-big** [comment]
Remove the space between $table_prefix and table 2:
`$sql = "SELECT id, client FROM ".$table_prefix." table2";
`

**Comment by modwebpl** [comment]
Omg :o, u are right. Sorry for that, my mistake.
Thanks a lot :)
