### ISSUE TITLE
EVO 1.4.2   php 7.2.*

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#807]
hi

anyone using EVO 1.4.2   and  php 7.2.* successfully? i didn't' see any mentions of that php version .

thanks

**Comment by user83743** [comment]
http://php.net/supported-versions.php

**Comment by user83743** [comment]
no. the count() issue is still there. i upgarde to evo 1.4.5   on   php 7.2 and  the contact form is dead and displaying:

Error : count(): Parameter must be an array or an object that implements Countable
Error information	
ErrorType[num]	WARNING[2]
File	/home/xxxxxxxxxxxx/public_html/xxxxxxxxxxxxx.com/assets/snippets/eform/eform.inc.php
Line	700
Source	$lastitems[count($lastitems)]="[+$name+]";



Backtrace
DocumentParser->executeParser()
index.php on line 139
DocumentParser->prepareResponse()
manager/includes/document.parser.class.inc.php on line 2862
DocumentParser->parseDocumentSource(string $var1)
manager/includes/document.parser.class.inc.php on line 2971
DocumentParser->evalSnippets(string $var1)
manager/includes/document.parser.class.inc.php on line 2713
DocumentParser->_get_snip_result(string $var1)
manager/includes/document.parser.class.inc.php on line 2025
DocumentParser->evalSnippet(string $var1, array $var2)
manager/includes/document.parser.class.inc.php on line 2113
eval()
manager/includes/document.parser.class.inc.php on line 1962
require(string $var1)
manager/includes/document.parser.class.inc.php(1962) : eval()'d code on line 1
eForm(DocumentParser $var1, array $var2)
assets/snippets/eform/snippet.eform.php on line 114
formMerge(string $var1, array $var2)
assets/snippets/eform/eform.inc.php on line 659

any ideas?

**Comment by BBloke** [comment]
I hit the same problem.  I moved over to FormLister but did do a core hack for WebLoginPE to work. See https://github.com/evolution-cms/evolution/issues/785 it may help.

**Comment by user83743** [comment]
thanks BBloke

**Comment by BBloke** [comment]
I'll tag this on here as I think it's relevant.  Our hosting company has upgrade from php 7.0 to php 7.2. Their one month reversion period has ended so the site cannot be used with 7.0.

I've finally gotten a standalone duplication development site locally on 7.2.  Whilst it works and eForm has been changed to FormLister (although cannot get captcha working - I'll leave that for another day :) ). A core hack to ensure using WebLoginPE doesn't screw it up too the one thing I come across is the staying logged in doesn't persists at all.

I visit my site. No problem. 

Using WebLoginPE:
It thinks I'm already signed in but restricted pages cannot be seen in the menu and any effort to get to them fails.

Using WebLogin:
Thinks I'm not logged in.
Enter credentials and get signed in after submission.
Menu looks great. 
Try to access ANY page and I'm returned to the home page needing to login again.

I'm simply don't know if this is a fault at my end with apache, php or whether this is a fault with Evo and php 7.2.

I'm hoping I'm not alone on this one.  Let me know if this should be in a separate thread.

BBloke

**Comment by dmi3yy** [comment]
I fixed eForm for 7.2 now work 

but recommend use: FormLister  and delete eForm, WebLogin

**Comment by user83743** [comment]
Thanks so much Dmytro. Is the new eform version on the old modx site?

**Comment by dmi3yy** [comment]
Fix only for support 7.2 
https://github.com/extras-evolution/eForm/commit/c3659306c9b7e2a1451c7e9a3406f91f309d0741

and work on all version off MODX

**Comment by user83743** [comment]
Thnaks Dymtro. do you mean it supports php 7.2+ (from now on) or just php
7.2?

**Comment by dmi3yy** [comment]
We not test on php 7.3 old extras and fix only if any one write about bug. 

But new Extras tested on new version

**Comment by dmi3yy** [comment]
Work on 5.4-7.2

**Comment by user83743** [comment]
thanks Dymtro and @risingisland
