### ISSUE TITLE
Два таба seo

### ISSUE THREAD

**Issue by chernyshovmaksim** [evolution-cms/evolution#811]
![screenshot_1](https://user-images.githubusercontent.com/8769580/45738569-4bab1c00-bc0a-11e8-8281-cf759aa38d36.png)
При чем один пустой а другой со стандартными полями из коробки

**Comment by dmi3yy** [comment]
Ну значит что то у вас еще 1 таб создает 

проверьте плагины + чанк mm_rules

**Comment by chernyshovmaksim** [comment]
Да надо было закоментировать строку в mm_rules
