### ISSUE TITLE
convert special tags from ajax data

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#813]
Hi All,

I was wondering is there a way of changing all special tags, placeholders etc when I'm grabbing data through ajax?

I have some URL links which contain [~[*id*]~]. Obviously when I get the data through AJAX it remains as that.  When I get the date normally modx handles it how it should.

I'm sure it's simple but I cannot think on how to do it.

Any ideas?
BBloke

**Comment by AgelxNash** [comment]
You can use **php://input**
Through this stream you will get the original **POST** data.
