### ISSUE TITLE
count and php7.2+

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#815]
In php7.2 count can throw warnings due to changes in the count function.

Should a 'polyfill' be added to Evo for 'is_countable' so any fixes needed to validate count can be coded using (is_countable) that will be in the upcoming php7.3 ?

https://stackoverflow.com/questions/42899605/how-to-check-if-something-is-countable

**Comment by dmi3yy** [comment]
In core all count fixed 
Maybe in some extras need fix

**Comment by bossloper** [comment]
ok, so extras would need changing on a case by case basis and the polyfill would need adding to each extra?
