### ISSUE TITLE
"Новое сообщение"  in  formlister

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#817]
Hi

"Новое сообщение" is hardcoded into the formlister code. we have the formlister code working but all new messages are emailed to the website owner with the email subject "Новое сообщение" . it is not in any of the tpl code that we can see so it must be hardcoded into the formlister. do you know where this is editable?

thanks

G.

**Comment by user83743** [comment]
found it in a google 
http://modx.im/blog/addons/4481.html
&subject=`Новое сообщение`

this should be in all the example forms on http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/anatomy-of-a-contact-form , no?

**Comment by modxuser** [comment]
Subject is, as such, in the forms found in the docs: http://www.evolution-docs.com/tutorials/extras-how-to/formlister-tutorials/anatomy-of-a-contact-form

What you are talking about is the "mail header" subject, not the form subject as described in the docs

You can use:
``&subjectTpl=`@CODE:[+subject.value+]`

Which will give you the subject from your form field

**Comment by user83743** [comment]
thanks. we used   "&subject=xxxxxxxxxxxxxxx " in the formlister call and that created the email subject we were looking for.

**Comment by modxuser** [comment]
Ah, OK

But that gives a permanent fixed subject - using the tpl, you get the subject thats added by the user

Further docs: http://www.evolution-docs.com/extras/formlister/mail-sending

**Comment by Pathologic** [comment]
"Новое сообщение" is not hard coded, you've got it because there's &config=\`default:core\` in your snippet call. Check the docs :cat:
