### ISSUE TITLE
evo 1.4.5 стиль админки

### ISSUE THREAD

**Issue by Fr3ddy7** [evolution-cms/evolution#818]
в последней версии не сохраняется стиль указанный в настройках

http://prntscr.com/kylhhc

**Comment by 64j** [comment]
Всё сохраняется.

**Comment by Nicola1971** [comment]
@64j 
i think it's not clear to everyone how it works

we can use the empty **manager_theme_mode_message** language string to add an explanation.

an example:
![manager_theme_mode_message](https://user-images.githubusercontent.com/7342798/46207384-7f332800-c327-11e8-9745-79c50998585f.png)

```$_lang['manager_theme_mode_message'] = 'This setting is used as "Default" theme mode, but is overridden by the theme mode switch button in the resource tree: <i class="fa fa-lg fa-adjust" aria-hidden="true"></i>';```

someone with a better english knowledge,  help me with the message :D

**Comment by fourroses666** [comment]
Maybe something like; 

`This color scheme setting is used as "Default" and can be overridden by the theme color mode switch button in the resource tree`

**Comment by Nicola1971** [comment]
@fourroses666 thanks

``` ..can be overridden  by the user..``` ???

**Comment by fourroses666** [comment]
`This setting is used as "Standard" and can be overridden by the user when using the theme color mode switch button in the Resource Tree: <i class="fa fa-lg fa-adjust" aria-hidden="true"></i>`

**Comment by bossloper** [comment]
overridden by the manager
? :-)

**Comment by Nicola1971** [comment]
just not sure about "standard"  vs "default" :)

**Comment by Nicola1971** [comment]
> p.s. it would be nice if hovering over the 'theme color mode switch button' in the site tree displayed a title popup indicating this is what the button/icon is (it does for all other icons).

agree

**Comment by Nicola1971** [comment]
![manager_theme_mode_message](https://user-images.githubusercontent.com/7342798/46212210-b8729480-c335-11e8-8df0-61b494720529.png)

**Comment by dmi3yy** [comment]
Нужно ленг русский поправить тоже
