### ISSUE TITLE
Default manager help pages need updating for EVO CMS

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#82]
https://github.com/evolution-cms/evolution/tree/develop/assets/templates/help

**Comment by Nicola1971** [comment]
i'm working on it.
![docs](https://user-images.githubusercontent.com/7342798/28839026-95389298-76f2-11e7-9acb-e38287531b64.png)

- @64j does the new document tree still use dTree. js? or we can remove from credits
- @dmi3yy and All : do we really need the old etomite credits?
![credits](https://user-images.githubusercontent.com/7342798/28839086-c79fef10-76f2-11e7-8616-015fae9873a9.png)

**Comment by Nicola1971** [comment]
...and about modx.im and modx.com.ua?

**Comment by dmi3yy** [comment]
i think its history: do we really need the old etomite credits?
modx.com.ua - no more need 
modx.im need - its russian evo community

**Comment by 64j** [comment]
@Nicola1971 
Javascript in the tree is rewritten.
modx.js

**Comment by Nicola1971** [comment]
..and the everaldo link is broken. so just php and mysql :D : we can remove all credits

**Comment by Nicola1971** [comment]
and finally delete the "credits" image folder from default manager theme :)

**Comment by 64j** [comment]
@Nicola1971 
> and finally delete the "credits" image folder from default manager theme :)

Yes)

**Comment by Nicola1971** [comment]
logo in about tab? :) (we have the space left by credits) 
![download](https://user-images.githubusercontent.com/7342798/28840446-3da58c48-76f7-11e7-8df4-1c6a9d3de285.png)

**Comment by Nicola1971** [comment]
and new tab order (about evo first)
![download](https://user-images.githubusercontent.com/7342798/28840628-df7ad2a8-76f7-11e7-83cb-e595fd48a9cf.png)

**Comment by Nicola1971** [comment]
There is a small issue:: tabs and tab names are automaticall loaded from templates folder
https://github.com/evolution-cams/evolution/tree/develop/assets/templates/help
New about tab is 01About_EVO.php
We need to delete /04About_MODX.php with install/ update process to remove "about modx" tab.

**Comment by Nicola1971** [comment]
ok, found a simple solution, without deleting old help files:
- move Help templates folder from assets/templates (I never understood why in assets) to actions/help, like resources and category manager files

**Comment by Nicola1971** [comment]
- Moved help templates to manager/actions
- Updated tabs content for EVO CMS
- New tabs order (about first)
- basic drafts for 1.3x version noticies (need to be completed by any 1.3 dev)
- Updated version noticies to support both cms names:
```
        if ($v >= '1.3.0') {
            $cms = 'EVO';
        }
        else {
            $cms = 'MODX EVO';
        }
```
:D :D 

@dmi3yy i have added a "draft" of 1.3.0 version noticies, need to be completed:
![130](https://user-images.githubusercontent.com/7342798/28921154-14999e34-7855-11e7-95c3-5d906bca3fb8.png)


do we need minor updates (1.3.1, 1.3.2, 1.3.3) in version release? 
![13x](https://user-images.githubusercontent.com/7342798/28921192-3c4c1fa6-7855-11e7-931d-e393e4bf35dd.png)

**Comment by Nicola1971** [comment]
note: we need to update all languages to fix some content of Help pages (to remove some modx words and links)

**Comment by bossloper** [comment]
@Nicola1971 - should we keep this issue open for now until languages are updated?

**Comment by bossloper** [comment]
Is the 'documentation' tab even relevant? It seems mostly a duplicate of links in the  'about' tab. 
Is just 'About', 'version' and 'change log' all that is needed?

**Comment by Pathologic** [comment]
I think, there's no need to publish minor updates. The documentation tab can be enhanced with links to solution of common problems: moving site to other server, updating existed site, etc.

**Comment by Nicola1971** [comment]
nice idea @Pathologic 

we could allocate a space in the documentation tab to international documentation, currently only in Russian, but I hope in the future even in other languages

![download](https://user-images.githubusercontent.com/7342798/29028201-caaa65ba-7b83-11e7-9ac7-ab4b00baaad4.png)

**Comment by bossloper** [comment]
Can I close this now?

**Comment by Nicola1971** [comment]
@bossloper 
yes, thanks
