### ISSUE TITLE
Bug in listing User Groups under Manager access permission

### ISSUE THREAD

**Issue by mehistaken** [evolution-cms/evolution#820]
Wrong table alias used in db query on line 101 of `/manager/actions/access_permission.dynamic.php`

Before:
`LEFT JOIN ' . $tbl_manager_users . ' AS users ON users.id = groups.member', '', 'groupnames.name, user_name');`

Fix:
`LEFT JOIN ' . $tbl_manager_users . ' AS users ON users.id = groups_member.member', '', 'groupnames.name, user_name');`

**Comment by AgelxNash** [comment]
Fixed #797
