### ISSUE TITLE
Cannot remove access permissions from documents

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#821]
Hi All,

I've come around to needing to update some document permissions.  I can add but I cannot remove any.

This is on top of an issue which needs me to almost constantly login to the manager. I normally use Chrome but the same happens for both instances on Firefox and Edge.

It's driving me barmy.  Whilst the permission thing gives me the feeling it's Evo. I'm not sure why I need to keep signing into the manager.  It always happens when I need to save documents etc.  

Please help!

**Comment by bossloper** [comment]
I also see the issue about not being able to uncheck a document permission. evo 1.4.5, php 7.1 and php7.2

Looks like this fix broke it:
https://github.com/evolution-cms/evolution/commit/a0c7f264cfb635e30cef82e4fe86ce82660b78ec#diff-907893dd0ebb6dd1e088480712266ff2

**Comment by BBloke** [comment]
Ah.  Nice to not be in a camp on my own.

I'm still on php 7.0.
