### ISSUE TITLE
Ajax search in the admin area should honour manager roles and manager permissions

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#83]
If a manager does not have access to chunks, snippets, modules, TVs or particular resources then the ajax manager search on the left side of the manager menu should not return their names, even though they cannot edit them. By trial and error they may deduces sensitive information.

**Comment by bossloper** [comment]
The search on modules also needs to check manager permissions for each module (similar to the top menu).

**Comment by bossloper** [comment]
Plus I suggest:
If 'exec_module' role then should just be searching title and description.
If 'edit_module' role then can search all fields.

**Comment by 64j** [comment]
@bossloper 
Why do we need such distinctions?

**Comment by bossloper** [comment]
Because if I grant a manager to be able to only run a module then they should not be able to search for code in the module.

**Comment by bossloper** [comment]
I see you have made some code changes, but after further thought I think it is just that the role check was incorrect. As the search is for modules to be edited then this line (from the old code):
https://github.com/evolution-cms/evolution/blob/893f83fc826090cd91e6ceffacb5f7584ec31784/manager/actions/search.static.php#L365

should just have been changed to:
if($modx->hasPermission('edit_module')) {

There is no need to return any results if the manager can only execute a modules as the search links are just to edit a module and do not return links to run them. Does that sound right?

**Comment by 64j** [comment]
@bossloper 
I would generally remove the search for modules)))

**Comment by bossloper** [comment]
Possibly, though I think a roll back to the previous code and then just the one line change should give a correct solution.

**Comment by 64j** [comment]
@bossloper
No problem

**Comment by bossloper** [comment]
Looks good.
