### ISSUE TITLE
create_function - PHP Strict Standards Problem PHP7.2

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#834]
ManagerManager uses create_function (depreciated in php7.2):

https://github.com/evolution-cms/evolution/blob/1.4.x/assets/plugins/managermanager/utilities.inc.php#L61

**Comment by AgelxNash** [comment]
Also
https://github.com/evolution-cms/evolution/blob/1.4.x/install/setup.info.php#L65
https://github.com/evolution-cms/evolution/blob/1.4.x/install/cli-install.php#L620
