### ISSUE TITLE
doclister in 1.4.5

### ISSUE THREAD

**Issue by Fr3ddy7** [evolution-cms/evolution#839]
вырезает внутри своего шаблона [+ - [*

тестировал на 3 сайтах, если внутри шаблона доклистера есть вывод ещё сниппета и в его параметрах есть [+ - [* - выводит пустоту, никаких ошибок. Доклистер из коробки 1.4.4 работает нормально

**Comment by Pathologic** [comment]
А обновить - никак?

**Comment by Fr3ddy7** [comment]
> 
> 
> А обновить - никак?

обновлял жеж )

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/tree/master

**Comment by AgelxNash** [comment]
@Fr3ddy7 может проще воспользоваться prepare и не заморачиваться?
