### ISSUE TITLE
Cancel edit element does not remove 'editing eye'

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#84]
If an element is edited and then cancelled, the lock is removed but the 'eye' icon is not removed until the page is refreshed or a different element is edited.
![untitled-1](https://user-images.githubusercontent.com/1744687/28412932-a0b645b6-6d3d-11e7-8265-5a8bf2062b59.jpg)

**Comment by Deesen** [comment]
The iframe / cancel-request to server is processed first, before the window.unload event which unlocks the element. This is why the eye is still visible, while the element is actually already unlocked.

I added GET-Params to the cancel-buttons which will triggers an unlock before the resources-list gets rendered. Also I tried to fix some issues with the eye-symbol with editing documents & resource-tree.
