### ISSUE TITLE
DLMenu Mulitple Parents obscure output render

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#842]
Hi All,

I've been working with DLMenu and multiple parents.  It is pretty simple but when using multiple parents the output is not what I would expect.

The output is given with two sets or parent template codes rather than creating one output for what would be given for one list.

 I don't need this output is there a way to control it?

Thanks,
BBloke

**Comment by Pathologic** [comment]
set &joinMenus=\`1\`
