### ISSUE TITLE
Uncatchable error "Call to a member function ... on null"

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#843]
When this error happens in snippet or plugin (executed by eval), the site just shows 500 error, without logging in modx log, or in server log.

Test snippet:
```php
return $something->do();
```

The solution may be catching `Throwable` or `Error`:
```php
try {
   $return = eval($phpcode);
} catch (Throwable $e) {
   $this->messageQuit($e->getMessage());
}
```

but they appeared only in php7.

**Comment by AgelxNash** [comment]
In the 2.x branch you can already use it.
In the 1.4.x branch i think, the commit https://github.com/evolution-cms/evolution/commit/2e247bfd93fa6962828253d512edbaa00c7260fb resolve this issue.
