### ISSUE TITLE
Database collation and quick update

### ISSUE THREAD

**Issue by Fenton1** [evolution-cms/evolution#845]
Hi there,

I posted it on the MODX Forum as well, maybe someone here got an idea, it only affects the first 3 rows of the DB:
https://forums.modx.com/thread/104552/after-update-to-evo-1-4-5-database-charset-is-set-to-latin1-even-though-database-is-set-to-utf8

thanks a lot, j

**Comment by Fenton1** [comment]
thanks AgelxNash,

but still, why did it change during the upgrade process for the first 3 rows? happened on another site as well and I checked beforehand, that it was indeed utf8_general_ci

cheers, j

**Comment by AgelxNash** [comment]
@Fenton1 
EvolutionSMS when updating removes and creates new tables
- active_users
- active_user_locks
- active_user_sessions

When creating tables, your server uses the latin1_german2_ci encoding. The latin1_german2_ci is default encoding on your server.

**Comment by AgelxNash** [comment]
@Fenton1 Use advanced upgrade

**Comment by Fenton1** [comment]
@AgelxNash ah! that explains it :) 

"EvolutionSMS when updating removes and creates new tables"

thanks a lot! updated a few sites to the current Evolution version and it looks great

cheers, j

**Comment by Fenton1** [comment]
yes, I used Advanced Upgrade already
