### ISSUE TITLE
DocLister not populating site variables

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#846]
Hi.

I have a page which is pulled through to my page using DocLister. The page has [(site_name)] in both title and content.

When I view the page directly I see what I should. When I view the page where DocLister provides the content then the variable doesn't come through.

My call is:

[[DocLister? &parents=`2` &display=`20` &filters=`private` &dateFormat=`%d-%m-%Y %H:%M` &summary=`len:600` &tvList=`2ColumnSpan` &commentschunk=`NewsComments` &tpl=`DLNews_home` &paginate=`0` &alwaysshow=`1` &orderBy=`createdon DESC` &emptyText=`You must be logged in to view News` &noResults=`You must be logged into view News.` ]]

Tried to search but didn't come up with anything.

BBloke

**Comment by Pathologic** [comment]
update doclister to master from Extras.
