### ISSUE TITLE
after the update to version 1.4.5 no files folder in KCFinder

### ISSUE THREAD

**Issue by webkarli** [evolution-cms/evolution#847]
after the update to version 1.4.5 no files and folders in the folder files are displayed in the KCFinder. With pictures everything is ok.

**Comment by dmi3yy** [comment]
check for file with cyrilic names

**Comment by webkarli** [comment]
It's a German website. There are no file names with Cyrillic letters in the folders for downloadfiles

**Comment by webkarli** [comment]
Transliteration was deactivated after the update. A German user had uploaded files with German umlauts. This was the error.
