### ISSUE TITLE
MySQL server strict sql_mode trouble

### ISSUE THREAD

**Issue by lefouk** [evolution-cms/evolution#849]
Our shared server was updated to MariaDB version 10.2 with "strict mode" enabled by default. 
Trying to log into the manager I get the error: 

> « Evo Parse Error »
> Execution of a query to the database failed - Data too long for column 'ip' at row 1 

> SQL > INSERT INTO `sycust_db01`.`modx_manager_log` (`timestamp`, `internalKey`, `username`, `action`, `itemid`, `itemname`, `message`, `ip`, `useragent`) VALUES('1540846718', '1', 'cubus', '58', '-', 'MODX', 'Logged in', '2a02:8109:9a80:7334:4b6:7a9d:6bab:b107', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8')

So I tried a new install, which also throws a Warning: 

> Checking MySQL for strict sql_mode: WARNING!    MySQL server strict sql_mode is enabled!
> 
> Certain features of EVO may not work properly unless the STRICT_TRANS_TABLES sql_mode is disabled. You can set the MySQL mode by editing the my.cnf file or contact your server administrator.

Because of security reasons the server admin does not want to change his MySQL, so I need a work around for this issue. Any idea?

thanks

**Comment by Ser1ous** [comment]
Fast fix for you
```
ALTER TABLE sycust_db01.modx_manager_log
	CHANGE COLUMN `ip` `ip` VARCHAR(38) NULL DEFAULT NULL AFTER `message`;
```
In next release all be ok. 
It's not strict_mode. Length column ip 15 symbol and this works for ipv6, but you send ipv6 and for this reason all crashed.
Sorry for my English

**Comment by lefouk** [comment]
Thanks Ser1ous. 
I just did that but didn't work. Than I did some reserch for the possible max. length of IPv6, here's what I found:

> Naive option would be:
> 8 * 4 + 7 = 39
> 8 groups of 4 digits with 7 ':' between them.
> 
> But to take into account the IPv4-mapped IPv6 addresses feature, eg. [::ffff:192.168.0.1], written out fully:
> (6 * 4 + 5) + 1 + (4 * 3 + 3) = 29 + 1 + 15 = 45
> Note, this is an input/display convention - the amount of data is the same and for storage it would probably be best to standardise on the raw colon separated format, ie. [0000:0000:0000:0000:ffff:7fa8:0001] for the address above.

So I ran the script with VARCHAR(50) to be save, that did the trick. 

Thanks again! and I hope I could contribute smth. worth it ... I love work with Evolution CMS since many years and where would I be without you guys who keep this project alive!

**Comment by AgelxNash** [comment]
**varchar(46)**: https://stackoverflow.com/a/15876397/2323306
