### ISSUE TITLE
Enhancement: Allow managers to update their own email address

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#85]
If a manager is setup without 'user management' roles to edit manager accounts then they have no way to update their own email address which is used for password resets.
Suggest at least they can update their own email address (maybe other fields too). Could add another menu item in the dropdown:
![untitled-1](https://user-images.githubusercontent.com/1744687/28414710-d3daa2c8-6d44-11e7-83a6-ffb3d0ef4fc1.jpg)

**Comment by Deesen** [comment]
Maybe a new permission like "Manage actual user" makes sense?

**Comment by bossloper** [comment]
Yes, something like that, depends how complex you want to go, but generally I think it needs some ability to change a manager email address.

**Comment by Deesen** [comment]
I thought more of adding this new permission to the already existing user-management. This way user can change all his details on his own, and there is no need to develop an extra action for that.

**Comment by bossloper** [comment]
Yes. As long as if the manager does not have 'user management' roles then they should only be able to update 'Gerneral' tab information (minus changing role) and not 'User' tab or 'access permissions' tab?

**Comment by Deesen** [comment]
Yes exactly. This should be easy to solve.
