### ISSUE TITLE
EVO - Hack - Version 1.3.6

### ISSUE THREAD

**Issue by mgzawlinoo** [evolution-cms/evolution#852]
Hi,
I don't know detail yet, 
but yesterday my exim show email error log and 
I found that unsuccessful email come from "assets/import/".
Evo Ver : 1.3.6
![download 2](https://user-images.githubusercontent.com/9032715/47752771-c95f4e80-dcc3-11e8-90e7-38e91eefbebc.png)
Now update to 1.4

**Comment by AgelxNash** [comment]
### Please, read the news in the manager dashboard!!
[![image](https://user-images.githubusercontent.com/1748872/47758896-e77e7c00-dcce-11e8-832e-412fec92d524.png)](https://github.com/extras-evolution/security-fix/releases/tag/1.4.5)
