### ISSUE TITLE
[info] Plugin to hide default widgets

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#86]
a fresh new plugin to hide widgets in evo 1.3.3 

- Show/Hide widgets: show/hide/AdminOnly
- Widget size: 12/6/4/3
- Menu index: sort widget order by number

https://github.com/Nicola1971/EvoDashboard-Manager

![screenshot](https://user-images.githubusercontent.com/7342798/28416659-4010ff90-6d55-11e7-9606-0b620bb878e6.png)

**Comment by bossloper** [comment]
A suggestion, could the '.... x size' fields be '.... width' and instead of 3,4,6,12 be picked from 25%, 33%, 50%, 100% ? Or alternatively make it more obvious we are selecting number of Bootstrap columns?

**Comment by pmfx** [comment]
@bossloper I was thinking the same. Maybe naming it with percent values will be better.

**Comment by Nicola1971** [comment]
+1 for width instead x 

yes the width is based on bootstrap

`$widgets['welcome']['cols']='col-sm-'.$welcome_sizex.'';`

not included col-sm for people that dont know bootstrap

**Comment by Nicola1971** [comment]
yes, percent is better, just need some new lines
