### ISSUE TITLE
Russian translations

### ISSUE THREAD

**Issue by AgelxNash** [evolution-cms/evolution#868]
- configcheck_filemanager_path
- configcheck_filemanager_path_msg
- configcheck_rb_base_dir
- configcheck_rb_base_dir_msg
- icon_description
- clientResize
- clientResize_message
- noThumbnailsRecreation
- noThumbnailsRecreation_message
- manager_theme_mode_title
- page_data_alias
- show_fullscreen_btn_message
- show_newresource_btn_message
- settings_show_picker_message
- show_fullscreen_btn
- show_newresource_btn
- show_picker
- system
- toggle_fullscreen
- allow_multiple_emails_title
- allow_multiple_emails_message
- enable_at_syntax_title
- enable_at_syntax_message
- enable_cache_title
- disabled_at_login
- login_form_style
- login_form_style_dark
- login_form_style_light

**Comment by AgelxNash** [comment]
New missing lines
- enable_mootools
- enable_mootools_message

**Comment by Ruslan-Aleev** [comment]
In Evo 1.4.8, there are some untranslated strings, see the image below.

![lang_top](https://user-images.githubusercontent.com/12523676/52784801-ba808a00-306f-11e9-851b-64dd5a4852c2.gif)

p.s. Perhaps this has already been fixed.
