### ISSUE TITLE
Question: Is there a startItemTpl for DLMenu?

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#873]
Hello,

I am a bit stuck with DLMenu 1.4.0 menu in an Evo 1.4.5 website.

I am making a sub menu with lots of differing level parents and children pages of varying depths.

The parentRowTpl template is getting me into trouble. It works fine when there are only 2 levels, where the one parent is shown with corresponding children. But when there are 3 or more levels I think I really need "startItemTpl" like there is in wayfinder that is use for the top most parent only.

Is there are startItemTpl in DLMenu?

Consider the following DLMenu call...
````
[[DLMenu?
	&id=`sub[*id*]`
	&parents=`[[UltimateParent]]`
	&disablePHx=`1`
	&maxDepth=`5`
	&hideSubMenus=`0`
	&showParent=`1`
	&hereClass=`active`
	&levelClass=``
	&oddClass=``
	&evenClass=``
	&parentRowTpl=`sub-menu-starter`
	&outerTpl=`sub-menu-wrapper`
	&rowTpl=`sub-menu-row`
	&innerTpl=`sub-menu-inner-wrapper`
	&innerRowTpl=`sub-menu-inner-row`
	&orderBy=`menuindex ASC`
	&filters=`AND(
		content:c.hidemenu:is:0
	)`
]]
````

With the following html structure...
````
<h2><a href="#" title="">Section (the ist level parent - this currently uses the parent template but would ideally use the start template equivalent)</a></h2>
<ul>
	<li class="first"><a href="#" title="">Sub Section (also a parent - this unfortunately uses the parent template and is output as h2 but should remain as a list item)</a>
		<ul>
			<li class="first"><a href="#" title="">Item</a></li>
			<li class=""><a href="#" title="">Item</a></li>
			<li class="last"><a href="#" title="">Item</a></li>
		</ul>
	</li>
	<li class="last"><a href="#" title="">Sub Section (also a parent - this unfortunately uses the parent template and is output as h2 but should remain as a list item)</a>
		<ul>
			<li class="first last"><a href="#" title="">Sub Sub Section (also a parent - this unfortunately  uses the parent template and is output as h2 but should remain as a list item)</a>
				<ul>
					<li class="first"><a href="#" title="">Item</a></li>
					<li class=""><a href="#" title="">Item</a></li>
					<li class="last"><a href="#" title="">Item</a></li>
				</ul>
            </li>
			<li class=""><a href="#" title="">Item</a></li>
			<li class="last"><a href="#" title="">Item</a></li>
		</ul>
	</li>
</ul>
````

All the 2nd level+ parents are output as h2, using the parent template. What I am trying to achieve is a h2 for the first level parent only (which was the start item in WayFinder), with all others parents treated just as list items.

Any tricks to make this work with DLMenu, or should I use Wayfinder (which handles this fine from memory) for submenus?

Thanks

**Comment by AgelxNash** [comment]
@nick0 Question about DL* elements must posting on the [DocLister repository](https://github.com/AgelxNash/DocLister/issues).

**Comment by nick0** [comment]
okay, posted there, thanks and will close this

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/DocLister/issues/331
