### ISSUE TITLE
Edit Request and Suggestion: Remove fullstop at end of new password displayed on screen. Add padding to left of that sentence

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#874]
Hello,

1. When changing a user password, there is a full stop at the end of the new password - sometimes its confusing as to whether the password is part of the password or not. And the trailing fullstop is easily copied by mistake when copying the password. I vote the full stop from that sentence is removed.

2. The sentence that says "The new password for XXXXX is XXXXX." in Evo 1.4.5 does not line up (its hard against the frame edge) with the heading "Create/Edit Manager User", which has a left margin on 1.25rem. Using this seems to resolve it
````
.sectionBody {
    padding-left: 1.25rem;
}
OR
.sectionBody p {
    padding-left: 1.25rem;
}
````
Thanks and keep up the great work.

**Comment by Pathologic** [comment]
https://github.com/evolution-cms/evolution/commit/a315fe63f95a8ef038d5b0843cffd8718fc467cd

**Comment by AgelxNash** [comment]
@nick0 resolved?

**Comment by nick0** [comment]
Just tested in 1.4.6...

1 was actioned (removing the fullstop). Thanks, that's awesome.

2 the changed password paragraphs are still hard against the LHS edge of the frame. Would look better to indent. to match all other content. So maybe not ready to close now.
