### ISSUE TITLE
Evo 1.4.6,  Doclister 2.4.1 DocInfo  0.4.1

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#880]
Evo 1.4.6  (released this 3 hours ago)  comes with Doclister 2.4.0 and DocInfo  0.4.0, but latest versions (required from OutdatedExtras plugin) are Doclister 2.4.1 DocInfo  0.4.1, why?

![screenshot-146](https://user-images.githubusercontent.com/7342798/47920567-a1820d80-deb2-11e8-893a-0317636aff4c.png)

NOTE: Update button for Doclister does not appear in Extras Module
![screenshot-extras-2018 11 02-15-15-09](https://user-images.githubusercontent.com/7342798/47920602-beb6dc00-deb2-11e8-9238-5742d2d34fa5.png)

**Comment by AgelxNash** [comment]
Testing was not enough.
Release 2.4.1 was crucial to support PHP Version 5.4
DocInfo also gave an incorrect result #806 (It's my mistake)
All packages fixed after this commit https://github.com/evolution-cms/evolution/commit/403e590d1cc5345838b9c920429fff3d3a82d5e0

Any other question?

**Comment by Nicola1971** [comment]
Thanks @AgelxNash  
just to understand and anticipate questions from users.

we need more organization and communication to allow contributors to test and close issues before launching a new release.
