### ISSUE TITLE
Evo setup > EVO startup template option

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#883]
At the "options" step of the setup it is no longer possible to select or deselect the EVO startup template installation.
I had not noticed it before and I do not know which version it changed
![screenshot-localhost-2018 11 04-20-52-26](https://user-images.githubusercontent.com/7342798/47969164-c7a2db80-e073-11e8-9093-500724edf62a.png)

You can install EVO startup only with the Sample Website, but you can not see it in the list anyway

**Comment by dmi3yy** [comment]
I think this template need with install demo site 
So we move template to sql ;)

Отправлено с iPhone

**Comment by Nicola1971** [comment]
Ok. I think we should allow people to install just the template (to restore after bad modifications or install as a base for a custom one), but we don't need to change Evo setup, we can just add Evo startup to extras site/module.
What do you think?

**Comment by fourroses666** [comment]
Ideally we should not have any snippets and plugins pre-installed unless we select them in the installer.

**Comment by dmi3yy** [comment]
After stable release evo 2 we start refactor extras after finish  in CORE will be ZERO snippets and plugins. And in step in install you can chose recommended extras and install in one step. 

we will build extras into the install. I think thiss will be best solution
