### ISSUE TITLE
 EVO 1.4.6 - Extras compatibility check

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#884]
> Configuration > RSS Security Feed (http://feeds.feedburner.com/modxsecurity) is outdated. Please download and install UpdateEvoRss from [Extras Module](index.php?a=112&id=)
> Configuration > RSS News Feed (http://feeds.feedburner.com/modx-announce) is outdated. Please download and install UpdateEvoRss from [Extras Module](index.php?a=112&id=)
> Snippet AjaxSearch (version 1.11.0) is vulnerable.

The link above [Extras Module](index.php?a=112&id=) is index.php?a=112&id= and does not load any site. Developer Fix: Set link to https://extras.evolution-cms.com/packages/core/updateevorss.html

Fastest Admin fix:
1. Go to "System configuration", Tab Site (default), then scroll down and enter the new URL:
http://feeds.feedburner.com/evocms-release-news (rss_url_news)
2. "System configuration", Tab Security, set http://feeds.feedburner.com/evocms-security-news (rss_url_security)

> Please update AjaxSearch to the latest version (min required 1.12.1) from Extras Module or move to: evoSearch

Go to https://extras.evolution-cms.com/packages/rabota-s-resursami/ajaxsearch.html and download AjaxSearch 1.12.1 zip and unpack in `assets/snippets/ajaxSearch` or if you do not use it, and have already removed the folder, then change the snippet description to `<strong>1.12.1</strong> Ajax and ...`

>  Snippet DocInfo (version 0.4) is outdated and no longer compatible with Evolution .4.6
> Please update DocInfo to the latest version (min required 0.4.1) from Extras Module

Go to https://extras.evolution-cms.com/packages/rabota-s-resursami/docinfo.html and download the snippet. Open file in text editor and add new PHP to the snippet. Also change the snippet description to `<strong>0.4.1</strong> ...`

**Comment by risingisland** [comment]
Should the link in step 2  be "https"?

**Comment by Nicola1971** [comment]
> The link above Extras Module is https://www.matheretter.de/evoman/index.php?a=112&id= and does not load any site. 

fixed yesterday:  https://github.com/evolution-cms/evolution/commit/24eaa5a3d9db1df71cb0d1770e77eceb9f87986b

in the latest refactor of the plugin the $ExtrasID was renamed in $extrasID, but not updated in the rss message.
Anyway the link to the extras module works for other outdated packages

**Comment by Nicola1971** [comment]
> Should the link in step 2 be "https"?

you're right. :) 

oddly, the url provided by feedburner is in HTTP, but I've just checked and the HTTPS version also seems to work
https://feeds.feedburner.com/evocms-release-news

**Comment by q2apro** [comment]
Ah damn, just saw that i revealed my domain and the modx path, could you please remove the domain name. @Nicola1971 Thanks.

**Comment by Nicola1971** [comment]
> Ah damn, just saw that i revealed my domain and the modx path, could you please remove the domain name. @Nicola1971 Thanks.

done :)

**Comment by q2apro** [comment]
Thanks a lot. Comment(s) can be deleted.
