### ISSUE TITLE
"Manager Start" shows white page after update

### ISSUE THREAD

**Issue by signalfeuer** [evolution-cms/evolution#885]
I updated many MODX Evolution projects the last days and with some of them i have a problem i could not fix so far.

For example:
I recently updated a 1.2.1 project to 1.3 and after that to the latest release 1.4.6.
After the last update the Startpage of the backend shows only a white page.

Any ideas?

Thanks for your help.

**Comment by AgelxNash** [comment]
PHP version?

**Comment by dmi3yy** [comment]
Check version of php 
need >= 5.6

**Comment by signalfeuer** [comment]
Sorry.
PHP 7.1

**Comment by dmi3yy** [comment]
Can you send  plugin list 

some old plugin can broke start manager page

**Comment by signalfeuer** [comment]
It seems that maybe there is a problem with phx which i could not reset oder install.
Some installs via Package Management 0.1.3 just doesn't work. I push the install button, message says "Installed" but nothing happened.

**Comment by AgelxNash** [comment]
Check the web server error logs.
Also, you can hack the condition to view the error. https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L182

**Comment by signalfeuer** [comment]
<img width="919" alt="bildschirmfoto 2018-11-07 um 16 06 34" src="https://user-images.githubusercontent.com/10433748/48139596-2d2ade00-e2a7-11e8-8bf5-839895820ef1.png">

**Comment by dmi3yy** [comment]
need delete MODX.Evolution.updateNotify - no need more 
fur update uses snippet Updater

**Comment by AgelxNash** [comment]
@signalfeuer try to disable the userHelper plugin

**Comment by signalfeuer** [comment]
Deleted & disabled with no effect.
Hm. Error logs is saying...
[Wed Nov 07 15:55:56 2018] [php7:warn] [pid 4018] [client xxx] [host xxx] PHP Warning:  mkdir(): No such file or directory in /is/htdocs/wpxxx/www/assets/modules/store/core.php on line 245

**Comment by 64j** [comment]
PHx needed update

**Comment by signalfeuer** [comment]
phx update doesn't seem to work:
PHP Warning:  mkdir(): Permission denied in /is/htdocs/wpxxx/www/assets/modules/store/core.php on line 245

Which folder doesn't have the required rights?

**Comment by AgelxNash** [comment]
Probably something in assets

**Comment by signalfeuer** [comment]
plugins, snippets, modules – all have "750" as required (i think)

**Comment by AgelxNash** [comment]
What components do you install?

**Comment by signalfeuer** [comment]
Hm it seems, that solved the problem.
But i wonder how i can solve the mkdir problem, which i have with other projects and different snippets, too.

Thanks for your help.

**Comment by AgelxNash** [comment]
Maybe you web server disallow chmod 777 https://github.com/evolution-cms/evolution/blob/1.4.x/assets/modules/store/core.php#L243
Try to change this 0777 to 0750

Try to logging the $folder variable via file_put_contents for get more information

Try to create folder via Evolutuon file manager (any errors?)

**Comment by signalfeuer** [comment]
Edited core.php (Line 26,27,28 and 243):
Change from 0777 to 0750 with no result.

Created a folder via file manager into /assets/cache and /assets/plugins without any problems.

**Comment by fourroses666** [comment]
What happens when you disable ElementsInTree plugin?
I had some issues with that on a site.

**Comment by AgelxNash** [comment]
```
private static function mkDir($folder, $perm=0777) {
	file_put_contents(MODX_BASE_PATH . 'issues-885.txt', $folder . PHP_EOL, FILE_APPEND);
	if(!is_dir($folder)) {
		mkdir($folder, $perm);
	}
}
