### ISSUE TITLE
ElementsInTree should be sorted by name

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#887]
DEV fresh version
<img src="https://monosnap.com/image/WOSnUq3HeO7KpfXFxVF7ZShy2Im3Gx.png">

**Comment by pmfx** [comment]
Confirmed. Same for me. Looks like it is sorted by ID. It should be sorted by name.

**Comment by Nicola1971** [comment]
![sort](https://user-images.githubusercontent.com/7342798/48301731-bf72f200-e4f2-11e8-970b-1f32ef47a6b7.png)

https://github.com/evolution-cms/evolution/commit/288a6f96b5de245b52fbc7807ee12ef0dc6d491b

**Comment by Nicola1971** [comment]
please test

**Comment by mnoskov** [comment]
All elements are sorted as necessary, except modules:

![2018-11-11_00-38-32](https://user-images.githubusercontent.com/8789957/48305307-3687a500-e54a-11e8-8b2d-c7936051ec84.png)

**Comment by Nicola1971** [comment]
@mnoskov thanks. I will check and fix tomorrow

**Comment by Nicola1971** [comment]
![screenshot-localhost-2018 11 11-11-18-41](https://user-images.githubusercontent.com/7342798/48311668-98282d80-e5a3-11e8-85ba-e1523de12310.png)

**Comment by Nicola1971** [comment]
can we close this ticket?

**Comment by pmfx** [comment]
EVO 1.4.7
Categories are not sorted by name ASC

**Comment by Nicola1971** [comment]
partially fixed - need to fix modules category order
