### ISSUE TITLE
Manager alertbox styling (only 3kb)

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#89]
Would really be cool to style the default alertbox.

(only 3kb)

https://alertifyjs.org/

**Comment by bossloper** [comment]
If the manager is based around Bootstrap then maybe should be using Bootstrap modal boxes
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Comment by fourroses666** [comment]
If thats possible with these default alert boxes yea will be great too.
I like that visual stuff.

**Comment by fourroses666** [comment]
I will close this and wait how the new manager theme looks like

**Comment by Nicola1971** [comment]
@fourroses666 check the 1.4 beta 

@64j added popup and alertbox in latest dev
![2017-09-07 2](https://user-images.githubusercontent.com/7342798/30182738-2f1636da-9418-11e7-9422-2c7e14619db0.png)

**Comment by fourroses666** [comment]
Very nice, doing a good job :)
