### ISSUE TITLE
duplicated element name issue

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#892]
Try to create a chunk or a snippet with the same name as an existing one.
of course, there will be a warning, but at that point you can not do anything. :( 
The page remains locked on the preloader
![screenshot 2018-11-12 11 45 29](https://user-images.githubusercontent.com/7342798/48342774-de978e00-e670-11e8-80a0-9e98d35824eb.png)

video:
https://youtu.be/LLlGg94SR4A

**Comment by Nicola1971** [comment]
it happens with all kinds of elements: templates, tvs, chunks, snippets and plugins

**Comment by bossloper** [comment]
It you turn off 'global tabs' system setting it works ok. But you do not then get the custom 'yellow' poup warning but the old one?! Something going on there.

**Comment by Nicola1971** [comment]
"it's a job for ~~Superman~~ Serg" 😄 
@64j

**Comment by Nicola1971** [comment]
![screenshot 2018-11-12 12 18 29](https://user-images.githubusercontent.com/7342798/48344374-2c15fa00-e675-11e8-8119-0fba6da3b035.png)

**Comment by fourroses666** [comment]
When trying to open a chunk/snippet/template when its locked it keeps loading too. Same issue.

**Comment by Nicola1971** [comment]
thanks @64j It works perfectly now 👍

**Comment by 64j** [comment]
@Nicola1971 
There is a much deeper problem

**Comment by 64j** [comment]
@Nicola1971 

**Chunk**

render
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/actions/mutate_htmlsnippet.dynamic.php#L122-L134
```action="index.php"```

index.php
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/index.php#L533-L556
______________________________

**Snippet**

render
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/index.php#L533-L556
```action="index.php?a=24"```

index.php
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/index.php#L506-L529

**Comment by Nicola1971** [comment]
@64j  
snippets does not work properly 
...and plugins too 

After the alert, you lost the page and redirect to the dashboard
video:
https://youtu.be/FevuN6JiTAQ

everything seems ok with templates, tvs and chunks

**Comment by 64j** [comment]
@Nicola1971 
Yes, I was talking about it.

**Comment by Nicola1971** [comment]
@64j 
Yes I understand. I thought you did not notice the problem with plugins too. :) 

this problem seems to be present also in 1.4.5

**Comment by 64j** [comment]
I'll try to fix it later.

**Comment by Nicola1971** [comment]
@64j 
Test creating duplicated elements:

- Chunks 🆗 
- Tvs 🆗 
- Snippets 🆗 
- Plugins 🆗 
- Modules (never tested before) : works , but lost the module name

see video:
https://youtu.be/ZdagWVcdfuE

**Comment by Nicola1971** [comment]
Tested #892
Modules  🆗

:)
