### ISSUE TITLE
MySQL5.6 end of life  Feb 2018 ---MySQL5.7 end of life Oct 2020

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#893]

**Comment by user83743** [comment]
Hi

is there any document or link mapping out what evo versions work on what mysql versions? we'd love to move all evo's to mysql5.7 to get us to the end of 2020.

**Comment by dmi3yy** [comment]
Hi 1.4.7 +. perfect work on 5.7  
Version older then 1.4.7 need test
