### ISSUE TITLE
Evo 1.2.1 sitemap.xml not working with https://

### ISSUE THREAD

**Issue by Tourist4Life** [evolution-cms/evolution#895]

**Comment by Tourist4Life** [comment]
I'm able to view the google sitemap with the .html extension as follows:

https://www.stackemhighpancakesandsoforth.com/sitemap.html

....but now 

https://www.stackemhighpancakesandsoforth.com/sitemap.xml

**Comment by 64j** [comment]
Name the document sitemap.xml

![image](https://user-images.githubusercontent.com/4653189/48665170-fd57b380-eaba-11e8-8e6f-d391b957e73c.png)

**Comment by Tourist4Life** [comment]
I'm using 1.2.1

https://cl.ly/a6b68c0839d8

**Comment by 64j** [comment]
@Tourist4Life 
Name the document sitemap.xml

**Comment by Tourist4Life** [comment]
thanks!
