### ISSUE TITLE
Phpthumb 1.3.1/1.3.2 does not create cache/images subfolders

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#896]
The latest phpthumb version in 1.4.6 and 1.4.x branch creates all cache files in the assets/cache/images/ folder, without creating their respective subfolders (ie: assets/cache/images/products/)

**Comment by Nicola1971** [comment]
there is another issue in the created image cache path:
assets/cache//images/

**Comment by fourroses666** [comment]
Noticed that double // yesterday indeed! It works but not correct.

**Comment by dmi3yy** [comment]
Tested last version all ok with subfolder and other 

http://14x.evo.im/phpthumb.html

**Comment by Nicola1971** [comment]
@dmi3yy Yes, I have not found other issues, I think we can close.
