### ISSUE TITLE
оформление

### ISSUE THREAD

**Issue by nuclear4547** [evolution-cms/evolution#898]
если выбрать в конфигурации сайта тему оформления все светлое
а в профиле пользователя выбрать тему Все темное
при просмотре эвентлога от этого пользователя фон темный и шрифт также темный.

**Comment by nuclear4547** [comment]
http://joxi.ru/p274qMVtobywYA
http://joxi.ru/823v71ViJpVRXm

**Comment by 64j** [comment]
https://monosnap.com/file/atql9NMa8P8nJmDgEoaNd39CiAZFee

@nuclear4547 
Всё работает
