### ISSUE TITLE
Clear cache in modal(ajax)

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#90]
А тут по-русски. Возможна ли реализация очистки кеша в админке в модальном окне в фоне? Как считаете на сколько это будет удобнее? Планируется ли реализация

**Comment by sazanof** [comment]
Is it possible to implement clear cache in the admin panel in a modal window in the background? As you consider how much it will be more convenient? Do you plan implementation

**Comment by janniconl** [comment]
Or via AJAX ;-)? Which would result in the same desired result (not leaving a page you're editing)

**Comment by sazanof** [comment]
@janniconl exactly!=)AJAX rules!

**Comment by 64j** [comment]
ребята, вообще то, это всё выполнимо, но главным минусом остаётся фрейм по середине, просто много плагинов и решений других разработчиков которые цепляются за него....
Сделать можно, но отвалятся другие решения!

**Comment by janniconl** [comment]
Vind je het echt handig om op een gesprek waar Engels word gesproken in het Russisch te antwoorden? Zullen we het gewoon Engels houden hier in deze repo?

**Comment by Deesen** [comment]
@64j: I dont understand the exact problem? I added extra-button to mainmenu:

![clearcache1](https://user-images.githubusercontent.com/8569221/28474154-bd0ae4e6-6e47-11e7-909b-bb6ab3fbbb8e.png)

This button uses:

```
modx.openWindow({
	url: 'index.php?a=26',
	title: 'Clear Cache'
})
```

which opens a popup (or Modal if Evo.Modal-plugin is installed?). And I added also a new button to `refresh_site.dynamic.php` so its possible to quickly clear cache again and again:

![clearcache2](https://user-images.githubusercontent.com/8569221/28474197-e1593c08-6e47-11e7-9b4d-4500fc8ec27d.png)

What do you think?

**Comment by Deesen** [comment]
https://github.com/Deesen/evolution/tree/issue-90/

https://github.com/Deesen/evolution/commit/3e585d446485a3bbb19ef061e4e98b8289ef5d81

**Comment by 64j** [comment]
@Deesen 
Great idea and solution.
Can I slightly modify it and make it into the official version of EVO?

mainmenu.php
```php

$sitemenu['refresh_site'] = array(
.......
    array(
        'refresh_site_in_modal' => array(
            'a',
            'btn-success',
            'modx.openWindow({url:\'index.php?a=26\', title:\'Clear Cache\'})',
            $_lang['refresh_site'],
            '<i class="fa fa-recycle"></i>'
        ),
        'optional' => array(
            'span',
            '',
            'alert("Optional")',
            'Optional',
            '<i class="fa fa-recycle"></i>'
        )
    )
```
menu.class.inc.php

```php

.....
                if(isset($this->menu[$id])) {
                    $level++;
                    $ph['DrawSub'] = $this->DrawSub($id, $level);
                    $level--;
                    // Optional buttons
                } else if(isset($value[11]) && !empty($value[11])) {
                    $optionalButton = '';
                    if(is_array($value[11])) {
                        foreach ($value[11] as $opt) {
                            $optionalButton .= sprintf('<%s class="%s" onclick="%s" title="%s">%s</%s>', $opt[0], $opt[1], $opt[2], $opt[3], $opt[4], $opt[0]);
                        }
                    } else {
                        $opt = $value[11];
                        $optionalButton = sprintf('<%s class="%s" onclick="%s" title="%s">%s</%s>', $opt[0], $opt[1], $opt[2], $opt[3], $opt[4], $opt[0]);
                    }
                    $ph['DrawSub'] = $optionalButton;
                }
....
```
 Added optional buttons
![image](https://user-images.githubusercontent.com/4653189/28635628-f578db6c-7243-11e7-8739-843f93f8271d.png)

**Comment by Deesen** [comment]
Yes of course, please go ahead.

**Comment by sazanof** [comment]
Yes, yes, its very useful thing. Great!
@deesen thank you for solution!
Evo so cool!
---
Testing.....
