### ISSUE TITLE
Formlister - Checkbox after validation

### ISSUE THREAD

**Issue by signalfeuer** [evolution-cms/evolution#901]
How can i archive that a checkbox keeps checked after validation of the FormLister form?

**Comment by fourroses666** [comment]
maybe you can script that, if checked keep checked?

**Comment by pmfx** [comment]
Example of checkbox:
```
<input type="checkbox" name="my_checkbox" value="yes">
```
Add parameter to snippet call:
```
&formControls=`my_checkbox`
```

**Comment by pmfx** [comment]
@signalfeuer is your issue fixed?

**Comment by signalfeuer** [comment]
Sadly, no! The &formControls parameter doesn't solved the problem.

**Comment by signalfeuer** [comment]
Here it is:
[tmp.txt](https://github.com/evolution-cms/evolution/files/2638637/tmp.txt)

**Comment by pmfx** [comment]
Looks good.

- Silly question: do you have `<input type="hidden" name="formid" value="ContactForm">` in your tpl?
- Is ``` &config=`default:core` ``` necessary? Maybe it is interfering with parameters? 
- Do you want to remember checkbox after successful validation (and email send), or do you want to remember it after failed validation (and email not send)?

**Comment by signalfeuer** [comment]
· Yes, i have the <input name="formid" type="hidden" value="ContactForm" />
· I removed the "&config" – it was part of an example i found online.
· I just want to remember it after failed validation (and email not send)

**Comment by pmfx** [comment]
You are missing control placeholder.
Replace checkboxes with this:
```
<label for="fs" class="checkradio">
  <input type="checkbox" name="fs" id="fs" class="checkradio" 
  value="Firmenseminar bei uns in Butzbach" 
  [+c.fs.Firmenseminar bei uns in Butzbach+]>
  Firmenseminar bei uns in Butzbach
</label>

<br class="clear" />

<label for="es" class="checkradio">
  <input type="checkbox" name="es" id="es" class="checkradio" 
  value="Einzelseminar bei uns in Butzbach"  
  [+c.es.Einzelseminar bei uns in Butzbach+]>
  Einzelseminar bei uns in Butzbach
</label>

<br />

<label for="ih" class="checkradio">
  <input type="checkbox" name="ih" id="ih" class="checkradio" 
  value="Inhouse-Seminar bei Ihnen vor Ort"  
  [+c.ih.Inhouse-Seminar bei Ihnen vor Ort+]>
  Inhouse-Seminar bei Ihnen vor Ort
</label><br class="clear" />
```

**Comment by signalfeuer** [comment]
Strike. I tried it with the control placeholder before, but was missing the "&formControls" parameter.
Now it works – thanks a lot for your help.

**Comment by pmfx** [comment]
That's great. I will close the issue now.
