### ISSUE TITLE
1.4.6 Saving system configuration corrupts .htaccess

### ISSUE THREAD

**Issue by pbowyer** [evolution-cms/evolution#902]
Every time I save the site's configuration, my `.htaccess` file is modified and the existing `RewriteBase /` line is changed to:
```RewriteBase /http://example.local```
(the site's domain is added)

This makes the syntax incorrect, and breaks the website.

**Comment by pbowyer** [comment]
No, a standard Ubuntu 16.04/Apache/PHP 7.2-fpm setup.

**Comment by dmi3yy** [comment]
Can you get access i check. 
dmi3yy@gmail.com

**Comment by pbowyer** [comment]
I have a Vagrant box defined - can you run Vagrant?
