### ISSUE TITLE
eForm/FormLister: How to define the words for the captcha

### ISSUE THREAD

**Issue by signalfeuer** [evolution-cms/evolution#905]
In older versions of MODX Evolution it was possible to define the words used for the captcha.
Is that still possible somewhere?

**Comment by risingisland** [comment]
In System (cogs icon), Configuration. Under the Security tab at the bottom of the page, you will see an option "Use CAPTCHA codes". 
Marking this as Yes will give you the option to add/edit the words.

**Comment by fourroses666** [comment]
Ana after changing the words you can set it off again if you want to
