### ISSUE TITLE
phpthumb rotate angle (ra) option broken

### ISSUE THREAD

**Issue by MadeInSwitzerland** [evolution-cms/evolution#908]
Calling the phpthumb snippet with the ra (rotate angle) option, e.g. like this "[phpthumb? &input=`assets/images/products/fpga_modules/mercury_ca1/mercury_ca1_front_new_600.jpg` &options=`w=96&ra=-90`]]" now leads to following error - it did work before (but I don't know how long it is already broken):

Trying to get property of non-object
« Evo Parse Error »
ErrorType[num] | WARNING[2]
File | /home/enclustr/public_html/assets/snippets/phpthumb/phpthumb.functions.php
Line | 210
Source | $newwidth  = (abs(sin(deg2rad($angle))) * $height) + (abs(cos(deg2rad($angle))) * $width);
Current Snippet | phpthumb
Current Plugin | PHx(OnParseDocument)

**Comment by Nicola1971** [comment]
I think you are using a wrong separator for phpthumb options.
Instead:
``` &options=`w=96&ra=-90` ```
try
``` &options=`w=96,ra=-90` ```

use comma with option instead &

example:

``` &options=`w=300,h=210,far=C,bg=FFFFFF,ra=-90` ```

**Comment by MadeInSwitzerland** [comment]
No, it still doesn't work. And it used to work with an older version of Evolution CMS. When I try the angles 0 or 180 degrees it is working, with 90 or -90 degrees it doesn't.

**Comment by fourroses666** [comment]
Don't know if that works but you could try;

ar =  set to "l" or "L" for landscape, or "p" or "P" for portrait. "l" and "P" rotate the image clockwise, "L" and "p" rotate the image counter-clockwise.

**Comment by Nicola1971** [comment]
> No, it still doesn't work. 

@MadeInSwitzerland works for me
![screenshot-localhost-2018 11 27-11-18-42](https://user-images.githubusercontent.com/7342798/49075073-5d2a2900-f236-11e8-856a-285f046ef241.png)

**Comment by Nicola1971** [comment]
can't replicate the issue. 

evo version?

**Comment by MadeInSwitzerland** [comment]
Evo 1.4.6, PHP 7.1

**Comment by MadeInSwitzerland** [comment]
I found the problem/solution: apparently in the newest version phpthumb needs also a height/h option to work correctly when rotating an image. That wasn't the case before! When I add the option "h=1000" it is working again:
<img src="[[phpthumb? &input=`assets/images/products/fpga_modules/mercury_ca1/mercury_ca1_front_new_600.jpg` &options=`w=96,h=1000,ra=-90`]]">

Thanks for the help!

**Comment by Nicola1971** [comment]
ok, i think we can close the issue
