### ISSUE TITLE
Redirect after save configuration

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#91]
Возможно ли оставаться на настройках после их сохранения, а не редиректить после него?

**Comment by bossloper** [comment]
.... translating... :-) I agree. After saving settings - assuming you refer to 'system configuration' then it would be more useful to return to that page after saving rather than closing.

**Comment by sazanof** [comment]
Thanks, it'll be great!

**Comment by fourroses666** [comment]
Talking about redirects;

I'm not sure yet. Is this correct behaviour? When you are on the Chunks page, then go to the top navbar and click "+Add new Snippet", then save that snippet you get redirected back to the Chunks page and not Snippets overview page.

**Comment by bossloper** [comment]
@fourroses666 - agreed that is not logical...

**Comment by sazanof** [comment]
I mean system configuration tab, after save it
@fourroses666

**Comment by bossloper** [comment]
@sazanof - I think @fourroses666 was just hijacking the thread ;-)

**Comment by fourroses666** [comment]
Yea I know, I agree on the redirecting to the same page!

Just noticed an other redirect which should be corrected, (maybe is was better to have started a new Issue 🙊)

**Comment by sazanof** [comment]
Oh, now i understood you!

**Comment by Seiger** [comment]
Added to EVO 3.2.x
