### ISSUE TITLE
Проблема с mcpuk после обновления 1.4.5 (в 1.4.6 сохранилась ошибка)

### ISSUE THREAD

**Issue by borkas29** [evolution-cms/evolution#910]
прикрепляю новое фото к странице
![image](https://user-images.githubusercontent.com/45383870/49066117-30bfde00-f231-11e8-90cc-8e41b85222c6.png)
далее, добавляю след фото
![image](https://user-images.githubusercontent.com/45383870/49066149-446b4480-f231-11e8-972c-ef5bd4230725.png)
нажимаю "обновить"
![image](https://user-images.githubusercontent.com/45383870/49066170-53ea8d80-f231-11e8-8767-325fdbbc988b.png)
появляются превьюшки корня
перехожу на любую папку и возвращаюсь на нужную, все становится нормально
![image](https://user-images.githubusercontent.com/45383870/49066218-7a102d80-f231-11e8-8268-87b6e04b5123.png)
p.s. версия от 1.4.4. работает правильно

**Comment by Pathologic** [comment]
Как воспроизвести?

**Comment by borkas29** [comment]
Вроде все расписано =)
Поставил MultiTV и прикрепляю изображения. Далее по инструкции со скринами.

**Comment by dmi3yy** [comment]
Проверил на 1.4.7 все работает корректно и с multitV и с обычных ТВ и кнопка обновить
