### ISSUE TITLE
DocLister + Ditto randomize doesn't work after update to Evo 1.4.6

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#918]
After update from 1.4.5 to Evo 1.4.6 this randomize options doesn't work:
1) [[DocLister? &parents="14" &tpl="prod_template" &orderBy="rand()" &display="3"]]

2) [[Ditto? &parents="14" &tpl="prod_template" &randomize="1" &display="3"]]

**Comment by 64j** [comment]
snippet must be NOT cached

**Comment by modwebpl** [comment]
I add [! !] in snippet and refreshing page doesn't change values. Here is example: http://nowe.sprawdzoneterapie.pl/ <-- on the bottom 3 videos thumbs should be randomize in DocLister.

**Comment by Nicola1971** [comment]
tested with fresh 1.4.6 install

```
[!DocLister? 
&parents=`0`
&tpl=`@CODE:
		<div class="dl_summaryPost">
			[+blog-image+]	
			<h3><a href="[~[+id+]~]" title="[+e.title+]">[+e.title+]</a></h3>
			<div class="dl_info">
				By <strong>[+author+]</strong> on [+date+].
				<a href="[+url+]#commentsAnchor">Comments <span class="badge">[+jotcount+]</span></a>
			</div>
			[+summary+]
			<p class="dl_link">[+link+]</p>
		</div>` 
&orderBy=`rand()` 
&display=`3`!]

```
page cached - snippet uncached : works

Do you have some server side caching system?

**Comment by modwebpl** [comment]
Sorry, problem solved - it's problem witch server side caching :o
