### ISSUE TITLE
Snippet "getField" causes ERROR

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#919]
Hello,
when I try to open a page I get the following Error:

```
Trying to get property 'action' of non-object
« Evo Parse Error »

Error : Use of undefined constant gfGetFieldContent - assumed 'gfGetFieldContent' (this will throw an Error in a future version of PHP)
```

Is there a way to get the snippet run again? What changes are necessary?

EvoCms is on version 1.4.6 and PHP is new on 7.2

Thanks

**Comment by bossloper** [comment]
If this is the 'GetField' snippet you will need to update the line near the start of the snippet from:
`if (!function_exists(gfGetFieldContent))`
to
`if (!function_exists('gfGetFieldContent'))`

**Comment by ArnoNymeier** [comment]
Hi bossloper,
thanks for your fast help :-)
There are two lines to change in the snippet file (getfield.inc.php)
`if (!function_exists(gfGetFieldContent))` and ` if (!function_exists(gfGetParentId))`
Now everything is displayed again as before...
