### ISSUE TITLE
Do we need: /assets/images/noimage.jpg ?

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#92]
Do we need `/assets/images/noimage.jpg` ?

(We already have a noimage for phpthumb.)

**Comment by Pathologic** [comment]
This file is related to something in assets/lib/

**Comment by fourroses666** [comment]
I always delete the image. Do you know where-to its related?

**Comment by Pathologic** [comment]
To \Helpers\Video and can be deleted, probably it's leftover from some project.
