### ISSUE TITLE
Ошибка в mm_ddMultipleFields

### ISSUE THREAD

**Issue by Dreamer0x01** [evolution-cms/evolution#921]
При редактировании страниц, где есть обработка параметров через mm_ddMultipleFields, в конце формы редактирования выводятся вот такие ошибки:

> Parse error: syntax error, unexpected end of file in C:\OSPanel\domains\vremgoda\public_html\assets\plugins\managermanager\widgets\ddmultiplefields\ddmultiplefields.php(76) : eval()'d code on line 1

Решение есть вот в этом комментарии: 
http://modx.im/blog/addons/4265.html#comment44232

Каждый раз при обновлении, соответственно, все слетает и надо менять код плагина повторно.

**Comment by dmi3yy** [comment]
fixed https://github.com/evolution-cms/evolution/commit/92a15c0b633777b3aa6b3da40ed1c70c4e667b75
