### ISSUE TITLE
Баг при обновлении страницы

### ISSUE THREAD

**Issue by Sesqiwake** [evolution-cms/evolution#924]
При обновлении страницы, появляется на секунду меню(на весь экран), которое по дефолту свернуто, я понимаю, что ошибка где-то по коду, но пока еще не разобрался (недавно работаю с ним). Посоветуйте куда смотреть
Видео проблемы - https://youtu.be/2DYU6jMt4pI

**Comment by pmfx** [comment]
How is this related to Evolution? Looks like a issue with custom front-end code.

**Comment by Sesqiwake** [comment]
Я понимаю, что дело не в эво, но решил обратиться и спросить у более понимающих людей, в какую сторону мне смотреть и в чем может быть проблема. Да вопрос слишком обширный и вариантов в каком из скажем файлов может быть проблема, но мало ли совет все таки кто-то даст. Сайт написан не мною, а более опытным программистом,  а я разбираюсь, что к чему

**Comment by 64j** [comment]
@Sesqiwake 
Для этого есть форум.
http://modx.im/

**Comment by Sesqiwake** [comment]
Спасибо за ответы, извиняюсь за офтоп

**Comment by dmi3yy** [comment]
Так же вот тут можно задавать вопросы : 
https://t.me/evolutioncms

**Comment by Evgeny-Mufteev** [comment]
Ну ты и тупой

**Comment by Evgeny-Mufteev** [comment]
мша остюд
