### ISSUE TITLE
Update to 2.0.0 – only new install offered

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#927]
When trying to update existing install from 1.4.7 to 2.0 using the „Update to version 2.0.0-alpha“ button in backend I get only the possibility for a new install, but not to upgrade the existing install.
Intended behaviour? Is there a possibility to actually upgrade an existing install?

**Comment by dmi3yy** [comment]
See this video:

https://t.me/evolutioncmsnews/130

**Comment by dmi3yy** [comment]
https://youtu.be/wP7vDNlxYak
