### ISSUE TITLE
After upgrade Upgrade advice still there

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#928]
After upgrade from 1.4.7 to 2.0.0-alpha the upgrade advice in backend: `System Update
Content management system is outdated. To update contact the site developers. Current version 2.0.0-alpha` is still there also when version information says 2.0.0-alpha.

**Comment by jamilsamara** [comment]
I am deeply concerned about the prompt for users to upgrade to Alpha. We have users who are clicking on the upgrade to 2.0.0-alpha link when they log in and are breaking their sites since there isn't an upgrade option, only perform a clean installation.

**Comment by dmi3yy** [comment]
I fix it soon (2-3 days need)

**Comment by dmi3yy** [comment]
fix this need update plugin Updater  from Extras 
<img width="675" alt="my evolution site- evo cms manager 2018-12-28 14-41-03" src="https://user-images.githubusercontent.com/669491/50515649-a75d2f00-0aae-11e9-9d5c-81eac0ac4d83.png">
