### ISSUE TITLE
1.4.7 – Parser - if (is_readable($file)) { / PHP - system events

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#931]
After updating PHP from 7.2 to 7.3 on my production servers (shared hosting) I get on all installs this error in system events log: `Parser - if (is_readable($file)) { / PHP - system events`.

`Trying to get property 'action' of non-object
« Evo Parse Error »

Error : is_readable(): open_basedir restriction in effect. File(Unknown) is not within the allowed path(s): (/home/webcvmw7d/:/tmp/:/opt/php-5.3/lib/php/:/opt/php-5.4/lib/php/:/opt/php-5.5/lib/php/:/opt/php-5.6/lib/php/:/opt/php-7.0/lib/php/:/opt/php-7.1/lib/php/:/opt/php-7.2/lib/php/:/opt/php-7.3/lib/php/:/dev/urandom)`

```
Error information  

ErrorType[num] | WARNING[2]
File | /manager/includes/document.parser.class.inc.php
Line | 6210
Source | if (is_readable($file)) {


Backtrace

DocumentParser->{closure}() on line
```

Webhoster says 7.3 config is exactly the same as 7.2 config. They have no idea what could be the reason on their side. They assume that Evo is the issue and that it is a PHP 7.3 incompatibility of Evo.

On my local server without open_basedir restriction all installs work without errors. On production servers there are some hundred of this error per day in different installs. Reverting back to PHP 7.2 seems to solve the issue: no more errors.

I watched this problem over some days: With PHP 7.3 multiple errors per hour in all installs, reverted to PHP 7.2 no more issues on any install over more than one day.

**Comment by dmi3yy** [comment]
We think its trouble in 7.3 
wait 7.3.1 and then check for Evo support 7.3.1
