### ISSUE TITLE
Site tree not expandable

### ISSUE THREAD

**Issue by tweezy-au** [evolution-cms/evolution#934]
I've just upgraded from Evo 1.2 to 1.4.7.

At the top level, my site tree has 9 resources, which are all containers for other pages. But only 2 of these 9 have an arrow that lets me expand to see their children.

Clicking the "Expand site tree" icon only expands these two.

Any thoughts on what I can do to fix this?

**Comment by tweezy-au** [comment]
SOLVED: I found a new/repurposed per-page setting labelled "Show child resources" (although its help text says "Log each visitor's visit to this page"??)

Went through all non-expandable containers and set this to ON, and the problem is gone.

**Comment by modxuser** [comment]
See: https://github.com/evolution-cms/evolution/issues/498

**Comment by tweezy-au** [comment]
Ha! Thanks.
