### ISSUE TITLE
Evo 2.0.0 - manager login error.

### ISSUE THREAD

**Issue by PaulYemelyanenko** [evolution-cms/evolution#935]
After updated from 1.4.1 to 2.0.0 when try to login in manager panel getting 'Error' on screen.

Path: /manager/processors/login.processor.php

 (500 Internal Server Error)

**Comment by AgelxNash** [comment]
Need more information.
Version php, error log ...

**Comment by AgelxNash** [comment]
@PaulYemelyanenko try upgrade to 1.4.7 => 2.0

**Comment by dmi3yy** [comment]
Typo error in config
