### ISSUE TITLE
1.4.7 MODResource wrong alias

### ISSUE THREAD

**Issue by sashabeep** [evolution-cms/evolution#937]
Господа, подскажите, это баг, или фича?
Автоматическая генерация псевдонима - выключено.
Суффиксы - выключено.
Разрешить повторяющиеся псевдонимы - включено.
Разрешить вложенные URL - включено.
PHP 7.1.2
Отловил такое:

Тестовый сниппет с modresource:
```php
//include modResource и тд
$doc->create(array(
    'pagetitle' => 'example',
    'template' => 10,
    'parent' => 97,
));
return($doc->save(false, false));
```
Создает документ с алиасом "-9"
![2018-12-26 22 57 02](https://user-images.githubusercontent.com/5689796/50455829-981c9b00-0961-11e9-9f81-aec2b60bfed0.png)

А вот такой вызов:
```php
//include modResource и тд
$doc->create(array(
    'pagetitle' => 'example',
    'template' => 10,
    'parent' => 97
));
return($doc->save(false, false));
```
Создает документ с пустым алиасом, как и должно быть. Разница в одном пустом элементе(?) в массиве. Видимо, из-за этого едет крыша у метода проверки алиаса в modxapi.

Это баг или так и должно быть?

**Comment by AgelxNash** [comment]
Примеры точно корректны?

**Comment by dmi3yy** [comment]
Проверил на 1.4.7 и на 2.0-alpha все работает как надо. 
Проверь работает ли плагин transalias

**Comment by sashabeep** [comment]
@dmi3yy Да работает плагин-то куда он денется, странности только при отключенной автогенерации псевдонима
