### ISSUE TITLE
2 date-TVs in DocLister is this not possible?

### ISSUE THREAD

**Issue by cimt** [evolution-cms/evolution#938]
I have two date-TV in unixtime / startdate and enddate

**DocLister:**
`[!DocLister? 
&id=`event` 
&parents=`21` 
&tpl=`eventtemp`  
&orderBy=`startdate ASC`
&tvList=`startdate,enddate`
!]`

**Chunk:** eventtemp
`<p>from [+tv.startdate:date=`%d.%m.%Y`+] to [+tv.enddate:date=`%d.%m.%Y`+]</p>`

**Result:**
from 01.01.1970 to 01.01.1970
**but should be like that:**
from 06.06.2019 to 10.06.2019

can someone help ... thanks!

**Comment by AgelxNash** [comment]
- Show original values ```startdate``` and ```enddate```
- What is your locale?

**Comment by cimt** [comment]
My solution:

**DocLister:**
`[[DocLister?
&parents=`[*id*]`
&id=`landp`
&tvSortType=`TVDATETIME`
&orderBy=`startdate_date ASC`
&tvList=`startdate_date,enddate_date`
&renderTV=`startdate_date,enddate_date` 
&tpl=`eventtemp`  
&tvPrefix=``
]]`

**Chunk:**
`<p>from [+startdate_date:date=`%d.%m.%Y`+] to [+enddate_date:date=`%d.%m.%Y`+]</p>`

why so? ...no idea, but it works!!

**Comment by dmi3yy** [comment]
Better this question ask here: 
https://github.com/AgelxNash/DocLister/issues
