### ISSUE TITLE
Evo 2.0.0 - Upgrade from 1.4.6 - not possible 

### ISSUE THREAD

**Issue by szakul80** [evolution-cms/evolution#940]
Only - New Installation option is available. Config.inc.php is on place. All paths are correct. Thank You for help.

**Comment by dmi3yy** [comment]
see this video 
https://www.youtube.com/watch?v=xR9filu4A8o

**Comment by szakul80** [comment]
Thank You for quick answer. Front works, but manager still shows - A possible CSRF attempt was detected. No referer was provided by the server. Any advice?
