### ISSUE TITLE
Evo 2.0.0 alpha Update info remains

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#942]
After an upgrade by clicking did not work I did a completely new installation.
All folders and files were deleted, then all Evo 2.0.0 files were reloaded onto the server.
As usual, the link to update to 2.0.0 appears in the manager, although under System Evo 2.0.0. is displayed as the current version.
That's irritating.
Unfortunately, the installation folder is no longer deleted automatically.
How can I remove the update message?

**Comment by ArnoNymeier** [comment]
...manager still shows - A possible CSRF attempt was detected. No referer was provided by the server.
Unfortunately everything does not work as hoped. I go back to 1.4.7 :-(

**Comment by AgelxNash** [comment]
> After an upgrade by clicking did not work I did a completely new installation.
> All folders and files were deleted, then all Evo 2.0.0 files were reloaded onto the server.
> As usual, the link to update to 2.0.0 appears in the manager, although under System Evo 2.0.0. is displayed as the current version.
> That's irritating.
> Unfortunately, the installation folder is no longer deleted automatically.
> How can I remove the update message?

#928

**Comment by AgelxNash** [comment]
> ...manager still shows - A possible CSRF attempt was detected. No referer was provided by the server.
> Unfortunately everything does not work as hoped. I go back to 1.4.7 :-(

#943
