### ISSUE TITLE
[2.0] A possible CSRF attempt was detected

### ISSUE THREAD

**Issue by AgelxNash** [evolution-cms/evolution#943]
Thank You for quick answer. Front works, but manager still shows - A possible CSRF attempt was detected. No referer was provided by the server. Any advice?

_Originally posted by @szakul80 in https://github.com/evolution-cms/evolution/issues/940#issuecomment-450211419_

**Comment by AgelxNash** [comment]
@Nicola1971 You have a similar problem. It's solved?

**Comment by Nicola1971** [comment]
>@Nicola1971 You have a similar problem. It's solved?

No , still have this issue with 2.0 alpha :(  

![screenshot 2018-12-27 21 14 34](https://user-images.githubusercontent.com/7342798/50493243-86e49480-0a1c-11e9-83d9-54dd81f1b9eb.png)


The only way to stop this alert is disable "Validate HTTP REFERER headers "
