### ISSUE TITLE
From Evo 2.0.0 alpha back to Evo 1.4.7 - Fatal Error

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#945]
On the way back (from 2.0.0 alpha) to evo 1.4.7 the following error occurs on the home site in manager:

`Fatal error: Uncaught Error: Class 'DLTemplate' not found in /www/htdocs/wwwxyz/website.de/assets/plugins/extrascheck/CheckOutdated.class.php:37 Stack trace: #0 /www/htdocs/wwwxyz/website.de/assets/plugins/extrascheck/OutdatedExtrasCheck.plugin.php(33): CheckOutdated->__construct(Object(DocumentParser), 'OutdatedExtrasC...', Array) #1 /www/htdocs/wwwxyz/website.de/manager/includes/document.parser.class.inc.php(1916) : eval()'d code(18): require('/www/htdocs/w01...') #2 /www/htdocs/wwwxyz/website.de/manager/includes/document.parser.class.inc.php(1916): eval() #3 /www/htdocs/wwwxyz/website.de/manager/includes/document.parser.class.inc.php(5510): DocumentParser->evalPlugin('/**\n * Outdated...', Array) #4 /www/htdocs/wwwxyz/website.de/manager/actions/welcome.static.php(401): DocumentParser->invokeEvent('OnManagerWelcom...', Array) #5 /www/htdocs/wwwxyz/website.de/manager/index.php(296): include_once('/www/htdocs/w01...') #6 {main} thrown in /www/htdocs/wwwxyz/website.de/assets/plugins/extrascheck/CheckOutdated.class.php on line 37`

The manager folder of evo 2.0.0 has been replaced by the one of 1.4.7.
The saved config.inc.php has been reloaded into the folder includes.
The files in the root folder have also been replaced by the version 1.4.7 files.
The folder extrascheck in plugins has also been added from the version package 1.4.7.

Is there a folder or a file that still needs to be changed?

PHP Version is 7.2.11

**Comment by AgelxNash** [comment]
replace https://github.com/evolution-cms/evolution/tree/1.4.x/assets/snippets/DocLister

**Comment by ArnoNymeier** [comment]
DocLister was present - I replaced the folder. Now the error is no longer displayed.
Thanks for the fast information.
