### ISSUE TITLE
UI, update widget bug

### ISSUE THREAD

**Issue by yorique** [evolution-cms/evolution#946]
Update widget is invisible (since 1.4 i guess, and still broken).

![clip1](https://user-images.githubusercontent.com/1080696/50512421-796def80-0a9a-11e9-93f5-32952e876700.jpg)

And appear if left panel closed.

![clip2](https://user-images.githubusercontent.com/1080696/50512436-8854a200-0a9a-11e9-9427-ab80f0a7bd65.jpg)

**Comment by fourroses666** [comment]
Yes I noticed that too on certain viewsizes.
Its because of the bootstrap style: `float:left` for class `.col-sm-12`

**Comment by fourroses666** [comment]
Fix would be: `<div id="updater" class="col-lg-12">`

**Comment by 64j** [comment]
https://github.com/evolution-cms/evolution/commit/09a17870a48a11d3dfb69087c3aa6e3efa5e5a0b

**Comment by 64j** [comment]
#923
