### ISSUE TITLE
Wishes - evolution 2.0

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#950]
The most important thing I would love to see is a way to create a beautiful paginate url's like:

www.example.com/category/2 <-- it will be page 2 etc.

**Comment by dmi3yy** [comment]
Its need write here: 
https://github.com/AgelxNash/DocLister/issues

its task not for core)

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/DocLister/issues/339
Custom route with the onPageNotFound event.
