### ISSUE TITLE
Updater messages on Dashboard

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#955]
In the manager the Updater message is: 
Update to new version_compare 2.0.0-alpha.

I would like to see 1.4.7 there. Can that be seperated for 1.x and 2.x versions?
Another possibility is to have two buttons: Upgrade to 1.4.7 or 2.0 alpha?
The button should be Green and also very important: default Only visible for Admin! 

Maybe also be able to clear RSS with a button? The updater button sometimes isn't there.

**Comment by dmi3yy** [comment]
Yes, we already fix it 
Need update Updater plugin from extras

**Comment by fourroses666** [comment]
_* When clearing /cache/RSS and /cache/updater/ it does show 1.4.7 again._

**Comment by dmi3yy** [comment]
I fix now Updater exist in Extras 

And updater have setting:
<img width="341" alt="updater" src="https://user-images.githubusercontent.com/669491/50687206-ff54e200-1028-11e9-8f79-9cc38584994b.png">

**Comment by fourroses666** [comment]
Show widget for: Admin Only default :(

**Comment by fourroses666** [comment]
Ah yes, thats better, update Button not visible for Editors (admin only)!
