### ISSUE TITLE
Uncaught ReferenceError: evo is not defined at main.js:2

### ISSUE THREAD

**Issue by Ekks-O** [evolution-cms/evolution#958]
Hello all,

I have the title message in the console as soon as I load the manager.

I just updated from 1.2.1 to 1.4.7, never had any issue with any other website I updated.

It seems like the "evo" variable is not defined. Any idea on how to correct this ?

**Comment by Ekks-O** [comment]
![cap1](https://user-images.githubusercontent.com/19590890/50825203-be1a4600-1338-11e9-8ecb-82487fad7bf4.jpg)
![cap3](https://user-images.githubusercontent.com/19590890/50825202-bd81af80-1338-11e9-81c1-483c4cec997a.jpg)

**Comment by dmi3yy** [comment]
Plz screen of plugin list 

test in fresh 1.4.7 all ok

**Comment by Ekks-O** [comment]
![cap4](https://user-images.githubusercontent.com/19590890/50825406-3aad2480-1339-11e9-88b3-c10fb4bfd566.jpg)

**Comment by Ekks-O** [comment]
Same screenshot with purged outdated plugins

![fireshot capture 123 - mustradem- evo cms manager - https___www mustradem com_manager_ _a 76 tab 4](https://user-images.githubusercontent.com/19590890/50825630-c921a600-1339-11e9-9ea9-7ee358a15286.png)

**Comment by dmi3yy** [comment]
all ok strange

**Comment by 64j** [comment]
@Ekks-O 
Refresh cache
Ctrl+F5 or Ctrl+Shift+R

Resave configuration

**Comment by Ekks-O** [comment]
Well, found a solution, I turned all pulgins off and everything worked fine.

Then I reactivated everything one by one. The problem seems to be with the Subscribe plugin.

I'll keep it off, I don't think I ever use it.
