### ISSUE TITLE
Evo 1.4.7 PHP 7.1 and above

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#959]
Hi All,

I know I've written about this before regarding a site not working on PHP 7.1 up to 7.2.  I thought I would revisit upgrading our PHP version on our internal sever.

Evo: 1.4.7
Current PHP: 7.0.33
Upgrading to PHP: 7.2.9
MariaDB: 5.5.5-10.1.19-MariaDB

The problem occurs when I try to log in.  I've described the issue here: https://github.com/evolution-cms/evolution/issues/807#issuecomment-423142468 and this issue still persists.

I would prefer to use WebLoginPE as I have some special features I prefer but I'm unable to get to the completely log in as before.  This appears to relate to PHP rather than the website.

Can anyone offer any help?

Thank you.
BBloke

**Comment by dmi3yy** [comment]
Eform not in core and need write and fix in eform repository:
https://github.com/extras-evolution/eForm

The same for another extras: 
https://github.com/extras-evolution/


for example WebLoginPE here: https://github.com/extras-evolution/WebloginPE

**Comment by BBloke** [comment]
Here's a little more info.

I'm using Chrome and when I check the cookies after signing in the expiration date on the evo random cookie shows expiration as 1969.

Whereas my normal Evo installation on php 7.0.30 has the expiration set at 7 days in the future.

Quite strange is my installation of Evo 1.4.8 on PHP 7.1.25 also has the cookie date in the past.

Is this why the program just doesn't think any page is accessible because it logs the user out due to cookie expiration?

My Evo 1.4.8 on PHP 7.1.25 is currently set up using FormLister as per the basic installation.

**Comment by BBloke** [comment]
Actual expiration date: 1969-12-31T23:59:59

**Comment by BBloke** [comment]
I don't think it has anything to do with the cookie date.

**Comment by BBloke** [comment]
Further testing shows I cannot get a successful result using any login method, WebLoginPE, WebLogin or FormLister.

Modx v1.4.8 (update 10/1/19)
PHP 7.1.25
DB: MariaDB 10.1

**Using my own template:**

**Signing in with WebLoginPE:**

Logging in produces an error which relates to $docgrp = implode(",", $docgrp); in the documentparser.
Changing all the occurences to $docgrp = implode(",", (array)$docgrp); allows WebLoginPE to process accordingly but some aspects of the site are incorrectly rendered.

1. TopMenu. Generated by DLMenu does not show restricted pages
2. SideMenu. Generated by DLMenu does show restricted pages
3. Home page contect Generated by DocLister does not show restricted pages
4. PHx webgroup assessments perform and show relevant information.

No pages, either restricted or unrestricted can be accessed.  Any URL click always takes you to the home page.  Any URL typed also takes you to the home page.

**Signing in with WebLogin:**

- any changes implemented with WebLoginPE have been reverted.

1. TopMenu. Generated by DLMenu does show restricted pages
2. SideMenu. Generated by DLMenu does show restricted pages
3. Home page contect Generated by DocLister does show restricted pages
4. PHx webgroup assessments perform and show relevant information.

The web page renders how it does in PHP7.0.33

Clicking on any URL takes you to the home page and shows you as logged out.

** Signing in with FormLister **
Results in an error of too many cookie redirects

This is with userHelper disabled and enabled.

I hope this is helpful in someway.  I have tried a standard evo 2 installation and I've been unsuccessful in getting web users and restricted pages to work.  This has been on PHP 7.1.25.  Has anyone had any success on PHP 7.1, 7.2 or 7.3?

Sorry if I'm labouring on this.  Whilst most of what I've done in Evolution is internal it's the biggest part of our website and restricted pages is a must.

**Comment by BBloke** [comment]
Has anyone had Evo 1.4.8 with php 7.1+ working with logins?

**Comment by dmi3yy** [comment]
WEbLogin and WebLoginPE not tested, Formlister work perfect

**Comment by BBloke** [comment]
Hi dmi3yy, I'm cannot get it to work with FormLister from a default installation.  There must be something in our configuration that is preventing it.  Would you have any ideas?  This is kinda killing me as I know PHP is going to need to be updated and that will kill our site!

**Comment by dmi3yy** [comment]
If you can do  clone of your site in dev server  setup php 7.2 and send me access (dmi3yy@gmail.com) i help

**Comment by BBloke** [comment]
Thank you. That is a great offer. I will set it up and let you know. Need to change it to 7.2 which I'll also test first. 

Do you need web access to the installation or remote access to the server?

**Comment by BBloke** [comment]
@dmi3yy 

I have set up a clone using 7.2.  I also had a light bulb moment.  I have always placed my login in a side column of my template.  This is what has caused an issue with FormLister and an error after logging in with a continuous redirect.

I have removed the login section and put it on a separate page and the site is working.

Thank you so much for your exceptionally kind offer of help.  It has been enough for me to really give it some thought and figure it out.

BBloke

**Comment by charismeki** [comment]
WebloginPE throughs exception on PHP7.3 within Evo14.1.10 : 
Source $docgrp = implode(",", $docgrp); 
File: /manager/includes/document.parser.class.inc.php

In Evo14.1.9 WebloginPE does work.

Changing core files of document.parser, wayfinder to $docgrp = implode(",", (array)$docgrp); as suggested above login does work aslo again. Any suggestion for a better solution then changing core files?

c--

**Comment by jubbbird** [comment]
I think I've found the proper fix. The root cause of the problem is the improperly initialised $documentGroups in the file "snippets/webloginpe/webloginpe.class.php". It is originally initialised as an empty string, but I think PHP 7.3 needs arrays to be properly initialised using "array()" or similar, as below:

Line 2125: $documentGroups = '';

needs to be:

$documentGroups = array();
