### ISSUE TITLE
Файл-менеджер и файл-браузер

### ISSUE THREAD

**Issue by makedonets** [evolution-cms/evolution#96]
Не появляются эти разделы в меню Конфигурации

**Comment by dmi3yy** [comment]
Отключите плагин тинимсе это он мешает

Отправлено с iPhone

**Comment by makedonets** [comment]
Спасибо, а без него не грузятся ресурсы. Не показвается содержимое и т.д. а просто белая страница

**Comment by dmi3yy** [comment]
Так зайдите в настройки там сохраните и все ок будет и гляньте какая ошибка в консоле браузера

**Comment by makedonets** [comment]
> 
Так зайдите в настройки там сохраните и все ок будет и гляньте какая ошибка в консоле браузера
> 
Давайте по пунктам
1.Убрать плагин tinymce
2. Зайти в конфигурацию и кликнуть сохранить
3. Обновить страницу (вкладки не появляются)
4.Выйти на главную и обновить котрольную сумму
5.Зайти в конфигурацию и снова обновить страницу(вкладки не появляются)
Это то что я сделал

**Comment by dmi3yy** [comment]
Вкладки не появляются в том случае если ошибка с плагином каким то зачастую тинимсе



Отправлено с iPhone

**Comment by makedonets** [comment]
Спасибо большое, ошибка была из за CKEditor

**Comment by toha-proud** [comment]
Не забываем закрывать Issues если вопрос решен
