### ISSUE TITLE
EVO 2.0 - Manager Resource template setup

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#961]
Will this be possible in 2.0? Choose a template for back-end Resource pages;
Or have a plugin where you can choose the different templates.
What really would be cool if we can use somekind of PageBuilder for these templates.
It shows all fields (TVs) and you can drop them in a pre-defined section.

https://github.com/modxcms/evolution/issues/672
https://github.com/modxcms/evolution/issues/764

**Comment by AgelxNash** [comment]
After writing a controller ([like this](https://github.com/evolution-cms/evolution/blob/2.0.x/core/src/Controllers/Snippet.php)) to replace the [old mix html+php](https://github.com/evolution-cms/evolution/blob/2.0.x/manager/actions/mutate_content.dynamic.php)
you can replace [view](https://github.com/evolution-cms/evolution/blob/2.0.x/manager/views/page/snippet.blade.php) via plugin.
