### ISSUE TITLE
2.0 configuration menu

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#964]
Hi All,

On the configuration menu Interface & Features now reads `Interface &amp; Features.`

**Comment by AgelxNash** [comment]
We have 2 way
* replace [Interface &amp; Features](https://github.com/evolution-cms/evolution/blob/2.0.x/manager/includes/lang/english.inc.php#L969) to `Interface & Features`
* replace [{{ ManagerTheme::getLexicon('settings_ui') }}](https://github.com/evolution-cms/evolution/blob/2.0.x/manager/views/page/system_settings/interface.blade.php#L3) to `{!! ManagerTheme::getLexicon('settings_ui') !!}`
