### ISSUE TITLE
New free theme kick-off

### ISSUE THREAD

**Issue by fourroses666** [evolution-cms/evolution#970]
I think it will be very good to have a new free demo template.
And even remove the Demo template from the installer and add it to Extras.

If evo.im is finished we can build the Demo a bit based on the Evo.im style.
Probably build on Bootstrap (which I hate, I build custom). 
Maybe we can do another contest like we did on the logo?

Its a kick-off for new payed and free themes.

EVO is very easy to build in. New EVO starter-users can build websites for their clients or personal use. Our community will grow.

**Comment by dmi3yy** [comment]
We start generate new light theme on Bulma.io 
after finish html i put to gitHub 

after that start video tutorials integrate this template on EVO 
and after that we will have new demo site + video tutorial 

bulma.io  light and new framework and good point for get people from their site )

**Comment by pmfx** [comment]
I would go for Bootstrap 4. But if it just for demo, CSS framework is not that important, I guess. In the end we can use any framework or custom CSS for our EVO templates and themes.

**Comment by dmi3yy** [comment]
We can add evo here: 
- https://bulma.io/extensions/
- https://bulma.io/expo/

and have new trafic to evo.im and EVO ). 

this is why i want build on Bulma )

**Comment by dmi3yy** [comment]
we can do 2-3 -10 demosite not see problem but need start with 1 )

**Comment by fourroses666** [comment]
Hi @Dmi3yy Is this still on the radar?

**Comment by Dmi3yy** [comment]
After release 3.0 i start new lessons will do new demo site
