### ISSUE TITLE
Add preview to Image TV

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#98]
It's appended by ManagerManager now.

**Comment by Deesen** [comment]
Generally some kind of flexible image-management would be awesome.. maybe with the possibility to add additional "IVs" (Image-Variables like Text-TVs, to be able to add additional attributes per image like `data-caption="xxx"`).

But native image-preview already sounds great, maybe we can display additional infos about the image like upload-date, dimensions, lightbox for fullsize view etc.

**Comment by dmi3yy** [comment]
All this simple do with multitv type single

Отправлено с iPhone

**Comment by Deesen** [comment]
I was thinking of an SQL-Table with all existing images, createdon-date, maybe images-categories, usage-statistic, alt/title-editing (and if required even more TVs) etc.. This would enable more professional SEO-management of images, images-cache, thumbs, image-sizes, whatever..

This idea was already mentioned several times at https://github.com/modxcms/evolution/issues

**Comment by fourroses666** [comment]
Would love that

**Comment by Dmi3yy** [comment]
for basic field use TemplateEdit3 or ManagerManager  all another solution have own previews for images
