### ISSUE TITLE
Правка в Тини 4

### ISSUE THREAD

**Issue by F1fanatik** [evolution-cms/evolution#980]
Просьба, добавить в исходник редактора ТиниМсе 4 проверку правописания русского языка, 
другие языки есть, а русского нет [http://images.vfl.ru/ii/1548070380/37f1c2cb/25044584.jpg](url)

**Comment by ProjectSoft-STUDIONIONS** [comment]
Создать свой конфигурационный файл на основе используемой конфигурации. 
В файл добавить ещё две строчки
```
// Подробнее о опциях плагина spellchecker https://www.tiny.cloud/docs/plugins/spellchecker/
$this->set('spellchecker_languages', 'Русский=ru,Украинский=uk,Английский=en');
$this->set('spellchecker_rpc_url', 'http://speller.yandex.net/services/tinyspell');
```
Выбрать конфигурацию в настройках TinyMCE сайта.
Пользуйтесь
