### ISSUE TITLE
1.4.8 System events: A bunch of "Evo parse error"

### ISSUE THREAD

**Issue by qlworx** [evolution-cms/evolution#984]
Since I updated some projects to Evo 1.4.8 I struggle with a bunch of annoying Evo system events here:

> Error : Directive 'register_globals' is no longer available in PHP

See attached pdf. I can't find the reason for these behavior. Backend and Frontend both working fine.  All Snippets are updated with Extras Module, I have no other snippets or moduls in use. 

Hoster is WebHostOne in Germany.

Can somebody help and point me in the right direction?

[evo parse error.pdf](https://github.com/evolution-cms/evolution/files/2796226/evo.parse.error.pdf)

**Comment by dmi3yy** [comment]
What php version?

**Comment by qlworx** [comment]
They offer 7.0.33, 7.1.25, 7.2.13 and 7.3.0. 

Regarding the error messages it doesn't matter, which I use.

**Comment by bossloper** [comment]
Maybe you have an old register_globals directive in an .htaccess file?

**Comment by qlworx** [comment]
It doesn't work, as expected.

**Comment by fourroses666** [comment]
maybe php.ini in root

**Comment by Deesen** [comment]
Also I would make a DB-dump, and search all files on your server (incl. "assets/backups" / dump) for the string "register_globals", to find out if there is a `ini_set ( 'register_globals' , 'On' )` or whatever in some old code.

**Comment by qlworx** [comment]
Thank you, @Deesen. But no result at all. We use nothing than pure Evo and some of the older standard snippets (e.g. wayfinder, ditto), which have been updated after 1.4.8 install.

And as I stated, everything works fine, besides these annoying system events. Very strange. I will ask for providers support as a next step.

**Comment by qlworx** [comment]
Result: Some outdated entries in root php.ini (shared hosting, out of my reach) were causing this behavior. @fourroses666 were right. Thank you all, evo folks 👍
