### ISSUE TITLE
Issue with pub_date format

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#985]
Hello,

This [+pub_date:date=`%d.%m.%Y`+] doesn't work in Evo 1.4.8

**Comment by 64j** [comment]
@modwebpl 
everything is working
```
[[DocLister?
&parents=`0`
&tpl=`@CODE:<a href="[+url+]"> [+date+] </a>`
]]
```

**Comment by 64j** [comment]
@modwebpl 

replace to
```[+publishedon:date=`%d.%m.%Y`+] ```

**Comment by modwebpl** [comment]
Well its my mistake, i figured it out - I need to turn on "filters".
