### ISSUE TITLE
doclister using a tpl which calls a snippet that has the rand()  function in it. the rand() is not being called multiple, separate times.

### ISSUE THREAD

**Issue by user83743** [evolution-cms/evolution#986]
Hi

any help on this would be much appreciated. 

doclister using a tpl which calls a snippet that has the rand()  function in it. the rand() is not being called multiple, separate times.

#############################

we have tried a few "stop the caching" measures and a few different php random number generator php code pieces but we cannot get 5 unique images to be display here. any help would be much appreciated:

the doclister calls is:

 [!DocLister?  &amp;id=`arch`  &amp;parents=`10`   &amp;offset=`0`   						&amp;orderBy=`menuindex DESC, createdon DESC`   &amp;tpl=`getbottomblogentry`     
 &amp;display=`5`  &amp;paginate = `1`  &amp;paginateAlwaysShowLinks=`1`  &amp;tvList=`` !]
							
							
							
	
the  getbottomblogentry  tpl is:

<div class="blog-holder">
                                <div class="blog-holder-inner">
                                    <div class="blog-image-block">
                                        <div class="blog-image">
						  <a href="[~[+id+]~]"><img src="[!getrandomimage1!]"
                                                          alt="MYIT - [+pagetitle+]"></a>
                                        </div>
                                    </div>
                                    <div class="blog-content-block">
                                        <div class="title-block">
                                            <h4><a href="[~[+id+]~]">[+pagetitle+]</a></h4>
                                        </div>
                                        <div class="data-block">
                                            <p>[+introtext+]...</p>
                                        </div>
                                        <div class="action-block">
                                            <a href="[~[+id+]~]" class="more-button">Read More</a>
                                        </div>
                                    </div>
                                </div>
</div>					

and the [!getrandomimage1!] snippet is:

<?php
function make_seed()
{
  list($usec, $sec) = explode(' ', microtime());
  return $sec + $usec * 1000000;
}
//srand(make_seed());
//$randval = rand(1,12);
//$randomphotoname = "graphic".rand(1, 11);
$randomphotoname2 = "graphic".mt_rand(1, 11);
//$randomphotoname = "graphic".$randval;
return "assets/images/".$randomphotoname2.".jpg";	

###################

it is functioning in that it returns a random image each time but we're displaying 5 doclister articles on each page and each image is the exact same instead of it being a random number selected image filename.

any ideas how i could get it to generate a random number selected image filename on each of the 5 articles on each page? we just want 5 images to be different. then on the next page 5 more random images will be selected.

**Comment by Pathologic** [comment]
Install master version of DocLister from extras, then add &parseDocumentSource=\`0\` to snippet call.

**Comment by user83743** [comment]
thnaks P. what is the "master version" of doclister?

**Comment by user83743** [comment]
in    http://domain.com/myit2.ie/manager/#?a=112&id=2   there is just one doclister

**Comment by user83743** [comment]
i see a master version in the version number dropdown. what is the "master" version? will it break the other snippets where we use doclister?  is the master-doclister  just the doclister with the same core but some additional features and parameters?

**Comment by user83743** [comment]
is "master" a version number between 2.4.0  to 2.3.17?  so i could just install the latest version of doclister which is  2.4.1 ?    i am using 2.3.14 now

**Comment by user83743** [comment]
is there a doclister equivalent of the Ditto   [+currentPage+]     ?

**Comment by fourroses666** [comment]
https://github.com/Nicola1971/Ditto-to-DocLister-Reference-Tables
https://github.com/Nicola1971/Doclister-Tags-in-Ditto-Style/blob/master/README.md

**Comment by user83743** [comment]
thanks four*

but that   [+current+]   in the example on https://github.com/Nicola1971/Doclister-Tags-in-Ditto-Style/blob/master/README.md does not work at all.  [+currentt+] returns no "current page number" :

================================
[[DocLister? 
	&jotcount=`1`
	&parents=`2` 
	&display=`2`
	&tvPrefix=``
	&tvList=`image,documentTags`
	&prepare=`prepareBlog`
	&summary=`notags,len:350` 
	&paginate=`offset` 
	&extender=`user` 
	&usertype=`mgr` 
	&userFields=`createdby,publishedby` 
	&tpl=`blogTPL` 
]]

<p>Showing <strong>[+current+]</strong> of <strong>[+totalPages+]</strong> Pages</p>
[+pages+]
===================================

**Comment by fourroses666** [comment]
I really dunno.
Did you add `&parseDocumentSource=0`

**Comment by user83743** [comment]
thnaks. i did the [! !] and  pathologic above suggested the    &parseDocumentSource=`0`   so we tried that too.  i don't think it works and we've spent too much time on it now.  i also notice that  simple:   "@EVAL  return   "dffsdfsdfsd";          don't work in the Default Value in template variables either.    have you used those in EVO lately?

**Comment by Pathologic** [comment]
Call your snippet as 
```
[!getrandomimage1? &id=`[+id+]`!]
```
It should work. As for pagination, it should be:
```
 Showing [+arch.current+] of [+arch.totalPages+] Pages
[+arch.pages+] 
```

**Comment by user83743** [comment]
thanks Path*

the [!getrandomimage1? &id=`[+id+]`!]  didn't work but the [+arch.current+]  did so we are able to hack a random function by using   [+arch.current+] and [+iteration+] side by side e.g.    [+arch.current+][+iteration+] use that to generate "random" type image appearances. thanks
