### ISSUE TITLE
Evo1.4.8 php 7.2.9 inconsistent login situation

### ISSUE THREAD

**Issue by BBloke** [evolution-cms/evolution#990]
Hi All,

I know you know I've had troubles with logins and php versions.  I'm back again.  Apologies in advance if this post doesn't read too well.

My current development server has Evo 1.4.8 with php 7.2.9 and Apache 2.4  with MariaDB 10.1 on windows. Main web browser Chrome.

I'm testing moving onto using FormLister for user logins.

I found an issue with FormLister sitting in my side bar which left it on a permanent redirection loop.  So my FormLister code sits in a standard document as does my profile and forgotten password code.

I'm finding that I have to sign in twice in order for the login "remember me" to stick but find I can be kicked out after navigating a handful of pages.

Whilst I mainly use chrome and firefox most of our users tend to use IE 11 and Edge.  I'm also seeing inconsistent user experiences across those three browers.

Maybe I'm doing too much which has raised one question regarding the whole process.  

Does Evo prefer to be run from one browser?  If I sign in with a different browser it knows to kill the session on the other browser forcing a re-login situation?

For instance, I login using chrome.  Use it for 30 minutes.  Everything is OK.
I decided to use MS Edge and use it for 30 minutes.  Everything is OK.
I return to Chrome and it asks me to sign back in because I used another browser in between?

It's another one of those things that is driving me nuts. Hope you are not sick of seeing my posts? yet?

BBloke

**Comment by BBloke** [comment]
Dug a little and found once the cookies are cleared I don't get a WebLoginPE cookie upon successful login.  Therefore when the browser closes I have to log back in again.

I've taken the code from the example and cannot see if there is anything wrong with the "rememberme" checkbox option.  It would appear it is not being remember!

**Comment by bossloper** [comment]
see here: https://github.com/evolution-cms/evolution/issues/755

**Comment by BBloke** [comment]
Thank you @bossloper I will have a read of that shortly.

**Comment by Pathologic** [comment]
> I return to Chrome and it asks me to sign back in because I used another browser in between?

Yes, because when you had created a new session in another browser, your autologin cookie in chrome became invalid.
