### ISSUE TITLE
При создании копии tv - Evo Parse Error

### ISSUE THREAD

**Issue by mmmborman** [evolution-cms/evolution#993]
Всем привет

Появляется ошибка Error : array_key_exists() expects parameter 2 to be array, null given

/core/vendor/illuminate/support/Arr.php
Line | 151
Source | return array_key_exists($key, $array);

Как воспроизвести:

1. Создаю новый тв config-1, ставлю ему шаблон и категорию. Сохраняю
2. После нажимаю сделать Копию и появляется ошибка. При этом тв создается, но без шаблона  config-1 Копия

Скрин http://i.piccy.info/i9/c4241d65185803cd9742144dffa816df/1549261051/52802/1299416/2019_02_04_08_10_BestDoc_800.jpg или https://s8.hostingkartinok.com/uploads/images/2019/02/46ba0f50c1b3826b817e8118e06ea638.jpg

**Comment by Dmi3yy** [comment]
fixed
