### ISSUE TITLE
Apache 2.4 - order, allow,deny deprecated

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#995]
https://httpd.apache.org/docs/trunk/upgrading.html

```
2.2 configuration:
Order deny,allow
Deny from all
2.4 configuration:
Require all denied
```

**Comment by AgelxNash** [comment]
**Solution 1** (_required mod_version_): https://stackoverflow.com/a/20135157/2323306
```
<IfVersion >= 2.4>
Require all denied
</IfVersion>
<IfVersion < 2.4>
Order deny,allow
Deny from all
</IfVersion>
```

**Solution 2** (_doesn't work with *win installations_): https://stackoverflow.com/a/15081790/2323306
```
# Apache 2.2
<IfModule !mod_authz_core.c>
Order deny,allow
Deny from all
</IfModule>
# Apache 2.4
<IfModule mod_authz_core.c>
Require all denied
</IfModule>
```
Which option we should use? [htmlpurifier](https://github.com/ezyang/htmlpurifier/pull/190) used second solution
