### ISSUE TITLE
Creat New page - bug!

### ISSUE THREAD

**Issue by jorjik** [evolution-cms/evolution#997]
**ver** - Evo 1.4.2 / PHP-7.2 , MySQL-5.7  
**error**: Execution of a query to the database failed - Expression #1 of ORDER BY clause is not in SELECT list, references column 'beg.sc.menuindex' which is not in SELECT list; this is incompatible with DISTINCT
**screen**: http://SSMaker.ru/549683f5/ plugins http://SSMaker.ru/2ae1caf6/

**Comment by AgelxNash** [comment]
Please! Up to version 1.4.8 and confirm the problem

**Comment by jorjik** [comment]
Нашел апдейт. Стало Ок. Вопрос: а почему на Modx.Com.Ua - не новая версия?

вс, 17 февр. 2019 г., 1:54 Евгений Борисов notifications@github.com:

**Comment by dmi3yy** [comment]
Потому что уже давно evolution cms 

И логично смотреть тут evo.im 

На старых ресурсах переодически обновляю версии но не всегда, темболее если даже обновить на оо что на модх.ком.уа он после предложит уже в админке обновить дальше
