### ISSUE TITLE
Help: phpThumb inside of multiTV call

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#999]
How does one get a phpThumb call inside of a multiTV?
I am trying to add the following to a template:
> [!multiTV? &tvName=`products` 
> &display=`3` &randomize=`1`  &docid=`27`
> &outerTpl=`@CODE:<ul>((wrapper))</ul>` 
> &rowTpl=`@CODE:<h4>((title))</h4><img src="[[phpthumb? &input=`((image))` &options=`w=300,h=214,zc=TL`]]" />`!]

**Comment by pmfx** [comment]
Maybe try moving template code to a chunk?

**Comment by fourroses666** [comment]
Use a tpl chunk and not @CODE:

Verstuurd vanaf mijn iPhone

**Comment by risingisland** [comment]
Sorry, still can not seem to get this to work.
Would either of you mind providing an example?

**Comment by fourroses666** [comment]
```&rowTpl=`productTpl` ```

Chunk productTpl

```<h4>[+title+]</h4><img src="[[phpthumb? &input=`[+image+]` &options=`w=300,h=214,zc=TL`]]" />```

**Comment by risingisland** [comment]
OK, perfect. 
With a little fumbling, I got it to work now.

Thank you both for the assist!
